### ISSUE TITLE
'keep_md: true' halts execution when rendering pdf document

### ISSUE THREAD

**Issue by broomej** [rstudio/rmarkdown#1001]
Trying to retain the intermediate .md files when rendering a .pdf document gives the following error message:
```
Error in (function (toc = FALSE, toc_depth = 2, number_sections = FALSE,  : 
  unused argument (keep_md = TRUE)
Calls: <Anonymous> -> create_output_format -> do.call -> <Anonymous>
Execution halted
```

Below is a minimal example that was able to reproduce the issue

````
---
output:
    pdf_document:
        keep_md: true
---

Document text

```{r}
print("execute some R code")
```
````

Either removing `keep_md: true` _or_ changing the output to `html_document` will fix the problem.

I tested this on macOS 10.12.3 and CentOS release 6.8, both R version 3.3.2 and rmarkdown version 1.3

**Comment by jjallaire** [comment]
Yes, that's not currently supported because it will give surprising results (images in pdf_document are PDFs not PNGs so the web page viewed by keep_md would have images that don't work). Might be better to just render to multiple formats if you need support for both PDF and markdown output.

**Comment by jjallaire** [comment]
Note that if it's just for debugging you can render with `clean = FALSE` to keep all intermediate files.

**Comment by fordc5** [comment]
Any update on if this is now supported? I believe not b/c still seeing similar behavior.

**Comment by yihui** [comment]
@fordc5 No, `render()` with `clean = FALSE` is the way to go if you really have to keep the intermediate .md file.

**Comment by yihui** [comment]
On second thought, instead of blocking users from using `keep_md` for `pdf_document`, I think it is more appropriate to let them use it with caution. This does not necessarily lead to bad consequences, e.g., to solve the image problem, users can choose to use the `dev: "png"` for `pdf_document`, which works for both PDF and previewing `.md` in HTML.
