### ISSUE TITLE
Output missing from notebook HTML, but not regular HTML

### ISSUE THREAD

**Issue by Deleetdk** [rstudio/rmarkdown#1002]
_yihui told me to post it here [after initially reporting it at **Knitr**](https://github.com/yihui/knitr/issues/1381)._

It seems that this is a bug related to using the chunk param `code` to input code. See [this Stackoverflow question](http://stackoverflow.com/questions/40519904/modularized-r-markdown-structure) (also me). 

I attach a minimal example, which has 4 files:

1. knitr_bug.Rmd
2. knitr_bug.R
3. knitr_bug.html
4. knitr_bug.nb.html

The first file is an R notebook style Rmd. It calls a single code chunk with the `code` param that calls the .R file. The .R file has a simple ggplot2 to plot some iris data. Then one simply clicks Knit. The two outputs look like this, side by side:

![knitr_bug](https://cloud.githubusercontent.com/assets/6759913/24136711/50c2c7a0-0e10-11e7-97b7-b96e3a00f176.png)

As can be seen, the regular HTML file has the output, but the Notebook version does not. Both have the R code itself.

[knitr_bug.zip](https://github.com/rstudio/rmarkdown/files/857338/knitr_bug.zip)

**Comment by jjallaire** [comment]
@jmcphers Could you take a look at this?

**Comment by jmcphers** [comment]
The `code= ...` chunk option does not currently work in notebooks. However, as of our latest release (1.0.136), Notebooks do support this workflow, using the `read_chunk` method from knitr. 

There's one additional requirement in notebook mode: you must call `read_chunk` in the setup chunk; since you can run notebook chunks in any order, this ensures that the external code will always be available. 

I'll post a more detailed response on StackOverflow as it's probably where others with this question will wind up. Appreciate the detailed report!

**Comment by Deleetdk** [comment]
I saw the answer at http://stackoverflow.com/a/42933842/3980197

How does it know which chunk to read? I mean, how does it know that `chunk` is `example.R`? You only have 1 .R file, but I usually have >10.

Here's an example of a working Rmd file I have for a project. The regular HTML file is correctly created, but the Notebook variant does not have any output. This is the project I based my reprex on.

Here's the regular HTML: http://rpubs.com/EmilOWK/PING_admixture_study

**Notebook.Rmd**
````
---
title: 'R Notebook for: Biogeographic ancestry, cognitive ability, and socioeconomic
  outcomes'
author: "Emil O. W. Kirkegaard"
output:
  html_document: default
  html_notebook: default
  word_document: default
editor_options:
  chunk_output_type: inline
---

# About
This is an R notebook of our R scripts used for the paper *Biogeographic ancestry, cognitive ability, and socioeconomic outcomes*. The supplementary files can be [found at OSF](https://osf.io/z8dy5/).

The codebase is split into chunks (.R files) which do have some comments.

#Start up code
This script loads packages, data, merges data and does some initial filtering.

```{r, init, code=readLines("r/init.R")}
```

#Recoding
This code recodes some variables, primarily the SIRE ones.

```{r, recode, code=readLines("r/recode.R")}
```

#Cognitive ability analyses
Impute missing data, factor analyze, score.

```{r, CA, code=readLines("r/CA.R")}
```

#S factor analyses
Impute missing data, factor analyze, score.

```{r, S, code=readLines("r/S.R")}
```

#Ancestry & SIRE
Some analyses of ancestry and SIRE.

```{r, ancestry_SIRE, code=readLines("r/ancestry_SIRE.R")}
```

#Precision analysis
The precision analysis.

```{r, precision, code=readLines("r/precision_analysis.R")}
```

#Modeling
After having done the initial analyses, we do the main modeling. This outputs quite a lot. Normally, one would do this interactively and only print the necessary stuff, but when the output is a static file, we will have to print everything.

```{r, model, code=readLines("r/model.R")}
```
````

I don't see how to recreate this using the solution you proposed.

PS. For those wondering how to have code blocks with 3 backticks. [Apparently](http://stackoverflow.com/questions/31825237/how-do-i-escape-three-backticks-surrounded-by-a-codeblock-in-markdown), md simply considers the longest backtick sequence the code delimiter, so I just used 4 backticks to make the code block.

**Comment by jmcphers** [comment]
You use a special header in the .R file to indicate the beginning of each chunk, e.g.

    ## ---- foo

will populate a chunk with the label `foo`, as in:

    ```{r, foo}

So if you want multiple .R files, you can just call `read_chunk` on all of them in your setup chunk; the annotation in the .R file will tell knitr (and the notebook) which chunk to map which file to.

**Comment by Deleetdk** [comment]
I see. That's a bit too complicated to use in practice for large projects, so I'll have to stay with plain Rmd. No chance you're going to make R notebook play nicely with regular Knitr?

There doesn't seem to be any bugs here, just odd features. Closing.

**Comment by jmcphers** [comment]
Notebooks use knitr but obviously have to do so piecemeal since the execution model is interactive rather than batch, and the IDE needs to emulate (read: duplicate/model) knitr to align the behavior. We're definitely interested in continuing to close the gap so that as many knitr docs as possible "just work" as notebooks.
