### ISSUE TITLE
Create a release with changelog to support automatic build systems

### ISSUE THREAD

**Issue by mdehollander** [rstudio/rmarkdown#1006]
Would it be possible to create a release for each version? Together with the changelog that is now present in https://raw.githubusercontent.com/rstudio/rmarkdown/master/inst/NEWS? That would really help automatic build and notifications systems (like conda/sibell.com)

Thanks!

**Comment by jjallaire** [comment]
There are branches with the various CRAN releases, see
https://github.com/rstudio/rmarkdown/branches

**Comment by yihui** [comment]
I think we should use tags instead of branches to annotate releases. That way, we can use Github releases and move NEWS items there.

**Comment by mdehollander** [comment]
@yihui Indeed, that would be nice!

**Comment by yihui** [comment]
Done. I have added tags for the past releases, but I didn't move NEWS to Github releases. I will make use of Github releases starting from the next version.
