### ISSUE TITLE
High memory use with rmarkdown rendered html in Firefox

### ISSUE THREAD

**Issue by mdehollander** [rstudio/rmarkdown#1007]
I experience high memory use when opening a html file in Firefox that has been rendered using rmarkdown. The file is relative small (3 MB), but requesting almost 2 GB of RAM to load. In Chromium it only needs 350 MB to load. In this a Firefox specific thing or related to the html generated with rmarkdown? I am using Ubuntu 16.04 LTS as OS.

**Comment by yihui** [comment]
I recommend you to ask this question on StackOverflow instead (and provide your HTML file there).  Thanks!
