### ISSUE TITLE
Small change, documentation could use a clarification

### ISSUE THREAD

**Issue by darachm** [rstudio/rmarkdown#1008]
I wanted to tell `rmarkdown` that the pandoc to use was somewhere not in PATH. The documentation for `pandoc_available()` states:

> The system environment variable ‘PATH’ as well as the version of pandoc shipped with RStudio (its location is set via the environment variable RSTUDIO_PANDOC’ by RStudio products like the RStudio IDE, RStudio Server, Shiny Server, and RStudio Connect, etc) are scanned for pandoc and the highest version available is used. Please do not modify the environment varaible ‘RSTUDIO_PANDOC’ unless you know what it means. 

Is there a list of environmental variables and what they mean? I couldn't find it, perhaps I'm a bit daft.

I think it would be very easy to state that 'RSTUDIO_PANDOC' points towards the directory that contains the pandoc binary, and I think that the current style of documentation dicourages the use of these packages outside of the RStudio ecosystem. I had to ask on twitter for the answer, which was kindly answered, but I can't imagine that RStudio wants to make this ecosystem a black box. 

Is this what it does, that 'RSTUDIO_PANDOC' points towards the directory that contains the pandoc binary? Should I make a pull request for this edit?

**Comment by jjallaire** [comment]
RSTUDIO_PANDOC is provided as a hint to the rmarkdown package as to the location of the embedded version of pandoc within RStudio. It's therefore not really intended to be set externally. If you want to use a different pandoc you should just ensure that it's on the PATH and that it's a later version than the one included with RStudio (as currently rmarkdown will always use the highest version that it fines).

If we wanted to make this more externally configurable I'd suggest we probe for a new `RMARKDOWN_PANDOC_PATH` environment variable. We could either make this behave the same way (and only be selected if it's the most recent version) or we could make it a hard override.
