### ISSUE TITLE
Erro: 16:9: unexpected symbol

### ISSUE THREAD

**Issue by tatianafalmeida** [rstudio/rmarkdown#1010]
Good night,

I´m trying to make a pdf file from the Rmarkdown, but I´m getting this error:

Erro: 16:9: unexpected symbol
15: #### -- Packrat Autoloader (version 0.4.8-1) -- ####
16: source("packrat
            ^
Execução interrompida

I´ve installed R from homebrew, I have a Mac OS Sierra, and currently using R version 3.3.3

Thank you very much,

**Comment by yihui** [comment]
It seems the problem was from packrat. If the problem goes away after you disable packrat, you need to report this to packrat instead. Thanks!
