### ISSUE TITLE
Render error with src$href htmlDependency htmlwidget 

### ISSUE THREAD

**Issue by qinwf** [rstudio/rmarkdown#1011]
Example R Markdown file:

```
---
title: "href-dep"
output: html_document
---

replace ''' with ```

'''{r}
library(htmlwidgets)

testit = function(option){
  dep = htmltools::htmlDependency(
          name = "testit",
          src = c(href = "https://example.com/"),
          script = "exmaple.min.js",
          version = "0.0.1"
        )

  return(
    htmlwidgets::createWidget(
      name = "testit",
      x    = list(option = option),
      dependencies = dep,
      package = "testit"
    )
  )
}

testit(1)
'''

```

Please replace ''' with ```

Error message is 

```
path for html_dependency not provided
```

from 

https://github.com/rstudio/rmarkdown/blob/444d7ae381a84ae32bf32cdfbb64882b799b1596/R/html_dependencies.R#L215-L216

```
validate_html_dependency <- function(list) {
  ...

  if (is.null(list$src$file))
    stop("path for html_dependency not provided", call. = FALSE)
  file <- list$src$file

  ...
}
```

Here is an simple htmlwidget package example with full source https://bitbucket.org/qinwf/widget-bookdown-html-dependency-example/src/c716ad448c6b6871dd3dbf9fde1ac9c1050eaa66/widget/R/testit.R?at=master&fileviewer=file-view-default 

I want to use `htmltools::htmlDependency(src = c(href = "https://example.com/"))` to keep the output file smaller.

**Comment by jjallaire** [comment]
That's correct, htmlwidgets in R Markdown currently must include the full source code of the widget (for creating standalone HTML and supporting offline usage). A workaround would probably be to make your widget just have some JS that bootstraps a library from a remote location.
