### ISSUE TITLE
Doc Header Vs rendering of table in word

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/rmarkdown#1013]
The only way I have found to include an image in the header of a template.docx is to se its  <Size and position/wrapping size> NOT to "in line with text". After this it seams mandatory to set in the "save" option to "Embed fonts in the file". If one of this two settings is missing the document is compiled without any error... and any header.

Anyway, as the option to embed the fonts in the saved (template) file is enable, the document (.rmd) is rendered with the headers BUT (only) if the rmd contain (at least) a table, the following chain of errors rise before that .docx is open:

- We're sorry. We can't open <name_file.docx> because we found a problem with its contents. Details: Microsoft Office cannot open this file because some parts are missing or invalid. Location: Part: /word/fontTable.xml, Line: 0, Column: 0 [Click on 0K]
- Word found unreadable content in <name_file.docx>. Do you want to recover the contents of this document? If you trust the sourse of this document, click Yes. [Click on Yes]
- This document contains fields that may refer to other files. Do you want to update the fields in this document? [Click on Yes]

Now the document appear. With its header, cross reference, R code compiled, ... all seams 0k, but the tables are all left aligned and all without the orizontal lines separating the header-row from the rest of the tables. the option fig.align='center' for figures doesn't work too.

How can I fix it?

Thank you very much.
Corrado.

**Comment by yihui** [comment]
This is probably a too deep Word issue for us to investigate. We rely on Pandoc to convert Markdown to Word, and the best we could do for you is try to make a minimal reproducible example. If we are able to reproduce your issue with pure Markdown (no R Markdown) and Pandoc, we can submit a issue to Pandoc (https://github.com/jgm/pandoc/issues) for you. Other than that, we won't be able to offer further help. 

BTW, I'm not sure which version of Pandoc you were using when you filed this issue, but a blind shot in the dark is to upgrade RStudio (which contains Pandoc 1.19.2.1): https://www.rstudio.com/products/rstudio/download/
