### ISSUE TITLE
Rstudio can't knit to pdf or html

### ISSUE THREAD

**Issue by rioualen** [rstudio/rmarkdown#1016]
Hello, 

I can't knit to HTML or PDF anymore, although it used to work just fine.
Here's the error I keep getting:

```
pandoc: out of memory (requested 1048576 bytes)
Error in strsplit(version_info, "\n")[[1]] : subscript out of bounds
Calls: <Anonymous> ... pandoc_available -> find_pandoc -> lapply -> FUN -> get_pandoc_version
In addition: Warning message:
running command ''/usr/lib/rstudio/bin/pandoc/pandoc' --version' had status 1 
Execution halted
```

I used to have Rstudio 0.999.903, which I uninstalled, I then installed 1.0.44 version, reinstalled the knitr package through Rstudio, got this error again. I also tried Rstudio Version 1.0.136 and no change. Even tried to go back to Rstudio 0.98.1103. 

I installed pandoc 1.18-1 from the git repository using the debian package installer, same problem again. I triedpandoc 1.19 more recently. 

I tried uninstalling R and re-installing a more recent version, again with no success.

The command-line works:

```
library(rmarkdown)
rmarkdown::render("test.Rmd", "html_document")
```
Here's my system info:

```
rioualen@dell3b31852 ~/app_sources $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	LMDE 2 Betsy
Release:	2
Codename:	betsy
rioualen@dell3b31852 ~/app_sources $ uname -r
3.16.0-4-amd64
```
Thank you

**Comment by rioualen** [comment]
In case someone runs into this issue... I posted a solution [here](http://stackoverflow.com/questions/40889451/rstudio-pandoc-issue-cant-knit-to-html-or-pdf/43409270#43409270).

**Comment by yihui** [comment]
FYI we have upgraded Pandoc to 1.19.2.1 in the latest version of the RStudio IDE.
