### ISSUE TITLE
Rstudio R Markdown not showing inline results for some dplyr selects

### ISSUE THREAD

**Issue by tgb417** [rstudio/rmarkdown#1017]
When I running the following, inline results are not showing consistently.

```{r Loading EDAWR data set}
library(dplyr)
library(tidyr)
library(EDAWR)

```

Note:
 - This does not seem to work inline in the R Markdown window.  (Console mode results is showing)

```{r Not selecting columns, echo=TRUE}
select(storms, -storm)

```
Note:
 - This does not seem to work inline in the R Markdown window.
```{r selecting only specific range of columns, echo=TRUE}
select(storms, wind:date)

```

```{r These select work OK, echo=TRUE}
#select specific columns works OK.
select(storms, storm, pressure)

```
This was done on Macintosh OSX 10.11
Rstudio Version 1.0.136
rmarkdown version 1.4

**Comment by jjallaire** [comment]
@jmcphers @javierluraschi

**Comment by kevinushey** [comment]
I suspect this is an issue in the current release where attempts to print data.frame objects containing `Date`s can fail. @tgb417, can you try installing the preview release?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by tgb417** [comment]
Thanks for the reply. 

May take a day or two for me to get to this. Will report back when I know more.

**Comment by tgb417** [comment]
That did it.  Thank You.  

With the updated RStudio v1.0.143 Preview.  This issue is no longer present.  

How far along is this "Preview" version?  I guess that is to ask:  Is it "safe" for non-production use, or does it have a strong likelihood to blow up in other areas?

**Comment by kevinushey** [comment]
Glad to hear it!

The current preview is just a patched version of the current version of RStudio, primarily with fixes to ensure that RStudio works fine when run against R 3.4.0. We're planning to promote it to a public release after we've finished testing + validation; it should be safe for general use in the mean-time (but please let us know if you encounter any issues!)

**Comment by danlemaire** [comment]
It took me a long time to find this thread... Thanks for posting it!!  I have had intermittent problems where running a pipeline during EDA doesn't actually print the resulting dataframe inline.  I couldn't figure out what was causing the issue and I couldn't find anyone else who was having the problem.  This helps immensely to know that it is related to dates and that it is a known issue.
