### ISSUE TITLE
Add YAML option to disable Rmd download in html_notebook

### ISSUE THREAD

**Issue by karseneau** [rstudio/rmarkdown#1021]
**Problem:** When sharing notebooks, there is sometimes confidential information stored in the code chunks. There is no way to disable this with the current format. While it is possible to hide them with `code_folding: hide` or `echo=FALSE` in the chunk, this is entirely visible when downloading the Rmd (which is embedded within the .nb.html output file).

**Workaround:** The author must be aware of the potential loss of confidentiality and externalise that from the notebook, possibly using `source` to pull in external scripts for example. This is tedious and I believe is outside the spirit of being able to maintain reproducible work with limited dependencies.

**Possible Solution:** Add a YAML option, such as `download_rmd`, the value could default `true` to maintain current behaviour, yet be set to `false` at the author's discretion.

**Comment by karseneau** [comment]
Perhaps use `code_download` to make consistent with `html_document()`

**Comment by jjallaire** [comment]
Agree it would be nice to have this option, but note that the core use case for notebooks is sharing source code. We'd need to "undo" a lot of the default mechanisms of notebooks to get them to NOT include the source code (as notebooks are intended to be openable as an Rmd). What about just rendering as html_document for those scenarios where you don't want to share source code?

**Comment by karseneau** [comment]
Thanks for the response JJ. I had missed that feature of notebooks, to open as an .Rmd, and agree that by rendering as `html_document` will solve my requirement. Please close this issue.
