### ISSUE TITLE
default toc_depth for PDF documents is 2; while others is 3

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#1024]
Is this intentional or just an oversight?

The reason I ask -- RStudio provides some UI for editing chunk options; among those the TOC depth. When that value is 3, RStudio assumes that this is the 'default' value and so writing out a `toc_depth` value is unnecessary. However, this leads us to producing the 'wrong' YAML header for PDF documents.

I'm curious whether this is a change that can occur on the `rmarkdown` side, or should occur on the RStudio side.

**Comment by jjallaire** [comment]
I don't recall why we chose 2 but I'd hate to change it underneath people at this point. So I think this is a change that should be made on the IDE side.

**Comment by kevinushey** [comment]
Sounds good -- I'll close this and file on the IDE side.
