### ISSUE TITLE
Tabset overwritten by styles.css

### ISSUE THREAD

**Issue by ltrainstg** [rstudio/rmarkdown#1028]
I wanted to set the style of my HTML Rmarkdown output using a custom css but I also want to use the default ability of tabset. I think if you provide a custom css sheet it is overwriting the tabset information. Could you make it so that tabset works even if custom css is provided? 

I'm going to see If I add the tabset code to the custom css sheet and see if that works.

**Comment by yihui** [comment]
This looks like a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with a reproducible example) and let us know the link if you don't get an answer in a few days. Thanks!
