### ISSUE TITLE
R Markdown deletes multiple lines, when I press backspace

### ISSUE THREAD

**Issue by elben10** [rstudio/rmarkdown#1031]
R markdown, has just begun to delete multiple lines, when I press the backspace button. I've never experienced the problem before. I use R version 3.3.2 (2016-10-31), and I use the RMarkdown 1.4.

**Comment by kerryTrue** [comment]
have you solved it? I have the same issue

**Comment by BernardWeems** [comment]
I too have this issue.

**Comment by GsProjects** [comment]
Closing R studio completely and restarting solved the problem for me.

**Comment by betsyrosalen** [comment]
This problem just started happening for me too, but restarting RStudio did nothing to fix it.  I may try restarting my whole computer and see if that helps (even though I just did a complete restart about 10 min ago), but I am thinking that maybe there a setting somewhere that I turned on by accident that I just need to turn off again?

**Comment by betsyrosalen** [comment]
OK, well a second restart of RStudio fixed the problem...

**Comment by sctyner** [comment]
I think this issue may need to be re-opened. I have had this problem intermittently for quite a while, and I know colleagues who have it as well. Restarting RStudio didn't work, restarting my computer didn't work, closing and reopening the RStudio project didn't work. Plus, restarting is a hack, not a solution to the underlying problem. I am running RStudio Version 1.2.1114 (but it has happened in previous versions). Here is my session info: 
```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6
```
If this is not the right location for this issue, please let me know what is. Thanks.

**Comment by betsyrosalen** [comment]
Yeah, this just happened to me again over the weekend too.  Nothing fixed it.  Restarted RStudio about 5 times.  Restarted the whole computer.  Still had backspace key and arrow keys doing weird things.  I finally found ways around using those keys and at some point they just started working again.  Can't for the life of me figure out why they went haywire or why they started working again either.  Not at home now, but I can post system/session info later if it's helpful.

**Comment by yihui** [comment]
I think this issue needs to be transferred to https://github.com/rstudio/rstudio. I don't have the privilege to make the transfer. Anyone from the IDE team? Cc @kevinushey @jmcphers

**Comment by kevinushey** [comment]
I don't think I can transfer the issue either.

**Comment by Brownsey** [comment]
Still happens

**Comment by kevinushey** [comment]
Please continue any discussion on the RStudio issue at https://github.com/rstudio/rstudio/issues/4064.

It would also be useful to know which version of RStudio you're using.

**Comment by MauroCE** [comment]
I have the same problem, it happens quite often actually. Possibly has to do with some keyboard combination pressed by accident? I restarted R completely and didn't solve the problem. Here is my R studio session info.

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=it_IT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    packrat_0.5.0 
```

**Comment by yihui** [comment]
@MauroCE This is the wrong repo to report the issue. Please see the reply right before yours. Thanks!
