### ISSUE TITLE
When using render i get follwing error ! Undefined control sequence. \grffile@filename ->

### ISSUE THREAD

**Issue by hooty668** [rstudio/rmarkdown#1033]
When i use the Knit button on rstudio everything works fine, however when i use rmarkdown::render i get the error ! Undefined control sequence. \grffile@filename ->. This was also happening when I added fig.align = 'center' to the plot chunk in the Rmd file.  my YAML looks like:

---
title: NULL
graphics: yes
output: pdf_document
geometry: top = .58in, bottom = 0.6in, right = .3in, left = .3in, headheight=65pt,includehead, voffset = -.8in
header-includes:
- \usepackage{fancyhdr}
- \usepackage{graphicx}
- \pagestyle{fancy}
- \fancyhead[LO,LE]{\includegraphics[width=3cm,height=1.5cm]{FullColor.png}}
- \fancypagestyle{plain}{\pagestyle{fancy}}
- \usepackage[dvipsnames]{xcolor}
- \usepackage{booktabs}
- \usepackage{caption}
- \renewcommand{\headrulewidth}{0pt}
- \usepackage[T1]{fontenc}
- \usepackage{tabularx}
- \usepackage{longtable}
- \usepackage{rotating}
- \usepackage{makecell}
- \usepackage{adjustbox}
- \usepackage{array}
- \usepackage{xparse}
- \usepackage{color}
- \usepackage{textcomp}
- \pagenumbering{gobble}
- \usepackage{xspace}
- \usepackage{sectsty}
- \subsectionfont{\normalfont\large\itshape\underline}
- \headsep = 35pt
- \footskip = 70pt
---

**Comment by hooty668** [comment]
Update.

When removing output_dir from the render function everything works fine.

**Comment by yihui** [comment]
I don't recommend using `output_dir`. Please see #861 for more info.
