### ISSUE TITLE
Incorrect latex code generated for figure caption when containing a '%' and alignment is set

### ISSUE THREAD

**Issue by ygc2l** [rstudio/rmarkdown#1034]
To make it short, backslashes are turn into \textbackslash{}. So instead of \begin{figure} you have \textbackslash{}begin{figure}. I tried both released and dev version of rmarkdown.

A minimal reprex:

Rmd file:
`    ```{r echo = FALSE, fig.cap="test %", fig.align='center'} plot(1:10)
```   `

R code:
`
rmarkdown::render("reprex.Rmd", output_format = rmarkdown::pdf_document(keep_tex = TRUE))
`

**Comment by yihui** [comment]
Same question as https://github.com/yihui/knitr/issues/1351#issuecomment-298337714 and the same answer applies (when there are special characters in figure captions, you have to either use bookdown or escape the characters, e.g. `\\%`).

**Comment by ygc2l** [comment]
Thanks! Escaping the characters works! I actually tried `\%` but not `\\%` before to submit this issue.

**Comment by baderstine** [comment]
Is there a list of the special characters to which this applies?

**Comment by yihui** [comment]
@baderstine http://www.personal.ceu.hu/tex/specchar.htm
