### ISSUE TITLE
disable incremental nested lists in beamer presentation

### ISSUE THREAD

**Issue by yimingli** [rstudio/rmarkdown#1037]
The tip [here](http://rmarkdown.rstudio.com/beamer_presentation_format.html#incremental_bullets) works for non-nested bullets. But for nested bullets, it does not seem to work.

Here is what I've tried:

```
> - level 1
>     - level 2 item 1
>     - level 2 item 2
```

[This post](http://stackoverflow.com/a/36867676/3101585) suggests adding multiple `<tab>` in front of the level 2 items. But it didn't work for me.

**Comment by yihui** [comment]
This is a Pandoc issue. The rmarkdown package does not do anything magical other than adding the `--incremental` flag to the `pandoc` command-line. It is up to pandoc how to generate the LaTeX code for your beamer presentation. The Pandoc repo or mailing list would be the right place to talk about your feature request: https://github.com/jgm/pandoc/issues Thanks!
