### ISSUE TITLE
User can't type working directory when creating new R project

### ISSUE THREAD

**Issue by idc9** [rstudio/rmarkdown#1039]
# Problem

When creating a new R project from an existing directory the user is unable to modify the text box that displays `Project working directory:` i.e.

<img width="741" alt="screenshot 2017-05-10 12 56 57" src="https://cloud.githubusercontent.com/assets/906398/25911193/f261ed2e-3580-11e7-9eea-b7b7c09a9656.png">

The user has to click the Browse button and manually move to the desired directory. In a lot of cases it would be easier to just type the desired directory. 

# Solution
Allow the user to type in the project working directory to create a new R project from an existing directory (see above image).

**Comment by yihui** [comment]
Closing since it is an RStudio IDE issue irrelevant to the rmarkdown package. Please report to support.rstudio.com instead. Thanks!
