### ISSUE TITLE
Add open graph tags

### ISSUE THREAD

**Issue by carlganz** [rstudio/rmarkdown#1040]
http://ogp.me/

Open graph tags are metadata that allow webpages to integrate nicely with things like Apple iMessage, Facebook, etc. 

With some tweaking to the HTML templates, it wouldn't be too difficult to specify og tags as YAML. 

If others are interested I would be happy to make a pull request.

Regards,
Carl

**Comment by yihui** [comment]
Yes, a pull request is welcome.
