### ISSUE TITLE
code folding for different engines

### ISSUE THREAD

**Issue by saptarshiguha** [rstudio/rmarkdown#1043]
Hello,
I'm using the python engine a lot (```{python ...}``` ) but the code folding toggle doesn't seem to fold the python fragments (works for ```{r}``` blocks)

Am i doing something wrong?

rmarkdown version: rmarkdown_1.4.0.9001

**Comment by saptarshiguha** [comment]
This is related to [#914](https://github.com/rstudio/rmarkdown/issues/914)

**Comment by saptarshiguha** [comment]
There is a JS file loaded when code folding is in use: codefolding.js.
In this file is a line
`// select all R code blocks
  var rCodeBlocks = $('pre.r');
  rCodeBlocks.each(function() {`


Changing `$('pre.r')` to say `$('pre.python')` hides python code fragments . Changing to `$('pre')` hides all `pre` fragments (the latter might be a bit of a hammer).

I'm no expert, but couldn't the codefolding.js select `$('pre.X')` where  X in some set of languages (that might cover most use cases)? or maybe add 'usercode' div class to each and select all 'usercode'

**Comment by yihui** [comment]
@ilia-kats Yes. Please feel free to submit a pull request! Thanks!

**Comment by cderv** [comment]
This was done for several language in https://github.com/rstudio/rmarkdown/commit/0f899450f3307e4975fda85d06c667f30ec56153 and https://github.com/rstudio/rmarkdown/commit/170d0486c50e2c5a48b62150a8129626e3b803f8

I close this and some new issue can be opened for new languages.
