### ISSUE TITLE
Data table in html file not opening on IOS devices after switching from hwriter to DT

### ISSUE THREAD

**Issue by myronwood** [rstudio/rmarkdown#1044]
I recently switched from from using hwriter to DT for the purposes of generating the table object that is then rendered to HTML by rmarkdown::render().  

When using hwriter, the resulting data table inside the html file was able to load on all browsers and OSs that my audience cared about.  To get around the bug/feature of hwriter that causes sections of an html table to be rendered as code snippets if the data element is preceded by 4 spaces, I switched to DT.  

Now that the html data table is a DT::datatable, that part of the html report does not load on IPhones.    The entire html file, including the data table, still loads correctly on Android and Windows.  htmltools::withTags is now used in the datatable generation process; it was not used before.

**Comment by yihui** [comment]
Could you provide a minimal, self-contained, and reproducible example? Please also provide info about your device and web browser.

I can view tables on https://rstudio.github.io/DT/ in Safari on my iPhone.
