### ISSUE TITLE
Plot and formattable in a loop -- with cat()

### ISSUE THREAD

**Issue by frankwwu** [rstudio/rmarkdown#1046]
I need to plot and formattable in a loop. I have tried the suggestion -- inserting cat("\n\n") -- posted previously, but it does not work in my case. Here is my demo code, [https://github.com/frankwwu/R-Knots/tree/master/Bug-mdR-loop](https://github.com/frankwwu/R-Knots/tree/master/Bug-mdR-loop). Any suggestion is appreciated.

**Comment by yihui** [comment]
This is an FAQ. Please see https://yihui.name/en/2017/06/top-level-r-expressions/ for more technical info, and ask the question on StackOverflow if it is still not clear to you. Thanks!
