### ISSUE TITLE
Sitemaps for R Markdown websites?

### ISSUE THREAD

**Issue by znmeb** [rstudio/rmarkdown#1047]
Is there an easy way to generate a sitemap for an R Markdown website? I haven't found anything on any of the help sites.

**Comment by jjallaire** [comment]
No, you would just have to post-process it to generate a sitemap.

**Comment by yihui** [comment]
It should not be hard to write an R script to generate the `sitemap.xml`. Basically you need `list.files(, '[.]html$')` and `file.mtime()`. Sounds like a good 15-min R exercise.

**Comment by znmeb** [comment]
It turns out Hugo (at least for the theme I'm using with Blogdown) generates them automatically! So I may be able to isolate that bit of code for other R Markdown sites.

**Comment by yihui** [comment]
Hugo does generate sitemap.xml by default, but you cannot reuse its code for R Markdown sites, if you are talking about http://rmarkdown.rstudio.com/rmarkdown_websites.html Hugo's code was written in Go. You have to rewrite it by yourself. As I said, it is really not difficult as long as you know the structure of sitemap.xml, which is quite simple, too.
