### ISSUE TITLE
Will i be able to use rmarkdown::run("Content of RMD") instead of rmarkdown::run("filename.rmd").

### ISSUE THREAD

**Issue by nivapo** [rstudio/rmarkdown#1051]
Hi,

I would like to run a app using the string (Rmd content) built on the fly without writing to the rmd file. is there any way that i can do with the current package. 

Regards,
Srinivasan S

**Comment by jjallaire** [comment]
Not currently. I recommend just writing a temporary file using the string and feed that to render.

**Comment by nivapo** [comment]
Thanks you for the quick response.  

Regards,
Srinivasan S
