### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by nivapo** [rstudio/rmarkdown#1055]
I was curios in ways to distribute shiny app without bundling the plain rmd.  What's your recommendation on this . Is there any way i can bundle the encrypted file and give a decrypting function as a arg for the shiny app.

**Comment by yihui** [comment]
I don't have a recommendation, and at the same time, I don't think this question is specific to rmarkdown, but looks like a more general R question (how to encrypt/decrypt R code), so please ask on StackOverflow instead. Thanks!
