### ISSUE TITLE
header functionality in html_fragment

### ISSUE THREAD

**Issue by berkorbay** [rstudio/rmarkdown#1057]
Hi. I frequently use `html_fragment` for a multi-page catalogue website in order not to generate js and css overhead (self_contained: false appends tons of unneeded files still and I cannot remove all those css and script src lines). But, I cannot use `in_header` option in `html_fragment`, therefore unable to insert my "homemade" script and css imports.

Is there a way to insert into `<head></head>` tags in `html_fragment` mode?

edit: Funnily I can add `<head>` tags in `html_fragment` file if I remove `<html>` tags.

**Comment by jjallaire** [comment]
I believe the latest version (1.5) includes the ability to proved before
body and after body includes, which of course you could use to inject
whatever tags you wanted

**Comment by yihui** [comment]
Just FYI, if you are trying to make a websites, you may consider blogdown now: https://github.com/rstudio/blogdown
