### ISSUE TITLE
Problem with jdbc connection in Rmarkdown 

### ISSUE THREAD

**Issue by buchi86** [rstudio/rmarkdown#1059]
Hi,
I have some trouble with a chunk of code on RMarkdown that on R works just fine. It seems like a problem with the connection to the Oracle Database, this is the error message I get

Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLException

To connect to the DB I use the JDBC package. Thanks' in advance for any hints

**Comment by cderv** [comment]
I think Rmd are render in clean R environment. It could be a lead to follow. You could check if you have settings in your R environnement that are reproduced when executing Rmd file. I have not the solution, but if it could help...
