### ISSUE TITLE
Trouble saving and loading

### ISSUE THREAD

**Issue by kmathers** [rstudio/rmarkdown#1060]
I've been writing a regression algorithm in an R Markdown Notebook in Rstudio. I Have writing probably 15 chunks in a file a couple hundred lines long.  After saving my .Rmd file and reopening it upon opening Rstudio a couple days later all my chunks and code are gone. There is not the chunk notation - just a blank space as if I were writing any script where I could insert my first chunk on line 1. The file is definitely open, it shows my filename.Rmd I saved it as under the tab name in Rstudio. This is the second time this happened.  Any idea what's wrong?

**Comment by yihui** [comment]
Sounds like an RStudio IDE issue and not relevant to the rmarkdown package. You may file this issue to https://github.com/rstudio/rstudio/issues. Thanks!
