### ISSUE TITLE
`runtime: shiny` not compatible with bookdown cross-references

### ISSUE THREAD

**Issue by aoles** [rstudio/rmarkdown#1063]
Hi,
I've recently run into an issue of using `bookdown::html_document2` with interactive R Markdown documents set with `runtime: shiny`. The problem is that cross-references to sections are not resolved correctly. I'm filing this issue here rather than with bookdown because the problem seems to be caused by the [`--id-prefix` set in `render`](https://github.com/rstudio/rmarkdown/blob/3544f1d5657d6e7d2156fab9e830e199179f70a8/R/render.R#L567-L571). I was wondering why do you actually need to set this prefix in first place, and what would be the best approach to get cross-references to work in interactive documents?

Please find below a MWE illustrating the issue. Cross referencing doesn't work unless `runtime: shiny` is removed from the yaml front matter.

I'm looking forward to your thoughts on this.

Cheers,
Andrzej

```
---
output: bookdown::html_document2
runtime: shiny
---

# Heading

A reference to \@ref(heading).
```

**Comment by aoles** [comment]
It seems that the default `section-` prefix can be overridden by having in the document front matter `pandoc_args: ["--id-prefix", '""']`. This allows cross references to link correctly. Still, it would be good to understand why dynamic R Markdown documents use a different prefix from static ones in order to make sure we don't loose anything by this approach.

**Comment by aoles** [comment]
Setting `--id-prefix` for `runtime: shiny` also affects sidenotes in `tufte::tufte_html`, see https://github.com/rstudio/tufte/issues/40.

**Comment by jjallaire** [comment]
That behavior is there because in Shiny IDs are used for input/output
bindings. If section headers were allowed to have no prefix they would
frequently conflict with input/output IDs and havoc would ensue.

**Comment by aoles** [comment]
Thanks @jjallaire for the clarification!

The overall problem here is that postprocessor functions, such as the one from `bookdown::html_document2` which resolves cross-references, or the one from `tufte::tufte_html` for converting footnotes into sidenotes, are not aware of the `--id-prefix` option to pandoc conversion.

I had a quick look into potential solutions and it seems to me that there is no way around of exposing the prefix to the postprocessor. Checking for `knitr::opts_knit$get("rmarkdown.runtime")` is not enough because the default `"section-"` prefix can be overridden by the document format function based on `pandoc_args` set e.g. in the document front matter. While the postprocessor has access to document's `metadata` , I don't see how to get the final setting of `--id-prefix` passed to the pandoc conversion.

I'm not sure what would be the best way of exposing the value of `--id-prefix` to the postprocessor. But I could imagine either introducing an additional `pandoc` argument to postprocessor which would contain the (sub)list of options used for the conversion, or having `rmarkdown.pandoc.id-prefix` in `knitr::opts_knit`. With either solution the fix to both bookdown and tufte postprocessor would be straightforward. What do you think @yihui ?

Cheers,
Andrzej

**Comment by jjallaire** [comment]
Adding arguments to post-processors is tricky because there is likely lots of code out there already that doesn't use `...` in the post-processor signature (so will break when we introduce the new argument. I'd therefore be in favor of an `rmarkdown.pandoc.id-prefix` knit option. @yihui Let me know what you think.

**Comment by yihui** [comment]
The knitr option sounds good to me.

**Comment by jjallaire** [comment]
PR here: https://github.com/rstudio/rmarkdown/pull/1065

**Comment by aoles** [comment]
Awesome, thank you @jjallaire for your quick patch! 

One thing: doesn't [this](https://github.com/rstudio/rmarkdown/blob/94a8385cff5ce7d6561c64b5425dee8a30b0208e/R/render.R#L576) duplicate the `--id-prefix` /R/render.R#L576 if it has been already present in [`output_format$pandoc$args`](https://github.com/rstudio/rmarkdown/blob/94a8385cff5ce7d6561c64b5425dee8a30b0208e/R/render.R#L296)?

**Comment by jjallaire** [comment]
@aoles Good catch! Just pushed a change that addresses this.

**Comment by aoles** [comment]
I made a patch to bookdown to account for the value of `rmarkdown.pandoc.id_prefix` when resolving section references: https://github.com/rstudio/bookdown/pull/404
