### ISSUE TITLE
Add option to preserve intermediate .md file

### ISSUE THREAD

**Issue by khughitt** [rstudio/rmarkdown#107]
Would it be possible to add an option to keep the intermediate `.md` file that get's generated when calling `render()` (perhaps giving it a similar filename to the output file?)

This way the more VCS-friendly markdown results could be captured and saved each time something like PDF or HTML is generated.

Downstream: jimhester/knitrBootstrap#50

**Comment by stevepowell99** [comment]
Just wondering if there could be a keep_md option for word_document as well? Would be very useful to implement "tracked changes" using wdiff old.md new.md | markdown-format-wdiff >changes.md.
This is a big part of completely replacing MS Word in my workflow; my clients really want tracked changes (and I sympathise with them too)

**Comment by jjallaire** [comment]
@stevepowell99 just implemented this here: https://github.com/rstudio/rmarkdown/commit/1502ff9c692cc1ad270b1cb65607cf14d452c8dc

**Comment by cpsievert** [comment]
Would adding this argument to `pdf_document` be as easy as 1502ff9c692cc1ad270b1cb65607cf14d452c8dc?

If so, I'd be happy to do so, as I'd find it helpful for my purposes

**Comment by oganm** [comment]
Personally I wouldn't mind being able to access the intermediate file even if it has some latex in it. Sometimes unexpected things go wrong so it has a debugging purpose

**Comment by yihui** [comment]
@oganm For now, the only way is `rmarkdown::render(..., clean = FALSE)`.

**Comment by ms609** [comment]
This is handy for single Rmd files; but is there an equivalent to the `clean=FALSE` in `rmarkdown::render_site`?

**Comment by tolot27** [comment]
It would be consistent to have `keep_md` for all output formats. Currently, I'm trying to debug some pdf output and have to switch to `render`.
