### ISSUE TITLE
Unable to render shiny rmd documment when using specific version of rmarkdown and stringr

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/rmarkdown#1071]
RStudioIDE 1.1.230
rmarkdown 1.5.9000
stringr 1.1.0

**Prerequisites**

- Install rmarkdown from github
`devtools::install_github("rstudio/rmarkdown")`

- Install stringr 1.1.0
`devtools::install_version("stringr", version = "1.1.0", repos = "http://cran.us.r-project.org")`

**Steps:**

1. Open a new (shiny) .Rmd file in the RStudio IDE by going to File > New File > R Markdown… > Select Shiny

2. Save file and run it locally by clicking a “Run Document” button at the top of the scripts pane.

**Result:** The rmarkdown doc is not rendered and an error is thrown

<img width="1145" alt="screen shot 2017-06-06 at 11 58 41 pm" src="https://user-images.githubusercontent.com/17551950/26862761-65323ad2-4b13-11e7-85a9-a189f1ba4d9c.png">

Error in rmarkdown tab in IDE
```
Warning: Error in stri_split_boundaries: argument `str` should be a character vector (or an object coercible to)
Stack trace (innermost first):
    113: stri_split_boundaries
    112: str_split
    111: FUN
    110: vapply
    109: fix_replacement
    108: stri_replace_all_regex
    107: stringr::str_replace_all
    106: process_html_res
    105: process_images
    104: output_format$post_processor
    103: render
    102: discover_rmd_resources
    101: find_external_resources
    100: copy_render_intermediates
     99: output_format$intermediates_generator
     98: <Anonymous>
     97: do.call
     96: contextFunc
     95: .getReactiveEnvironment()$runWith
     94: shiny::maskReactiveContext
     93: <reactive>
     82: doc
     81: shiny::renderUI
     80: func
     79: origRenderFunc
     78: output$__reactivedoc__
      3: <Anonymous>
      2: do.call
      1: rmarkdown::run
      ```

**Comment by yihui** [comment]
This might be related to #1050. Any ideas @yutannihilation?

**Comment by yihui** [comment]
No worries. That sounds good to me.

**Comment by yutannihilation** [comment]
Sure. Thanks!
