### ISSUE TITLE
Support CommonMark syntax for code chunks/fenced code blocks

### ISSUE THREAD

**Issue by jdidion** [rstudio/rmarkdown#1073]
The CommonMark syntax for a code block does not require curly braces around the info string (what R Markdown calls "chunk options"). I.e. the following is valid CommonMark:

<pre>
```r include=FALSE
x = 1+1
```
</pre>
Is there any reason why the curly braces couldn't be made optional in R Markdown? It would be really nice if I could write valid R Markdown and also have code blocks be syntax highlighted when I open them in a text editor such as atom or vscode.

**Comment by yihui** [comment]
Curly braces come from Pandoc's Markdown: http://pandoc.org/MANUAL.html#fenced-code-blocks

The reason for requiring the curly braces is to differentiate regular code blocks with code blocks that should be executed, e.g.

````
```r
x = 1 + 1
```
````

is a regular fenced code block, and **knitr** will not execute it. This is a **knitr** code block:

````
```{r}
x = 1 + 1
```
````

Without the `{}` token, it will be awkward to mark code blocks that should not be executed, i.e.

````
```r eval=FALSE
x = 1 + 1
```
````

You probably need to request Atom/Visual Studio to support curly braces to properly highlight **knitr** code blocks.

**Comment by jdidion** [comment]
Submitted as a vscode issue.
