### ISSUE TITLE
R Notebook removes blank lines from code chunks when eval=TRUE

### ISSUE THREAD

**Issue by connorp** [rstudio/rmarkdown#1074]
When previewing an R Notebook/knitting to .nb.html, code chunks that contain blank lines within the code (between lines of code, not leading or trailing whitespace) have those blank lines removed from the output, only when `eval=TRUE` (either explicitly or implicitly as the default). The blank lines are preserved when `eval=FALSE`, or when knitting to a HTML or PDF file (this only happens in an R Notebook). Should it not preserve the code formatting as is, or at least have an option to preserve these lines? I reviewed and tried several knitr chunk options that might be relevant to the code rendering, including `strip.white` and `tidy`; neither had any impact on this behavior. 

By way of example, this code chunk (`eval=TRUE`):

    ```{r CH-test, eval=TRUE}
    a <- c(1,2,3)
    b <- 4*a
    
    # leaving some space
    
    a
    ```

renders in the R Notebook as 

    a <- c(1,2,3)
    b <- 4*a
    # leaving some space
    a

while this chunk (`eval=FALSE`):

    ```{r CH-test, eval=FALSE}
    a <- c(1,2,3)
    b <- 4*a
    
    # leaving some space
    
    a
    ```

renders in the R Notebook as

    a <- c(1,2,3)
    b <- 4*a
    
    # leaving some space
    
    a

Using the default Theme and syntax highlighting style, RStudio version 1.0.143, `rmarkdown` package version 1.5, and `knitr` version 1.16.

**Comment by jmcphers** [comment]
This is a known issue in the RStudio IDE, which is responsible for recording which lines of code were executed when using interactive execution. We hope to have a fix soon! You shouldn't see the issue when the code is executed by knitr (e.g. when knitting to a format like `html_document`).

**Comment by Teebusch** [comment]
Thank you! Is there a workaround for this? Knitting to `html_document` does not produce equivalent output (no "Hide" buttons for code chunks, no interactive tables for data frames).

How can I produce RNotebook html files (`.nb.html`) that show the code and preserve blank lines in code chunks? I tried `knitr::knit("mynotebook.Rmd")` from the RStudio console, but it also removed the blank lines. Setting `knitr::opts_chunk$set(eval=F)` preserves the blank lines, but removes the output.

**Comment by connorp** [comment]
@Teebusch I think you can get close using some of the arguments in `html_document`, such as `code_folding`, `code_download`, and `df_print`, etc, as a workaround. But I leave it to the experts if I am wrong.

**Comment by scworland-usgs** [comment]
I suppose you could also have two chunks for each process. One to run the code, `{r, echo=F, eval=T}`, and one to show the code formatted with spaces, `{r,echo=T,eval=F}`. I realize it isn't ideal.

**Comment by jmcphers** [comment]
Issue is now tracked on the RStudio IDE side here: https://github.com/rstudio/rstudio/issues/1556
