### ISSUE TITLE
No figure in pdf document if `fig.cap` included

### ISSUE THREAD

**Issue by jkbest2** [rstudio/rmarkdown#1075]
If I try to include a figure caption in a pdf document, neither the figure nor the caption show up. This reproduces for me using @yihui 's minimal example from #522, changing `output` in the YAML header to `pdf_document`:

````
---
title: "Untitled"
author: "Frida Gomam"
output: 
  html_document: 
    fig_caption: yes
---

```{r fig.cap="My figure caption."}
plot(cars)
```
````

Note that both the figure and the caption are included for an `html_document`.

Thanks!

**Comment by yihui** [comment]
Not reproducible to me.

````
---
title: "Untitled"
author: "Frida Gomam"
output: 
  pdf_document: 
    fig_caption: yes
---

```{r fig.cap="My figure caption."}
plot(cars)
```
````

Output:

![image](https://user-images.githubusercontent.com/163582/26902367-bc01e41c-4b9e-11e7-9552-8443bc8b4f69.png)

Please provide your `devtools::session_info('rmarkdown')` and `rmarkdown::pandoc_version()`, unless you have tried to [update everything](https://yihui.name/en/2017/05/when-in-doubt-upgrade/).

BTW, I'd appreciate it if you could [properly format your example](https://yihui.name/en/2017/05/four-backticks-github/) next time using four backticks in Github issues.

**Comment by jkbest2** [comment]
Updating everything solved the problem. I'll be sure to include `checkBuilt = TRUE` when I upgrade from now on.

Sorry for the noise, and thanks for a great package!

**Comment by yihui** [comment]
No worries.

**Comment by Gian77** [comment]
Hello,
I am trying to include a PDF figure in my .Rmd document using the following script

```
{r, Fig S2, echo=FALSE, out.width = "50%", fig.align="center", fig.cap = "**Fig. 2 ** NMDS Ordination"}
knitr::include_graphics("2_manuscript_suppl/Fig_S2.pdf")
```
However, if I want to remove the image's caption, then the image is not displayed any more. 

```
{r, Fig S2, echo=FALSE, out.width = "50%", fig.align="center"}
knitr::include_graphics("2_manuscript_suppl/Fig_S2.pdf")
```
Is there a way to solve this?
Thanks you,
G.

**Comment by mikey-harper** [comment]
I am failing to reproduce your error @Gian77 .  It would help if you provided a full reproducible example like this:

    ---
    output: pdf_document
    ---

    ```{r, Fig S2, echo=FALSE, out.width = "50%", fig.align="center"}
    plot(pressure)
    ```
That runs fine for me producing the plot.

As mentioned by @yihui above, please provide your devtools::session_info('rmarkdown') and rmarkdown::pandoc_version(), unless you have tried to [update everything](https://yihui.name/en/2017/05/when-in-doubt-upgrade/).

**Comment by Gian77** [comment]
Hi @mikey-harper and @yihui,
Thanks a lot for the fast reply! I appreciate it.
I have just updated everything by doing 

`update.packages(ask = FALSE, checkBuilt = TRUE)`

but anything changed. I am still not able to display the PDF if I do not include the fig.cap="something"
```
---
title: "Manuscript's figures"
author: ''
date: ''
output:
  html_document: default
  pdf_document: default
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 And thats' the code
```
{r, Fig S2, echo=FALSE, out.width = "50%", fig.align="center"}
knitr::include_graphics("2_manuscript_suppl/Fig_S2")
```

Thanks a lot!
G.

**Comment by mikey-harper** [comment]
Thanks for the code. But reproducible example should be entirely reproducible:  I don't have access to figure ""2_manuscript_suppl/Fig_S2" . However, running it with a my own image included, I still cannot replicate the error and the figure appears.

It must be something with your configuration. Please provide the output of the functions I provided you in my last post so we can check your configuration.

Also, any RMarkdown code should be indented by four spaces to format correctly on GitHub, otherwise the backticks are lost. Please make sure they are formatted correctly in the future to make it easier for others to check.

Finally, I would advise in the future that you post errors like this first to Stackoverflow: there is a larger community to check, and by spending less time troubleshooting problems, @yihui  can have more time to produce awesome code :)

**Comment by Gian77** [comment]
Hello @mikey-harper
I am sorry I wasn't complete in my post.
This is the output you asked
```
> devtools::session_info('rmarkdown')
Session info --------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.143)           
 language en_CA:en                    
 collate  en_CA.UTF-8                 
 tz       Canada/Eastern              
 date     2018-03-06                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.2   2017-12-13 cran (@1.1.2)                     
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                    
 digest      0.6.15  2018-01-28 CRAN (R 3.4.3)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                    
 glue        1.2.0   2017-10-29 cran (@1.2.0)                     
 graphics  * 3.4.3   2017-12-01 local                             
 grDevices * 3.4.3   2017-12-01 local                             
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                    
 knitr       1.20    2018-02-20 cran (@1.20)                      
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                    
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)                    
 methods   * 3.4.3   2017-12-01 local                             
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                    
 Rcpp        0.12.15 2018-01-20 CRAN (R 3.4.3)                    
 rmarkdown   1.9.2   2018-03-06 Github (rstudio/rmarkdown@9313596)
 rprojroot   1.3-2   2018-01-03 cran (@1.3-2)                     
 stats     * 3.4.3   2017-12-01 local                             
 stringi     1.1.6   2017-11-17 cran (@1.1.6)                     
 stringr     1.3.0   2018-02-19 cran (@1.3.0)                     
 tools       3.4.3   2017-12-01 local                             
 utils     * 3.4.3   2017-12-01 local                             
 yaml        2.1.17  2018-02-27 cran (@2.1.17) 
```

And this si the code I run
```
---
title: ''
author: ''
date: ''
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Manuscript's Figures

```{r Fig1, echo=FALSE, out.width = "50%", fig.align="center"}
knitr::include_graphics("2_manuscript_suppl/fig_test.pdf")
```

Fig S2 Ordination
```

[fig_test.pdf](https://github.com/rstudio/rmarkdown/files/1786683/fig_test.pdf)

**Comment by mikey-harper** [comment]
Thanks for the update. It seems like your packages are up to date. 

Did you try the minimal example provided above? It doesn't rely on any external files so it is a better indicator of the problem.

Again, the code in the last one is not formatted correctly so I cannot see the chunk headers.  You can press the "preview" button before posting to make sure the formatting is correct.

**Comment by yihui** [comment]
@Gian77 You may edit your reply after reading the issue template: https://github.com/rstudio/rmarkdown/issues/new (remember [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).
