### ISSUE TITLE
Errors encountered when rendering a md file into a pdf file

### ISSUE THREAD

**Issue by likanzhan** [rstudio/rmarkdown#1076]
I tried to convert a md file into a pdf version with "render" function in `rmarkdown`: 
`render("~/website/hugo/content/en/cv/_index.md", "pdf_document")`

And I got the following output:
`
/usr/local/bin/pandoc +RTS -K512m -RTS _index.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output _index.pdf --template /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine xelatex --include-in-header header.tex --variable graphics=yes --variable 'geometry:margin=1in' 
`
as well as the following errors:
`
pandoc: xelatex not found. xelatex is needed for pdf output.
Error: pandoc document conversion failed with error 41
`

Any suggestions? Thanks.

**Comment by yihui** [comment]
Did you install `xelatex` in your LaTeX distribution (presumably MacTeX)?

**Comment by yihui** [comment]
You may help me test TinyTeX (which includes xelatex by default) if you want: https://github.com/rstudio/rticles/pull/130#issuecomment-348812489
