### ISSUE TITLE
Any way to disable latex equations in word_document?

### ISSUE THREAD

**Issue by peng-howard** [rstudio/rmarkdown#1078]
There are some latex equations such as `$a+b=c$`, `$$a+b=c$$`, `\begin{equation}a+b=c\end{equation}` in a R Markdown file, and when I convert this file to a new word document, is there a way to disable these latex-style code fragments to be translated to word-style equations? I just want them stay as their original looks in the source R Markdown file.

For example, `$a+b=c$` should not be displayed in word as a equation `a+b=c`, it should be a string `$a+b=c$`.

Thx.

**Comment by yihui** [comment]
Yes, you can remove the Pandoc extensions `tex_math_dollars` and `raw_tex`:

```yaml
output:
  word_document: 
    md_extensions: "-tex_math_dollars-raw_tex"
```

See http://pandoc.org/MANUAL.html for more info.
