### ISSUE TITLE
When rendering Rmd file as both github_document and pdf_document, the pdf_document has to be run first

### ISSUE THREAD

**Issue by underthecurve** [rstudio/rmarkdown#1079]
Say I want to create a github document with plots (like this one: https://github.com/underthecurve/r-dataviz-ggplot2/blob/master/R-advancing-with-dataviz.md) as well as a PDF document (like this one: https://github.com/underthecurve/r-dataviz-ggplot2/blob/master/R-advancing-with-dataviz.pdf) from the same R Markdown file. I can accomplish this by running a line of code like `render("R-advancing-with-dataviz.Rmd", output_format = c("pdf_document", "github_document"))`

However, I **have to** specify the "pdf_document" FIRST before "github_document", because if I `render("R-advancing-with-dataviz.Rmd", output_format = c("github_document", "pdf_document"))`, otherwise all of the plots rendered in the .md file created will disappear.

**Comment by atusy** [comment]
This issue seems to be solved via https://github.com/rstudio/rmarkdown/issues/1503
I tried a following example with rmarkdown v1.11 and v1.12, and the latest master.
Only v1.11 reproduces the bug, the version before merging #1503.

# My example

## command

```r
rmarkdown::render("test.Rmd", c("pdf_document", 'github_document'))
```

## test.rmd

````
---
title: title
---

```{r}
plot(iris)
```
````

**Comment by cderv** [comment]
I confirm that both

```r
rmarkdown::render("test.Rmd", c("pdf_document", 'github_document'))
```
and 
```r
rmarkdown::render("test.Rmd", c("github_document", 'pdf_document'))
```
works for me with last version. 
Thanks for checking @atusy !!

**Comment by yihui** [comment]
Time cures all bugs? I wish it could be this simple :D Thanks everyone!
