### ISSUE TITLE
Problem about the code block output in pdf

### ISSUE THREAD

**Issue by mousieur-g** [rstudio/rmarkdown#1081]
Can I determine the position of the code block.in pdf generated by rmd? For example, I want the whole block indented in 2 characters, how shall I set the chunk options, please?

**Comment by yihui** [comment]
There is no chunk option for that. You must have sufficient LaTeX hacking skills to do that: read the .tex output (`keep_tex: true`), figure out the LaTeX environment names, renew the environment definitions, and add the code to the LaTeX preamble (via `includes: in_header`). That said, I don't know exactly how to indent a LaTeX environment.
