### ISSUE TITLE
Table of Contents Toc: True not working HELP! 

### ISSUE THREAD

**Issue by la1ooo** [rstudio/rmarkdown#1082]
Hello,
I recently started using rmarkdown. I have been able to run all my code correctly. The only problem I am having is getting a table of contents to show. I already tried stackoverflow and other resources for help but cannot get my issue resolved. 

My code is 

```
---
title: "LPmerge"
author: "EB"
date: "June 12, 2017"
output: 
html_document:
toc: True  
---
```

When I knit my title,author,date shows up. My toc does not show up, it just says "true" on the html published.

**Comment by yihui** [comment]
You have to properly indent subfields in YAML. Please learn more about YAML syntax: https://bookdown.org/yihui/bookdown/r-markdown.html
