### ISSUE TITLE
Bug in rmarkdown::render params

### ISSUE THREAD

**Issue by jgitr** [rstudio/rmarkdown#1084]
Good day, 

first of all a big thank you to the developers. 
When using rmarkdown today I just encountered a potential bug in rmarkdown::render when trying to pass params. 
The following .Rmd file was directly knit'able in RStudio:

```
---
title: My Document
output: pdf_document
params:
 etfnumber: !r c(1:5)
---

```{r}
params$etfnumber[3] ```
```
However, when trying to execute the following code, an error occurred:

`rmarkdown::render("C:/Users/"USER"/Desktop/asdf.rmd", output_file = "asdf.pdf", 
                  encoding = "UTF-8", params = list("etfnumber" = params$etfnumber))`

**Error in knit_params_get(input_lines, params) : object 'params' not found**

This counts for every subset of `params$etfnumber`, too.

The solution is to define params manually as follows.

`params = list("etfnumber" = c(1:5))`
`attr(params, 'class') = "knit_param_list"`

and then execute 

``rmarkdown::render("C:/Users/"USER"/Desktop/asdf.rmd", output_file = "asdf.pdf", 
                  encoding = "UTF-8", params = list("etfnumber" = params$etfnumber))``

**Comment by jjallaire** [comment]
@aronatkins Should we do this automatically in `render` so that a list can be passed directly as the `params` argument? (I believe this is the documented behavior).

**Comment by jjallaire** [comment]
The problem is that this expression is invalid: `list("etfnumber" = params$etfnumber)` as there is no `params` previously defined. 

You need something more like: `params = list("etfnumber" = c(1:5))`

**Comment by jjallaire** [comment]
Here are the docs on passing parameters: http://rmarkdown.rstudio.com/developer_parameterized_reports.html#passing_parameters
