### ISSUE TITLE
Paged Dataframe Printing doesn't work in Rmarkdown

### ISSUE THREAD

**Issue by stevekm** [rstudio/rmarkdown#1085]
I found this feature listed in the [docs](http://rmarkdown.rstudio.com/html_document_format#data_frame_printing), and even found [source code](https://github.com/rstudio/rmarkdown/blob/ca634d7951753228fd88a3b5483b2f485b47d097/R/html_paged.R#L223) that it seems to be referencing, but it doesn't actually work when you compile an R Markdown document to HTML. For example, source Rmd:

```
---
output:
  html_document:
    df_print: paged
---

.```{r cars}
print(cars)
.```

```

output:
<img width="1098" alt="screen shot 2017-06-14 at 7 01 04 pm" src="https://user-images.githubusercontent.com/10505524/27158240-0d896400-5134-11e7-8565-8e5d66cd4b45.png">
 
In fact, none of the `df_print` options listed on [that page](http://rmarkdown.rstudio.com/html_document_format#paged_printing) do anything at all. And if you try to include any of the options listed there, like this:

```
---
output:
  html_document:
    df_print: paged
      max.print: 1
---
```

It just returns an error when you try to 'Knit': 

```
Error in yaml::yaml.load(string, ...) : 
  Scanner error: mapping values are not allowed in this context at line 4, column 16
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load_utf8 -> <Anonymous> -> .Call
Execution halted
```

Is there something I am missing? Is this a bug? Or a feature that hasn't actually been implemented yet? For reference, I tested it on this system:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_1.5

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  backports_1.1.0 magrittr_1.5    rprojroot_1.2   htmltools_0.3.6 tools_3.4.0     yaml_2.1.14    
 [8] Rcpp_0.12.11    stringi_1.1.5   knitr_1.16      stringr_1.2.0   digest_0.6.12   evaluate_0.10  

```

It also sounds similar to [this issue](https://github.com/rstudio/rmarkdown/issues/964), though I am not sure its the same thing.

I also tried to do it manually, but that does not work either:

```
> library(rmarkdown)
> rmarkdown::print.paged_df(cars)
Error: 'print.paged_df' is not an exported object from 'namespace:rmarkdown'
```

**Comment by jjallaire** [comment]
Those are chunk options rather than YAML options, e.g.

    ```{r, max.print = 1}

    ```

@javierluraschi Could you submit a PR for the docs to clarify this and perhaps provide an example of setting these options both globally and per -chunk?

**Comment by stevekm** [comment]
So this is supposed to work?

```
---
output:
  html_document:
    df_print: paged
---

.```{r cars, max.print: 1}
print(cars)
.```

```

I am still getting the exact same output as before. No pageable HTML tables are appearing anywhere. Is there a minimal working example of this? Thanks.

**Comment by jjallaire** [comment]
You don't call the print function directly (that bypasses the special print
handling). Just do this:

```{r cars, max.print=1}
cars
```
