### ISSUE TITLE
--smart pandoc option not used for Word doc output

### ISSUE THREAD

**Issue by connorp** [rstudio/rmarkdown#1090]
R Markdown documentation says that the `--smart` flag for pandoc is enabled by default, and this seems to be the case when I output to HTML documents. However, when outputting to Word documents, this does not seem to be the case. In addition, I can't seem to find a way to tell rmarkdown to set that flag. I've tried `params = list("smart" = "yes")` as an argument to a manual call to `render()`, as well as the YAML headers

    output:
      word_document:
        smart: yes
        pandoc_args: [
          "--smart"
        ]

as well as those two YAML headers separately. Neither have any effect. I manually copied the pandoc command generated by `render()` and executed it myself with an added `--smart`, which worked fine, so clearly pandoc supports the smart flag for Word outputs.

**Comment by jjallaire** [comment]
Thanks for the report, fixed here: https://github.com/rstudio/rmarkdown/commit/8cfe0cbad226edc43e1525eb8592cfa9073d180c
