### ISSUE TITLE
Feature Request: Hooks for knitting (particularly after-knit-hook)

### ISSUE THREAD

**Issue by rkrug** [rstudio/rmarkdown#1092]
Hi
# Feature Request
Hook to run code after successful knitting.

# Motivation
in my workflow I run a notebook which renders several other notebooks and in this process imports data, checks the data, creates some summary graphs, etc. All these are rendert as html_documents (and other formats as well) and the root notebook is called index and contains links to the others so that I can access all as a website.
Now there are others involved in the project who are also interested in the report and I am sharing it on as a website by copying them over to a http server.
Everything works automated, but the last step, the copying of the directories containing the final outputs, is done automatically.

# Examples
1. run a script (R, sh, doesn't matter) in a hook which is executed when the document is successfully knitted / exported to automatically copy the directory containing the to the http server.

2. send an email containing the report automatically to others

**Comment by yihui** [comment]
I feel this can be easily automated outside of R/rmarkdown. You were proposing a hook, but isn't it easier to write a shell script like `Rscript -e "rmarkdown::render()" && scp _site/ user@host ...`?

**Comment by rkrug** [comment]
To make this in Studio, I would have to create a new workbook like

    ---
    title: "R Notebook"
    output: html_notebook
    ---
    ```{bash}
    Rscript -e "rmarkdown::render()" && scp _site/ user@host ...
    ```

Correct? Or 

    ---
    title: "R Notebook"
    output: html_notebook
    ---
    ```{r render}
    rmarkdown::render()
    ```
    ```{bash}
    scp _site/ user@host ...
    ```

Definitely an option.

**Comment by yihui** [comment]
I think an easier way is to create an RStudio project and specify your custom build script:

![image](https://user-images.githubusercontent.com/163582/31389183-de6404b4-ad95-11e7-8f2a-3937e6c1680a.png)

Of course, you can also use Makefile:

![image](https://user-images.githubusercontent.com/163582/31389235-0acfd924-ad96-11e7-92b4-711af019d503.png)

Then all you need is Ctrl/Command + Shift + B to build the project.
