### ISSUE TITLE
Unable to pass custom function to df_print in YAML header

### ISSUE THREAD

**Issue by connorp** [rstudio/rmarkdown#1093]
Per the rmarkdown documentation, `df_print` can be passed an arbitrary function for printing. This works fine when passed directly to `render()`, but [`resolve_df_print()` inside `render()`](https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L819) is not set up to handle the names of arbitrary functions passed via YAML headers in .Rmd documents. Could a case be added to the `resolve_df_print()` function to check that the passed string from YAML:

- is a valid function name
- that function returns the right kind of output

and if so, set that function to `df_print`. Step two I would imagine is optional, depending on its difficulty to define vs how you want the user to see an error. Example code for step one below. Apologies, I'm not sufficiently well versed in R development and the rmarkdown package to suggest code step two.  

    else if (is.function(get(df_print)))
            df_print <- get(df_print)

Ideally I'd like to do this with an R Notebook, but per issue #964, `df_print` has no effect when rendering an HTML notebook, which is suboptimal. Why not make `paged_table_html_asis` the default for `df_print`, instead of the exclusive, hardcoded option? 

Thanks for all your work on a great package!

**Comment by connorp** [comment]
I'd just like to give a little nudge to this request, given the impending change to the YAML package to disallow evaluating R expressions in YAML headers by default. The workaround to this problem, `df_print: !expr custom_print_function`, will break soon without either passing `eval.expr = TRUE` to `yaml_load()` (which I don't think is possible when you're just using the RStudio Render button, or set it as a global option, `options(yaml.eval.expr = TRUE)`. This latter choice works fine within RMarkdown documents, but seems like overkill for this issue.

**Comment by cderv** [comment]
> will break soon without either passing eval.expr = TRUE to yaml_load()

This argument is already set
https://github.com/rstudio/rmarkdown/blob/6f4cfaf99aa0f5b9e50571b201c64248b72a1c27/R/util.R#L79-L81

So I think it won't break. 

Using `df_print: !expr custom_print_function` is I think the correct way currently to pass a function. It seems easy enough to pass custom function to `df_print`. Does it work for you ?

**Comment by connorp** [comment]
Interesting, okay. It does work, but I still get the warnings about this impending breaking change when I run code inline in an RMarkdown Notebook:

```
Warning messages:
1: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
2: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
3: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
```

If it's helpful, I could put together a reprex to yield this warning. It's obviously not a dealbreaker since it's only a warning, but I'd rather not have to mute *all* warnings just to be rid of it. Including `options(yaml.eval.expr = TRUE)` eliminates the warning as well, but that seems suboptimal to have to do. 

Also, could the documentation be updated to indicate that `df_print: !expr custom_print_function` is possible and the recommended method when specifying in the YAML header? Currently, the documentation as written says you can pass an arbitrary function, but it certainly wasn't obvious to me that `!expr` was the way to do so.

**Comment by cderv** [comment]
> If it's helpful, I could put together a reprex to yield this warning. 

Yes please. So that I can look into it. 

> Also, could the documentation be updated to indicate that df_print: !expr custom_print_function is possible and the recommended method when specifying in the YAML header? Currently, the documentation as written says you can pass an arbitrary function, but it certainly wasn't obvious to me that !expr was the way to do so.

Where should we put this in your opinion ? I ask so that it is found easily. You can also make a PR if you want.

**Comment by connorp** [comment]
The following saved as a `.Rmd` file is sufficient:


````r
---
title: "R Notebook"
output: 
  html_notebook:
    df_print: !expr knitr::kable
---

```{r}
plot(cars)
```
````

Running the code cell inline within RStudio generates the plot as is appropriate, but also throws warning messages in the console. 

Regarding the placement of this instruction, I think it would definitely be appropriate in the documentation for the `df_print` argument within the documentation of each of the output functions (`html_document()`, `pdf_document()`, `html_notebook()`, etc). Perhaps something along the lines of:

>If specifying this option within a YAML header, arbitrary functions must be prefaced by `!expr`. See `?yaml::yaml.load` for details.

I would also suggest a similar note go into the relevant sections of the R Markdown documentation book: [section 3.1.6](https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing) and [section 3.3.3](https://bookdown.org/yihui/rmarkdown/pdf-document.html#data-frame-printing-1). At the moment, this documentation doesn't even mention the possibility of using an arbitrary function.

**Comment by cderv** [comment]
> Running the code cell inline within RStudio generates the plot as is appropriate, but also throws warning messages in the console.

Which version of RStudio are you using ? I can't reproduce with 1.3.1056

And thank you for the input. I'll add this in the documentation.

**Comment by connorp** [comment]
Version `1.3.1056`. Okay, this is very interesting. Let me give more precise instructions, because I've discovered this sometimes does and sometimes doesn't work. 

1. (With R freshly restarted) Create a new R Notebook file via the RStudio File menu.
2. Paste in the contents above.
3. Save the file.
4. Run the code block inline. Observe the warning messages in the console.
5. Restart R and clear output.
6. Run the code block inline again. This time, there is no error. 

I am thoroughly confused, but this works for me consistently.

**Comment by cderv** [comment]
I can reproduce now. I think this comes from the RStudio IDE itselfs. 
The inline running with the result appearing under the chunk is an IDE feature. 
It is possible they are parsing the yaml only once the first time and this cause the warning is they use the R function without the argument set to TRUE. It should be reported in the IDE repo. 
You can do it, ot I can. Tell me.

**Comment by connorp** [comment]
That makes sense. I'd probably be inclined to let you do it, since I'd imagine you're very practiced at writing up issues in the most helpful format 😊

**Comment by cderv** [comment]
Your last comment with the steps to reproduce and the explanation before
would suffice I think to open a clear issue in the rsrudio/rstudio repo
following their issue guid  and with a link to this one.

IMO I am no more qualified than you for this 😉
So this is a opportunity to report the issue you found. It is up to you.

Le ven. 7 août 2020 à 18:57, Connor P. Jackson <notifications@github.com> a
écrit :

**Comment by connorp** [comment]
Alright, can do!
