### ISSUE TITLE
List all bibliography entries using nocite 

### ISSUE THREAD

**Issue by frankyan** [rstudio/rmarkdown#1096]
Hi, I need to list all the bibliography entries from a .bib file, none of them are cited. I found that it can be done with `nocite` as following
```
---
nocite: | 
  @item1, @item2
...
```
However, there are a lot of entries. So how can I use something like `\nocite{*}` to list all the entries?
Besides, if I want to place the bibliographies somewhere else instead of the end of the document, what's the easiest way to do that?
Thanks a lot.

**Comment by frankyan** [comment]
Hi, Yihui, sorry for the previous mis-submission by triggering the shortcuts without intention when I was reading other issues. I didn't mention that I had created the issue until got a notification email of issue closed.

**Comment by yihui** [comment]
This is a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead and let us know the link if you don't get an answer in a few days. Thanks!

**Comment by frankyan** [comment]
Thank you, Yihui. 

1. I have figured out the first question. As following:
```
---
nocite: '@*'
...
```

2. I found similar question on stackoverflow, here is the link: [Include the text of a `bibentry` in the (R)markdown text body output](https://stackoverflow.com/questions/46260431/include-the-text-of-a-bibentry-in-the-rmarkdown-text-body-output). Maybe you can answer that question to help us.

**Comment by yihui** [comment]
1. Perfect. Thanks for sharing the solution!

2. I don't really have a good answer. I have seen the same question in the Pandoc repo but there was no straightforward solution, either. The only possibility is a custom Pandoc template, which requires you to understand more about Pandoc.
