### ISSUE TITLE
rmarkdown couldn't show full googleVis charts

### ISSUE THREAD

**Issue by JackHo327** [rstudio/rmarkdown#1097]
Hi,

I met this issue when I use Rmarkdown and googleVis.

Here are my rmarkdown codes:

    ---
    title: "GoogleVis"
    author: "NAME"
    date: "July 10, 2017"
    output: html_document
    ---

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```

    ```{r gv, results='asis', cache=TRUE, warning=FALSE,message=FALSE}
    # motion chart
    library(googleVis)
    M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=600,height=400))
    # plot(M)
    print(M,"chart")

    # Geo chart
    G <- gvisGeoChart(Exports, locationvar = "Country", colorvar = "Profit",options=list(width =600, height=400))
    # plot(G)
    print(G, "chart")

    # merge googleVis charts
    T1 <- gvisTable(Exports, options=list(width = 200, height= 270))
    GT <- gvisMerge(G, T1, horizontal = FALSE)
    GTM <- gvisMerge(GT, M, horizontal = TRUE, tableOptions="bgcolor=\"#CCCCCC\" cellspacing=10")
    # plot(GTM)
    print(GTM,"chart")
    ```

When I knitr this file, I get error codes say:

> pandoc.exe: Could not fetch https://www.google.com/jsapi?callback=displayChartMotionChartID121c3db055b1
HostCannotConnect "www.google.com" [connect: failed (Connection timed out (WSAETIMEDOUT))]
Error: pandoc document conversion failed with error 67

I saw several folks overcome the Error 67 by setting the output option of the yaml head as:

    ---
    title: "GoogleVis"
    author: "NAME"
    date: "July 10, 2017"
    output:
       html_document:
        self_contained: no
    ---

I could only see the `Geo chart`, and the table in the `GTM`, but I could not see the `googleMotion chart` and the `googleMotion chart`  and the `Geo chart` in the `GTM`.

<img align="middle" src="https://user-images.githubusercontent.com/11900174/28013962-7a832faa-659d-11e7-98eb-a082a395361e.png" /> 

****

My R session info:

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

> locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

> attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
 [1] RevoUtilsMath_10.0.0 RevoUtils_10.0.3     RevoMods_11.0.0      MicrosoftML_1.3.0    mrsdeploy_1.1.0      RevoScaleR_9.1.0    
 [7] lattice_0.20-35      rpart_4.1-11         curl_2.7             jsonlite_1.5        

> loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11           codetools_0.2-15       CompatibilityAPI_1.1.0 rprojroot_1.2          digest_0.6.12         
 [6] foreach_1.4.3          grid_3.3.3             R6_2.2.2               backports_1.1.0        magrittr_1.5          
[11] evaluate_0.10.1        stringi_1.1.5          rmarkdown_1.6          iterators_1.0.8        tools_3.3.3           
[16] stringr_1.2.0          rsconnect_0.8          yaml_2.1.14            htmltools_0.3.6        knitr_1.16            
[21] mrupdate_1.0.1 

****
My RStudio Version：

> RStudio
> Version 1.0.143 – © 2009-2016 RStudio, Inc.
> Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1
> Unless you have received this program directly from RStudio pursuant to the terms of a commercial license agreement with RStudio, then this program is licensed to you under the terms of version 3 of the GNU Affero General Public License. 

****
Related R Packages' Version:

    > packageVersion("googleVis")
    [1] ‘0.6.3’
    > packageVersion("rmarkdown")
    [1] ‘1.6’
    > packageVersion("knitr")
    [1] ‘1.16’

****
My Pandoc Version:

> pandoc -v
> pandoc 1.19.2.1
> Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
> Default user data directory: C:\Users\Renzhi He\AppData\Roaming\pandoc
> Copyright (C) 2006-2016 John MacFarlane
> Web:  http://pandoc.org
> This is free software; see the source for copying conditions.
> There is no warranty, not even for merchantability or fitness for a particular purpose.

**Comment by prontog** [comment]
Are you behind a proxy? If you are then try using the https_proxy env var.

**Comment by JackHo327** [comment]
Hi @prontog , thanks for your help. This is an old project that I did long ago, I think I overcame it later, and you could close the issue ;p

**Comment by yihui** [comment]
@JackHo327 Thanks! I love hearing that ("you can close the issue") 😄

**Comment by JackHo327** [comment]
haha @yihui  salute to you :feelsgood:
