### ISSUE TITLE
Feature request: handouts for beamer slides-- LaTeX knowledge prob not required

### ISSUE THREAD

**Issue by Kenkleinman** [rstudio/rmarkdown#1098]
This should be easy for someone who knows YAML, and how RMarkdown works.
If handouts are required, then they could be 6 per page or 4 per page.
If the YAML says either is needed, then the first line of the .tex file reads:
\documentclass[ignorenonframetext, handout]{beamer}

If 4 slides per page are needed, the LaTeX header needs to include the material here:
https://goo.gl/n1xdUL

If 6 slides per page are needed, the LaTeX header needs to include the material here:
https://goo.gl/oEOH1o

**Comment by yihui** [comment]
Thanks for posting the solutions! Two comments:

1. Some printers support printing multiple PDF pages on a single page of paper, so this problem may be solved on the printer's side.

2. The LaTeX code you provided is not trivial, so I'm afraid we are not going to incorporate it in this package, but ask users to insert it by themselves via the `includes` option in YAML instead. Usually we can only include code that we are able to maintain in the future.

I'd recommend you to post this on StackOverflow to share with more people (you can post a question and answer your own question on StackOverflow).
