### ISSUE TITLE
Feature request: Enable ` in inline code blocks to be escaped

### ISSUE THREAD

**Issue by dondelelcaro** [rstudio/rmarkdown#1099]
It would be very nice for \` in inline code blocks to be escapable using \\\` or potentially using ``` ``r foo[,`bar baz`]`` ``` or one of the many other more complicated inline code escapes available and defined in markdown.

**Comment by dondelelcaro** [comment]
Actually, I think this is a knitr issue, not an rmarkdown. I'll raise it there; sorry for the noise.

**Comment by yihui** [comment]
I'm unlikely to support this in knitr. It will be a bottomless hole once I support a single backslash. Then users may ask how to write a literal string `` \` ``, and I'll have to start thinking about `` \\` ``... https://xkcd.com/1638/ I don't have the courage or capability to invent a proper parser in knitr for these cases.

Currently you have to avoid backticks in inline R expressions. Either rename your column names, or calculate the inline value in advance. Sorry for the inconvenience.

For ``foo[, `baz baz`]``, I think single/double quotes should work. I'm not aware of a case in which a backtick is unavoidable.

**Comment by dondelelcaro** [comment]
It's actually not that bad; changing the inline.code pattern to something like `` (`+)r[\\s#](.+?)\\1 `` and instead of pasting all capture groups together, allowing the code capture group to be specified would fix the problem completely.

I'll code up a patch which does this in knitr and file a pull request eventually.

**Comment by yihui** [comment]
Okay, thanks a lot!
