### ISSUE TITLE
Letting render accept text input?

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#110]
Is there a reason for this deviation from knitr? knit2html had a shortcut (the `text` argument) for knitting a text, instead of a file. There'd probably be ways to work around this (textConnection?), but why make it hard?

**Comment by yihui** [comment]
I doubt if we will ever implement this in **rmarkdown**. The tricky issue is that there are many things that rely on the input filename (e.g. figure/cache paths), and I don't what a proper filename is in this case. Anyway, if you don't care about these issues, the wrapper function is simple enough:

```r
render_text = function(text, ...) {
  f = tempfile('rmarkdown', '.', '.Rmd')
  on.exit(unlink(f), add = TRUE)
  writeLines(text, f)
  o = rmarkdown::render(f, ...)
  readLines(o)
}
```
