### ISSUE TITLE
ioslides logo sub directory not working 

### ISSUE THREAD

**Issue by adamrobinson361** [rstudio/rmarkdown#1101]
I am trying to add a logo in a styling sub directory in an r project using ioslides. 

If I have the file in the root directory everything works fine. Example as follows:

```r 
---
title: "Blank"
author: "Blank"
date: "Blank"
output:
  ioslides_presentation: 
  widescreen: true
  logo:  logo.png
---

##Blank slide
```

When I put the png in a sub folder the image no longer shows as a logo in the resulting ioslides presentation.

Example as follows:

```r
---
title: "Blank"
author: "Blank"
date: "Blank"
output:
  ioslides_presentation: 
  widescreen: true
  logo:  Styles/logo.png
---

##Blank slide

```

Is it not possible to add logo in subdirectory?

Thanks

Adam

**Comment by yihui** [comment]
I don't think we will be able to fix this issue. Please see https://github.com/rstudio/rmarkdown/issues/801#issuecomment-326624787. Thanks for the report anyway!
