### ISSUE TITLE
large files take long time to load even with cache =T

### ISSUE THREAD

**Issue by adeldaoud** [rstudio/rmarkdown#1103]
Hi, 

Large files take a long time to load even with cache =T. I am loading a large ~4 gb STATA file with haven package. I am setting using lazyloading because the STATA file will not load otherwise. It takes about 8 min to knit the markdown file, even when I did no changes to the file whatsoever. Any idea what is going on? Is the file not being cached?

````
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = T, message = FALSE)
```

```{r, cache.lazy = FALSE}
# load data
library(haven)
df.dhs <- read_stata("data.dta")
```
````

**Comment by yihui** [comment]
Lazy loading does not imply speed. It is only "lazy": do not load until the object is actually used. As long as you use `df.dhs` in a following chunk, the cached object has to be loaded anyway. You have to compare the speed to lazy-loading a `.rds` file with that of `read_stata()`. The former is not necessarily faster.

**Comment by adeldaoud** [comment]
a) ok. But does a lazy-load get cached still (when specifying cache=T, of course)?

b)
And, what is the explanation for the fact that the knitting still takes about 8 min to complete, even if I have not done any changes in the rmd file (and the document was previously cached)? In this case, should the knitting not be (almost) instantaneous? 

c)
Generally, what is your recommendation in dealing with large files (>2Gb) in R markdown?

d) 
do you have a guide to how to optimize a R markdown for speed (regardless of large or small files)?

Sorry for the many questions, but really like to speed up the knitting process. 

Thanks for your input

**Comment by yihui** [comment]
a) Yes.

b) I just realized you set `cache.lazy = FALSE`, which means you didn't use lazy-loading.

c) For big data, I recommend using databases instead of files. I'm not an expert in this area, but you may take a look at http://dplyr.tidyverse.org

d) In your case, the bottleneck is probably the data size, which I think is hard to optimize. In general, you may export all R code chunks (`knitr::purl()`) and use usual profiling tools to figure out the bottlenecks. My personal favorite is https://rstudio.github.io/profvis/

**Comment by adeldaoud** [comment]
b) yeh, you are right--my bad. 

c) dplyr does not help much in big data unfortunately. The data.table package is more promising: https://cran.r-project.org/web/packages/data.table/index.html


So R-markdown/knitr does not help with data-size issuse; it comes down to data preprocessing, maybe partly done outside of knitr in an external script. 

d) ok, will have a look. 

thanks
