### ISSUE TITLE
messages are printed even when message = FALSE

### ISSUE THREAD

**Issue by adeldaoud** [rstudio/rmarkdown#1104]
Hi

Messages are printed even when message = FALSE. The chunk below still prints the following in my pd knited file:
```

## [[1]]
## [1] TRUE
##
## [[2]]
## [1] TRUE
##
## [[3]]
## [1] TRUE
##
## [[4]]
## [1] TRUE
##
## [[5]]
## [1] TRUE
##
## [[6]]
## [1] TRUE
##
## [[7]]
## [1] TRUE
```

Any ideas what to do?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = T, message = FALSE)
```

```
# load packages
my.packages <- c("dplyr", "tidyr", "readxl", "ggplot2", "stringr", "countrycode", "haven")
lapply(my.packages, require, character.only = T)
```

**Comment by kevinushey** [comment]
What you're seeing here is the return value of `lapply()` being printed. If you want to suppress that, you need to use `include = FALSE` to disable inclusion of R outputs from that chunk in the generated document.

**Comment by adeldaoud** [comment]
Ok, I see. Can I control this behavior in the opts_chunk?

I have to now go through each chunk and set include =F.

**Comment by kevinushey** [comment]
Yes, you can set it in `opts_chunk()` but that would imply no R code output is shown for any chunks.

**Comment by adeldaoud** [comment]
ok, thanks.

**Comment by yihui** [comment]
These are not messages but text output. If you only want to suppress text output, you may use `results="hide"`. `include=FALSE` simply hides everything (including graphics and text output).https://yihui.name/knitr/options/

**Comment by adeldaoud** [comment]
great, that results="hide" is what I need. Thanks
