### ISSUE TITLE
Markdown inside HTML in RPresentation

### ISSUE THREAD

**Issue by dlukes** [rstudio/rmarkdown#1105]
I'm not quite sure whether this is an issue with RMarkdown because the RPresentation compilation process is fairly opaque (I couldn't find information on how to run it without using RStudio), but I assume the RMarkdown package is involved at some point :)

When knitting a regular R Markdown file in RStudio, the following...

```html
<div>
### Heading
</div>
```

... renders as...

```html
<div>
<h3>Heading</h3>
</div>
```

... which is probably what the user (well, me at least :) ) expects. By contrast, in R Presentation, this stub is rendered as ...

```html
<div>
### Heading
</div>
```

..., i.e. the inner Markdown isn't parsed and rendered.

Shouldn't the default be the same as for regular R Markdown files? If not, it would be great if there was at least an option for enabling this behavior on demand...

**Comment by dlukes** [comment]
It basically looks like the reverse of #2.

**Comment by jjallaire** [comment]
Unfortunately Rpres doesn't use rmarkdown (rather it uses the sundown markdown engine (essentially the same as that used by the legacy markdown package). 

Rpres was originally developed for the purpose of creating interactive tutorials that run within the IDE (so as you observed runs only within the IDE). Subsequently we created the rmarkdown package (which does a better job at presentations) and the learnr package (https://rstudio.github.io/learnr) which does a better job at interactive tutorials).  Rpres will never be removed from RStudio but it also pretty much deprecated as a result of these other packages.

**Comment by dlukes** [comment]
Oh, OK :) Thank you very much for taking the time to explain the context! I'll take the liberty of closing this then.
