### ISSUE TITLE
beamer_presentation type output does not pass any intermediates

### ISSUE THREAD

**Issue by longvaio** [rstudio/rmarkdown#1106]
The pdf_document type output ensures that intermediates (images) are copied, see: https://github.com/rstudio/rmarkdown/blob/master/R/pdf_document.R#L207-L223

Whereas beamer_presentation type output doesn't pass any intermediates, see: https://github.com/rstudio/rmarkdown/blob/master/R/beamer_presentation.R#L129-L139

Both types will rendering correctly in local.

But when try to publish a Rmd document with output type as beamer_presentation with picture/attachments to Rstudio-connect, since it does not pass the intermediates, on Rsutdio-connect server, when it try to rendering the document will complain about missing files.

sample testing code:
https://github.com/longvaio/beamer_bug
will fail to publish even we add the image file during the deployment:
![beamer_add_files](https://user-images.githubusercontent.com/15175450/28586672-962c8c32-7142-11e7-8959-d93a012da075.png)

and deploy log shows:
2017/07/25 14:09:35.731866490 /opt/rstudio-connect/ext/pandoc/pandoc +RTS -K512m -RTS /tmp/Rtmpyo64FL/beamer_presentation.utf8.md --to beamer --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /opt/rstudio-connect/mnt/report/beamer_presentation.pdf --template /tmp/Rtmpyo64FL/file1ce7a1df0977.tex --highlight-style tango --latex-engine pdflatex
2017/07/25 14:09:37.287504968 ! Package pdftex.def Error: File **`sample.jpg'** not found.
2017/07/25 14:09:37.287531254
2017/07/25 14:09:37.287541763 See the pdftex.def package documentation for explanation.
2017/07/25 14:09:37.287542971 Type  H <return>  for immediate help.
2017/07/25 14:09:37.287546479  ...
2017/07/25 14:09:37.287547465
2017/07/25 14:09:37.287550152 l.75 \end{frame}
2017/07/25 14:09:37.287550998
2017/07/25 14:09:37.287554226 pandoc: Error producing PDF

On the other hand, if we change the output type from beamer_presentation to pdf_document, everything works.

Thanks for your help.
Sincerely,
John

**Comment by jjallaire** [comment]
@jmcphers It looks like this part of the original commit:

https://github.com/rstudio/rmarkdown/commit/eed788ee8f275d7e31aa03c7349c27c53665d8c2#diff-b3656b1448a6664365941a3081112c04

Also needs to be done for the beamer_presentation format.

**Comment by jmcphers** [comment]
Got it, I'll take a look at this soon.

**Comment by jjallaire** [comment]
Great, thanks!
