### ISSUE TITLE
Hyperlinks in ioslides presentation on iOS devices not working

### ISSUE THREAD

**Issue by bsarbe** [rstudio/rmarkdown#1108]
I've noticed that hyperlinks created in an ioslides presentation with R Markdown are not clickable on iOS devices (iOS v10.3.1) using either Safari or Chrome.  When displaying on a laptop/PC, the links work fine, and Markdown is rendering the links appropriately in the .html file:

`<a href='https://www.rstudio.com' title=''>R Studio</a>`

Any insights would be appreciated---I've searched for the error and haven't come up with any solutions as to whether this is an iOS problem or not.  For what it's worth, slides created with reveal.js do not have the same problem.

**Comment by jjallaire** [comment]
@yihui Could you take a look at this?

**Comment by yihui** [comment]
I can reproduce it the problem on my iPhone, but I have no idea why links are not clickable there.

**Comment by bsarbe** [comment]
It's genuinely strange!  I get the same problem suing Safari and Chrome on any iOS device.  So far I haven't been able to make sense of why it's happening.

**Comment by yihui** [comment]
I don't think we will be able to fix this issue. Please see https://github.com/rstudio/rmarkdown/issues/801#issuecomment-326624787. Thanks for the report anyway!
