### ISSUE TITLE
Set knitr figure device `dev` by output type?

### ISSUE THREAD

**Issue by cboettig** [rstudio/rmarkdown#111]
In addition to setting things like `fig.width` and `fig.height` by output type (e.g. pdf, html) in the rmarkdown yaml, it would be great to be able to set a global `dev` option. For instance, I usually want this to `pdf` in pdf/latex outputs but `svg` or `png` in html outputs. Before `rmarkdown` I've always relied on writing a custom script to set these chunk options before calling `knit`, but it would be more tidy to have this in the header.  

Thanks for considering!

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/d66a5e6c1b5a98774d499bf6162c1be98b4388b4
