### ISSUE TITLE
theme not available for html_vignette

### ISSUE THREAD

**Issue by ThierryO** [rstudio/rmarkdown#1110]
Below is a minimal example. The `html_document` compiles. The `html_vignette` returns an error: `formal argument "theme" matched by multiple actual arguments`. 

    ---
    output: 
      html_vignette:
        theme: "readable"
      html_document:
        theme: "readable"
    ---
    
    ## R Markdown

**Comment by jjallaire** [comment]
That's correct, themes are not supported for html_vignettes (that's part of
the notion of the html_vignette templates is that by having a more
lightweight theme smaller html files are generated).

**Comment by ThierryO** [comment]
Then I would suggest to update the help file of `html_vignette`. It currently reads `... | Additional arguments passed to html_document`. And maybe ignore the `theme` (with a warning).

**Comment by yihui** [comment]
@ThierryO That is a good suggestion. We will do it, unless you want to submit a pull request :)
