### ISSUE TITLE
tabbed content in  html file did  not change.

### ISSUE THREAD

**Issue by Bryant-zhu** [rstudio/rmarkdown#1111]
Hi there
  I am currently trying to build up a daily HTML report through markdown.
there is one problem that quite bothers me.
   I designed two different tabbed section two show two different plot.
ie 

`##CTR{.tabset .tabset-fade .tabset-pills}`
`###tab1`
 `plot1`
`###tab 2 `
  `plot2 `
 
 
**the problem is:
while  I click the tab 1, it successfully showed plot1,
   but then click for tab2, the plot2  is not shown (looks like the page is not refreshed ).** 

can any one help? thx

**Comment by jjallaire** [comment]
This was a bug a few versions ago in R Markdown. Are you running the latest version?

This code works correctly for me:

    ---
    title: "Plot Tabs"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    ```
    
    ## CTR {.tabset .tabset-fade .tabset-pills}
    
    ###tab1
    
    ```{r}
    plot(cars)
    ```
    
    ###tab 2
    
    ```{r}
    plot(pressure)
    ```
    
If updating doesn't fix the issue for you please post a complete minimally reproducible example of the problem and we'll investigate further.

**Comment by Bryant-zhu** [comment]
thanks a lot,    seems like it worked temporaryly after I updated my rmd packages!
   But here come another annoying things, for the title I used for each tab, it would not work unless I add space between words, did you have any idea why would that happen? 
     ie: if I type "tapped1" it might not work, I have to type "tab 1" in order to let the tabbed pill show correctly in my HTML file.

**Comment by bschneidr** [comment]
@Bryant-zhu 
Could you post an entire R Markdown example that can be used to recreate your new issue?

For instance, something like the following? (This, by the way, doesn't give me any issue)

```
    ---
    title: "Plot Tabs"
    output: html_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    ``` 
  
    ## CTR {.tabset .tabset-fade .tabset-pills}
  
    ###tab1
  
    ```{r}
    plot(cars)
    ```
  
    ### tab 2
  
    ```{r}
    plot(pressure)
    ```

**Comment by yihui** [comment]
Closing, and waiting for a reproducible example from the OP. (And thanks, @bschneidr!)
