### ISSUE TITLE
BibTeX error when `citation_package` is set for documents without citations

### ISSUE THREAD

**Issue by aoles** [rstudio/rmarkdown#1113]
Hi,
I've run into the following issue when attempting to build a PDF document with a format function which uses `citation_package = "natbib"`. 

**test.Rmd**
```markdown
---
title: "natbib issue"
author: "Andrzej Oleś"
output: function(...) output_format(NULL, NULL, base_format=pdf_document(..., citation_package="natbib"))
---

Test file to illustrate `citation_package` argument issue.
```
The PDF builds, but BibTeX gives an error.
```r
render("test.Rmd")
```
```
This is BibTeX, Version 0.99d (TeX Live 2013/dev)
The top-level auxiliary file: test.aux
The style file: plainnat.bst
I found no \citation commands---while reading file test.aux
I found no \bibdata command---while reading file test.aux
(There were 2 error messages)
```

In particular, this issue affects all of the *rticles* formats which use natbib as their default `citation_package`.

I believe the problem is caused by the fact that even though there are no actual citations in the document, BibTeX is called in an attempt of resolving them. It seems that this could be addressed by including the pandoc argument `--natbib` only when there are any citations in the document, or at least when there is a `bibliography` defined in the document metadata header. What do you think?

Cheers,
Andrzej

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by aoles** [comment]
Awesome, many thanks @yihui for fixing this!
