### ISSUE TITLE
rmarkdown::find_pandoc does not work correctly on shiny-server

### ISSUE THREAD

**Issue by dcellis1950** [rstudio/rmarkdown#1114]
In the rmarkdowm library, pandoc.R file, function find_pandoc  if the .pandoc$dir is null, the following code does not work correctly. The problem is that sources is a vector with three objects. The embedded function 
 versions <- lapply(sources, function(src) {
      if (dir_exists(src))
        get_pandoc_version(src)
      else
        numeric_version("0")
    })
does not return the expected results. dir_exists only checks the first object in the vector, which is "" in shiny-server. To make this work  you can set RSTUDIO_PANDOC environment variable to dirname(which(pandoc)), but that is a kluge and can cause other problems

The error reported in /var/log/shiny-server/ is
    60: system
    59: force
    58: with_pandoc_safe_environment
    57: get_pandoc_version
    56: FUN
    55: lapply
    54: find_pandoc
    53: pandoc_available
    52: htmlwidgets::saveWidget
    51: plotsToFile [/srv/shiny-server/test/XXXXXX/server.R#1312]
  
The problem is that sources is a vector with three objects. The embedded function 

Shiny-server running on a Fedora 25 (4.11.12-200.fc25.x86_64)

**Comment by jjallaire** [comment]
I don't clearly understand the issue report. Shiny Server does set the RSTUDIO_PANDOC environment variable already and as far as I know we have no reports of it not working there (and it's been serving interactive Rmds for years). 

@jcheng5

**Comment by dcellis1950** [comment]
You are correct that shiny-server set the RSTUDIO_PANDOC to /usr/local/shiny-server/ext/pandoc, but unfortunately the pandoc executable is in /usr/local/shiny-server/ext/pandoc/static. This does not mean that there isn't a bug in find_pandoc.

**Comment by jjallaire** [comment]
@jcheng5 It looks like in some configurations RSTUDIO_PANDOC isn't set correctly.

**Comment by jcheng5** [comment]
@dcellis1950 There are supposed to be pandoc executables in both `/usr/local/shiny-server/ext/pandoc/` and `/usr/local/shiny-server/ext/pandoc/static/`, the latter copy shouldn't be relevant for Fedora 25.

And if `sources` is a vector then `lapply` should run the function on each of the elements individually.

If you're still encountering this problem, can you provide more of the error?
