### ISSUE TITLE
issues running code in chunks in vignettes since updating to RStudio 1.1

### ISSUE THREAD

**Issue by EllaKaye** [rstudio/rmarkdown#1119]
Hello. Since updating to RStudio 1.1, some of the behaviour of code chunks in vignettes has changed. 

Within a code chunk in a vignette, pressing Cmd+Enter on a line in a chunk no longer runs it (similarly pressing Cmd+Enter from anywhere in a pipe). It only runs if highlighted first.

Also, typing the name of a data frame followed by the pipe operator then Enter no longer automatically indents the next line. 

Both of those behaviours still happen in R scripts, and in other .Rmd documents, just not in vignettes. The output doesn't seem to make a difference (I've tried rmarkdown::html_vignette, rmarkdown::html_document and bookdown::html_document2).

Removing the lines
```
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
```
from the yaml fixes the issue, but of course creates the issue of then not building the vignette! I'm using devtools::use_vignettes() to generate the vignette template.

I'm running RStudio 1.1.336, R 3.4.1, rmarkdown 1.6, knitr 1.16, macOS 10.12.5

**Comment by jjallaire** [comment]
@jmcphers @kevinushey

**Comment by kevinushey** [comment]
This should be fixed in the latest daily builds of RStudio (since v1.1.338). You can download the latest build here:

https://dailies.rstudio.com/

and we should be bumping the preview release version as well. Thanks for reporting!

**Comment by jmcphers** [comment]
Just bumped the preview to 1.1.338.

**Comment by EllaKaye** [comment]
Brilliant! Thanks for getting onto that and fixing it so fast. It's working fine my end now.
