### ISSUE TITLE
Insert html plotly files to an rmarkdown html report

### ISSUE THREAD

**Issue by ndrubins** [rstudio/rmarkdown#1122]
Hi,

Suppose I created several figures, both `ggplot2` `png` figures and `plotly` `html` figures:
```

library(plotly)
library(ggplot2)
library(reshape2)

p <- plot_ly(z = volcano, type = "heatmap")
htmlwidgets::saveWidget(p,"p.html")

df <- reshape2::melt(volcano)
d <- ggplot(df,aes(value))+geom_histogram()
ggsave(d,filename = "d.png")

s <- ggplot(df,aes(x=Var1,y=Var2))+geom_point()
ggsave(s,filename = "s.png")

```

My `rmarkdown` code then tries to insert them:

```{r.setup, include=FALSE,echo=FALSE}
library(knitr)

knitr::opts_chunk$set(echo=FALSE,out.width='1000px',dpi=200,fig.keep="all")
options(width = 1000)
options(knitr.table.format = "html")
```

```
---
title: "test"
output: html_document
---
```

```{r insert.ggplot1, echo=FALSE}
knitr::include_graphics("d.png")
```

```{r insert.plotly, echo=FALSE}
htmltools::includeHTML("p.html")
```

```{r insert.ggplot2, echo=FALSE}
knitr::include_graphics("s.png")
```

In the output `html` page I only see the `p.html` figure taking over the entire page rather than appearing between `d.png` and `s.png`.

So my question is what's the proper way to insert an `html` figure.

In addition, suppose I generated and saved a list of `plotly` figures, outside the `rmarkdown` code, for example:

```
for(i in 1:3){
  pi <- plot_ly(z = volcano, type = "heatmap")
  htmlwidgets::saveWidget(pi,paste0("p.",i,".html"))
}

```

and I'd like to loop over them and insert them in the `rmarkdown` code. I know that if I'd generated them in the `rmarkdown` code I'd use `htmltools::tagList`, something like this:

```
plot.list <- vector(mode="list",3)
for(i in 1:3) plot.list[[i]] <- plot_ly(z = volcano, type = "heatmap")
htmltools::tagList(plot.list)

```

But I don't know how to import them. Any idea how to handle that?

**Comment by yihui** [comment]
This is a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead and let us know the link if you don't get an answer in a few days. Thanks!
