### ISSUE TITLE
Slidy presentations and different display math output

### ISSUE THREAD

**Issue by jar1karp** [rstudio/rmarkdown#1123]
How to reproduce: create a new Rmarkdown Slidy presentation with the following content:

```
## Title

This is rendered as paragraph:
$$
\exp\left(-\sum_{i=1}^{N} p_i \log p_i\right)
$$

This is not:
\begin{align*}
\exp\left(-\sum_{i=1}^{N} p_i \log p_i\right)
\end{align*}

Test:
$$
x+y+z
$$
```

Then knit to HTML. When previewing the slide, the first and third paragraphs (with $$...$$ display math) has some left indentation, but the second paragraph (with \begin{align*}...\end{align*} display math) doesn't.

Looking at the generated HTML source it seems that this is because the second paragraph is missing the enclosing `<p>` and `</p>` tags:

```
<div id="title" class="slide section level2">
<h2>Title</h2>
<p>This is rendered as paragraph: <span class="math display">\[
\exp\left(-\sum_{i=1}^{N} p_i \log p_i\right)
\]</span></p>
This is not:
<span class="math display">\[\begin{align*}
\exp\left(-\sum_{i=1}^{N} p_i \log p_i\right)
\end{align*}\]</span>
<p>Test: <span class="math display">\[
x+y+z
\]</span></p>
</div>
```

It's quite minor but visually bothersome. The `align*` environment is occasionally necessary for e.g. multiple equations.

**Comment by yihui** [comment]
If you need `This is not:` to be in a separate paragraph, you need to add an empty line after it, e.g.

```
This is not:

\begin{align*}
\exp\left(-\sum_{i=1}^{N} p_i \log p_i\right)
\end{align*}
```

If you don't want to add an empty line, you will need to report this issue to Pandoc: https://github.com/jgm/pandoc/issues I have prepared a minimal reproducible example for you to file the issue there:

Command:

```
pandoc -f markdown -t html --mathjax
```

Paste the Markdown input:

```
## Title

This is rendered as paragraph:
$$1$$

This is not:
\begin{align*}
1
\end{align*}

```

`Ctrl + D` and the output is:

```html
<h2 id="title">Title</h2>
<p>This is rendered as paragraph: <span class="math display">\[1\]</span></p>
This is not:
<span class="math display">\[\begin{align*}
1
\end{align*}\]</span>
```
