### ISSUE TITLE
Notebook preview has missing code chunk if not whole chunk is executed 

### ISSUE THREAD

**Issue by linda-kr** [rstudio/rmarkdown#1132]
Hello,

When I open the standard R Notebook in R Studio (Version 1.0.153) (with the `plot(cars)` example) and look at the htlm Preview, I had an interesting observation.

1. If do not execute anything, I get an htlm with the code chunk for `plot(cars)`. As expected.
2. If I execute the whole chunk which only contains the the `plot(cars)` code line, I get an html with code chunk and figure. As expected.
3. If I execute only the line in the chunk where `plot(cars)` is written, I get an htlm with the figure but no code! That is confusing to me. Why is that the case?

I played around a little bit and found out that if you use `print("a")` instead of `plot(cars)` the above described point 3. behaves like 2. So I see both code and print result regardless of whether I execute the whole chunk or only the line containing the command.

Maybe there is a good reason for this behaviour which I do not understand. I just wanted to let you know my observation.

**Comment by yihui** [comment]
I'm not sure if that was by design or not. Cc @jmcphers

**Comment by jmcphers** [comment]
If you don't execute all the lines of chunk, you aren't going to see fully consistent output, but it sounds like you're seeing a bug in RStudio if not all the code is making it through. I'll file a case on our end; this is probably an issue in RStudio, not rmarkdown.
