### ISSUE TITLE
Addition of horizontal line removes controls from following chunk

### ISSUE THREAD

**Issue by pssguy** [rstudio/rmarkdown#1133]
![horizontal](https://user-images.githubusercontent.com/2775918/29950630-f5e98188-8e71-11e7-9e34-3fd74aced585.png)

Going to 4 returns the controls and using asterisks does not appear to have same issue
Windows 10 
RStudio 1.1.353

**Comment by yihui** [comment]
Thanks for the report. This is an RStudio IDE issue. Cc @kevinushey @jmcphers. Reproducible example below:

````
---

```{r}
summary(cars)
```
````

Without `---`:

![image](https://user-images.githubusercontent.com/163582/29954606-c64b5b90-8e9e-11e7-8640-a4b23cd9d501.png)

With `---` (the toolbar of the code chunk is gone):

![image](https://user-images.githubusercontent.com/163582/29954613-d58be142-8e9e-11e7-96d1-3906d9a3bed4.png)

**Comment by kevinushey** [comment]
I believe this is because RStudio sees the `---` and treats it as the beginning of a YAML header (even though it doesn't occur at the start of the document). I'll take a look!

**Comment by pssguy** [comment]
@kevinushey @yihui Thanks. Just to add that this is a relatively recent issue in RStudio

**Comment by yihui** [comment]
@kevinushey I updated the minimal reproducible example above to include an actual YAML header, and the problem still persists.

**Comment by kevinushey** [comment]
Yes, the issue here is that RStudio currently allows a YAML block to appear _anywhere_ in the document (and multiple blocks are permitted). I'll fix this up.

**Comment by yihui** [comment]
I see. Thanks Kevin!
