### ISSUE TITLE
Add options for making handouts from beamer slides

### ISSUE THREAD

**Issue by Kenkleinman** [rstudio/rmarkdown#1134]
I'd like to add LaTeX options for making 6-up handouts from beamer slides.  This involves changing options in the \documentclass and adding a large block of text to the preamble.

Can someone give some suggestions about the best way to go about making these additions?

**Comment by jjallaire** [comment]
Here's the beamer template: https://github.com/jgm/pandoc-templates/blob/master/default.beamer

You can add arbitrary document class options with the `classoption` YAML option.

You can inject LaTeX into the document headers using the `includes > in_header` YAML option.

**Comment by Kenkleinman** [comment]
Thanks, JJ.  I wasn't aware off the classoption YAML.  I forked the repos.  Suppose I wanted to permanently bundle the header material into the package, would includes > in_header > location/filename still be the right/best way to do that?  And what location would I select?

**Comment by jjallaire** [comment]
I would just make a new R Markdown template which has the classoption and
in_header that you want:
http://rmarkdown.rstudio.com/developer_document_templates.html

**Comment by Kenkleinman** [comment]
Aha, perfect.  I had been thinking about making these options via YAML, for others, but a separate temple would definitely be easier.  Thanks!
