### ISSUE TITLE
Convert R markdown file to normal R script

### ISSUE THREAD

**Issue by Mark-Tepeck** [rstudio/rmarkdown#1135]
There is some code online to do this. However, is there any official built-in function for that?
Sometimes, it is easy to pass the raw R script to a collaborator who has no concept of R markdown.

**Comment by yihui** [comment]
This is a question. Could you do us a favor to ask it on StackOverflow first (using the tags `r`, `rmarkdown`, and `knitr`)? http://stackoverflow.com/questions/ask That way, you may not need to wait for us to answer it. Thanks!

**Comment by sibojan** [comment]
I can help to put it on StackOverflow first.

**Comment by sibojan** [comment]
Hi Yihui,

I found a code online to perform that function. [http://rstudio-pubs-static.s3.amazonaws.com/12734_0a38887f19a34d92b7311a2c9cb15022.html](url) 

That might be incorporated into the rmarkdown package one day.

**Comment by yihui** [comment]
@isteves Thanks!

**Comment by sibojan** [comment]
@isteves Thank you so much.

**Comment by dcassol** [comment]
Hi @yihui and @sibojan9, 
do you have any tips about how to extract only a specific chunk of code?
Let's say I have three chunks of code with a tag="step1", and I only need these three parts on the .R file. Is it possible?
Thank you very much!

**Comment by yihui** [comment]
@dcassol Mark the chunks that you don't want to export with the chunk option `purl = FALSE`. If that is not flexible enough, `knitr::knit_code$get()` inside a code chunk will give you the list of all code chunks, and you can filter this list by yourself programmatically. Again, for general questions, please follow the issue guide to ask them elsewhere to reduce the burden of maintainers and benefit a wider community: https://github.com/rstudio/rmarkdown/issues/new Thanks!
