### ISSUE TITLE
post_processor not working

### ISSUE THREAD

**Issue by ThierryO** [rstudio/rmarkdown#1138]
I'm trying to write a post_processor() for a custom rmarkdown format. The
goal of the post_processor() is to modify the latex file before it is
compiled. For some reason the post_processor() is not run. The
post_processor() does work when I run it manually on the tex file.

More details in [this thread on R-help](https://stat.ethz.ch/pipermail/r-help/2017-September/448990.html). The code is available at https://github.com/inbo/INBOmd/tree/post_processor

**Comment by dmurdoch** [comment]
I did some debugging, and found that the issue was in rmarkdown::render.  If Bibtex is needed, it runs Latexmk before the post-processor.  Thierry's problem was that this step failed, because the LaTeX code needed some fixups by the post-processor before it was valid.

**Comment by ThierryO** [comment]
@dmurdoch  suggested on R-help to add a dummy command in tex for `\EndFirstPage`. That solves part of the problem. That is: `post_processor()` runs.

Now I get warnings about the locale. I've traced the problem: the value `output_file` is set to `skeleton.pdf` instead of `skeleton.tex`

```
Warning messages:
1: In grep("^\\\\EndFirstPage", text) :
  input string 2 is invalid in this locale
```

**Comment by dmurdoch** [comment]
The `output_file` is `skeleton.pdf` because you're not specifying the `ext` parameter.  Just add `ext = ".tex"` to your `pandoc_options()` call and you should get what you are looking for (but no `.pdf` file will be produced; that will need to be done separately).

**Comment by ThierryO** [comment]
I solved it by using `bookdown` instead of only `rmarkdown`

bookdown YAML, outfile for `post_processor()` = .tex

```
---
output: 
  bookdown::pdf_book:
    base_format: INBOmd::rsos_article
---
```

rmarkdown YAML: outfile for `post_processor()` = .pdf, hence it fails

```
---
output: 
  INBOmd::rsos_article
---
```
