### ISSUE TITLE
default to svglite for html outputs

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#1141]
Would it be possible to default to `dev = 'svglite'` for HTML documents?

Plots via `svglite` in HTML output just look so much better, and this would be one less thing for the average user to think about, set up (which, of course, can be done already). Upstream tools such as `bookdown` could also inherit this default behavior.

On the downside, `svglite` would be another dependency (and also has system dependencies via `gdtools`, I think).

Perhaps `rmarkdown` could default to `"svglite"` whenever `require("svglite")`, and else to `"png"`, that way, `rmarkdown` would always produce something.

Or would that be too clever by half?

Would be happy to put together a PR to this effect, but I'm not knowledgeable enough to judge whether this would be a good idea to begin with.

**Comment by yihui** [comment]
I'm against the idea of using svglite as the default device. Reasons:

1. As you said, it introduced two new dependencies (we have already got a lot of dependencies).

1. Vector graphics and bitmap both have their advantages and disadvantages. For example, when there are too many graphical elements (such as a scatterplot with too many points), an SVG file may be huge.

1. I don't think `require('svglite')` is a good idea. It may surprise users that sometimes they get `svg` and sometimes they get `png`.

1. Changing the graphical device is easy enough for individual R Markdown documents. If you want to change it globally (not a good idea), you can set `options(knitr.chunk.dev = 'svglite')` (you can set it even in `.Rprofile`).

**Comment by maxheld83** [comment]
thanks @yihui!
