### ISSUE TITLE
pandoc_args behaves different for HTML and PDF

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/rmarkdown#1142]
When I used

~~~
output:
  pdf_document:
   pandoc_args: [
     "--data-dir", "_pandoc",
     "--template", "apa6.tex",
     "--output", "apa6.pdf"
   ]
~~~

on the YAML header of my document and run Knit, the log shows

~~~
usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS paper.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output paper.pdf --template /home/raniere/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --data-dir _pandoc --template apa6.tex --output apa6.pdf --variable 'geometry:margin=1in' 
~~~

Note that my `--template` option is after the default one which means that Pandoc is going to use the option that I provided.

When I used

~~~
output:
  html_document:
    pandoc_args: [
      "--data-dir", "_pandoc",
      "--template", "university-of-manchester.html",
      "--output", "paper.html"
    ]
~~~

on the YAML header and run Knit, the log shows

~~~
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS paper.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output paper.html --smart --email-obfuscation none --self-contained --data-dir _pandoc --template university-of-manchester.html --output paper.html --standalone --section-divs --template /home/raniere/R/x86_64-pc-linux-gnu-library/3.4/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpICieib/rmarkdown-str22be582057ea.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
~~~

Now, my `--template` option is behind the default one which means that Pandoc is **not** going to use the option that I provided.

**I know that I should use the [template option](http://rmarkdown.rstudio.com/html_document_format.html#custom_templates) as explained in the documentation but would be great if always the `pandoc_args` were at the end of the Pandoc call.**

**Comment by yihui** [comment]
I'm not sure if there are any unexpected consequences of changing the order of `pandoc_args`, so I tend not touch it, especially given that this particular issue you reported has a clear solution as you mentioned. Thanks for the report anyway!
