### ISSUE TITLE
PDF document - Specifying a language for table of contents changes bullets type

### ISSUE THREAD

**Issue by stephLH** [rstudio/rmarkdown#1145]
I write an article in French and I specify the `lang` parameter to `fr` to have the table of contents in French.

I noticed that specifying the language changes the bullets used in the article (nested bullets).

For example in English (without the `lang` parameter), the nested bullets are different :
```
---
title: "Title"
output:
  pdf_document:
    toc: true
---

\newpage

# Section 1

* temp
    + test
* temp2
    + test2
    + test3
```

In French, all the bullets are the same (the main one) :
```
---
title: "Titre"
lang: fr
output:
  pdf_document:
    toc: true
---

\newpage

# Section 1

* temp
    + test
* temp2
    + test2
    + test3
```

**Comment by yihui** [comment]
That is a LaTeX issue. Have you tried to ask on StackOverflow or TeX.SE?

**Comment by stephLH** [comment]
Ok, I'll try there.
