### ISSUE TITLE
How to specifiy the name of the output file when using render_site ?

### ISSUE THREAD

**Issue by kezhan** [rstudio/rmarkdown#1146]
With render, we can specify the name of the output file. But it seems that it is not the case. Is there a way to do this ?

In fact I try to create a loop to render_site, by specifying different names for the output files. Another way can be: a loop to create rmd files, with different names, then I can render_site each rmd file.

Thank you for your help.

**Comment by yihui** [comment]
The output of `render_site()` is typically a directory specified by `output_dir` in `_site.yml`. One way to achieve your goal is to render to the default directory, and use `file.rename()` to move it to your desired directory.

If you need further help, please consider [posting this question on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead. Thanks!
