### ISSUE TITLE
No blank lines created after HTML tags, which breaks CommonMark rendering

### ISSUE THREAD

**Issue by daattali** [rstudio/rmarkdown#1148]
Using `rmarkdown::render(..., output_format = "md_document")` causes any HTML tags to not have blank lines after them, even if they do in the source. This in turn means that according to CommonMark specs, the following lines will not be rendered as markdown.

Example:

This Rmd source

```
<h1>foo</h1>    


**bar**
```

Generates this md output

```
<h1>
foo
</h1>
**bar**
```

(I'm doing this so that I can add an `id` attribute to the tag). This is undesirable because bar would no longer be rendered as bold, but instead it will just show the two asterisks. There should be a blank line before `**bar**`

Reference: http://spec.commonmark.org/0.28/#html-blocks

Proof of how this looks broken on github:

![image](https://user-images.githubusercontent.com/952340/30890890-ae7acb7c-a2fd-11e7-8063-b582e5e1aeef.png)

**Comment by yihui** [comment]
This looks like a Pandoc issue. The rmarkdown package won't touch these blank lines. You can probably try to minimize the example to isolate rmarkdown and present a pure Pandoc example to the Pandoc developers (I don't have time to help you do this at the moment).

**Comment by daattali** [comment]
If you're sure it's pandoc, then feel free to close this issue. I'll take your word for it (I haven't used pandoc directly before and also don't have much time atm to look into this)

If you have a suggestion of how to add an ID to a header in a markdown document in a different way, I'd love to know

**Comment by yihui** [comment]
The (Pando'sc Markdown) syntax for ID is `# Section Title {#your-custom-id}`, but of course, the `id` attribute does not make sense if the output is Markdown, since Markdown (whatever flavor it is) does not have the syntax for the `id` attribute of any HTML elements, unless you use raw HTML tags.

BTW, I'm constantly surprised how frequently you and @jennybc use the `md_document` output format (I have never used it myself). Specifically, I'm always surprised that you want to rely on Github to render Markdown for you. IMHO you should not expect too much from Github. At best it is a toy renderer, even though [it has tried to follow the CommonMark specs](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown). There is still a big gap between CommonMark and Pandoc. If you are serious about how the output looks like or any slightly advanced features, I'd suggest you render Rmd to real HTML. Before blogdown was finished, I didn't have the confidence to say this, but with blogdown (+Netlify), I don't think you have any strong excuses :)

**Comment by daattali** [comment]
I'm also surprised to hear that @jennybc uses md_document, seeing as she's the one who created the github one!

I do see daily tweets raving about blogdown :) But my usecase here is for the package README on github so I don't think it applies. That's why I'm sticking with markdown. And the reason I don't want to use the github document format is because I want to make sure it'll render fine in any other place that also renders that README.md file, such as CRAN, rdocumentation, etc.

Unfortunately, for github the `{#id}` thing doesn't work, that's why I reverted to the ugly HTML tags, which worked fine up until github decided to change to commonmark. 

I hope that's an ok excuse!

**Comment by yihui** [comment]
Sure!

For me, I never write anything that Github cannot render in README, and I'll put these things on the project website of the repo.

**Comment by jennybc** [comment]
To explain (defend?) myself, I am usually facilitating a workflow that helps [students share code-heavy coursework on GitHub](https://ubc-mds.github.io/2017-08-24-teaching-with-github/), where we need decent-looking markdown. We created *thousands* of (private) repos full of R and Python code this year in our data science program. GitHub Enterprise allows our students to authenticate with their university credentials and we have unlimited private repos. We're not going to create and host 5,000 password-protected websites.

Or I'm maintaining reprex, who sole purpose is to create little bits of markdown to be posted on GitHub, like this very thread we are talking in here 🙂. So blogdown and netlify don't solve these use cases.

**Comment by jennybc** [comment]
In fact, I think I may have another report of this same phenomenon on reprex as well (the lack of space between an html table and an R chunk, in this case): https://github.com/tidyverse/reprex/issues/77#issuecomment-304315814

**Comment by daattali** [comment]
Haven't looked into it much but from his comment "I believe the reprex function is inserting an extra line break between the code and the HTML rendered" it seems like it's the opposite problem of having TOO much space vs me wanting an extra blank line? Maybe you're right and I needed to skim it more carefully.

**Comment by jennybc** [comment]
No, you're correct @daattali. I think OP just mis-spoke/mis-typed. It *needs* an extra line inserted after the HTML table, which the annotated screenshot makes more clear.

**Comment by daattali** [comment]
Oh you're right (which means I was not correct...?), in the first
screenshot I see what you mean, an extra line needs to be inserted. So yes
your issue might also be attributed to pandoc. Not the reason Yihui
summoned you here, but glad you made that link - maybe the more rstudio
packages this affects, the more likely someone is to reproduce in pandoc
and report it :)

On Sep 27, 2017 01:41, "Jennifer (Jenny) Bryan" <notifications@github.com>
wrote:

No, you're correct @daattali <https://github.com/daattali>. I think OP just
mis-spoke/mis-typed. It *needs* an extra line inserted after the HTML
table, which the annotated screenshot makes more clear.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rstudio/rmarkdown/issues/1148#issuecomment-332414676>,
or mute the thread

**Comment by jennybc** [comment]
If this the content of `test.md`:

```md
<h1>foo</h1>    


**bar**
```

and you do: `pandoc -s test.md -t markdown -o test-out.md`

here is the content of `test-out.md`

```md
<h1>
foo
</h1>
**bar**
```

so, yeah, it recreates exactly your problem.

**Comment by daattali** [comment]
Thanks, I had in my TODO to lookup the syntax for a simple pandoc statement, you saved me 5 minutes. I'll report the issue

**Comment by daattali** [comment]
Hm I'm not sure if I should report this as an issue for pandoc because if I use `-t commonmark` (which is what github uses) then it does insert the line after the html tag.

I don't know if I'd still consider it their bug then.

If there's a simple way to tell `rmarkdown::render()` to use the `-t commonmark` option then I'd be happy

**Comment by jennybc** [comment]
This YAML seems very promising:

``` yaml
---
output:
 md_document:
   variant: markdown
   pandoc_args: [
     "-t", "commonmark"
   ]
---
```

**Comment by yihui** [comment]
I'm fine with Github's Markdown renderer as long as the Markdown text is simple enough, e.g. no HTML tags, no LaTeX math, and no citations, etc. So yes, for reprex, Github's Markdown is good because the reprex output is simple in terms of Markdown syntax (contains only fenced code blocks and images). All I meant was that there was a line, and when you are going to cross this line, you should no longer rely on Github's Markdown. I feel you are likely to cross this line very often, and that is why I don't recommend Github's Markdown in general. Of course, this doesn't make sense if my assumption is wrong (i.e. you can keep your Markdown simple most of time).

**Comment by daattali** [comment]
@jennybc thanks, that actually works! Do you know the `rmarkdown::render()` syntax to include those parameters in the function call instead of in the YAML? I tried

```
rmarkdown::render("test.Rmd", output_format = "md_document", params = list("pandoc_args" = c("-t", "commonmark")))
```

which is very obviously wrong. I'm embarrassed to ask, but what's the correct syntax?

**Comment by jennybc** [comment]
I'm not sure. This example from [another thread](https://github.com/rstudio/rmarkdown/issues/409#issuecomment-87254832) seems relevant:

```r
rmarkdown::render("~/Desktop/foo.Rmd", 
   output_options = list(pandoc_args = c("--metadata=title:\"foo\""))
)
```

but there don't seem to be many examples of passing pandoc args to `render()`.

**Comment by daattali** [comment]
Thanks @jennybc ! That really helped. Solved it with

```
rmarkdown::render(
  "foo.Rmd",
  output_format = "md_document",
  output_options = list(pandoc_args = c("-t", "commonmark")))
```
