### ISSUE TITLE
Rmd partials, best practice

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#1152]
I'm working on a package that generates rmarkdown codebooks for surveys.
To do so, I've made a couple of Rmd partials (e.g. for the survey description, for summarising an item). Basically, one calls the `codebook` function and my partials summarise the data and plot graphs in a structured way.

I previously asked in the [printr package issues](https://github.com/yihui/printr/issues/28), what the best practice for supplying Rmd partials in a package is, but got no response, hence the follow-up.

Are there any best practice recommendations for doing such a thing or even any existing examples? I'm not sure how to write tests for the partials, where to store them in a package and how to make debugging easy for the end users. If there is no best practice recs, that's also useful information.

One thing I'm struggling with is that I would to set 

```r
options(knitr.duplicate.label = 'allow')
```

for the partial so that the repeated partials have meaningful chunk names. But I don't think I can do so at the package level.

Another thing that I'm struggling with is that these warnings are emitted

> Warning in in_dir(input_dir(), evaluate(code, envir = env, new_device =
> FALSE, : You changed the working directory to /Users/rubenarslan/Dropbox/
> vomstudiumindenberuf/data_cleaning_R/wave3 (probably via setwd()). It will
> be restored to /Library/Frameworks/R.framework/Versions/3.3/Resources/
> library/formr. See the Note section in ?knitr::knit

although I'm not setting any working directory explicitly.

**Comment by yihui** [comment]
Sorry I don't have any recommendations on best practice. 

You should be able to set `options(knitr.duplicate.label = 'allow')` before you include child Rmd documents.

I think the warning about the working directory can be safely ignored.

**Comment by rubenarslan** [comment]
Thanks. I'll try setting the option in the function that includes the Rmds. 
The warning is annoying though and I don't want users to turn off warnings in general. 
Any way to avoid triggering it, or suppress it?

**Comment by yihui** [comment]
Re: warnings, do you have a reproducible example (ideally minimal)?

**Comment by rubenarslan** [comment]
I'll whip one up tomorrow.

**Comment by rubenarslan** [comment]
Here's a reproducible example. It only happens when I nest more than one child call (but in the real example I might actually nest two or three times).
Also, I usually use this [helper function](https://github.com/rubenarslan/formr/blob/e9ed94a5a019824a4b5a36b78545e159fde6022e/R/rmarkdown_options.R#L247), so that nesting actually works as I intend it to, but for the purposes of showing the warning it's not necessarily.

	```{r}
	tempDir <- tempfile()
	dir.create(tempDir)
	child <- file.path(tempDir, "child.Rmd")
	cat("Yes\n", file=child)
	
	child2 <- file.path(tempDir, "child2.Rmd")
	cat(paste0("```{r}\nknitr::knit_child('",child,"')\n```\n"), file=child2)
	```
	
	
	## works
	```{r}
	knitr::knit_child(child)
	```
	
	## warns
	```{r}
	knitr::knit_child(child2)
	```

**Comment by rubenarslan** [comment]
Oh and just in case you're considering giving the knit child working directory code another look: Is there really a good reason `knit_child` cannot be called interactively? It sometimes would make development much easier.

**Comment by yihui** [comment]
I don't have time to investigate this issue at the moment, but I recommend you to always use relative paths instead of absolute paths. Both `child` and `child2` are absolute paths.

> Is there really a good reason knit_child cannot be called interactively? It sometimes would make development much easier.

You can certainly use `knit_child` _interactively_. You probably mean "using it outside `knit()`"? That won't make sense because a child is not meaningful without a parent. It was designed to be called inside a parent document.

**Comment by rubenarslan** [comment]
Relative paths: makes sense. I'm getting the paths to my partials via system.file though, so I don't quite know if I can make them relative.

Interactive: I guess my helper function could just decide whether to use `knit` or `knit_child` based on a call to `interactive()`. Sorry didn't think about this earlier.

**Comment by yihui** [comment]
Is it possible to `file.copy()` the child Rmd file from the installed package directory to the current directory?

**Comment by rubenarslan** [comment]
I guess it's possible, but it seems wrong and inelegant to mess with the user directory. There might end up being 10 such files and I need to avoid collisions.
I tried messing around with `R.utils::getRelativePath` for the `system.file` (and also in the , but depending on the approach it either doesn't work for nested files or yields the same warning.

The only solution I could come up with was reading the partial myself and passing it in as a text argument. What do you think about that? Unexpected downsides? It seems to work well with my present approach.

```r
asis_knit_child = function(input = NULL, text = NULL, ..., quiet = TRUE, options = NULL, envir = parent.frame()) {
	stopifnot( xor(is.null(text), is.null(input)))
	text = paste0(readLines(input), collapse = "\n")
	if (interactive()) {
		output = knitr::knit(text = text, ..., quiet = quiet, envir = envir)
	} else {
		output = knitr::knit_child(text = text, ..., quiet = quiet, options = options, envir = envir)
	}
	knitr::asis_output(output)
}
```

**Comment by yihui** [comment]
Yes, I think `knit_child(text)` is the only solution given your constraints.
