### ISSUE TITLE
Object not found error associated with render() using intermediates_dir argument

### ISSUE THREAD

**Issue by paulobrecht** [rstudio/rmarkdown#1154]
My use case: an R script, say driver.R, that calls `rmarkdown::render()` to render an .Rmd file into either pdf or html. I execute the driver by using `source("driver.R")`.

I want to conditionally execute chunks depending on whether certain conditions are true in the data, so within one chunk certain Booleans are defined, and later chunks use `eval` along with those Booleans to determine whether the chunk should be evaluated.

When I output to html_document or pdf_document, I get the following error, _but only when supplying an_ `intermediates_dir` _argument_.

```
Error in eval(x, envir = envir) : object 'runChunk1' not found
Error in eval(x, envir = envir) : object 'runChunk2' not found
```

It looks like some function called by`render()` to handle `intermediates_dir` scans the Rmd and looks at the `eval` arguments. But since it's not executing code in the chunks, the objects in later `eval` arguments are not found.

As far as MWE, here's a driver:

```
library(rmarkdown)

rmarkdown::render("process.Rmd",
  output_format="html_document",
  envir = topenv(),
  output_dir = "output_dir",
  intermediates_dir = "intermediates_dir",
  clean = FALSE
)
```

and here's a process.Rmd:

````
---
title: "Test2 MWE"
output: html_document
---

```{r}
runChunk1 <- TRUE # Chunk 1 should execute
runChunk2 <- FALSE # Chunk 2 should not
```

First chunk 1.
```{r 'Chunk1', eval = runChunk1}
  print("This is chunk 1.")
```

Next chunk 2.
```{r 'Chunk2', eval = runChunk2}
  print("This is chunk 2.")
```

Now this chunk. `eval` is TRUE by default, but I test echo.
```{r 'Chunk3', echo = runChunk1}
  print("This is chunk 3.")
  rm(list=ls()) # remove objects so they're not found if re-sourcing driver.R interactively
```

Now done.

````

When I call `render()` on the Rmd interactively, there's no issue. But when I `source("driver.R")`, I get the object-not-found errors. I have isolated it to the `eval` argument. (Using `echo = runChunk1` in Chunk3 above does not produce an object-not-found error.) I have isolated it to output formats html_document and pdf_document. (Nothing else results errors.) And I have isolated it to cases in which `intermediates_dir` is supplied. (If it is not supplied, no errors.)

Here's the full log:

```
> source("driver.R")
Error in eval(x, envir = envir) : object 'runChunk1' not found
Error in eval(x, envir = envir) : object 'runChunk2' not found


processing file: process.Rmd
  |.......                                                          |  11%
  ordinary text without R code

  |..............                                                   |  22%
label: unnamed-chunk-1
  |......................                                           |  33%
  ordinary text without R code

  |.............................                                    |  44%
label: Chunk1 (with options) 
List of 1
 $ eval: symbol runChunk1

  |....................................                             |  56%
  ordinary text without R code

  |...........................................                      |  67%
label: Chunk2 (with options) 
List of 1
 $ eval: symbol runChunk2

  |...................................................              |  78%
  ordinary text without R code

  |..........................................................       |  89%
label: Chunk3 (with options) 
List of 1
 $ echo: symbol runChunk1

  |.................................................................| 100%
  ordinary text without R code


output file: /path/to/intermediates_dir/process.knit.md

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS /path/to/intermediates_dir/process.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /path/to/output_dir/process.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /var/folders/kp/0mrxz_pj41lg4x7sw6d6cgsm0000gn/T//Rtmpka3na6/rmarkdown-str3165727b834d.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 

Output created: output_dir/process.html
```

And session info:

```
> devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-10-11                  

Packages ----------------------------------------------------------------------
 package    * version date       source         
 backports    1.1.0   2017-05-22 cran (@1.1.0)  
 base       * 3.4.1   2017-07-07 local          
 compiler     3.4.1   2017-07-07 local          
 datasets   * 3.4.1   2017-07-07 local          
 devtools     1.13.3  2017-08-02 CRAN (R 3.4.1) 
 digest       0.6.12  2017-01-27 CRAN (R 3.4.0) 
 evaluate     0.10.1  2017-06-24 cran (@0.10.1) 
 graphics   * 3.4.1   2017-07-07 local          
 grDevices  * 3.4.1   2017-07-07 local          
 htmltools    0.3.6   2017-04-28 cran (@0.3.6)  
 knitr        1.17    2017-08-10 CRAN (R 3.4.1) 
 magrittr     1.5     2014-11-22 cran (@1.5)    
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.0) 
 methods    * 3.4.1   2017-07-07 local          
 Rcpp         0.12.12 2017-07-15 cran (@0.12.12)
 rmarkdown  * 1.6     2017-06-15 CRAN (R 3.4.0) 
 rprojroot    1.2     2017-01-16 cran (@1.2)    
 rstudioapi   0.6     2016-06-27 CRAN (R 3.4.0) 
 stats      * 3.4.1   2017-07-07 local          
 stringi      1.1.5   2017-04-07 cran (@1.1.5)  
 stringr      1.2.0   2017-02-18 cran (@1.2.0)  
 tools        3.4.1   2017-07-07 local          
 utils      * 3.4.1   2017-07-07 local          
 withr        2.0.0   2017-07-28 CRAN (R 3.4.1) 
 yaml         2.1.14  2016-11-12 cran (@2.1.14) 
```

**Comment by yihui** [comment]
Thanks for the report! This is one of the best bug reports I have seen (clear and minimal), but I'm afraid I'm unable to tell you the full story about why this happens because I'm not entirely familiar with the intermediates dir mechanism. The TL;DR version is you can safely ignore the error messages; they don't really hurt.

Basically, when you specify `intermediates_dir` (not sure why you need it), `rmarkdown::render()` will render Markdown in an intermediate directory (if I understand it correctly), and it has to copy all possible resources referenced in the Rmd document to this directory, which requires it to parse these resources first. For some reason, it has to call `knitr::purl()` to extract R code from your Rmd document and analyze the R code to extract resources used in your R code chunks.

The error messages you saw were from `knitr::purl()`. Because it does not execute any code chunks but only extracts R code, it does not know what `eval = runChunk1` means (the variable `runChunk1` was not created because the first code chunk was not executed). However, `purl()` still needs the value of `eval` (for a code chunk with `eval = FALSE`, `purl()` has to comment out the code when writing it to the R script), so it _tries_ to evaluate `runChunk1` but apparently it will fail:
https://github.com/yihui/knitr/blob/1a4670cb/R/block.R#L455 In your case, it does not matter if it fails. The whole resource discovery mechanism is by heuristics anyway, and is not guaranteed to be solid.

I hope this makes sense.

**Comment by paulobrecht** [comment]
Thanks for the explanation. Glad to have a clearer understanding of what's happenings under the hood there. And it makes sense, since it's not fatal and doesn't impact output, that it's not a crucial fix.

**Comment by yihui** [comment]
FYI, I have fixed this issue in the current dev version of rmarkdown. Thanks!
