### ISSUE TITLE
Ability to preview file with embedded figs depends on length of filename

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#1156]
Consider this `.R` file:

``` r
#' ---
#' output:
#'   md_document:
#'     pandoc_args: [
#'       '-t', 'commonmark'
#'     ]
#' ---

plot(runif(1:3))
```

If you name it `foo.R`, you can use RStudio's html preview on the resulting `foo.md`, which includes the plot like so:

```
![](foo_files/figure-markdown_strict/unnamed-chunk-1-1.png "fig:")
```

If you name it something much longer, the html preview does not work because a hard line break has been introduced into the image syntax:

```
![](fooabcdefghijklmnopqrstuvwxyz_files/figure-markdown_strict/unnamed-chunk-1-1.png
"fig:")
```

You get this pandoc error:

```
pandoc: Could not fetch fooabcdefghijklmnopqrstuvwxyz_files/figure-markdown_strict/unnamed-chunk-1-1.png%20%22fig:%22
fooabcdefghijklmnopqrstuvwxyz_files/figure-markdown_strict/unnamed-chunk-1-1.png "fig:": openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
```

even though the file does exist.

To pre-emptively answer the question "why are you requesting CommonMark?", see #1148, i.e. it's related to [GitHub's adoption of CommonMark](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown). If I use `output: github_document` this line break problem goes away, but then I have other problems.

**Comment by yihui** [comment]
I think this is caused by the default option `--wrap=auto` in Pandoc: http://pandoc.org/MANUAL.html You may try `none` or `preserve` (using the `pandoc_args` argument).

**Comment by jennybc** [comment]
Thanks @yihui! That does indeed solve the problem, i.e. both `--wrap=none` and `--wrap=preserve` prevent the harmful line break.

Do you understand why the trailing `"fig:"` gets inserted into the image tag in the first place? It is not there when targeting other flavours of markdown.

**Comment by yihui** [comment]
I don't understand, but I have prepared the reprex for you to ask Pandoc experts:

```bash
$ echo '![](foo.png)' | pandoc -f markdown -t commonmark
![](foo.png "fig:")

$ pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/yihui/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I guess my mission is complete now in this issue :)

**Comment by jennybc** [comment]
For posterity, here's the thread on pandoc-discuss: https://groups.google.com/d/topic/pandoc-discuss/kl6Nbr-dcxk/discussion.

So it sounds like pandoc will stop auto-adding the `"fig:"` when writing CommonMark. But in the meantime, this appears to be a better workaround, i.e. to turn off implicit figures vs. messing with text wrapping:

``` yaml
output:
  md_document:
    pandoc_args: [
      '-f', 'markdown-implicit_figures',
      '-t', 'commonmark'
    ]
```
