### ISSUE TITLE
Online documentation has broken link

### ISSUE THREAD

**Issue by BarkleyBG** [rstudio/rmarkdown#1157]
At the bottom of the [online documentation for bibliographies](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#unused_references_(nocite)) there is a broken link. The sentence reads:

> When the output is LaTeX/PDF, you can also use LaTeX packages (e.g. natbib) to generate citations; see [PDF documents] for details.

The link should go to the [online documentation for PDF documents](http://rmarkdown.rstudio.com/pdf_document_format.html) but doesn't include the actual link.

I couldn't find the file to make this change - are these files not made open-source on github, or did I miss the subfolder on this repo?

**Comment by yihui** [comment]
Fixed now. Thanks for report! The documentation is in the gh-pages branch: https://github.com/rstudio/rmarkdown/compare/gh-pages You are welcome to submit a pull request next time.

**Comment by BarkleyBG** [comment]
Oh, I'd forgotten to look for gh-pages. Thanks!
