### ISSUE TITLE
Lack of bold latin symbols when knitting to word

### ISSUE THREAD

**Issue by thk686** [rstudio/rmarkdown#1158]
I know this is a pandoc/knitr issue but it causes a limitation in using rmarkdown. Currently, you cannot use eg $\pmb{\theta}$ and knit to word, unless there is a work-around I have not found. The $\mathbf{\theta}$ markup does not produce bold latin symbols. Hoping that reporting it here will be most likely to get this feature added. Thanks.

**Comment by yihui** [comment]
We rely on Pandoc to convert Markdown to Word, and we do not do anything special to math expressions during the conversion. You may have better luck if you post this question to the Pandoc mailing list or Github issues or StackOverflow. Thanks!

**Comment by thk686** [comment]
BTW, I just noticed that symbols ARE bolded in the DOCX output, but not in the HTML output.

**Comment by yihui** [comment]
Interesting. If HTML output is problematic, it is probably a MathJax issue.
