### ISSUE TITLE
Name of figure-containing directory is super-detailed

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#1159]
What I'm doing: knitting `README.Rmd` with `output: github_document`, but I suspect could be a general phenomenon with markdown output formats.

I'm used to figures being left behind in subdirectories within a directory named `README_files`, specifically, `README_files/figure-markdown_github/`.

But with the dev version of rmarkdown the name has gotten even more elaborate: `README_files/figure-markdown_github-ascii_identifiers/`. Is this intentional?

**Comment by yihui** [comment]
@kevinushey introduced `-ascii_identifier` in #1049. I'm not sure if it should go to `md_extensions` instead.

---

(Off-topic) `README_files/figure-markdown_github-ascii_identifiers/` looks cumbersome, but in my eyes, even `README_files/` looks cumbersome -- I just never use README.Rmd myself. As soon as I feel I need anything advanced, I'll just make a real web page and add the link to README.md. I did hear your point of private Github repos last time, though 😉

**Comment by yihui** [comment]
You can now test the fix I just proposed at #1175 via:

```r
devtools::install_github('rstudio/rmarkdown#1175')
```
