### ISSUE TITLE
Support custom reveal.js themes

### ISSUE THREAD

**Issue by pyltime** [rstudio/rmarkdown#116]
Allow customization of backgrounds and fonts with custom reveal.js themes.

See the post here - https://support.rstudio.com/hc/communities/public/questions/201838098-Trying-to-create-custom-themes-for-reveal-js-presentations-

**Comment by yihui** [comment]
I believe this has been implemented in the separate package **revealjs**: https://github.com/rstudio/revealjs If not, you may move the issue over to that repo. The reveal.js presentation format is no longer in the rmarkdown repo.
