### ISSUE TITLE
renderPlot in a rmarkdown using load dataset: does not recognize my data!

### ISSUE THREAD

**Issue by MelissaLe44** [rstudio/rmarkdown#1160]
I try to include interactive plots in my rmarkdown.
 My dataset (mydata) comes from a .rdata that I load into a r chunk global
 In another r chunk, I got my selectinput and my renderPlot that is based on plotting a subset of mydata depending on selectinput.
 It does not work because it does not recognize mydata. However if instead I use renderPrint to compute the length of subset of mydata, this works! so it seems it is only a problem with renderPlot!! Using ggplot, I specify environnment=environnment() but this is not working!!
 Any advice?

Thanks,
 Best
 Mélissa

**Comment by yihui** [comment]
[Cross-posted](https://yihui.name/en/2017/10/cross-posting/) at https://github.com/rstudio/shiny/issues/1872 without mentioning it. I'm closing this issue as a duplicate for now, until rmarkdown is found guilty.

As I mentioned in https://github.com/rstudio/markdown/issues/86, you shall provide a reproducible example, and you didn't when filing https://github.com/rstudio/shiny/issues/1872.

**Comment by yihui** [comment]
Should be fixed via #1165.
