### ISSUE TITLE
Error with data.frame syntax with runtime:shiny and renderPlot

### ISSUE THREAD

**Issue by wch** [rstudio/rmarkdown#1162]
This is originally from #1160 and rstudio/shiny#1872, but I'm filing here with a more detailed example.

There's some sort of interaction between data.table, rmarkdown, and shiny, where the data.table syntax doesn't work correctly in a `renderPlot()`. Oddly, it does work if you use `eval(quote(<expr>))`, but not `evalq(<expr>)`.

````
---
output: html_document
runtime: shiny
---

```{r}
library(data.table)
mydata <- data.table(A=c("a", "a", "b", "c", "c"), val=c(1:5))

renderPlot({
  # Works - see console for output
  try(
    print(eval(quote( mydata[A %in% c("a", "c")] )))
  )
  
  # Error - see console for message
  try(
    print(evalq( mydata[A %in% c("a", "c")] ))
  )
  
  # Error - see console for message
  try(
    print( mydata[A %in% c("a", "c")] )
  )

  plot(1:3, 1:3) # Just an arbitrary plot
})


# All forms work fine in renderPrint
renderPrint({
  print(eval(quote( mydata[A %in% c("a", "c")] ))) # Works
  print(evalq( mydata[A %in% c("a", "c")] ))       # Works
  print( mydata[A %in% c("a", "c")] )              # Works
})

```
````

**Comment by yihui** [comment]
@MelissaLe44 @ @mschilli87 If you want, you can test the fix via

```r
devtools::install_github('rstudio/rmarkdown#1165')
```

Note the PR has not been merged yet, so please consider #1165 as a temporary patch for now.

**Comment by wch** [comment]
@yihui Do you know why `eval` works but not `evalq`? And why it works in `renderPrint` but not `renderPlot`? It seems really strange to me.

**Comment by yihui** [comment]
I don't know. It is indeed strange.
