### ISSUE TITLE
Rmd will knit with bib file with errors when LaTeX gives error

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rmarkdown#1166]
Below is my Rmd:

```
---
title: My awesome paper
bibliography: references.bib
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: yes
documentclass: article
---

Here I have something to cite from my first reference. [@ASA2014]

Then I have something to cite from my second reference. [@Knitr2016].
```

and here is my bib file, which has an error (there should be a close curly braces, }, at the end of the first bib entry.

```
@article{ASA2014,
  title = {The 2014 American Statistical Association Curriculum Guidelines for Undergraduate Programs in Statistical Science},
  author = {American Statistical Association Undergraduate Guidelines Workgroup},
  url = {http://www.amstat.org/education/curriculumguidelines.cfm},
  year = {2014},
  misc = {Alexandria, VA: American Statistical Association}

@Manual{Knitr2016,
  title = {knitr: A General-Purpose Package for Dynamic Report Generation in R},
  author = {Yihui Xie},
  year = {2016},
  note = {R package version 1.13.1},
  url = {http://yihui.name/knitr/},
}
```

R Markdown will knit and generate the PDF with correct references without any warnings or errors, which is great, but I think it shouldn't work.

The tex file that R Markdown produces will however give the following (expected) error:

```
This is BibTeX, Version 0.99d (TeX Live 2017)
The top-level auxiliary file: paper.aux
The style file: plainnat.bst
Database file #1: references.bib.bib
I was expecting a `,' or a `}'---line 8 of file references.bib.bib
 : 
 : @Manual{Knitr2016,
(Error may have been on previous line)
I'm skipping whatever remains of this entry
Warning--empty journal in ASA2014
(There was 1 error message)
```

I would expect the R Markdown to also give the same/similar error.

**Comment by yihui** [comment]
I agree it shouldn't work, but I don't understand why it works... Sounds like `bibtex` is quite forgiving.

![works and doesn't work](https://user-images.githubusercontent.com/163582/31794696-c8ff93d6-b4e8-11e7-88fb-c3dd0bc36477.jpg)

**Comment by mine-cetinkaya-rundel** [comment]
I don't understand either. But I would expect R Markdown and LaTeX to have the same level of permissiveness.

**Comment by yihui** [comment]
I just read the error message again, and I think this explains why `bibtex` "succeeded":

> I'm skipping whatever remains of this entry

In other words, it is indeed permissive and can parse a malformed .bib file.

Actually I knew the reason why it didn't raise an error and stop R. It was my intentional decision:
https://github.com/rstudio/rmarkdown/blob/7bf14a28cf481485831b446df1e0a6a3bf188413/R/util.R#L382
I thought it should not bother users when there are errors in `makeidx` or `bibtex`.

Let me rethink about it.

**Comment by yihui** [comment]
Should be fixed now (i.e. it should not work now). Thanks for the report!
