### ISSUE TITLE
close all coe chunks with one click

### ISSUE THREAD

**Issue by andreasLD** [rstudio/rmarkdown#1167]
As my r markdown scripts and especially the code chunks therein are getting longer I would like to be able to close all code chunks of a Rmd-script with one click. This would allow for a better overview imho. I got some answers when I posted this on [SO](https://stackoverflow.com/questions/45815783/close-and-open-all-chunks-feature-in-a-rmarkdown-script-in-rstudio), however they are not exactly what I'm looking for.

**Comment by yihui** [comment]
For issues related to the RStudio IDE, please file them to https://community.rstudio.com or https://github.com/rstudio/rstudio/issues. Thanks!
