### ISSUE TITLE
`.R` templates

### ISSUE THREAD

**Issue by kkmann** [rstudio/rmarkdown#1186]
Hey, 

what are the chances of getting support for `.R` script templates? Currently, I cannot define a custom template via an `.R` script (only `.Rmd`).

Best,

Kevin

**Comment by yihui** [comment]
What kind of templates are you talking about? http://rmarkdown.rstudio.com/developer_document_templates.html?

**Comment by kkmann** [comment]
Well, if I do not put a skeleton.Rmd in the /skeleton subfolder, the template is not recognized by RStudio correctly. I simply put an empty skeleton.Rmd and the actual template.R in the /skeleton folder, which works for me but is kinda hackish. I'd like to work with a skeleton.R, because it is more flexible and accessible to people not familiar with markdown...

**Comment by yihui** [comment]
I see. I'm afraid this won't be supported any time soon. I'll take a look at it next year, unless you want to submit a pull request to implement it by yourself.
