### ISSUE TITLE
output html_document error when rendering vanilla site

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rmarkdown#1189]
@yihui is already on this, but wanted an issue to cross-reference.

A vanilla site without any configuration YAML is experiencing the error:

```
> rmarkdown::render_site()
Error in config$output[["html_document"]] : subscript out of bounds
```

Looks like fallout from #1177

**Comment by aronatkins** [comment]
Given a `_site.yml` with only `output: html_document`, we now get the error:
```
> rmarkdown::render_site()
Error in config[["output"]][["html_document"]] : subscript out of bounds
```

**Comment by yihui** [comment]
😱

**Comment by woali** [comment]
I've got the same problem after updating R (3.4.2) and markdown v1.7
> rmarkdown::render_site()
Error in config[["output"]][["html_document"]] : subscript out of bounds

Any solution?

**Comment by ginolhac** [comment]
fixed in rmarkdown v1.8 at least for me

**Comment by yihui** [comment]
Yes, please install v1.8 from CRAN.

**Comment by woali** [comment]
working, but install from Github. Thx.
