### ISSUE TITLE
Bug with rendering a child and using intermediates_dir

### ISSUE THREAD

**Issue by bellma-lilly** [rstudio/rmarkdown#1190]
Use of intermediates_dir with render and child causes an error.
This works: Rscript -e "rmarkdown::render( input = 'example.Rmd') "
This does not: Rscript -e "rmarkdown::render( input = 'example.Rmd', intermediates_dir='.') "

I believe this problem may be related to #807 and #1154

This is the error:
<pre>
Error in eval(expr, envir, enclos) : object 'child.nm' not found
Quitting from lines 21-21 (/node/scratch/11821349.1.all.ia.q/RtmpR3SNAL/child.nm) 
Error in readLines(if (is.character(input2)) { : 
  cannot open the connection
Calls: <Anonymous> ... process_tangle.block -> lapply -> FUN -> knit -> readLines
In addition: Warning message:
In readLines(if (is.character(input2)) { :
  cannot open file '/node/scratch/11821349.1.all.ia.q/RtmpR3SNAL/child.nm': No such file or directory
Execution halted
</pre>

example.Rmd looks like this:
<pre>
---
title: "child example"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document
---

```{r setup, include=FALSE}
init.child.rmd <- function( child.nm ){
  cmdline = NULL
  cmdline = rbind( cmdline, "```{r}" )
  cmdline = rbind( cmdline, "print( 'child test' )" )
  cmdline = rbind( cmdline, "```" )
  write.table( cmdline, file = child.nm, sep="\t", row.names=F, col.names=F, quote=F )
}
child.nm = "child.example.rmd"
init.child.rmd(child.nm )
```

```{r, child=child.nm }
```
</pre>

I am using a clone of this repo that I pulled today.

**Comment by yihui** [comment]
#1154 should be irrelevant.

Like I asked in #826, is there a reason you have to set `intermediate_dir` explicitly? Personally I don't recommend you to change the defaults of these three arguments: `output_file`, `output_dir`, and `intermediate_dir`. I have seen too many problems with them, but unfortunately I don't think we will be able to fix them anytime soon.

**Comment by bellma-lilly** [comment]
I have a workaround (copying the Rmd file to my destination directory and running from there), but I submitted this because it really is a bug and the other issues are closed. I spent a considerable amount of time understanding the problem and coming up with a work around, so I wanted others to be able to avoid the same problem.

**Comment by yihui** [comment]
Yes, I believe it _is_ a bug, and I'm sorry for that. I was only wondering why you had to use this argument, and all I was trying to say was that this argument was fragile (from my impression of reading other users' reports), so I wouldn't recommend using it unless you have strong reasons.

**Comment by bellma-lilly** [comment]
I use the intermediates_dir option because the original Rmd file is located in a directory I don't have write access to, so if it worked, it would be very convenient. But it isn't required.

**Comment by yihui** [comment]
I have fixed this particular issue for the case of `intermediates_dir = '.'`, but this argument will still be problematic when it takes other values...

```r
remotes::install_github('yihui/knitr')
```

Thanks!
