### ISSUE TITLE
rmarkdown 1.7 breaks Shiny R Markdown documents

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rmarkdown#1193]
Today's upgrade of my workstation to current CRAN got me rmarkdown 1.7.  Which appears to have a bad effect on shiny apps using flexdashboard -- of which we have a few.   The log now shows

```
Warning in dygraph(X, group = "Plot") :
  restarting interrupted promise evaluation
Warning in dygraph(X, group = "Plot") :
  restarting interrupted promise evaluation
Warning: Error in <reactive:data>: object 'input' not found
Stack trace (innermost first):
```

indicating that something goes astray with reactives.  Not sure if it is a shiny server bug.  The MRE below was set up on a (very current) Ubuntu 17.04 machine (aka my laptop) onto which the most recent shiny-server .deb was installed too.  Everything else CRAN current, and Ubuntu current.

````
---
title: "Rmd Bug"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
suppressMessages({
    library(xts)
    library(dygraphs)
})

data <- reactive({
    n <- as.numeric(input$days)
    x <- xts(100+cumsum(rnorm(n)), order.by=Sys.Date()+seq(-(n-1):0))
    x
})

doPlot <- function(X) {
    dg <- dygraph(X, group="Plot")
    dg <- dyOptions(dg, colors = "blue", stepPlot=TRUE, strokeWidth=1) 
    dg <- dyRangeSelector(dg)
}
```

Column {.sidebar data-with=100 }
--------------------------------

<p>

```{r}
textInput("days", "Days", 100)
```

Column
-----------------------------------------------------------------------

```{r}
renderDygraph(doPlot(data()))
```
````

**Comment by yihui** [comment]
Thanks for the report! I have minimized the reproducible example and will try to fix the issue later:

````
---
title: "Rmd Bug"
output: html_document
runtime: shiny
---

```{r}
textInput("days", "Days", 100)
```

```{r}
renderPrint(input$days)
```
````

**Comment by eddelbuettel** [comment]
Good point re MRW. It really is "just" `input` not propagating.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by jjallaire** [comment]
@yihui Should be consider a patch release to CRAN for this?

**Comment by yihui** [comment]
@jjallaire Yes, definitely. This bug is pretty bad.

**Comment by andreaslang** [comment]
I suppose there is no workaround except downgrading to a previous version?

**Comment by yihui** [comment]
@andreaslang You can install the development version via

```r
devtools::install_github('rstudio/rmarkdown')
```

**Comment by eddelbuettel** [comment]
I had the same need yesterday, and created a tarball of what was then current -- rmarkdown_1.7.4.

I just put it into the [ghrr drat repo](http://ghrr.github.io/drat/) so you can install it via

```r
install.packages("rmarkdown", repo="http://ghrr.github.io/drat")
```

or one of the other drat-using ways describe [at that repo](http://ghrr.github.io/drat/).
