### ISSUE TITLE
--chapters has been removed - Pandoc 2.0

### ISSUE THREAD

**Issue by mavogel** [rstudio/rmarkdown#1195]
Error message: 
```sh
--chapters has been removed. Use --top-level-division=chapter instead.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
Please delete _main.Rmd after you finish debugging the error.
Execution halted
```

Installed latest `devtools::install_github("rstudio/rmarkdown")` as mentioned in #1120, but unfortunately it did not fix the issue.

I use RStudio and the [thesisdown](https://github.com/ismayc/thesisdown) template. The `gitbook` output works only `pdf` fails.

**Comment by yihui** [comment]
This has nothing to do with the rmarkdown package. Please report to the author of thesisdown. Thanks!

**Comment by benwhalley** [comment]
For info, this error also occurs when using `bookdown::tufte_book2:` with the latest dev version of book down from GitHub
