### ISSUE TITLE
Issues with pandoc 2.0 and rendering README.Rmd

### ISSUE THREAD

**Issue by hadley** [rstudio/rmarkdown#1200]
There are currently three issues:

* Spurious warning: 

  ```
  [WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'README'
  ```

* `README.gfm-ascii_identifiers` created instead of `README.md`

* Rendered html file has huge line height in code blocks
  <img width="610" alt="screen shot 2017-11-14 at 8 27 47 am" src="https://user-images.githubusercontent.com/4196/32784899-b775efac-c915-11e7-9934-6dadac6313f3.png">

(With rmarkdown 1.7.5, knitr 1.17, and pandoc 2.0.2)

You should be able to reproduce by checking out https://github.com/r-lib/usethis, `devtools::install_dev_deps()`, then opening `README.Rmd` and pressing `Cmd + Shift + K`.

**Comment by yihui** [comment]
- The Pandoc warning has been suppressed (https://github.com/jgm/pandoc/issues/4048).

- The file extension has been corrected.

- The extra line-spacing has been removed.

Thanks!
