### ISSUE TITLE
require_bibtex is writing to ~/Downloads/test.txt

### ISSUE THREAD

**Issue by zeehio** [rstudio/rmarkdown#1202]
Looks like some test code was left on `R/util.R` now both in the CRAN 1.7 version and the development version... Or am I missing something...

https://github.com/rstudio/rmarkdown/blob/33518cc20239f27415892e1e062d870a709715a0/R/util.R#L400-L406

From this commit:

https://github.com/rstudio/rmarkdown/commit/93b3eff7cd180929fa03cce0bf9a315a7b31d1db#diff-f47fc41e7988539165edd36a2fc8fd66R402

I don't have a ~/Downloads so it took me a while to realize where the error was coming from :open_mouth: :smiley:

**Comment by yihui** [comment]
Ah!! Silly me! Just removed the code for my own debugging purpose.

Many thanks for the report!
