### ISSUE TITLE
Rendering of YAML elements in md output

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rmarkdown#1205]
YAML does not seem to be rendered properly in md output resulting from `keep_md: true` when using `rmarkdown` version 1.7.

Here is a MWE Rmd:

````r
---
title: "My title"
date: "November 15, 2017"
output: 
  html_document: 
    keep_md: true
---

```{r}
packageVersion("rmarkdown")
```
````

Here is a screenshot of the md output when using 1.6:
<img width="991" alt="screen shot 2017-11-15 at 11 34 08 pm" src="https://user-images.githubusercontent.com/5965649/32874099-0ea95cfc-ca5e-11e7-86be-60680decce51.png">

And here is a screenshot of the md output when using 1.7:
<img width="992" alt="screen shot 2017-11-15 at 11 30 53 pm" src="https://user-images.githubusercontent.com/5965649/32874100-11fb70c0-ca5e-11e7-9381-d79fc08e8ed0.png">

I believe the correct behaviour should be the result from 1.6.

**Comment by yihui** [comment]
The change was from #1169. If you care about the preview on Github, you should use `github_document` as the output format. The option `keep_md: yes` in other formats does not guarantee the .md by-product previews well on Github.

If you really care about the HTML preview, I'd recommend that you render it to actual HTML (e.g. via blogdown). The Github preview sort of works, but it lacks many things that Pandoc supports (which is probably fine in your use cases).

**Comment by jjallaire** [comment]
@yihui The only thing to keep in mind here is that `keep_md: yes` was added for the scenario of GitHub publishing (it was added before github_document was available) so there are likely thousands of documents out there relying on it.

**Comment by yihui** [comment]
I see. These .md documents are not "broken" -- it is just that the title, author, and date are displayed differently on Github. I don't think that is too bad.

I have argued with Jenny several times regarding this matter in the past. My major point is that the Github's preview of Markdown documents are an approximation of the actual HTML output after all (and the approximation is good enough in most cases). R Markdown is not based on Github Flavored Markdown but Pandoc's Markdown, and things like math expressions and citations won't work on Github. I tend to treat Github's rendering as a rough previewing method, and I don't feel the strong need to match with the actual Pandoc HTML output.
