### ISSUE TITLE
RNotebooks - Add error=TRUE support for sql chunks

### ISSUE THREAD

**Issue by colearendt** [rstudio/rmarkdown#1208]
I think documentation about what chunk options are supported for non-R chunks in R Notebooks would be helpful, in general, but I am thinking about the sql chunk in particular.  I was unable to find such documentation for R notebooks.  Maybe the (very thorough) RMarkdown reference could include such a note?

Below is an example where the `error=TRUE` option is honored by R, but not by sql.  

Of course, maybe this is just a bug request if the intent is for all options to be universally supported across all engines - but it seems like that might be a tall order!

````
---
title: "Error Not Honored"
output:
  html_document
---
```{r, message=FALSE}
knitr::opts_chunk$set(error = TRUE)

library(DBI)

con <- dbConnect(RSQLite::SQLite(), ":memory:")

```


```{r}
stop('error message that I want to print')
```


```{sql, connection=con}
select test;
```
````

**Comment by yihui** [comment]
The `error` option should be respected by all engines. I guess the support for `sql` chunks is currently missing.

**Comment by colearendt** [comment]
Thanks!  I changed the title accordingly, as I have tested no other options that I expected to work and didn't.

**Comment by cderv** [comment]
Thanks for the long-time-ago report @colearendt ! Better late than never ! 😅 

This should work ok now. Tested with 
````md
 ---
title: "Error Not Honored"
output: html_document
---

```{r, message=FALSE}
knitr::opts_chunk$set(error = TRUE)
library(DBI)
con <- dbConnect(RSQLite::SQLite(), ":memory:")
```

```{r}
stop('error message that I want to print')
```

```{r}
dbWriteTable(con, "mtcars", mtcars)
```

```{sql, connection=con}
SELECT * FROM mtcars WHERE cyl = 4
```

```{sql, connection=con}
DROP TABLE mtcars
```

```{r}
dbListTables(con)
```

```{sql, connection=con}
select test;
```
````
