### ISSUE TITLE
How to put 2 figures side by side in r markdown 

### ISSUE THREAD

**Issue by HuaLing1** [rstudio/rmarkdown#1210]
I got error message of "! LaTeX Error: \subfloat outside float. " when trying to put 2 figures side by side using subfloat. 

the yaml is shown below ( I included all the possible packages as i can)
header-includes:
- \setlength{\parindent}{2em}
- \setlength{\parskip}{0em}
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{subfig}
- \usepackage{graphicx}
- \usepackage{float}
# - \usepackage{xcolor}
- \onehalfspacing
- \usepackage{floatpag}
- \floatpagestyle{empty}

\begin{figure}
\centering
  \subfloat[Distribution of minor allele frequency.]{
    \label{fig:maf_hist}
    \includegraphics[width=0.3\textwidth]{../Results/13_snp_quality/maf_hist.pdf}
  }
  
  \subfloat[Correlation of allelic dosage.]{
    \label{fig:snp_corr}
    \includegraphics[width=0.3\textwidth]{../Results/13_snp_quality/snp_corr.pdf}}\\%
  }
  
\caption[Summary of concordance by SNP]{Summary of concordance by SNP over  duplicate sample pairs, binned by minor allele frequency (MAF).}
 \label{fig:snp_conc_all}
\end{figure}

**Comment by yihui** [comment]
This looks like a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead and let us know the link if you don't get an answer in a few days. Thanks!
