### ISSUE TITLE
No TOC when using github_document

### ISSUE THREAD

**Issue by chendaniely** [rstudio/rmarkdown#1211]
I'm not able to create a TOC with the `github_document` output, but I am able to do it with the `md_document` output with the `markdown_github` `variant`.

I've provided my session info and results below.

```r
> devtools::session_info('rmarkdown')
Session info --------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.392)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-11-28                  

Packages ------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.1)                    
 digest      0.6.12  2017-01-27 CRAN (R 3.4.1)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                    
 graphics  * 3.4.2   2017-11-13 local                             
 grDevices * 3.4.2   2017-11-13 local                             
 highr       0.6     2016-05-09 CRAN (R 3.4.1)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.1)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)                    
 knitr       1.17    2017-08-10 CRAN (R 3.4.1)                    
 magrittr    1.5     2014-11-22 CRAN (R 3.4.1)                    
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                    
 methods   * 3.4.2   2017-11-13 local                             
 mime        0.5     2016-07-07 CRAN (R 3.4.1)                    
 Rcpp        0.12.14 2017-11-23 CRAN (R 3.4.2)                    
 rmarkdown   1.8.3   2017-11-28 Github (rstudio/rmarkdown@07f7d8e)
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.1)                    
 stats     * 3.4.2   2017-11-13 local                             
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                    
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.1)                    
 tools       3.4.2   2017-11-13 local                             
 utils     * 3.4.2   2017-11-13 local                             
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.1)
```

Using `md_document`:

```
---
title: "github toc"
output:
  md_document:
    variant: markdown_github 
    toc: true
---

# H1a

## H2

# H1b
```

The markdown output:

```
-   [H1a](#h1a)
    -   [H2](#h2)
-   [H1b](#h1b)

H1a
===

H2
--

H1b
===

```

Using the `github_document`:

```
---
title: "github toc"
output:
  github_document:
    toc: true
    toc_depth: 2
---

# H1a

## H2

# H1b

```

The markdown output:

```
github toc
================

# H1a

## H2

# H1b

```

Am I wrong to assume the `.md` results from `md_document` and `github_document` should be the same? Or at least the beginning of the file that creats the TOC?

**Comment by yihui** [comment]
Yes, that is a wrong assumption. `md_document` and `github_document` are different output formats.

That said, I cannot reproduce your issue. I get

````
github toc
================

-   [H1a](#h1a)
    -   [H2](#h2)
-   [H1b](#h1b)

H1a
===

H2
--

H1b
===
````

What is your `rmarkdown::pandoc_version()`?

**Comment by chendaniely** [comment]
```r
> rmarkdown::pandoc_version()
[1] ‘2.0.3’
```

**Comment by yihui** [comment]
@chendaniely I think that is the problem. [There is no need to use Pandoc 2.0](https://yihui.name/en/2017/11/pandoc-2/), but if you have to, please file an issue to the [Pandoc repo](/jgm/pandoc/) with a minimal Markdown example.

**Comment by stla** [comment]
@chendaniely The behavior of `toc` has changed in Pandoc 2.0:

> * Use `table-of-contents` for contents of toc, make `toc` a boolean
>     (#2872).  Changed markdown, rtf, and HTML-based templates accordingly.
>     This allows you to set `toc: true` in the metadata; this
>     previously produced strange results in some output formats.
>     For backwards compatibility, `toc` is still set to the
>     toc contents.  But it is recommended that you update templates
>     to use `table-of-contents` for the toc contents and `toc`
>     for a boolean flag.

The mentioned issue: https://github.com/jgm/pandoc/issues/2872

I'm not sure to understand these explanations. I would try:
```
---
title: "github toc"
toc: true
output:
  github_document:
    toc: true
    toc_depth: 2
---
```

**Comment by stla** [comment]
@chendaniely 
Nope. I've tried Pandoc 2.0.4 and there's no automatic table of contents for the `gfm` output.
As a workaround you can firstly output a markdown document and then take this file as input to generate a `gfm`.

**Comment by jeroen** [comment]
Using pandoc 2.1.1 and still no toc for `github_document()`.

**Comment by mstuart1** [comment]
Updating [pandoc](https://pandoc.org/installing.html) solved this issue for me.
