### ISSUE TITLE
All `learnr` tutorials acting up in rmarkdown master

### ISSUE THREAD

**Issue by bborgesr** [rstudio/rmarkdown#1213]
A bug in two acts
---

### Act I
Consider the following `learnr` tutorial:

````julia
---
title: "R Notebook"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup}
library(leaflet)
m <-  leaflet() %>% addTiles()
m  # a map with the default OSM tile layer

# set bounds
m %>% fitBounds(0, 40, 10, 50)

# move the center to Snedecor Hall
m %>% 
  setView(-93.65, 42.0285, zoom = 17) %>% 
  addPopups(-93.65, 42.0285, 'Here is the <b>Department of Statistics</b>, ISU')
```
````

This works "fine" (see Act II) with `rmarkdown` from CRAN. However, with the latest github version of `rmarkdown` (07f7d8ef8db1774a35b4bcf427d443218aeea9c8), the same tutorial fails to render with only these two lines in the R Markdown console:

```
Error: path for html_dependency not found: 
Execution halted
```

Both myself and @andrie found a weird workaround. In his words:

> To make it [the error above] go away, I have to make an edit in the Rmd file.  Any edit will do.  Add a space, delete the space, then knit. The problem always goes away. But I have to make the same non-edit every single time. 

Here's my session info:

<details>
  <summary><code>devtools::session_info()</code></summary>

```r
Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Lisbon               
 date     2017-12-05                  

Packages -----------------------------------------------------------------------------
 package     * version date       source                            
 backports     1.1.1   2017-09-25 CRAN (R 3.4.2)                    
 base        * 3.4.2   2017-10-04 local                             
 compiler      3.4.2   2017-10-04 local                             
 datasets    * 3.4.2   2017-10-04 local                             
 devtools      1.13.4  2017-11-09 CRAN (R 3.4.2)                    
 digest        0.6.12  2017-01-27 CRAN (R 3.4.0)                    
 evaluate      0.10.1  2017-06-24 CRAN (R 3.4.1)                    
 graphics    * 3.4.2   2017-10-04 local                             
 grDevices   * 3.4.2   2017-10-04 local                             
 htmltools     0.3.6   2017-04-28 CRAN (R 3.4.0)                    
 htmlwidgets   0.9     2017-07-10 CRAN (R 3.4.1)                    
 httpuv        1.3.5   2017-07-04 CRAN (R 3.4.1)                    
 jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)                    
 knitr         1.17.20 2017-12-05 Github (yihui/knitr@73387d6)      
 learnr        0.9.1   2017-11-16 CRAN (R 3.4.2)                    
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)                    
 markdown      0.8     2017-04-20 cran (@0.8)                       
 memoise       1.1.0   2017-04-21 CRAN (R 3.4.0)                    
 methods     * 3.4.2   2017-10-04 local                             
 mime          0.5     2016-07-07 CRAN (R 3.4.0)                    
 R6            2.2.2   2017-06-17 CRAN (R 3.4.0)                    
 Rcpp          0.12.13 2017-09-28 cran (@0.12.13)                   
 rmarkdown     1.8.3   2017-12-05 Github (rstudio/rmarkdown@07f7d8e)
 rprojroot     1.2     2017-01-16 CRAN (R 3.4.0)                    
 rsconnect     0.8.5   2017-08-23 CRAN (R 3.4.1)                    
 shiny         1.0.5   2017-08-23 CRAN (R 3.4.1)                    
 stats       * 3.4.2   2017-10-04 local                             
 stringi       1.1.5   2017-04-07 cran (@1.1.5)                     
 stringr       1.2.0   2017-02-18 CRAN (R 3.4.0)                    
 tools         3.4.2   2017-10-04 local                             
 utils       * 3.4.2   2017-10-04 local                             
 withr         2.1.0   2017-11-01 CRAN (R 3.4.2)                    
 xtable        1.8-2   2016-02-05 CRAN (R 3.4.0)                    
 yaml          2.1.15  2017-12-01 cran (@2.1.15)
```

</details>

-----

### Act II
You can also repro the second issue with the tutorial above, but really, any `learnr` tutorial will do, even a bare one:

```julia
---
title: "R Notebook"
output: learnr::tutorial
runtime: shiny_prerendered
---
```

The document knits just fine: 

<details>
  <summary><code>R Markdown console -- knitting</code></summary>

```
Loading required namespace: shiny
  |.................................................................| 100%
  ordinary text without R code




processing file: andrie.Rmd
output file: andrie.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS andrie.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output andrie.html --email-obfuscation none --section-divs --template /Library/Frameworks/R.framework/Versions/3.4/Resources/library/learnr/rmarkdown/templates/tutorial/resources/tutorial-format.htm --no-highlight --variable progressive=false --variable allow-skip=false --id-prefix section- --variable 'theme:cerulean' --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 

Output created: andrie.html

Listening on http://127.0.0.1:4023
```

</details>
<br/>

However, the R Markdown console keeps on showing the same warning and error about every second (though the app above works just fine, even while demonstrating this behavior):

```
Warning: Error in shinysession$handleRequest: attempt to apply non-function
Stack trace (innermost first):
    3: <Anonymous>
    2: do.call
    1: rmarkdown::run
Error : attempt to apply non-function
Warning: Error in download$filter: attempt to apply non-function
Stack trace (innermost first):
    3: <Anonymous>
    2: do.call
    1: rmarkdown::run
Error : attempt to apply non-function
Warning: Error in download$filter: attempt to apply non-function
Stack trace (innermost first):
    3: <Anonymous>
    2: do.call
    1: rmarkdown::run
Error : attempt to apply non-function
Warning: Error in download$filter: attempt to apply non-function
Stack trace (innermost first):
    3: <Anonymous>
    2: do.call
    1: rmarkdown::run
Error : attempt to apply non-function
```

**Comment by bborgesr** [comment]
The second issue may be a shiny or a shiny-prerendered issue, but I'm not sure.

Also, as for the first issue, I should add that I was able to `git bisect` the bad commit: 7663afa87bfc93590fa84bf587375bee9dfa4efd. Here's the last of my output:

````
Barbaras-MacBook-Pro:rmarkdown$ git checkout 7663afa87bfc93590fa84bf587375bee9dfa4efd

HEAD is now at 7663afa... use html4 specifically instead of the ambiguous html, 
which means html5 in Pandoc 2.0, and can cause problems like https://community.rstudio.com/t/3019

Barbaras-MacBook-Pro:rmarkdown$ git bisect bad

Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d01fc30d96f9703d405698723a168dacfd24a8e1] html4 should be treated as an HTML format, too

Barbaras-MacBook-Pro:rmarkdown$ git checkout d01fc30d96f9703d405698723a168dacfd24a8e1

HEAD is now at d01fc30... html4 should be treated as an HTML format, too

Barbaras-MacBook-Pro:rmarkdown barbaraborges$ git bisect good

7663afa87bfc93590fa84bf587375bee9dfa4efd is the first bad commit
commit 7663afa87bfc93590fa84bf587375bee9dfa4efd
Author: Yihui Xie <xie@yihui.name>
Date:   Tue Nov 21 14:00:43 2017 -0600

    use html4 specifically instead of the ambiguous html, 
    which means html5 in Pandoc 2.0, and can cause problems 
    like https://community.rstudio.com/t/3019

:040000 040000 be060f36a90fb3175e26cc6775593c7e186bfd4e 87a410d5fb5ec56191f5499ea2cf2376a3e80c49 M R
:040000 040000 2aacda48276d29e6f80a312b77c30e3624e95b8a f93d385272db6c5fb345ce261ba89bd6ac5fbe36 M inst

````

cc @jcheng5 @yihui

**Comment by jjallaire** [comment]
My guess would have been that this is what introduced the problem: https://github.com/rstudio/learnr/commit/6eb75a031a0a6977e4731697c098c66b208c72de

The commit isn't necessarily problematic, but it results in a cache invalidation issue whereby the cached .html file for the tutorial has pointers to dependencies that no longer exist. I would expect that if you delete the .html file associated with the tutorial (which is effectively what you did by making an edit to the Rmd) then the problem would permanently go away

**Comment by wch** [comment]
When I open it in a browser and look at the JS console, it looks like error is coming from the `initialize` endpoint, as in: http://127.0.0.1:3151/session/188c6231f2a7ac685ae884c873d01438/dataobj/initialize?w=
<img width="900" alt="screen shot 2017-12-05 at 1 35 53 pm" src="https://user-images.githubusercontent.com/86978/33626788-3c880f0c-d9c1-11e7-9f9c-7d735464a2b6.png">


When I follow that link, the page just says `Error in download$filter: attempt to apply non-function`.
<img width="687" alt="screen shot 2017-12-05 at 1 36 07 pm" src="https://user-images.githubusercontent.com/86978/33626801-4527ac80-d9c1-11e7-8d38-c954e8f184eb.png">


When I add a `browser()` call in [`ShinySesssion$registerDataObj()`](https://github.com/rstudio/shiny/blob/cad20a0b/R/shiny.R#L1781), and then run the document with `rmarkdown::run()`, it appears that the `"initialize"` endpoint is not getting registered.

**Comment by yihui** [comment]
It sounds like pre-rendered Shiny Rmd documents should have a cache invalidation mechanism, e.g. when the rmarkdown version has changed, perhaps the .html output file should be regenerated.

**Comment by jjallaire** [comment]
Yes, Winston that all stems for the cache invalidation.

@yihui You are absolutely right that they need a cache invalidation mechanism or we will continue to see this sort of thing periodically.

**Comment by bborgesr** [comment]
@yihui, if I interpret the conversation above correctly, both problems stem from caching issues in the way that `rmarkdown` handles pre-rendered Shiny Rmd documents, right? Do you need anything else from me or `learnr`? I'm not sure what is the best way to help...

**Comment by jcheng5** [comment]
I had an offline conversation with JJ where he gave me some pointers on how this could be fixed.

Here's where we insert some dependency metadata into the document; we could add a cache fingerprint to the document around here too. https://github.com/rstudio/rmarkdown/blob/07f7d8ef8db1774a35b4bcf427d443218aeea9c8/R/render.R#L568-L573

Here's where rmarkdown decides whether to rerender or whether to use the cached version. We could call `shiny_prerendered_extract_context` to retrieve the cache fingerprint.
https://github.com/rstudio/rmarkdown/blob/07f7d8ef8db1774a35b4bcf427d443218aeea9c8/R/shiny_prerendered.R#L88

JJ also suggested incorporating not only the rmarkdown version, but also the version of the package that is providing the output function, into the cache fingerprint.

@yihui were you planning on taking this on yourself, or do you want me to take a shot at it?

**Comment by yihui** [comment]
@jcheng5 I haven't got a chance to investigate it by myself yet (sorry @bborgesr), but if it is clear to you what needs to be done, please go ahead, and I'll appreciate it!

**Comment by jcheng5** [comment]
I can reproduce the second issue with the CRAN versions of learnr and rmarkdown BUT it only happens when there are no actual learnr questions in the Rmd document--in other words, I think the minimal repro was a bit too minimal!

**Comment by jcheng5** [comment]
The first issue only occurs when using an old version of learnr (CRAN) and a new version of rmarkdown (GH master). No repro if learnr and rmarkdown are both from CRAN. No repro if learnr and rmarkdown are both from GH master. So @andrie, upgrading learnr should fix the problem.

The commit that JJ pointed out, https://github.com/rstudio/learnr/commit/6eb75a031a0a6977e4731697c098c66b208c72de didn't introduce the problem--it fixed it! It's because before that commit, highlight.js had this source: `system.file("rmd/h/highlightjs-1.1", package = "rmarkdown")`, which is the correct path for rmarkdown@CRAN but not the correct path for rmarkdown@GitHub (the `-1.1` has been removed). After that commit, learnr stops relying on internal knowledge of rmarkdown paths and uses exported rmarkdown functions instead.

@jjallaire @yihui There may also be a fundamental cache invalidation issue but we don't have a repro case of one--is this still something I should pursue to avoid future pain, or should I just leave it for now?

**Comment by jjallaire** [comment]
Since this isn't as severe (in terms of likely occurrence) as we thought, I think we should leave this alone for now (but keep the issue open as a reminder). I think adding the cache invalidation mechanism is valuable but I can't argue that the time it will take outweighs time lost on other more valuable things.

**Comment by rpruim** [comment]
I'm having lots of grief with tutorials.  Behavior seems unpredictable.  I've tried downgrading to the latest stable version of RStudio from a daily build that was a bit behind.  Worked for awhile but didn't last.   See https://github.com/ProjectMOSAIC/ggformula/issues/62.

Most recently I tried deleting an HTML file to force a rebuild and just got complaints about the HTML  file being missing.  Then I restarted the R session and things worked.  Seem like tutorial processing has gotten very flakey somehow.

**Comment by jcheng5** [comment]
@rpruim Does the problem go away if you reinstall both learnr and rmarkdown from CRAN (and definitely restart R)? And if that works, does it continue to work if you install learnr and rmarkdown from GitHub?

**Comment by yihui** [comment]
This issue actually contains two separate issues. One is related to rmarkdown, and one is to learnr. I have fixed the error `Error: path for html_dependency not found:` (it was due to the highlightjs dependency, and I have monkey patched it).

For the problem `Error in download$filter: attempt to apply non-function`, @jcheng5 has pointed out the cause. It was because `learnr::initialize_tutorial()` was never called in this particular example, because it does not contain any exercises.

https://github.com/rstudio/learnr/blob/c8940576866a7ac45a77e34c125c6d778ed2dcbd/R/knitr-hooks.R#L65-L66

I thought quite a while about it, but couldn't provide a proper fix in learnr. For this particular example, it seems the only way to fix it is to manually add a code chunk:

````
```{r}
learnr::initialize_tutorial()
```
````

**Comment by jjallaire** [comment]
@yihui You are correct that you need the explicit initialization in this case (the `initialize_tutorial()` happens automatically if there is either an exercise or a question, but if you have used neither it needs to be explicit and there isn't a way around this I've seen)
