### ISSUE TITLE
Incremental Display does not work 

### ISSUE THREAD

**Issue by huyingjie** [rstudio/rmarkdown#1223]
The bullet points in "First Slide" do now show one by one

Here is my code. 

``` 
design
========================================================
author: y
date: 2017-12-18
autosize: true
incremental: true
transition: rotate
transition-speed: slow

First Slide
========================================================
incremental: true
type: section

* 1
* 2
* 3
```

Here is my session info

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16   
```

**Comment by yihui** [comment]
Thanks for posting on StackOverflow: https://stackoverflow.com/q/47874246/559676

Actually you are using R Presentation (.Rpres) instead of R Markdown presentation (.Rmd). The two are different (I know this is very confusing).

**Comment by huyingjie** [comment]
@yihui The reason I posted here because I cannot find github repo for R presentation. And I thought R presentation was using R Markdown and maybe RStudio combined these two repos together.

**Comment by yihui** [comment]
It is fine to post the issue here. I'm closing it only because it has been posted to SO (which is what I'd recommend). Thanks!
