### ISSUE TITLE
htmlwidgets element not showing in webshot

### ISSUE THREAD

**Issue by Bryant-zhu** [rstudio/rmarkdown#1225]
hi there
I have been using the web shot as an final step of my automated daily report for a while.
it's been working for my previous web shot of markdown made of high charter and other screen shot.

but recently I have try out the flexdashboard in R for better visual effect.
then when I try webshot, it turns out like this.
all the element made of HTML widgets is not showing. (sometimes even in the Rstudio viewer , those htmlwidget element were not showing, I have to view it in brower in order to see them)

 
![image](https://user-images.githubusercontent.com/13691830/34287664-a967b86a-e723-11e7-8fca-220b9d78aabe.png)

is there any way of fixing this ? that would be really helpful.

**Comment by yihui** [comment]
When you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Let's keep everyone in the same thread (https://github.com/wch/webshot/issues/50). Thanks!
