### ISSUE TITLE
No caption in html_document for plots

### ISSUE THREAD

**Issue by dataopt** [rstudio/rmarkdown#1226]
The following, when knitted to html, does not have a caption.  (Screenshot attached.)  However, when knitted to pdf, the caption is present.

````
---
title: "Test"
author: "Someone"
output:
  html_document:
    fig_caption: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r pressure, echo=FALSE, fig.cap='Pressure vs temperature'}
plot(pressure)
```
````
<img width="677" alt="screen shot 2017-12-26 at 11 22 06 am" src="https://user-images.githubusercontent.com/28999218/34360463-1c5dd698-ea2f-11e7-8003-43127a6c0890.png">

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  backports_1.1.0 bookdown_0.5.13 magrittr_1.5   
 [5] rsconnect_0.8.5 rprojroot_1.2   htmltools_0.3.6 tools_3.4.0    
 [9] yaml_2.1.16     Rcpp_0.12.11    stringi_1.1.5   rmarkdown_1.8.5
[13] knitr_1.17      stringr_1.2.0   digest_0.6.13   evaluate_0.10.1
```

**Comment by cderv** [comment]
To add information for helping debug, this is working with last CRAN version `rmarkdown 1.8`  and `knitr 1.17` (see screenshot at the end) but I can reproduce with last dev version `rmarkdown 1.8.5` and `knitr 1.17`. 

Using `git bisect`, it seems the change in 7663afa8 breaks this. I think pandoc do not translate figure caption the same way between `--to html4` and `--to html`. 

I did not manage to make a simple example to override the hard coded `--to html4` argument using `pandoc_args`. However, I tested it with `--to html` with command line and it worked.

Hoping it helps.

## Working with `rmarkdown 1.8`
![image](https://user-images.githubusercontent.com/6791940/34405276-bb7bd20a-ebb2-11e7-91b9-ee65d76aa1f2.png)

**Comment by yihui** [comment]
Thanks, @cderv, for help debug the issue. I think knitr >= 1.18 should resolve this issue, and 1.18 was on CRAN yesterday.
