### ISSUE TITLE
multi-line latex equation in R Markdown and Windows

### ISSUE THREAD

**Issue by ignacio82** [rstudio/rmarkdown#1227]
I think this might be a bug:

The following code works fine on linux:

    ---
    title: "LaTeX test"
    author: "Ignacio"
    output: html_document
    ---
      
    
    ## Latex
    
    $$ 
    \begin{aligned}
    
    y_j \sim N(\theta_j , \sigma_j^2) \\
    
    \sigma_j = \nu/\sqrt{n_j}   \\
    
    \theta = \mu +\tau \times \eta \\
    
    \eta \sim N(0,1) \\
    
    \mu + \tau\times\eta = \theta \sim N(\mu , \tau^2)
    
    \end{aligned}
    $$

On Windows, rstudio renders the equations correctly:

[![enter image description here][1]][1]

But, when I Knit the file and open the HTML with chrome or ie the latex is not rendered correctly:

[![enter image description here][2]][2]

    > devtools::session_info('rmarkdown')
    Session info --------------------------------------------------------------------------------------------
      setting  value                       
    version  R version 3.4.2 (2017-09-28)
    system   x86_64, mingw32             
    ui       RStudio (1.0.153)           
    language (EN)                        
    collate  English_United States.1252  
    tz       America/New_York            
    date     2017-12-26                  
    
    Packages ------------------------------------------------------------------------------------------------
      package   * version date       source        
    backports   1.0.5   2017-01-18 CRAN (R 3.4.0)
    base64enc   0.1-3   2015-07-28 CRAN (R 3.3.0)
    bitops      1.0-6   2013-08-17 CRAN (R 3.3.0)
    caTools     1.17.1  2014-09-10 CRAN (R 3.3.0)
    digest      0.6.12  2017-01-27 CRAN (R 3.3.3)
    evaluate    0.10.1  2017-06-24 CRAN (R 3.4.2)
    highr       0.6     2016-05-09 CRAN (R 3.3.0)
    htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)
    jsonlite    1.5     2017-06-01 CRAN (R 3.4.2)
    knitr       1.17    2017-08-10 CRAN (R 3.4.2)
    magrittr    1.5     2014-11-22 CRAN (R 3.3.0)
    markdown    0.8     2017-04-20 CRAN (R 3.4.0)
    mime        0.5     2016-07-07 CRAN (R 3.3.2)
    Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)
    rmarkdown   1.6     2017-06-15 CRAN (R 3.4.2)
    rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)
    stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)
    stringr     1.2.0   2017-02-18 CRAN (R 3.3.3)
    yaml        2.1.14  2016-11-12 CRAN (R 3.3.3)

PS: I asked this question on [StackOverflow](https://stackoverflow.com/questions/47913433/multiline-latex-equation-in-r-markdown-and-windows)

  [1]: https://i.stack.imgur.com/6qo4k.png
  [2]: https://i.stack.imgur.com/9fq7n.png

**Comment by yihui** [comment]
Okay, let's follow up on SO. Thanks!
