### ISSUE TITLE
How to display inline images in notebook viewer?

### ISSUE THREAD

**Issue by jeroen** [rstudio/rmarkdown#1228]
The magick pkg has a [`knit_print` method](https://github.com/ropensci/magick/blob/master/R/base.R#L111-L118) which calls `knitr::include_graphics()` to automatically display images when rendering an rmarkdown document.

This works great via `knitr::knit()` or `rmarkdown::render()` however the `knit_print` method gets [ignored when knitting inside rmarkdown notebooks](https://github.com/ropensci/magick/issues/102). Is there an alternative hook or method to display inline images in the rmarkdown notebook IDE? cc @jmcphers

**Comment by yihui** [comment]
I think this issue belongs to https://github.com/rstudio/rstudio
