### ISSUE TITLE
Headings are not rendered when creating a document from RStudio with pandoc 2.0

### ISSUE THREAD

**Issue by artasom** [rstudio/rmarkdown#1229]
If a RNotebook document is knit-ed from RStudio and pandoc 2.0, only the output html_notebook (Preview Notebook) renders the headings.

![image](https://user-images.githubusercontent.com/6305118/34462261-0bb48c50-ee40-11e7-852d-51d1131dee08.png)

Any other output (HTML, Word, PDF), shows the heading as plain text, with the hashtag.

![image](https://user-images.githubusercontent.com/6305118/34462272-43323772-ee40-11e7-9a6b-b3e3dfa57a82.png)

I tried updating rmarkdown to the last version in the development branch, to no avail. I attach the session info.

The reason I want to use pandoc 2.0 is because this version allows to format all the tables in the word document output by using a reference document with a table style named [Table]

Any idea why this can be happening and how to solve it?

Thanks and best regards,
Miguel A.

[session_info.txt](https://github.com/rstudio/rmarkdown/files/1595234/session_info.txt)

**Comment by yihui** [comment]
I think you need a space after `##`.

**Comment by artasom** [comment]
Hi @yihui. You are right indeed. I cannot understand why it was working with the version of Pandoc embedded in RStudio and not with Pandoc 2.0...

Thanks for your help

**Comment by yihui** [comment]
It is probably because Pandoc 2.0 is more strict about the Markdown syntax. Anyway, I always use spaces and empty lines myself to avoid ambiguities.
