### ISSUE TITLE
Automatic freezing of shiny elements for static html or pdf

### ISSUE THREAD

**Issue by kmader** [rstudio/rmarkdown#123]
It would be very useful if shiny code could be automatically 'frozen' in the initial state for generating static / offline versions of the document without manually changing the code every time

**Comment by yihui** [comment]
I'm not sure what "freezing" means here, but I feel this feature probably belongs to the **knitr** package. Please bring an example to elaborate what you meant by "freezing" and how exactly you "manually change the code".
