### ISSUE TITLE
Include image lightbox effect as default behavior in html output?

### ISSUE THREAD

**Issue by mbacou** [rstudio/rmarkdown#1232]
I see lightbox is available in themes provided in package https://github.com/juba/rmdformats, just wondering if there's a reason not to make this the default behavior in rmarkdown, or provide a `fig_lightbox` chunk option for html output? Is it because that effect is not part of Bootstrap?
Apologies if that has been discussed earlier.

**Comment by yihui** [comment]
I agree it is nice, but as the current maintainer of this package, I don't want to introduce one more JS library to this package. Typically it is fairly easy to introduce dependencies, but it can be extremely painful to maintain them in the future. Honestly, I have already felt overwhelmed by the number of JS dependencies in this package.

If rmdformats works, I'd happily suggest you use it. Thanks!
