### ISSUE TITLE
Feature Request: Parameters for templates

### ISSUE THREAD

**Issue by colearendt** [rstudio/rmarkdown#1234]
#1233 suggests a need for parameters for rmarkdown templates, and I am curious to discuss what such a feature might look like.  I imagine something like:

```
rmarkdown::draft("/path/to/folder", "html_vignette", 
        "rmarkdown", create_dir = FALSE, edit = FALSE
        , template_param = list("package"="mypackagename"))
```

Which would replace something like:

````
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(template_param$package)
```
````

with something like:
````
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(mypackagename)
```
````

Features to consider:
- syntax for replacement within a Rmd.  Would this simply be utilization of rmarkdown parameters?  Or would this be a "higher level" that is replaced on draft creation (I lean towards the latter)
- Ability to define a default value within the `template.yaml`
- Ability to define values within `rmarkdown::draft` (and elsewhere?)
- Plug-in to the UI that allows defining types, values, etc.
- It's not clear to me whether this should use R syntax or some other template syntax for replacement (i.e. `{{TEMPLATEPARAM}}`)

Happy to discuss!

**Comment by yihui** [comment]
Thanks for the ideas, but let's reach a decision in #1233 before discussing this more general feature. I don't feel how widely useful this could be (i.e. do you have other use cases?).

**Comment by colearendt** [comment]
I don't and do not mind waiting at all.  I actually did not know about templates until yesterday.  Just wanted to document the thought!

**Comment by yihui** [comment]
We could use something like `knitr::knit_expand()`, but as I said, I don't know what the potential use cases are, so I'm closing this for now (it can be reopened in the future).
