### ISSUE TITLE
Allow sql-code-chunk-results to be collected and stored in an R object

### ISSUE THREAD

**Issue by EdwinTh** [rstudio/rmarkdown#1236]
Using sql-code-chunks in a `.Rmd` is very convenient. It has nice syntax highlighting and we don't need any R functions around the sql code. Like the following:

    ```{sql connection=con}
    SELECT * 
    FROM my_table
    ```

However, as far as I know, it does not allow for pulling the query result into your R session to further analyse the data locally. This calls for the following code

    ```{r}
    my_table_in_r <-
      odbc::dbGetQuery(
      con,
      "SELECT *
       FROM my_table") %>%
      dplyr::collect()
    ```
In this silly example the sql code is still reasonably clear. However, as the query gets more complicated this can get quite messy, as it is in a character string with no sql syntax highlighting. Also you have to be careful with single and double quotes within the code, since the sql code is within one of them.

It would be super awesome if the result from a sql-chunk could be stored in an R object right away. Maybe by specifying the desired object name in the chunk argument like

    ```{sql connection=con, r_obj=my_table_in_r}
    SELECT * 
    FROM my_table
    ```
I have no idea if this is feasible, but it woud make me very happy!

**Comment by jjallaire** [comment]
This is currently supported via the `output.var` chunk option, see http://rmarkdown.rstudio.com/authoring_knitr_engines.html#sql

**Comment by EdwinTh** [comment]
Fantastic! Missed it somehow when reading this. Sorry to bother...

**Comment by marbotte** [comment]
How do we do in order to store the result in a output.var **AND** print the result in the same query sql chunk?
