### ISSUE TITLE
Feature Request: Permission Dependencies

### ISSUE THREAD

**Issue by GrimTrigger88** [rstudio/rmarkdown#1237]
Our team is having a hard time assessing which pieces of the (Red Hat Linux) file structure a user needs access to in order to use the markdown document. It would be great if knit created an R object with the filepaths accessed upon successful completion. This way the creator would know the permissions required by the consumers.

We are currently having individuals open the same .Rmd file because RConnect won't let us publish markdown documents that reference the drivers needed to connect to SQL. However, upon completion (we are seeing warnings that are only created on successful completion), the users are being told they do not have access to the document that is created.

**Comment by nwstephens** [comment]
Chris, could create a support ticket with a little more info for us at support@rstudio.com? I'd like to understand your setup a little better.

If you are running RStudio Connect on its own machine, you'll have to set up the file structure and the ODBC drivers ahead of time. The configuration will be set and you should make that known to your data science team. You can specify the differences between your dev and prod environments by using the `config` R package.

If you are running RStudio Server Pro and RStudio Connect on the same infrastructure (same server with same file shares) and you want dev/prod deployments to work seamlessly without the config package, then we'll need a little bit more information about what you're trying to do. The best way to do that is to get that support thread going.

**Comment by GrimTrigger88** [comment]
I've submitted the support request.

**Comment by yihui** [comment]
By default, `rmarkdown::render()` will create a bunch of files and directories under the directory of the Rmd source file. It also reads a template file from the **rmarkdown** package (`find.package('rmarkdown')). Sometimes it also creates temporary files (`tempdir()`). I believe these are all files that are accessed. In terms of permission: you should be fine as long as you have write permission under the Rmd directory. Not sure if this answers your question.
