### ISSUE TITLE
relax self-contained requirement for GitHub documents?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#1238]
Currently, the HTML previews generated for GitHub documents are generated with `--self-contained`, as per:

https://github.com/rstudio/rmarkdown/blob/561b812d249c65e5031418b5e10ab1986bc9eecd/R/github_document.R#L61-L69

However, this can fail when attempting to preview documents that request external web resources, if that resource is inaccessible for some reason (no internet; old version of pandoc that doesn't handle `https://`; etc).

Is it worth relaxing the standalone requirement in this case, so that document previews can still be viewed?

I think if we take away `--self-contained` we also need to do a bit of extra work to ensure that the GitHub CSS is injected into the template by hand, as without `--self-contained` `pandoc` won't do that work for us.

cc: https://github.com/rstudio/rstudio/issues/1922

**Comment by kevinushey** [comment]
But the `--self-contained` is required so that images on the local disk can be injected into the document after render; otherwise, those will fail to show...

**Comment by yihui** [comment]
Without Pandoc's `--self-contained`, we will have to do the heavy lifting by ourselves to embed local resources.

Four years ago, I suggested Pandoc provide an option to skip remote web resources in the case of `--self-contained`, but @jgm didn't seem to be interested: https://groups.google.com/forum/#!msg/pandoc-discuss/cN0sTSdesT8/ngKRNJ5tBQAJ I believe there are two types of self-containedness: every byte of external resources strictly embedded in a single output file, or allow using web resources and only embed local files. The latter is also a self-contained document (no other local files required to view this document), although it requires internet connection. In a certain old version of Pandoc, there was an `--offline` flag, which could be a perfect option to control whether remote resources should be fetched and embedded (it didn't mean this at that time).

Anyway, I guess this is going to be too much work with minimal gain, so once again, @jennybc, consider giving up Github Markdown documents and moving your README.Rmd to blogdown websites :)

**Comment by jgm** [comment]
+++ Yihui Xie [Jan 25 18 15:29 ]:
>   Four years ago, I suggested Pandoc provide an option to skip remote web
>   resources in the case of --self-contained, but [1]@jgm didn't seem to
>   be interested:
>   [2]https://groups.google.com/forum/#!msg/pandoc-discuss/cN0sTSdesT8/ngK
>   RNJ5tBQAJ I believe there are two types of self-containedness: every

From the pandoc manual:

> Elements with the attribute `data-external="1"` will be left alone; the documents they link to will not be incorporated in the document.

In case you didn't know about that.

**Comment by yihui** [comment]
Thanks @jgm! I was aware of that option, but I still think a command-line argument `--offline=yes|no` is much nicer (with `--offline=no`, we don't have to add `data-external=1` to every single http(s) resource).

**Comment by jennybc** [comment]
My first experiments using the attribute `data-external="1"` with, e.g., Travis or Codecov badges have been a failure (https://github.com/r-lib/usethis/issues/195#issuecomment-361091876). But it may still be user error.
