### ISSUE TITLE
toc, df_print, and bibliography fields do not work properly in rmarkdown::powerpoint_presentation()

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rmarkdown#1249]
Hello,

I am using R x64 3.4.3 and Pandoc 2.1 in Windows 10 (x64).

I have found some issues with rmarkdown::powerpoint_presentation():

1. 'toc=TRUE' parameter does not affect a converted result.

2. Inserted citation using BiTeX (e.g., @key) does not appear in converted PPT content while it does at the end of powerpoint as a reference list.

3. `df_print: "tibble"` field in YAML causes some issue when rendered while `rmarkdown::powerpoint_presentation(df_print = "tibble")` does not.

4. `df_print: "kable"` is not automatically applied to a data.frame in Rmd document.

For example, the following is not rendered into a kable object while the df_print is set to "kable."

```
```{r example}
(x <- airquality)
class(x)
```
```

Still, you should manually surround the data.frame object with knitr::kable().

The following is my R session info.

```
> devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RTerm                       
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2018-01-26                  

Packages ----------------------------------------------------------------------
 package   * version    date       source                          
 base      * 3.4.3      2017-11-30 local                           
 compiler    3.4.3      2017-11-30 local                           
 datasets  * 3.4.3      2017-11-30 local                           
 devtools    1.13.4     2017-11-09 CRAN (R 3.4.2)                  
 digest      0.6.14     2018-01-14 CRAN (R 3.4.3)                  
 graphics  * 3.4.3      2017-11-30 local                           
 grDevices * 3.4.3      2017-11-30 local                           
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.1)                  
 methods   * 3.4.3      2017-11-30 local                           
 stats     * 3.4.3      2017-11-30 local                           
 utils     * 3.4.3      2017-11-30 local                           
 withr       2.1.1.9000 2017-12-23 Github (jimhester/withr@df18523)
```

**Comment by rich-iannone** [comment]
@jooyoungseo the Powerpoint format has its own subset of rules. A good source of documentation (which also provides some pointers on what's possible) can be found on this support page:

https://support.rstudio.com/hc/en-us/articles/360004672913-Rendering-PowerPoint-presentations-with-RStudio

Tables, in particular, can be `kable` tables, Markdown tables, or the tables specified in this Pandoc document: http://pandoc.org/MANUAL.html#tables.

**Comment by yihui** [comment]
The option `toc: true` should work. I believe I just tested not too long ago.
