### ISSUE TITLE
Error showing mathematical equations

### ISSUE THREAD

**Issue by calote** [rstudio/rmarkdown#1250]
Error showing mathematical equations in RStudio v1.2:
![rstudio_errormaths_f20180201](https://user-images.githubusercontent.com/4060891/35671100-ac72dc4c-073a-11e8-9c5f-293628927d86.png)

**Comment by yihui** [comment]
This looks like an RStudio IDE issue. Please try https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by calote** [comment]
Sorry for the inconvenience. Thanks!
