### ISSUE TITLE
How do I hide the 'Hide' button in R Markdown?

### ISSUE THREAD

**Issue by ImranAliPhD** [rstudio/rmarkdown#1251]
When I generate html output files from R notebooks, there is always a button on the top-right labeled  'Code', providing options to hide code. Then _again_ for every single code cell, there are buttons on top-right labeled 'hide', to hide the code. Both of these are really annoying and I can't believe they are supposed to be there by default. Can someone please help me in getting rid of both of these button?  [I am new to R Notebooks and I have Googled this quite a bit but all to no avail.]

**Comment by cderv** [comment]
The code folding part is by default for the `html_notebook` document format. It is not for `html_document` format. R notebook is a specific format with some defaults different from other document format. It has some specifities like preview and source Rmd code included. You could find useful information about formats on the [rmarkdown website](http://rmarkdown.rstudio.com/formats.html)

About the code folding option, you can find how it works inside the [html_document format page](http://rmarkdown.rstudio.com/html_document_format.html#code_folding). Know that you can also use these options in a `html_notebook` document. You can see all the options of the format in the [help page](https://www.rdocumentation.org/packages/rmarkdown/versions/1.8/topics/html_notebook). Each one of the argument of the `html_notebook` function can be specified in a yaml header.

Then you can either modify the default option in your yaml header
```yaml
output:
  html_notebook:
      code_folding: hide
```

or switch format for publication using `html_document` instead if this format suits best your use case.

Know also that you can have several formats in header, and choose when knitting

As a side note, know that for this type of question https://community.rstudio.com is a better place to ask. Stackoverflow too. The community is large.

**Comment by rich-iannone** [comment]
Thanks @cderv, this seems to answer the question perfectly. So, I'm closing this issue.

**Comment by hwalinga** [comment]
It almost answers the question. The right answers is as follows: 

    code_folding: "none"

**Comment by mlduarte** [comment]
> It almost answers the question. The right answers is as follows:
> 
> ```
> code_folding: "none"
> ```

That still leaves the code button there, (for me), but with the option: "Download Rmd".  Would be good to know how to remove button altogether.  Yes, I know I can use the html_document but in my case, I like the Preview option as running interactively.
