### ISSUE TITLE
Listing files in an absolute directory does not work in chunks

### ISSUE THREAD

**Issue by jzadra** [rstudio/rmarkdown#1257]
Using file listing functions such as `list.files()`, `dir()`, or `fs::dir_ls` works when executing a chunk individually, but when knitting these functions return an empty character vector.  This is despite providing the full absolute path.

**Comment by yihui** [comment]
Print out `getwd()` to see what exactly your working directory is when knitting the document.

**Comment by jzadra** [comment]
`getwd()` is my github repo, which is not where the files are.  However, I'm providing the full, absolute path to the file listing function. Shouldn't the working directory not have any bearing when using absolute paths?

**Comment by yihui** [comment]
`getwd()` in a code chunk cannot possibly return a Github repo. Try to insert `getwd()` in a code chunk, knit the document, and see what the output is.

In theory, `list.files()` with a full absolute path should work, but are you sure you provided a path that actually exists? (e.g. no typo? verify it by `dir.exists()`)

**Comment by jzadra** [comment]
Sorry, I meant my local copy of the repo.  `getwd()` returns the location of the Rmd file. (Again, this is not where the data files are)

`dir.exists()` on the path provided to the listing functions returns true when knitting. And all the code works if running it in console.

**Comment by yihui** [comment]
Okay, if possible, please show screenshots of different behaviors of `list.files()` with an absolute path in the console and in R Markdown.

**Comment by jzadra** [comment]
In console:
![image](https://user-images.githubusercontent.com/25590353/35990028-076a2760-0cc0-11e8-9021-8e4ea70e18c1.png)


Rmarkdown:


![image](https://user-images.githubusercontent.com/25590353/35990053-1980119e-0cc0-11e8-8d8f-1f4a38abb187.png)

**Comment by yihui** [comment]
Thanks! Hmm, that is interesting. Does this happen to other absolute paths that are not in the Google drive?

**Comment by jzadra** [comment]
It does not! That's the culprit.

Interesting.  If I can provide anything to help debug this let me know. I'm on OS X 10.12.6
with Google Drive File Stream 25.157.185.1505, R 3.4.0

**Comment by cderv** [comment]
@jzadra is this still an issue ? 

I can't reproduce on windows, and I don't how to on Linux. I don't have a Mac so I can't try. 

Thank you.

**Comment by jzadra** [comment]
It appears to work now.

**Comment by cderv** [comment]
Great ! 
Thanks for the report in the first place and sorry for the delay to deal with that directly.
