### ISSUE TITLE
SUGGESTION: Include the absolute/relative path in "Output created: ..." message by render()

### ISSUE THREAD

**Issue by HenrikBengtsson** [rstudio/rmarkdown#126]
In rmarkdown 0.2.46, calling

``` s
html <- render("path/to/index.md")
```

outputs message:

```
Output created: index.html
```

Although `html` contains the proper (absolute) pathname, the above message is slightly misleading when it's not specifying the path, which makes one believe it wrote the file to the current directory.  It's probably cleanest if it does so by the relative path, e.g.

```
Output created: path/to/index.html
```

Just a minor suggestion.

**Comment by yihui** [comment]
Closing this issue because of its age, and changing the output message after several new versions of RStudio IDE is probably quite risky now. Anyway, thanks for the suggestion!
