### ISSUE TITLE
Update to Bootstrap v4?

### ISSUE THREAD

**Issue by schantanu** [rstudio/rmarkdown#1260]
What is the road map to implementation of Bootstrap 4, since it has been fully released now.

I have tried replacing the Bootstrap version in "C:\Program Files\R\R~version\library\rmarkdown\rmd\h\bootstrap-3.3.5", but it has never worked in its entirety. Any suggested hacks for now?

**Comment by olgamie** [comment]
+1

**Comment by rich-iannone** [comment]
@Schantanu Thanks for the suggestion implement Bootstrap 4. We'll consider it as we work on future updates to `rmarkdown`. There has been no testing yet with Bootstrap so we are unable to provide recommendations on workarounds (and it's not advisable to manually replace the Bootstrap JS library).

**Comment by yihui** [comment]
This may be a good item for us to discuss in June during our work week. Shiny has the same issue: https://github.com/rstudio/shiny/issues/1604

**Comment by rich-iannone** [comment]
@yihui definitely!

**Comment by Schantanu** [comment]
Pretty, please. :grinning:

I have lost my sleep with sticky footer and card groups issues in Bootstrap 3.3.

**Comment by illsio** [comment]
Still +1

**Comment by royfrancis** [comment]
Just leaving a comment here.

**Comment by jayhesselberth** [comment]
I worked out BS4 migration in pkgdown and some of it may be useful.

https://github.com/r-lib/pkgdown/pull/1111

**Comment by krook1024** [comment]
I'm interested in this too.

**Comment by michaelquinn32** [comment]
Twitter has deprecated bootstrap 3.
https://github.com/twbs/release

Has there been any discussion on moving the v4?

Thanks!

**Comment by yihui** [comment]
Not yet. Sorry. I have reopened this issue for consideration next year, but I guess the actual work would not be trivial. It is even trickier with the fact that we'll also have to migrate to Bootstrap 4 together with the Shiny team.

Thanks for your patience!

**Comment by jcheng5** [comment]
FYI, my team and I have been working on this for months. We think we have a way to move everyone relatively painlessly forward to Bootstrap 4 without breaking backward compatibility for existing documents. Stay tuned.

**Comment by cderv** [comment]
For information for anyone still arriving on this old issue thread now locked, bootstrap 4 can now be used with Rmarkdown using the **bslib** package. This allows to switch to bootstrap 4 and any newer version that the **bslib** package will support.
