### ISSUE TITLE
data.frame / tibble printout for code chunks not showing grouping

### ISSUE THREAD

**Issue by jannikbuhr** [rstudio/rmarkdown#1261]
When a data frame or tibble is grouped with `dplyr`s  `group_by` function and printed out to the console, e.g.
```
data("mtcars")
mtcars %>% group_by(cyl)
```
The user gets information about the grouping, which helps to reduce errors produced by forgetting about a grouping done earlier, like this:
```
# A tibble: 32 x 11
# Groups:   cyl [3]
```
However, there is currently no way to produce this information about the grouping when displaying the data frames as chunk output in Rmd-Notebooks. This information might not be relevant for the final report created with `knitr`, but I do believe that this information would benefit the exploratory workflow when using notebooks and there should be a way to enable it documentwide.

Keep up the good work :)
Jannik

**Comment by rich-iannone** [comment]
What you need is the chunk option `paged.print=FALSE` for any chunks where you would like the console output instead of the paged table.

Hopes this solves the issue, please re-open if that's not the case.
