### ISSUE TITLE
[Feature Request] New Loading GIF

### ISSUE THREAD

**Issue by PaulC91** [rstudio/rmarkdown#1263]
Pedantic request here but would it be possible to update the 'Loading...' gif that appears prior to rendering a flexdashboard? It feels a bit outdated and pixelated compared to the 'Please wait...' version that appears on regular shiny apps.

Initially filed this in the flexdashboard repo but was advised to file here instead.

Thanks!

**Comment by yihui** [comment]
Next time it will be great if you can mention the link to your original issue: https://github.com/rstudio/flexdashboard/issues/174

Could you give a minimal example and a screenshot? I'm not sure which GIF you are talking about.

**Comment by PaulC91** [comment]
Sorry, yes. An example would be launching any flexdashboard with `runtime: shiny` in the YAML: https://jjallaire.shinyapps.io/shiny-biclust/

gives this loading icon:

![loading](https://user-images.githubusercontent.com/25231784/36443810-ab32af6a-1671-11e8-92ed-b7faaa0e1424.png)

**Comment by yihui** [comment]
Okay, that is much clearer to me. Thanks!

Just a note to myself: the gif was from
https://github.com/rstudio/rmarkdown/blob/b49b7eb92ed94/R/shiny.R#L377

**Comment by PaulC91** [comment]
Thanks Yihui!

**Comment by rich-iannone** [comment]
@PaulC91 FYI: the replacement of the gif was just merged in. Thanks for the feature request!

**Comment by PaulC91** [comment]
@rich-iannone @yihui thanks guys! much appreciated.
