### ISSUE TITLE
slide-level for powerpoint_presentation

### ISSUE THREAD

**Issue by NMarkgraf** [rstudio/rmarkdown#1270]
Hi folks!

Pandoc 2.1.1 has a very useful slide-level parameter for slide presentations. But currently this is not part of the powerpoint_presentation stuff inside rmarkdown.. So a YAMl part like

```
---
output:
  powerpoint_presentation:
    slide-level: 2
---
```

will lead to an error. - As a workaround I use currently

```
---
output:
powerpoint_presentation:
  pandoc_args:
    - --slide-level
    - 2
---
```

which also shows, that it is a known parameter by the pandoc powerpoint presentation writer.
I think it would be nice, if someone would fix it in the next release. - Thanks, and keep on going the good work!

**Comment by jjallaire** [comment]
@yihui Seems like this should be pretty straightforward to add?

**Comment by yihui** [comment]
Indeed straightforward. Will do it when I have a chance. Thanks @NMarkgraf!

**Comment by yihui** [comment]
@NMarkgraf Added in the dev version here. Could you test it? Thanks!

**Comment by jjallaire** [comment]
Thanks @yihui !

**Comment by NMarkgraf** [comment]
I would like to, but ... you need to fix the other bug too! ;-P --- I promise today!

**Comment by NMarkgraf** [comment]
Well @yihui , worked as expected! -- Thanks, a lot! - Now please the other bugs too! ;-)
