### ISSUE TITLE
Latest rmarkdown won't find any local *.sty files in base/main directory

### ISSUE THREAD

**Issue by NMarkgraf** [rstudio/rmarkdown#1273]
Hi folks,

after upgrading markdown and use tinytex I found a serious bug, I think it is one. Because I'm not sure where it needs to be fixed, I also filed a bug issue at [tinytex](https://github.com/yihui/tinytex/issues/22) .

Normally you may have a main directory in which your, lets say, test.Rmd files is. Let us guess you make a pdf (with keep_tex=true) out of it. You also uses a latex style file, name it mystyle.sty which is also in the main directory. You might render it, no problems.

BUT: If you use the latest rmarkdown and tinytex AND use an output_directory different from the main directory, you got into trouble!

I the old day, a temporary tex and pdf file was build in the main directory and moved after that into the output_directory, everything went well.
But now, it seems that you build the tex file first in the output_directory and rund latexmk (r something) on it in that directory, which is worse. Because the latex sty-files would not be in the search path of latex any more.
This is extremely annoying where you use your own beamer theme files (which are .sty files).

What might help as a quick bugfix is: Add the main directory to TEXINPUTS environment variable of the shell you use before starting any latexmk word. Something like "setenv TEXINPUTS ..:" or appropriate.

There is probably a much better solution, than my workaround... copying all tex and sty files to the output_directory is none!

Yours
Norman

**Comment by yihui** [comment]
It will be fixed in tinytex https://github.com/yihui/tinytex/issues/22. Thanks!
