### ISSUE TITLE
Bundling/licensing audit

### ISSUE THREAD

**Issue by QuLogic** [rstudio/rmarkdown#1275]
I'm trying to package rmarkdown in Fedora, but it is made a bit more difficult by the several bundled items. I have looked through `inst/NOTICE` which has been helpful but doesn't appear to cover everything. I have found at the very least, the following items in 1.7 (which I realize is a bit outdated, but there doesn't appear to be much change here):

* `inst/rmd/h/font-awesome-4.5.0/fonts/`: [fontawesome-fonts](https://fontawesome.com/) 4.5.0
* `inst/rmd/ioslides/ioslides-13.5.1/fonts/` _and_ `./inst/rmd/h/bootstrap-3.3.5/css/fonts/`:  [open-sans-fonts](https://fonts.google.com/specimen/Open+Sans) (unknown version)
* `inst/rmd/h/bootstrap-3.3.5/`: [bootstrap](https://getbootstrap.com/docs/3.3/getting-started/) 3.3.5 (MIT), plus many other fonts.
* `inst/rmd/h/highlightjs/`: [highlight](https://highlightjs.org/) 9.12.0 (BSD)
* `inst/rmd/h/ionicons-2.0.1/`: [ionicons-fonts](http://ionicons.com/) 2.0.1 (MIT)
* `inst/rmd/h/jquery-1.11.3/`: [jquery1](https://jquery.com/) 1.11.3 (MIT)
* `inst/rmd/h/jqueryui-1.11.4/`: [jqueryui](https://jqueryui.com/) 1.11.4 (MIT)
* `inst/rmd/h/tocify-1.9.1/`: [jquery-tocify](http://gregfranko.com/jquery.tocify.js/) 1.9.1 (MIT)
* `inst/rmd/ioslides/ioslides-13.5.1/`: ioslides 13.5.1 (ASL 2.0)
* `inst/rmd/ioslides/ioslides-13.5.1/fonts/SourceCodePro.ttf`: [adobe-source-code-pro-fonts](https://adobe-fonts.github.io/source-code-pro/) 1.017 (maybe) (OFL)
* `inst/rmd/ioslides/ioslides-13.5.1/js/hammer.js`: [hammer.js](https://hammerjs.github.io/) 0.4 (MIT)
* `inst/rmd/ioslides/ioslides-13.5.1/js/modernizr.custom.45394.js`: [modernizr](https://modernizr.com/) 2.5.3 (MIT & BSD)
* `inst/rmd/ioslides/ioslides-13.5.1/js/{require-1.0.8.min,order}.js`: [requirejs](http://requirejs.org/) 1.0.8 (MIT | BSD)
* `inst/rmd/ioslides/ioslides-13.5.1/js/prettify/`: [code-prettify](https://github.com/google/code-prettify) (MIT)
* `inst/rmd/slidy/Slidy2/`: [slidy 2](https://www.w3.org/Talks/Tools/Slidy2/) (W3C)

Do I have the right sources for everything? Have I missed anything?

**Comment by rich-iannone** [comment]
@QuLogic 

I've got this list:

```
bootstrap-3.3.5
font-awesome-4.5.0
highlightjs
ionicons-2.0.1
jquery-1.11.3
jqueryui-1.11.4
navigation-1.1
pagedtable-1.1
rmarkdown
rsiframe-1.1
tocify-1.9.1
ioslides-13.5.1
OpenSans.ttf
OpenSansItalic.ttf
OpenSansSemibold.ttf
OpenSansSemiboldItalic.ttf
SourceCodePro.ttf
fonts.css
hammer.js
modernizr.custom.45394.js
require-1.0.8.min.js
slide-controller.js
slide-deck.js
Slidy2
```

Please note that some JS scripts have been edited for R Markdown (`slidy.js` is one example of this).

**Comment by QuLogic** [comment]
How about files in `inst/rmd/ioslides/ioslides-13.5.1/js/polyfills`? There are minified, but no original sources.

I do not think I will unbundle most things, so the edits are mostly fine, but I do need to provide original, non-minified sources.

**Comment by QuLogic** [comment]
Actually these files seem unreferenced, perhaps they can be removed?

**Comment by QuLogic** [comment]
`inst/rmd/ioslides/ioslides-13.5.1/js/order.js` and `inst/rmd/ioslides/ioslides-13.5.1/js/require-1.0.8.min.js` are also minified, but appear unused?
