### ISSUE TITLE
[Feature Request]: export tables as standalone pdf files?

### ISSUE THREAD

**Issue by sjkiss** [rstudio/rmarkdown#1277]
Would it be possible to have RMarkdown export tables as stand-alone pdfs in the way that plots are exported? I know I can render documents to word and generate tables in word, but sometimes I like generating LaTeX tables and then inserting them into Word documents. Now, I generate a separate pdf that contains plots and tables and take screenshots of the tables and insert them into Word documents.

**Comment by sjkiss** [comment]
I tried this but couldn't get it to work [https://tex.stackexchange.com/questions/140796/generating-a-separate-pdf-file-of-tables-and-figures-from-a-latex-file](url)

**Comment by cderv** [comment]
Some time has passed and now I would have a look at the **gt** package where you can export a table to a file. 
https://gt.rstudio.com/reference/gtsave.html

Maybe other table framework have such feature.
https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html
