### ISSUE TITLE
[Bug] Rstudio freezes when first time creating new RMarkdown files when the computer is in a closed network

### ISSUE THREAD

**Issue by madcarrot** [rstudio/rmarkdown#1279]
I am working under company network which blocks the CRAN R mirrors. When I tried to create a new RMarkdown file, R freezes, because it needed to install two extra packages, and it cannot establish a link to any of the mirrors. However, even when the warning about connection pops up, it kept being frozen. It's only when I connected to external network did it finally installed the required packages and start.

I think this counts as a bug as it's really hard to understand what's going on for novice users. I would like to suggest putting all the required packages for Rstudio to create RMarkdown files in the requirement for installing the `rmarkdown` package, or stop Rstudio from attempting to connect to a CRAN R mirror when the connection times out.

**Comment by yihui** [comment]
I think this issue belongs to the RStudio IDE: https://github.com/rstudio/rstudio

**Comment by yihui** [comment]
It should be reported there. If confirmed as an IDE issue there, we can close this one and let the OP watch the Github issue there.

**Comment by rich-iannone** [comment]
Okay, I'll post it there and cc the OP to make aware of the location.

cc @madcarrot

**Comment by madcarrot** [comment]
@yihui @rich-iannone Thanks so much!
