### ISSUE TITLE
yeti theme is not actually available

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#128]
The yeti theme is listed as a valid theme, but I can't use it. A minor issue.

I'm not sure if this is the place to report but the theme is promised here in the R Markdown v2 web docs:
http://rmarkdown.rstudio.com/html_document_format.html

```
Error in match.arg(theme, themes()) : 
  'arg' should be one of “default”, “cerulean”, “journal”, “flatly”, “readable”, “spacelab”, “united”, “cosmo”
Calls: <Anonymous> -> <Anonymous> -> base -> match.arg
Execution halted
```

RStudio Version 0.98.913. rmarkdown_0.2.46

**Comment by englianhu** [comment]
Tried to add 3D visualization css `luman` but failed. System prompted me below error and the folder and css file auto deleted once I `knit HTML`.
<http://rmarkdown.rstudio.com/html_document_format.html#appearance-and-style>
![rmarkdown theme](https://cloud.githubusercontent.com/assets/7227582/10425557/841fb0b8-7113-11e5-8c87-5d3eb0c63fa2.jpg)

**Comment by jjallaire** [comment]
Yes, you shouldn't place user CSS in the _files directory as it does get
deleted during preview. Rather, you should place it alongside the Rmd or
even within another subdirectory (e.g. "styles" or "css")
