### ISSUE TITLE
MathJax does not render when using a local copy

### ISSUE THREAD

**Issue by pat-s** [rstudio/rmarkdown#1283]
https://github.com/yihui/xaringan/issues/119

Maybe related: https://github.com/mathjax/MathJax/issues/1934

MathJax.js: https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML

Reprex:

    ---
    title: "Untitled"
    output: 
      html_document:
        toc: true
        mathjax: "<path>/MathJax.js"
    ---

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```

    ## R Markdown

    ```
    $$\bar{X}=\frac{1}{n}\sum_{i=1}^nX_i$$
    ```

    $$\bar{X}=\frac{1}{n}\sum_{i=1}^nX_i$$

When using `xaringan` it additionally shows the following JS errors:

```
libs/extensions/MathMenu.js?V=2.7.1 Failed to load resource: the server responded with a status of 404 (Not Found)
libs/extensions/MathZoom.js?V=2.7.1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

However, solving these has no effect.

**Comment by rich-iannone** [comment]
@pat-s  Thanks for this. Is there any reason why you would want to use a local copy of MathJax?

**Comment by N0rbert** [comment]
This problem is very actual. `bookdown::html_document2` or simple `html_document` may be shown on device without internet (completely offline), so self_contained or something is needed for MathJax.

**Comment by pat-s** [comment]
> @pat-s Thanks for this. Is there any reason why you would want to use a local copy of MathJax?

People need it for self-contained offline presentations using `xaringan`. 

I do not know why its so difficult to link to a local copy of Mathjax whereas linking to other JS libraries is usually not a big deal. Could you share some details here?

**Comment by yihui** [comment]
@pat-s Note that `mathjax='local'` is not implemented in **xaringan**. Feel free to study the source code of rmarkdown and implement it in **xaringan**.

**Comment by rich-iannone** [comment]
@jjallaire I just tried using the local option with `self_contained: false`. The equations don't appear to render in the preview doc but they do appear in the final HTML file.

This is the .Rmd:

````
---
title: "Habits"
output:
  html_document:
    mathjax: local
    self_contained: false
---

We can use inline equations such as $y_i = \alpha + \beta x_i + e_i$

$$3^2+4^2=5^2$$
````

This is the preview:

<img width="1677" alt="rmd_mathjax_local_preview" src="https://user-images.githubusercontent.com/5612024/40075625-a1318c96-5831-11e8-9de4-7d568ec70730.png">

The rendered HTML document gives:

<img width="1011" alt="rmd_mathjax_local_final_html" src="https://user-images.githubusercontent.com/5612024/40075697-c8ad3de2-5831-11e8-9314-49f53401ac53.png">

So, the preview here is problematic. I feel like this is a separate issue. Should I file it as such?

**Comment by N0rbert** [comment]
@rich-iannone - see my [comment on related issue](https://github.com/yihui/xaringan/issues/119#issuecomment-381722720).

**Comment by jjallaire** [comment]
I would take a look at the JS debugging tools to see if you can get to the bottom of what's going on.

**Comment by rich-iannone** [comment]
@jjallaire will do.

**Comment by jhuntergit** [comment]
Not sure if it's for the same reason, but LaTeX equations won't render for me in blogdown when I'm offline. When I `blogdown::serve_site()` LaTeX equations such as the following won't render:

`$$\sigma = \sqrt{ \sum_{i=1}^N \frac{(x_i - \overline{x})^2}{N}}$$`

When I'm back online the same equation renders without issue.

**Comment by bonedog32** [comment]
I am having a similar problem on my blog (using theme gohugo-theme-ananke). In the near past the math rendered fine, but now earlier posts I have made no longer show correctly rendered equations. Not sure exactly when this happened, but tried a new post yesterday and discovered the issue. What I see is this: 'blogdown::build_dir("./content/post/")' renders the math. However, when I then run 'blogdown::serve_site()' the correctly rendered math now does not render and comes out as $$formula$$ or \[formula\]. Anyone have an idea why the rendering would suddenly just stop working? Also, now, the uploaded files to github and then netlify are also not rendering. I don't know if this may be related to Hugo or not. Don't have much hair, so not pulling it out.

**Comment by py9mrg** [comment]
Why not add support for KaTeX? It's been mentioned already as a [feature request for Bookdown](https://github.com/rstudio/bookdown/issues/401) and seems like it would solve a lot of the issues of trying to use MathJax in offline and/or self contained documents?

**Comment by atusy** [comment]
I opened PR #1940 to solve this.

**Comment by cderv** [comment]
We have now included broader support for HTML math method as supported by Pandoc (https://pandoc.org/MANUAL.html#math-rendering-in-html). 

This include better support for other engine that does not load a JS library (like `webtex`) which can help when local is prefered. 

Also https://github.com/rstudio/rmarkdown/pull/2215 will bring support for using the **katex** R package which will allow to have server side rendering of maths, which will be best when local is required.
