### ISSUE TITLE
find_external_resources needs pandoc 2.0 fix

### ISSUE THREAD

**Issue by hadley** [rstudio/rmarkdown#1290]
```R
rmarkdown::find_external_resources("~/Documents/tidyverse/purrr/README.Rmd")
#> [WARNING] This document format requires a nonempty <title> element.
#>   Please specify either 'title' or 'pagetitle' in the metadata.
#>   Falling back to 'file35ae52634c27.utf8'
#>                   path explicit  web
#> 1 man/figures/logo.png    FALSE TRUE
```

I think the documentation should also mention that pandoc is run, as I found that somewhat surprising.

**Comment by yihui** [comment]
@rich-iannone I think this will be a relatively easy fix (see 6558c3ce3d785133182b12a161fcc4928829e537). Could you do it?

**Comment by rich-iannone** [comment]
Yes! I will do it.

**Comment by rich-iannone** [comment]
@yihui when I was reproducing this output, I got regular output without a warning:

```
rmarkdown::find_external_resources("~/Documents/tidyverse/purrr/README.Rmd")
#>                   path explicit  web
#> 1 man/figures/logo.png    FALSE TRUE
```

To reproduce I downloaded a zip of the purrr repo and placed in my file system in the same location so that the same path to file works. Could it be that this is already fixed, or am I missing something?

**Comment by yihui** [comment]
@rich-iannone I believe @hadley was using Pandoc 2.x.

**Comment by rich-iannone** [comment]
@yihui thanks for that. Will install v2+ Pandoc and then get back into the issue.
