### ISSUE TITLE
[DOC] unclear behaviour when both output_dir and output_file are provided

### ISSUE THREAD

**Issue by NelleV** [rstudio/rmarkdown#1292]
One can both provide output_dir and output_file at the same time. How `rmarkdown::render` behaves is right now unclear in the documentation.

**Comment by rich-iannone** [comment]
@NelleV Thanks for opening this issue awhile back. It's now being addressed in a pull request.

**Comment by NelleV** [comment]
Thanks for letting me know!

**Comment by rich-iannone** [comment]
You're welcome. It's just been merged into the dev version of R Markdown.
