### ISSUE TITLE
pandoc errors from render() when intermediates_dir and output_dir != input dir

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#130]
Using `rmarkdown_0.2.46`.

Re: `render()`

I find that it is very brittle when setting `intermediates_dir` and `output_dir` to values other than the directory of the input source.

Specifically, almost any setting for `intermediates_dir` causes pandoc to give a fatal error about not being able find a file it needs.

Also, if sending intermediate files and html files to the same, non-source directory, I get similar errors, unless there's a happy coincidence re: where that directory is in the hierarchy.

I made a small repository that reproduces the errors:
https://github.com/jennybc/arms-length-render

and the `README.md` gives the beginnings of a diagnosis and fix.

This comes up in projects with nontrivial directory structure and where you want to save intermediate Markdown, due to the benefits on GitHub. I use a generic `.rmd` file to process many input datasets. I do this via a wrapper script that takes the data file as a command line argument and programmatically constructs the path and filenames for the intermediates and outputs.

One last thing re: intermediate files. When `clean = FALSE` in `render()`, `foo.rmd` leads to `foo.knit.md` and then `foo.utf.md`. This is kind of unfortunate for the GitHub workflow where the intermediate Markdown is precious. I'd much prefer to be left with a file named just `foo.md`.

**Comment by jmcphers** [comment]
Should be fixed via https://github.com/rstudio/rmarkdown/pull/431.
