### ISSUE TITLE
Feature request: Support for row sorting and filtering in df_print: paged 

### ISSUE THREAD

**Issue by mehmetaergun** [rstudio/rmarkdown#1309]
RStudio's View() function (as an example) supports the ability to interactively sort and filter rows per each column. 

It would be very useful if this could be implemented in df_print:paged for html_documents and html_notebooks. Currently, I believe one has to embed a shiny code chunk to accomplish this task, which I think makes it cumbersome to print a data.frame (including from e.g. a python or sql chunk) and sharing a self-contained document. 

Thank you :)

**Comment by cderv** [comment]
> Currently, I believe one has to embed a shiny code chunk to accomplish this task

You can use htmlwidgets without having shiny code. I have in mind [DT](https://rstudio.github.io/DT/) 📦 . Have you tried it already ? There is no shiny needed. Just a call to `DT::datatable`

![image](https://user-images.githubusercontent.com/6791940/38163987-72d896de-34fd-11e8-85b1-f8b127eed1e7.png)

The document could be self contained. However, this would mean that the DT js library would be included in the html file, and the data too. 

Know that this 📦 offers a lot of options to customize table functionality. 

Is this the kind of things you are looking for ?

**Comment by mehmetaergun** [comment]
That is most helpful and comes very close to what I was looking for :) 

It does replicate RStudio's View(df) window for R chunks,

![image](https://user-images.githubusercontent.com/767161/38197860-43acbf14-3658-11e8-9f4d-9e06e10c9c86.png)

but I usually weave my code with sql (and sometimes python) chunks along with R chunks, all of which usually print a data frame at some point. The DT approach works perfectly (thank you for the pointer!) for R chunks, but seems not to work for sql and python chunks? 

Attached is an example, where I would prefer not to wrap the sql chunk (in section 2) with DT inside an R chunk (like in section 5). 

[test_dfprint_sqlite.nb.zip](https://github.com/rstudio/rmarkdown/files/1868256/test_dfprint_sqlite.nb.zip)

(Hopefully I am not wasting your time with this.)

**Comment by rich-iannone** [comment]
@mehmetaergun I think that as @cderv mentioned, **DT** is the main route for getting this table functionality. For SQL and Python chunks, I'd think that collecting output then using a separate R chunk with `DT::datatable` is not a bad way to go. I'll look into whether this can be made more direct in the future, but closing this for now.
