### ISSUE TITLE
Bug Report: When making PDF documents, modifying the geometry: margin=.20in causes plots to plot outside of the pdf.

### ISSUE THREAD

**Issue by mad100141** [rstudio/rmarkdown#1310]
````
---
title: "Test"
output: 
  pdf_document: default
geometry: margin=0.20in
---

```r
library(gam)
model = gam(data = abalone, Y ~ x1+x2+x3+x4+x5)
plot.Gam(model)
```
````
The plots that are plotted outside of the pdf window aren't the ones that you use par to set, this one by default outputs 5 plot on the rmd page but when I run the pdf the plots are show outside the pdf.
![image](https://user-images.githubusercontent.com/11380888/38144298-29b24e0a-3412-11e8-9410-63704618e9c7.png)

**Comment by rich-iannone** [comment]
@mad100141 This looks to be an RStudio IDE issue. Could you please re-post this issue in `rstudio/rstudio`? I'm going to close it here.

**Comment by yihui** [comment]
Actually this is irrelevant to the RStudio IDE. It just happens that the margin of 0.20in makes the page wide enough for one plot, but not enough for two, but LaTeX is not smart enough in this case to break the second plot into the next line. I don't have a good solution here. The worst case is you draw these four plots one by one, and insert new lines among them (`cat('\n\n')`).

BTW, that was not a minimal example (requires the **gam** package). Here is a minimal one:

````
---
title: "Test"
output: 
  pdf_document: default
geometry: margin=0.20in
---

```{r}
fit = lm(dist ~ speed, data = cars)
plot(fit)
```
````

**Comment by rich-iannone** [comment]
@mad100141 Sorry for the mixup, please don't post an issue in `rstudio/rstudio`. Perhaps use @yihui's workaround for the plotting.

**Comment by yihui** [comment]
The other workaround is to set `out.width`, e.g.,

````
---
title: "Test"
output: pdf_document 
geometry: margin=0.20in
---

```{r out.width='50%'}
fit = lm(dist ~ speed, data = cars)
plot(fit)
```
````
