### ISSUE TITLE
Last plot of several in a chunk renders at a smaller size

### ISSUE THREAD

**Issue by daviesbj** [rstudio/rmarkdown#1314]
```r
devtools::install_github("rstudio/rmarkdown")
```

This fragment, when executed in an Rmarkdown html_notebook, demonstrates a bug with the last of a series of comparable plots coming out at a different size

```{r bug_demo}
for ( iPower in 1:5 )
  plot( 1:10, (1:10)^iPower ) # 5 vacuous x-y plots
```

This produces a plot panel in the rendered notebook with five "plot icons". When I inspect them, the last one is smaller (or maybe it's doing the others too large -- they go all the way to the right margin)

<img width="1092" alt="screen shot 2018-04-02 at 11 51 36" src="https://user-images.githubusercontent.com/7505182/38193887-520eb8fa-366c-11e8-8951-74b1b3ac7fa8.png">

<img width="1072" alt="screen shot 2018-04-02 at 11 51 52" src="https://user-images.githubusercontent.com/7505182/38193892-56e8512e-366c-11e8-8cfc-92478668bc64.png">

Low-Impact bug, not a showstopper.

I'm running in Rstudio 1.1.442 on MacOs 10.13.3 with all packages updated to current versions immediately before testing the bug & submitting this report.

**Comment by yihui** [comment]
This is likely to be an RStudio IDE issue.

**Comment by rich-iannone** [comment]
@yihui I'm also thinking the same.

@daviesbj would you be able to re-post this in `rstudio/rstudio`? Then you can track the issue toward resolution in that repo. Because there is nothing that can be done here, I'll close the issue.
