### ISSUE TITLE
How do I hide the all output of the R chunk using hide button?  

### ISSUE THREAD

**Issue by lida-R** [rstudio/rmarkdown#1317]

**Comment by lida-R** [comment]
I have a R chunk creates different plots using loop and would like to collapse/hide all of the outputs using hide button. I used the script in "https://stackoverflow.com/questions/42630248/collapsing-hiding-figures-in-r-markdown " and it works correctly when I have one output in R chunk but not for multi ones. Just it can collapse/hide the first result of the loop. I appreciate your help.

**Comment by rich-iannone** [comment]
@lida-R would you be able to share the document you are trying to run (or at least another small example doc that reproduces the issue)?

**Comment by lida-R** [comment]
Thank you, I solved it.

**Comment by rich-iannone** [comment]
@lida-R Great!
