### ISSUE TITLE
Feature request: Support for customizing default SQL Code Chunk

### ISSUE THREAD

**Issue by j450h1** [rstudio/rmarkdown#1318]
I don't want to specify the `connection = ` everytime I create a new sql chunk. So I have this set in the setup chunk as such:

\`\`\`{r setup, include=FALSE}
knitr::opts_chunk$set(connection = "rodbc")
\`\`\`

The problem is when I add a new sql chunk, through **Insert** it returns:

\`\`\`{sql connection=}

\`\`\`

So I have to still specify the connection anyways or delete the connection part....

**Comment by yihui** [comment]
I think this is an IDE issue and should be filed to https://github.com/rstudio/rstudio/issues instead.

**Comment by rich-iannone** [comment]
@j450h1 Jas, could you create this issue in https://github.com/rstudio/rstudio/issues as @yihui mentioned? That way you can follow the issue in that repo. I'm closing it here.
