### ISSUE TITLE
problems trying to knit markdown to pdf file

### ISSUE THREAD

**Issue by Fraggle2911** [rstudio/rmarkdown#1323]
I am trying to knit my rmarkdown document to a pdf but when I try i am getting
Error in table.  How do i fix this?

**Comment by Fraggle2911** [comment]
I am getting a message reading - Error in read_csv(file.choose()) : could not find function read_csv(file.choose()) : <Anonymous> ... could not read handle -> withCllingHandlers -> withVisible -> eval -> eval  Execution halted

**Comment by condwanaland** [comment]
Again, could you please provide a _reproducible_ example. It's hard to look at this just from the error message. 

Have you added `library(readr)` either to the setup chunk or to the chunk where you call `read_csv(file.choose())`?

**Comment by rich-iannone** [comment]
@Fraggle2911 if this is still an issue, please respond with a reproducible example. As soon as this issue goes to 20 days, it will be closed. (You can always open a new issue beyond that time, of course.)

**Comment by rich-iannone** [comment]
This is being closed due to lack of response.
