### ISSUE TITLE
renderText ejects header class into document

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rmarkdown#133]
When I place reactive text into a header, it appears and reactivity works. However, part of the html also appears in the document, which looks bad.

For example, this .Rmd file

``````

---
title: "Hurricanes"
runtime: shiny
output: html_document

---

Between 1995 and 2005, 79 "named" storms developed in the Atlantic Ocean.
These are storms that reached Tropical Depression status or greater.

```{r echo = FALSE}
selectInput("data", "Choose a state to explore:", choices = state.name)
```

## `r renderText(input$data)`
``````

renders as 

![screen shot 2014-06-18 at 11 13 37 am](https://cloud.githubusercontent.com/assets/85014/3315624/ae9386c8-f6fb-11e3-8e33-339fdfed266c.png)

**Comment by yihui** [comment]
This will be fixed by #1131.
