### ISSUE TITLE
Add support for Font Awesome 5?

### ISSUE THREAD

**Issue by andrewheiss** [rstudio/rmarkdown#1334]
Beginning with v5.0.11, Font Awesome includes an icon for R (!!) (see [here](https://fontawesome.com/icons/r)). 

As of v1.9, RMarkdown automatically bundles Font Awesome v4.5. Given that Font Awesome 5 has been out for a few months now and is stable, it would be nice to have support for it in RMarkdown (perhaps as an option in `_site.yml` or in YAML frontmatter in individual Rmd files, like `font-awesome: 4` or `font-awesome: 5`)

**Comment by rich-iannone** [comment]
@andrewheiss This has been addressed in a recent PR that was just merged. Thanks for the suggestion!
