### ISSUE TITLE
Vertical spacing after htmlwidgets

### ISSUE THREAD

**Issue by aoles** [rstudio/rmarkdown#1343]
Hi,

Similar to paragraphs or code chunks, I believe html widgets should have the small 10px spacer between the bottom of the widget and the succeeding content. Otherwise they "stick" on top of the blocks following them, as it is currently the case (see the example bellow). This could be easily fixed by adding the CSS rule to the default HTML template:

```css
.html-widget {
  margin: 0 0 10px;
}
```

I'm looking forward to your thoughts on this.

Best,
Andrzej

````
---
output: html_document
---

```{r}
library(DT)
datatable(cars)
```

```{r}
library(leaflet)
leaflet() %>% addTiles()
```

```{r}
## code
```
````

<img width="883" alt="widgets" src="https://user-images.githubusercontent.com/6545356/39987753-ceb17fe0-5765-11e8-8424-a4166544ae72.png">

**Comment by jjallaire** [comment]
I agree. Here's a PR to address this: https://github.com/rstudio/rmarkdown/pull/1344
