### ISSUE TITLE
Vertical space in place of float in PDF output

### ISSUE THREAD

**Issue by wuffi** [rstudio/rmarkdown#1345]
When having a plot or image between two parts of text in a *.Rmd file, the generated LaTeX file for PDF output will have a blank lines before and after the figure environment storing this float.
Therefore, if LaTeX's algorithms move the figure to the top or bottom of the page, there will be a space between the 2 paragraphs, which looks strange and is not intended.
It would be great, if the LaTeX's `figure` environment would not be surrounded by blank lines, because then there wouldn't be the vertical space between the two parts of text.  
Those who want could still enter a blank line between the parts of the text to have it also in the PDF file in the end.

Minimal example:

    ---
    output: pdf_document
    ---
    
    This is my first paragraph. 
    Next in the Rmd file would be the code for the figure.  
    The figure is correctly treated as a float by LaTeX, meaning that LaTeX will put it to the next suitable position.
    ```{r pressure, echo=FALSE, fig.cap="Example", out.width='0.5\\textwidth', fig.pos='B'}
      plot(pressure)
    ```
    The problem now is, that this leaves space to my second paragraph.
    Usually, this should not be the case.
    In pure LaTeX, there is a linebreak, of course, but no vertical space in addition.

**Comment by yihui** [comment]
Your minimal example does not compile, and the error message is:

```
! LaTeX Error: Unknown float option `B'.
```

**Comment by wuffi** [comment]
Hi Yihui,
For me it compiles fine:

    setting  value                       
    version  R version 3.2.2 (2015-08-14)
    system   x86_64, linux-gnu           
    ui       RStudio (1.1.423)           
    language (EN)                        
    collate  de_DE.UTF-8                 
    tz       Europe/Berlin               
    date     2018-05-14      

You could try a smallcap like in `fig.pos='b'`

**Comment by yihui** [comment]
The vertical space is just the natural space between paragraphs in LaTeX. You can see it if you add a third paragraph:

![image](https://user-images.githubusercontent.com/163582/40012097-40cca9ca-576f-11e8-8a0d-8588f310caa9.png)


The LaTeX output from the above Rmd example (with `fig.pos='b'`) is:

```tex
\begin{document}

This is my first paragraph. Next in the Rmd file would be the code for
the figure.\\
The figure is correctly treated as a float by LaTeX, meaning that LaTeX
will put it to the next suitable position.

\begin{figure}[b]
\includegraphics[width=0.5\textwidth]{test_files/figure-latex/pressure-1} \caption{Example}\label{fig:pressure}
\end{figure}

The problem now is, that this leaves space to my second paragraph.
Usually, this should not be the case. In pure LaTeX, there is a
linebreak, of course, but no vertical space in addition.

\end{document}
```

You seem to imply that the figure should not introduce a new paragraph, i.e., your whole document is a single paragraph (which is the case in the Rmd source document). Unfortunately that is not possible, and we don't have control over the behavior. Pandoc introduced the blank lines (there might be a way to inhibit the blank lines -- I'm not sure) when converting the intermediate Markdown code to LaTeX:

```md
This is my first paragraph. 
Next in the Rmd file would be the code for the figure.  
The figure is correctly treated as a float by LaTeX, meaning that LaTeX will put it to the next suitable position.
\begin{figure}[b]
\includegraphics[width=0.5\textwidth]{test_files/figure-latex/pressure-1} \caption{Example}\label{fig:pressure}
\end{figure}
The problem now is, that this leaves space to my second paragraph.
Usually, this should not be the case.
In pure LaTeX, there is a linebreak, of course, but no vertical space in addition.
```

The only possibility that I can see is that you do not put the figure in the middle of a paragraph. It will float away anyway.

````md
---
output: pdf_document 
---

This is my first paragraph. 
Next in the Rmd file would be the code for the figure.  
The figure is correctly treated as a float by LaTeX, meaning that LaTeX will put it to the next suitable position.
The problem now is, that this leaves space to my second paragraph.
Usually, this should not be the case.
In pure LaTeX, there is a linebreak, of course, but no vertical space in addition.

```{r pressure, echo=FALSE, fig.cap="Example", out.width='0.5\\textwidth', fig.pos='b'}
  plot(pressure)
```
````
