### ISSUE TITLE
Wrong encoding for characters with umlauts in parameters in YAML

### ISSUE THREAD

**Issue by christianlindell** [rstudio/rmarkdown#1346]
I'm am trying to use parameters with in YAML, but when I use swedish characters somthing goes wrong with the encoding, I'm using Windows 10:

Example:

```
---
title: "test_yaml_encoding"
output: html_document
params:
  swe_chars_param: "åäöÅÄÖ"
---

r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
print(params$swe_chars_param)
```
Result:

[1] "Ã¥Ã¤Ã¶Ã…Ã„Ã–"

The problem seems to be similar to a closed bug:
https://github.com/rstudio/rmarkdown/issues/420 

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_10.0.7     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.19    knitr_1.20

**Comment by christianlindell** [comment]
Sorry for the cross-posting. I didn't mean to cause you extra work. 

I just publised a realy ugly quick fix on https://community.rstudio.com/t/text-encoding-for-swedish-characters-goes-wrong-in-yaml/8417/2 .  It doesn't solve the real problem with encoding in YALM, but it worked as a quick fix to correct the encoding so I can use parameters i the YALM.

**Comment by cderv** [comment]
> But I just noticed that it works when I knit the code, but not when I run it. Strange!

It works ok if I click the knit button and render the document. What do you mean by run it ? 

I'll close as I can't reproduce this so it may be fixed. Please reopen if this is still an issue for you. Thank you.
