### ISSUE TITLE
document which bootswatch version is currently default

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#1347]
The [documentation](https://rmarkdown.rstudio.com/html_document_format.html#appearance_and_style) states that `rmarkdown::html_document()` currently defaults to Bootswatch themes.

I *think* this is referring to [Bootswatch 3.x](https://bootswatch.com/3/), but I'm not quite sure.

The Bootswatch link on the [docs](https://rmarkdown.rstudio.com) however, goes to the current Bootswatch 4.x, which might confuse people (it did confuse me).

Would be nice to have this link (to Bootswatch 3.x) in the docs (online and in `man/`) so that folks are looking in the right place, when they want to use some of the included CSS classes.

I'll be happy to add this via PR, but couldn't find the source repo for https://rmarkdown.rstudio.com.

**Comment by rich-iannone** [comment]
Hi @maxheld83 , I just made a PR to address this. Thanks for the suggestion. FYI, the location of the site content is in the branch `gh-pages`.

**Comment by rich-iannone** [comment]
and... PR is now merged. Cheers.
