### ISSUE TITLE
Apply theme when using vignette builder 

### ISSUE THREAD

**Issue by hettling** [rstudio/rmarkdown#1357]
I'm writing a vignette for [my package](https://github.com/naturalis/nbaR) and want to specify a theme and some settings like toc, etc. 
If I build the vignette with ```rmarkdown::render```, everything works and the theme is applied to the vignette:

```rmarkdown::render("vignettes/nbaR.Rmd")```

However, when I want to use the vignette builder specified in my package, the theme is not rendered, e.g. with 

```R CMD build . && R CMD INSTALL nbaR_0.0.0.tar.gz```

or with

```devtools::install_github("naturalis/nbaR", build_vignettes=T)```

so I guess `rmarkdown::render` is not used when building the vignette. In my `DESCRIPTION`, I have

```VignetteBuilder: knitr```

[Here the related question on SO](https://stackoverflow.com/questions/50394988/rmarkdown-theme-not-applied-in-vignette-using-r-cmd-build)

How can I make the theme render when using e.g. ```install_github```? Many thanks in advance!

**Comment by yihui** [comment]
Please delete the HTML output file in the `vignettes/` folder, and see my comment at https://stackoverflow.com/questions/50394988/rmarkdown-theme-not-applied-in-vignette-using-r-cmd-build#comment87992825_50488466
