### ISSUE TITLE
two bibliography entries fails

### ISSUE THREAD

**Issue by jackwasey** [rstudio/rmarkdown#1358]
Originally filed under `rticles` package, but appears to be a `rmarkdown` issue: https://github.com/r-lib/pkgdown/issues/657

I have two valid bibtex files, which build fine with a vignette with YAML header like:
```
bibliography:
  - one.bib
  - two.bib
```

`pkgdown` will only build the corresponding article if _either_ of the bib files is present, but fails with pandoc-citepro error 83 when both are present, stating that one.bib is not found if both are present.

Concatenating one.bib and two.bib into all.bib makes it work fine. Could this be related to #658, in that if only one YAML entry is expected, the YAML is misinterpreted.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
