### ISSUE TITLE
Interplay of header-includes, extra_dependencies, and in_header in pdf_document()

### ISSUE THREAD

**Issue by crsh** [rstudio/rmarkdown#1359]
Hi,

I've noticed some unexpected interplay between the different methods of customizing the document preamble in PDF documents. `header-includes` and `includes: in_header` both work individually, but when I use both `header-includes` appears to be ignored:

~~~yaml
---
title: "Untitled"
output: 
  pdf_document:
    keep_tex: true
    includes:
      in_header: preamble.tex

header-includes:
  - \usepackage{booktabs}
---
~~~

`preamble.tex` could for example simply contain

~~~tex
\usepackage{tabulary}
~~~

However, once I include the additional `extra_dependencies` everything is included.

~~~yaml
---
title: "Untitled"
output: 
  pdf_document:
    keep_tex: true
    extra_dependencies:
      - tabularx
    includes:
      in_header: preamble.tex

header-includes:
  - \usepackage{booktabs}
---
~~~

Is this intended behavior? To me it would be useful and less confusing if these three approaches could be used independently of one another.

**Comment by crsh** [comment]
Hi, sorry to bother again. In case this is not intended behavior, I'd be willing to contribute a pull request to fix this. Any pointers as to where this could originate would be appreciated.

**Comment by mnazarov** [comment]
This is actually an issue upstream in `pandoc` - see https://github.com/jgm/pandoc/issues/3139 and links from there

**Comment by dmurdoch** [comment]
One other observation:  if you include `extra_dependencies` in the `pdf_document` call, then inline R code in the `header-includes:` field is not executed.  For example, this works:

    ---
    output: 
      pdf_document:
        keep_tex: true
    header-includes: 
      - \usepackage{fancyhdr}
      - \pagestyle{fancy}
      - '`r paste0("\\fancyhead[CO,CE]{", params$figureno, "}")`'
    params:
      figureno: "Fig. 1-1"
    ---

but this doesn't:

    ---
    output: 
      pdf_document:
        keep_tex: true
        extra_dependencies: fancyhdr
    header-includes: 
      - \pagestyle{fancy}
      - '`r paste0("\\fancyhead[CO,CE]{", params$figureno, "}")`'
    params:
      figureno: "Fig. 1-1"
    ---

If you look at the generated `.tex` file in the second one, you can see that the R code was never executed, and the literal string including it was inserted into the header.

    This is some text.

**Comment by pauljohn32** [comment]
Problem still exists in pandoc-2.7.   My document which has a template and an includes statement:
output:
  pdf_document:
    citation_package: natbib
    fig_caption: true
    highlight: haddock
    keep_tex: true
    latex_engine: pdflatex
    pandoc_args: [--listings]
    template: "theme/report-template.tex"
    includes:
      in_header: "theme/guidePreambleKnitr.tex"

was failing to run the "header-includes: " section.  I solve problem in short term by following your fix to add an extra_dependencies flag.

This is a bad bug for me and I was having a hard time figuring it out until I found this post.  Thanks very much to the original poster.  I've grown frustrated with relying on pandoc because of problems like this.

**Comment by yihui** [comment]
As @mnazarov pointed out, this was by design of Pandoc. I agree it is confusing, so I just pushed a fix to always include the code from the `header-includes` field in the LaTeX preamble. Thanks for the report!
