### ISSUE TITLE
Conflicts between `header-includes` and certain packages

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rmarkdown#1368]
The rmarkdown fails to compile and leads to a Latex error when adding `header-includes` and certain packages such as `kableExtra` package. Here's a sample code:

````
---
title: "Untitled"
header-includes:
- |
  ```{=latex}
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  ```
output: pdf_document
---

```{r setup, include=FALSE}
library(kableExtra)
```
````

The compiled file led to a `LaTex Error`:

````
! LaTeX Error: Missing \begin{document}.

Error: Failed to compile test.tex. See test.log for more info.
Execution halted
````

If moving `library(kableExtra)` or changing to other package, the file compiled smoothly.

**Comment by yihui** [comment]
I strongly recommend you to put the content of `header-includes` in an external file, and include it via the `includes: in_header` option of `pdf_document`.

That said, it could be a bug, which I don't have time to investigate. Perhaps @haozhu233 has an idea.

**Comment by haozhu233** [comment]
@sammo3182 I don't think you are using the correct syntax for header-includes:

````
---
title: "Untitled"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
output: pdf_document
---

```{r setup, include=FALSE}
library(kableExtra)
```
````

**Comment by sammo3182** [comment]
Thank you for pointing this out, @haozhu233. However, using your way, the `\newcommand` will disappear from the Latex compiling process. John suggested the above way to get around of this issue (https://github.com/jgm/pandoc/issues/4667).  You can see it by this example (using bookdown was just to keep the tex file for check):

````
---
title: "Untitled"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
output: 
  bookdown::pdf_document2:
    keep_tex: yes
---

```{r setup, include=FALSE}
library(kableExtra)
```

\blandscape 

Test 

\elandscape

````

I'm not sure this is an issue of `pandoc` or `rmarkdown`, but I guess I will follow the way Yihui suggested. Thank you for following up with this question.

**Comment by yihui** [comment]
@sammo3182 I guess it is an rmarkdown problem, to which I don't have a solution without a further investigation.

@haozhu233 The syntax ```` ```{=format}```` is new in Pandoc 2.x. See http://pandoc.org/MANUAL.html#generic-raw-attribute

**Comment by haozhu233** [comment]
@sammo3182 somehow I can get the example you provided rendered successfully on a Mac. For kableExtra, you can try to follow instructions on page 3 of this vignette https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf, disable the auto-loading behavior and manually load all latex packages by yourself. It should work in this case.
