### ISSUE TITLE
Display language type in code chunk

### ISSUE THREAD

**Issue by Schantanu** [rstudio/rmarkdown#1373]
Is there a way to display the language of the code chunk in the top-right corner or something? If not then any thoughts on having an integration in the upcoming releases?

This is especially useful if the documentation is written for non-developers. A good example of this can be found on the [Vue.js documentation](https://vuejs.org/v2/guide/) where you can differentiate between html, css, js, etc.

**Comment by Schantanu** [comment]
Thank you for the interest. Also a 'Copy Code' button while we are at it. :grin:

**Comment by rich-iannone** [comment]
@Schantanu I agree, it's in the same spirit. This is all most likely to occur after we upgrade from Bootstrap 3.
