### ISSUE TITLE
rmarkdown: installation failure

### ISSUE THREAD

**Issue by ollllllllllo** [rstudio/rmarkdown#1376]
**try to install rmarkdown via several ways posted, no success.**

-- install.packages("rmarkdown")

  There is a binary version available but the source version is later:
          binary source needs_compilation
        rmarkdown    1.9   1.10             FALSE

installing the source package ‘rmarkdown’

trying URL 'https://cran.rstudio.com/src/contrib/rmarkdown_1.10.tar.gz'
Content type 'application/x-gzip' length 2447327 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

* installing *source* package ‘rmarkdown’ ...
** package ‘rmarkdown’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘backports’
ERROR: lazy loading failed for package ‘rmarkdown’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rmarkdown’
Warning in install.packages :
  installation of package ‘rmarkdown’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/wj/nfzzd0357sq7m3ds4wdm3h81k6nvzx/T/Rtmpin08sM/downloaded_packages’

--- devtools::install_url("http://cran.r-project.org/src/contrib/rmarkdown_1.9.tar.gz")
Downloading package from url: http://cran.r-project.org/src/contrib/rmarkdown_1.9.tar.gz
Installation failed: Not Found (HTTP 404).

--- devtools::install_github("rstudio/rmarkdown")
Downloading GitHub repo rstudio/rmarkdown@master
from URL https://api.github.com/repos/rstudio/rmarkdown/zipball/master
Installing rmarkdown
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/private/var/folders/wj/nfzzd0357sq7m3ds4wdm3h81k6nvzx/T/Rtmpin08sM/devtoolsc0676632608f/rstudio-rmarkdown-18207b9'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘rmarkdown’ ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘backports’
ERROR: lazy loading failed for package ‘rmarkdown’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rmarkdown’
Installation failed: Command failed (1)

**Comment by ollllllllllo** [comment]
mac               
system         x86_64, darwin15.6.0                   
language       R                           
version.string R version 3.4.4 (2018-03-15)

**Comment by yihui** [comment]
[Is everything up-to-date?](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. try `update.packages(ask = FALSE, checkBuilt = TRUE)`

BTW, please do not ignore the [formatting guidelines](https://yihui.name/en/2018/05/github-issue-format/) in the Github issue template next time.

**Comment by ollllllllllo** [comment]
thanks for reminding me the formatting guidelines, I am still new here, will follow it next time.
I update everything, the problem still remains.  
I am able to load "rmarkdown"  by specifying the library location
library("markdown", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library").
But simply run following didn't work:
library(rmarkdown)

**Comment by yihui** [comment]
How about `install.packages('backports')`?

**Comment by Karosuchiha** [comment]
Yes! It works if you first install.packages('backports') and then install.packages('rmarkdown')

Thank you for the tip!

**Comment by ollllllllllo** [comment]
Thanks
