### ISSUE TITLE
Missing NEWS file?

### ISSUE THREAD

**Issue by njtierney** [rstudio/rmarkdown#1377]
Hi there!

Thanks for writing and maintaining something that I use literally every day!

This is a bit of nitpicking, so please feel free to ignore. This is a general user/dev point of view question - is there a reason that there is now NEWS file for `rmarkdown`? I can look to the [release](https://github.com/rstudio/rmarkdown/releases) page, but I was just wondering if there was a deliberate choice to not include a NEWS file? I would find it useful to read over and see what has changed, and it would also appear on the CRAN view as well.

Cheers!

**Comment by yihui** [comment]
It is under `inst/`. I don't know why it was there instead of under the root directory.

**Comment by rich-iannone** [comment]
@yihui Should it be moved to the top level? I'm not sure but I think it is indexed by services...

**Comment by yihui** [comment]
I'm fine with the top level. I think it was @jjallaire who put it under `inst/`. Let's see what he thinks.

**Comment by jjallaire** [comment]
Top level is fine by me.

**Comment by njtierney** [comment]
Thanks! :)
