### ISSUE TITLE
mathcode in slide title stops slide rendering

### ISSUE THREAD

**Issue by dar143** [rstudio/rmarkdown#1382]
## Slide with Plot of Pressure$^{1/2}$.

```{r pressure}
plot(sqrt(pressure))
```

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by dar143** [comment]
---
title: "Untitled"
author: "R User"
date: "25/06/2018"
output: powerpoint_presentation

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = 'left')
```

## R Markdown

This is an R Markdown presentation. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot of Pressure$^{1/2}$.

```{r pressure}
plot(sqrt(pressure))
```
