### ISSUE TITLE
Floating TOC in HTML docs doesn't highlight scrollable sections

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rmarkdown#1383]
When creating an HTML Rmarkdown document with a floating TOC, and some of the output from the cells in the middle of the sections are scrollable tables, in some cases when the rest of the document doesn't contain paragraph sections, when passing through the sections with scrollable output, the TOC no longer updates itself to reflect that one is browsing those sections (that contain scrollable tables).

**Steps to reproduce:**
* Create some Rmarkdown document with a floating TOC, some sections with scrollable tables, and other sections with only headers.
* Build the document into an HTML.
* Scroll through the document and watch the TOC at the side.

**Expected beahvior:**
* TOC should highlight the section that the user is browsing.

**Actual behavior:**
* When browsing the scrollable sections, it keeps on highlighting whatever was being highlighted before.

**Reproducible:** always, with different web browsers.

The following code triggers this behavior:
```` R
---
title: "example"
author: "no one"
date: "6/22/2018"
output:
  html_document:
    theme: united
    toc: yes
    toc_float:
      collapsed: no
---

# header1

```{r, echo=FALSE, results='asis'}
cat("<h2> header 2 here </h2>")
```

# header 2
```{r, echo=FALSE}
library(knitr)
library(kableExtra)
df <- data.frame(col1 = rnorm(100), col2 = rnorm(100))
txt <- kable(df, caption = "title") %>% kableExtra::kable_styling() %>% scroll_box(height = "500px")
txt <- gsub("<caption>(.*)</caption>",
            "<h2>\\1</h2>", txt)
txt
```

```{r, echo=FALSE}
library(knitr)
library(kableExtra)
df <- data.frame(col1 = rnorm(100), col2 = rnorm(100))
txt <- kable(df, caption = "title2") %>% kableExtra::kable_styling() %>% scroll_box(height = "500px")
txt <- gsub("<caption>(.*)</caption>",
            "<h2>\\1</h2>", txt)
txt
```
````

**Comment by cderv** [comment]
I can't reproduce that with last versions of packages. The sections in the toc are correctly browsing.

![toc-highlight](https://user-images.githubusercontent.com/6791940/97333829-45250f00-187c-11eb-86a6-a0d0c1018304.gif)

Please reopen if you still found issues. Thanks!
