### ISSUE TITLE
! Undefined control sequence. l.115 \toprule

### ISSUE THREAD

**Issue by phillip-toone** [rstudio/rmarkdown#1384]
I get this error:

> ! Undefined control sequence.
> l.115 \toprule

When I run this code obtained from [this](https://github.com/haozhu233/kableExtra/blob/master/vignettes/awesome_table_in_pdf.Rmd#linebreak-processor) kableExtra vignette:

````
---
output:
  pdf_document:
    toc: false
    template: default.latex
---

```{r, include=FALSE}
library(dplyr)
library(kableExtra)
```

```{r, echo=FALSE}
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"), 
  Value = c(10, 100)
)

dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```
````

This error is ONLY generated when I specify a template file.  For example:

````
---
output:
  pdf_document:
    toc: false
---

```{r, include=FALSE}
library(dplyr)
library(kableExtra)
```

```{r, echo=FALSE}
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"), 
  Value = c(10, 100)
)

dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```
````
does not generate this error.

**Comment by yihui** [comment]
Your example is not complete. We don't know your `default.latex`.

**Comment by phillip-toone** [comment]
This error is generated when ANY template file used. So for simplicity and consistency in the example quoted above I referenced the default pandoc template "default.latex".  On my system this is located in the "/usr/share/pandoc/data/templates" directory.  I discovered that my system looks here by using a "nonexistent.tex" template file and reading the resulting error.

> pandoc: Could not find data file /usr/share/pandoc/data/templates/nonexistent.tex
> Error: pandoc document conversion failed with error 97
> Execution halted

**Comment by yihui** [comment]
Okay. Thanks for the explanation!

Cc @haozhu233 (author of **kableExtra**).

**Comment by haozhu233** [comment]
@phillip-toone See page 3 of the vignette https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf

If ever the auto-loading behavior messed up your template, you can disable this behavior by setting `options(kableExtra.latex.load_packages = FALSE)` before you load `kableExtra` and put the list of latex packages (again on page 3) in your template file.

**Comment by phillip-toone** [comment]
@haozhu233 If I understand you correctly, this should work:

````
---
output:
  pdf_document:
    toc: false
    template: default.latex
---

```{r, include=FALSE}
library(dplyr)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
```

```{r, echo=FALSE}
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"), 
  Value = c(10, 100)
)

dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```
````

but it doesn't.  If fact not only do I get the same error but using this option generates this error without explicitly specifying a template.  In other words this:

````
---
output:
  pdf_document:
    toc: false
---

```{r, include=FALSE}
library(dplyr)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
```

```{r, echo=FALSE}
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"), 
  Value = c(10, 100)
)

dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```
````

also generates the error.

**Comment by haozhu233** [comment]
I was suggesting  you should try to add the list of latex packages on page
3 to your template. Have you done that?

**Comment by phillip-toone** [comment]
Yes. This works:

````
---
header-includes:
- \usepackage{booktabs}
- \usepackage{makecell}
output:
  pdf_document:
    toc: false
    template: default.latex
---

```{r, include=FALSE}
library(dplyr)
library(kableExtra)
```

```{r, echo=FALSE}
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"), 
  Value = c(10, 100)
)

dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```
````
Also, adding
```
\usepackage{booktabs}
\usepackage{makecell}
```
to the beginning (just after the \documentclass statement) of any template file (that I have tried) also works.

Thank you! :)

**Comment by yihui** [comment]
Thanks @haozhu233!

**Comment by westland** [comment]
Thanks.  Including the 4 files in header info worked for me as well
