### ISSUE TITLE
Quoted R system.file() in YAML header fails

### ISSUE THREAD

**Issue by bwiernik** [rstudio/rmarkdown#1387]
If I use `system.file()` to refer to a file in the YAML header, rendering (with RStudio) fails:
```
---
title: "Header Test - !expr"
output:
  word_document:
    reference_docx: '`r system.file("templates", "reference_docx_landscape.docx", package = "psychmeta")`'
---
```

However, if I enter it as an R expression, it works (but evaluating expressions will apparently be disabled by default in the near future):
```
---
title: "Header Test - !expr"
output:
  word_document:
    reference_docx: !expr system.file("templates", "reference_docx_landscape.docx", package = "psychmeta")
---
```

**Comment by yihui** [comment]
> evaluating expressions will apparently be disabled by default in the near future

Could you provide the source of this claim?

**Comment by bwiernik** [comment]
knitting with the evaluation syntax produces the warning:

See the documentation here: https://www.rdocumentation.org/packages/yaml/versions/2.1.19/topics/yaml.load

See bug report of the same here: https://github.com/rstudio/config/issues/12

**Comment by yihui** [comment]
Don't worry about it. It should be fairly easy for us to call `yaml.load(..., eval.expr = TRUE)` in this package (will do it in the next release).

Note to myself: [also need to patch it in knitr](https://github.com/yihui/knitr/blob/2b3e617a700f6d236e22873cfff6cbc3568df568/R/params.R#L106).

**Comment by bwiernik** [comment]
Is it possible to fix evaluation of quoted r system.file() calls?

**Comment by yihui** [comment]
I have added `eval.expr = TRUE` to our `yaml.load()` call. Thanks!

The expression `` `r ` `` is evaluated by **knitr** and there shouldn't be anything to fix.

**Comment by bwiernik** [comment]
> The expression `r ` is evaluated by knitr and there shouldn't be anything to fix. 

But this example does fail reliably: 

```
---
title: "Header Test - !expr"
output:
  word_document:
    reference_docx: '`r system.file("templates", "reference_docx_landscape.docx", package = "psychmeta")`'
---
```

**Comment by yihui** [comment]
Perhaps I didn't make it clear last time. You provided two examples in your original post. The first one has always worked. The second has never worked, and it has always been the wrong way to pass a dynamically generated path to `reference_docx`.

**Comment by bwiernik** [comment]
Got it thanks.

**Comment by statquant** [comment]
Is this supposed to work with spin ?
I tried to render the following r file starting with 
I literally tried all combinaison of author but Sys.getenv("USER") never gets evaluated (and is rendered as Sys.get...)

```
#' ---                              
#' title: "r_research"              
#' author: !expr Sys.getenv('USER') 
#' output:                          
#'  html_document:                  
#'     toc: true                    
#'     number_sections: true        
#'     code_folding: "hide"         
#'     toc_float:                   
#'       collapse: false            
#'       smooth_scroll: false       
#'     css: css/styles.css          
#' params:                          
#'  echo: FALSE                     
#'  warnings: FALSE                 
#'  messages: FALSE                 
#'  out.width: "100%"               
#' ---     
```

**Comment by yihui** [comment]
@statquant Sounds like a bug. Could you file a new issue? Thanks!
