### ISSUE TITLE
Tab completion in R Markdown Notebook bash chunks?

### ISSUE THREAD

**Issue by kubu4** [rstudio/rmarkdown#1391]
Jupyter Notebooks do this out of the box. Is there a way to enable this in R Markdown Notebooks?

Per the Issues Guidelines, here's the StackOverflow question on this topic: https://stackoverflow.com/questions/51119005/tab-completion-in-r-markdown-notebook-bash-chunks?noredirect=1#comment89224854_51119005

**Comment by yihui** [comment]
Sorry, but https://github.com/rstudio/rstudio/issues is the right place to file the issue, since this definitely requires the IDE support. The **rmarkdown** package itself cannot do the Tab completion.

**Comment by kubu4** [comment]
Ah, thanks!
