### ISSUE TITLE
weird bug when using a for loop

### ISSUE THREAD

**Issue by randomgambit** [rstudio/rmarkdown#1397]
Hello there!

Please have a look at this SO question https://stackoverflow.com/questions/51199368/how-to-use-a-for-loop-in-rmarkdown

Essentially I am trying to print a `kableExtra` table into html slides iteratively but it seems like the packages are not passed correctly unless one creates a dummy table first. is this a bug?
thanks!

**Comment by yihui** [comment]
Not a bug: https://yihui.name/en/2017/06/top-level-r-expressions/

**Comment by yihui** [comment]
It is still related to top-level expressions. When the table is not generated from a top-level expression, its metadata will be lost. In your case, the metadata refers to the HTML dependencies from **kableExtra**.

A full explanation will involve quite a bit technical details and may take me an hour to type out. Here is the start: https://cran.rstudio.com/web/packages/knitr/vignettes/knit_print.html

**Comment by randomgambit** [comment]
very interesting. i will have a closer look at the link. in practical terms, do you agree with the fix used in the SO question?
thanks again!!

**Comment by yihui** [comment]
Please give me some more time to think about this problem. It is constantly confusing and surprising. We probably should provide a more intelligent solution. I may talk to @haozhu233 next week.

**Comment by haozhu233** [comment]
Just added a post to that SO question, you can forcibly turn on the htmldepencies in kableExtra through `options(kableExtra.html.bsTable = T)`.

**Comment by randomgambit** [comment]
thanks @haozhu233, that is pretty neat!
