### ISSUE TITLE
Change site_libs path directory

### ISSUE THREAD

**Issue by rasyidstat** [rstudio/rmarkdown#1402]
Hi,

I would like to build a static HTML using RMarkdown. My `_site.yml` configuration is like this:

name: "My RMarkdown Website A"
output_dir: ../../_site/web-a
  output:
    rmarkdown::html_document:
       self_contained: false
       lib_dir: site_libs

When I knit my RMarkdown, my `lib_dir` folder will be stored on `../../_site/web-a`. Is there any way that I can store my `lib_dir` folder on `../../_site`?

Stackoverflow link: https://stackoverflow.com/questions/51309003/change-site-libs-path-of-rmarkdown-website

**Comment by cderv** [comment]
you need to have your local dependencies in the same folder than your website. Rmarkdown website is best used from a RStudio project and not using relative path like `../../` that could cause issue. 

As you are asking a question, https://community.rstudio.com is more oriented for that. This ticket is quite old with no more activity. You may have found your answer now. If you still have an issue, please reopen this ticket. Thank you.
