### ISSUE TITLE
Output created: Untitled.pdf Error in tools::file_path_as_absolute(output_file) 

### ISSUE THREAD

**Issue by hutaohutc** [rstudio/rmarkdown#1404]
I have uninstall miktex on my computer,and install tinytex V0.6 and rmarkdown 1.10. my error as follows : 
```
Output created: test3.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'test3.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
停止执行

```

I just click file-> new file->rmarkdown->from template->ctex documents->knit.

```

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
 [5] htmltools_0.3.6 tools_3.5.0     rticles_0.5     yaml_2.1.19    
 [9] Rcpp_0.12.17    tinytex_0.6     stringi_1.2.3   rmarkdown_1.10 
[13] knitr_1.20      stringr_1.3.1   digest_0.6.15   xfun_0.3       
[17] evaluate_0.10.1

```

**Comment by yihui** [comment]
Could you post the full log of the R Markdown compilation? Thanks!

**Comment by hutaohutc** [comment]
```
processing file: test3.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: unnamed-chunk-1 (with options) 
List of 1
 $ eval: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: unnamed-chunk-2
  |..............................................                   |  71%
   inline R code fragments

  |........................................................         |  86%
label: scatter (with options) 
List of 1
 $ fig.cap: chr "cars数据散点图以及回归直线。"

  |.................................................................| 100%
  ordinary text without R code


output file: test3.knit.md

"D:/Rstudio/bin/pandoc/pandoc" +RTS -K512m -RTS test3.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test3.tex --table-of-contents --toc-depth 2 --template "F:\R\R-3.5.0\library\rticles\rmarkdown\templates\ctex\resources\default.latex" --number-sections --highlight-style tango --latex-engine xelatex 

Output created: test3.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'test3.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
停止执行
```
Thank you for your time

**Comment by hutaohutc** [comment]
test3.Rmd is on my local computer D disk ,my system disk is C disk, I did not setting a network drive. I don't know if I answered your question..Thank you

**Comment by yihui** [comment]
Could you provide the output of `Sys.which('xelatex')` and `system('xelatex --version')`?

**Comment by hutaohutc** [comment]
Maybe I get the reason ,i did not fullly uninstall miktex. Thank you your time, take a break early. If I have any problem, I will post it . @

**Comment by hutaohutc** [comment]
I have solved my problem .  Thank you @yihui  .
Solution: run the code  `Sys.which('xelatex')` in R to see if you have uninstall your miktex or TeXLive  fully.
If the output of  `Sys.which('xelatex')`  is something like `TinyTeX\\bin\\win32\\xelatex.exe` ,you can Basically run your rmarkdown code successfully.

**Comment by yihui** [comment]
Excellent. Thanks!

**Comment by fuguigui** [comment]
I also meet this problem. When I input "Sys.which('xelatex')", my system says "C:\\PROGRA~1\\tex\\miktex\\bin\\x64\\xelatex.exe". I have no idea whether it is right? How to solve the problem? I really appreciate your reply.

**Comment by ramanbala** [comment]
@fuguigui unistall Miktex from your system and try this 

install.packages('tinytex')
tinytex::install_tinytex()

**Comment by hutaohutc** [comment]
@jpkarani  I think U should show the result of `Sys.which('xelatex')`

**Comment by rachgee** [comment]
Hello, I am having the same issue. Here is the end of the output when I knit:

output file: HW2.knit.md


Output created: HW2.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'HW2.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning message:
In readLines(logfile) : incomplete final line found on 'HW2.log'
Execution halted

And below is what occurs when I put the following commands:
> Sys.which('xelatex')
                                                                              xelatex 
"C:\\Users\\Lio\\AppData\\Local\\Programs\\MIKTEX~1.9\\miktex\\bin\\x64\\xelatex.exe" 
> system('xelatex --version')
MiKTeX-XeTeX 2.9.6933 (0.99999) (MiKTeX 2.9.6930 64-bit)
(C) 1994-2008 by SIL International, (C) 2009-2012 by Jonathan Kew, (C) 2010-2012 by Han The Thanh, (C) 2012-2013 by Khaled Hosny
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.61.1; using libcurl/7.61.1 WinSSL
compiled with expat version 2.2.6; using expat_2.2.6
compiled with fontconfig version 2.13.1; using 2.13.1
compiled with freetype2 version 2.9.1; using 2.9.1
compiled with graphite2 version 1.3.12; using 1.3.12
compiled with harfbuzz version 2.0.2; using 2.0.2
compiled with icu version 60.1; using 60.1
compiled with jpeg version 9.3
compiled with liblzma version 50020042; using 50020042
compiled with libpng version 1.6.35; using 1.6.35
compiled with libressl version LibreSSL 2.8.2; using LibreSSL 2.8.2
compiled with MiKTeX Application Framework version 4.6930; using 4.6930
compiled with MiKTeX Core version 10.6941; using 10.6941
compiled with MiKTeX Archive Extractor version 1.6882; using 1.6882
compiled with MiKTeX Package Manager version 5.6938; using 5.6938
compiled with poppler version 0.60.1
using teckit version 2.4
compiled with uriparser version 0.8.6
compiled with zlib version 1.2.11; using 1.2.11

What should I do? I have been trying to knit the pdf for a few hours now.

**Comment by yihui** [comment]
@rachgee See @ramanbala's reply above: https://github.com/rstudio/rmarkdown/issues/1404#issuecomment-433021026

**Comment by acemacdonald** [comment]
Hi I am having the same issue, and nothing seems to work (been trying different things for about 4 weeks)
My error code is as follows:

pandoc.exe: pdflatex not found. pdflatex is needed for pdf output.
Error: pandoc document conversion failed with error 41
Execution halted

No TeX installation detected (TeX is required to create PDF output). You should install a recommended TeX distribution for your platform:

  Windows: MiKTeX (Complete) - http://miktex.org/2.9/setup
  (NOTE: Be sure to download the Complete rather than Basic installation)

  Mac OS X: TexLive 2013 (Full) - http://tug.org/mactex/
  (NOTE: Download with Safari rather than Chrome _strongly_ recommended)

  Linux: Use system package manager

Which is weird because I have tinytex installed and everything and now it says I have to install MikTex.

I also get the following:

Sys.which('xelatex')
xelatex 
     ""

**Comment by hutaohutc** [comment]
@acemacdonald 
Do you run the code `tinytex::install_tinytex()` ?

**Comment by acemacdonald** [comment]
@hutaohutc thank you for your quick reply.
I did, I got the following:

trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
Content length 365 bytes
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
trying URL 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    351      0  0:00:01 --:--:--  0:00:01   748
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection was reset
Error in download.file(url, output, ..., method = method) : 
  'curl' call had nonzero exit status
In addition: Warning messages:
1: In download.file(url, output, ..., method = method) :
  URL 'http://ftp.leg.uct.ac.za/pub/packages/ctan/systems/texlive/tlnet/install-tl.zip': status was 'Failure when receiving data from the peer'
2: In download.file(url, output, ..., method = method) :
  InternetOpenUrl failed: 'The connection with the server was reset'
3: In download.file(url, output, ..., method = method) :
  InternetOpenUrl failed: 'The connection with the server was reset'
Please quit and reopen your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.

I'm guessing I have done this wrong?

**Comment by hutaohutc** [comment]
@acemacdonald 
reopen your R session,run the code `tinytex:::is_tinytex() `,

**Comment by acemacdonald** [comment]
It returns FALSE :(

**Comment by hutaohutc** [comment]
I suggest that you should change your network and run `tinytex::install_tinytex()`.
If you had already installed tinytex in your computer , you can use 'tinytex'

**Comment by acemacdonald** [comment]
Sorry @hutaohutc could you elaborate?
I've tried to install tinytex a few times and it returns that same FALSE
How would one change their network?

**Comment by yihui** [comment]
@acemacdonald In general, please try not to reply under a closed issue (try to file a new issue instead). Anyway, whenever you report issues (new or old), please follow the issue guide to provide the relevant info: https://github.com/rstudio/rmarkdown/blob/master/.github/ISSUE_TEMPLATE.md
