### ISSUE TITLE
Strange behavior of the command  \LaTeX  

### ISSUE THREAD

**Issue by tinu-schneider** [rstudio/rmarkdown#1414]
I try to use the command  `\LaTeX`  in an   .Rmd document like this `$\LaTeX$`.

If I render it to HTML, it works as expected. But if I render to PDF, it stops with the error:

```
! You can't use `\spacefactor' in math mode.
\@->\spacefactor 
                 \@m {}
l.99 But if we try \(\LaTeX
                           \) 
```

The intermediate `.tex` file has the original `$\LaTeX$` translated to ` \(\LaTeX\) ` which seems to make problems during the conversion to PDF (pandoc).

Here is an example with different cases for PDF and HTML. 

```
---
title: "LaTeX in Text"
output: pdf_document
---

## LaTeX in Markdown

### Works
We can use math mode in text $\alpha + \beta$.

### Fails for PDF, but works for HTML
If we try `$\LaTeX$` it fails when we render the PDF.
Ok in HTML, error in PDF:  <!-- $\LaTeX$  uncomment for HTML -->

### Works for PDF but fails for HTML
We can use \LaTeX\  like this, then it's ok in PDF, but is missing in HTML

````

### Left: HTML, right: PDF
![both](https://user-images.githubusercontent.com/854515/43096976-f3c22ca8-8eba-11e8-8fda-11bf9fd59151.PNG)

**Comment by tinu-schneider** [comment]
Here is what I found from pandoc https://github.com/jgm/pandoc/issues/583

> No, it's not a bug in pandoc. In LaTeX, the macro
\LaTeX cannot be used in math mode. 

A solution is provided, although not fully statisfying.

So it's no .Rmd problem and I think I can close the issue.

**Comment by yihui** [comment]
@tinu-schneider Many thanks for coming back to close an old issue!
