### ISSUE TITLE
Space after a colon in YAML Header leads to scanner error

### ISSUE THREAD

**Issue by MartinGuth** [rstudio/rmarkdown#1425]
Hi,

I am not sure if this is the right spot to post this, but I've just encountered following error when putting a white space after a colon within a header/footer in a markdown document:

```
Error in yaml::yaml.load(string, ...) : 
  Scanner error: mapping values are not allowed in this context at line 10, column 18
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load_utf8 -> <Anonymous>
execution stopped
```

This simple .RMD sample works and produces the footer "**A colon:and space**":

```
---
header-includes:
   \usepackage{fancyhdr}
   \pagestyle{fancy}
   \fancyhead[C]{}
   \fancyhead[L]{}
   \fancyhead[R]{}
   \renewcommand{\headrulewidth}{0pt}
   \cfoot{}
   \rfoot{\thepage}
   \lfoot{A colon:and space}
output: 
  pdf_document
---


## GitHub Test

This is just a test for GitHub.
```

Now we add a single space between the colon and the and

```
---
header-includes:
   \usepackage{fancyhdr}
   \pagestyle{fancy}
   \fancyhead[C]{}
   \fancyhead[L]{}
   \fancyhead[R]{}
   \renewcommand{\headrulewidth}{0pt}
   \cfoot{}
   \rfoot{\thepage}
   \lfoot{A colon: and space}
output: 
  pdf_document
---


## GitHub Test

This is just a test for GitHub.
```

and it breaks.

The error occurs in headers and footers and is not limited the usage of `\cfoot`, `\lfoot`, `\rfoot` or a version of `\fancyfoot[]` (or the respective versions for the header). 

Is there a way to get the white space after a colon?

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252 LC_NUMERIC=C                    LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6 tools_3.5.0     yaml_2.1.19     Rcpp_0.12.17    stringi_1.2.3   rmarkdown_1.10 
[11] knitr_1.20      stringr_1.3.1   digest_0.6.15   evaluate_0.11  
```

**Comment by yihui** [comment]
Could you tell me where you learned about `header-includes`? I have seen many people use this field in the YAML metadata, but I have never asked where they learned it. Personally I strongly recommend using the `includes: in_header` option of the specific output format. The `header-includes` field is fragile and not portable. Please see the SO post for more info: https://stackoverflow.com/a/51471606/559676

Anyway, YAML has many flaws, and the colon is probably the most surprising thing. It is a special character (when followed by a space), so you have to be careful with it (quote the string when it contains special characters). I still recommend using `includes: in_header`, which is safe and portable. Of course, the downside is that you will need to create an external file.

**Comment by MartinGuth** [comment]
Hi Yihui,

for the most part I've learned it through [SO](https://stackoverflow.com/questions/46107181/combine-multiple-pages-of-pdf-into-rmarkdown) and [GitHub](https://github.com/haozhu233/kableExtra/issues/16) posts. It was a somewhat easy solution to the problem(s) at hand and thus I did not question the stability of the solution.

Anyway, thanks for the fast reply! I tried your proposed solution and in principle it worked. 
However, I am actually using a `for-loop`, the `rmarkdown::render` function and inline R-code within the footer to create the reports. With the included preamble.tex, this is not working anymore, as the inline code is evaluated as text.

A new toy example which covers this would be:

**test.R** - the footer vector includes the trouble causing colon and the white space
```
footer <- paste0("Car: ",rownames(mtcars))

for(i in 1:length(footer))
{
  rmarkdown::render(input = "test.Rmd",
                    output_format = "pdf_document",
                    encoding = "UTF-8",
                    output_file = paste0("Report", " - ", rownames(mtcars)[i], " - ", Sys.Date(), ".pdf"))
}
```

**test.Rmd** - now using the includes - in_header
```
---
output: 
  pdf_document:
    includes:
      in_header: preamble.tex
---


## GitHub Test

This is just a test for GitHub.
```

**preamble.tex** - the footer should display "Car: XYZ"
```
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[C]{}
\fancyhead[L]{}
\fancyhead[R]{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot[C]{`r footer[i]`}
```

Is there are work-around for the inline code to be evaluated or should I just get rid of the colon?

**Comment by yihui** [comment]
In that case, I recommend you to use the second way mentioned in my SO answer, i.e.

````yaml
header-includes: |
  ```{=latex}
  % your raw LaTeX code here
  ```
````

That is the most reliable solution, but it requires Pandoc 2.x. If you are using the preview version of RStudio, you should be good.

If you don't have Pandoc 2.x, you may add a pipe after `header-includes: `. That should make it work in this particular case, but there is no guarantee in other cases. For the meaning of the pipe in YAML, you may see https://en.wikipedia.org/wiki/YAML.

**Comment by MartinGuth** [comment]
Sorry for the late reply!

Our pandoc version is not > 2.0, but I am in contact with my IT department to get an upgrade.

Thank you for your help!
