### ISSUE TITLE
missing pagetitle if title is not supplied

### ISSUE THREAD

**Issue by schloerke** [rstudio/rmarkdown#1434]
#1355 introduced a bug where if the `pagetitle` is supplied and `title` is not supplied, the title of the document is now the name of the document, not the `pagetitle` value.

Example header in `my_document.md`:
```yaml
-------------
pagetitle: "my title"
-------------
```

Currently produces an html document with a title of `"my_document.md"`

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

Cc @jdblischak
