### ISSUE TITLE
Suggested Improvement to documentation for knit_hooks

### ISSUE THREAD

**Issue by CharlesCara** [rstudio/rmarkdown#1436]
Can I suggest the following change to the documentation for knit_hooks - it incorporates your answer to https://stackoverflow.com/questions/28268584/trying-to-set-knitr-document-output-hook-results-in-code-chunk-line-breaks-bei 

**Output hooks**
...
All these hooks should be of the form function(x, options) (except the inline and document hooks which only have one argument x), where x is the character string of the output, and options is a list of current chunk options. 
Output hooks can be set as follows (this adds extra html formatting to any error messages).  
```r
knitr::knit_hooks$set(error = function(x, options){ 
      paste('\n\n<div style="color:Crimson; background-color: SeaShell;">',
            gsub('##', '\n', gsub('^##\ Error', '**Error**', x)),
            '</div>', sep = '\n')
})
```
Hooks can be chained together with
```r
knitr::knit_hooks$append(error = function(x, options){ 
      "Additional actions"
})
```
Unlike chunk hooks which are empty by default, output hooks all come with default values which can be reset with:
```r
knitr::knit_hooks$restore() 
``` 

Output hooks should be set inside the document.  If the hooks are set before `knitr::knit()` processes the document run then `render_xxxx()` must be called first, where *xxxx* is the output format eg `render_markdown()` or `render_html()` - see below.

...etc

knitr is a great package, which I use everyday, so thank you for creating it.

**Comment by jdblischak** [comment]
I agree! I realized that I had to first run `render_markdown()` from reading the unit tests in [test-hooks.R](https://github.com/yihui/knitr/blob/2b3e617a700f6d236e22873cfff6cbc3568df568/tests/testit/test-hooks.R#L19). Please let me know if there is anyway that I can help to update the documentation.

**Comment by yihui** [comment]
If you mean the documentation at https://yihui.name/knitr/hooks/, please feel free to click "Edit this page" on the left, and submit a pull request to improve it. Thank you!

**Comment by CharlesCara** [comment]
Have submitted under pull request #75
