### ISSUE TITLE
Remove quotes around metadata fields in pandoc args

### ISSUE THREAD

**Issue by bearloga** [rstudio/rmarkdown#1440]
If providing a metadata field to `pandoc_args`, the resulting command includes quotation marks which I'm *pretty sure* is what's making pandoc ignore it.

Specifically, I'm trying to make `nocite: '@*'` a default for my template so the end-user doesn't have to include it in their YAML in every single Rmd document (bearloga/wmf-product-analytics-report#1) and according to jgm/pandoc#4872 the way to do this is with:

`pandoc -M nocite='@*'`

and according to #409 maybe `pandoc --metadata=nocite:'@*'` could also be a way to do that.

But when I add `"-M nocite='@*'"` to `pandoc_args` or to `config$pandoc$args` e.g.:

```
config$pandoc$args <- c(pre_pandoc, wmfpar_args, "-M nocite='@*'")
```

the pandoc call ends up looking like:

```
/usr/local/bin/pandoc +RTS -K512m -RTS skeleton.utf8.md
  --to latex
  --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
  --output skeleton.tex
  --template …/library/memor/rmarkdown/templates/memor/resources/memor.tex
  --highlight-style tango
  --pdf-engine xelatex
  --bibliography /var/…/wmfpar_rpkgs_c7f7211ee1bb.bib
  --filter /usr/local/bin/pandoc-citeproc
  --csl …/library/wmfpar/rmarkdown/templates/wmfpar/resources/apa.csl
  --variable footer_on_first_page=yes
  --variable fontsize=12pt
  --variable geometry=margin=1in --variable subparagraph
  --variable "mainfont=Source Serif Pro"
  --include-in-header …/library/wmfpar/rmarkdown/templates/wmfpar/resources/preamble.tex
  "-M nocite='@*'"
```

(newlines added for readability)

Either rmarkdown is lacking support for metadata fields as args or I'm doing something wrong. Either way, please help :)

**Comment by kevinushey** [comment]
I think setting these separately should help; e.g.

```R
config$pandoc$args <- c(pre_pandoc, wmfpar_args, "-M", "nocite='@*'")
```

Does that make a difference?

**Comment by bearloga** [comment]
Oh yeah, totally forgot to mention that I tried that and it outputs the following:

```
/usr/local/bin/pandoc … -M "nocite='@*'" 
```

which also doesn't work :( and I have no idea how to get rmarkdown to not automatically quote that second part.

**Comment by yihui** [comment]
Currently there is no way to remove the quotes. All arguments are quoted:
https://github.com/rstudio/rmarkdown/blob/19008bf684659f8592c5cbd440f9ce7e3786d65a/R/pandoc.R#L685-L694

I don't have an idea on what to do in this case. Sorry.

**Comment by bearloga** [comment]
Gonna have to reopen that pandoc issue because I adjusted the `quoted` function to allow for flagging args that shouldn't be `shQuoted()` and it didn't work. So maybe jgm's solution doesn't actually work but that's outside the scope of this issue :)

In any case, in my solution an arg can be flagged as "not to be quoted" by starting it with `^`. I guess any special character that's not in `rmarkdown:::.shell_chars_regex` can be used so folks are welcome to suggest alternatives but I'm gonna submit a PR for the version I have. Y'all are welcome to reject it but I think it might be nice to just have that option?

**Comment by yihui** [comment]
I agree it would be nice to have a way to tell `quoted()` not to quote an element. I was just not sure what a proper way would be. Using `^` as the flag sounds hackish to me.

On the other hand, I'm a little surprised that the quoted argument `"nocite='@*'"` and unquoted version`nocite='@*'` have different meanings to Pandoc. In CLI, they are typically the same.

```sh
$ echo "abc"
abc
$ echo abc
abc
```

Sounds like Pandoc uses a special command-line argument parser.

**Comment by cderv** [comment]
There may be an issue with Pandoc on this one. Here is what I tried at the command line to see how metadata are processed. 

* Setting nocite in the document yaml
```sh
$ pandoc -t json
---
nocite: [@*]
---
something
^Z
{"pandoc-api-version":[1,22],"meta":{},"blocks":[{"t":"Table","c":[["",[],[]],[null,[]],[[{"t":"AlignDefault"},{"t":"ColWidthDefault"}]],[["",[],[]],[]],[[["",[],[]],0,[],[[["",[],[]],[[["",[],[]],{"t":"AlignDefault"},1,1,[{"t":"Plain","c":[{"t":"Str","c":"nocite:"},{"t":"Space"},{"t":"Cite","c":[[{"citationId":"*","citationPrefix":[],"citationSuffix":[],"citationMode":{"t":"NormalCitation"},"citationNoteNum":1,"citationHash":0}],[{"t":"Str","c":"[@*]"}]]}]}]]]]]]],[["",[],[]],[]]]},{"t":"Para","c":[{"t":"Str","c":"something"}]}]}
```
We see nocite is found and processed because some other metadata are added by pandoc

* Trying to pass the metadata field at the command line does not seem to work
```sh
$ echo something | pandoc -t json --metadata "nocite='@*'"
{"pandoc-api-version":[1,22],"meta":{"nocite":{"t":"MetaString","c":"'@*'"}},"blocks":[{"t":"Para","c":[{"t":"Str","c":"something"}]}]}
``` 
* Passing it in a file seem to work
```sh
$ echo "nocite: '@*'" > metadata.yml
$ echo test | pandoc -t json --metadata-file metadata.yml
{"pandoc-api-version":[1,22],"meta":{"nocite":{"t":"MetaInlines","c":[{"t":"Cite","c":[[{"citationId":"*","citationPrefix":[],"citationSuffix":[],"citationMode":{"t":"AuthorInText"},"citationNoteNum":1,"citationHash":0}],[{"t":"Str","c":"@*"}]]}]}},"blocks":[{"t":"Para","c":[{"t":"Str","c":"test"}]}]}
```

* Trying with other than @*: ok in a metadata file
```sh
$ echo "nocite: '@item2,@item1'" > metadata.yml
$ echo test | pandoc -t json --metadata-file metadata.yml
{"pandoc-api-version":[1,22],"meta":{"nocite":{"t":"MetaInlines","c":[{"t":"Cite","c":[[{"citationId":"item2","citationPrefix":[],"citationSuffix":[],"citationMode":{"t":"AuthorInText"},"citationNoteNum":1,"citationHash":0}],[{"t":"Str","c":"@item2"}]]},{"t":"Str","c":","},{"t":"Cite","c":[[{"citationId":"item1","citationPrefix":[],"citationSuffix":[],"citationMode":{"t":"AuthorInText"},"citationNoteNum":2,"citationHash":0}],[{"t":"Str","c":"@item1"}]]}]}},"blocks":[{"t":"Para","c":[{"t":"Str","c":"test"}]}]}
```
but does not work at the command line
```sh
$ echo test | pandoc -t json --metadata "nocite='@item1,@item2'"
{"pandoc-api-version":[1,22],"meta":{"nocite":{"t":"MetaString","c":"'@item1,@item2'"}},"blocks":[{"t":"Para","c":[{"t":"Str","c":"test"}]}]}
```

There is something happening with pandoc regarding the understanding of nocite metadata. I believe it should work with the `--metadata` flag, but it seems it is not. 

There is not much to do in **rmarkdown** for now if we don't know what should work with Pandoc. Maybe it should be asked in 

@bearloga for your specific use case, using a metadata file works. You can provide one in your package, and add it to command line so that it is taken into account for all call to pandoc. 
```r
config$pandoc$args <- c(pre_pandoc, wmfpar_args, "--metatadata-file",  "nocite.yml")
```
with `nocite.yml`
```yaml
nocite: |
  @*
```

I believe it should work.

**Comment by atusy** [comment]
@cderv This is the documented behavior.

On CLI,

> Values will be parsed as YAML boolean or string values

In YAML metadata blocks,

> all string scalars will be interpreted as Markdown

https://pandoc.org/MANUAL.html#metadata-blocks

**Comment by atusy** [comment]
I think only way to support this is a Lua filter like

```lua
function Meta(meta)
  local nocite = meta.nocite
  if nocite and type(nocite) == 'string' then
    meta.nocite = pandoc.read(nocite, "markdown")
    return meta
  end
end
```

**Comment by cderv** [comment]
Thanks ! That explains it then. 

IMO this is a pretty specific case here to pass `nocite` at command line. I don't really think that **rmarkdown** should handle this specific one using another included Lua filter.

We have two solutions now for @bearloga to set a default `nocite` for a format: 
* Using metadata in a yaml file (as shown in https://github.com/rstudio/rmarkdown/issues/1440#issuecomment-720419280)
* using command line argument + a Lua filter (following https://github.com/rstudio/rmarkdown/issues/1440#issuecomment-819553035)

@bearloga is one of them solving your (long overdue) issue ?

**Comment by atusy** [comment]
I agree

> I don't really think that rmarkdown should handle this specific one using another included Lua filter.

**Comment by cderv** [comment]
I still believe there is nothing that we should really do in rmarkdown directly considering there are already 2 solutions. 

I'll close this issue. Please reopen if you think we should still consider a fix here or in Pandoc.

Thanks.
