### ISSUE TITLE
[feature request] option to save sql chunk to a string

### ISSUE THREAD

**Issue by rld2** [rstudio/rmarkdown#1441]
SQL chunks have the nice feature of syntax highlighting, but as far as I know they only offer the option to save the result as a data.frame. A better solution for me would be to save the SQL string to a string. This would be a great feature for my use case. I could use the resulting string to manipulate downstream and pass to a custom SQL retrieval function that is specific to my work environment. Using the current capabilities (con=sql_con, output.var=sql_df) is not possible in my current work environment. Mentioned this here https://github.com/rstudio/rstudio/issues/2232 too. Thanks!

**Comment by yihui** [comment]
Let's keep the conversation in a single place rstudio/rstudio#2232. Thanks!
