### ISSUE TITLE
Specific case when render() can't parse source code

### ISSUE THREAD

**Issue by crew102** [rstudio/rmarkdown#1444]
In https://github.com/tidyverse/reprex/issues/202, @kevinushey found a circumstance under which `render()` fails to parse source code . Specifically, if you try to render the following piece of code, you'll get a failure to parse error (see reproducible example below for error details):

```r
code <- "
#' hello, world!"
```

From what I can tell, `#'` must be the leading characters on the second line of the `code` string for this error to occur. For example, if you remove `#` you won't get an error, and if you add a few spaces before `#'` you also won't get an error. 

## Reproducible example

``` r
library(rmarkdown)

render_one <- function(src) {
  file <- "to-render.R"
  writeLines(src, file)
  render(file)
}

# doesn't work:

src_no_work <- "code <- \"
#' hello, world!\""
render_one(src_no_work)
#> Quitting from lines 3-4 (to-render.spin.Rmd)
#> Error in parse(text = x, srcfile = src) :
#>  <text>:1:9: unexpected INCOMPLETE_STRING
#> 1: code <- "
#>            ^


# ...but these all work:

# no ' after #
src1 <- "code <- \"
# hello, world!\""

# no # before '
src2 <- "code <- \"
' hello, world!\""

# #' is at the start of the first line of the string, not the second line
src3 <-"code <- \"#' hello, world!\""

# leading spaces come before #'
src4 <-"code <- \"
  #' hello, world!\""

lapply(c(src1, src2, src3, src4), render_one)
```

Here's my session info:

<details>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, darwin15.6.0
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  tz       America/New_York
#>  date     2018-09-10
#> Packages -----------------------------------------------------------------
#>  package   * version date       source
#>  base      * 3.5.1   2018-07-05 local
#>  compiler    3.5.1   2018-07-05 local
#>  datasets  * 3.5.1   2018-07-05 local
#>  devtools    1.13.6  2018-06-27 CRAN (R 3.5.0)
#>  digest      0.6.16  2018-08-22 CRAN (R 3.5.0)
#>  evaluate    0.11    2018-07-17 CRAN (R 3.5.0)
#>  graphics  * 3.5.1   2018-07-05 local
#>  grDevices * 3.5.1   2018-07-05 local
#>  htmldeps    0.1.1   2018-09-10 Github (rstudio/htmldeps@c1023e0)
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)
#>  knitr       1.20    2018-02-20 CRAN (R 3.5.0)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.5.0)
#>  methods   * 3.5.1   2018-07-05 local
#>  Rcpp        0.12.18 2018-07-23 CRAN (R 3.5.0)
#>  rmarkdown   1.10.13 2018-09-10 Github (rstudio/rmarkdown@19008bf)
#>  stats     * 3.5.1   2018-07-05 local
#>  stringi     1.2.4   2018-07-20 CRAN (R 3.5.0)
#>  stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)
#>  tools       3.5.1   2018-07-05 local
#>  utils     * 3.5.1   2018-07-05 local
#>  withr       2.1.2   2018-03-15 CRAN (R 3.5.0)
#>  yaml        2.2.0   2018-07-25 CRAN (R 3.5.0)
```

</details>

**Comment by yutannihilation** [comment]
This seems a problem of `knitr::spin()`; `#'` is treated specially around here:

https://github.com/yihui/knitr/blob/01407a72c8d3497336487029b21189ad13bee498/R/spin.R#L71

**Comment by yihui** [comment]
Yes, @yutannihilation was spot on.

**Comment by yutannihilation** [comment]
One possible fix is to consider if the line is independently complete or not by parsing the line one by one. If the line is incomplete, it is probably not a doc. But, I'm afraid this is a bit too heavy just to fix this one case...

``` r
tmp <- tempfile(fileext = ".R")
writeLines(
  c("print(1)",         # --- expression 1
    "code <- \"",       # -+
    "#' hello, world!", #  |- expression 2
    "\""),              # -+
  con = tmp
)

x <- readLines(tmp)

is_parsable <- function(text) {
  tryCatch(
    {
      parse(text = text)
      message("OK!")
      TRUE
    },
    error = function(e) {
      message("error...")
      FALSE
    }
  )
}

pos <- 1
is_complete <- logical(length(x))
for (i in seq_along(x)) {
  message(i, ": ", appendLF = FALSE)
  
  # if the line is not parsable, try with the next line.
  if (!is_parsable(x[seq(pos, i)])) {
    next()
  }
  # if the line is single and parsable, it is complete
  if (i == pos) {
    is_complete[i] <- TRUE
  }
  # if the line is parsable, move the position to the next
  pos <- i + 1
}
#> 1: OK!
#> 2: error...
#> 3: error...
#> 4: OK!

is_complete
#> [1]  TRUE FALSE FALSE FALSE
```

Created on 2018-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by yihui** [comment]
@yutannihilation Genius! (And great minds think alike? 😆  https://github.com/yihui/highr/blob/5ca33a1005b3218206b4fcd93e992cf3189fc71d/R/utils.R#L8-L30)

Are you interested in rewriting or patching `knitr::spin()`? https://github.com/yihui/knitr/blob/master/R/spin.R Your approach of parsing line by line is one way to go. The other way is to use `utils::getParseData()` to obtain the line numbers of comments. I don't know which way is faster (you'll need to benchmark them). Anyway, we need a way to identify lines that are true comments.

**Comment by yutannihilation** [comment]
@yihui 
Thanks! (Yours seems clever! 👍)

Yes, let me try to create a PR to fix this. Using `utils::getParseData()` sounds nice, so I'll try the both way. Can we keep discussing here? Or, should I file a new issue on knitr's repo?

**Comment by yutannihilation** [comment]
I see.

**Comment by jennybc** [comment]
I think we've stumbled on another example of this via reprex https://github.com/tidyverse/reprex/issues/206. Currently `reprex()` is erroring on this input, due to my overly crude "dogfood" check. But once I sort that out, I think that same piece of code will trigger this problem and still fail.

**Comment by yutannihilation** [comment]
OK, here's a reprex for #206 from the viewpoint of knitr. This needs a different fix. Maybe we have to use ` ```` ` (four backticks) to indicate a code chunk if the chunk contains ` ``` ` (three backticks)?

```` r
tmp <- tempfile(fileext = ".R")
writeLines(
  c('"',
    '```{r, eval = FALSE}',
    '```',
    '"'),
  con = tmp
)

setwd(tempdir())
knitr::spin(tmp, knit = FALSE)
#> [1] "C:\\Users\\HIROAK~1\\AppData\\Local\\Temp\\RtmpkdPTzH\\file18f02c596a75.Rmd"

rmd <- readLines(paste0(tools::file_path_sans_ext(tmp), ".Rmd"))
cat(rmd, sep = "\n")
#> 
#> ```{r }
#> "
#> ```{r, eval = FALSE}
#> ```
#> "
#> ```
````

Created on 2018-09-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
I need to consider inline chunks as well. Now this

``` r
code <- "
{{ Sys.Date() }}
"
```

fails as below:

``` r
code <- "
#> Error: <text>:1:9: unexpected INCOMPLETE_STRING
#> 1: code <- "
#>             ^
```

2018-09-15

``` r
"
#> Error: <text>:1:1: unexpected INCOMPLETE_STRING
#> 1: "
#>     ^
```

Created on 2018-09-15 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Hmm, what about this one?

``` r
{{ `[`(letters, 1) }}
```

\[`(letters, 1)`
Created on 2018-09-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
`/*` and `*/` are outside of R's syntax, which means they don't get affected by the R's syntax, so the above result seems valid. Sorry.

**Comment by yutannihilation** [comment]
``` r
{{ "`" }}
```

Result (I cannot reprex on this):

```
Rendering reprex...
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:2: unexpected INCOMPLETE_STRING
1:  "
     ^
```

**Comment by yutannihilation** [comment]
To summarise, there are two types of issues:

### 1. `spin()` doesn't consider the case that the line is in string literals or symbols

Example:

``` r
code <- "
#' hello, world!"
```

``` r
code <- "
{{ 1 + 1 }}
"
```

This will be fixed by yihui/knitr#1610.


### 2. `spin()` uses fixed number of backticks to construct inline and block chunks, so if a chunk contains some backticks, it breaks 

Example:

```` r
"
```{r, eval = FALSE}
```
"
````

``` r
{{ `[`(letters, 1) }}
```

This will be fixed by yihui/knitr#1611

**Comment by yihui** [comment]
Fixed in the development version of **knitr** by @yutannihilation:

```r
devtools::install_github('yihui/knitr')
```

**Comment by yutannihilation** [comment]
@yihui 
Sorry, it seems I failed to fix the second issue about backticks; I thought I just needed to fix `spin()` then `knit()` would handle any number of backticks, but my naive assumption was false...

````` r
tmp_rmd <- tempfile(fileext = ".Rmd")
tmp_md <- tempfile(fileext = ".md")

writeLines(
  c('````{r}',
    'x <- "',
    '```',
    '"',
    '````'),
  con = tmp_rmd
)

cat(readLines(tmp_rmd), sep = "\n")
#> ````{r}
#> x <- "
#> ```
#> "
#> ````

res <- knitr::knit(tmp_rmd, output = tmp_md, quiet = TRUE)
cat(readLines(tmp_md), sep = "\n")
#> 
#> ```r
#> x <- "
#> #> Error: <text>:1:6: unexpected INCOMPLETE_STRING
#> #> 1: x <- "
#> #>          ^
#> ```
#> "
#> ````
`````

<sup>Created on 2018-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yihui** [comment]
@yutannihilation That will be tricky to fix. I guess someday I'll have to rewrite the **knitr** parser using Pandoc instead of regular expressions...

**Comment by yutannihilation** [comment]
Yeah, I understand how tough it is to implement a parser, considering the ambiguity of Markdown syntax...

For this particular case, I could manage to do with back reference, but I don't think I can fix this quickly. I'll file an issue for this on knitr's repo in order not to forget (and hope this will eventually be fixed somehow). 🙄

````` r
# use \x60 instead of `
x <-
'\x60\x60\x60\x60{r}
x <- "
\x60\x60\x60
"
\x60\x60\x60\x60
'

stringr::str_extract_all(
  x,
  stringr::regex('^(`{3,}).*?^\\1$',
                 multiline = TRUE, dotall = TRUE)
)
#> [[1]]
#> [1] "````{r}\nx <- \"\n```\n\"\n````"
`````

<sup>Created on 2018-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
