### ISSUE TITLE
markdown output for Jekyll sites should protect liquid tags

### ISSUE THREAD

**Issue by itcarroll** [rstudio/rmarkdown#1447]
I sought help for this problem on SO with no success:
https://stackoverflow.com/questions/52299423/how-to-prevent-urlencoding-of-liquid-tags

The working example I posted on SO is:
````
---
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(base.url = '{{ site.baseurl }}/')
knitr::opts_chunk$set(fig.path = 'assets/images/')
```

```{r sin_plot}
plot(1:100, sin(1:100))
```
````

The `base.url` setting inserts the liquid tag into the figure's path in the Markdown document, and rmarkdown::render does that just fine ... but then comes pandoc. When rmarkdown::render calls pandoc on the knit document, the braces are urlencode, breaking Jekyll.

A SO user suggested I've got my pipeline confused, but I can't see a better way that would still allow folks on my team using RStudio + RMarkdown write posts their preferred way. The site is and will remain a Jekyll site hosted on GitHub pages.

If there is a YAML heading param that disables pandoc, that would probably solve the problem, but I cannot find one.

**Comment by yihui** [comment]
I have posted an answer to your SO question. Thanks!
