### ISSUE TITLE
Nested list indentation doesn't match Pandoc Markdown documentation

### ISSUE THREAD

**Issue by stragu** [rstudio/rmarkdown#1448]
I have noticed that the [Pandoc Markdown's nested list documentation](https://pandoc.org/MANUAL.html#block-content-in-list-items) linked from the [rmarkdown website](https://rmarkdown.rstudio.com/lesson-8.html) does not match the actual behaviour of rmarkdown.

In the Pandoc documentation, it is said that two spaces are enough for nested lists. The [RMarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf) is not specific, the ["Markdown Basics" page](https://rmarkdown.rstudio.com/authoring_basics.html) says 4 spaces.

Is this an issue with Pandoc's documentation itself and should be reported there?

A different version of the Pandoc documentation, on Garrett Grolemund's website, uses the 4-space indentation (but also lists the tab option, which doesn't work): https://garrettgman.github.io/rmarkdown/authoring_pandoc_markdown.html#lists
It looks like this one was forked in 2016, so it's all very confusing to me...

Here is some Rmd to test it (you might have to replace the indentation with an actual tab in the tab line):

````
---
title: "indented-lists"
output: html_document
---

## Indented lists

Using `rmarkdown` version 1.10 and latest GitHub dev version (1.10.13):

* A list starts like this
     + Four spaces: works

* A list starts like this
  + Tab: does not work

* A list starts like this
  + Two spaces: does not work
````

---
**Edit**: the current cheatsheet does not specify how many spaces are needed, except for a line return inside a list (4 spaces).

**Comment by yihui** [comment]
I don't know how you found the website `https://garrettgman.github.io/rmarkdown/`, but you should ignore it. The canonical documentation website for rmarkdown is https://rmarkdown.rstudio.com. (@garrettgman Could you delete or redirect your copy of the website?)

What is your `rmarkdown::pandoc_version()`? Note that Pandoc's manual always refers to the latest version of Pandoc.

The rules for indentation have changed from Pandoc 1.x to 2.x. If you are still using 1.x, you may try to upgrade RStudio: https://www.rstudio.com/products/rstudio/download/preview/, unless you are not using RStudio, in which case you need to upgrade Pandoc separately.

And your example works for me:

![image](https://user-images.githubusercontent.com/163582/45797243-4aa9d700-bc6a-11e8-888f-c4c40a056d30.png)

**Comment by stragu** [comment]
Hi @yihui 

I am using the latest stable RStudio version (1.1.456) and:

```
> rmarkdown::pandoc_version()
[1] ‘1.19.2.4’

> xfun::session_info("rmarkdown")
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS, RStudio 1.1.456

Locale:
  LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_AU.UTF-8        LC_COLLATE=en_GB.UTF-8    
  LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_GB.UTF-8   
  LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   digest_0.6.17     evaluate_0.11     glue_1.3.0       
  graphics_3.4.4    grDevices_3.4.4   highr_0.6         htmldeps_0.1.1   
  htmltools_0.3.6   jsonlite_1.5      knitr_1.20        magrittr_1.5     
  markdown_0.8      methods_3.4.4     mime_0.5          Rcpp_0.12.18     
  rmarkdown_1.10.13 stats_3.4.4       stringi_1.2.4     stringr_1.3.1    
  tinytex_0.8       tools_3.4.4       utils_3.4.4       xfun_0.3         
  yaml_2.2.0       

Pandoc version: 1.19.2.4
```

So I guess this is still a valid report against the current stable version of RStudio? I'd like to stick to the stable version of RStudio rather than preview releases.

Good to know that it does work as intended in the next release of RStudio.

**Comment by yihui** [comment]
RStudio 1.1 has been released, so Pandoc won't be updated in it any more, and you'll have to either wait for RStudio 1.2, or install Pandoc by yourself. Thanks!
