### ISSUE TITLE
cannot knit to pdf file

### ISSUE THREAD

**Issue by Yufei-Z** [rstudio/rmarkdown#1450]
i try to knit it, but it shows Error: Failed to compile hw2.tex.
In addition: Warning message:
running command '"pdflatex" -halt-on-error -interaction=batchmode "hw2.tex"' had status 1 
Execution halted

**Comment by yihui** [comment]
Did you install LaTeX? https://bookdown.org/yihui/rmarkdown/installation.html

**Comment by Yufei-Z** [comment]
Yes, I have installed miktex and set “updating automatically” as your advice.
Best regards
yufei

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by yihui** [comment]
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? Please also include your session info:

```r
devtools::session_info('rmarkdown')
```

**Comment by Yufei-Z** [comment]
Dear yihui
Even knitting the template error may happen
[cid:image002.png@01D45417.15709DF0]
And seesion information

R version 3.4.4 (2018-03-15)

Platform: x86_64-w64-mingw32/x64 (64-bit)

Running under: Windows >= 8 x64 (build 9200)



Matrix products: default



locale:

[1] LC_COLLATE=English_United States.1252

[2] LC_CTYPE=English_United States.1252

[3] LC_MONETARY=English_United States.1252

[4] LC_NUMERIC=C

[5] LC_TIME=English_United States.1252



attached base packages:

character(0)



other attached packages:

[1] rmarkdown_1.10



loaded via a namespace (and not attached):

 [1] compiler_3.4.4  backports_1.1.2 magrittr_1.5

 [4] rprojroot_1.3-2 graphics_3.4.4  htmltools_0.3.6

 [7] tools_3.4.4     utils_3.4.4     yaml_2.2.0

[10] grDevices_3.4.4 Rcpp_0.12.18    stats_3.4.4

[13] datasets_3.4.4  stringi_1.1.7   knitr_1.20

[16] methods_3.4.4   stringr_1.3.1   digest_0.6.16

[19] base_3.4.4      evaluate_0.11


>



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

**Comment by yihui** [comment]
I'm afraid this is going to be hard to debug. There is too little information. Two things you can try:

1. Remove MiKTeX and install TinyTeX instead: https://bookdown.org/yihui/rmarkdown/installation.html

2. If that still fails, insert a code chunk containing the R code `options(tinytex.verbose = TRUE)`, compile the document, and see if there are additional error messages.
