### ISSUE TITLE
Trouble rendering word document with style from shiny server

### ISSUE THREAD

**Issue by mrjoh3** [rstudio/rmarkdown#1451]
I have been having trouble rendering a word docx file using a `reference_docx` style document on shiny server. The file renders but the style is not applied.

Curiously, the file and the style render as expected when the shiny app is run from rstudio server on the same machine. Plus I have tested a reprex on another machine and could not reproduce the error. 

I have created a [gihub repo](https://github.com/mrjoh3/reprex-shiny-rmd-docx) with a minimum example. I will include the shiny app code below.

The shiny server (open source) is version `Shiny Server v1.5.3.838" "Node.js v6.10.0` and is running on `Ubuntu 16.04.1`.  and I have updated the `shiny` and `rmarkdown` packages. 

The rmd and docx files are copied to a temp folder for rendering and I have ensured that the user permissions are and have ensured that the user permissions are `chmod 1777 /tmp`.

A similar issue was flagged on the [rstudio community forum](https://community.rstudio.com/t/generating-downloadable-reports-rmarkdown-reference-docx-yaml-header-is-not-read-by-knitr/3308), but the suggestions made there did not resolve the issue.My question there was moved [here](https://community.rstudio.com/t/issues-generating-downloadable-reports-from-shiny-server-word-document/14655),  @jcheng5 requested I submit an issue here with a reprex. All required files are in the [github repo](https://github.com/mrjoh3/reprex-shiny-rmd-docx), the `app.R` and `.Rmd` files are copied below. The `.docx` template file is [here](https://github.com/mrjoh3/reprex-shiny-rmd-docx/blob/984cc998709de6f08d55bb8321319d7bcd9d1f8d/photo_log_template.docx). 

please advise if more details are required.

## The app.R file 

```r
library(shiny)
library(dplyr)
library(knitr)
library(rmarkdown)
library(DT)
library(jsonlite)
library(hashids)


cat("Doing application setup\n")

onStop(function() {

  cat("Removing Temporary Files and Folders\n")
  unlink(temp_folder, recursive=TRUE)

})

temp_folder <<- file.path(tempdir(),
                          hashids::encode(as.integer(Sys.time()),
                                          hashid_settings(salt='fews', min_length = 6))
)

dir.create(temp_folder)

ui <- shinyUI(fluidRow(
  column(10,
        h2('Data Output'),
        DT::DTOutput("images"),
        downloadButton("report", "Generate report",
                       style="color: #fff; background-color: #337ab7; border-color: #2e6da4")
        )
  )
)

server <- shinyServer(function(input, output, session) {

    dat <- reactiveValues(images = data_frame("photographer" = c('A','B'),
                                              "organisation" = 'The Org',
                                              "location" = 'The Place',
                                              "address" = c('2 some place', '3 that place'))
    )

    output$images <- DT::renderDT(dat$images,
                                  server = FALSE,
                                  rownames = FALSE,
                                  class = 'dt-body nowrap',
                                  selection = 'single', editable = TRUE,
                                  extensions = c('Buttons','Responsive'),
                                  options = list(pageLength = 5,
                                                 dom = 'Blfrtip',
                                                 buttons = c('csv', 'excel')))

    output$report <- downloadHandler(

      filename = "Photo_Log.docx",
      content = function(file) {

        tempReport <<- file.path(temp_folder, "report.Rmd")
        tempTemplate <<- file.path(temp_folder, "photo_log_template.docx")
        file.copy("report.Rmd", tempReport, overwrite = TRUE)
        file.copy("photo_log_template.docx", tempTemplate, overwrite = TRUE)

        params <- list(organisation = input$select_org,
                       photographer = input$select_user,
                       df = select(dat$images,
                                   `Premises / Location` = location,
                                   Address = address)
                       )

        rmarkdown::render(tempReport, 'word_document',
                          output_file = file,
                          params = params,
                          envir = new.env(parent = globalenv())
        )
      }
    )

})

shinyApp(ui = ui, server = server)
```

## The rmd file

````
---
title: "Photograph Log"
output:
  word_document:
    reference_docx: photo_log_template.docx
params:
  organisation: NA
  photographer: NA
  df: NA
---

### Photograph Log: `r params$organisation`
### Photographer: `r params$photographer`

```{r, echo=FALSE, warning=FALSE}

library(knitr)

knitr::kable(params$df)

```
````

**Comment by yihui** [comment]
Thanks for the report! Your reprex is not minimal enough (packages like dplyr, jsonlite, DT, and hashids are unnecessary). Here is a minimized version:

## app.R

```r
library(shiny)

temp_folder <- tempfile()

onStop(function() {
  cat("Removing Temporary Files and Folders\n")
  unlink(temp_folder, recursive=TRUE)
})

dir.create(temp_folder)

ui <- shinyUI(downloadButton("report", "Generate report"))

server <- shinyServer(function(input, output, session) {

  dat <- data.frame(x = c('A', 'B'), y = as.character(rmarkdown::pandoc_version()))

  output$report <- downloadHandler(

    filename = "Photo_Log.docx",
    content = function(file) {

      tempReport <- file.path(temp_folder, "report.Rmd")
      tempTemplate <- file.path(temp_folder, "photo_log_template.docx")
      file.copy("report.Rmd", tempReport, overwrite = TRUE)
      file.copy("photo_log_template.docx", tempTemplate, overwrite = TRUE)

      rmarkdown::render(
        tempReport, 'word_document', output_file = file, params = list(df = dat)
      )
    }
  )
})

shinyApp(ui = ui, server = server)
```

## report.Rmd

````
---
title: "Photograph Log"
output: word_document
params:
  df: NA
---

### Photograph Log

### Photographer

```{r, echo=FALSE}
knitr::kable(params$df)
```
````

I published it to https://yihui.shinyapps.io/reprex-shiny-rmd-docx-master/ and I don't see any obvious problems.

I recommend that you compare the Pandoc versions in your RStudio Server and Shiny Server. In my minimal reprex, I added the version info to the table, so you can see it from the Word document.

**Comment by mrjoh3** [comment]
yes that's it the `shiny-server` and `rstudio-server` `pandoc` versions were different. `shiny` was still on 1.12. 

Thanks for your help, I have now updated `shiny-server` and everything works as expected. It had not occurred to me that the two servers would use separate versions of pandoc.
