### ISSUE TITLE
Passing greek letters as colnames to kable.

### ISSUE THREAD

**Issue by igvalmas** [rstudio/rmarkdown#1456]
I've been trying to name an R data frame columns with greek letters in order to call kable and get a latex output table with header names as these greek letters.
The result is that kable does not recognise column names as the way latex greek letters are written, or the arguments are not passing to the function in the correct format.

```{r}
A <- t(as.data.frame(seq(1:4)))
colnames(A) <- c("$\\\\alpha$", "$\\\\beta$", "$\\\\delta$", "$\\\\gamma$")
A %>%
  kable(.,"latex", escape = F, booktabs = T, linesep = "", align = "c")
```

Is there a way to do this propperly?

The best solution I,ve found so far is set column names of the data frame to NULL, and write the table headers form the knit options as follows:

```{r}
A <- t(as.data.frame(seq(1:4)))
colnames(A) <- NULL
A %>%
  kable(., "latex", escape = F, booktabs = T, linesep = "", align = "c") %>% 
  add_header_above(c("$\\\\alpha$", "$\\\\beta$", "$\\\\delta$", "$\\\\gamma$"))
```
But this way is quite messy and lacks of automation.

Finally I tried the following and it doesn't work too.
```{r}
A <- t(as.data.frame(seq(1:4)))
A %>%
  kable(., "latex", escape = F, booktabs = T, linesep = "", align = "c", col.names = c("$\alpha$", "$\beta$", "$\delta$", "$\gamma$"))
```

**Comment by yihui** [comment]
This looks like a question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead, and let us know the link if you don't get an answer in a few days. Thanks!
