### ISSUE TITLE
Allow epub to load css from html dependency?

### ISSUE THREAD

**Issue by haozhu233** [rstudio/rmarkdown#1457]
Right now when output is "epub"/"epub3", it is not possible to load css through HTML dependency. I'm wondering if it makes sense or possible to add "epub" and "epub3" to this line: https://github.com/rstudio/rmarkdown/blob/df4ec915a67608bf287f2633bb5eebb26d86c2d0/R/output_format.R#L765

I came across this problem when I was working on creating [documentation for using kableExtra in bookdown](https://haozhu233.github.io/kableExtra/bookdown/index.html). Now my solution was to load this bootstap table css manually through `bookdown::epub_book(stylesheet)` but it would be nice if HTML dependencies can be loaded automatically.

**Comment by yihui** [comment]
That might be fine, but I don't have time to think about the possible consequence of the change.

https://github.com/rstudio/rmarkdown/blob/df4ec915a67608bf287f2633bb5eebb26d86c2d0/R/render.R#L671-L690

**Comment by haozhu233** [comment]
@yihui I guess this code was created to prevent things like `DT` got rendered in `md/pdf_document`. If we add those 2 `epub`, it means some htmlwidgets may be rendered as html instead of images in `epub` (if `epub` does support those fancy things?). However, after I tried it out earlier in [my fork](https://github.com/haozhu233/rmarkdown/commit/e3fb1e35b68a5db14b90afb0fbbe8e81e2519bce), I did get what I need for kableExtra but surprisingly `DT` and `plotly` results were still rendered as images... 🧐Although it might be even better this way, I was sure about the reason...

Anyway, with this change, the only possible impacted domain is the epub output in `bookdown`.

I will do some more experiments with other html widgets tomorrow and let you know the result.

**Comment by haozhu233** [comment]
@yihui never mind. I found something that doesn't work already. `rmarkdown::paged_table`, which uses the same mechanism to load html dependencies, can't be rendered in `epub`. I guess with an error note, users at least know that there is something wrong. 

<img width="511" alt="screen shot 2018-10-04 at 12 51 41 am" src="https://user-images.githubusercontent.com/7014590/46453482-c0846700-c76f-11e8-8699-1d4c44a52a0a.png">
