### ISSUE TITLE
Export pandoc()

### ISSUE THREAD

**Issue by noamross** [rstudio/rmarkdown#1465]
I was wondering if you could export `pandoc()`.  There are a few pandoc commands that aren't covered by `pandoc_convert()` or `pandoc_version()` and would be nice to be able to run against the same version of pandoc **rmarkdown** is using. 

In my case I am calling `pandoc --print-default-data-file reference.pptx` to get the pandoc's internal template, which could be different places depending on the system and if the user has placed a template in their pandoc data directory. I'm currently doing so with a `getFromNamespace()` hack:

```
#' @importFrom utils getFromNamespace
get_default_pandoc_pptx <- function(outfile = tempfile(fileext = ".pptx")) {
  sys::exec_wait(getFromNamespace("pandoc", "rmarkdown")(),
    args = c("--print-default-data-file", "reference.pptx"),
    std_out = outfile)
  return(outfile)
}
```

**Comment by jjallaire** [comment]
Could you give us a PR for this? Maybe we could name the exported function `pandoc_exec()` ?

**Comment by noamross** [comment]
Done!
