### ISSUE TITLE
Background color (using zenburn highlight) in R-chunks not showing correctly

### ISSUE THREAD

**Issue by gponce-ars** [rstudio/rmarkdown#1471]
When I create an R-notebook and then apply highlight (zenburn) and theme (journal), the background color of the R-chunk shows in grey color and it should be black.  Already tested with both `rmarkdown` versions, the devel and latest in production through CRAN.  I'm using the latest version of Rstudio (Version 1.1.463).

![image](https://user-images.githubusercontent.com/20215136/47740320-bea9a880-dc34-11e8-8953-8ec133c44eb7.png)
**System info:**

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] yaml_2.2.0      xfun_0.4        tinytex_0.9     stringr_1.3.1   stringi_1.2.4  
 [6] mime_0.6        markdown_0.8    magrittr_1.5    knitr_1.20      jsonlite_1.5   
[11] htmltools_0.3.6 htmldeps_0.1.1  highr_0.7       glue_1.3.0      evaluate_0.12  
[16] digest_0.6.18   base64enc_0.1-3 Rcpp_0.12.19   

loaded via a namespace (and not attached):
[1] packrat_0.4.9-3   rmarkdown_1.10.14 tools_3.5.0       rsconnect_0.8.8   compiler_3.5.0   
```

**Comment by kevinushey** [comment]
The issue does not reproduce for me with either the CRAN version of `rmarkdown` or with the development version (v1.10.14) either.

**Comment by kevinushey** [comment]
Sorry, I think I misunderstood your question (I thought the issue you were reporting was the black background on the top of the chunk; whereas IIUC you expect the _whole_ background to be black, not grey).

This appears to be an issue in `rmarkdown` as opposed to RStudio since I can reproduce outside of RStudio. Would you mind filing (with the full document you're trying to use to reproduce just so we can also easily reproduce) at https://github.com/rstudio/rmarkdown/issues?

**Comment by gponce-ars** [comment]
@kevinushey 

By using the default example when you do File + New File + R Notebook, then add the `theme:  journal` and `highlight: zenburn` makes the behavior I posted. 

I also tested in a Mac Pro laptop and it's doing the same thing.  

This is the OSx version I currently have on my iMac and Mac pro. 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/20215136/47811463-11ea2c80-dd03-11e8-9cf6-280d7dbee970.png">
  
I asked a co-worker who is also using OSx and he didn't have the problem, he's getting the right highlight using zenburn with the default example.

![image](https://user-images.githubusercontent.com/20215136/47811558-41993480-dd03-11e8-86df-0f097ec83913.png)

I asked him to send me his .nb.html  so then I opened it on my Rstudio and did the renderization (preview) and the same thing happened again, gray background with the black background in the Hide/Show button.

I'm wondering if some add-ins could be causing this, I have this on my add-ins menu:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/20215136/47811895-21b64080-dd04-11e8-9916-e9089420794c.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/20215136/47811928-38f52e00-dd04-11e8-8438-a56ec4aec0d8.png">

I'll try to share the html generated by my co-worker and the one from me, so you can check there're some differences.  One initial is that it looks that his html is enconding javascript code and in my html the Javascript frameworks such as Jquery is not encoded.

**Comment by gponce-ars** [comment]
Html working well (from another Mac)
https://www.dropbox.com/s/rl54oaitxvur813/test_works.nb.html?dl=0

Html generated not working as expected 
https://www.dropbox.com/s/b09qd4mrypmvruu/test.notWorking.nb.html?dl=0

This is the contents of the .Rmd:

```
---
title: "R Notebook"
output:
  html_notebook:
    theme: journal
    highlight: zenburn
editor_options:
  chunk_output_type: inline
---

This is an [R Markdown](http://rmarkdown.rstudio.com) Notebook. When you execute code within the notebook, the results appear beneath the code.

Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Cmd+Shift+Enter*.
```
```{r}
# Comment
plot(cars)
```
```
Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
```

**Comment by kevinushey** [comment]
Thanks for the extra information.

I see the expected output with RStudio v1.1 + Pandoc 1.19.2.1, and the wrong / unexpected output with RStudio v1.2 + Pandoc 2.3.1. Can you confirm what version of Pandoc is being used in your case? That is, what is the output of the following in your R session?

``` r
rmarkdown:::.pandoc$version
```

I'm going to distill this into a separate issue after a bit more investigation.

**Comment by kevinushey** [comment]
Thanks for the extra information. I think this is ultimately caused by a change in the way Pandoc emits highlight rules. Compare with Pandoc 1.19.2.1 (as bundled in RStudio v1.1)

![screen shot 2018-10-31 at 4 08 04 pm](https://user-images.githubusercontent.com/1976582/47823818-348e3c80-dd27-11e8-99ff-4ec9c9598cee.png)

And with RStudio v1.2, with Pandoc 2.3.1:

![screen shot 2018-10-31 at 4 08 21 pm](https://user-images.githubusercontent.com/1976582/47823830-3ce67780-dd27-11e8-8d7e-01a10ce7d201.png)

If we look at the highlight rules, we see in the Pandoc 1.19.2.1 some override rules are defined for `pre` that get used. 

![screen shot 2018-10-31 at 4 10 41 pm](https://user-images.githubusercontent.com/1976582/47823888-88992100-dd27-11e8-8f82-f7a7574d24aa.png)

However, those styles no longer exist with Pandoc 2.3.1 and so some different style is gaining higher precedence. Inspecting the command used to generate the file:

``` r
/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS zen.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output zen.html --email-obfuscation none --self-contained --standalone --section-divs --template /Users/kevin/Library/R/3.5/library/rmarkdown/rmd/h/default.html --highlight-style zenburn --variable 'theme:bootstrap' --include-in-header /var/folders/qt/txb728ms5012wp_4yn369wth0000gn/T//RtmpE0RtZS/rmarkdown-str364c7e245110.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
```

We see that rmarkdown generates a temporary file for including in the header of the generated document. If I inspect that `rmarkdown-str` file, I see it contains:

```
<script src="/Users/kevin/Library/R/3.5/library/htmldeps/rmd/h/jquery/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="/Users/kevin/Library/R/3.5/library/htmldeps/rmd/h/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<script src="/Users/kevin/Library/R/3.5/library/htmldeps/rmd/h/bootstrap/js/bootstrap.min.js"></script>
<script src="/Users/kevin/Library/R/3.5/library/htmldeps/rmd/h/bootstrap/shim/html5shiv.min.js"></script>
<script src="/Users/kevin/Library/R/3.5/library/htmldeps/rmd/h/bootstrap/shim/respond.min.js"></script>
<script src="/Users/kevin/Library/R/3.5/library/rmarkdown/rmd/h/navigation-1.1/tabsets.js"></script>
```

Note in particular the inclusion of the Boostrap CSS, and IIUC currently Bootstrap 3.3.5 is used in `htmldeps`. The rules for `pre` are hence from there:

https://github.com/twbs/bootstrap/blob/16b48259a62f576e52c903c476bd42b90ab22482/dist/css/bootstrap.css#L1560-L1572

All that said, I don't yet know what the right fix is.

**Comment by gponce-ars** [comment]
Ok... Since I'm more interested in getting the styling solved for readability, I decided to do this:
1. Remove 2.3.1 with pandoc perl script (https://raw.githubusercontent.com/jgm/pandoc/master/macos/uninstall-pandoc.pl)
2. Install 1.19.12.1 using this: https://github.com/jgm/pandoc/releases/tag/1.19.2.1

That's it, back to normal.

I guess this is another reason to keep Pandoc 1.x in rmarkdown as @yihui stated in one of his blog-posts [No Need to Upgrade to Pandoc 2.0 (Yet)](https://yihui.name/en/2017/11/pandoc-2/)

I'm not sure if this issue can be closed or moved?

**Comment by yihui** [comment]
I'll investigate this issue as soon as I have time. At this point, I don't want to push users back to Pandoc 1.19.

**Comment by cderv** [comment]
More precisely in happened in jgm/skylighting#25 where the choice was made to apply colour only to the outer div. That is why it is now `div.sourceCode` only. 
A fix in Rmarkdown could be to apply a css rule based on pandoc choice
```css
pre.sourceCode  {
  color: inherit;
  background-color: transparent;
}
```
This would make the `<pre class="sourceCode">` impacted by `<div class="sourceCode">` and this way not be erase by bootstrap or by the journal theme. 

A quick fix waiting to see how to report this to Pandoc ? 🤔

**Comment by yihui** [comment]
@cderv Thanks a lot for the investigation! Please feel free to submit a PR to add the above four lines of CSS to the default HTML template.

**Comment by cderv** [comment]
I opened a PR to show progress on this. I think the impact is broader and the four lines are not enough. Further discussion in the PR.

**Comment by yihui** [comment]
Should be fixed now. Thanks @gponce-ars for the report and @cderv @RLesur @kevinushey for the help!
