### ISSUE TITLE
Plots generated in chunk don't appear with render_site()

### ISSUE THREAD

**Issue by rmcd1024** [rstudio/rmarkdown#1472]
For a reproducible example and complete explanation see https://stackoverflow.com/questions/53093495/plots-generated-in-chunk-dont-appear-with-rmarkdownrender-site

Summary: if rendering both pdf and html output with `render_site`, the `figure-html` subdirectory gets removed if html output is generated first, so the figures linked in the html file don't exist when rendering completes.

Since the generated html file has links to figure-html, isn't it a bug that the figure-html directory is ever removed?

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
