### ISSUE TITLE
Stan code chunk not visible in HTML output

### ISSUE THREAD

**Issue by VectorPosse** [rstudio/rmarkdown#1478]
Posted to StackOverflow with no solution:

[https://stackoverflow.com/questions/52049377/stan-code-chunk-not-visible-in-html-output](https://stackoverflow.com/questions/52049377/stan-code-chunk-not-visible-in-html-output)

In an R notebook (using the `html_notebook` output type), the "Preview" button produces a `.nb.html` file in which Stan code chunks fail to appear.

The Stan code chunk runs just fine. The output is available to future code chunks. But in the rendered HTML file, the Stan code is not visible.

Here is a full markdown document as a reproducible example.

````
---
title: "Stan chunk reprex"
output: html_notebook
---

```{r}
library(rstan)
```

```{r}
N <- 18
y <- c(rep(1, 12), rep(0, 6))
stan_data <- list(N = N, y = y)
```

```{stan, output.var = "bin_unif"}
data {
    int<lower = 0> N;
    int<lower = 0, upper = 1> y[N];
}
parameters {
    real<lower = 0, upper = 1> theta;
}
model {
    theta ~ uniform(0, 1);  // prior
    y ~ bernoulli(theta);   // likelihood
}
```

```{r}
fit_bin_unif <- sampling(bin_unif, data = stan_data)
fit_bin_unif
```
````

**Comment by kevinushey** [comment]
Please take the time to fill out the issue template so we know what version of RStudio + R + OS you're using.

**Comment by kevinushey** [comment]
Thanks -- this is an issue in the RStudio IDE's integration with rmarkdown as opposed to an issue with rmarkdown directly. We'll take a look!

**Comment by VectorPosse** [comment]
Sorry, I forgot the version info:

```
- Session info --------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 ```

**Comment by kevinushey** [comment]
This should be fixed in the latest [preview release](https://www.rstudio.com/products/rstudio/download/preview/) of RStudio -- thanks for reporting!
