### ISSUE TITLE
Setting fig.align in R chunks makes plot disappear in Beamer

### ISSUE THREAD

**Issue by xiaoweiz** [rstudio/rmarkdown#148]
If the option `fig.align` is set to anything other than `default`, the figure won't show up in the generated beamer slides.

Minimal example: 

`````` markdown

---
title: "Untitled"
author: "X"
date: "30 June, 2014"
output: beamer_presentation

---
## Slide with Plot
```{r, echo=FALSE, fig.align='center'}
plot(cars)```

``````

**Comment by johnsonzhj** [comment]
fig.align='center' seem still not work in the current version of knitr.

**Comment by yihui** [comment]
@johnsonzhj You may also need the development version of rmarkdown here.
