### ISSUE TITLE
unsupported conversion from 'UTF-8-BOM' to 'UTF-8' in codepage 1252

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rmarkdown#1480]
Hello,

I am testing some document formats written in Korean using R Markdown.
I know I have to save my Rmd file as "UTF-8 without BOM," however, I was wondering if there would be any way to render Rmd file encoded with UTF-8 with BOM.

Since RStudio is not accessible to screen reading software (I am blind so I am using assistive technology when doing R, but the ACE editor that R Studio employs is not accessible for assistive technology), I have to use Notepad++ in Windows platform to save any file as UTF-8 without BOM. But I am lazy to use NPP; just would like to use notepad.

To cut to the chase, Notepad, the built-in text editor in Windows, does not have options for saving a file as UTF-8 without BOM; it only saves it as UTF-8 with BOM.
So there should be a warkaround to render UTF-8-BOM. I used `encoding="UTF-8-BOM"` for a test file generated from notepad (not NPP), but it seems like it fails.

I am attaching `test.Rmd` (I had to change its file extension for upload) file for reproducibility of the issue.
The original error message I got from the terminal is different from what I obtained from `reprex::reprex()` function, so I am also copying and pasting the original error message here as well:

``` r
# This is what I see (actually, what I hear...) on my end in the terminal:
rmarkdown::render('test.Rmd', output_format='all', encoding='UTF-8-BOM')                                                                             
     
#> Error in iconv(x, from = encoding, to = "UTF-8") :                                                                                                     
#> unsupported conversion from 'UTF-8-BOM' to 'UTF-8' in codepage 1252                                                                                   
```

The following is generated by reprex:

``` r
rmarkdown::render('test.Rmd', output_format='all', encoding='UTF-8-BOM')
#> Warning in file(con, "r"): cannot open file 'test.Rmd': No such file or
#> directory
#> Error in file(con, "r"): cannot open the connection
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2018-11-14                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib
#>  assertthat    0.2.0      2017-04-11 [1]
#>  backports     1.1.2      2017-12-13 [1]
#>  base64enc     0.1-3      2015-07-28 [1]
#>  callr         3.0.0      2018-08-24 [1]
#>  cli           1.0.1      2018-09-25 [1]
#>  crayon        1.3.4      2017-09-16 [1]
#>  desc          1.2.0      2018-05-01 [1]
#>  devtools      2.0.1.9000 2018-11-08 [1]
#>  digest        0.6.18     2018-10-10 [1]
#>  evaluate      0.12       2018-10-09 [1]
#>  fs            1.2.6      2018-08-23 [1]
#>  glue          1.3.0      2018-10-31 [1]
#>  highr         0.7        2018-06-09 [1]
#>  htmltools     0.3.6      2017-04-28 [1]
#>  knitr         1.20.22    2018-11-13 [1]
#>  magrittr      1.5        2014-11-22 [1]
#>  memoise       1.1.0      2017-04-21 [1]
#>  pkgbuild      1.0.2      2018-10-16 [1]
#>  pkgload       1.0.2      2018-10-29 [1]
#>  prettyunits   1.0.2      2015-07-13 [1]
#>  processx      3.2.0      2018-08-16 [1]
#>  ps            1.2.1      2018-11-06 [1]
#>  R6            2.3.0      2018-10-04 [1]
#>  Rcpp          1.0.0.1    2018-11-11 [1]
#>  remotes       2.0.2      2018-10-30 [1]
#>  rlang         0.3.0.9000 2018-11-14 [1]
#>  rmarkdown     1.10.15    2018-11-06 [1]
#>  rprojroot     1.3-2      2018-01-03 [1]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  stringi       1.2.4      2018-07-20 [1]
#>  stringr       1.3.1.9000 2018-09-19 [1]
#>  testthat      2.0.1      2018-10-13 [1]
#>  usethis       1.4.0.9000 2018-11-14 [1]
#>  withr         2.1.2      2018-03-15 [1]
#>  xfun          0.4        2018-10-23 [1]
#>  yaml          2.2.0      2018-07-25 [1]
#>  source                            
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.0)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  Github (r-lib/devtools@9780c9f)   
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  Github (tidyverse/glue@35c61e9)   
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  Github (yihui/knitr@dc5ead7)      
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  Github (RcppCore/Rcpp@4f168e6)    
#>  CRAN (R 3.5.1)                    
#>  Github (hadley/rlang@31b80d4)     
#>  Github (rstudio/rmarkdown@9875136)
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  Github (hadley/stringr@0b5a4c4)   
#>  CRAN (R 3.5.1)                    
#>  Github (r-lib/usethis@6fee375)    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#>  CRAN (R 3.5.1)                    
#> 
#> [1] C:/Program Files/R/R-3.5.1/library
```

</details>

[test.Rmd.txt](https://github.com/rstudio/rmarkdown/files/2583651/test.Rmd.txt)

**Comment by cderv** [comment]
Hi, 

Did you tried to render the file using simply `encoding = "UTF-8"` ? I believe it would detect BOM or not. 
With your Rmd file example, I manage to render it
``` r
tempfile <- tempfile(fileext = ".Rmd")
url<- "https://github.com/rstudio/rmarkdown/files/2583651/test.Rmd.txt"
download.file(url, destfile = tempfile, mode = "wb")
readr::guess_encoding(tempfile)
#> # A tibble: 3 x 2
#>   encoding     confidence
#>   <chr>             <dbl>
#> 1 UTF-8              1   
#> 2 windows-1252       0.41
#> 3 windows-1250       0.21
res <- rmarkdown::render(tempfile, encoding = "UTF-8")
#> processing file: file6b9058c45548.Rmd
#> output file: file6b9058c45548.knit.md
#> "C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS file6b9058c45548.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output file6b9058c45548.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\chris\Documents\R\win-library\3.5\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Users\chris\AppData\Local\Temp\RtmpKaDDAQ\rmarkdown-str6b90307e3bd6.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --metadata pagetitle=file6b9058c45548.utf8.md
#> 
#> Output created: file6b9058c45548.html
```

``` r
# to see the file
browseURL(res)
```

![image](https://user-images.githubusercontent.com/6791940/48536086-c3fe2880-e8ad-11e8-9c39-7b6b57eac2e5.png)

**Comment by jooyoungseo** [comment]
Hello @cderv,

Thank you very much for your kind support. I have also tried `encoding="UTF-8"`; however, it only returns HTML output not other output types I had defined in the `test.Rmd` YAML.

I am re-attaching a file, called `k.Rmd.txt` (please change the file extension into .Rmd). This file is saved in Windows notepad as UTF-8, which is UTF-8 with BOM.
Please test whether you can render this file into Word file (not HTML) that I declared in the YAML.
I cannot render this using either UTF-8 or UTF-8-BOM.

[k.Rmd.txt](https://github.com/rstudio/rmarkdown/files/2586915/k.Rmd.txt)

**Comment by yihui** [comment]
@jooyoungseo I think this is a bug of **rmarkdown**. I just pushed a fix. Please test the current Github version (`remotes::install_github('rstudio/rmarkdown')`). Thanks for the report!

**Comment by yihui** [comment]
Actually [I have been hoping](https://yihui.name/en/2018/11/biggest-regret-knitr/) to drop the support for all other character encodings and only support UTF-8 in the (far) future, so I'll truly appreciate it if you can stick with UTF-8.

**Comment by jooyoungseo** [comment]
I really appreciate your quick and kind address @yihui!
I have just confirmed that `encoding="UTF-8-BOM"` renders the file correctly now! Yes, I will attempt to save my Rmd files as UTF-8 without BOM using NPP. My high hope is that RStudio provides blind people with the accessible program interface soon so that I do not need to rely on either NPP or original notepad in Windows.

**Comment by yihui** [comment]
@jooyoungseo Heard you. Actually the RStudio IDE team has just talked to another blind user a couple of weeks ago on improving the accessibility. I'm not on the IDE team, so I don't have further news to share, but I believe we'll certainly try to address this issue in the future. Thank you!

**Comment by jooyoungseo** [comment]
@yihui, that's  such a great sign! I deeply appreciate RStudio's nice consideration on that issue!
