### ISSUE TITLE
Provide finer-grained control over pandoc and pandoc-citeproc locations

### ISSUE THREAD

**Issue by hammer** [rstudio/rmarkdown#1482]
I'm hunting down a rendering bug that I believe to be related to a specific Pandoc version. I'd like to be able to render the document multiple times in a single R session using different versions of `pandoc`, but `find_pandoc()` and `.pandoc` are private to the `rmarkdown` package.

I'd like to at least be able to invalidate the `.pandoc` cache.

**Comment by jjallaire** [comment]
Good feature request. We should probably export a "discover_pandoc()" function which invalidates the cache and calls `find_pandoc()` under the hood.

In the meantime, this code will invalidate the cache:

```r
assign("dir", NULL, envir = rmarkdown:::.pandoc)
```

Another approach would be to use the callr package (https://github.com/r-lib/callr#readme) to execute your testing code in a fresh R process.

**Comment by yihui** [comment]
The cache can be invalidated via `rmarkdown:::find_pandoc(cache = FALSE)` now. Thanks for the report!

**Comment by hammer** [comment]
Thanks for the quick fix but why not make this API public? It seems like bad practice to keep useful functionality hidden behind `:::`.

**Comment by yihui** [comment]
Unless you need to use it in a CRAN package, I tend not to export it, since exporting it means I have to document it (and assume greater responsibility), which I don't have time to do at the moment (if you do, a pull request is welcome; I guess the documentation may be merged with `?pandoc_version`).
