### ISSUE TITLE
HTML summary triangle is missing in Firefox

### ISSUE THREAD

**Issue by Bisaloo** [rstudio/rmarkdown#1483]
## Description of the issue

The triangle that signals that a HTML section has been folded with `<details><summary>...</summary></details>` is missing in Firefox, as illustrated in the screenshot below from the [pkgdown details page](https://pkgdown.r-lib.org/articles/test/details.html):

![](https://user-images.githubusercontent.com/8360597/48353275-507ed000-e68f-11e8-870a-50b7707e09b2.png)

## Steps to reproduce 

Run `rmarkdown::render()` on the following example and view the ouput **in Firefox**:

````
---
title: 'Missing triangle'
output: html_document
---

<details>Once upon a time...</details>

<details>
  <summary>Long story</summary>
  Once upon a time...
</details>
````

## Source of this issue

According to Mozilla docs, [the HTML spec requires `display: list-item` to display the triangle. On the other hand, `display: block` will remove it.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#Default_style)

This means the current `rmarkdown` bootstrap template will remove the triangle:

https://github.com/rstudio/rmarkdown/blob/98751369bac17d1ae2a5ce966c11f0c473d6d8d7/inst/rmd/h/bootstrap/css/bootstrap.css#L27-L29

## Proposed fix

1. This was fixed upstream in https://github.com/twbs/bootstrap/issues/21060. The best solution would be to update `rmarkdown` bootstrap template to the latest version.

1. According to https://github.com/rstudio/rmarkdown/issues/1260, it may be difficult to update the template so an alternative (temporary) fix would be to simply add:

```css
summary {
  display: list-item
}
```

to [`default.html`](https://github.com/rstudio/rmarkdown/blob/0ff85d8db1c1b75386cc752062f6016884709139/inst/rmd/h/default.html) to overwrite the style specified in [`boostrap.css`](https://github.com/rstudio/rmarkdown/blob/f111cf9601393317bac9cbc0e6dc81336c4fe002/inst/rmd/h/bootstrap/css/bootstrap.css)

## Additional info

This issue was first reported by @maelle in the pkgdown repo: https://github.com/r-lib/pkgdown/issues/884

I can try to submit a PR if that helps. I would probably need some guidance if you decide to go with the first proposed fix (update bootstrap template) though.

**Comment by yihui** [comment]
The second proposed fix sounds good to me (feel free to send a PR). Thanks a lot for your investigation and clear explanations!
