### ISSUE TITLE
replacing paged_table_type_sum with tibble::type_sum

### ISSUE THREAD

**Issue by sebkopf** [rstudio/rmarkdown#1487]
I'm curious if this is still the plan as noted in the comments for `paged_table_type_sum`? It would be extremely useful to help standardize the display of column types between interactive RStudio use and knitted documents displaying paged tables, especially for new classes that implement their own `type_sum.new_class` methods.

https://github.com/rstudio/rmarkdown/blob/34d2fd0ebceb91705a54692ee5cfb46f0f09e28e/R/html_paged.R#L2

**Comment by yihui** [comment]
Cc @javierluraschi I think you are the right person to ask.

**Comment by sebkopf** [comment]
Following up on this issue - pillar is moving away from the `type_sum()` generic for succinct column headers and towards the new `vctrs::vec_ptype_abbr()` which provides easy-to-implement data type abbreviations as part of the excellent [vctrs](https://github.com/r-lib/vctrs) framework. At present, new `vctrs` data types still show up as generic `<S3: class name>` in paged tables - would you be willing to consider a move towards `vctrs::vec_ptype_abbr()` in `rmarkdown:::paged_table_type_sum` for S3 classes that extend `vctrs_vctr`? This would make it possible to have consistent column headers for custom data types in interactive RStudio and knitted documents with paged tables. I'd be happy to provide a suggestion via pull request if you're okay with adding `vctrs` to the `Imports`?
