### ISSUE TITLE
Possibility to knit / render a .Rmd file that has errors in code chunks?

### ISSUE THREAD

**Issue by skranz** [rstudio/rmarkdown#149]
If I press the button 'Knit Html', it typically fails to generate a HTML file if there is an error in a code chunk. Is there a possibility to still generate the HTML file and just show in the output of the code chunk that there is an error?

My use case are R problem sets that often cause errors until students have correctly solved all exercises. Here is a simple example:

``````
    # A problem set

    a) Generate a vector x consisting of 4 numbers
    ```{r}
    # Generate x here ...
    ```
    We can now calculate with x.
    For example the following code multiplies each element by 3:
    ```{r}
    3*x
    ```
``````

The example `3*x` only runs after the student has correctly generated a variable `x`. Without generating `x`, RMarkdown stops the knitting with an error message:
`Error in eval(expr,envir,enclos): object 'x' not found: ....`

Yet, it would be nice if students could generate a HTML file even when not all code chunks run without error.

**Comment by sy2729** [comment]
@ramnathv Thanks. I got my issue solved finally!

**Comment by lucaspaolucci** [comment]
I was experiencing this same issue. Thanks @ramnathv, setting error=T solved it!

**Comment by isaactpetersen** [comment]
Setting `error = TRUE` does not solve the error for me.  I'm trying to use the `render()` function.
