### ISSUE TITLE
Comments in PowerPoint presentations

### ISSUE THREAD

**Issue by mattantaliss** [rstudio/rmarkdown#1495]
I wanted to add some explanatory comments to a sample presentation and discovered that a comment in a section header slide breaks the presentation. An example is attached ([Untitled.txt](https://github.com/rstudio/rmarkdown/files/2664978/Untitled.txt); GitHub didn't allow .Rmd, so I renamed it to be a .txt file), which is just a slightly-modified version of the default content of a new presentation.

When the comment in the first section slide (line 12) is included, the presentation doesn't render correctly; when it is removed, the presentation renders fine. I can include comments in 'Title and Content' slides and 'Two Content' slides, just not 'Section Header' slides.

**Comment by mattantaliss** [comment]
Follow-up: If a comment is put between a 'Two Content' slide header and its content, then the slide is split apart (one just has the header, one just has the content).

**Comment by 1beb** [comment]
As a temporary work-around you can use an R code chunk with `#`

**Comment by nwstephens** [comment]
This looks like a Pandoc issue. https://github.com/jgm/pandoc/issues/6688

For reference, I verified this issue with slightly simpler code. This code renders as a single slide when we would expect it to render as two separate slides.

```
---
output: powerpoint_presentation
---

# Section Header

<!-- Some comments here -->

## Content Slide

Lorem ipsum
```

**Comment by nwstephens** [comment]
The issue here is that Pandoc treats comments like content and set the slide level to the section header. The solution is to override the default slide level as described under [Structuring the Presentation](https://support.rstudio.com/hc/en-us/articles/360004672913-Rendering-PowerPoint-Presentations-with-RStudio). This code will give you the desired result.

```
---
output: 
  powerpoint_presentation:
    slide_level: 2
---

# Section Header

<!-- Some comments here -->

## Content Slide

Lorem ipsum
```
