### ISSUE TITLE
Filenames containing spaces are not addressable in Markdown

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rmarkdown#151]
Repro
1.  Give an image file a filename containing a space (e.g. `foo logo.png`)
2. Add this logo to a R Markdown document: `![Foo](foo logo.png)`

Result:

```
pandoc: Could not find data file foo%20logo.png
Error: pandoc document conversion failed with error 97
```

**Comment by yihui** [comment]
It seems I can no longer repro this issue, so closing now.
