### ISSUE TITLE
Use new LaTeX templates from Pandoc

### ISSUE THREAD

**Issue by adunning** [rstudio/rmarkdown#1510]
This is following on the discussion from #1509. The `default-1.17.0.2.tex` template is based is on the version at <https://github.com/jgm/pandoc-templates/blob/fea830fcd27b4df2a337ac774daa7d4bbca00866/default.latex>, which shows that the differences boil down to the following sections:

- <https://github.com/rstudio/rmarkdown/blob/c0b5945458aa1a99718ee174f9633ed65141f939/inst/rmd/latex/default-1.17.0.2.tex#L108>: added in <https://github.com/rstudio/rmarkdown/commit/bc2a49ed9da00fd5ec414bc192b112bbba34513d> for Pandoc 2.x compatibility, already in newer upstream templates
- <https://github.com/rstudio/rmarkdown/blob/c0b5945458aa1a99718ee174f9633ed65141f939/inst/rmd/latex/default-1.17.0.2.tex#L190>: I'm having trouble finding the reason for this, but if memory serves, this was a very old Pandoc bug in which it wasn't using `\thanks` for footnotes for `\maketitle`
- https://github.com/rstudio/rmarkdown/blob/c0b5945458aa1a99718ee174f9633ed65141f939/inst/rmd/latex/default-1.17.0.2.tex#L195

The last bit is the only significant difference in the repository's template. I think the intent of this was to fix the problem that Pandoc doesn't render `\subtitle` by default. This could be done more efficiently by adding the following via `header-includes`:

```latex
% Render \subtitle in \maketitle
\usepackage{titling}
\providecommand{\subtitle}[1]{%
  \posttitle{%
    \par\end{center}
    \begin{center}\large#1\end{center}
  }%
}
```

This should be fixed upstream; I'll take care of it.

**Comment by adunning** [comment]
Simpler code, submitted in #5213:

```latex
\providecommand{\subtitle}[1]{%
    \usepackage{titling}
    \posttitle{%
  \par\large#1\end{center}}
}
```

**Comment by adunning** [comment]
The `subtitle` fix is now in the upstream template. I still don't entirely understand what the footnote protection is intended to achieve, but I think we can assume it's unnecessary, because this certainly works:

```shell
pandoc -o test.pdf << EOT

---
title: "Test^[test]"
---

test

EOT
```

**Comment by adunning** [comment]
The `subtitle` fix (and other improvements) will be in the Pandoc 2.6, which will be out soon. For earlier versions, you could simply add my `etoolbox` solution above through header-includes without having to maintain separate templates.

If you also want to retain the compression of `\maketitle` (I don't think its appearance is desirable, but putting that aside), I could come up with something that could also be inserted this way.

**Comment by yihui** [comment]
Yes, as I said in https://github.com/rstudio/rmarkdown/pull/1509#issuecomment-453208600, I'm all for dropping our homemade LaTeX template if there is a more elegant way through `header-includes`. Thank you!

BTW, RStudio 1.2.x (not officially released yet) has bundled Pandoc 2.6 on Windows only. For *nix platforms, the Pandoc version is still 2.3.1. For RStudio 1.1.x, it is still Pandoc 1.9.x. When you patch the default template, you'll need to consider these information.

**Comment by adunning** [comment]
That's excellent. Allowing each version of Pandoc to use its built-in template will fix the problems that the custom templates were attempting to solve.

If you're concerned about the subtitle not appearing for users of Pandoc 1.16 (when the problem first appeared) through 2.5, you could add the `etoolbox` code from above through `header-includes` if the version of Pandoc is less than 2.6. That will avoid potential conflicts with the `titling` package while changing the appearance minimally. This is completely backwards-compatible; adding the code through `header-includes` in versions before Pandoc 1.16 won't do any harm.

**Comment by yihui** [comment]
Sounds great! I guess I won't have time for this in the next few months, but I'd welcome a pull request!

**Comment by jemus42** [comment]
Quick question as I found this issue through searching before I submit a different issue:

Am I understanding correctly that this is related to my surprise given that `subtitle: my subtitle` in the YAML header of document to be rendered through `pdf_document` *actually gives be a subtitle* even though as of now that is not a documented argument in `pdf_document()` (which also does not have `...`)?

I compared this to `html_document()` which at least has `...` and says it passes those to `html_document_base()` – I'm since trying to figure out how `pdf_document` knows about the `subtitle:` YAML option and doesn't throw an error due to an unknown argument.

(For completeness: I'm on pandoc `‘2.7.1’`)

**Comment by adunning** [comment]
Right – the `subtitle` variable is covered through the LaTeX template. There are a number of similar things not in the Rmarkdown documentation; see the [Pandoc manual](https://pandoc.org/MANUAL.html).

**Comment by yihui** [comment]
I have finished tweaking the PR #1563 and merged it. Thanks a lot for your contribution! I'm really happy about the outcome!

**Comment by adunning** [comment]
Thank you for the revisions and all your work on this!
