### ISSUE TITLE
Can't knit md to html within PDF-bound Rmd

### ISSUE THREAD

**Issue by eheinzen** [rstudio/rmarkdown#1512]
I'm having trouble rendering a separate .md file into an HTML document from within a PDF-bound .Rmd.  Basically, here's what I'm trying to do:

````
---
output: pdf_document
---

```{r}
cat("hi there", file = "hithere.md")
rmarkdown::render("hithere.md", output_format = rmarkdown::html_document())
```
````

If I run these lines in the console, it works fine, but as soon as I try to render the PDF (the "parent" document), it fails with this error:

```
Error: Failed to compile hithere.tex. See hithere.log for more info. Execution halted
```
I'm not sure why it's using a tex file to output to HTML, but In that log file it notes:
```
! LaTeX Error: Missing \begin{document}.
```

Here is my session info:

```
> xfun::session_info('rmarkdown')
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200), RStudio 1.1.463

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  digest_0.6.18    evaluate_0.12    glue_1.3.0       graphics_3.5.2  
  grDevices_3.5.2  highr_0.7        htmltools_0.3.6  jsonlite_1.6     knitr_1.21      
  magrittr_1.5     markdown_0.9     methods_3.5.2    mime_0.6         Rcpp_1.0.0      
  rmarkdown_1.11.3 stats_3.5.2      stringi_1.2.4    stringr_1.3.1    tinytex_0.10    
  tools_3.5.2      utils_3.5.2      xfun_0.4         yaml_2.2.0      

Pandoc version: 1.19.2.1
```

Thanks for your time!
Ethan

**Comment by RLesur** [comment]
@eheinzen  I was able to reproduce your problem. 
Using `rmarkdown::render(..., envir = new.env(parent = emptyenv()))` solved it.

**Comment by eheinzen** [comment]
Thanks for looking into it!  Did you mean something like this?

````
---
output: pdf_document
---

```{r}
cat("hi there", file = "hithere.md")
rmarkdown::render("hithere.md", output_format = rmarkdown::html_document(),
                  envir = new.env(parent = emptyenv()))
```
````

Even with that, I'm still getting the same error.  I had tried playing around with the `envir=` argument before posting without much luck, so I'm not sure what's going on with that

**Comment by eheinzen** [comment]
Not sure if this is helpful or not, but It looks like the appropriate HTML got written to hithere.tex, but that it's trying to compile it as a PDF instead of HTML

**Comment by kevinushey** [comment]
The output format in the YAML header always overrides anything that might be passed directly to the `render()` function.

I think the simplest way to handle your case would be to write the document out at `.md`, but explicitly change the YAML header to produce an HTML document.

**Comment by kevinushey** [comment]
(also perhaps worth saying that `render()` always expects to receive an R Markdown document, so even though you're giving it a file with extension `.md` it's still going to render it as an `.Rmd`, hence parsing of the YAML header)

**Comment by eheinzen** [comment]
Thanks for the ideas!

I did notice that it works if you cat to an Rmd:

````
---
output: pdf_document
---

```{r}
# this works
cat("hi there", file = "hithere.Rmd")
rmarkdown::render("hithere.Rmd", output_format = rmarkdown::html_document())
```
````

It also works to cat to an md if the "parent" document is HTML and you're trying to render to PDF:

````
---
output: html_document
---

```{r}
# this also works
cat("hi there", file = "hithere.md")
rmarkdown::render("hithere.md", output_format = rmarkdown::pdf_document())
```
````

However, explicitly specifying the md as html in its YAML header didn't work:

````
---
output: pdf_document
---

```{r}
cat("---\noutput: html_document\n---\n\nhi there", file = "hithere.md")
rmarkdown::render("hithere.md")
```
````

The original post works if I revert to rmarkdown v1.8, and breaks upon v1.9.  Is it something to do with tinytex?  I'm currently using MiKTeX, but I tried renaming the MiKTeX install directory and using tinytex instead, which solved the problem.

**Comment by eheinzen** [comment]
I had tried the "install missing packages on the fly" fix from #1285 , but that didn't work either.

**Comment by yihui** [comment]
Due to all sorts of complicated side-effects, I don't really recommend calling `rmarkdown::render()` within an Rmd document to render it to a different output format. If you must do it, I recommend doing it in a new R session, e.g. you can use the **callr** package: https://cran.rstudio.com/web/packages/callr/

**Comment by eheinzen** [comment]
Works for me!
