### ISSUE TITLE
Error in tools::file_path_as_absolute(output_file) :

### ISSUE THREAD

**Issue by mzhibo** [rstudio/rmarkdown#1520]
I couldn't output pdf file in the rstudio with r markdown. I saw the same issue with previous versions in the threads. I have MikeTex 2.9 installed.
The log file when I click Knit-pdf is shown below:

processing file: testworld.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: cars
  |..............................................                   |  71%
  ordinary text without R code

  |........................................................         |  86%
label: pressure (with options) 
List of 1
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS testworld.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output testworld.tex --template "C:\Rpackages\3.5\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" 
output file: testworld.knit.md

Output created: testworld.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'testworld.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning message:
In readLines(logfile) : incomplete final line found on 'testworld.log'
Execution halted
__________________________________________________________________________________________________________
Session info:
xfun::session_info("rmarkdown")
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 digest_0.6.18   evaluate_0.12   glue_1.3.0      graphics_3.5.2  grDevices_3.5.2 highr_0.7      
  htmltools_0.3.6 jsonlite_1.6    knitr_1.21      magrittr_1.5    markdown_0.9    methods_3.5.2   mime_0.6       
  Rcpp_1.0.0      rmarkdown_1.11  stats_3.5.2     stringi_1.2.4   stringr_1.3.1   tinytex_0.10    tools_3.5.2    
  utils_3.5.2     xfun_0.4        yaml_2.2.0     

Pandoc version: 1.19.2.1

Any idea what's wrong?

**Comment by cderv** [comment]
From previous issues you mentioned (#1404), it seems that this could be related to your latex installation. 
I do not use mikTex myself (I have gone with great [tinytext](https://yihui.name/tinytex/)).

I don't think this is related to a bug in rmarkdown. You can also find help for such question in https://community.rstudio.com. There is also several issues about that in [SO](https://stackoverflow.com/search?q=tools%3A%3Afile_path_as_absolute)

Have you check you MikTex installation or try to reinstall ? Could it be a solution to use tinytex instead of miktex ?

**Comment by yihui** [comment]
Regarding RStudio's message about the missing LaTeX installation, I just replied another users a few days ago: https://yihui.name/tinytex/#comment-4293434798

> The warning message has been changed in the newer version of RStudio: https://github.com/rstudio/rstudio/pull/3979. You may try the RStudio Preview version at the moment: https://www.rstudio.com/products/rstudio/download/preview/.

**Comment by yihui** [comment]
I just submitted the R package **tinytex** v0.11 to CRAN. Please try

```r
update.packages(ask = FALSE, checkBuilt = TRUE)
```

in a couple of hours to update at least **tinytex**. The new version might reveal more information about the error.

In the meantime, please test the preview version of RStudio as I mentioned above. Thanks!
