### ISSUE TITLE
Find files in hidden directories

### ISSUE THREAD

**Issue by noamross** [rstudio/rmarkdown#1522]
When using the `Cmd/Ctrl + .` shortcut, I cannot find files in hidden directories.  For instance, the in the following test directory structure, I can not get to `.test/anothertest.R` or `.test/test.yml`.

```
.
├── .gitignore
├── .test
│   ├── anothertest.R
│   └── test.yml
├── .test.R
└── tt.Rproj
```

I realize that some hidden directories such as `.git` and `.Rproj.user` contain a lot of files one would want to avoid in the search tree.  However, many projects have useful hidden directories, especially for configuration.  I use `.circleci/` and `.github/` regularly.  Perhaps a short list of hidden directory names could be blacklisted?  And/or search behavior could reflect the state of viewing hidden files in the Files pane?

**Comment by cderv** [comment]
Hi @noamross ,

Am I misunderstanding something or is this rather a rstudio IDE feature request than rmarkdown ? 🤔 

Just asking to make sure you get a reply quickly.

**Comment by noamross** [comment]
Oh, nuts.  Sorry.  I autocompleted my way into the wrong repo!
