### ISSUE TITLE
Feature Request: For Automatic Scientific Notation, can \ensuremath be used?

### ISSUE THREAD

**Issue by billdenney** [rstudio/rmarkdown#1527]
I found myself experiencing issue #160, #301, #385, and #406 yesterday:  I had a number with scientific notation in some inline code where I didn't have an equation marker around it:

```
`r 2e13`
```

and not

```
$`r 2e13`$
```

I love that printing scientific notation looks good in LaTeX output, but I wonder if it could be improved by wrapping it in `\ensuremath` so that those issues do confuse users (i.e. confuse me)?

**Comment by billdenney** [comment]
Thanks for the pointer to tinytex-- there are external limitations that keep me on the system TeX.

Would you consider a PR for adding `\ensuremath{}` to Rmd (which I think would be a pretty small change here: https://github.com/yihui/knitr/blob/0f53929e263afeb0567e4637e9d2977a535d94ec/R/hooks-md.R#L151)?

**Comment by yihui** [comment]
Yes, it appears to be a simple change, but when a package is very widely used, even trivial changes have to be made with care. In this case, it is indeed simple enough to fix the issue for LaTeX output with `\ensuremath{}`, but we have to consider the consequence for other output formats.

Anyway, I have tried to fix it via yihui/knitr@e7e4060. Thanks!

**Comment by billdenney** [comment]
Thank you!
