### ISSUE TITLE
 Win: Render() function not found ...

### ISSUE THREAD

**Issue by Drunkenpanda2000** [rstudio/rmarkdown#1531]
##bug
have a clean install of  **R 3.5.2**
When i execute the render i get the following issue  '\U' used without hex digits in character string starting "'C:\U"

it also does not find the render function.

It is verry verry similar to #1484 and htt
ps://stackoverflow.com/questions/44273571/starting-r-error-u-used-without-hex-digits-in-character-string-starting-c

i however don't have a .Rprofile

**Comment by Drunkenpanda2000** [comment]
Dident send require and backslashes need to be forward slashes wich is verry annoying.

**Comment by jcheng5** [comment]
Glad you were able to figure it out!
