### ISSUE TITLE
working directory changed when filenames contain spaces

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rmarkdown#1533]
Given a simple R Markdown file that writes a CSV to disk:

````
---
title: "filenames with spaces"
output: html_document
---

```{r}
filename <- paste0("mtcars_",Sys.Date(),".csv")
write.csv(mtcars, filename)
```

Here is a link to the file [`r filename`](`r filename`)
````

Write that R Markdown to a file named `with spaces.Rmd`; the whitespace in the filename is important.

Run `rmarkdown::render` with output and intermediates directories:

```r
rmarkdown::render("with spaces.Rmd", output_dir = "output", intermediates_dir = "inter")
```

The `inter` directory contains the R Markdown generated CSV file:

```r
list.files("inter")
# => [1] "mtcars_2019-02-19.csv"
```

The output directory (as expected), contains the rendered HTML:

```r
list.files("output")
# => [1] "with spaces.html"
```

This behavior does not happen if the R Markdown file is named `index.Rmd`. Rendering a file named `index.Rmd` causes the CSV to be written to the working directory (in this case, containing the R Markdown file).

Workaround: Avoid using spaces in R Markdown filenames.
Workaround: Avoid using `intermediates_dir`.

**Comment by aronatkins** [comment]
Modifying Connect to no longer specify `intermediates_dir` to our renders.

**Comment by yihui** [comment]
I'm excited to know that Connect no longer uses `intermediates_dir`. This argument has caused countless issues and I felt it would be super challenging to fix them (so I usually just tell users not to use it instead).
