### ISSUE TITLE
Passing eval=<variable> to chunk not respected when running chunks (only when knitting)

### ISSUE THREAD

**Issue by mlduarte** [rstudio/rmarkdown#1534]
Test code:
````
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
temp <- FALSE
```

## R Markdown
```{r cars, eval= temp}
summary(cars)
```

## Including Plots
```{r pressure, echo=FALSE}
plot(pressure)
```

````

Session Info:

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1, RStudio 1.2.1186

Locale:
  LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
  LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
  LC_TIME=English_Australia.1252    

Package version:
  backports_1.1.2 base64enc_0.1.3 digest_0.6.18   evaluate_0.12  
  glue_1.3.0      graphics_3.5.1  grDevices_3.5.1 highr_0.7      
  htmltools_0.3.6 jsonlite_1.5    knitr_1.20      magrittr_1.5   
  markdown_0.8    methods_3.5.1   mime_0.6        Rcpp_1.0.0     
  rmarkdown_1.10  rprojroot_1.3.2 stats_3.5.1     stringi_1.2.4  
  stringr_1.3.1   tinytex_0.9     tools_3.5.1     utils_3.5.1    
  xfun_0.4        yaml_2.2.0

**Comment by yihui** [comment]
For issues related to the RStudio IDE (like this one), please file them to https://community.rstudio.com or https://github.com/rstudio/rstudio/issues. Thanks! (BTW, I guess it would be hard to fix in the IDE... and you see if you like `xaringan::inf_mr()` as mentioned in https://bookdown.org/yihui/rmarkdown/compile.html)
