### ISSUE TITLE
Under emacs, is it possible to send bash trunks of rmd file to R to execute using ESS

### ISSUE THREAD

**Issue by crotoc** [rstudio/rmarkdown#1536]
Thanks for the great package! I am very happy to use it to organize my work flow! I have a question that under emacs for r code trunks, I can just use ctrl-c ctrl-c to send the codes but is there a way to implement this function for bash trunk? Please give me some hints so that I can implement it if possible. Thanks!

Rui

**Comment by yihui** [comment]
This has to be supported by ESS. There is nothing we could do in **rmarkdown**.

**Comment by crotoc** [comment]
Thanks!
