### ISSUE TITLE
pandoc path: search also if latest version has pandoc-citeproc?

### ISSUE THREAD

**Issue by MatthieuStigler** [rstudio/rmarkdown#1537]
pandoc is complaining about `Could not find executable 'pandoc-citeproc'.`

This is because: I have two pandoc versions on my computer:

* pandoc 1.19.2.4 without pandoc-citeproc (system installation)
* pandoc 1.19.2.1 with pandoc-citeproc (rstudio bin)

I understand that rmarkdown will look for latest version of pandoc. But whenever the user enter a `bibliography` entry in yaml, would it be possible to search for the latest pandoc that also contains pandoc-citeproc? This was mentioned in https://github.com/rstudio/rmarkdown/issues/258 but seems to have been discarded? 

In the meanwhile, is there an easy solution to this? I tried setting it within the markdown document:

    Sys.setenv("RSTUDIO_PANDOC"="/usr/lib/rstudio/bin/pandoc")
    Sys.setenv("pandoc-citeproc"="/usr/lib/rstudio/bin/pando-citeproc")

But rmarkdown will still use latest version that does not have pandoce-citeproc

Thanks!

**Comment by yihui** [comment]
I guess the easier solutions could be one of these:

- Use RStudio (which contains `pandoc` and `pandoc-citeproc`).

- Install `pandoc-citeproc`.

- Symlink RStudio's `pandoc` and `pandoc-citeproc` to a directory in `PATH` (e.g. `/usr/local/bin`).
