### ISSUE TITLE
footnotes don't work in presentations

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#154]
I am not sure if this is a bug or if it's intended, but in a presentation, I can't create a footnote using either footnotes or inline_notes; the id or the bracket and first word are superscripted. Relatedly, the closing ^ for superscripts in a presentation doesn't work. I'd like to be able to footnote in a slide, and consistency between documents and presentations, to the extent possible, would be good.

**Comment by dth0m** [comment]
I'm still seeing this in my rpresentation.  I have updated my packages to the newest versions.
![image](https://cloud.githubusercontent.com/assets/6320945/16415054/40acf210-3d09-11e6-95c0-25efa17f478c.png)
![image](https://cloud.githubusercontent.com/assets/6320945/16415061/4f35cc8a-3d09-11e6-95a2-35ff5710ff61.png)

**Comment by yihui** [comment]
@dth0m Are you using R Presentation (.Rpres) or R Markdown presentation (.Rmd)? They are different things. What JJ mentioned here was the `ioslides_presentation` output format, which is not .Rpres.

**Comment by dth0m** [comment]
I am using .Rpres which may be the issue.
