### ISSUE TITLE
Add ability to append text to figure markdown?

### ISSUE THREAD

**Issue by andrewheiss** [rstudio/rmarkdown#1542]
The pandoc filter [pandoc-crossref](http://lierdakil.github.io/pandoc-crossref/) provides syntax for creating cross references to figures and tables:

```
Lorem ipsum dolor sit amet, consectetur adipisicing elit (see @fig:figure1)

![Caption for figure](/path/to/figure){#fig:figure1}
```

It's possible to use it as a filter when knitting, and it works great:

```
---
title: "Title goes here"
output: 
  html_document: 
    pandoc_args:
      - --filter
      - pandoc-crossref
---

Lorem ipsum dolor sit amet, consectetur adipisicing elit (see @fig:figure1)

![Caption for figure](/path/to/figure){#fig:figure1}
```

However, there's no easy solution to adding the `{#fig:blah}` to figures generated with R.

I've found two solutions so far:

## Use `cat()`

If you add `echo=FALSE, results="asis"` to the chunk options and use `cat()` to add the figure reference, the correct Markdown is generated and knitting works:

````
---
title: "Title goes here"
output: 
  html_document: 
    pandoc_args:
      - --filter
      - pandoc-crossref
---

Lorem ipsum dolor sit amet, consectetur adipisicing elit (see @fig:figure1)

```{r method1, fig.width=4, fig.height=4, fig.cap="Here's a plot", echo=FALSE, results="asis"}
plot(1:10)
cat("{#fig:figure1}")
```
````

One problem with this is that it breaks if you use `echo=TRUE`. Which leads to the second method:

## Use raw markdown

Another option is to use raw markdown syntax to point to the figures that knitr generates:

````
---
title: "Title goes here"
output: 
  html_document: 
    pandoc_args:
      - --filter
      - pandoc-crossref
---

```{r setup, include=FALSE}
# Save figures to a folder named "fig"
knitr::opts_chunk$set(fig.path = "fig/", echo = FALSE)
```

Lorem ipsum dolor sit amet, consectetur adipisicing elit (see @fig:figure2)

```{r method2, fig.width=4, fig.height=4, include=FALSE}
plot(1:10)
```

![Here's a plot](fig/method2-1.png){#fig:figure2}
````

With this method you can use `echo=TRUE, results="hide"` to get the code but suppress the picture. This doesn't work with standalone HTML files, though.

---

Neither of these options are especially intuitive and they feel hacked together.

It might be nice to add an additional chunk option like `fig.suffix`, similar to `fig.lp`, that would append the passed-in text to the generated Markdown.

Something like this perhaps?

````
```{r method-potential, fig.width=4, fig.height=4, fig.cap="Here's a plot", fig.suffix="{#fig:figure-potential}"}
plot(1:10)
```
````

… which would generate:

```
![Here's a plot](path-to-figure/method-potential-1.png){#fig:figure-potential}
```

**Comment by yihui** [comment]
Have you used `bookdown::html_document2`? https://bookdown.org/yihui/bookdown/a-single-document.html Most **bookdown** features are supported there, such as referencing figures: https://bookdown.org/yihui/bookdown/figures.html

**Comment by andrewheiss** [comment]
Ooh, I hadn't seen that—cool! 

I've been sticking with pandoc-crossref since it's used more commonly outside of the **bookdown** ecosystem (like in @kjhealy's [pandoc templates](https://github.com/kjhealy/rmd-starter/blob/master/article-template.Rmd)), and in my just-now tinkering with `bookdown::html_document2` I've found that the pandoc-crossref approach is more extensible.
