### ISSUE TITLE
Shiny R Markdown YAML error

### ISSUE THREAD

**Issue by DanielStay** [rstudio/rmarkdown#1543]
Hello everyone,

I'm currently working on a Shiny app which should also generate a R Markdown. So far everything worked fine but when I try to send new data to params, such as gender, it always throws me the same error. 

See parts of my server code bellow:

```r
output$report <- downloadHandler(
    filename = "Report.html",
    
    content = function(file) {
      tempReport <- file.path(tempdir(), "template_V5.Rmd")
      
      file.copy("template_V5.Rmd", tempReport, overwrite = TRUE)
      
      params <- list(
        bins = input$bins,
        cancer = input$type,
        TL_change = input$TL_change,
        data = d,
        gender = input$gender
      )
      rmarkdown::render(
        tempReport,
        output_file = file,
        params = params,
        envir = new.env(parent = globalenv())
      )
    }
  )
```
This is some of the code from the  R Markdown template:

```r
---
title: "Report"
output: 
  html_document
  
params:
  data: data
  cancer: cancer
  bins: bins
  TL_change: TL_change
  Gender: gender
---
```
Gender is either "male" or "female" and works fine in the Shiny UI and Server function. Even when I try to pass other params such as age or selections of years it always throws me the error:

**Warning: Error in knit_params_get: render params not declared in YAML: gender**

Could anyone help me with this?

Thanks

Daniel

**Comment by cderv** [comment]
in params you have *g*ender with a lowercase `g`
```r
      params <- list(
        bins = input$bins,
        cancer = input$type,
        TL_change = input$TL_change,
        data = d,
        gender = input$gender
      )
```

in your yaml you have *G*ender, with an uppercase `G`
```yaml
params:
  data: data
  cancer: cancer
  bins: bins
  TL_change: TL_change
  Gender: gender
```

So yes, 
`render params not declared in YAML: gender`

You need to respect the case
```r
      params <- list(
        bins = input$bins,
        cancer = input$type,
        TL_change = input$TL_change,
        data = d,
        Gender = input$gender
      )
```

I tested it on a dummy example and it works

## Rmd called test.Rmd

```
---
title: "Report"
output: 
  html_document
  
params:
  data: data
  cancer: cancer
  bins: bins
  TL_change: TL_change
  Gender: gender
---

# test
```

## Rendering with params

use `Gender` not `gender`

```r
params <- list(
    bins = 1,
    cancer = "type1",
    TL_change = "whatever",
    data = iris,
    Gender = "male"
)
rmarkdown::render(
    "test.Rmd",
    params = params,
    envir = new.env(parent = globalenv())
)
```
