### ISSUE TITLE
kable_styling & PowerPoint

### ISSUE THREAD

**Issue by cgoo4** [rstudio/rmarkdown#1545]
Does the PowerPoint option support kable_styling? The reprex below is unstyled, unless I've misstepped.

````
---
title: "ppt kable_styling reprex"
output: 
  powerpoint_presentation:
    df_print: kable
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include=FALSE}
library(tidyverse)
library(kableExtra)
```

## Table

```{r, echo = FALSE}
tribble(
  ~a, ~b,
  1, 2,
  3, 4
) %>% 
  kable() %>%
  kable_styling("striped", position = "left", font_size = 7)
```
````

The code chunk generates a styled table:
<img width="798" alt="screenshot 2019-03-08 at 17 59 16" src="https://user-images.githubusercontent.com/32419319/54046356-f5d42b80-41cb-11e9-802d-99283f0bb90e.png">

But the Powerpoint is unstyled:
<img width="760" alt="screenshot 2019-03-08 at 18 01 11" src="https://user-images.githubusercontent.com/32419319/54046442-392e9a00-41cc-11e9-848b-a8b5a10efa81.png">

R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3, RStudio 1.2.1320

Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8

Package version:
  base64enc_0.1.3   digest_0.6.18     evaluate_0.13     glue_1.3.0        graphics_3.5.2    grDevices_3.5.2  
  highr_0.7         htmltools_0.3.6   jsonlite_1.6      knitr_1.21        magrittr_1.5      markdown_0.9     
  methods_3.5.2     mime_0.6          Rcpp_1.0.0        rmarkdown_1.11.10 stats_3.5.2       stringi_1.3.1    
  stringr_1.4.0     tinytex_0.10      tools_3.5.2       utils_3.5.2       xfun_0.5          yaml_2.2.0       

Pandoc version: 2.3.1

**Comment by yihui** [comment]
This would be better filed to **kableExtra**, but I guess the answer would be no. When the output format is PPT, `kable()` generates Markdown tables, and there is no way to apply the striped style to Markdown tables (only possible for LaTeX and HTML).

That said, this might be possible with a custom PPT template (I'm not totally sure). See https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html
