### ISSUE TITLE
rmarkdown output: github_document and new lines

### ISSUE THREAD

**Issue by kiwiroy** [rstudio/rmarkdown#1546]
A minor issue I've prepared a [gist](https://gist.github.com/kiwiroy/f96bb822ed4df2a6dcaad41b51cfb5a4) to demonstrate.

Either rmarkdown or knitr consumes whitespace at the end of lines. This is generally a *good* thing, except for the case of two spaces at the end of a line when used to insert a `<br />`tag, as per [John Gruber](https://daringfireball.net/projects/markdown/syntax#block)

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

There are such spaces at the end of [this line][spaces], which renders as a newline in [rstudio], but there are no spaces at the end of the line in the generated [markdown].

This issue affects `output: github_document`, but not `output: md_document`.

Rstudio Version: 1.1.463

[spaces]: https://gist.github.com/kiwiroy/f96bb822ed4df2a6dcaad41b51cfb5a4#file-readme-rmd-L6
[rstudio]: https://gist.githubusercontent.com/kiwiroy/f96bb822ed4df2a6dcaad41b51cfb5a4/raw/271514c603dccefaf81a52b2a4559a45836dc1a1/rstudio-viewer.png
[markdown]: https://gist.githubusercontent.com/kiwiroy/f96bb822ed4df2a6dcaad41b51cfb5a4/raw/271514c603dccefaf81a52b2a4559a45836dc1a1/README.md

**Comment by atusy** [comment]
It sounds like a Pandoc's issue.
Anyway, it should be okay under recent environment (Pandoc 2.7.3).
If you are using Windows, try RStudio 1.2.1355 which bundles Pandoc 2.2.1, or RStudio preview version which bundles 2.7.2.
Of course you can update Pandoc itself separately.

I use Pandoc 2.7.3.

**Comment by kiwiroy** [comment]
This is resolved as @atusy describes.
