### ISSUE TITLE
Disable custom margins with document class specified

### ISSUE THREAD

**Issue by adunning** [rstudio/rmarkdown#1549]
If one sets the margins without `geometry`, such as when using KOMA-Script, the custom Rmarkdown setting stops this from taking effect:

```markdown
---
documentclass: scrbook
classoption:
- DIV=12
---
```

At the moment, the margins are set to one inch unless there are custom settings for `geometry` in the YAML front matter:

<https://github.com/rstudio/rmarkdown/blob/cdf4ff0598bbae6c231451bad046e931a84c97aa/R/pdf_document.R#L173>

I would think that the user is very unlikely to want the margins set this way if using a document class other than `article`. Could I suggest that the custom margins be removed if either `geometry` or `documentclass` are set in the front matter?

**Comment by yihui** [comment]
That sounds reasonable to me.
