### ISSUE TITLE
Enable rmarkdown::render() output_file argument to automate file extension

### ISSUE THREAD

**Issue by apreshill** [rstudio/rmarkdown#1551]
I'm using `rmarkdown::render()` to create multiple output formats from a single .Rmd. I would like to change the name of the file *without* needing to specify the file extension. For example, this works:

```r
purrr::walk2(
  .x = c("ioslides_presentation", "slidy_presentation", "powerpoint_presentation"),
  .y = c("html", "html", "pptx"),
  ~ rmarkdown::render(
    "index.Rmd",
    output_file = glue::glue("slide_{.x}.{.y}"),
    output_dir = "gallery-output/test/",
    output_format = .x,
  )
)
```

But I would like to be able to specify the output file name dynamically (`{.x}`) and have the extension (currently `{.y}`) be automatic based on my output format. 

If I don’t specify `output_file` that happens, but I can’t exert control over the output filename. So, in my example, the ioslides presentation file gets overwritten by the slidy presentation.

```r
purrr::walk(
  .x = c("ioslides_presentation", "slidy_presentation", "powerpoint_presentation"),
  ~ rmarkdown::render(
    "index.Rmd",
    output_dir = "gallery-output/test2/",
    output_format = .x,
  )
)
```

Thank you for considering this feature request!
Alison

**Comment by yihui** [comment]
Done. The file extensions will be automatically added.
