### ISSUE TITLE
YAML dates cause an error with PowerPoint templates

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rmarkdown#1555]
If I use set `date:` and `reference_doc:` in my YAML header and then knit to PowerPoint I get an error:

![image](https://user-images.githubusercontent.com/7519295/54720942-18086a80-4b37-11e9-9247-ecf628a47742.png)

This probably occurs because I do not have a date field in my template. But I would expect to get no error, because that's what happens when I don't use a template. When I don't use a template, I don't get an error and I don't get a date field in the rendered output.

**Comment by yihui** [comment]
And your reproducible example is?... (as requested by the issue guide)

Without a reproducible example, my guess is that this is very likely to be a Pandoc issue. If we report to Pandoc, we will still need a reproducible example.
