### ISSUE TITLE
Latex shell-escape options in YAML header don't use

### ISSUE THREAD

**Issue by DarkNoys** [rstudio/rmarkdown#1570]
I'm writing a report on Rmarkdovn but when you try to compile - pandoc_args options ignored when compile pdf.

I find this question:
https://stackoverflow.com/questions/34064292/is-it-possible-to-include-svg-image-in-pdf-document-rendered-by-rmarkdown

But it does not work because *--latex-engine-opt* replaced by *--pdf-engine-opt*. I replaced, but also did not work.

**Compilation command:**
```{bash}
Rscript -e "rmarkdown::render('test.rmd')"
```

**test.rmd**
```{markdown}
---
title: Test
papersize: a4paper
output:
  pdf_document:
    latex_engine: pdflatex
    pandoc_args: [
      --pdf-engine-opt, -shell-escape,
      --pdf-engine-opt, -interaction=nonstopmode]
header-includes:
  - \usepackage{minted}
---
```

**Output:**
```
processing file: test.rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1 (with options)
List of 1
 $ engine: chr "python"


output file: test.knit.md

/usr/bin/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --template /home/renesat/R/x86_64-pc-linux-gnu-library/3.5/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --pdf-engine pdflatex --variable graphics=yes --pdf-engine-opt --shell-escape --pdf-engine-opt -interaction=nonstopmode --variable 'geometry:margin=1in' --variable 'compact-title:yes'
! Package minted Error: You must invoke LaTeX with the -shell-escape flag.

Error: Failed to compile test.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See test.log for more info.
Execution halted
```

I can use knitr -> pandoc -> xelatex, but it would be more convenient to use YAML header.

I asked this [question](https://stackoverflow.com/questions/55459948/latex-shell-escape-options-in-yaml-header-dont-use?noredirect=1#comment97651281_55459948) on the StackOverflow but did not get an answer.

Pandoc version - 2.7.1. RMarkdown and Knitr - latest.

**Comment by yihui** [comment]
I have answered your question on SO. Thanks!
