### ISSUE TITLE
Rmarkdown to pdf error

### ISSUE THREAD

**Issue by YazidKurdi** [rstudio/rmarkdown#1575]
I am unable to format my rmd file to pdf through knit as well as render() function, I have installed MiKTeX and uninstalled it to try to get tinytex to work. I installed the package tinytex and ran it in R through library.

I run install_tinytex() and get this in the console:
TinyTeX installed to C:\Users\yazeed\AppData\Roaming/TinyTeX
Please restart your R session and IDE (if you are using one, such as RStudio or Emacs) and check if tinytex:::is_tinytex() is TRUE.
Warning messages:
1: In download.file(url, output, ..., method = method) :
  cannot open URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile': HTTP status was '404 Not Found'
2: In download.file(url, output, ..., method = method) :
  cannot open URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile': HTTP status was '404 Not Found'
3: In download.file(url, output, ..., method = method) :
  cannot open URL 'https://github.com/yihui/tinytex/raw/master/tools/texlive.profile': HTTP status was '404 Not Found'
4: In file.remove("TinyTeX/install-tl.log") :
  cannot remove file 'TinyTeX/install-tl.log', reason 'No such file or directory'
> 

I restart R and tinytex:::is_tinytex() returns:
FALSE

Sys.which("xelatex") returns:
xelatex 
     ""

**Comment by cderv** [comment]
There was some changes in the files' name, you need to upgrade the 📦 to last CRAN version 0.12
https://github.com/yihui/tinytex/releases

> Renamed tools/texlive.profile to tools/tinytex.profile in this repo. If you are using tinytex::install_tinytex() to install TinyTeX, you have to update the R package to version 0.12 first (it is on CRAN now)

```r
install.packages("tinytex")
```

**Comment by YazidKurdi** [comment]
I did not do anything and I dont know what exactly happened, but its working now.
install.packages("tinytex") workings correctly, and tinytex:::is_tinytex() returns true, I was able to knit to pdf.

**Comment by cderv** [comment]
So this is working now ? 

If so, you can close the issue. If not, tell us what is still the issue.
