### ISSUE TITLE
Feature Info: Paste images in R Markdown files

### ISSUE THREAD

**Issue by Timag** [rstudio/rmarkdown#1580]
See https://github.com/rstudio/rstudio/issues/4038 for the feature request.

I ran into the same issue and gave it a try.

See here:  https://github.com/Timag/imageclipr and a quick technical workthrough: https://stackoverflow.com/questions/55541345/copy-and-paste-an-image-from-clipboard-to-rmarkdown-rmd-code/55541381.

It is still a workaround as it requires Python in the backend, but it saved my a lot of "manual" c&p of images and maybe it also helps some other R developers.
I thought it might be interesting for you as well.

(Not sure if it should be an issue it can be also closed/deleted).

**Comment by yihui** [comment]
Thanks! This would certainly be a nice feature, but probably doesn't belong to the **rmarkdown** package. Fingers crossed for rstudio/rstudio#4038.
