### ISSUE TITLE
Code snippet for rmarkdown ? 

### ISSUE THREAD

**Issue by neonira** [rstudio/rmarkdown#1585]
I just wonder if possible to add a rmarkdown section to supported code snippets languages in Rstudio?

Unable to find any hint about that point, so far. Any suggestion ?

**Comment by yihui** [comment]
There has already been a Markdown section. I don't know why you want an R Markdown section.

![image](https://user-images.githubusercontent.com/163582/58342020-3fb8cf00-7e15-11e9-8365-11b124eb80bb.png)

Anyway, this is an RStudio IDE issue, not directly relevant to the R package **rmarkdown** here.

**Comment by neonira** [comment]
Thanks for clear and  constructive answer. Indeed, markdown section was not
visible on rstudio until I reboot. Might be a glitch. Solved.
