### ISSUE TITLE
Rmarkdown-Knit problem

### ISSUE THREAD

**Issue by Xia1048** [rstudio/rmarkdown#1590]
Repro
On Windows, create an R Markdown file, and try to knit it (for testing). the errors appear: 
"The filename, directory name, or volume label syntax is incorrect"
The problem was reported after updating the Version of R.
Here is the system info:

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1, RStudio 1.2.1335

Locale:
  LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
  LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

Package version:
  base64enc_0.1.3 digest_0.6.17   evaluate_0.11   glue_1.3.0      graphics_3.5.3  grDevices_3.5.3 highr_0.7       htmltools_0.3.6 jsonlite_1.5   
  knitr_1.20      magrittr_1.5    markdown_0.8    methods_3.5.3   mime_0.5        Rcpp_1.0.1      rmarkdown_1.11  stats_3.5.3     stringi_1.1.7  
  stringr_1.3.1   tinytex_0.10    tools_3.5.3     utils_3.5.3     xfun_0.5        yaml_2.2.0     

Pandoc version: 2.6

Many thanks.

**Comment by yihui** [comment]
What is the path of your Rmd file?

**Comment by Xia1048** [comment]
I set the Knit Directory as "Current Working Directory" and set my working directory as my Desktop. 
Also, I try to open my previous Rmd file from the new RMarkdown file in R, the error message is " Access is denied", but it works when I directly open the Rmd file. 
I am not sure if this problem is connected with another one, so I am reporting to you as well. I try to import the excel data through "Import Dataset", the error message is " Is this a valid Excel file? cannot open the connection. " It works when I write the code:  "read_excel("~/Win7/Desktop/A.xlsx")".

**Comment by yihui** [comment]
You didn't answer my question.

> I set the Knit Directory as "Current Working Directory" and set my working directory as my Desktop.
> Also, I try to open my previous Rmd file from the new RMarkdown file in R, the error message is " Access is denied", but it works when I directly open the Rmd file.

In R or in RStudio?

> I am not sure if this problem is connected with another one, so I am reporting to you as well. I try to import the excel data through "Import Dataset", the error message is " Is this a valid Excel file? cannot open the connection. " It works when I write the code: "read_excel("~/Win7/Desktop/A.xlsx")".

This is not relevant to the **rmarkdown** package. Sounds like an RStudio IDE issue.

**Comment by Xia1048** [comment]
> You didn't answer my question.
> 
Sorry, I am not good at RMarkdown and in the process of learning. I am trying to describe the problem as clear as I can. The problem is when creating a NEW RMarkdown file in the R studio, and trying to knit it for testing. When I click "Knit" and save the file at my Desktop, and then the error message appears. 

> > I set the Knit Directory as "Current Working Directory" and set my working directory as my Desktop.
> > Also, I try to open my previous Rmd file from the new RMarkdown file in R, the error message is " Access is denied", but it works when I directly open the Rmd file.
> 
> In R or in RStudio?

it is in RStudio

> > I am not sure if this problem is connected with another one, so I am reporting to you as well. I try to import the excel data through "Import Dataset", the error message is " Is this a valid Excel file? cannot open the connection. " It works when I write the code: "read_excel("~/Win7/Desktop/A.xlsx")".
> 
> This is not relevant to the **rmarkdown** package. Sounds like an RStudio IDE issue.

As for this problem, what I can do?

**Comment by yihui** [comment]
I asked for the full path of your Rmd file, and you didn't tell me. Basically I was wondering if there were any special characters in the path.

For RStudio IDE issues, please use community.rstudio.com or github.com/rstudio/rstudio/issues.

**Comment by Xia1048** [comment]
> I asked for the full path of your Rmd file, and you didn't tell me. Basically I was wondering if there were any special characters in the path.

Sorry to ask this stupid question, but I do not know how to check the full path. I googled, but I did not get the answer. 

> For RStudio IDE issues, please use community.rstudio.com or github.com/rstudio/rstudio/issues.

Thanks, I will do that.

**Comment by adam-sampson** [comment]
You don't know the full directory to your .Rmd file? The knit button in RStudio tries to knit the file in the directory where the Rmd file is located. There are some known problems relating to directory naming so that is why we are asking for the directory you are using.

**Comment by Xia1048** [comment]
Thanks for replying. As I described the problem in the previous message, the Rmd file is supposed to be saved on my computer desktop. Also, I set the Knit Directory as “Current Working Directory” and set the working Directory as my desktop. I assumed this the path that you might want to know. I was kept asking for the path, and I thought I was misunderstood about the “path” you mean. Is it clear?

**Comment by adam-sampson** [comment]
Ok. Are you using a network drive. In some work places they set up your desktop to be saved on the network drive instead of on your computer. If this is a possibility you can find out by opening windows explorer, right clicking on the desktop icon, clicking properties, and looking at the location in the properties dialog box. If your desktop is stored on a network drive this would explain the problem because there is a known error regarding windows network drives. If the location is on your C: drive then it is likely a different problem.

**Comment by Xia1048** [comment]
> Ok. Are you using a network drive. In some work places they set up your desktop to be saved on the network drive instead of on your computer. If this is a possibility you can find out by opening windows explorer, right clicking on the desktop icon, clicking properties, and looking at the location in the properties dialog box. If your desktop is stored on a network drive this would explain the problem because there is a known error regarding windows network drives. If the location is on your C: drive then it is likely a different problem.

Hi Adam, many thanks again for clarifying this question. I really appreciate it. Yes, as you said, I just double checked the path, my desktop is stored on a network drive instead of the Local Disk (C), which I thought was local. So, I just make the issues clear.
1. When I create and new Rmd.file  and try to save it to my desktop (which is stored on a network), it does not work and receives the error message "Error Saving File: The filename, directory name, or volume label syntax is incorrect". This never happens before updating the version of R and Rstudio.
2.   I cannot open my previous Rmd.file through the RStudio: "file"-"open file", which gives me the error message: "Access is denied". But, I can go the file location and double click it to open it in the RStudio. This also happens after updating the version of R.

**Comment by yihui** [comment]
I feel this is an RStudio IDE issue. Please see my reply above: https://github.com/rstudio/rmarkdown/issues/1590#issuecomment-505109740 Thanks!
