### ISSUE TITLE
Floating TOC doesn't work in interactive RMarkdown

### ISSUE THREAD

**Issue by larspijnappel** [rstudio/rmarkdown#1591]
As already reported on [stackoverflow](https://stackoverflow.com/questions/55308088/floating-toc-doesnt-work-in-interactive-rmarkdown) the floating toc is not working anymore. According to Isak Hietala it seems to be related to rmarkdown version 1.2 +. 

Maybe I missed it, but is this a known issue which is expected to be fixed anytime in the future? 

My system details:
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth     
            
> packageVersion('rmarkdown')
[1] ‘1.13’

**Comment by cderv** [comment]
Hi,

Did you try with last dev version ? It should have been fixed in #1587

**Comment by yihui** [comment]
@larspijnappel Please follow the issue guide when filing issues. Had you followed it, you wouldn't need to file this issue, because the issue guide explicitly asked you to test the development version.
