### ISSUE TITLE
Cannot add extra LaTeX content at the end of pdf_document using includes in YAML header

### ISSUE THREAD

**Issue by warkentinmatt** [rstudio/rmarkdown#1599]
Hi,

I am having difficulty adding extra content to the end of a PDF document using the `includes` option in the YAML header. I think the text below should create a minimally reproducible example of the error I'm running into.

Here is the basic setup to show the error (at least on my end).

First I created a `test.Rmd` file with this content:

```
---
output: 
  pdf_document:
    includes:
      after_body: test-add.tex
---

## R Markdown

Here is some text.
```

Then I created a second document, in the same directory as the first, titled `test-add.Rmd`, which includes the following content (I added the backslashes here on GitHub to ignore the Rmd code blocks inside the code block below):
```
---
output: 
  pdf_document:
    keep_tex: yes
---

## Including Plots

You can also embed plots, for example:

\```{r pressure, echo=FALSE}
plot(pressure)
\```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```
 
I knit the `test-add.Rmd` file to produce the `test-add.tex` file; the PDF is produced and everything looks fine. Then I expected when I knit the `test.Rmd` file is would add the content to the end of the document. Here is the error in the `RStudio console`:
```
processing file: test.Rmd
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |.................................................................| 100%
  ordinary text without R code


/usr/local/bin/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --template /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --pdf-engine pdflatex --include-after-body test-add.tex --variable graphics=yes --variable 'geometry:margin=1in' --variable 'compact-title:yes' 
output file: test.knit.md

! LaTeX Error: Can be used only in preamble.

Error: Failed to compile test.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See test.log for more info.
Execution halted
```

Here is the full log file: [test.log](https://github.com/rstudio/rmarkdown/files/3369763/test.log).

For context, I am using `RStudio` version 1.2.1335, `rmarkdown` version 1.12, and `pandoc` version 2.7.2.

**Comment by warkentinmatt** [comment]
As a follow-up, it seems that the issues is with some of the LaTeX stuff (preamble) in the `after_body` document, and it is clashing with the preamble in the main `test.Rmd` document. I edited the `test-add.tex` file and just erased everything up until:

```
\begin{document}

\hypertarget{including-plots}{%
\subsection{Including Plots}\label{including-plots}}

You can also embed plots, for example:

\includegraphics{test-add_files/figure-latex/pressure-1.pdf}

Note that the \texttt{echo\ =\ FALSE} parameter was added to the code
chunk to prevent printing of the R code that generated the plot.


\end{document}
```
And this worked. I was able to add the plot to the end of the other document.

So basically, I only kept the LaTeX for the figure itself, but none of the preamble stuff before it describing the article type, usepackages, etc. Is this an expected conflict? It would be nice to be able to create a TeX file from an `Rmd` file to use directly as the `after_body` file without having to erase preamble manually. But if the LaTeX preamble creates conflicts thats a problem. Is manually erasing the only solution?

**Comment by warkentinmatt** [comment]
Okay, I am returning with a possible solution to creating an `after_body` file without having to manually edit the LaTeX preamble.

Once you have created the `Rmd` file with whatever tables/figures you want to include, you can run the following `R` code:
```
> rmarkdown::pandoc_convert('tables-figures.Rmd', to = 'latex', output = 'tables-figures.tex')
```

This will create a `tex` file with ONLY the table/figure LaTeX code and none of the preamble. You can then feed the `tex` file right into the main (`main.Rmd`) document using the following YAML header:
```
header-includes:
  - \usepackage{setspace}
  - \usepackage{float}
  - \usepackage{graphicx}
output: 
  pdf_document:
    includes:
      after_body: tables-figures.tex
```

Keep in mind, any packages you needed/used in the `tables-figures.Rmd` file need to to be in the YAML header in the `main.Rmd` file.

**Comment by warkentinmatt** [comment]
Returning with yet a better solution, I think...

Simply create the `tables-figures.Rmd` as you want it to produce the desired output. In my case, this is a PDF document with some tables and figures. Then, if you want the tables/figures to appear after the References section in your manuscript, you can just use this code within your `manuscript.Rmd`:
```
### REFERENCES

<div id="refs"></div>

\```{r test-add, child = 'tables-figures.Rmd'}
\```
```

I create a level-three markdown header for references, then add HTML code to specify exactly where you want the references to show up (if you don't include this, the figures will come before the references). Then `knitr` will run `tables-figures.Rmd` and  include the output  where the code chunk is located (in my case, the very last thing in the document).

**Comment by cderv** [comment]
This two solutions are ok ! And the child document is powerful one. 
Seems to me that you got everything covered, don't you ?

**Comment by warkentinmatt** [comment]
Yes, I think I got everything covered after all. I just wanted to make sure I documented my solutions in this thread for others to possibly benefit from. Happy to close the issue now.

**Comment by cderv** [comment]
>  I just wanted to make sure I documented my solutions in this thread for others to possibly benefit from

Thank you for that ! 👍 That was a nice idea !

**Comment by yihui** [comment]
Thank you!

BTW, re:

> I added the backslashes here on GitHub to ignore the Rmd code blocks inside the code block below [...]

> [...] note the backslashes were added by me so that the codechunk shows up properly here on GitHub, do not include these in your actual Rmd...

[The issue guide](https://yihui.name/issue/) has told you how to write verbatim Rmd text if you read it more carefully. More on this: https://yihui.name/en/2018/11/hard-markdown/

**Comment by warkentinmatt** [comment]
@yihui Thanks for the advice. I have edited my comments to reflect this suggestion.

**Comment by yihui** [comment]
@warkentinmatt Perfect! Thank you so much!

**Comment by ZAK41** [comment]
@mattwarkentin - thank you so much for this thread, finally I have my Appendix tables in the right place! Happy Days.

**Comment by mattwarkentin** [comment]
@ZAK41 Glad it was helpful!
