### ISSUE TITLE
[feature request] render_site to print first which file it is working on

### ISSUE THREAD

**Issue by vttrifonov** [rstudio/rmarkdown#1604]
When I hit the build website button the output does not print first which file it is rendering at the moment. This is an example (only the first several lines are included)

==> rmarkdown::render_site(encoding = 'UTF-8')
  |..                                                               |   2%
  ordinary text without R code
  |...                                                              |   5%
etc. 

Only at the end do I see something from the pandoc execution that has the file name in it that tells me what _was_ rendered.

So that when something crashes before pandoc is run (e.g. the example above crashed with execution halted and exited with status 1) it is not clear which Rmd caused the problem and leaves me guessing (e.g. alphabetical order of files?) about what happened.  A simple print at the beginning that says e.g. "rendering XYZ.Rmd" looks like a small change that could be really useful in resolving issues when rendering a site with a bunch of Rmd's in it (which is my case).

**Comment by yihui** [comment]
Sounds like a very reasonable feature request, but I don't have time for it at the moment. If someone can implement it and send a pull request, I can probably review it. Thanks!
