### ISSUE TITLE
Insert, Delete followed by Select SQL operations not showing up

### ISSUE THREAD

**Issue by iembry** [rstudio/rmarkdown#1612]
Hi, I am using `rmarkdown` version 1.14 and R version 3.6.0.

Whenever I use either the delete or insert SQL operations in code blocks, I do not get a result in the `rmarkdown` rendered HTML documents. This is not the case with other SQL commands.

Below are modified examples of the code blocks that I am using:

```SQL
Delete from table where datetime <= '1993-11-13' and X00010_00001_cd = 'A'; Select * from table Limit 6
```

```SQL
Insert into table values('1995-06-06', 7.21, 'e', 0.34, '', 3.775, 'e', 10.03, '', 21.95, 'A', 12.79, 'e', 17.37, 'e'); Select * from table Order By datetime Desc Limit 6;
```

What is the best method to use delete, insert, etc. SQL commands to obtain a result in `rmarkdown` rendered documents?

Thank you.

**Comment by cderv** [comment]
Hi, 

`INSERT` and `UPDATE` are of the type of _update queries_. They are executed using `DBI::dbExecute` and not `DBI::dbGetQuery` or `DBI::dbSendQuery` + `DBI::dbFetch`. 
See the documentation about `?DBI::dbExecute` that does not return value from the database.

knitr is looking for those _update queries_ and do not print any data after the execution of this query 
See [here in knitr](https://github.com/yihui/knitr/blob/544f2559232fbcc6e6029a64514037587be1861d/R/engine.R#L542)
All these verbs are [found](https://github.com/yihui/knitr/blob/544f2559232fbcc6e6029a64514037587be1861d/R/engine.R#L482): `INSERT|UPDATE|DELETE|CREATE|DROP`

I think this is on purpose but we need to dig in history to find why.

What are you expecting to see as a result in Rmarkdown exactly  ?

**Comment by iembry** [comment]
@cderv  Thank you for sending me the knitr documentation on SQL. It was helpful.

I am currently updating this [rmarkdown document](https://www.ecoccs.com/R_Examples/Microsoft-Excel_and_SQL_examples_in_R-1.html) to include SQL code blocks.

Anyways, in the old document, you can see the intended results using `sqldf` in these 2 sections:

7) Delete srs_sc records which have datetime Date <= 1993-11-13

9) Add the following record to the srs_sc table

**Comment by cderv** [comment]
Thank you it is helpful. In both you examples, there is `SELECT *` call just after the `update` or `delete`. I did not see those in your first post - long line issues... 

In both case two command are sent. You can do the same by creating two SQL chunk one after another. Knitr sees a SQL chunk has only one SQL command and determine to use `dbExecute` or `dbFetch` depending on keyword. 

A workaround is to use two chunks. This is the easiest. Modify this behavior would probably require that knitr does that for you by parsing the query to find the `;` and create two queries (and print the result of last one ? or both?). 

Is creating two chunks something that would work for you ?

**Comment by iembry** [comment]
@cderv  Let me see and I'll get back to you. Thank you for the suggestion.

**Comment by iembry** [comment]
@cderv  Yes, your suggestion has worked. Thank you again for your assistance.
