### ISSUE TITLE
Feature request: pass the name of the _output.yml to render

### ISSUE THREAD

**Issue by jm-t** [rstudio/rmarkdown#1613]
It would be convenient to pass the name of the _output.yml file to use as part of the render function. It would allows to easily switch from one output configuration to another.

Something similar to bookdown render that allows to pass the _bookdown.yml file name to use.

**Comment by cderv** [comment]
For reference, this is related to a discussion in [rstudio community](https://community.rstudio.com/t/bookdown-how-to-pass-the-name-of-the-output-yml-to-use-in-render-book/36665/6)

**Comment by yihui** [comment]
That sounds like a reasonable feature request but I don't have time for it. Sorry.

**Comment by atusy** [comment]
I'll do it.

**Comment by jm-t** [comment]
Thank you. I learned a lot by looking at the pull request.
