### ISSUE TITLE
Could users customize the relative width of two-column layout for powerpoint_presentation?

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rmarkdown#1624]
According to [this tutorial](https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html), it seems like users can customize the relative width of two-column layout for `rmarkdown::powerpoint_presentation()` using column class with width attribute provided by Pandoc.

However, it is fixed to 50-50 ratio on my end. I am using the latest Pandoc V2.7.3 and the latest dev rmarkdown.

````````````````````````````
---
title: "Habits"
author: John Doe
date: March 22, 2005
output: powerpoint_presentation
---

:::::: {.columns}
::: {.column width="10%"}
Content of the left column.
:::

::: {.column width="90%"}
Content of the right column.
:::
::::::
````````````````````````````

**Comment by yihui** [comment]
The Pandoc manual says you could specify column widths: https://pandoc.org/MANUAL.html#columns If it doesn't work, it is probably a Pandoc bug. Cc @jkr

**Comment by jkr** [comment]
Unfortunately, that's not relevant to PowerPoint output (and that should be clarified in the manual). Two-column in PowerPoint is done through slide layouts -- two-column is one of the four templates. So you have to change it in the template (they could be vertically oriented, for example). 

PowerPoint simply isn't designed to accomodate on-the-fly layout changes of that sort.
