### ISSUE TITLE
How to omit a certain heading from toc in powerpoint_presentation?

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rmarkdown#1625]
Let's say users do not want to include a certain heading for toc in powerpoint_presentation output. However, `{-}` does not have any effect to achieve this goal.
Do you have any plans to improve this feature?

````
---
title: "Test"
output:
  powerpoint_presentation:
    toc: true
---
# Introduction

Content

# Literature Review {-}

Content

# Conclusion

Content
````

**Comment by cderv** [comment]
The TOC is generated by pandoc and currently, I don't think you can exclude any header. This is not yet implemented in pandoc and still discussed in https://github.com/jgm/pandoc/issues/1762

**Comment by yihui** [comment]
Pandoc 2.8 has implemented it. You need two classes:

```md
# Section {.unlisted .unnumbered}
```
