### ISSUE TITLE
Strikeout in lists

### ISSUE THREAD

**Issue by Maschette** [rstudio/rmarkdown#1627]
Hello, 
I am using strikethrough in a list, it works for the highest level, but not for any sub-points as below:

1.	~~list item one~~
    +  ~~sub-point ~~
2.	~~list item 2~~

**Comment by yihui** [comment]
https://pandoc.org/MANUAL.html#strikeout

**Comment by Maschette** [comment]
Ah so the actual issue is that I'm an idiot. Thanks (and sorry) @yihui!

**Comment by yihui** [comment]
No worries :)
