### ISSUE TITLE
bookdown::word_document2:base_format: rticcles::springer_article 

### ISSUE THREAD

**Issue by gtalckmin** [rstudio/rmarkdown#1635]
Hello Yihui,

Big fan of your work and using it to write my thesis. Something I struggling is to use Rticles to produce a word document (so I can send to my supervisors and journals). 

Would that be possible? If so, how?
I originally thought it would be possible using the YAML section:
output:
bookdown::word_document2:
base_format: rticcles::springer_article 

Error in rmarkdown::word_document(fig_caption = fig_caption, md_extensions = md_extensions,  : 
  unused argument (base_format = "rticles::springer_article")
Calls: <Anonymous> -> create_output_format -> do.call -> <Anonymous>
Execution halted

Cheers

**Comment by yihui** [comment]
To ask questions, please follow the issue guide: https://github.com/rstudio/rmarkdown/issues/new Thanks!
