### ISSUE TITLE
Allow simple linebreaks.

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#164]
I'm using [Parsedown](http://parsedown.org/) to generate non-dynamic HTML from markdown, and knitr/rmarkdown to generate dynamic HTML from rmd.

Parsedown has the Option setBreaksEnabled, where like here on Git
hub you can get a linebreak without ending the line with two spaces.

I always thought this was the only sane way to do it. According to this [spec](https://support.rstudio.com/hc/en-us/articles/200488468-R-Markdown) you also want to support GH-flavoured Markdown, but maybe that's out of date?

**Comment by jjallaire** [comment]
Note that we've now added an `md_extensions` parameter to the output formats which would allow you to disable the line-break behavior on a per-document basis.

**Comment by rubenarslan** [comment]
Yeah, I saw, good stuff :-)
