### ISSUE TITLE
RMarkdown does not produce valid XHTML

### ISSUE THREAD

**Issue by grady** [rstudio/rmarkdown#1640]
The problem discussed in [issue #995](https://github.com/rstudio/rmarkdown/issues/995) is still present. The `xmlns` attribute to the `<html>` tag causes some content-type detectors (Apache Tika) to declare generated html files as application/xhtml+xml. If the file is then served with this content type in the http header, the browser will report a parse error instead of displaying the page, since the file is not valid XHTML. 

In particular, seems that there are characters in the embedded javascript `<script>` blocks that cause the xml parser to fail.

There are two possible ideas for a fix that I came up with:

- Remove the `xmlns` atrribute from the `<html>` tag. The content type detector reports text/html and the page is served and parsed appropriately as ordinary HTML5. This option was rejected in #995.
- Add `<![CDATA[`...`]]>` delimiters around the portions of the document that are not valid XML. E.g.
```
<script>
/*<![CDATA[*/ 
...JQUERY_CODE... 
/*]]>*/
</script>
```
I added these delimiters around the embedded jQuery, bootstrap, Shiv, respond.js, the code labeled ECMA-262, jQuery Sticky Tabs, code folding script, and one other unlabeled javascript. With the CDATA delimiters present, the document successfully parsed as XHTML (in Chrome) and was displayed correctly when served as content-type:application/xhtml+xml

**Comment by RLesur** [comment]
I faced once this problem and I also used the `CDATA` trick. IMO, this is the best choice.

**Comment by Guillawme** [comment]
Not sure whether this is related, but an RMarkdown website served on GitHub Pages gives me a 404 error when pointing the browser to `gh-pages-url/`, while the site displays correctly when pointing the browser to `gh-pages-url/index.html`.

**Comment by Guillawme** [comment]
I just tried to remove the `xmlns` attribute from the `html` tag, and it solved my problem: my GH Pages site now displays ok when I point the browser to the root without specifying `index.html`.

Removing this `xmlns` from the HTML templates seems like it would solve two problems, so would you reconsider this question @yihui ?

**Comment by yihui** [comment]
@Guillawme Please see #995. I do wish to solve your problems, but I do not want to do that at the cost of introducing new problems. Thank you!

**Comment by grady** [comment]
@yihui I'm definitely not an expert on technical details of HTML and XML, but as I was trying to work out what the issue was in my case, I came to the following conclusions:

- The declared <!DOCTYPE html> means we're targeting HTML5.
- HTML5, like other html, can either be or not be valid XML in addition to being HTML
- By declaring the xmlns attribute, you're declaring the document to be XML. Parsers should parse it as XML.
- The documents generated by Rmarkdown are NOT valid XML. XML parsers will fail on them. This is due to non-escaped special characters (specifically ampersands) that are part of the self-contained inline javascript.
-  Declaring the xmlns attribute is __optional__. If you don't declare it, you're just saying the file is regular non-xml HTML. 
- The file IS valid HTML.
- Other Rmarkdown html formats (like ioslides, etc.) do not declare this attribute.

It doesn't make sense to claim the document is valid XML, and then not produce valid XML.

Why is it important to pay attention to the validator warning about xmlns in the case of  html_document output but not ioslide_presentation?

**Comment by Guillawme** [comment]
@yihui I did read #995, and I think the reason you gave back then for not changing the template is not valid anymore.

I just ran the [current default template](https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/h/default.html) through the validator (with automatic detection of document type and character encoding), and it did not give the error you showed in #995. I got the same validation report either with or without the `xmlns` attribute. All this suggests that one shouldn't rely on this validator to decide whether or not to update a template. Relying on the actual results (will the site display correctly with a given template?) seems like a better approach.

**Comment by grady** [comment]
I'd just like to reiterate that there is a concrete and realistic case where this issue causes a showstopping error:
- Uploading a rmarkdown html_document to a website that does content-type introspection (not based on file extension). The algorithm will probably believe your `xmlns` claim to be a valid XML document.
- The website serves your file with content-type:html+xml as a result of the introspection.
- User's browser attempts to parse the file as XML. Parser error message is displayed, not the document. 

This is a realistic problem, for example, the Sakai LMS works this way. I ran into the problem because I was trying to host course documents through my institution's Sakai installation, but everyone was just seeing errors when they tried to view them.

I'm not sure if this sort of misidentification is also underlying @Guillawme problem or not, but it's a definite possibility.

**Comment by RLesur** [comment]
Since this problem appears with JS code in `script` tags, another option could be to turn the JS scripts into HTML dependencies as mentioned in https://github.com/rstudio/rmarkdown/pull/1405#pullrequestreview-137663612.

**Comment by Guillawme** [comment]
When building a website (not only a single, self-contained html_document), all the non-HTML material (CSS, JS, etc.) is already stored separately in a site-libs directory at the root of the generated website.

**Comment by RLesur** [comment]
> all the non-HTML material (CSS, JS, etc.) is already stored separately

except CSS stylesheets and JS scripts embedded in the HTML template (I mentioned the use of HTML dependencies as an alternative to the use `CDATA` delimiters).

**Comment by grady** [comment]
One possible alternative fix, and one that would produce valid XML, would be to add
```
/*<![CDATA[*/ 
...
/*]]>*/
```
at the top/bottom of all the javascript files in the Rstudio installation.

**Comment by grady** [comment]
I have a suspicion that this may also be a pandoc issue? I think Rmarkdown calls pandoc with some sort of a self-contained flag, and that causes pandoc to turn any references to external resources into either `data:` urls or by inlining code. 

It would seem that pandoc should  be guarding javascripts that it inlines? I even found a long-ago patch note there that seemed to imply that it will insert CDATA guards. However, this doesn't appear to be happening.

**Comment by yihui** [comment]
I just removed the `xmlns` attribute. Thanks for all your analysis and explanations! Please let me know it fixes the problem for you:

```r
remotes::install_github('rstudio/rmarkdown')
```
