### ISSUE TITLE
Marking the chunk with error when an R Notebook is run using "Run All"

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rmarkdown#1643]
When running a long R Notebook with numerous chunks using the "Run All" option, if an error occurs, it is not straightforward to determine which exact chunk caused the error. To this end, one needs to either check the console and perhaps search for a few phrases in the line in which the error occurred, or scroll the document all the way from top to bottom to identify the error text in the red font.

To help facilitate the above process, it would be helpful if a marker will be shown in one or both of the following places:

* In the **Jump to Chunk/Function** section at the bottom of the window where a list of all chunks is presented upon a click.
* In the **Document Outline** if any section/subsections was created by the user.

PS. Currently a green marker is displayed next to the section where the mouse pointer is located at in the Document Outline. The marker requested above can be very similar to this marker just with a different color.

**Comment by cderv** [comment]
Hi @hzarkoob 

I think this is a great idea ! 
It seems to me it is more a RStudio IDE feature to better integrate rmarkdown users' experience. I think you should open a feature request in https://github.com/rstudio/rstudio and link to this issue too.

**Comment by hzarkoob** [comment]
Hi @cderv, Thank you for your suggestion. I just did!
