### ISSUE TITLE
pandoc_citeproc_convert does not work on windows

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1651]
I think this issue is the cause of https://github.com/rstudio/distill/issues/103

``` r
rmarkdown::pandoc_citeproc_convert("biblio.bib")
#> Error in system(command, intern = TRUE): 'pandoc-citeproc' not found
```

I think this is because `pandoc_citeproc` does not handle windows binaries
https://github.com/rstudio/rmarkdown/blob/73d055257ecb32b92d703ede9c1b55615bcb0629/R/pandoc.R#L666-L674

`citeproc_path` will not exist on windows because of a missing `.exe` at the end. 

This issue is currently only affecting `distill` i think because this package use directly `pandoc_citeproc_convert` and `rmardown` only pass pandoc-citeproc path to pandoc itself, and it is working without the exe.

One fix is to handle windows binary by adding `.exe` to the path.

**Comment by yihui** [comment]
I think you are right. Would you submit a PR? Thanks a lot!

**Comment by cderv** [comment]
Yes I will do that. 👍
