### ISSUE TITLE
invalid destination host

### ISSUE THREAD

**Issue by apoosakkannu** [rstudio/rmarkdown#1656]
Hi, I am getting following error while i tried to knit a rmd file. could you please help me to overcome this problem. I am using windows desktop and latest Rstudio. 

output file: trubida_26092019.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS trubida_26092019.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output trubida_26092019.html --email-obfuscation none --self-contained --standalone --section-divs --template "\\serverFPR\Redir\FPR\apoosakkannu\My Documents\R\win-library\3.6\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Users\APOOSA~1\AppData\Local\Temp\RtmpCu2PbD\rmarkdown-str8342d274ca5.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
Could not fetch http://?/UNC/serverFPR/Redir/FPR/apoosakkannu/My%20Documents/R/win-library/3.6/rmarkdown/rmd/h/default.html
HttpExceptionRequest Request {
  host                 = ""
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/"
  queryString          = "?/UNC/serverFPR/Redir/FPR/apoosakkannu/My%20Documents/R/win-library/3.6/rmarkdown/rmd/h/default.html"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InvalidDestinationHost "")
Error: pandoc document conversion failed with error 61
Execution halted

**Comment by apoosakkannu** [comment]
Hi, I am new to rmarkdown, could you give me the reason for the above problem. I am not sure why it has been closed.

**Comment by yihui** [comment]
Please read and follow [the issue guide](new) exactly to provide all the required information. Please do not ignore the issue guide. Thanks!
