### ISSUE TITLE
Setting image width prevents inlining in ioslides

### ISSUE THREAD

**Issue by hadley** [rstudio/rmarkdown#1687]
Take this simple Rmd doc and sample image:

```
---
output: ioslides_presentation
---

![](sample.png)

![](sample.png){width=80%}
```

<img width="176" alt="sample" src="https://user-images.githubusercontent.com/4196/68252311-d0155580-ffea-11e9-8dde-dc18a51a00a6.png">

If you knit this document, the first image is embedded (correct), and the second is not (incorrect).

**Comment by atusy** [comment]
Both are embedded if I prepare an image with a following code, and then knit the Rmd doc.

```r
# Prepare image
ggplot2::ggsave("sample.png", ggplot2::qplot(1, 1), width = 1, height = 1)
```
![image](https://user-images.githubusercontent.com/30277794/68282787-a2e5a780-00bd-11ea-911d-2f928a351928.png)

**Comment by tareefk** [comment]
The hope is that you can embed static images (example: screen shots)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
