### ISSUE TITLE
Enhancement request: provide a setting to create an html fragment

### ISSUE THREAD

**Issue by akniss** [rstudio/rmarkdown#171]
There are certain scenarios when it is desirable to create an html fragment. This is simply done within RStudio by going to the console and typing `knit2html("file.Rmd", fragment.only=TRUE`. However, it would be nice to set this as an option in the "Edit the R Markdown format options" settings. When doing revisions, it is sometimes simply easier to click the "Knit HTML" button rather than go to the console. Adding a "create html fragment" check box in the advanced options would be very helpful for me (and presumably others) when working on documents where the fragment is desired. 
![rstudiooptions](https://cloud.githubusercontent.com/assets/8174285/3592697/e8daf6e2-0c75-11e4-8534-b08166295229.png)

**Comment by jjallaire** [comment]
This is now handled via the `html_fragment` format.
