### ISSUE TITLE
Failed to run Julia codes in a R Markdown code chunk

### ISSUE THREAD

**Issue by waynelapierre** [rstudio/rmarkdown#1712]
I am using R Markdown to write a tutorial for Julia users. 
I embedded Julia code like this:

```{julia}
using LibPQ, Tables, DataFrames
```
but got the error message:
Errors happen in Julia. Syntax: "$" expression outside quote stacktrace.

**Comment by cderv** [comment]
It seems you deleted the issue template included when you opened the issue. This template asked for a reproducible example. I will help a lot to see how to reproduce your error. 

Know that, [rmarkdown only get Julia support](https://bookdown.org/yihui/rmarkdown/language-engines.html#julia) through knitr that build on top of `JuliaCall` knitr engine `JuliaCall::eng_juliacall`. 
If there is an issue, it could also be there and not in Rmarkdown.

Thank you !
