### ISSUE TITLE
1.19 update and fix #1716 breaks the compact title when only title and date fields are present

### ISSUE THREAD

**Issue by chrisothal** [rstudio/rmarkdown#1719]
It seems the most recent update to 1.19 removed the custom latex template and uses pandoc's default template. [Fix #1716](https://github.com/rstudio/rmarkdown/commit/cf8e5df1b309edc9d75e610f9c52c451588c302b) was proposed to keep a compact title by including `compact-title.tex` in the `includes` argument of `pdf_document()` (essentially `render("test.Rmd", output_format = pdf_document(includes = includes(in_header = "compact-title.tex")))`). However, if I have title and date fields but no author field, the rendered PDF document contains a blank line between the title and date. I'm not sure if this is a pandoc, latex, or rmarkdown change, as I receive a "no \author given" warning. Rmarkdown before used to render simply the title and date with no whitespace in between and wouldn't throw any issue with a missing \author.

test.Rmd
```
---
title: "test"
output: pdf_document
date: "12/3/2019"
---
This is a test document
```

**Comment by chrisothal** [comment]
After comparing template `default-1.17.0.2.tex`, it seems the `compact-title:yes` variable was used within the template to remove the line where the author field would be and assign a blank author.

**default-1.17.0.2.tex:**
```
$if(author)$
  \author{$for(author)$$author$$sep$ \\ $endfor$}
  $if(compact-title)$
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  $endif$
$else$
  \author{}
  $if(compact-title)$
  \preauthor{}\postauthor{}
  $endif$
$endif$
```

**Comment by yihui** [comment]
For the warning "no \author given", I just submitted a PR to Pandoc to fix it: https://github.com/jgm/pandoc/pull/5961

For the blank space when no author is given, I'll see how to remove it. Thanks for the report!

**Comment by yihui** [comment]
Could you install the development version and see if you are happy with the spacing now? Thank you!

```r
remotes::install_github('rstudio/rmarkdown')
```
