### ISSUE TITLE
Deals with empty header-includes that now errors.

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1728]
This follows a question on community
https://community.rstudio.com/t/enc2utf8-issue-with-render-book-from-bookdown/46701/2

here is a reprex with las rmarkdown dev version
````
---
title: "test"
output: pdf_document
header-includes:
  -
---

```{r pressure, echo=FALSE, fig.align = 'center'}
plot(pressure)
stars(cbind(1:16, 10 * (16:1)), draw.segments = TRUE)
```
````

This will error to 
```
Error in enc2utf8(text) : argument is not a character vector
Calls: <Anonymous> ... includes_to_pandoc_args -> includes -> as_tmpfile -> write_utf8 -> writeLines
Exécution arrêtée
```
because header-includes is empty but still pass to be written to the file, following the new way to include hearder with pandoc. 

Let's note that with rmarkdown 1.17 there is no error and the file build ok to pdf. So this is a regression that I think should be deal with. 

I'll work on a PR as soon as I can.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
