### ISSUE TITLE
Can´t compile example document

### ISSUE THREAD

**Issue by tobi2185** [rstudio/rmarkdown#173]
I just recently installed the new RStudio. I can´t compile the example document to PDF from Rmarkdown document:

pandoc: Error producing PDF from TeX source.
! LaTeX Error: There's no line here to end.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.113 \end{enumerate}} \

Fehler: pandoc document conversion failed with error 43
Ausführung angehalten

My sessionInfo()

essionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-apple-darwin13.1.0 (64-bit)

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.4     htmltools_0.2.4  rmarkdown_0.2.50 tools_3.1.0      yaml_2.1.13    

Any help is greatly appreciated since I´m using Rmarkdown and knitr so very often :-)

**Comment by galadude** [comment]
This is also a problem on danish computers since the data is stored with the format "19. feb. 2015".

**Comment by yihui** [comment]
@galadude Please see my reply above.

**Comment by tobi2185** [comment]
The error is back again! @yihui, can you check that please? 
Workaround: Just remove the dot in the date.
Thx, tobi

**Comment by yihui** [comment]
@tobi2185 Again, please see my reply above: https://github.com/rstudio/rmarkdown/issues/173#issuecomment-52839287

**Comment by Deleetdk** [comment]
I had the same issue. Removing the dot worked for me too. I also tried escaping the dot with `\` or `\\`. Neither worked.

Versions:

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

rmarkdown_1.6
knitr_1.17

emil-office etc # pdflatex --version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.41.0
```

**Comment by yihui** [comment]
@Deleetdk 
Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)? I don't see any issues with `\\.`. Here is my example:

```markdown
---
title: "Untitled"
author: "Tobias Ludwig"
date: "18\\. Juli 2014"
output: pdf_document
---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:
```
