### ISSUE TITLE
ioslides feature suggestion: hierarchical levels indented in Rstudio document outline

### ISSUE THREAD

**Issue by jzadra** [rstudio/rmarkdown#1734]
With Rmarkdown html documents, the Rstudio document outline indents the label based on the number of hash marks for that label (ie sections):

![image](https://user-images.githubusercontent.com/25590353/70660161-c18c1080-1c1e-11ea-8330-ee39da787102.png)

It is a very useful features and helps a lot with using the outline to navigate around large documents.

With Rmarkdown ioslides documents, this doesn't happen:

![image](https://user-images.githubusercontent.com/25590353/70660174-ce106900-1c1e-11ea-99e4-c49c3a7fa219.png)

**Comment by yihui** [comment]
This is an RStudio IDE issue. Would you please file it to https://community.rstudio.com or https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by jzadra** [comment]
Done!
