### ISSUE TITLE
Grab title for vignettes from "vignette" header

### ISSUE THREAD

**Issue by krlmlr** [rstudio/rmarkdown#1765]
One of my vignettes has this in the header:

```
---
title: "Column data types"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Column data types}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

Ideally, I'd like to write

```
---
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Column data types}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

and have the `title` inferred from the contents of `\VignetteIndexEntry` in the `vignette:`. This would remove redundancy and reduce error potential that arises from mismatching titles and index entries. The `title` still could be overridden.

Would you support this behavior?

**Comment by atusy** [comment]
I'd prefer the title field because it catches my eyes.
What about to change the template and change the `VignetteIndexEntry` according to the title?

```yaml
---
title: "test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{`r rmarkdown::yaml_front_matter(knitr::current_input())$title`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

**Comment by krlmlr** [comment]
Does this really work? Somehow I recall that the file contents are searched verbatim for `\VignetteIndexEntry{}`.

**Comment by atusy** [comment]
Sorry it is not working...
I made an example package https://github.com/atusy/grabVignetteTitle/tree/master/vignettes, and its vignette Index become something like

```
Vignettes in package ‘grabVignetteTitle’:

hello                  `r
                       rmarkdown::yaml_front_matter(knitr::current_input())$title`
                       (source, html)
```

**Comment by krlmlr** [comment]
This brings us back to the original issue. (Perhaps the vignette's title is collected by parsing the test for `\VignetteIndexEntry{}`.)

@yihui: What's a good way to sync `\VignetteIndexEntry{}` and the vignette's title?

**Comment by krlmlr** [comment]
Asking because this just happened to me:

![Screenshot from 2020-03-31 08-52-39](https://user-images.githubusercontent.com/1741643/77995987-128a5680-732d-11ea-966b-89d010236a58.png)

**Comment by cderv** [comment]
I think that would be possible using a `pre_processor` in `html_vignette` that would parse the IndexEntry if no title is provided in the yaml front matter. I tested this idea and it is working fine when rendering a vignette with `rmarkdown::render` for now. It requires further testing though. 

I'll PR something very soon. I wanted to let you know I am on this.

**Comment by cderv** [comment]
@krlmlr can you test the PR ? 
Providing only `vignetteIndexEntry` is enough to set the tile is none is provided. If one if provided it will use the title in the yaml header. 
Does it seems ok to you ? I let you comment in the PR if you have any comment.
