### ISSUE TITLE
Portability: image paths are case sensitive on Linux but not on Mac

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rmarkdown#179]
Given a document containing an image reference:

`![foo](Foo.png)`

and an accompanying image `foo.png`, the image will be successfully rendered under OS X, but not on Linux.

**Comment by yihui** [comment]
This issue is not specific to rmarkdown but arises from the OS level. I guess the two possible solutions are (1) a file path linter (2) education. It seems even if we go with (1), users may still be bitten by this issue in other places. They probably have to learn it the hard way...
