### ISSUE TITLE
Linux: rmarkdown::run doesn't work on ioslides presentations unless runtime = shiny is present

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rmarkdown#180]
Attempting to use `rmarkdown::run` on a trivial `ioslides_presentation` works OK on Mac, but gives this on Linux:

      pandoc: ioslides_presentation.lua: openFile: does not exist (No such file or directory)
      Error : pandoc document conversion failed with error 1

Adding `runtime = shiny` to the presentation's YAML fixes the problem (but shouldn't be necessary).

**Comment by englianhu** [comment]
I faced same issue just now, tried to create Shiny oislides without modisy anything, but the interactive graph doesn't display inside the ioslides.

```
> devtools::session_info()$platform
Session info ----------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.849)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2016-01-15
```
