### ISSUE TITLE
Disconnect CSS doesn't cover ioslides

### ISSUE THREAD

**Issue by trestletech** [rstudio/rmarkdown#181]
As discussed [here](https://github.com/rstudio/shiny-server-pro/issues/239) the disconnect CSS from Shiny doesn't appear very clearly in the ioslides setup. 

Could we add a property that taps into the `body.disconnect` state to more clearly identify when a presentation has been disconnected?

**Comment by yihui** [comment]
This issue might have gone. This is what I see now:

![image](https://user-images.githubusercontent.com/163582/29900682-f9a8ec46-8db8-11e7-9f51-52a77dab05a6.png)

Disconnected:

![image](https://user-images.githubusercontent.com/163582/29900689-019a5516-8db9-11e7-9f5b-e74dad79df69.png)
