### ISSUE TITLE
Creating Student version assignment from Solutions RMD file 

### ISSUE THREAD

**Issue by sukhjitsehra** [rstudio/rmarkdown#1813]
I searched through all to find the solution to create a student version assignment from "solutions assignment" RMD file.

If Pandoc or any other script can remove the certain r scrip cells and create the student version. What would be method for it?

Thanks

**Comment by tallguyjenks** [comment]
you could use parameterized rmarkdown documents to toggle a variable value in the R code chunks to set the `echo` option on the answer chunks to false

**Comment by tallguyjenks** [comment]
[Rstudio Parameterized Rmarkdown](https://rmarkdown.rstudio.com/developer_parameterized_reports.html%23parameter_types%2F)
[Bookdown section 2.1.2](https://bookdown.org/yihui/rmarkdown/basics-examples.html)

**Comment by sukhjitsehra** [comment]
@tallguyjenks Can you give me more insight or a working example to get started.  I was thinking to put some special attributes in the code chunk and the script removes all those code chunks and prepares a student version of the file.

**Comment by remlapmot** [comment]
I use the `include` code chunk option. You can set this on a per chunk basis and for the whole document with `knitr::opts_chunk$set(include = )`.

Here is an example example `.Rmd` file

````
---
title: "Example exercise"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE) # change to TRUE when rendering solutions
```

1. This is question 1. Which might have some R code you always want to show.
    ```{r, include=TRUE}
    x <- 1
    ```
    
    ```{asis}
    Paragraph text for the solution can be kept in the document in an `asis` chunk. 
    And solution R code in an `r` chunk. 
    Both of these will use the `include` value from the `setup` chunk.
    ```
    
    ```{r}
    x <- 2
    ```

````

Manually change the output filename for the knits with the different setup chunk `include` values.

I also did slightly more complex example [here](https://github.com/remlapmot/rmd-questions-and-answers/blob/7f662dc75cee037f0d91fa727eec8cf0e103f7b7/rmd-questions-and-answers.Rmd.)

**Comment by sukhjitsehra** [comment]
@remlapmot, 

Thanks, but I want to create another RMD file so that it can be shared with the students. Please suggest. The link for complex example did not open can you assist here. I

**Comment by sukhjitsehra** [comment]
Yes, that is the second idea is close, but it removes the code chunk "{ }". From that file copy paste and then correct the code chunk is required.

**Comment by yihui** [comment]
This type of question/discussion is more appropriate for RStudio Community. This issue tracker is mainly for bug reports and feature requests, instead of how-to's or applications. Thanks!

Anyway, within an Rmd document, you can use an arbitrary variable to control chunk options like `echo` or `include`. More at: https://bookdown.org/yihui/rmarkdown-cookbook/chunk-variable.html

````
```{r, include=FALSE}
FULL_VERSION = TRUE  # change to TRUE for the full version
```

## Homework Problem

Description.

```{r, include=FULL_VERSION}
# this is the solution that students shouldn't see at the moment
x <- 1:10
```

```{asis, echo=FULL_VERSION}
Do you want to show some tips to help students work on the assignment?...
```
````

**Comment by sukhjitsehra** [comment]
Thanks
