### ISSUE TITLE
Rmd-to-html codeblock highlight delivers unpleasant information for screen readers

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/rmarkdown#1828]
When code highlight is applied for `rmarkdown::html_document` output, screen-reader users experience unneccessary difficulties in reading code blocks.

I am not going to duplicate the issue here so please kindly visit [pandoc/issue#6352](https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) that I have detailed there.

Fortunately, the fix will be implemented in the next `pandoc` version; however, I wanted to create backword solution towards previous versions <= v2.9.2.1.

To this end, I have attempted to write a simple `lua` filter, but that does not seem to be possible unless we consider postprocessing an html output.

Many blind people, including me, have already experienced this challenge caused by redundant codeblock ID information, and I think we need to come up with some universal solutions for Rmd-to-html output process given that many tutorials and online books have been produced by rmarkdown/pandoc under the hood.

Does anyone have a great solution?

**Comment by jooyoungseo** [comment]
I think I have figured out how to address this issue globally using js and `rmarkdown:::html_dependencies()`. I will make a PR soon.

**Comment by jooyoungseo** [comment]
The following code would resolve this issue when embedded in html output:

``` js
/* Hide empty <a> tag within CodeBlock for screen reader accessibility (see https://github.com/jgm/pandoc/issues/6352#issuecomment-626106786) --> */

const codeList = document.getElementsByClassName("sourceCode");

for(var i in codeList) {
  var linkList = codeList[i].getElementsByTagName('a');
  for(var j in linkList) {
    if(linkList[j].innerHTML === "") {
      linkList[j].setAttribute('aria-hidden', 'true');
    }
  }
}
```

@yihui, where would be the best place for me to put the `js` I have  written for this fix? I added a new function (referencing `rmd/h/accessibility/this.js>,                                                                                                         `) to `htmlDependency.R`, and called the function within `html_document` by appending it to the `extra_dependencies` list on top of `html_dependency_jquery`, `html_dependency_jqueryui`, etc. But, that does not call my js when rendered. Should I directly modify `default.html`? But, wouldn't it be a global fix for people using different html themes?

**Comment by atusy** [comment]
@jooyoungseo Would you share your branch of your forked repository so that we can help you?

**Comment by jooyoungseo** [comment]
Thanks very much @atusy! I have made a PR as a draft via [#1828](https://github.com/rstudio/rmarkdown/pull/1833)

**Comment by atusy** [comment]
I opened a PR to patch your branch.
By the way, does the issue only matters with pandoc 2.9.2.1?

**Comment by jooyoungseo** [comment]
Thanks very much @atusy! But, I don't see your PR there.

I don't quite remember since when `pandoc` has put this empty anchor for highlighted code.

It may be after 2.7.x. However, I need to double check.

At this moment, I think `<= v2.9.2.1` would be safer solution.

**Comment by atusy** [comment]
My PR is here: https://github.com/jooyoungseo/rmarkdown/pull/1

> It may be after 2.7.x. However, I need to double check.

Yes, please. I think this is important because the latest RStudio bundles Pandoc 2.7.2.

**Comment by jooyoungseo** [comment]
Thanks for your patch @atusy; however, it has the same issue as mine. The rendered html output does not include the js file.

**Comment by jooyoungseo** [comment]
Okay, I have tested each pandoc version one by one, and have identified the issue has been introduced after v2.7.3, so the following is the best condition:

`pandoc_version()` >= '2.7.3' && `pandoc_version()` <= '2.9.2.1'

I will add this condition to the source code; however, we still need to figure out why the js is not included for html output.

**Comment by atusy** [comment]
Please try highlight other than default. If you need JS even if default, please let the following statement be independent `if` instead of `else if`. Before my patch your JS was not included properly because it required `toc = TRUE`.
https://github.com/rstudio/rmarkdown/pull/1833/files#diff-d244a3f1d96cb8bba005d659d4cdc69dR284

**Comment by jooyoungseo** [comment]
The result that I was referring to came from `"tango"` highlight. FYI, "default" value of highlight argument does not insert an empty anchor tag, so we do not need additional condition.

**Comment by atusy** [comment]
ok now I see the problem.
Your JS is incorporated, but not working.

You need to wrap your code with following so that your script runs after the document is ready.

```js
$(document).ready(function(){

}
```

**Comment by atusy** [comment]
Also I suggest the script be placed under `rmd/h/pandoc`, so that we can rename the script to the short one such as `accessibleCodeBlock.js`

**Comment by atusy** [comment]
A better alternative wrapper without jQuery.
```
document.addEventListener('DOMContentLoaded', function() {
// your code
}
```

**Comment by jooyoungseo** [comment]
I have just confirmed that everything works! Thanks very much @yihui for your wonderful final touch! I have learned a lot from your insightful changes. :)
