### ISSUE TITLE
ioslides size fixed at 1024x768?

### ISSUE THREAD

**Issue by sje30** [rstudio/rmarkdown#185]
Hello,
Are the ioslides fixed at 1024x768?  On my laptop I see a lot of whitespace around the edges of the slides.  (Hitting "w" does get my widescreen, but still there is a large border around the slides.)  When I use the presentation mode trick, the only way I could get the slides to display correctly on the external data projector was to select 1024x768 (e.g. 800x600 was too small, with most of the slides chopped off).

**Comment by ryanatanner** [comment]
If I want to change the size from 1024x768 to say...1920x1080, where do I start? Is there CSS for the ioslides, is there an HTML template to edit? R functions to investigate? Just looking for the beginning of the breadcrumb trail. Thanks!

**Comment by sje30** [comment]
Hi, this thread is a few years old now.  If using Rmd for your slides, I'd recommend you use the xaringan package:  https://bookdown.org/yihui/rmarkdown/xaringan.html
