### ISSUE TITLE
Question: how to define the scope of inline chunks

### ISSUE THREAD

**Issue by courtiol** [rstudio/rmarkdown#1853]
Dear @yihui and colleagues, this is a rather technical question (see link to RStudio community at the end)

Within a package I am working on, I am creating optional vignettes that the user can build on demand.

I would like the building of such vignettes happens in an environment that does not have the global one as parent.
So, my custom vignette building function includes something like:

```r
vignette_env <- new.env(parent = baseenv())
rmarkdown::render(path.to.file, envir = vignette_env)
```

The problem, when I do that, is that the package loaded and the objects created inside knitr chunks are not visible (in scope) to inline calls that follow, although they are visible to other chunks.

I don't understand why and how to cope with this scoping issue.

I have posted a question on RStudio community **with a full reprex**  (https://community.rstudio.com/t/scoping-environment-struggle-in-r-markdown/70709), but failed to attract any attention in more than a week.

**Comment by atusy** [comment]
As far as I tried, I faced error with a normal chunk.

I'd recommend `render`ing within `callr::r`.
An easy way is to use `reprex::reprex_render`, but it is not yet available on CRAN.

I guess this is the cause.
Even if you use `new.env(parent = baseenv())`, `search()` does not change.
Also, `library` attaches the package to the 2nd position of `search()`.
As a result, imported package is located between `.GlobalEnv` and `stats`.
In the example below, `library(MASS)` adds `"package:MASS"` between them.
This location is not accessible from the environment you defined.

````
# rmarkdown::render('~/R/example.Rmd', envir = new.env(baseenv()))
library(MASS)
environment()
## <environment: R_GlobalEnv>
parent.env(environment())
## <environment: package:MASS>
## attr(,"name")
## [1] "package:MASS"
## attr(,"path")
## [1] "/usr/local/lib/R/library/MASS"
search()
##  [1] ".GlobalEnv"        "package:MASS"      "package:stats"    
##  [4] "package:graphics"  "package:grDevices" "package:utils"    
##  [7] "package:datasets"  "package:methods"   "Autoloads"        
## [10] "package:base"
````

**Comment by courtiol** [comment]
Thanks @atusy but I don't get you: I am fine with packages attaching envir at the second position and I don't see how this explains why chunks and inline work using different scopes. Would not that be simply a bug?

**Comment by cderv** [comment]
@atusy FWIW we are discussing this in the community website if you want to join and share ideas 
https://community.rstudio.com/t/scoping-environment-struggle-in-r-markdown/70709

**Comment by courtiol** [comment]
The scoping issue does not seem to be reproduced by others, and manipulating environment can easily be avoided by using `callr::r()`. See previous link to community rstudio for more info.
