### ISSUE TITLE
Rmarkdown

### ISSUE THREAD

**Issue by Twi-87** [rstudio/rmarkdown#1857]
I am trying to use rmarkdown but while installing the package I am facing the below error:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'xfun' 0.13 is being loaded, but >= 0.15 is required
ERROR: lazy loading failed for package 'knitr'
* removing 'C:/Users/tgoyal007/Documents/R/R-3.5.1/library/knitr'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘knitr’ had non-zero exit status
ERROR: dependency 'knitr' is not available for package 'rmarkdown'
* removing 'C:/Users/tgoyal007/Documents/R/R-3.5.1/library/rmarkdown'

I have tried installing knitr and also I am not sure how to get xfun 0.15 as I have tried updating the packages. Please provide me with a solution on how to resolve the above.

**Comment by yihui** [comment]
I guess you should have figured it out by yourself, had you not deleted the issue guide (and you were asked not to delete it): https://github.com/rstudio/rmarkdown/issues/new

**Comment by hhoresearch** [comment]
I had a similar issue with knitr. The error that I had with knitr was with xfun, which I solved by manually installing from CRAN.

Then there was another issue with the knitr install. At this point, I updated to R 3.6 and reinstalled all my packages. This worked, so it may have been an issue with R versions.

**Comment by Twi-87** [comment]
Thank you so much. It is resolved now. Installed a new version of R studio
and it is working.
