### ISSUE TITLE
Error with shiny runtime and data.table :=

### ISSUE THREAD

**Issue by jrowen** [rstudio/rmarkdown#187]
I'm running into the following error with this markdown document:

``````

---
title: "Untitled"
output: html_document
runtime: shiny

---

```{r}
library(data.table)
DT = data.table(mtcars)
DT[, mpg:=mpg / 10]
DT
```
``````

R Markdown output is:

```
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: unnamed-chunk-1


processing file: test.Rmd

Quitting from lines 8-12 (test.Rmd) 
Error in `:=`(mpg, mpg/10) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
```

This runs fine if `runtime: shiny` is omitted.

```
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.4     htmltools_0.2.4  rmarkdown_0.2.50 tools_3.1.1      yaml_2.1.13 
```

**Comment by rubenarslan** [comment]
In case other people stumble upon this problem:

Even if your package just passes some arguments to knitr or rmarkdown, you need to make it data.table aware (the function at the bottom of this script in [my example](https://github.com/rubenarslan/formr/blob/master/R/rmarkdown_options.R)). Luckily this just means adding the line `.datatable.aware = TRUE` somewhere in your code.

I don't know if it's possible to make data.table smarter about this (it must lead to unforeseen and untested problems whenever any non-data.table-aware packages allows for the execution of custom code). In my case data.table was complaining about := assignment even though is.data.table was true. That seems overly sensitive, after all := has no "normal, vanilla data frame" use? But of course I see the reasoning whenever variables are accessed etc.
