### ISSUE TITLE
Add a new format for new commonmark_x output in Pandoc 2.10.1

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1870]
Pandoc 2.10.1 introduces a new `commonmark_x` format that supports some pandoc extension by default. 
See https://pandoc.org/releases.html#pandoc-2.10.1-2020-07-23
> Add commonmark_x output format. This is commonmark with a number of useful pandoc extensions enabled.

and also the announcement 
https://groups.google.com/g/pandoc-announce/c/aDKyXI3QFTg/m/z1qhmQHeDwAJ?pli=1
It seems in it is an important future formart
> `commonmark_x` is now available as a new input and output
format. This is `commonmark` with a number of useful pandoc
extensions enabled. Eventually (when more extensions are
supported) this may become pandoc's default markdown.

Maybe it is worth adding a new format or work toward correct integration and documentation. 
Also this changes impact the `gfm` format. 

At least those news formats needs to be looked into IMO.

**Comment by atusy** [comment]
Do you mean adding `commonmark_x_document`?
I think `commonmark_x` will be just a variant of `md_document`.

I agree with you, if you mean output formats should migrate to `--from commonmark_x` with some extensions in the future.

**Comment by cderv** [comment]
Yeah you're right. `commonmark_x` as variant in `md_document()` should be enough. I'll close this and reopen if necessary. 
The documentation update is tracked in https://github.com/rstudio/rmarkdown/issues/2209
