### ISSUE TITLE
line numbering is not working with pandoc 2.10.1

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1876]
```r
xfun::write_utf8(
  c(
    "# Line numbers",
    "",
    "```{r, attr.source='.numberLines'}",
    "x <- 1",
    "x+1",
    "```"
  ),
  "test.Rmd"
)

rmarkdown::find_pandoc()

# converting with Rmarkdown
rmarkdown::render("test.Rmd", 
                  output_format = rmarkdown::html_document(
                    highlight = "tango", 
                    keep_md = TRUE)
)
# open the resulting test.html and you'll have no numbering

# converting with pandoc only
rmarkdown::pandoc_convert("test.md", 
                          output = "test-pandoc.html", 
                          options = c("-s", "--highlight-style=tango"), 
                          verbose = TRUE)
# Open the resulting test-pandoc.html and you get correct numbering. 
```

This is an issue with pandoc (skylighting) and boostrap used by Rmarkdown 

boostrap defines 
```css
pre {
  overflow: auto;
}
```
and previously pandoc insured that overflow was visible with line number
```css
.sourceCode { overflow: visible; } -- needed for line numbers
```
but it has been removed (here https://github.com/jgm/skylighting/commit/7234122d64431e5f73af93637af1746c5f92ab07)

If we add it back to the Rmd file, it is working as expected
````md
---
title: "Untitled"
author: "Unauthored"
date: "0/20/2020"
output:
  html_document:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
.sourceCode { overflow: visible; }
```


## Line numbers

```{r, attr.source='.numberLines'}
if (TRUE) {
  x <- 1:10
  x + 1
}
```
````

An issue in pandoc will be opened to that this works again. 

_Moved from https://github.com/yihui/rmarkdown-cookbook/issues/271, originally reported by @aosavi_

**Comment by aosavi** [comment]
Not sure if this is related, but if I use `collapse=TRUE` without the line numbers, the code and results are collapsed into a single block (as I would expect), even if I evaluate multiple lines of code. However, as soon as I enable line numbers, using @cderv's trick above, I get multiple blocks of code and results combined for multiple lines of code (as opposed to `collapse=FALSE` where code and results are in separate blocks). It's not what I want or would expect, but is it on purpose?

**Comment by cderv** [comment]
I don't know how the line numbering should works when `collapse = TRUE`  - I suspect there is a compatibility to insure and I am note sure it is the case. Can you open a new issue with a reproducible example so that we discuss that there ? 
It is not the same topic I think. Thanks !

**Comment by yihui** [comment]
@aosavi I think that's expected. [With `collapse = TRUE`](https://bookdown.org/yihui/rmarkdown-cookbook/opts-collapse.html), you indicate that you want a single code block in the output that contains both source code and text output from the code. In a single code block, there is no way to tell which line comes from which original block. Therefore all lines in this single block are numbered sequentially.

**Comment by cderv** [comment]
@yihui I agree with that, but adding `.numberLines` does not render as in the cookbook, we got two code block and not one,  and hence two numbering. What you described (one block with sequantial numbering), would be the expected output for me.

````md
```{r, collapse=TRUE, attr.source = ".numberLines"}
1 + 1
1:10
```
`````

![image](https://user-images.githubusercontent.com/6791940/92257537-add3b900-eed5-11ea-912c-b0feb7064afa.png)

I keep highjack this thread but it may be worth opening another issue, don't you think ?

**Comment by atusy** [comment]
@cderv I think it worth opening another issue because this is not the matter of `.numberLines`. The chunk result splits into code blocks when `attr.source` or `class.source` are specified.

````
```{r, collapse=TRUE, attr.source = ".foo"}
1 + 1
1:10
```
````

**Comment by cderv** [comment]
Yeah that is what I thought. Thank you for checking @atusy !

**Comment by yihui** [comment]
@cderv You are right. Thanks!

**Comment by cderv** [comment]
Still no answer upstream regarding putting back the CSS rule in pandoc. I left another comment today.

@yihui should we add the CSS rule 
```css
.sourceCode { overflow: visible; }
```
in our template to fix this in our side with templates using bootstrap ? 

`.numberLines` is still not working with latest Pandoc versions. I guess it is not so used as not a lot of people have reported it. It could become more problematic once RStudio 1.4 is released with new Pandoc included.

**Comment by yihui** [comment]
> should we add the CSS rule

I'll let you decide. I'm okay with that.

**Comment by cderv** [comment]
I added the CSS rule in our template. We'll revert if changes happens upstream in skylighting which is unsure as they fixed (not on purpose) in the default CSS template but we don't use it ourselves (because we use bootstrap). It is the same as adding the rule in our template I believe.

**Comment by cderv** [comment]
For reference (and because it is good to know when we found a bug upstream), it will finally be back in skylighting in next Pandoc versions. 
https://github.com/jgm/skylighting/commit/f4430e1fa2241a919dfb1e286b8768ed938671f1

Thanks @aosavi for reporting in the first place !

**Comment by cderv** [comment]
And it is already release ! https://github.com/jgm/pandoc/releases/tag/2.11.3

So we will have a gap between 2.10.1 and 2.11.3 where we need this rule for `.numberlines` to work - I believe this is a small addition without too much impact so we can keep the rule in our template. Too bad it has not been fix as soon as we reported.
