### ISSUE TITLE
Issues with downloading rmarkdown

### ISSUE THREAD

**Issue by hatefishlovemeat** [rstudio/rmarkdown#1914]
I try to download rmarkdown using code
    install.packages("rmarkdown")
However, it shows 
  Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rlang’
 Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
 Execution halted
 ERROR: lazy loading failed for package ‘rmarkdown’
 * removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown’
 Warning in install.packages :
  installation of package ‘rmarkdown’ had non-zero exit status

Can anyone help me with it?

**Comment by cderv** [comment]
> there is no package called ‘rlang’

This means you are missing rlang. There must be something not ok with your R library. 

Try 

```r
install.packages("rlang")
```

then reinstall rmarkdown  `install.packages("rmarkdown")`.

Also, for such questions, please ask on https://community.rstudio.com/ next time. You could also search for answer this already happen to others. 

Thank you !
