### ISSUE TITLE
Support new pandoc 2.11 --citeproc option to deal with citations

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1915]
Pandoc 2.11 has been released yesterday: https://github.com/jgm/pandoc/releases/tag/2.11

Among the changes, there is a new flag to use with citations instead of the pandoc-citeproc filter. 

I believe we must do some adjustment to support this new feature when `pandoc_available("2.11")`

See the release note for details.

**Comment by jjallaire** [comment]
It looks to me like the 2 things we need to do are:

1) Use the `--citeproc` argument here when pandoc >= 2.11: https://github.com/rstudio/rmarkdown/blob/master/R/pandoc.R#L83-L90

2) Write a pandoc >= 2.11 compatible version of this function: https://github.com/rstudio/rmarkdown/blob/master/R/pandoc.R#L121-L122

Note we will of course need to preserve the old implementations for compatibility when earlier versions of pandoc are installed.

**Comment by jjallaire** [comment]
It's not super obvious in the docs but `--bib2yaml` is replaced by `pandoc <file> --to markdown --standalone`

There is also n extra `nocite` field that ends up in the YAML which might need to be stripped.

`--bib2json` is just `pandoc <file> --to csljson`

**Comment by cderv** [comment]
From first tests based on the draft PR above, the new citeproc processing does not output the same HTML as the filter did. This creates an issue with **bookdown** where references are not correctly relocated in each chapter as it should. 

I assume default style for citation is not the same.

**Comment by jjallaire** [comment]
You may be able to solve this by including CSL that emulates the old behavior? Alternatively I think just changing bookdown to  accommodate both variations of HTML would work.

**Comment by cderv** [comment]
> You may be able to solve this by including CSL that emulates the old behavior?

Yes I was thinking of that. It depends if we want to have a default that looks like before or keep the new default from pandoc 2.11

`pandoc-citeproc`: 
![image](https://user-images.githubusercontent.com/6791940/95756481-22a0cc80-0ca6-11eb-8dbb-77c3e2ffaa1e.png)

`--citeproc`
![image](https://user-images.githubusercontent.com/6791940/95756372-fedd8680-0ca5-11eb-97e6-99d35763017b.png)

> Alternatively I think just changing bookdown to accommodate both variations of HTML would work. 

I agree.

**Comment by jjallaire** [comment]
I prefer the new treatment in any case so making bookdown work w/ both is
IMO the way to go.

**Comment by yihui** [comment]
> Basically, what is linked changed. Just a styling thing :)

@cderv This change might affect the **tufte** package, since it parses citations from these links. If you have a chance, please double check if the **tufte** package is still able to place citations in the margin with Pandoc 2.11. Thank you!
