### ISSUE TITLE
Support Pandoc 2.11 new AST in ioslide Lua filter  

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1918]
We use in ioslide format a Lua filter using Table 
https://github.com/rstudio/rmarkdown/blob/cd0ca7fc4a0d2179c05dfb0ea0aa46978662b863/inst/rmd/ioslides/ioslides_presentation.lua#L436-L439

This should be adjust to support Pre / Post 2.11. 

Also there is a new Underline token to be taken into account

See changes about Lua Filter in Pandoc release note : https://pandoc.org/releases.html and new Lua filter doc (https://pandoc.org/lua-filters.html)

**Comment by jjallaire** [comment]
In my initial testing it looks like tables in `ioslides_presentation()` are still working. I wonder if Pandoc is using some sort of compatibility mode based on inspecting the signature of the `Table` function?

**Comment by jjallaire** [comment]
From the docs it looks like they've created a conversion utility for migrating Lua scripts:

**Lua filters:**

Add SimpleTable for backwards compatibility (#6575, Albert Krewinkel). A new type SimpleTable is made available to Lua filters. It is similar to the Table type in pandoc versions before 2.10; conversion functions from and to the new Table type are provided. Old filters using tables now require minimal changes and can use, e.g.,

```lua
if PANDOC_VERSION > {2,10,1} then
  pandoc.Table = pandoc.SimpleTable
end
```

and

```lua
function Table (tbl)
  tbl = pandoc.utils.to_simple_table(tbl)
  …
  return pandoc.utils.from_simple_table(tbl)
end
```

to work with the current pandoc version.

**Comment by jjallaire** [comment]
But it looks like perhaps our Lua script was written so long ago that perhaps it's benefiting from yet another layer of compatibility shims? I noted that our function takes a few arguments and the docs there show a single `tbl` argument.

**Comment by jjallaire** [comment]
I see what's happening now. ioslides isn't a filter it's a Lua custom writer, and Lua custom writers do not yet support the new table AST, e.g. here is the sample writer: https://github.com/jgm/pandoc/blob/master/data/sample.lua

**Comment by jjallaire** [comment]
This should take care of the Underline token: https://github.com/rstudio/rmarkdown/commit/3aa8babe410f04240a7c2445fe1c535fccd337cf

I believe that's all we are aware of that needs to be fixed here.
