### ISSUE TITLE
investigate differences in gfm output w pandoc 2.11

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#1919]
I've noticed that now GFM behaves a bit differently. For example, in Pandoc 2.9.2.1 

```bash
echo '## <https://www.google.com>' | pandoc --to gfm
```
Gives:

```
## <https://www.google.com>
```

Whereas in Pandoc 2.11 it gives:

```text
<a href="https://www.google.com" class="uri">https://www.google.com</a>
-----------------------------------------------------------------------
```

**Comment by jjallaire** [comment]
The header issue can be fixed with:

```bash
echo '## <https://www.google.com>' | pandoc --to gfm --atx-headers
```
```
## <a href="https://www.google.com" class="uri">https://www.google.com</a>
```

The `class="uri"` is there b/c pandoc adds the UI class automatically in the AST. This could be stripped with a filter, but it seems to me like this isn't intended behavior and perhaps should be fixed upstream?

**Comment by jjallaire** [comment]
I have found that the `gfm` format in pandoc is a source of behavioral variations mostly b/c it's evolving along w/ `commonmark` (and now `commonmark_x`). One way to sidestep this variation is to just spell out the exact subset of features known to be supported by `gfm`. That's what we do in the visual editor (and as a result the pandoc v2.11 update didn't affect our `gfm` editing mode at all):

https://github.com/rstudio/rstudio/blob/feature/pandoc-2-11/src/gwt/panmirror/src/editor/src/api/pandoc_format.ts#L355-L393

So in the `github_document()` format you'd basically use the full definition as the `variant`, e.g.

```
markdown_strict+pipe_tables+raw_html+auto_identifiers <...etc...>
```

I'd strongly recommend doing this as a way of permanently isolating `github_document()` from these sorts of changes (note that this would have also prevented the problems that we had w/ pandoc 2.10 and `gfm`)

**Comment by jjallaire** [comment]
Note that I have tried this approach and it doesn't seem to yield different behavior (so not worth pursuing except probably the `--atx-headers`)

**Comment by jjallaire** [comment]
Filed upstream issue here: https://github.com/jgm/pandoc/issues/6740

**Comment by jjallaire** [comment]
@yihui and @cderv, I submitted a fix for this directly to master (https://github.com/rstudio/rmarkdown/commit/64e8307a2e468ed71ca37343caa496aed2068d04) so that I could upgrade tomorrow's RStudio daily build to Pandoc 2.11 w/o breaking`github_document()`. This is really intended as a PR so let's discuss here if you think we should take a different approach and/or wait to see if there is an upstream fix.

**Comment by yihui** [comment]
64e8307 looks good to me. Thanks!

**Comment by cderv** [comment]
LGTM too

However, the fix has already been done upstream for the uri class addition.  
Maybe would could keep this change to support 2.11 as soon of now and remove it when next version is out ? 

Atx headers will be the default also (following https://github.com/jgm/pandoc/issues/6662) and `--atx-header` will be deprecated. So we should remove it later too for newer version.

**Comment by jjallaire** [comment]
Yes, let's leave this in until a new version of Pandoc that fixes both issues is released. If they release e.g. 2.11.1 w/ fixes then IMO it would be okay for us to drop the workaround entirely (just advising users to use 2.11.1 rather than 2.11).

**Comment by cderv** [comment]
the patched release is out with the autolink/raw html fix for gfm: https://github.com/jgm/pandoc/releases/tag/2.11.0.1

**Comment by jjallaire** [comment]
Great! I just removed the Lua filter (we still need --atx-headers until
another pandoc PR not part of this release is merged). Tomorrow's daily
build of the IDE will have Pandoc v2.11.0.1.

**Comment by cderv** [comment]
As I mentioned in https://github.com/rstudio/rmarkdown/issues/1919#issuecomment-707592082, `--atx-header` is now deprecated as it is the default behavior. Which impact us - see #1956. New argument to control the behavior: `--markdown-headings=atx|setext`

But the issue described here no more exist. With Pandoc 2.11
```sh
$ echo '## <https://www.google.com>' | pandoc --to gfm
## <https://www.google.com>
```

We can revert the fix now in https://github.com/rstudio/rmarkdown/commit/64e8307a2e468ed71ca37343caa496aed2068d04

However, should we support version that has this "bug" and make the fix conditional ? 
Or should we communicate and warn that **rmarkdown** is not to be used if Pandoc version is after 2.9.2.1 but below 2.11.2 ?

**Comment by jjallaire** [comment]
Let's keep the fix conditional on the versions where we know it needs to be applied.
