### ISSUE TITLE
Should anchors be added to empty headings?

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rmarkdown#1937]
The new `anchor_sections` feature adds anchors to empty headings in HTML documents and I think it may be better not to add anchors to these headings.

As one example, in learnr tutorials it's common to insert a pause by adding a blank level-3 heading. There's no need for the anchor in these cases and they're likely to be confusing since they appear in empty space where there is no text.

I'd be happy to submit a PR.

**Comment by atusy** [comment]
Sounds nice.
Just to clarify, do you mean exceptions for headings like below?

```bash
echo '# {}' | pandoc -t html                                                                     
# <h1 id="section"></h1>
```

**Comment by gadenbuie** [comment]
Yes, pretty much. I was thinking of adding a test to determine if the element is empty and if so to not add the anchor.

```js
  h.forEach(function(x) {
    const id = x.id || section_id(x.parentElement);
    if (id === '' || x.matches(':empty')) {
      return null;
    }
    //... add anchor
  }
```

It's hard for me to imagine a scenario where a user would have created an empty heading and would still want to have the anchor appear on hover.

**Comment by yihui** [comment]
@gadenbuie I completely agree that the test `x.matches(':empty')` is necessary here. Please feel free to submit a PR. Thanks a lot!

@cderv Please feel free to merge the PR anytime.

**Comment by cderv** [comment]
It seems learnr will deactivate the use of anchor_sections. But the fix are still relevant for other formats IMO so I guess it is ok to make those changes.
