### ISSUE TITLE
update rmarkdown

### ISSUE THREAD

**Issue by alaratomurcuk** [rstudio/rmarkdown#1945]
![image](https://user-images.githubusercontent.com/74178107/98520185-c324e500-2282-11eb-9dc0-de3d89182ab5.png)

**Comment by alaratomurcuk** [comment]
I have problem opening a new rmarkdown file. I get this warning every time (Creating R Markdown documents requires an updated version of the rmarkdown package. ) then it comes again even after say yes for the installing updated version.
Thanks!

**Comment by cderv** [comment]
This is something related to the IDE and not the **rmarkdown** package directly.
Which is your RStudio version ?

**Comment by alaratomurcuk** [comment]
It’s version 1.3.1093. What do you suggest?

**Comment by cderv** [comment]
This is not what I thought. From you screenshot, this is an issue with installing rmarkdown or your mac environment. 

Rmarkdown 2.5 binary is not available for CRAN for now unfortunately. Only the source package is available but you need to have a dev environment for R in your computer to install source package: https://r-pkgs.org/setup.html#macos

Can you try installing rmarkdown from Public Package Manager before doing anything else ? 
```r
install.packages("rmarkdown", repos = "https://packagemanager.rstudio.com/all/latest")
```

If it does not work you would need to do the dev setup for Mac to install source package (from the link above). 

Sorry for the inconvenience.

**Comment by alaratomurcuk** [comment]
Thanks for the help Christophe. It was about my mac environment I did not
notice at the time. Markdown works perfectly now. :))

Christophe Dervieux <notifications@github.com>, 9 Kas 2020 Pzt, 14:33
tarihinde şunu yazdı:

**Comment by cderv** [comment]
Glad it works. I'll close this issue then.

**Comment by yihui** [comment]
Since the **rmarkdown** package doesn't require compilation (i.e. it doesn't contain C/C++/Fortran code), you should be able to install the source package with any version of R above 3.0.0, and should not need Xcode (or Rtools on Windows). The failure above seems to be from a broken installation of R. I'm not totally sure. Anyway, I'm glad that it works now.
