### ISSUE TITLE
issue with rmarkdown 2.5 and Pandoc 2.11.1

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1947]
Hey all, I'm encountering an issue with rmarkdown 2.5 which is supposed to include the change of this PR:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.0.2  magrittr_1.5    htmltools_0.5.0 tools_4.0.2     yaml_2.2.1     
 [6] tinytex_0.27    stringi_1.4.6   rmarkdown_2.5   knitr_1.30      stringr_1.4.0  
[11] xfun_0.19       digest_0.6.25   rlang_0.4.7     evaluate_0.14
```

I get:

```
> rmarkdown::render("background.Rmd"	output_format = "pdf_document")	
processing file: background.Rmd		
|.........................................................................................| 100%		
ordinary text without R code		
output file: background.knit.md		
/usr/local/bin/pandoc +RTS -K512m -RTS background.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output background.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' --filter /usr/local/bin/pandoc-citeproc		
[WARNING] Deprecated: pandoc-citeproc filter. Use --citeproc instead.		
pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1	22] but attempted to decode with [1	21].
CallStack (from HasCallStack):		
error	called at ./Text/Pandoc/JSON.hs:112:48 in pandoc-types-1.21-LpPdBV1sPudK4kVghsVxWs:Text.Pandoc.JSON	
Error running filter /usr/local/bin/pandoc-citeproc:		
Filter returned error status 1		
Error: pandoc document conversion failed with error 83
```

Where on a terminal:

```
$ /usr/local/bin/pandoc --version
pandoc 2.11.1
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,
citeproc 0.1.0.3, ipynb 0.1.0.1
User data directory: /Users/udi/.local/share/pandoc or /Users/udi/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

And if I don't install `pandoc-citeproc` (via homebrew), I get a 127 error due to `pandoc-citeproc` not found. If I _do_ install `pandoc-citeproc`, I get the rstudio error above, which is essentially this issue:

https://github.com/jgm/pandoc-citeproc/issues/448

----

So what should I do? All packages are updated to their latest, including pandoc and it's version is not detected correctly? It should be, according to the [NEWS](https://github.com/rstudio/rmarkdown/blob/master/NEWS.md#rmarkdown-25) right?

_Originally posted by @doronbehar in https://github.com/rstudio/rmarkdown/pull/1916#issuecomment-724818933_

**Comment by cderv** [comment]
Hi @doronbehar, 

I opened an issue from your comment because it is better place to discuss this. 

Rmarkdown 2.5 is indeed suppose to support Pandoc 2.11 changes regarding citeproc. 

Can you share : 

* Result of `rmarkdown::find_pandoc()` from you R console 
* Result of `rmarkdown:::rmarkdown::pandoc_citeproc_args()` (note the three column as it is an internal function)

Thank you.

**Comment by doronbehar** [comment]
Hey, apparently I'm no longer experiencing the issue, after I restarted rstudio :shrug:. Also I get the expected results with the commands you gave me:

```
> rmarkdown::find_pandoc()
$version
[1] ‘2.11.1’

$dir
[1] "/usr/local/bin"
> rmarkdown:::rmarkdown::pandoc_citeproc_args()
Error: unexpected '::' in "rmarkdown:::rmarkdown::"
> rmarkdown::pandoc_citeproc_args()
[1] "--citeproc"
```

Besides that `:::` though..

I think this can be closed, but if I'll encounter once more that pandoc is not detected correctly, I'll post here again the results. Thanks for the attendance :).

**Comment by cderv** [comment]
> Result of rmarkdown:::rmarkdown::pandoc_citeproc_args() (note the three column as it is an internal function)

Sorry it was a wrong copy paste! 

> Hey, apparently I'm no longer experiencing the issue,

It could have been a side effect while new pandoc was found and new rmarkdown installed but previous version still loaded and used. 

Glad it works now!
