### ISSUE TITLE
Footnotes not rendering correctly in email

### ISSUE THREAD

**Issue by cranknasty** [rstudio/rmarkdown#1952]
Hi, I've built a HTML document in Rmarkdown and used some footnotes. 
In R the rendering occurs correctly and I get nice tasty foonotes. 
However when i send using sendmailR...the footnote return symbol is garbled...

![image](https://user-images.githubusercontent.com/7220445/99488337-a93a7f00-29b3-11eb-83ed-114f7a148484.png)

Is this fixable? Any ideas why it's happening?

**Comment by cderv** [comment]
Hi, 

If after the **rmarkdown** rendering it renders ok, I tend to think this can come from **sendmailR** processing.
Did you open an issue with **sendmailR** already (https://github.com/olafmersmann/sendmailR) ? 

FYI this symbol is introduced by Pandoc conversion for the backlink
https://github.com/jgm/pandoc/blob/efa34a8de67409a5604207e016b0a49e525c2db6/src/Text/Pandoc/Writers/HTML.hs#L1441

I believe there could be an encoding issue that **sendmailR** needs to deal with when processing the Rmd or html file. I don't know a lot about **sendmailR** sorry. I rather use **blastula** (https://rstudio.github.io/blastula/)

You can ask this type of question in https://community.rstudio.com as someone may have encounter this issue. 

However, this is not an issue with **rmarkdown** package I believe. If you agree with that, I'll close here. Thanks.
