### ISSUE TITLE
clean_site should default to preview TRUE to prevent deletion without notice

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1971]
Will close https://github.com/rstudio/blogdown/issues/518

`rmarkdown::clean_site(preview = TRUE)` should be the default with a nice message showing the files that would be deleted and informing what command to run to remove thoses files. 

Example of cleaning function with message: `bookdown::clean_book()`

**Comment by yihui** [comment]
If possible, I'd like to ship this in the next patch release. If you feel that's a hurry, I'm also okay with this going into v2.7.

**Comment by cderv** [comment]
👍
I can work on that tomorrow.
