### ISSUE TITLE
Fix CI on windows 

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#1986]
TinyTeX installation issue... 
Don't know why yet... 🤔

**Comment by yihui** [comment]
Yes, that's really weird. I've never run into this issue on AppVeyor but it occurs in GHA frequently:

```
C:\Users\RUNNER~1\AppData\Local\Temp>powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest $Env:TINYTEX_URL -OutFile install.zip" 
Invoke-WebRequest : Unable to read data from the transport connection: An existing connection was forcibly closed by 
the remote host.
At line:1 char:82
+ ... Type]::Tls12; Invoke-WebRequest $Env:TINYTEX_URL -OutFile install.zip
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by cderv** [comment]
I use the action to a commit using the new binary install script. You can't see that quickly here because the action renames it. 

I may try to switch back to old install script for windows, or install myself with `setup-tinytex`. 

Issue is only on Windows, so weird.

I'll look into that later.

**Comment by cderv** [comment]
Strangely, it works in PR checks like this one from 16hours ago
https://github.com/rstudio/rmarkdown/runs/1590369732

But not in last commit from 12 hours ago
https://github.com/rstudio/rmarkdown/runs/1591592787

Is this an issue with mutualized runner and when build are trigger ? 
I can't reproduce it for now in a dummy repo using the same actions setup-tinytex.

**Comment by cderv** [comment]
And it works ok now in a small test
https://github.com/rstudio/rmarkdown/pull/1992/checks?check_run_id=1594189223

**Comment by cderv** [comment]
And the full workflow is working when run in the PR 🤷‍♂️ 
https://github.com/rstudio/rmarkdown/pull/1992/checks?check_run_id=1594340444

**Comment by cderv** [comment]
This is now working after changing nothing specific to Windows in the PR. We won't know why - must be something wrong with the runner and a reset-like operation must have fixed it.

**Comment by cderv** [comment]
And it was even working before I merge the PR !! 
https://github.com/rstudio/rmarkdown/runs/1594296319

I won't try to understand more. We'll see if this will happen again

**Comment by cderv** [comment]
And it is broken again... really weird.

**Comment by cderv** [comment]
Possible that this could be related to reached server being busy... but it is odd that this only happens on windows then. https://stackoverflow.com/a/5420788/3436535

**Comment by cderv** [comment]
And it is working again. I believe there is something with Windows Runner and Powershell downloads - I used a smaller bundle (TinyTeX-1) and we'll see if we still have issues in the long run.
