### ISSUE TITLE
fig.cap

### ISSUE THREAD

**Issue by wilson0106** [rstudio/rmarkdown#1987]
---
Hi,

I'm using fig.cap in my R chunk, but it isn't work when I use webr package.

For example:

{r fig.cap = 'my caption here'}
install.packages("webr")
library(webr)
a <- rnorm(n = 100, sd = 1.9) + runif(n = 100, min = 5, max = 25)
b <- 13.5
c <- t.test(x = a, mu = b)
plot(c)

PS: I remove back accent of chunk to show the code.

When I execute this R chunk code above, my caption appears in latex language in my pdf document: 

\begin{figure}[H]
\caption{my caption here}
\end{figure}

How could I solve it?
Thanks

Wilson

**Comment by cderv** [comment]
I did this 
````md
---
title: manual anchor
output: 
  pdf_document: default
  html_document: default
---

```{r fig.cap = 'my caption here'}
library(webr)
a <- rnorm(n = 100, sd = 1.9) + runif(n = 100, min = 5, max = 25)
b <- 13.5
c <- t.test(x = a, mu = b)
plot(c)
```
```` 

and in both I see caption. Example for PDF
![image](https://user-images.githubusercontent.com/6791940/102643254-44fc0e00-415f-11eb-877d-fe387d4ebe01.png)

So no issue on my end.

You can try to follow the issue guide and be sure to update your package. Also we are missing good formatting, session info and a full reproducible example. All is explained here: https://yihui.org/issue/

**Comment by wilson0106** [comment]
Hi cderv
 
I'm updated my packages but it wasn't work.

I'm use pdf_book, because I'm working with bookdown. When I change pdf_book to pdf_document or pdf_document2 it also won't works. Could be some conflict with bookdown?

PS: I'm test in RMarkdown just this code and works too.

Thank you for quickly reply

**Comment by wilson0106** [comment]
Hi cderv,

I come back here to inform the solution of my question.

In my script I added percent symbol (%) without double backslash in fig.cap.

Thanks for your attention

**Comment by cderv** [comment]
Glad you found your solution. 
You indeed need to escape all characters in `fig.cap`. 
Or you can use text reference feature if you are using a bookdown output format. It allows to use markdown syntax and avoid the need of escaping. 

https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references

Hope it helps.
