### ISSUE TITLE
bibliography rendering for markdown files

### ISSUE THREAD

**Issue by bquast** [rstudio/rmarkdown#202]
I am not sure if you could call this an issue, as I am sure it is by design. 

However, it would be useful to have an option to render the bibliography in the markdown file. So that markdown-based platforms such as Jekyll can also make use of this functionality.

**Comment by yihui** [comment]
Since you mentioned Jekyll, I assume you were interested in creating websites based on R Markdown. If that is the case, you may want to take a look at blogdown: https://github.com/rstudio/blogdown
