### ISSUE TITLE
UTF-8 characters in YAML header and markdown body

### ISSUE THREAD

**Issue by ripkrizbi** [rstudio/rmarkdown#205]
I am experiencing several problems while trying to get my Rmd document containing UTF8 chars to properly render in PDF (and Word for that matter).

First, I have noticed that including a non-ascii character in Title header causes pandoc to complain about strange characters with 

```
pandoc.exe: Could not parse YAML header: Control characters are not allowed "source" (line 2, column 1)
```

The Title is not rendered in the final PDF at all. This seems to be a bit inconsistent, especially when no such warning is given for the Author field, and it does seem to be rendered, even when it contains UTF-8 chars (but see below).

Next, no matter how I try I cannot get the Latin2 chars to appear in my PDF. I've used xlatex as the rendering engine, saved Rmd in UTF8 without BOM (this is a default encoding for all my R files), but still no characters appear. Of all the accented characters I'm trying to get, I only am able to display C-caron, but without the accent. The funny thing is that even the intermediate TeX file is stripped away of the non-latin characters. Also notice the D-bar character that renders OK in one case (Author) but not in other cases where it gets converted to plain D.

My environment:

```
> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pander_0.3.8     knitr_1.6        rmarkdown_0.2.54

loaded via a namespace (and not attached):
[1] digest_0.6.4    evaluate_0.5.5  formatR_0.10    htmltools_0.2.4 stringr_0.6.2   tools_3.1.0    
[7] yaml_2.1.13  
```

Rmd file:
https://www.dropbox.com/s/cieswf87o5qc52n/test2.Rmd

Intermediate tex file:
https://www.dropbox.com/s/8w4fd746t10za0i/test2.tex

Rendered PDF:
https://www.dropbox.com/s/4oxj7wqpnfh8th7/test2.pdf

**Comment by djhurio** [comment]
The workaround is to save title and author in text files with UTF-8 encoding and read them in with R. I am using the following YAML header:

```
---
title: "`r readLines('apraksts/title.txt', encoding = 'UTF-8')`"
author: "`r readLines('apraksts/author.txt', encoding = 'UTF-8')`"
date: "`r Sys.time()`"
---
```
