### ISSUE TITLE
reveal.js print to pdf only prints the first slide?

### ISSUE THREAD

**Issue by cboettig** [rstudio/rmarkdown#206]
This appears to be due to an older version of pandoc's reveal.js template.  See the current template here:  https://github.com/jgm/pandoc-templates/blob/master/default.revealjs

Which uses the same solution as provided here: http://stackoverflow.com/questions/23571270/reveal-js-print-to-pdf-only-prints-the-first-slide

(Apologies if you've already fixed this, I try to check against the latest version of rmarkdown, but sometimes not sure if rmarkdown's pandoc calls are using my default templates in `~/.pandoc` or the rmarkdown ones)

**Comment by yihui** [comment]
I guess you are more satisfied with xaringan now :) https://github.com/yihui/xaringan/issues/65

**Comment by srearl** [comment]
If other folks are running into this problem, I struggled for quite some time trying to print a `xaringan` presentation to PDF in Firefox 59.0.2 (printed only the first slide - all other pages were blank), but the same html file without any modification printed to PDF without problems in Chrome. Identical behavior on both Ubuntu and MacOS.
