### ISSUE TITLE
Convert html to docx

### ISSUE THREAD

**Issue by markwsac** [rstudio/rmarkdown#2074]
Thanks for this lovely package. Is it possible to convert html text to word document?

**This does not work**
`rmarkdown::pandoc_convert("<b>Sam</b> <i>Dave</i>", to = "docx", output = "word.docx" )
`

**This works**
`rmarkdown::pandoc_convert("test.html", to = "docx", output = "word.docx" )`

**Comment by cderv** [comment]
Yes this is expected. Currently, `pandoc_convert()` only work with file input as documented: 
https://rmarkdown.rstudio.com/docs/reference/pandoc_convert.html

So you'll need to write to file locally before converting. Here an example wrapper: 
````r
convert_html <- function(text, ...) {
  tmp_file <- tempfile(tmpdir = ".")
  on.exit(unlink(tmp_file), add = TRUE)
  xfun::write_utf8(text, tmp_file)
  rmarkdown::pandoc_convert(input = tmp_file, ...)
}

convert_html("<b>Sam</b> <i>Dave</i>", from = "html", to = "docx", output = "word.docx")
```

The working directory for Pandoc can be tricky unless you set the expected flag for pandoc or use absolute path.

I'll keep that issue open as a reminder for improving the function wrapping Pandoc - maybe in another package, a thinner wrapper to Pandoc.
