### ISSUE TITLE
Select Rmarkdown files dynamically

### ISSUE THREAD

**Issue by johnbde** [rstudio/rmarkdown#2097]
I have multiple Rmarkdown files and I want to select Rmarkdown file based on selection of dropdown value. I made it my own template (see below) and added dropdown. I want if value Saab is selected, then Saab.Rmd file gets rendered. Is it possible in Rmarkdown?

**mytemplate.htm**

```
<head>
</head>

<body>

  <label for="cars">Choose a car:</label>
  <select id="ddlViewBy" name="cars" id="cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>

<script>
  document.addEventListener("DOMContentLoaded", (_) => {
    document.querySelector("select").addEventListener("change", (e) => {
      alert(e.target.value);
    });
  });
</script>


$body$
</body>

```
Later in the parent file

```
output:
  html_document:
    template: mytemplate.htm

```

**Comment by cderv** [comment]
Thanks for opening an issue. 

I am not sure to understand how this will play out. An HTML template will be used to render a Rmd file. 
When you say you want the dropdown value to trigger a render, I am not sure how you imagine that to work. 

Let's discuss your use case: 
> I have multiple Rmarkdown files and I want to select Rmarkdown file based on selection of dropdown value. 

For this you need an interface that would allow selection and be able to trigger an R process to call `rencer()` on the correct file. I believe you could do that with a small Shiny interface that would offer the dropdown menu, and call in R `ramrkdown::render()` based on the selection. Here is an example: https://shiny.rstudio.com/articles/generating-reports.html for download report generated base on a shiny app state. 

There is another view for this if we consider that your multiple Rmd files are just small variations of a same template. For this, you could be interesting to look a Parametrized report (https://bookdown.org/yihui/rmarkdown/parameterized-reports.html) where you will be able to render different output report based on a same source Rmd file, by just changing Parameters.

Anyway, I don't think this is something directly related to how **rmarkdown** is working. I would also advice to follow the issue guide (https://yihui.org/issue/#got-a-question) and ask in a Q&A site like https://community.rstudio.com as a broad community is there ready to help and they will have useful experience to share I am sure.
