### ISSUE TITLE
rmarkdown/lua/pagebreak.lua:25: attempt to compare table with string

### ISSUE THREAD

**Issue by jeroen** [rstudio/rmarkdown#2099]
Started getting this error everywhere when rendering vignettes using the dev version of rmarkdown

```
--- re-building ‘bookdown.Rmd’ using rmarkdown
Error running filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua:
...lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua:25: attempt to compare table with string
stack traceback:
	...lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua:25: in main chunk
Error: processing vignette 'bookdown.Rmd' failed with diagnostics:
pandoc document conversion failed with error 83
--- failed re-building ‘bookdown.Rmd’
```

Examples: 
 - https://github.com/r-universe/tidyverse/runs/2299347396?check_suite_focus=true
 - https://github.com/r-universe/rstudio/runs/2301506560?check_suite_focus=true
 - https://github.com/r-universe/rstudio/runs/2298734428?check_suite_focus=true

**Comment by jeroen** [comment]
Reproducer here: https://github.com/rstudio/rmarkdown/pull/2100

**Comment by atusy** [comment]
@jeroen Thanks for the report, and sorry for breaking the reverse dependencies.

It seems `PANDOC_VERSION` can be compared with string since Pandoc 2.7.3.
We need fix.

> Lua: add Version type to simplify comparisons (Albert Krewinkel). Version specifiers like PANDOC_VERSION and PANDOC_API_VERSION are turned into Version objects. The objects simplify version-appropriate comparisons while maintaining backward-compatibility. A function pandoc.types.Version is added as part of the newly introduced module pandoc.types, allowing users to create version objects in scripts. https://pandoc.org/releases.html

**Comment by cderv** [comment]
Thanks. It is what I was worried about as we had an issue in **pagedown** with that in the past. I did not test enough. I'll fix that. Thanks @jeroen !

**Comment by jeroen** [comment]
Did you notice the [lua docs](https://pandoc.org/lua-filters.html) have examples of how to check for a minimum version:


```lua
PANDOC_VERSION:must_be_at_least '2.7.3'
PANDOC_API_VERSION:must_be_at_least(
  '1.17.4',
  'pandoc-types is too old: expected version %s, got %s'
)
```

**Comment by cderv** [comment]
Thanks - we've seen that. 

* `PANDOC_VERSION:must_be_at_least` throws an error and we don't want that. Pandoc would error and we just want to skip the filter here
* `PANDOC_VERSION:must_be_at_least` is available since Pandoc 2.7.3
* `PANDOC_VERSION` is available since Pandoc 2.1 but since 2.7.3 it is a version object while before it was a simple table. 

I made a change to handle all these versions now. This should be ok. Thanks for catching that this quick!

**Comment by cderv** [comment]
i'll watch th universe build. 

BTW why **rmarkdown** is built twice in r-universe in rstudio/ and in tidyverse/ universe ?

**Comment by cderv** [comment]
> BTW why rmarkdown is built twice in r-universe in rstudio/ and in tidyverse/ universe ?

It was manually added I see - I have my answer
https://github.com/r-universe/tidyverse/commit/fb0c57fdfce3c689184a95ce5b0b2cf50da215f4#diff-f7a51064e887d17782288e3364f18f8087dc3a3e7ecc73660e21f6fe476a8da8

**Comment by jeroen** [comment]
> BTW why rmarkdown is built twice in r-universe in rstudio/ and in tidyverse/ universe ?

This is because the tidyverse package haven specifies rmarkdown as a `remote` in the description. Thereby it becomes part of the universe.

**Comment by cderv** [comment]
Good to know ! Any remotes becomes part. Thanks!
