### ISSUE TITLE
[LUA] Find a way to load / require files to avoid duplication of shared functions

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2103]
Currently we need to copy some code in each Lua filter. 

It would be better to be able to have one `utils.lua` or `init.lua` that we would load in each filter, and then only modify this one. 

Possible solution: 

- use an import function: https://gist.github.com/cderv/ca24d2681b0a1c4b6f91e0b49d725f36 (only available since 2.1.2)

- modify `--data-dir` (advices from @tarleb)

> The best option would probably be to call pandoc with a custom `--data-dir` and place an `init.lua` in that folder that would work with all versions since 2.0.5
> --- advice from @tarleb

- modify `LUA_PATH` variables

> with LUA_PATH one could then call `require 'mylib'` at the top of each filter. The advantage is that it works for all versions, but still requires code to be added to all filters" 
> --- advice from @tarleb

**Comment by tarleb** [comment]
Maybe one additional method would be to set a separate `RMARKDOWN_LUA_INIT` environment variable and use it with

``` lua
dofile(os.getenv 'RMARKDOWN_LUA_INIT')
```

That's short, keeps for full control in RMarkdown, and doesn't interfere with anything a user might want to set.

**Comment by cderv** [comment]
Oh that is a really great idea! Thanks!

**Comment by cderv** [comment]
@yihui where do you think it would be better to set this variable ? 

I see several options:
* `.onLoad` or `.onAttach`
* in `render()` directly maybe
* or closer to the need in when `pandoc_lua_filter_args()` is called maybe. 

I would think the 3rd option but maybe that is not good practice ?

All this will happen before Pandoc is called so I think it will be available to Pandoc.

**Comment by cderv** [comment]
This could also be a way to maintain a shared script in **rmarkdown** and use it in all other packages using **rmarkdown**, like **bookdown** or **pagedown** 🤔
