### ISSUE TITLE
Disconnected Error Event

### ISSUE THREAD

**Issue by markwsac** [rstudio/rmarkdown#2104]
Thanks for this great package. I wonder if there is any event like shiny for disconnected screen or errors (like below). I am trying to stop JS operation of my custom JS  when rmarkdown stops.
 
```
$(function() {$(document).on('shiny:disconnected shiny:error', function(event) {

  }) });
```

**Comment by cderv** [comment]
Hi, 

I may be misunderstanding your question but **rmarkdown** is not like **shiny**: There is no R process opened when you look at a document produced only with **rmarkdown**. Most general usecase is that you will produce a HTML output format using `rmarkdown::html_document()` and this will produce a HTML file from your source Rmd file. When you open your HTML document, nothing is running so I am not sure what is to stop. 
**rmarkdown** is only used during the rendering process, so before anyone would open the document in a browser and some JS script apply. 

Can you tell us more about your use case by giving an example ?

**Comment by markwsac** [comment]
Thanks for your response. I am using [countdown](https://github.com/gadenbuie/countdown) package which runs in JS. You can check or track running time in console. It keeps on running in browser even if I stop processing of document in R. I was thinking to stop it via JS if we have some events like shiny. My bad if rmarkdown does not work like this.

**Comment by cderv** [comment]
I think you should open an issue in **countdown** if there is something not working as you expect. 
To help I am pinging the author @gadenbuie (👋)

> You can check or track running time in console. It keeps on running in browser even if I stop processing of document in R.

What do you mean by "stop processing" ? It is my understanding that **countdown** is used in the browser while a document in being viewed. So there is no R or any **rmarkdown** functions happening at this staged. 
Can you give an example of what you meant with the above ?
