### ISSUE TITLE
HTML dependency error or blank box where shiny app should be in website built using rmarkdown

### ISSUE THREAD

**Issue by bpbraun** [rstudio/rmarkdown#2111]
We use rmarkdowns to make websites, at this point with static html. However, we'd like to add shiny content. Yet, the only way I've figured out how to do this is with an iframe (https://datasciencegenie.com/how-to-embed-a-shiny-app-on-website/). When I try to code the shiny app either directly in the rmarkdown chunk or refer to it with shinyAppDir I get this error:

Error: path for html_dependency not provided
I've tried changing the runtime of the individual rmd but that fails with the same error.

Is there a way to imbed shiny apps in rmarkdown website without separately publishing them and referring to them as iframes?

Here's a github repo with a minimally repeatable example. In this case I don't get the same error, but the shiny will not render in the website.

https://github.com/bpbraun/shiny-doesnt-work-in-website

**Comment by cderv** [comment]
Hi @bpbraun, 

Thanks for your patience. 

> Error: path for html_dependency not provided

About this issue, this is something we need to fix and it is tracked in another issue: https://github.com/rstudio/rmarkdown/issues/2021 with a potential fix in https://github.com/rstudio/rmarkdown/pull/1948

Hopefully we'll merge this soon. 

About the why: it seems that one of the html dependency used in your documents does not provide a `path` on disk and just a url which **rmarkdown** does not handle correctly - this is a bug IMO. 

I don't where it comes from for you - maybe something change recently with **shiny**

> Is there a way to imbed shiny apps in rmarkdown website without separately publishing them and referring to them as iframes?

This is one of the way to share an independant shiny app in a Rmd document. 

However you can use shiny in what we called interactive document: https://bookdown.org/yihui/rmarkdown/shiny-documents.html - These are special document with `runtime: shiny` that allow to create shinyapps using Rmd document. 

I understand you are using R Markdown website. I think this should work if you use `runtime: shiny`. It won't with `runtime: shiny_prerendered` (related to https://github.com/rstudio/rmarkdown/issues/1576)
Usually, users who are doing website do directly a shiny apps. But there are easier way like using **flexdashboard** when the layout is ok. (https://rmarkdown.rstudio.com/flexdashboard/shiny.html) 

Let's note that shiny runtime requires to us `rmarkdown::run()` and not `rmarkdown::render()`. This is what will happen if you click the knit button in your file `shiny_runtime/index.Rmd`. So related to your example repo, you run `rmarkdown::run("shiny_runtime/index.Rmd")`

This works for me when I clone your repo "bpbraun/shiny-doesnt-work-in-website" 

Hope it helps.

**Comment by bpbraun** [comment]
Thanks--it's really just an issue for the website.  When I knit the individual rmd's everything works.

**Comment by cderv** [comment]
> it's really just an issue for the website4

🤔 that is weird. I have not issue when rendering the website in your example repo. Does it happens in this example too ?

**Comment by bpbraun** [comment]
Here's what I'm doing:

![image](https://user-images.githubusercontent.com/36509209/116289121-33a3bd80-a760-11eb-827d-1ae8ff6e25c3.png)

Then when the website renders I get this blank box where the shiny app should be:

![image](https://user-images.githubusercontent.com/36509209/116289244-52a24f80-a760-11eb-9006-fefcd0ee2ce8.png)

**Comment by cderv** [comment]
Thanks for sharing this. 

By trying with your example, I don't think the RStudio IDE knows how build a website using shiny runtime. It is not so common it seems. Build website will run `rmarkdown::render_site()` and this won't work. 
However, if you open `index.Rmd` and click "Run Document" button, it should open the website.

If you run the command `rmarkdown::run()` - does it works as expected for you ? 

I wonder if this is correctly handle when publishing to RStudio Connect. 🤔

**Comment by bpbraun** [comment]
I added runtime shiny to the index yaml header--still no go.  The website builds and shows the normal loading dial for shiny, but when I click on the tabs of the navbar I get not found.

![image](https://user-images.githubusercontent.com/36509209/116412133-5f787f00-a804-11eb-9d1e-aaf80a75155a.png)

![image](https://user-images.githubusercontent.com/36509209/116412255-7fa83e00-a804-11eb-92e6-25a7d3421fa4.png)

![image](https://user-images.githubusercontent.com/36509209/116412301-8afb6980-a804-11eb-896b-33633d8d44e2.png)

Is it something that needs to be added to the .yml file?  Maybe I need to use a different framework like `blogdown`?

Here's my .yml

```
name: "202 Group"
navbar:
  title: "Website"
  left:
    - text: "Overview"
      href: index.html
    - text: "Untitled"
      href: Untitled.html
```

And rstudio connect is not handling it either . . .

**Comment by cderv** [comment]
hum I see. R Markdown Website and Shiny document is not the most simple out of the box. 

Try changing your YAML to point to Rmd file
````yaml
name: "202 Group"
navbar:
  title: "Website"
  left:
    - text: "Overview"
      href: index.Rmd
    - text: "Untitled"
      href: Untitled.Rmd
```

As you are using shiny, your html file does not exist in your project. html from the Rmd file are rendered by shiny during the rendering process of the application.  
This is the same for single shiny document: You run them to start the shiny apps and not html will be produced in output. This is because it is shiny app and not a standard R Markdown document. 

By setting the Rmd in the navbar, you are telling the website to point to a Rmd file which shiny runtime knows how to render and show. 

Is this working for you with this change ?

**Comment by bpbraun** [comment]
YES!!!

Thank you!
