### ISSUE TITLE
Fails to locate images which are in directories having a prefix of the document name in the name

### ISSUE THREAD

**Issue by krassowski** [rstudio/rmarkdown#2119]
I apologize ahead I must be doing something wrong and/or not seeing a step in the R tool chain that causes the issue. I also think it might not be a bug in rmarkdown itself, but would greatly appreciate help in narrowing down where is this coming from. Possibly related to #2110

I have an vignette: `Examples_R.Rmd` and files for that vignette: `Examples_R_files/`. Possibly after updating versions of packages in my environment my R CMD check started failing in the "re-building vignettes" step:

```
   Error(s) in re-building vignettes:
     ...
   --- re-building ‘Examples_R.Rmd’ using rmarkdown
   File Examples_R_files/Examples_R_12_0.png not found in resource path
   Error: processing vignette 'Examples_R.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 99
   --- failed re-building ‘Examples_R.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘Examples_R.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
```

It is also now failing on Win Builder for R develop version.

I checked numerous times that `Examples_R_files/Examples_R_12_0.png` is indeed in the correct location. It just happens to be the first image in my markdown file:

```
![ ](Examples_R_files/Examples_R_12_0.png)
```

If I remove the line with that image, it fails on the next one (which is also present).

I originally intended to diagnose the issue by removing all images and execution `print(getwd())` but in the process I noticed something very surprising: renaming the file to anything else, say `Examples_A.Rmd` fixes the issue.

After rolling back the rename, I then followed by renaming the directory to `Examples_A_files` (and all relevant occurrences in `Examples_R.Rmd`) and it worked again.

To demonstrated that the issue is indeed with the prefix, I followed by renaming `Examples_R.Rmd` to `Examples_A.Rmd` (while keeping the files and references as `Examples_A_files` and it broke again.

I downgraded rmarkdown all the way down to 2.0 and it did not fix the issue. Unless I did something wrong when downgrading the next conclusion would be that it might be something with pandoc instead. The might be coming from: 

https://github.com/jgm/pandoc/blob/60974538b25657c9aa37e72cc66ca3957912ddec/src/Text/Pandoc/Class/PandocPure.hs#L184-L194

I tested with two pandoc versions:
- 2.9.2
- 2.8.1

both demonstrate the described behaviour.

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

1. Starting from any R package you have, create a vignette named `Examples_A.Rmd` in the `vignettes/`

```
---
title: "Examples - R"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Examples - R}
  %\usepackage[utf8]{inputenc}
---

![ ](Examples_A_files/Examples_R_12_0.png)
```

2. Create a directory named `Examples_A_files` in `vignettes/`
3. Put a file called `Examples_R_12_0.png` in the `Examples_A_files` directory
4. Confirm your layout with `tree`:

    ```
    vignettes/
    ├── Examples_A_files
    │   └── Examples_R_12_0.png
    └── Examples_A.Rmd
    ```

5. Try to run R CMD check and see it fail.
6. Note that running `rmarkdown::pandoc_convert("Examples_A.Rmd")` works perfectly fine.

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.10

Locale:
  LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
  LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
  LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2       
  graphics_4.0.2    grDevices_4.0.2   highr_0.9         htmltools_0.5.1.1
  jsonlite_1.7.2    knitr_1.33        magrittr_2.0.1    markdown_1.1     
  methods_4.0.2     mime_0.10         rlang_0.4.10      rmarkdown_2.7.12 
  stats_4.0.2       stringi_1.5.3     stringr_1.4.0     tinytex_0.31.6   
  tools_4.0.2       utils_4.0.2       xfun_0.22         yaml_2.2.1       

Pandoc version: 2.8.1
```

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

**Comment by krassowski** [comment]
Also running `devtools::build_vignettes()` from `vignettes/` works perfectly fine for me:

```
> devtools::build_vignettes()
ℹ Building ComplexUpset vignettes
✔ Creating 'doc/'
✔ Adding '^doc$' to '.Rbuildignore'
✔ Setting active project to '<no active project>'
✔ Adding '/doc/' to '.gitignore'
✔ Setting active project to '<no active project>'
ℹ Moving Examples_A.html and Examples_A.R to doc/
ℹ Copying Examples_A.Rmd to doc/
✔ Creating 'Meta/'
✔ Adding '^Meta$' to '.Rbuildignore'
✔ Setting active project to '<no active project>'
✔ Adding '/Meta/' to '.gitignore'
✔ Setting active project to '<no active project>'
ℹ Building vignette index
```

The HTML file does contain the embedded image (base64-encoded).

**Comment by yihui** [comment]
I don't think this is caused by **rmarkdown** but `R CMD check` instead. I didn't find the relevant source code in base R, but I suspect that `R CMD check` would ignore `foo_files` when copying the vignette `foo.Rmd` (just to let you know, when `R CMD check` checks the vignette, it will copy the vignette to a separate folder).

I'm afraid there isn't anything we could do about it on our side. Either base R has to carry the `foo_files` folder forward, or you rename it.

Thanks for the report!
