### ISSUE TITLE
Is sass caching really working as we expect ? 

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2120]
Take this example with last dev version of rmarkdown: 

````
---
title: Test
date: 28/04/2021
output: 
  html_document:
    css: style.scss
---
# What color am I ? 
Will this change color ?
````

Render first with `style.scss`
````scss
$main: red;

h1 {
  color: $main;
}
````

It will be red

but then with 
````scss
$main: blue;

h1 {
  color: $main;
}
````
it will stay red.

So maybe sass caching and rmarkdown are correctly working together... 🤔 

This follows test in https://github.com/yihui/xaringan/pull/311 with @abichat

I have seen that mentioned in https://github.com/rstudio/bslib/issues/307#issuecomment-822907221 and setting the sass cache to FALSE will solve this. Should it be FALSE by default with rmarkdown ? 

I believe activating caching when working on a Rmd document is not a good idea. But it would be useful when nothing change but a document is rerendered without change to css. 

It is possible that we need to offer a switch to activate / deactivate cache easily. Or that we document clearly this. 

Also, if I am correct on the above, should cache be deactivated by default, and opt-in by user by adding `options(sass.cache = TRUE)` in the setup chunk.

**Comment by cderv** [comment]
From `sass::sass` doc, we may need to add a `cache_key_extra` 
> For example, if input contains something like "@import sass_file.scss" you may want to include the file.mtime() of sass_file.scss

This way, the cache would be invalidated each time the file provided in `css` is changed. Which is the expected  behavior I think.

**Comment by cderv** [comment]
But I would have expected that to work out of the box in `sass:::sass_hash()`
https://github.com/rstudio/sass/blob/4b988689d8de4c4bfe3b891590df45d932efa0e8/R/sass_cache.R#L212-L233

`sass:::add_sass_file_mtime()` is for that when a sass input is with `sass::sass_file()`

However, `sass::sass(sass::sass_file("file.scss"))` is not providing a `sass_file` object to this hash function because it gets processed by `sass::as_sass()` before https://github.com/rstudio/sass/blob/dd6a2b17bb0b93b879c48ddd6d17ce2324f81913/R/sass.R#L171

so what happens in **rmarkdown** when `css: style.scss` is passed in YAML

```r
sass::sass(sass::sass_file("style.scss")) 
# will call internally
sass::as_sass(sass::sass_file("style.scss"))
# and the hash will be calculated on this 
sass:::sass_hash(sass::as_sass(sass::sass_file("style.scss"))) 
# which does not know how to include the mtime and is different from 
sass:::sass_hash(sass::sass_file("style.scss"))
# which will trigger  sass:::add_sass_file_mtime I believe
```

**Comment by cderv** [comment]
This just ☝️ is a **sass** issue I believe. 

Regarding **rmarkdown**, I confirm that by adding `cache_key_extra` it now works as expected and this rmarkdown's issue is fixed. 

```diff
diff --git a/R/html_document_base.R b/R/html_document_base.R
index c4529c6c..a0420b0c 100644
--- a/R/html_document_base.R
+++ b/R/html_document_base.R
@@ -99,15 +99,16 @@ html_document_base <- function(theme = NULL,
         f <- sass::sass(
           sass::sass_file(f),
           # write output file to `lib_dir/sass-{sass:::sass_hash()}{[basename(f)}`
           output = sass_output_template(
             basename = xfun::sans_ext(basename(f)),
             tmpdir = lib_dir
           ),
-          options = sass::sass_options(output_style = "compressed")
+          options = sass::sass_options(output_style = "compressed"),
+          cache_key_extra = file.mtime(f)
         )
       }
       f <- normalized_relative_to(output_dir, f)
       args <- c(args, "--css", pandoc_path_arg(f, backslash = FALSE))
     }
```

Only drawback: when `self_contained: FALSE`, a folder `sass{sass_hash()}/` will be created in `lib_dir` for each time the cache is invalidated. 

I don't know if we can offer a cleaning mechanism - but I guess it is like with HTML dependencies: a folder is created for each, but older ones are not removed automatically. It is just less frequent

Maybe we should deactivate the sass cache by default, and document how to activate it if needed by the user as **rmarkdown** is sass cache aware. Or if we should document how to deactivate the cache when developing the css of a **rmarkdown** document to avoid creating so many folders. 

This is obviously not an issue when `self_contained = TRUE` because the lib dir folder will be cleaned. 

I am waiting for @cpsievert to look into this at **sass** level before doing anything on **rmarkdown** side.

**Comment by cpsievert** [comment]
Thanks for looking into this @cderv, it's due to a recent `{sass}` regression. Feel free to close this and track https://github.com/rstudio/sass/issues/84 instead

**Comment by cderv** [comment]
I added sass in Remote field in c9dcaf174f1b09523d577220c0821468fcfaaba7 so that it gets fixed when user are installing dev version
