### ISSUE TITLE
Wish: Possibility to load cached chunks on which a chunk of interest depends

### ISSUE THREAD

**Issue by ugroempi** [rstudio/rmarkdown#2124]
Thank you for providing RStudio with Rmarkdown. Below you find a wish for a utility in connection with cached chunks: 
Working with Rmarkdown documents, I often want to play with a particular chunk interactively without running the entire document. It is easy to run the entire document up to the chunk in question with the "Run all chunks above" command. If some of the chunks contain lengthy computations, it would be very helpful if there were a "load relevant cached chunks" (or similar) command that would load cached content from the chunks that are listed in the "dependson" chunk option. 

I would expect that other people might also find this useful. Or did I overlook a simple way to achieve what I am looking for?

Thanks and regards,
Ulrike

**Comment by cderv** [comment]
Thanks for opening this feature request. 

In case you don't know, there is `knitr::load_cache()` function that allows you to load object from the cache of a specific chunk. 
See example in https://bookdown.org/yihui/rmarkdown-cookbook/load-cache.html
and also ?knitr::load_cache()

Would this help your usage ? 

I think it could help you load the cache of the relevant chunks. 

>  If some of the chunks contain lengthy computations, it would be very helpful if there were a "load relevant cached chunks" (or similar) command that would load cached content from the chunks that are listed in the "dependson" chunk option.

As you are referring before to "Run all chunks above" , are you wishing for something in the RStudio IDE directly ?

**Comment by ugroempi** [comment]
Thanks for the fast reply, and thanks for the hint to `knitr::load_cache`, which I wasn't aware of. I yesterday found an old blog post that suggests the use of `lazyLoad` on the file names without suffix in the cache directory. And yes, indeed I was looking for something within the RStudio IDE directly, because the steps for loading the files seem like something that distracts me from my actual intentions and that can be easily delegated to the IDE.

**Comment by cderv** [comment]
> And yes, indeed I was looking for something within the RStudio IDE directly, because the steps for loading the files seem like something that distracts me from my actual intentions and that can be easily delegated to the IDE.

You then could open a feature request in RStudio repo if there is non already. I don't think the IDE is especially aware of knitr caching for now. Maybe something could be done in the future.
