### ISSUE TITLE
Automatic link creation breaks manually created link

### ISSUE THREAD

**Issue by davidwales** [rstudio/rmarkdown#2130]
## Checklist

Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, self-contained, and reproducible example?
- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?
- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?
- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

## ReprEx

**test.Rmd**

```` r
---
title: R Markdown
title_link: https://rmarkdown.rstudio.com/
output:
  html_document:
    template: custom-template.html
---

# Test

Auto-link generation breaks manually created links.
````

**custom-template.html** Note: The issue also exists if you modify the default template to use links from R Markdown YAML. This is an intentionally minimal template to demonstrate the issue.

```` html
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
</head>

<body>

$if(title)$
$if(title_link)$
<h1><a href="$title_link$">$title$</a></h1>
$else$
<h1>$title$</h1>
$endif$
$endif$

$body$

</body>
</html>
````

## Expected HTML output:

**test.html**

``` html
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
</head>

<body>

<h1><a href="https: rmarkdown.rstudio.com">R Markdown</a></h1>

<div id="test" class="section level1">
<h1>Test</h1>
<p>Auto-link generation breaks manually created links.</p>
</div>

</body>
</html>
```

## Actual HTML output

**test.html**

``` html
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
</head>

<body>

<h1><a href="&lt;a href=" https: rmarkdown.rstudio.com " class="uri">https://rmarkdown.rstudio.com/</a>&quot;&gt;R Markdown</a></h1>

<div id="test" class="section level1">
<h1>Test</h1>
<p>Auto-link generation breaks manually created links.</p>
</div>

</body>
</html>
```

## `xfun::session_info('rmarkdown')`

``` r
> xfun::session_info('rmarkdown')
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.4.1103

Locale:
  LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
  LC_TIME=English_Australia.1252    

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.0.3    grDevices_4.0.3   highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2   
  knitr_1.33        magrittr_2.0.1    markdown_1.1      methods_4.0.3     mime_0.10         rlang_0.4.11      rmarkdown_2.7.13  stats_4.0.3       stringi_1.5.3    
  stringr_1.4.0     tinytex_0.31      tools_4.0.3       utils_4.0.3       xfun_0.22         yaml_2.2.1       

Pandoc version: 2.11.2
```

**Comment by RLesur** [comment]
Hi @davidwales,

There is no issue here, the result you got is the expected one.
This is not a bug, this is a combination of several features :upside_down_face:

The first feature is that metadata variables in a YAML block are parsed as markdown. This is explained in the Pandoc documentation here: https://pandoc.org/MANUAL.html#extension-yaml_metadata_block

> all string scalars will be interpreted as Markdown

The second feature comes from the [`autolink_bare_uris`](https://pandoc.org/MANUAL.html#extension-autolink_bare_uris) extension which

> Makes all absolute URIs into links, even when not surrounded by pointy braces `<...>`.

This combination of features implies that with the following YAML declaration

``` yaml
title_link: https://rmarkdown.rstudio.com/
```

the value of the `title_link` metadata variable is `<a href="https://rmarkdown.rstudio.com" class="uri">https://rmarkdown.rstudio.com/</a>`.

The first solution is to disable the `autolink_bare_uris` extension like that:

    ---
    title: R Markdown
    title_link: https://rmarkdown.rstudio.com/
    output:
      html_document:
        template: custom-template.html
        md_extensions: "-autolink_bare_uris"
    ---
    
    # Test
    
    Auto-link generation breaks manually created links.

Another solution is to pass the `title_link` variable as a CLI argument (it will not be parsed as markdown):

    ---
    title: R Markdown
    output:
      html_document:
        template: custom-template.html
        pandoc_args: ["-M", "title_link=https://rmarkdown.rstudio.com/"]
    ---
    
    # Test
    
    Auto-link generation breaks manually created links.

**Comment by davidwales** [comment]
Ahh! That makes a lot of sense. Thank you! My other workaround was to avoid specifying the protocol in the YAML, which prevented it being picked up by the autolinker, and to hardcode the protocol in the template:

**test.Rmd**

``` rmarkdown
---
title: "rmarkdown.rstudio.com"
output:
  html_document:
    template: custom-template.html
---

# Test

Auto-link generation breaks manually created links.
```

**custom-template.html**

``` html
<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8" />
</head>

<body>

$if(title)$
$if(title_link)$
<h1><a href="https://$title_link$">$title$</a></h1>
$else$
<h1>$title$</h1>
$endif$
$endif$

$body$

</body>
</html>
```

This worked, but feels like a bit of a hack. I might switch to just using Markdown links in the YAML as suggested:
`title: "[R Markdown](https://rmarkdown.rstudio.com/)"`

(The title was just for the ReprEx. My actual use case is adding all my organisation's social media links to a report, so I'm using a YAML variable for each.)
