### ISSUE TITLE
I have managed myself to hack some template as I explain below. However, it would be great if this small modification could be included in the beamer_presentation.

### ISSUE THREAD

**Issue by nithinmkp** [rstudio/rmarkdown#2133]
I have used your technique to hack short title. But am not able to do so for short authors. Say i have 4 authors. Could you provide any help?

**Comment by cderv** [comment]
Hi @nithinmkp 

Can you follow the issue guide https://yihui.org/issue/ ? 
Good practice are explained in the text you deleted when you opened the issue. 

For general question on How-To with **rmarkdown**, please ask first on Q&A website: https://yihui.org/issue/#got-a-question

Thanks you.

**Comment by cderv** [comment]
Our last comment did not get any answer. It is heard to help you without some example to work on. 

Since then you may have found an answer. I'll close this. But feel free to reopen and add information if not. Thank you !
