### ISSUE TITLE
convert_ipynb : conversion of `$..$` is not workable but `$$..$$` workable

### ISSUE THREAD

**Issue by englianhu** [rstudio/rmarkdown#2138]
> Great! Please feel free to let me know if you run into any other problems. You are the first person to my knowledge who has actually used this function for real, so I really appreciate your feedback :)

*_Originally posted by @yihui in https://github.com/rstudio/rmarkdown/issues/1925#issuecomment-712996021_*

---

`Part 1` and `Part 2` from [Overview of Advanced Methods of Reinforcement Learning in Finance (An R Markdown document converted from ‘./data/QED_DJI_calibration_Coursera_course_4.ipynb’)](https://rpubs.com/englianhu/QED_DJI_calibration_Coursera_course_4ipynb) shows the conversion of `$..$` is not workable but `$$..$$` workable, kindly look into it?

Reference : 

- [Convert a Jupyter/IPython notebook to an R Markdown document](https://rmarkdown.rstudio.com/docs/reference/convert_ipynb.html)
- [Typesetting Math using MathJax for IPython Notebook Web page](https://stackoverflow.com/a/28809385/3806250)

**Comment by yihui** [comment]
You have been reminded in #2135 to provide a minimal reproducible example when reporting issues. Please do not ignore the reminder or the issue guide. Thanks!

**Comment by cderv** [comment]
Unfortunately we don't have a reproducible example to work with. It has been some time now so I'll close this. 

Please reopen if there is still something to look into. Provide a `.ipynb` file which creates the issue will be helpful for us. Thank you !
