### ISSUE TITLE
citations not formatted and a reference list not inserted during standard pdf output

### ISSUE THREAD

**Issue by ReedMerrill** [rstudio/rmarkdown#2148]
When trying to knit a standard rmarkdown pdf file with references I get warnings such as `[WARNING] Citeproc: citation erikson1971 not found` for every citation key entered in the Rmd file. In the output file the citations are not formatted and a reference list is not appended. I have verified that the citation keys in the bib file match those used in the rmarkdown file. I am using Zotero to generate the references.bib file. I have attached my Rmd file, my complete references.bib file, for reproducibility and the output pdf to illustrate the problem. I am using the latest (but not preview) version of RStudio, R 4.1.0, and rmarkdown 2.8.3 (installed from github).

This is the rmarkdown output that I get for this issue:
```
processing file: lit-review-ch-draft.Rmd
  |......................................................................| 100%
  ordinary text without R code


/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS lit-review-ch-draft.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output lit-review-ch-draft.tex --lua-filter /home/reed/R/x86_64-pc-linux-gnu-library/4.1/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/reed/R/x86_64-pc-linux-gnu-library/4.1/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' --citeproc 
output file: lit-review-ch-draft.knit.md

[WARNING] Citeproc: citation erikson1971 not found
[WARNING] Citeproc: citation fowler2016a not found
[WARNING] Citeproc: citation freier2015 not found
[WARNING] Citeproc: citation goldewijk2010 not found
[WARNING] Citeproc: citation kushner1997 not found
[WARNING] Citeproc: citation lucas2021a not found

Output created: lit-review-ch-draft.pdf
```
The output of just `xfun::session_info('rmarkdown')`:
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS, RStudio 1.4.1106

Locale:
  LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
  LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.1.0    grDevices_4.1.0  
  highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.33        magrittr_2.0.1    markdown_1.1     
  methods_4.1.0     mime_0.10         rlang_0.4.11      rmarkdown_2.8.3   stats_4.1.0       stringi_1.6.2    
  stringr_1.4.0     tinytex_0.31      tools_4.1.0       utils_4.1.0       xfun_0.23         yaml_2.2.1       

Pandoc version: 2.11.4
```
Note that when I also have pandoc installed in my OS, and the output of `pandoc --version` is 2.5, which doesn't match the version used by R:
```
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/reed/.pandoc
```
## Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

[rmd-citation-issue-reprex-files.zip](https://github.com/rstudio/rmarkdown/files/6541322/rmd-citation-issue-reprex-files.zip)

**Comment by cderv** [comment]
This is because your reference key in the bibliography file are incorrectly formatted
```
@article{[erikson1971],
```
should be 
```
@article{erikson1971,
```
without the brackets, as you used in Rmd text `@erikson1971`. 

How did you generate the bib file ? As I see Zotero, you may be interested in the new Visual Editor mode in RStudio IDE : https://rstudio.github.io/visual-markdown-editing/#/citations?id=citations-from-zotero

**Comment by ReedMerrill** [comment]
@cderv Thanks! Fixing the bib formatting stopped the issue. The problem was with an add-on I'm using in Zotero.

I'll check out the RStudio visual editor, sounds cool. I usually write in Atom or RStudio and then knit from RStudio.
