### ISSUE TITLE
Lua filters broken since v2.8

### ISSUE THREAD

**Issue by rfaelens** [rstudio/rmarkdown#2149]
A bug got introduced in v2.8:
https://github.com/rstudio/rmarkdown/blob/e340d757943cc9ec956aac41e61b0e42ffb64f58/R/render.R#L903

As `input` is a named list, `dirname(input)` fails.

**Comment by cderv** [comment]
Thanks for the report. I'll look closer, it seems indeed there is something not right in this part when `file_scope` option is used. 

Are you using this `file_scope` option with a specific format ? It is not activated by default. So this part of code should run in specific case only. 

Also, why do you mention Lua filters ? This part is not related to Lua filter specifically. 

I just want to be sure we fix the correct bug you found. Thanks!

**Comment by cderv** [comment]
@rfaelens thanks for the report. This part of the code you link to is now fixed. 

As I am not seeing the direct relation with Lua filters, I may have missed something. 
Please open a new issue with some details if I did. Thanks !
