### ISSUE TITLE
[FR] Display more columns in inline output.

### ISSUE THREAD

**Issue by tomasrei** [rstudio/rmarkdown#2155]
I don't think there is an option to change the number of columns displayed for when you have the chunk output set to **inline**. As you can tell from the screenshot below, it would make better sense to display the remaining 3 columns instead of having to click on the arrow to scroll to the right. 

![output](https://user-images.githubusercontent.com/50247285/120622919-88251180-c45f-11eb-8e79-2225d57fa2dc.jpg)

**Comment by tomasrei** [comment]
Nevermind. I finally found it. Just put ````cols.print=12````, in the options or whatever number you want.

**Comment by cderv** [comment]
For reference, this is documented in the R Markdown 
Definitive Guide https://bookdown.org/yihui/rmarkdown/html-document.html#paged-printing
