### ISSUE TITLE
Unexpected line break for Rmarkdown Word in Chinese

### ISSUE THREAD

**Issue by sammo3182** [rstudio/rmarkdown#2166]
When I compile a rmd in Chinese into MS Word file, the lines are no longer combined into a paragraph if they are (together) longer than a line in the output file but showing as separate lines.
The issue occurred very recently, and that is not a problem for HTML files. 
I illustrate the issue with the following code and attach the output file.
[template_temp.docx](https://github.com/rstudio/rmarkdown/files/6634734/template_temp.docx)

```rmarkdown
---
title: "Untitled"
output: word_document
---


正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。

正文正文正文正文正文正文。
正文正文。
正文。
```

I'm using the dev version of rmarkdown.

```r
> xfun::session_info('rmarkdown')
R Under development (unstable) (2021-05-17 r80314)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.5.95

Locale:
  LC_COLLATE=Chinese (Simplified)_China.936 
  LC_CTYPE=Chinese (Simplified)_China.936   
  LC_MONETARY=Chinese (Simplified)_China.936
  LC_NUMERIC=C                              
  LC_TIME=Chinese (Simplified)_China.936    
system code page: 65001

Package version:
  base64enc_0.1.3    cli_2.5.0          digest_0.6.27     
  ellipsis_0.3.2     evaluate_0.14      glue_1.4.2        
  graphics_4.2.0     grDevices_4.2.0    highr_0.9         
  htmltools_0.5.1.1  jsonlite_1.7.2     knitr_1.33        
  lifecycle_1.0.0    magrittr_2.0.1     markdown_1.1      
  methods_4.2.0      mime_0.10          rlang_0.4.11      
  rmarkdown_2.8.6    stats_4.2.0        stringi_1.6.2     
  stringr_1.4.0.9000 tinytex_0.32.2     tools_4.2.0       
  utils_4.2.0        vctrs_0.3.8        withr_2.4.2       
  xfun_0.23          yaml_2.2.1        

Pandoc version: 2.11.4
```

**Comment by cderv** [comment]
Hi @sammo3182, 

Can you just help me see what is the expected result you want ? The same as in the source ? 

FWIW, in Pandoc's Markdown, going to new line in the source file will not mean it will be a new line in the output. Two spaces at the end of the line must be added for a line break in a paragraph (https://pandoc.org/MANUAL.html#paragraphs) 

> A paragraph is one or more lines of text followed by one or more blank lines. Newlines are treated as spaces, so you can reflow your paragraphs as you like. If you need a hard line break, put two or more spaces at the end of a line.

I am surprised it was working for you before (unless those trailing spaces has been removed somehow in the meantime). That is why I am not sure to have fully understand. 

Thanks

**Comment by sammo3182** [comment]
Hi Christophe, what I tried to illustrate with the attached example aimed to show that the markdown function you discussed not work for Chinese, although it was. What I wanted was that, no matter how long the lines are, rmarkdown combines them into a paragraph as long as I didn't insert a blank line or two-spaces. What I got from these codes below though is like this:

When the sentences are short, they are combined into one line/pagaraph:

Input: 

```rmarkdown
正文正文正文正文正文正文。
正文正文。
正文。
```

Output:

```
正文正文正文正文正文正文。正文正文。正文。
```

But when the sentences are longer, they will stay in separate lines rather than combined into a paragraph.

Input: 

```rmarkdown
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
```

Output:

```
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
```

What I want:

```rmarkdown
正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文正文。
```

I tried in the html format, it performs just as I wanted. But it does not work for the Word output since recently. Hope I explained my issue clearly. As a scholar relying on rmarkdown to do almost everything and 90% are in Word files, I really hope this bug could be fixed soon!🙏🙏🙏

**Comment by cderv** [comment]
When I tried the above, I get this into the docx file 
![image](https://user-images.githubusercontent.com/6791940/121922786-8fd79680-cd3a-11eb-9cc9-e277c6a1df6e.png)

If I show the mark for paragraph I can see that the 3 pieces are in the same paragraph. Not several. You see the dot for the space then the paragraph mark only at the end. If I reduce font size, you see this goes on on less line. Mainly because the word is not broken in the middle by Word I believe

![image](https://user-images.githubusercontent.com/6791940/121924742-75062180-cd3c-11eb-8e5d-d3fe77dd6ea5.png)


I don't think this is related to rmarkdown. You should try to write this in a `.md` file and run at command line
````
pandoc -t docx -o test.docx test.md
```

If you get the same result then this is from Pandoc. You can try your old pandoc version too to see if that changed in time. However, I check quickly it since Pandoc 2.1 it seems to work that way. I can't reproduce the old behavior you are describing.

**Comment by sammo3182** [comment]
Thank you for helping me with this! Although the above answer did not solve the problem but gave me a critical clue. You are absolutely right: this is not an error related to rmarkdown---it relates to MS Word. I consistently got break lines, even if I shrank the font size and saw the breaking point was the dot (a space sign). To solve it is actually too easy to be believed: one just needs to insert a space in a random position in the output word file (the docx file given by rendering the rmd or md file). Everything looks fine then. Here as I recorded.
