### ISSUE TITLE
Pandoc error glyphicons does not exist

### ISSUE THREAD

**Issue by ygoltrant** [rstudio/rmarkdown#2167]
Hi !

When I knit my Rmd file since I upgraded my system (to Ubuntu 21.04, with R version 4.1.0 (2021-05-18)), I got this error :

`pandoc: /usr/lib/R/site-library/rmarkdown/rmd/h/bootstrap/css/../fonts/glyphicons-halflings-regular.eot: openBinaryFile: does not exist (No such file or directory)
`

Do you have any idea on what's wrong and what to do ? It's happening even on a very simple html_document.

For info :
```r
> xfun::session_info('rmarkdown')
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 21.04, RStudio 1.4.1103

Locale:
  LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
  LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   digest_0.6.25     evaluate_0.14     glue_1.4.1        graphics_4.1.0    grDevices_4.1.0   highr_0.8        
  htmltools_0.5.1.1 jsonlite_1.6.1    knitr_1.33        magrittr_1.5      markdown_1.1      methods_4.1.0     mime_0.9         
  rlang_0.4.10      rmarkdown_2.6     stats_4.1.0       stringi_1.5.3     stringr_1.4.0     tinytex_0.29      tools_4.1.0      
  utils_4.1.0       xfun_0.23         yaml_2.2.1       

Pandoc version: 2.11.2
```

**Comment by cderv** [comment]
Can you try again after having updated you R package ? 

I see you are using **rmarkdown** 2.6 and 2.8 is now out. This may be something fixed already - I don't remember. 
Can you update and retry ? 

Also, sharing an example file would help. Does it happens with the template Rmd you get when creating a new Rmd in RStudio IDE ? 

I don't have Ubuntu 21.04 but I tried on 20.04 and I cant reproduce this. 

Thanks

**Comment by ygoltrant** [comment]
Thanks for the quick reply ! It's all working now.

For the explanation : Checking updates told me all was fine. I nonetheless tried to (re)install rmarkdown, and now I got rmarkdown 2.8. So I guess I encountered a problem during the upgrade which messed up with the package updates.

I'm sorry for the annoyance.
I'm gonna update this way all my packages to be sure all's fine
