### ISSUE TITLE
inline code

### ISSUE THREAD

**Issue by Liripo** [rstudio/rmarkdown#2171]
```r
---
title: "Untitled"
output: pdf_document
---

`r pi` `r "a"` `r print("a")`
```
when I knitr the above rmd, Igot the pdf.The last "a" not print.
![image](https://user-images.githubusercontent.com/54770415/122746596-bf4b4d80-d2bc-11eb-9fcb-ad95fb5d61ea.png)
<details>
<summary>xfun::session_info("rmarkdown")</summary>
```r
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS, RStudio 1.4.1106

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
  LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
  LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14    
  glue_1.4.2        graphics_4.1.0    grDevices_4.1.0  
  highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2   
  knitr_1.33        magrittr_2.0.1    markdown_1.1     
  methods_4.1.0     mime_0.10         rlang_0.4.11     
  rmarkdown_2.8     stats_4.1.0       stringi_1.6.2    
  stringr_1.4.0     tinytex_0.31      tools_4.1.0      
  utils_4.1.0       xfun_0.23         yaml_2.2.1       

Pandoc version: 2.11.4
```
</details>

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [ x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [ ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by yihui** [comment]
That's because `print(x)` (usually) returns `invisible(x)` while printing the value to the console as a _side effect_, and **knitr** will not render invisible inline values. More on this: https://yihui.org/en/2017/06/top-level-r-expressions/ Thanks for the report anyway!
