### ISSUE TITLE
.Rmd files will occasionally not save

### ISSUE THREAD

**Issue by ayushnoori** [rstudio/rmarkdown#2174]
Hi there, 

I am a frequent user of markdown documents and appreciate the convenient organization of code and documentation which they facilitate. However, after upgrading to R 4.1.0, I have recently encountered an issue with saving `.Rmd` files.

Occasionally (with no discernable pattern or warning), I will be unable to save the markdown file I am working on in RStudio. Pressing `CTRL + S` or File > Save in the RStudio does not save the file (the file name at the top remains in blue font with an asterisk). When this occurs, I have noticed that pressing `CTRL + Enter` does not execute the current line of the markdown file in the console; rather, I have to manually copy the line to the console.

After I notice that the file is not saving, I have no choice but to close the RStudio session, re-open my project, and re-execute the code chunks up to where I was working on. When I re-open the project, the markdown file is able to be saved again by pressing `CTRL + S`, and any changes made in the interim are usually preserved (i.e., when I open the project, the file name at the top is in blue font w/ asterisk), with my changes unsaved but present.

As this issue is with the IDE, not sure how to include a reproducible example. Please see my `xfun::session_info('rmarkdown')` output below.

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.4.1106

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2        graphics_4.1.0   
  grDevices_4.1.0   highr_0.9         htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.33       
  magrittr_2.0.1    markdown_1.1      methods_4.1.0     mime_0.11         rlang_0.4.11     
  rmarkdown_2.9     stats_4.1.0       stringi_1.6.2     stringr_1.4.0     tinytex_0.32     
  tools_4.1.0       utils_4.1.0       xfun_0.23         yaml_2.2.1       

Pandoc version: 2.11.4
```

Thanks for your help!

**Comment by ayushnoori** [comment]
Might also be worth mentioning that I am editing the `.Rmd` files in visual mode.

**Comment by cderv** [comment]
This is something happening with IDE it seems. Can you check with last available version 1.4.1717 ? 

https://www.rstudio.com/products/rstudio/download/#download

And maybe with last daily ? 

https://dailies.rstudio.com

Thanks !

**Comment by ayushnoori** [comment]
Just installed version 1.4.1717 "Juliet Rose," if I still receive the error will try with the latest daily and report back. Thanks, @cderv!

**Comment by cderv** [comment]
Great. If you still have an issue with last daily, this would be something to report in Rstudio IDE github repo with reproducible steps for them to look into.
