### ISSUE TITLE
learnr tutorials fail to run with dev. rmarkdown

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#2182]
With the development version of `rmarkdown`, installed via `remotes::install_github("rstudio/rmarkdown")`), I'm seeing that `learnr` tutorials fail to start:

```
> library(learnr)
> run_tutorial("ex-data-basics", package = "learnr")
Warning: $ operator is invalid for atomic vectors
Warning: $ operator is invalid for atomic vectors
Warning: $ operator is invalid for atomic vectors
Warning: $ operator is invalid for atomic vectors


processing file: ex-data-basics.Rmd
  |........                                                                                                                                                                              |   4%
  ordinary text without R code

  |................                                                                                                                                                                      |   9%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |........................                                                                                                                                                              |  13%
  ordinary text without R code

  |................................                                                                                                                                                      |  17%
label: mpg-setup
Quitting from lines 44-45 (ex-data-basics.Rmd) 
Error: Tutorial exercises require the use of 'runtime: shiny_prerendered'
```

Is this expected?

```
> xfun::session_info("rmarkdown")
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4, RStudio 1.4.1725

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3      digest_0.6.27        evaluate_0.14        fastmap_1.1.0       
  glue_1.4.2           graphics_4.1.0       grDevices_4.1.0      highr_0.9           
  htmltools_0.5.1.9006 jsonlite_1.7.2       knitr_1.33           magrittr_2.0.1      
  markdown_1.1         methods_4.1.0        mime_0.11            rlang_0.4.11        
  rmarkdown_2.9.2      stats_4.1.0          stringi_1.6.2        stringr_1.4.0       
  tinytex_0.32         tools_4.1.0          utils_4.1.0          xfun_0.24           
  yaml_2.2.1          

Pandoc version: 2.14.0.3
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Thanks @kevinushey for the report. 

I don't think this is expected, and I confirm this is due to a recent change in the dev version - bab481aa016f38a94d08f4c03284e9273804b3d4

This change seems to be about `runtime` for shiny prerendered document which has now been set to `shinyrmd` instead of `shiny_prerendered`. Issue is `learnr` does know about `shinyrmd` yet. 

https://github.com/rstudio/learnr/blob/357e7f070084301e85bb24e5c4167fafbd2a8f40/R/knitr-hooks.R#L10-L12
````r
is_shiny_prerendered_active <- function() {
    identical(knitr::opts_knit$get("rmarkdown.runtime"),"shiny_prerendered")
  }
````

@jjallaire it would be interesting to discuss more about new `shinyrmd` runtime and new `server` yaml key you introduced so that we can plan where all this needs to be supported. 

For this specific issue here, I think it should be **learnr** which needs to know about the new `shinyrmd` runtime. Do we agree on this ?

**Comment by jjallaire** [comment]
I was actually able to fix this this with a commit to rmarkdown: https://github.com/rstudio/rmarkdown/commit/d9c3227d480a2701ff8b404a8f2e1056354c4869

Some history on this:

1) We originally introduced `runtime: shiny_prerendered` specifically for learnr tutorials (to provide a shiny integration mode that didn't require a full re-render of the document per-client).

2) Once we realized that this might be a generally useful way to create shiny Rmds we introduced the alias `shinyrmd` as a slightly nicer syntax (along with the ability to provide server code in `server.R` and name the Rmd `ui.R` and have it automatically recognized by `rmarkdown::run`).

3) All of this also now works w/ quarto. We also specifically wanted to introduce a place for server options in the quarto scenario. We didn't love that `shinyrmd` included "rmd" (when your source file might be a "qmd"). So I recently added the option to do either of the following:

    ```
    server: shiny
    ```

    ```
    server:
       type: shiny
    ```

To make this work I had to make changes to RStudio, `rmarkdown`, `rsconnect`, `renv`, and `packrat`. This *should* all be working as expected now in the development versions of all of those packages. With this change to rmarkdown, any other package like `learnr` that is specifically looking for `shiny_prerendered` in  `rmarkdown.runtime` within `opts_knit` will now see it.

**Comment by cderv** [comment]
Thank you for the context! All this may require an update in documentation. 

> Otherwise, it would mean having runtime value set to shiny_prerendered, even with a runtime: shinyrmd, or server: shiny YAML key, for backward compatibility as this is used in rmarkdown.runtime knitr's option.

When I mention this above, d9c3227 was indeed the other fix I had in mind. It is the simpler one - thanks for the commit! 

> This should all be working as expected now in the development versions of all of those packages.

Awesome ! Thank you. `server: shiny` is a nice way of setting it IMO. 

@kevinushey, I close this issue as this is now fixed. Thanks again for the report !
