### ISSUE TITLE
[FR] Relay conditions from callr processes

### ISSUE THREAD

**Issue by fkohrt** [rstudio/rmarkdown#2188]
Conditions that are signalled from within **callr** processes do not show up in R Markdown logs during the knitting process if setting the chunk option `message = FALSE`:

``````Rmd
---
title: "trouble relaying callr messages to R Markdown logs"
output: html_document
---

```{r print_main, message = FALSE}
message("printed message in the main process")
```

```{r print_external, message = FALSE}
callr::r(function() message("external printed message"))
```
``````

This would be very useful, however, as the **targets** package uses **callr** to enhance reproducibility. **targets** provides a caching mechanism that makes it very useful for long running functions. But if these functions signal their progress via `message()` it is not displayed to the user while knitting. Therefore I propose to relay conditions from **callr** processes.

Relevant **targets** discussion: ropensci/targets#559

**Comment by atusy** [comment]
I think `callr::r` will not message even on console or chunk wirh `message=TRUE`.
The document of `callr::r` returns message as stderr and can be saved to a file.
I think you should use that feature.

``` r
# Without catching stderr
    callr::r(function() message("external printed message"))
#> NULL
    
# With catching stderr
msgfile <- tempfile()
callr::r(function() message("external printed message"), stderr = msgfile)
#> NULL
message(readLines(msgfile))
#> external printed message
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In case of targets package, trick will be something like

``` r
callr_function <- function(...) {
    msgfile <- tempfile()
    result <- callr::r(function() message("external printed message"), stderr = msgfile)
    message(readLines(msgfile))
    return(result)
}
```

**Comment by fkohrt** [comment]
Printing to a file is not always as nice as seeing the progress right away, but definitely better than nothing. Thanks!

**Comment by cderv** [comment]
Note that `callr::r()` as a `show` argument which default to `FALSE`. 

Setting it to `TRUE` will show what is usually show in console output if you were running interactively:

``` r
callr::r(function() message("external printed message"), show = TRUE)
#> external printed message
#> NULL
```

However, this does not help with `message = FALSE` or `message = TRUE` because condition handling are happening in the background process. 

Sharing as an alternative for when you want to see what happens. Writing to file is for now the best option for logging the stderr.
