### ISSUE TITLE
rmarkdown/rstudio: no pdf viewer window with RStudio on M1 Mac

### ISSUE THREAD

**Issue by zjl19902003** [rstudio/rmarkdown#2189]
Hello. My rmarkdown file does not produce the rstudio-pdf-viewer after running on my M1 Macbook Air. I ran the same file on intel iMac and the viewer window will pop up. I checked the global settings, and made sure rstudio is up-to-date.

The codes will run and generate the pdf output with no error. The problem is the pdf viewer does not pop out.

Any help? Thanks!

**Comment by cderv** [comment]
Hi @zjl19902003, 

I believe you are mentioning the PDF viewer that RStudio IDE would open for you. Is that right ? 

In this case, this would be a RStudio IDE issue. 

**rmarkdown** does not handle the opening of the PDF for you. The function `rmarkdown::render()` will only output the path of the resulting PDF file.

**Comment by cderv** [comment]
> I believe you are mentioning the PDF viewer that RStudio IDE would open for you. Is that right ?

Unfortunately no answer. So I assume you were talking about the RSTUDIO feature to open PDF. 

If this is still an issue, please open an issue in RStudio IDE repo. Thank you !
