### ISSUE TITLE
Why Rstudio change my file by itself?

### ISSUE THREAD

**Issue by ajeep8** [rstudio/rmarkdown#2207]
My system is Ubuntu 20, and using Rstudio Server Open Source License.

## Chinese image filename

When I open a md/Rmd file edited by Typora or other markdown editor by Rstudio, I just save, the image link with Chinese image filename change to UTF-8 code, and Rstudio say: (No image at path %E4......%BD.png)

```
![](中文图片名.png)
```
Rstudio change to:

```
![](%E4......%BD.png)
```

## soft line break

Sometime I want the soft line break like:

```
I say:
I want to go.
```

when I save file in Rstudio, it change to:

```
I say: I want to go.
```

Even I directly open the soft-line-breaked md file and knit to docx(the source md file remain soft line break), the output docx become 1 line. Typora export to docx will remain soft line break.

## others

I always use one space between list number and text like:

```
1. abc
2. bbc
``` 
When Rstudio save my file, it become 2 space.

How can I edit file by myself, stop Rstudio change my file by itself?

**Comment by cderv** [comment]
Hi, 

This is the repository about **rmarkdown** R package. I believe you have issue with RStudio IDE. 
This would be reported instead in https://github.com/rstudio/rstudio following there guide : https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports

This could also be asked on https://community.rstudio.com/c/rstudio-ide/9 

That being said, I am just sharing a it on something: Are you using the new visual editor ? 
* https://blog.rstudio.com/2020/09/30/rstudio-v1-4-preview-visual-markdown-editing/
* https://rstudio.github.io/visual-markdown-editing/

When writing and switching in visual editor there could be some rewriting of the source based on the content in the visual editor. See global option: https://rstudio.github.io/visual-markdown-editing/options.html?q=canonica#global-options

This visual markdown editor has an option to always use canonical mode in source and in visual editor when using both: 
https://rstudio.github.io/visual-markdown-editing/markdown.html?q=canonic#canonical-mode

This may not be linked at all. 

In any case, I won't be able to help further. You should ask on the community or open a reproducible bug report on the rstudio IDE Github repo. 

Thanks.
