### ISSUE TITLE
A very wired problem: error message "! Extra }, or forgotten \endgroup.  l.50 } "

### ISSUE THREAD

**Issue by crotoc** [rstudio/rmarkdown#2208]
I encounter a problem that I have a rmd file (saved as scRNA.runHarmony.rmd) with content like this:

![image](https://user-images.githubusercontent.com/12446554/131719489-c500ff0f-52bf-4ea6-b0ca-d5eac3b8f79c.png)

Sorry I want to attach a file but can not find the right way to do it.

I tried to render this file using command like this:

`R -e 'library(rmarkdown);render(input="/fs0/chenr6/chenr6/myscript/Rscripts/rmd/singlecell/scRNA.runHarmony.rmd",output_file="all.cocluster.nofilter.pdf")'
`

_It failed with the message:

processing file: scRNA.runHarmony.rmd
  |...................................                                   |  50%
  ordinary text without R code

  |......................................................................| 100%
label: unnamed-chunk-1 (with options) 
List of 1
 $ eval: logi FALSE

output file: scRNA.runHarmony.knit.md

/fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/bin/pandoc +RTS -K512m -RTS scRNA.runHarmony.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output all.cocluster.nofilter.tex --lua-fi
lter /fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --s
elf-contained --table-of-contents --toc-depth 2 --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' 
! Extra }, or forgotten \endgroup.
l.50 }

Error: LaTeX failed to compile all.cocluster.nofilter.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See all.cocluster.nofilter.log for more info.
Execution halted_

However, when I run the command with a modified output file name like this:

`R -e 'library(rmarkdown);render(input="/fs0/chenr6/chenr6/myscript/Rscripts/rmd/singlecell/scRNA.runHarmony.rmd",output_file="all.cocluster_nofilter.pdf")'
`
It will success with msg:

_processing file: scRNA.runHarmony.rmd
  |...................................                                   |  50%
  ordinary text without R code

  |......................................................................| 100%
label: unnamed-chunk-1 (with options) 
List of 1
 $ eval: logi FALSE

output file: scRNA.runHarmony.knit.md

/fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/bin/pandoc +RTS -K512m -RTS scRNA.runHarmony.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output all.cocluster_nofilter.tex --lua-filter /fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --table-of-contents --toc-depth 2 --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' 

Output created: all.cocluster_nofilter.pdf_

The only difference is I replace the dot with underscore and I tried a lot of output file name and only the dot one failed. Please help me address the problem. Thanks!

SessionInfo:

_R version 4.1.0 (2021-05-18)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /fs0/chenr6/chenr6/opt/condaEnv/AccreLibEnv/lib/libopenblasp-r0.3.15.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_2.10

loaded via a namespace (and not attached):
[1] compiler_4.1.0  fastmap_1.1.0   tools_4.1.0     htmltools_0.5.2
[5] knitr_1.33      xfun_0.25       digest_0.6.27   rlang_0.4.11   
[9] evaluate_0.14_

[runHarmony.zip](https://github.com/rstudio/rmarkdown/files/7093700/runHarmony.zip)

**Comment by cderv** [comment]
It would be great if could attach the file. You can do it using a zip file in the Github issue. 
Otherwise, uploading online like in Github or as a Gist (https://gist.github.com/) is another option. 

This would help us look at this. 

If you want to dig further, you can set `keep_tex: true` under `pdf_document` as argument so that you have the tex file available. Then we can compare both : the one working and the other which is not to understand. 

I don't remember exactly if this something we can handle or if LaTeX does not support file name with dots except for extensions 🤔

**Comment by crotoc** [comment]
Thanks! I have upload the file. I will try to get the tex files and give a shot.

**Comment by crotoc** [comment]
I figured that only "all.cocluster.nofilter.pdf" doen't work. "all.cocluster.nofilte.pdf", "all.nofilter.pdf" and any other names worked.... How wired!

**Comment by crotoc** [comment]
The tex files have no difference. Maybe it's a bug of render function?

**Comment by cderv** [comment]
> The tex files have no difference. Maybe it's a bug of render function?

The error you get comes from LaTeX to PDF conversion. Rmarkdown works like this: 
1. Rmd -> md using knitr
1. md -> tex using Pandoc
1. tex -> pdf using LaTeX

I believe your error happens during step 3. This means that something is not supported during the LaTeX conversion. If the file are the same, I really don't know what happens. I'll check the file you sent

**Comment by crotoc** [comment]
> > The tex files have no difference. Maybe it's a bug of render function?
> 
> The error you get comes from LaTeX to PDF conversion. Rmarkdown works like this:
> 
> 1. Rmd -> md using knitr
> 2. md -> tex using Pandoc
> 3. tex -> pdf using LaTeX
> 
> I believe your error happens during step 3. This means that something is not supported during the LaTeX conversion. If the file are the same, I really don't know what happens. I'll check the file you sent

Thanks! It's really strange. Not in hurry because I can change the name of output file. If you are avaiable, please help have a check. I am wrting some pipeline so avoiding this kind of error is important. Appreciate!

**Comment by cderv** [comment]
I can't reproduce the issue. I tried rendering with the file provided but it did not create errors for me.

**Comment by crotoc** [comment]
Thanks @cderv! I think I can try to debug further at my end. I will update if I can repeat it more reliably. Appreciate your help very much!
