### ISSUE TITLE
Problem with toc ids, with non latin headers 

### ISSUE THREAD

**Issue by gd047** [rstudio/rmarkdown#221]
This is an example of a table of contents created, using `toc= yes` in yaml. As you can see the ids contain only `_` (as many as the spaces in the header) which is obviously a problem. Is there a solution?

<div id="TOC">

<ul>
<li><a href="#--.">Γενικά στοιχεία δείγματος.</a></li>
<li><a href="#--.">Περιγραφικά Στατιστικά Στοιχεία.</a><ul>
<li><a href="#------.">Στατιστικά των αναθεωρημένων τιμών μελέτης και προσφοράς.</a></li>
<li><a href="#-------.">Διάγραμμα Παράλληλων Συντεταγμένων Αναθ/νων Τιμών Μελέτης και Προσφοράς.</a></li>
<li><a href="#-------heatmaps.">Σύγκριση τιμών μεταξύ των συμβάσεων μέσω Θερμοχαρτών (Heatmaps).</a></li>
</ul></li>
<li><a href="#-----">Έλεγχοι υποθέσεων - Διαστήματα εμπιστοσύνης</a><ul>
<li><a href="#------.">Υπόθεση κανονικά κατανεμημένων τιμών Μελέτης και Προσφοράς.</a></li>
<li><a href="#--------">Διάστημα Εμπιστοσύνης των μέσων Αναθ/νων τιμών Μελέτης και Προσφοράς</a></li>
<li><a href="#-----">Διάστημα Εμπιστοσύνης του μέσου Ποσοστού Έκπτωσης</a></li>
</ul></li>
<li><a href="#-----1530">Στοιχεία Χρονοσειράς Συντελεστή Αναθεώρησης ΟΔΟ-1530</a></li>
</ul>

</div>

**Comment by gd047** [comment]
Has anything changed regarding the aforementioned, with the release of R Markdown v0.9.5?

**Comment by yihui** [comment]
You can assign your own identifiers using `{#your-identifier}` after the section heading, e.g.

    # Γενικά στοιχεία δείγματος {#whatever}
