### ISSUE TITLE
Use the new Github citation feature 

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2210]
Documented here: 
* https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files
* https://citation-file-format.github.io/

`inst/CITATION` are already recognized and GIthub will link to them directly from the home page
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files#other-citation-files

However, if it is possible to convert from R citation file to `CITATION.cff`, this could allow to offer a more user friendly direct way to get the APA like or bibtex format through the prompte. Using GITHUB action, we could automate any change in the main CITATION file or at each package release.

Also `CITATION.cff` is supported by ZOTERO and browser plugin can pick it up
https://citation-file-format.github.io/#/supported-by-zotero-

**Comment by cderv** [comment]
There is now a ROpensci package to create this file: https://docs.ropensci.org/cffr/

There is a function to create an action that would help keeping such file up to date: https://docs.ropensci.org/cffr/reference/cff_gha_update.html

We could add that easily I guess in our repo

**Comment by cderv** [comment]
@yihui @tracykteal we discussed about this once. I have added an action to create the cff file that Github will pick up. you can see the result in the repo home page. 

We could tweak the current citation as we want, specifically if we want to feature a different reference in the repo homepage. 
**cffr** package contains everything needed for that.

**Comment by yihui** [comment]
Looks good! Thanks!
