### ISSUE TITLE
[FR]: Function returning the output format of an R Markdown document

### ISSUE THREAD

**Issue by maelle** [rstudio/rmarkdown#2213]
The output format of an R Markdown document can be specified in four places

* The document YAML itself;
* A site configuration `_site.yml`;
* `output.yml`
* As argument to a rendering function.

I see the three YAML configurations are merged/combined https://github.com/rstudio/rmarkdown/blob/0af6b3556adf6e393b2da23c66c695724ea7bd2d/R/output_format.R#L493

If I, given an R Markdown document in its location, want to determine its output format, I can copy the logic from that code.

However I was wondering whether it'd make sense for rmarkdown itself to extract and export a function returning the output format (and potentially other options) it deduced?

**Comment by cderv** [comment]
Did you try `rmarkdown::default_output_format()` ? 
https://pkgs.rstudio.com/rmarkdown/reference/default_output_format.html

I believe this is doing what you seek. Is this not working correctly ?

**Comment by maelle** [comment]
Right you mean `resolve_output_format()`? I missed it :woman_facepalming: Thank you!!

**Comment by cderv** [comment]
>Right you mean resolve_output_format()?

No that is another one 
https://pkgs.rstudio.com/rmarkdown/reference/resolve_output_format.html

They differ in the return value I believe, and what you could do with them.
