### ISSUE TITLE
Extra whitespaces/line breaks while plotting this 

### ISSUE THREAD

**Issue by jjyotikataria** [rstudio/rmarkdown#2219]
![image](https://user-images.githubusercontent.com/58770228/133915250-264bb4a5-a199-4e41-a059-05072bcf70d0.png)

Hi @hadley @rekado @zeehio @garrettgman @wch 

Could you please help me in removing this extra line breaks after the plots i.e. before and after the legend box?

The code snippet is as follows:

First chunk takes the plots in a list and prints them in a grid. Second chunk prints the combined legend for all these plots.

```{r hd_umaps, eval=species=="Human",out.width = "600px", echo=FALSE,fig.align='center',results='asis',fig.height=2,fig.width=5,strip.white=TRUE}

p[[j]]<-UMAPPlot(object = data[[j]]) + scale_color_manual(values = cluster.colors[(names(cluster.colors)%in%clusters[[j]])])+ theme(legend.position="bottom",legend.text = element_text(size = 10)) + ggtitle(title_name)  + theme_void() + NoLegend()+ theme(plot.title = element_text(size=8,hjust = 0.5, vjust=0.5))

cowplot::plot_grid(plotlist = p,ncol = 3)
```

```{r hd_legend,eval=species=="Human",out.width = "600px", echo=FALSE,strip.white=TRUE,results='asis',fig.align='center'}
plot(NULL ,xaxt='n',yaxt='n',bty='n',ylab='',xlab='', xlim=0:1, ylim=0:1)
legend("center", ncol=4,legend=names(cluster.colors), pch=16, pt.cex=1, cex=1,col = unname(cluster.colors))

**Comment by hadley** [comment]
@jjyotikataria it's not appropriate to cc'd a bunch of people to get them to help you with your problem. I'd recommending read reading <https://www.tidyverse.org/help/> to learn how to ask questions in a way that's mostly likely to get a helpful answer and then asking on <https://community.rstudio.com>.
