### ISSUE TITLE
Feature request: output `beamer_presentation` with option for `latex_engine`

### ISSUE THREAD

**Issue by Shinoto-github** [rstudio/rmarkdown#223]
knitr works with pdflatex as default, but for CJK scripts etc. xelatex or lualatex is necessary. For the time being, this can be invoked by adding a pandoc option like this: 

```
output: 
  beamer_presentation:
    pandoc_args: '--latex-engine=xelatex'
```

but an option for direct support in Rmarkdown should be easier to write: 

```
latex_engine: xelatex
```

Same for lualatex. 

Thanks for listening.

**Comment by yihui** [comment]
This has been fixed via a213c66ec0951f43994e099d3e5cf7b7d7725b66.
