### ISSUE TITLE
[FR] Interrupted lists are merged into a continuous list

### ISSUE THREAD

**Issue by HossamGhorab** [rstudio/rmarkdown#2235]
# Problem
A list whose numbering continues after interruption is created as:
```
   (@) element 1
   (@) element 2
------interruption----
   (@) element 3
   (@) element 4
```

The problem is when including more than one such list in document, they are treated as a single interrupted list: their numbering is merged. Example:
```
List 1:

   (@) element 1
   (@) element 2
------interruption----
   (@) element 3
   (@) element 4

Some very long paragraphs and code chunks.
List 2:

   (@) element 5
   (@) element 6
```

Interruption is undefined, so the numbering of an list is continuous with that of the previous list. 

# Suggestions
1. As with tabsets, using `(@) {-}` after each interrupted list to may mark it's end, so the numbering of any further list of the same type is independent of it's previous cousin. This approach is simpler than the next.
2. Maybe we can use an ID for each list, where the list ID is placed in the `(@)` itself. Example: 
```
List 1:

   (@1) element 1
   (@1) element 2
------interruption----
   (@1) element 3
   (@1) element 4

Some very long paragraphs and code chunks.
List 2:

   (@2) element 1
   (@2) element 2
```
This may be helpful for overlapping lists, where we might want the numbering of a list to be continuous with a specific list, which might not be the previous one. Example:
```
List 1:

   (@1) element 1
   (@1) element 2

--interruption----
List 2:

   (@2) element 1
   (@2) element 1

---- interruption----

List 1 continuous: 

   (@1) element 3
   (@1) element 4
```

An ID may be anything not only a numeric. 
This approach isn't as simple as the first but may be of use in very limited cases. However, these limited cases may be ubiquitous in some industries or some fields in academia, so you might consider it.

Warmly

**Comment by HossamGhorab** [comment]
Dear @cderv 

No, not yet. I will take your advice & do ask there. Thanks a lot for your understanding.

With gratitude

**Comment by cderv** [comment]
HI @HossamGhorab, 

Is there any news from Pandoc regarding this ? 
Without any change on Pandoc's front, we won't be able to support that I believe.

**Comment by HossamGhorab** [comment]
Dear @cderv ,

Thanks a lot for showing such patience. A posted a [question](https://groups.google.com/g/pandoc-discuss/c/dYjJ2KO_5R0) in the Pandoc discuss group once I read your last reply, but it seems not a very active place to ask. I shall wait for a couple of days, if no answer, I will post an issue on their GitHub repo. 

I will post the updates here. Thanks again.

**Comment by HossamGhorab** [comment]
From John MacFelarne's [response](https://groups.google.com/g/pandoc-discuss/c/dYjJ2KO_5R0):

> No, you can't have two separate example lists in a document. If you use (@foo1) and (@foo2) in example lists, it simply
gives you a way to refer back to these list items later, e.g. "see item (@foo2)."

> LaTeX has a sophisticated mechanism of counters which allow
you to have multiple automatically numbered lists, with
different numbering styles etc. Pandoc's markdown is much
simpler, and I'm not convinced that we should try to
do everything you can do in more complex formats.

It seems like a dead end. The issue may be closed safely.
