### ISSUE TITLE
Math rendering incorrectly on RStudio

### ISSUE THREAD

**Issue by nicholasgyd** [rstudio/rmarkdown#2239]
latex is rendering incorrectly on rmd. No idea how to resolve this - any help is appreciated. 

<img width="569" alt="Screenshot 2021-10-26 at 3 44 54 PM" src="https://user-images.githubusercontent.com/73956295/138832264-1f7f0b5b-1726-4273-9d45-2022eef580e4.png">

Thanks!

**Comment by cderv** [comment]
I retried this and I see no issue (as long as `&` is escaped using backslash). If you found one, please report in the rstudio IDE repo. 

Thank you!
