### ISSUE TITLE
accented characters wrong in pdf file

### ISSUE THREAD

**Issue by JLOlivares** [rstudio/rmarkdown#2240]
[RStudio-error-in-title.txt](https://github.com/rstudio/rmarkdown/files/7419500/RStudio-error-in-title.txt)
This is a simple rmd file produced by the standard template in RStudio. The metadata section includes title and author wuth accented characters.
In RStudio
Version 1.4.1717
© 2009-2021 RStudio, PBC
"Juliet Rose" (df86b69e, 2021-05-24) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

it produces a pdf with proper accents everywhere:
[RStudio-error-in-title.pdf](https://github.com/rstudio/rmarkdown/files/7419549/RStudio-error-in-title.pdf)

If I import this rmd to
RStudio
2021.09.0 Build 351
© 2009-2021 RStudio, PBC
"Ghost Orchid" Release (077589bc, 2021-09-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

The accents in title and author are wrong:
[RStudio-error-in-title-v2.pdf](https://github.com/rstudio/rmarkdown/files/7419562/RStudio-error-in-title-v2.pdf)

Comparing the tex files produced by both RStudios you can see that Version 1.4.1717 places the lines
\title{RStudio error en título}
\author{José Luis Olivares Vázquez}
\date{26/10/2021}
at the end of the tex preamble (right before \begin{document}), but v.2021.09.0 Build 351 places them at the beginning. If I manually move those lines to the end of the preamble and latex the file externally, the pdf is produced with proper accents everywhere.

How can I control in v.2021.09.0 Build 351 the tex output of those lines?

Thanks. José Luis Olivares V.

**Comment by yihui** [comment]
> I received a warning about my TeXLive installation conflicting with TinyTeX, and install_tinytex() did not proceed to modify my PATH environment variable, so I had to manually edit PATH in order to be able to use it in RStudio.

@JLOlivares You shouldn't need to do that if you are using [**tinytex** >= 0.30](https://github.com/yihui/tinytex/releases/tag/v0.30) (v0.30 was released in March this year). The warning has been removed since then.

Since you didn't provide your session info as requested by the issue guide, we don't know your **tinytex** version.
