### ISSUE TITLE
Dark Header Table Formatting in word_document()

### ISSUE THREAD

**Issue by phargarten2** [rstudio/rmarkdown#2242]
Thank you for allowing me to create attractive reports using R markdown. 

As you know, a powerful tool is to create a reference template using **pandoc** and then adjust it [as listed here](https://bookdown.org/yihui/rmarkdown-cookbook/word-template.html) [](https://rmarkdown.rstudio.com/articles_docx.html) . I realize that the different styles in Microsoft Word are utilized by **pandoc** to create finalized reports.  I followed the instructions to adjust the table style to have dark headers (with white text) and a normal body. It looks great in the template:

![image](https://user-images.githubusercontent.com/17706062/139956782-85926ac5-7ba9-44d1-a27c-beda521b0f40.png)

which was created under "Styles"
![image](https://user-images.githubusercontent.com/17706062/139956893-10a69fbd-b2c5-421d-a9c3-142d6131eb27.png)

. However, when I use the template to render the example, the default black text gets applied to the header:

![image](https://user-images.githubusercontent.com/17706062/139956964-476fb6f1-9061-4056-aa04-85e8097b77bd.png)

This is puzzling, as the font color for the header row in the table is "white" yet pandoc renders it using the font color of "automatic", I think. Is this just a weird bug with dark header tables?

Thanks! In the following zip file, the word template, a minimally created R markdown document, and R code to render it  (also pasted below). I also included a word document that consists of what I would expect **pandoc** to create.  In reality, I am using `bookdown::word_document2()`, but I traced the problem to `rmarkdown::word_document()`. 

[dark_header_row_issue_rmarkdown.zip](https://github.com/rstudio/rmarkdown/files/7464225/dark_header_row_issue_rmarkdown.zip)

```{r}
my_word <- function(...){
#  bookdown::word_document2(
    rmarkdown::word_document(
    reference_docx = "word-style-template.docx",
 #   toc = TRUE,
 #   toc_depth = 4,   #DEFAULT Depth of headers to include in table of contents
 #   df_print = "kable",   #using printr
 #   highlight =  "tango",

#    fig_width =  7,  #inches
#   fig_height = 6,  #inches
#    fig_caption = TRUE,
#    mainfont = "Times New Roman",

    keep_md = TRUE,    #keep the markdown file from knitting
#    md_extensions = NULL,    #default
#    pandoc_args = NULL       #default
  )
}

rmarkdown::render(
  input = "work_formatting.Rmd",
  output_format = my_word(),
  clean = FALSE,
  quiet = FALSE
)
```

xfun::session_info("rmarkdown")
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 2021.9.0.351

Locale: LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  bslib_0.3.1      digest_0.6.28    evaluate_0.14    fastmap_1.1.0    fs_1.5.0         glue_1.4.2       graphics_4.1.1   grDevices_4.1.1  highr_0.9        htmltools_0.5.2 
  jquerylib_0.1.4  jsonlite_1.7.2   knitr_1.36.7     magrittr_2.0.1   methods_4.1.1    R6_2.5.1         rappdirs_0.3.3   rlang_0.4.12     rmarkdown_2.11.3 sass_0.4.0       stats_4.1.1     
  stringi_1.7.5    stringr_1.4.0    tinytex_0.34.5   tools_4.1.1      utils_4.1.1      xfun_0.27        yaml_2.2.1      

Pandoc version: 2.14.0.3

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by phargarten2** [comment]
Using the same template, [I found a different problem regarding the formatting of section numbering and header.](https://github.com/rstudio/bookdown/issues/1281) However, I think that the issues are unrelated.

**Comment by cderv** [comment]
Hi @phargarten2 

For context, this is the same as in #1281

However, here you may have found an issue in Pandoc. From the doc you sent, it seems that the correct table style is applied, but the text inside the table get the Compact Paragraph style that overwrites the style you set in the Table style. 
It seems to be a known issue in Pandoc: https://github.com/jgm/pandoc/issues/6670

There is no easy workaround for that as this seems to be a Pandoc issue. However, do you know about the package **flextable** ? https://ardata-fr.github.io/flextable-book/
It can help you create table and style them for word document. Maybe it could help your case.

As with #1281, there is nothing much we can do here but this should be an issue to dealt with in Pandoc directly.

**Comment by phargarten2** [comment]
Thank you. I see that it is indeed a Pandoc issue. I will cite this issue after your comment there. I am aware of **flextable**, but its syntax is different than using **knitr::kable**'s. I would need to learn the unique syntax of **flextable** .

**Comment by cderv** [comment]
Oh yeah rstudio/bookdown#1281 I wasn't paying attention that it was another repo.

**Comment by cderv** [comment]
I am closing this as this is something due to upstream issue. We can't to anything in **rmarkdown** directly. Thanks !
