### ISSUE TITLE
How to flexdashboard save as html?

### ISSUE THREAD

**Issue by Geon27** [rstudio/rmarkdown#2246]
---
title: "LEARNIT"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: spacelab
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
if (!require(pacman)) {install.packages("pacman")
  library(pacman)}
pacman::p_load("flexdashboard","ggplot2","plotly","shiny","plyr","dplyr",
               "plotly","tm")
```

```{r}
# file.choose()
DATA = read.csv("D:/3-1 Rshiny/IMDB-Movie-Data.csv")
```

```{r}
DATA$Genre2 = DATA$Genre

DATA$Genre2=gsub(","," ",DATA$Genre2)

CORPUS=Corpus(VectorSource(DATA$Genre2))
CORPUS_TM = tm_map(CORPUS,removePunctuation)
CORPUS_TM = tm_map(CORPUS_TM, removeNumbers)
CORPUS_TM = tm_map(CORPUS_TM, tolower)

DTM = DocumentTermMatrix(CORPUS_TM)

DTM = as.data.frame(as.matrix(DTM))

DATA = cbind(DATA,DTM)

FIRST_GENRE = c()
for(i in 1:nrow(DATA)){
  FIRST_GENRE[i] = strsplit(as.character(DATA$Genre[i]),",")[[1]][1]
}

DATA$FIRST_GENRE = FIRST_GENRE
# head(DATA)
# names(DATA)
```

탐색적분석 {data-orientation=rows}
==========================

column {data-height=1200}
------------------------
### head
```{r}
head(DATA)
```

Row {data-height{250}
--------------------------------
### name
```{r}
names(DATA)
```

Row {data-height=70}
--------------------------------
### dim
```{r}
dim(DATA)
```

<br>

board1
==========================
Column {.sidebar}
--------------------------

<br>

```{r}
date()
```

```
Learnit Job Class    
Description :

1. 대시보드 만들기      
2. 새로운 평가지표 만들어보기    
3. 그래프 이쁘게 그려보기    
4. 유지보수 잘하기   
```
```{r}
selectInput('type','장르',DATA$FIRST_GENRE, selected = 'action')
numericInput('scoring','평균점수:', 6)
```

Row 
------------------------
### Target Of Dashboard

Row
--------------------------------
### Ratings Gauge

Board 2
==========================

Row {data-height=650}
------------------------ 
### 년도별 영화 매출 추이(장르 선택)

**Comment by Geon27** [comment]
here is data file! : [https://github.com/Geon27/3-1-R-Homework/blob/main/IMDB-Movie-Data.csv](url)

**Comment by cderv** [comment]
Hi, 

Please follow the issue guide https://yihui.org/issue/ to format your content correctly and also give more context of what issue you found. A sentence in a title is not enough. 

If you have a question and not an issue, follow the guide too https://yihui.org/issue/#got-a-question and ask in the right place. 

Thank you!
