### ISSUE TITLE
{rvest} example in website gallery is 404

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rmarkdown#2250]
Seen here: https://rmarkdown.rstudio.com/gallery.html

![gallery](https://user-images.githubusercontent.com/11330453/143688740-23abb019-c001-4610-89ef-10643f89d4c7.PNG)

P.S. I know this is not a bug report, but I couldn't find any docs-relevant tag, so I am filing it under this issue tag.

**Comment by cderv** [comment]
Thanks, that is the right place to report this !
