### ISSUE TITLE
Could not fetch picture website

### ISSUE THREAD

**Issue by huangwb8** [rstudio/rmarkdown#2253]
Recencly, I use `RMarkdown` for beautiful html production, and I was stubborned by a problem.

Here is the picture url

![](https://github.com/huangwb8/test_file/blob/master/GSClassifier/GSClassifier-model.jpg?raw=true)

When click `Knit`, it returns an erorr:

```
C:/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Advanced-development.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output Advanced-development.html --lua-filter "D:\research\Rpackage\4.0.3\library\rmarkdown\rmarkdown\lua\pagebreak.lua" --lua-filter "D:\research\Rpackage\4.0.3\library\rmarkdown\rmarkdown\lua\latex-div.lua" --self-contained --standalone --section-divs --template "D:/research/Rpackage/4.0.3/library/prettydoc/resources/templates/architect.html" --highlight-style pygments --include-in-header "C:\Users\ADMINI~1\AppData\Local\Temp\RtmpeSDz2c\rmarkdown-str373873824cfb.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --variable resource-dir=Advanced-development_files --variable katex --css Advanced-development_files/style.css 

Could not fetch https://github.com/huangwb8/test_file/blob/master/GSClassifier/GSClassifier-model.jpg?raw=true
HttpExceptionRequest Request {
  host                 = "github.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/huangwb8/test_file/blob/master/GSClassifier/GSClassifier-model.jpg"
  queryString          = "?raw=true"
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException Network.Socket.recvBuf: invalid argument (Invalid argument))
错误: pandoc document conversion failed with error 61
停止执行
```

Ocationally it could succeed but fail in most time.

How to solve it?

**Comment by cderv** [comment]
This error seems to come from Pandoc directly. How are you including the image in your document ? There are lots of ways to do that and you do not share the information. 

Considering the URL you are using, I would use the non-redirected version : https://raw.githubusercontent.com/huangwb8/test_file/master/GSClassifier/GSClassifier-model.jpg 
The actual url is a redirect and possibly the tool you are using does not support it out of the box. 

If this does not solve it, we need more information and what you are doing. This simple example is working fine 

````markdown
---
title: test
output: html_document
---

![](https://github.com/huangwb8/test_file/blob/master/GSClassifier/GSClassifier-model.jpg?raw=true)
````

So I don't see any issue with this URL using this minimal reproducible example.

**Comment by huangwb8** [comment]
@cderv 
The link you provide is also had the same problem for me, which might be caused by my local network. I had try another way to store the picture.  It's nothing about the rmarkdown, I think. 
Thanks for quick reply!
