### ISSUE TITLE
strange behaviour with TeX conditionals

### ISSUE THREAD

**Issue by samuelmehr** [rstudio/rmarkdown#2254]
I've upgraded my OS to Big Sur and am experiencing strange behaviour with RMarkdown documents that include TeX conditionals. This same computer previously had no issues with them (two documents I update regularly include similar conditionals). A reproducible example follows.

This Rmd code knits fine and produces a pdf that looks normal.
```
---
header-includes:
output: 
  pdf_document: 
    latex_engine: lualatex
---

This is a document to test whether RStudio can knit in TeX. It can.
```

In contrast, this Rmd code fails with the following error.
```
---
header-includes:
 - \newif\ifFlag
output: 
  pdf_document: 
    keep_tex: true
    latex_engine: lualatex
---

\Flagtrue

This is a document to test whether RStudio can knit in TeX with conditional statements.

\ifFlag
Flag is set to TRUE.
\else
Flag is set to FALSE.
\fi

The preceding test is enclosed in an ifelse statement.
```

Here is the error text:
```
! Emergency stop.
<*> tex_ifelse-test.tex

Error: LaTeX failed to compile tex_ifelse-test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See tex_ifelse-test.log for more info.
Execution halted
```

When I inspect the raw TeX created from the Rmd, it's clear why it's not rendering. Here is the relevant section of code:
```
\newif\ifFlag
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}

\def\iffalse\iftrue

This is a document to test whether RStudio can knit in TeX with
conditional statements.

\iftrue

Flag is set to TRUE. \else Flag is set to FALSE. \fi

The preceding test is enclosed in an ifelse statement.

\end{document}
```

As you can see, the if-else logic doesn't make any sense. This is new behavior after my macOS upgrade and it sort of baffles me ... why would this and only this be affected? (Several other Rmd documents I work with regularly knit fine, but only those with TeX conditionals fail).

This is in RStudio 2021.09.1 Build 372, freshly installed, with a fresh install of MacTeX. Any ideas?

**Comment by cderv** [comment]
Can you share you Pandoc version ? 
```
rmarkdown::pandoc_version()
```

I believe this is an issue in Pandoc itself. From my test, last one to work with your example if Pandoc 2.13, and it fails from Pandoc 2.14

It seems to come with the Markdown reader interpretating the raw Tex line. 

If you set the line in header include to be raw Latex, this works 
````
header-includes: 
  - |
    ```{=latex}
    \newif\ifFlag
    ```
````

This above follows example in https://pandoc.org/MANUAL.html#metadata-blocks

Hope it helps

**Comment by samuelmehr** [comment]
This is in pandoc 2.14.0.3 and yes, renders for me with the header line in raw tex. Weird that the same header line would be interpreted differently in pandoc 2.13 vs 2.14 though ... I guess from the pandoc documentation I should have been enclosing the \newif in a code block within the header to begin with? (news to me!)

**Comment by cderv** [comment]
> Weird that the same header line would be interpreted differently in pandoc 2.13 vs 2.14 though ...

Yes I find it unexpected too. Maybe there is a regression in Pandoc. Something to look into an report - The release note needs to be checked to see about this kind of this.

**Comment by samuelmehr** [comment]
Gotcha. I guess this is probably the wrong place to report it... I'll close this issue for {rmarkdown} since it's clearly a pandoc issue. Thanks for your help!

**Comment by cderv** [comment]
I have looked a bit into that, and it seems something related to `header-includes` as a YAML field. 
This is one way to define header to includes using a variable which is filled automatically otherwise: https://pandoc.org/MANUAL.html#variables-set-automatically

The other way is to use a file to pass a command line flag `--include-in-header`. To do that with R Markdown, you would use the `includes` and `in_header`. And in that case it works fine 

````markdown
---
output: 
  pdf_document: 
    keep_tex: true
    latex_engine: lualatex
    includes:
      in_header: preamble.tex
---

```{cat, engine.opts = list(file = "preamble.tex"), echo = FALSE}
\newif\ifFlag
```

\Flagtrue

This is a document to test whether RStudio can knit in TeX with conditional statements.

\ifFlag
Flag is set to TRUE.
\else
Flag is set to FALSE.
\fi

The preceding test is enclosed in an ifelse statement.
````

So I guess this behavior is due to how the YAML field is parsed and the doc warns against it

> Raw content to include in the document’s header may be specified using header-includes; however, it is important to mark up this content as raw code for a particular output format, using the raw_attribute extension), or it will be interpreted as markdown. 

So I am not sure there is an issue to open and maybe this is more like a feature. If one need to include raw code as header include, it would need to be marked as is.
