### ISSUE TITLE
[FR] moving to Bootstrap 5 

### ISSUE THREAD

**Issue by davidbudzynski** [rstudio/rmarkdown#2257]
Hi, are there any plans for moving to Bootstrap 5, like you did with pkgdown?

**Comment by cderv** [comment]
Hi, 

**rmarkdown** should be already compatible with **bslib**. 
Have you read the vignette yet ? 

https://rstudio.github.io/bslib/articles/bslib.html

You should be able to use bootstrap 4 and probably 5 as **bslib** supports it. 

Have you tried already ? What is not working ? 

If you encounter any issue, please share. 

Thanks

**Comment by davidbudzynski** [comment]
I was not aware of this package, thanks for pointing me to it!
