### ISSUE TITLE
Broken link: vignettes/rmarkdown.Rmd

### ISSUE THREAD

**Issue by debruine** [rstudio/rmarkdown#2268]
Line 126 : link is to a page not found. This is the same URL as in the RStudio Help > Cheatsheets menu, so I'm not sure where this document lives now.

[R Markdown Reference](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)

**Comment by cderv** [comment]
Thanks for the report. I'll try to find where it went... 🕵️

**Comment by cderv** [comment]
In fact I think this document do not exist anymore. It has been replaced by the new Cheatsheet: https://raw.githubusercontent.com/rstudio/cheatsheets/main/rmarkdown.pdf which is an update of the previous cheatsheet and this doc. As it was unmaintained it has been decided to remove it. 

The content of the small reference guide can be also found in different chapter of the R Markdown books I'll believe. I'll check that everything is in there. 

I'll update the vignette to remove the 404 link. Thanks again for the report
