### ISSUE TITLE
Incorrect direction of single curved quote if we use a citation followed by 's and a word followed by' in the same para

### ISSUE THREAD

**Issue by anirban-mukherjee** [rstudio/rmarkdown#2269]
If R Markdown has a citation followed by 's and another word followed by ' (but not by 's) then the single quote is in the wrong direction. Below is a MWE where @cat is a reference to Cat (2021).
```
1. Correct direction: cat's fur.
2. Correct direction: cat's fur. dogs' fur.
3. Correct direction: cat's fur. dog's fur.
4. Correct direction: @cat's fur. dog's fur.
5. Incorrect direction: @cat's fur. dogs' fur.
```
The output should be:
```
Cat (2021)'s fur. dogs' fur.
``` 
Instead we get:
```
Cat (2021)`s fur. dogs' fur.
``` 
Note the quote after Cat (2021) is a left quote and not a right quote.

dogs' fur only trips the code if there is a citation followed by a quote (case 5 in the MWE) but not if there is a word followed by 's (case 2 in the MWE). 

In cases 3 and 4, we have dog's fur. In those cases, the input does not trip up the parser.

```
> xfun::session_info('rmarkdown')
R version 4.1.2 Patched (2021-12-24 r81416)
Platform: x86_64-apple-darwin21.2.0 (64-bit)
Running under: macOS Monterey 12.1, RStudio 2021.9.1.372

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 digest_0.6.29   evaluate_0.14   fastmap_1.1.0   glue_1.6.0     
  graphics_4.1.2  grDevices_4.1.2 highr_0.9       htmltools_0.5.2 jquerylib_0.1.4
  jsonlite_1.7.2  knitr_1.37      magrittr_2.0.1  methods_4.1.2   rlang_0.4.12   
  rmarkdown_2.11  stats_4.1.2     stringi_1.7.6   stringr_1.4.0   tinytex_0.36   
  tools_4.1.2     utils_4.1.2     xfun_0.29       yaml_2.2.1     

Pandoc version: 2.14.0.3
```

**Comment by cderv** [comment]
Hi @anirban-mukherjee, 

Here is a self contained minimal reprex I built based on your example
````markdown
---
title: "Test"
output: pdf_document
references:
- type: article-journal
  id: cat
  author:
  - family: Cat
    given: billy
  issued:
    year: 2021
  title: 'Journal about Cat'
  volume: 171
  issue: 4356
  page: 737-738
  language: en-GB
---

1. Correct direction: cat's fur.
2. Correct direction: cat's fur. dogs' fur.
3. Correct direction: cat's fur. dog's fur.
4. Correct direction: @cat's fur. dog's fur.
5. Incorrect direction: @cat's fur. dogs' fur.

# Reference

````

Assuming you are talking about PDF output, I believe what you see is something directly related to Pandoc. If I convert using Pandoc command line to LaTeX, I get this 
```sh
❯ pandoc -f markdown -t latex test.Rmd
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Correct direction: cat's fur.
\item
  Correct direction: cat's fur. dogs' fur.
\item
  Correct direction: cat's fur. dog's fur.
\item
  Correct direction: @cat's fur. dog's fur.
\item
  Incorrect direction: @cat`s fur. dogs' fur.
\end{enumerate}

\hypertarget{reference}{%
\section{Reference}\label{reference}}
```

I think the Pandoc parser see this as single quotes and as `smart` extension is active, it converts to TeX Ligatures. See  https://pandoc.org/MANUAL.html#extension-smart

This would be an issue for Pandoc directly so that they don't parse this as a pair of single quotes.

**Comment by anirban-mukherjee** [comment]
Thank you for the exhaustive investigations! Yes that looks correct.

In terms of a real case example, I hit this bug when writing an academic paper. It is common in economics and marketing to write "in @cat's study of the pet food industry". I am unsure of how often people will have both "@cat's study" and "dogs' fur" in the same paragraph but that's what happened in my draft (of course the real citations and sentences in my paper are very different from cats and dogs).

I think the more painful part was drilling down down to a MWE (I originally thought some Tex packages were interacting in a weird way). Having identified the issue, a (kludgy) workaround is not that difficult. Hence, I leave it to your judgment as to whether or not to open an issue.

Thanks much!

**Comment by cderv** [comment]
> Hence, I leave it to your judgment as to whether or not to open an issue.

I don't know if I am the best judge of this. I don't write papers evolving such situation. 

If this could happen, then this is something to report to Pandoc as their parser does not handle this correctly. I don't know if there is an easy solution to detect (maybe the `.` in what is seen a Single quoted ?).

> (of course the real citations and sentences in my paper are very different from cats and dogs).

Maybe the real life example sentence could help make our case to Pandoc teams that this could be a real issue and not just something encountered by chance and does not worth fixing. 

So IMO, you're the best judge for this :) What should we do ?

**Comment by yihui** [comment]
I think the solution is simple: you can escape the apostrophe, i.e., `@cat\'s`.

**Comment by anirban-mukherjee** [comment]
Super, that works. Might be a bit challenging for people to discover the fix but we can hope that the search engines will do their magic. I am closing this issue as I think its likely too far a corner case for the pandoc team to spend the efforts on a fix. Thanks both!

**Comment by cderv** [comment]
Thanks @yihui ! I forgot about escaping. That is indeed the easiest !
