### ISSUE TITLE
Knitting HTML from RStudio versus using rmarkdown::render() treats iframes differently 

### ISSUE THREAD

**Issue by nicolerg** [rstudio/rmarkdown#2270]
Hello, 

I am trying to embed standalone HTML files within a larger HTML report generated with Rmd using iframes. When I knit to HTML within RStudio, I get the expected behavior, which is an independent HTML file that can be shared with others. When I instead generate an HTML using `rmarkdown::render()` from the command line, the name of the iframe source file is included in the rendered HTML, and the iframes appear as broken links if the paths to the iframe source files are not maintained. 

Here is an example with this `minimal.html`:
```{html}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    hello there
  </body>
</html>
```
and this `embed-iframes.Rmd`: 
````
---
title: "Embed iframes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data(cars)
```

```{r, results = "asis"}
# it needs to work inside a loop
for (i in 1){
  # print a plot
  plot(cars$speed, cars$dist)
  
  # print an iframe from an external html
  print(htmltools::tags$iframe(title = "My embedded document", src = "minimal.html"))
}
```
````

In the attached zip file, there are two HTMLs: 

* `embed-iframes.html`: This is the HTML when knitted within Rstudio and what I would also like to get from `rmarkdown::render()`.  "hello there" is visible in an iframe as expected. 

* `embed-iframes-RMDrender.html`: This is the HTML generated using `Rscript -e "rmarkdown::render('embed-iframes.Rmd', output_file='embed-iframes-RMDrender.html')"`. Instead of "hello there", you see a broken link icon with "It may have been moved, edited, or deleted" (as long as `minimal.html` is not in the same path as `embed-iframes-RMDrender.html`). The path to the iframe source file, i.e. "minimal.html", is written explicitly in the HTML code. 

My current workaround is to share folders with the HTML report and all iframe source HTMLs, but this is not ideal. I imagine there's a pandoc setting to get the iframe source embedded directly into the rendered HTML report, but I am at a bit of a loss. I would appreciate any help. 
[htmls.zip](https://github.com/rstudio/rmarkdown/files/7809521/htmls.zip)

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core), RStudio 2021.9.0.351

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3 digest_0.6.28   evaluate_0.14   fastmap_1.1.0   glue_1.5.0      graphics_4.0.3  grDevices_4.0.3 highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.2 
  knitr_1.36      magrittr_2.0.1  methods_4.0.3   rlang_0.4.12    rmarkdown_2.11  stats_4.0.3     stringi_1.7.5   stringr_1.4.0   tinytex_0.35    tools_4.0.3     utils_4.0.3    
  xfun_0.28       yaml_2.2.1     

Pandoc version: 2.14.0.3
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`? 
- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)? - **No - I am limited by the cluster I use**

**Comment by cderv** [comment]
Hi, 

Thanks for opening an issue.

I understand that you want the iframe content to be self contained inside the main document. Is that right ? 
I also understand this works correctly inside RStudio IDE, by either Knitting with the button or calling `rmarkdown::render()` in console, but does not outside when using `RScript` in terminal.  Is that also right ? 

One difference that you main encounter is that the Pandoc version used when within RStudio or within terminal is different. 
RStudio ships a pandoc binary that will be used by **rmarkdown** when you use the IDE. However, outside of the IDE, the version from your system will be used by default (the one found in PATH). If the Pandoc version are different, and Pandoc behavior regarding embeding iframe is different, then that would explain. Especially, this behavior changed a bit in [pandoc 2.11.2](https://pandoc.org/releases.html#pandoc-2.11.2-2020-11-19) where now iframe will be self contained.

Can you run this to check this ? 
```sh
Rscript -e "rmarkdown::find_pandoc()"
```

Thanks

**Comment by nicolerg** [comment]
Thanks for your quick reply!

> I understand that you want the iframe content to be self contained inside the main document. Is that right ?
I also understand this works correctly inside RStudio IDE, by either Knitting with the button or calling `rmarkdown::render()` in console, but does not outside when using `RScript` in terminal. Is that also right ?

Yes, correct on both accounts. 

You are right, a much older version of `pandoc` is installed on my system (1.12.3.1). I will try installing a newer version and rerunning `Rscript -e "rmarkdown::render()`. 

I appreciate your help!

**Comment by cderv** [comment]
Version 1.12.3.1 is quite old ! You will probably have a lot of differences depending how much you rely on R Markdown features, based on recent Pandoc feature. 

I don't think Pandoc is that complicated to install (https://pandoc.org/installing.html). You could also use the version ship with RStudio in the script you want to run at terminal. RStudio IDE ships with pandoc so you can also use the binary outside of RStudio if you configure the PATH.

Anyway, I am sure you'll find the proper solution now that we have pinpoint the issue. 

I'll close this as this is not directly related to **rmarkdown**

Thanks!
