### ISSUE TITLE
Use fontawesome R package for HTML dependencies

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2276]
Use the **fontawesome** R package https://github.com/rstudio/fontawesome and deprecated the **fontawesome** dependency. 
https://github.com/rstudio/rmarkdown/blob/fedcdcf112971c5900c210c79aa08216b54808c3/R/html_dependencies.R#L185-L195

Some other package may use this dependency 

* **pagedown** https://github.com/rstudio/pagedown/blob/db0764afa05c8b38f70bbfc1972bbb0ee3dffd43/R/resume.R#L17
* **flexdashboard** https://github.com/rstudio/flexdashboard/blob/33458eaae7c4164ed300a02be30bcb61d14a4f20/R/dependencies.RL4

and a lot of others:  https://github.com/search?q=html_dependency_font_awesome&type=Code
as this usage is quite widespread
```r
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

This should solves https://github.com/rstudio/rmarkdown/issues/2042 and https://github.com/rstudio/rmarkdown/issues/1661 by relying on the other package to update the JS library

**Comment by cderv** [comment]
Another issue with icon not available in **flexdashboard** which is using **rmarkdown** dependency
https://community.rstudio.com/t/some-icons-not-working-in-flexdashboard/156504

**Comment by rich-iannone** [comment]
@cderv Sorry for leaving this for so long. I’ll update the fontawesome package (to newest v6 icons, and I’ll fix a bad bug where some icon font files are not included). Then, it will be better to integrate the dependency with R Markdown.

**Comment by cderv** [comment]
No hurry. I am just referencing encountered issue. We'll rediscuss next week to see when next rmarkdown version is scheduled.
