### ISSUE TITLE
Show / Hide does not work with Boostrap 5

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2278]
````markdown
---
title: test
output:
  html_document:
    theme:
      version: 5
    code_folding: show
---

```{r, eval = TRUE}
1 + 1 
```
````
![hide-show](https://user-images.githubusercontent.com/6791940/149163957-3f5682f2-c302-4c95-99d8-81f634df426e.gif)

**Comment by cpsievert** [comment]
Pretty sure this is no longer an issue

**Comment by cderv** [comment]
Yes you're right - this is working - I can't reproduce anymore. 

Thanks for the heads up !
