### ISSUE TITLE
Rmd does not render pdf file successfully 

### ISSUE THREAD

**Issue by PursuitOfDataScience** [rstudio/rmarkdown#2293]
Hi, I've been having issues rendering .Rmd files into PDF format, even after I followed strictly what this [link](https://yihui.org/tinytex/r/#debugging) told me to do. All my R packages, R, Rstudio are the latest. 

Here I produce a simple example:

```
---
title: "test"
date: "January 24, 2022"
output: pdf_document
---
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This is just simply a test.

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

And the output is attached below in the screenshot fomat:

![image](https://user-images.githubusercontent.com/54338793/150801537-2992d9a5-357a-4a4f-ada3-caf5588cc2aa.png)

Could you please help me out and offer me some advice? This happens even after I `tinytex::reinstall_tinytex()` multiple times. Thanks!

**Comment by yihui** [comment]
Could you provide the output of `xfun::session_info('tinytex')` and `tinytex::tinytex_root()`?

**Comment by PursuitOfDataScience** [comment]
Thanks for the reply.

Here I attach the output for both functions you mentioned:

![image](https://user-images.githubusercontent.com/54338793/150809838-66a120a0-8d3c-4df3-a783-38b9ae9604f2.png)

Thanks!

**Comment by yihui** [comment]
As I guessed, your RStudio is not the latest version. You have RStudio 1.1.463. Please try to upgrade: https://www.rstudio.com/products/rstudio/download/ Not all of your R packages are up-to-date, either (e.g., tinytex).

**Comment by PursuitOfDataScience** [comment]
Strangely, I got the machine roughly a month ago and I downloaded everything from the scratch. I deemed everything was "latest," but unfortunately they were not. Here I just updated my RStudio and packages, but the same problem still occurs, although the error message is shorter than the previous one. 

![image](https://user-images.githubusercontent.com/54338793/150821084-2b0f84cc-f145-4d2a-a805-12a3662095ac.png)

![image](https://user-images.githubusercontent.com/54338793/150821133-17bc62d6-66f3-47f6-8ac1-595716c31b69.png)

**Comment by yihui** [comment]
Is this your own machine or is it managed by IT or other people?

Could you provide the output of the following code?

```
(function() {
  tinytex:::tweak_path()
  system2('pdflatex', '--version')
})()
```

**Comment by PursuitOfDataScience** [comment]
It is managed by IT, although I have the local admin control. Before I filed this issue, I asked them to dissect where the problems were and there was nothing they could find out, as other output formats (html, word, etc.) worked perfectly.  

The output of the function provided by you returns nothing. Is it the expected output?

**Comment by yihui** [comment]
It's not expected. It should return the `pdflatex` version info. Try:

```r
(function() {
  tinytex:::tweak_path()
  Sys.which('pdflatex')
})()
```

**Comment by PursuitOfDataScience** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/54338793/150870890-bb731fdf-4071-42c6-8993-a219a519d42f.png)

**Comment by yihui** [comment]
Then I don't know what's wrong. It seems you are unable to execute `pdflatex.exe` on your computer. You will have to ask IT for help. They might have enforced some security restrictions on your computer.

**Comment by PursuitOfDataScience** [comment]
Okay. Thanks for your help!

**Comment by PursuitOfDataScience** [comment]
Hi Yihui,

I asked the IT folks to look into the issue. After spending hours remotely to help me, they said the security configuration does not hinder `pdflatex.exe` or any other file. The problem is still unresolved, and they will dispatch some technician tomorrow to see what has happened on spot. In the meantime, if you can help narrow down issue, maybe it can help solve it faster. Let me know what I can do. Thanks!
