### ISSUE TITLE
rmarkdown::render() reorders all YAML header keys at least for gfm with preserve_yaml: true

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rmarkdown#2297]
With `rmarkdown` 2.11 and Pandoc 2.14.0.3, all YAML header keys are sorted alphabetically, see below reprex. This happens at least for `gfm` output with `preserve_yaml: true`.

I didn't investigate whether this is actually Pandoc doing this - anyhow the behaviour is different than before. While this result is still functional (usecase: `hugo server`) it is unwanted.

RStudio is the current stable release:

> RStudio 2021.09.2+382 "Ghost Orchid" Release (fc9e217980ee9320126e33cdf334d4f4e105dc4f, 2022-01-04) for Ubuntu Bionic
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
> 

``` r
tmpin <- tempfile()
tmpout <- tempfile(fileext = ".md")
string <- 
  '---
title: "Example title"
description: "Example description"
date: 2022-01-31
output: 
  md_document:
    preserve_yaml: true
    variant: gfm+footnotes\n---
    
Some text.'

writeLines(string, tmpin)
cat(readLines(tmpin), sep = "\n")
#> ---
#> title: "Example title"
#> description: "Example description"
#> date: 2022-01-31
#> output: 
#>   md_document:
#>     preserve_yaml: true
#>     variant: gfm+footnotes
#> ---
#>     
#> Some text.
rmarkdown::render(tmpin, output_file = tmpout)
#> /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS file65f8125410da --to gfm+footnotes+yaml_metadata_block --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/RtmpeFo9O5/file65f82618488a.md --standalone
#> 
#> Output created: /tmp/RtmpeFo9O5/file65f82618488a.md

cat(readLines(tmpout), sep = "\n")
#> ---
#> date: 2022-01-31
#> description: Example description
#> output:
#>   md_document:
#>     preserve_yaml: true
#>     variant: gfm+footnotes
#> title: Example title
#> ---
#> 
#> Some text.

xfun::session_info('rmarkdown')
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Linux Mint 20
#> 
#> Locale:
#>   LC_CTYPE=nl_BE.UTF-8       LC_NUMERIC=C              
#>   LC_TIME=nl_BE.UTF-8        LC_COLLATE=nl_BE.UTF-8    
#>   LC_MONETARY=nl_BE.UTF-8    LC_MESSAGES=nl_BE.UTF-8   
#>   LC_PAPER=nl_BE.UTF-8       LC_NAME=C                 
#>   LC_ADDRESS=C               LC_TELEPHONE=C            
#>   LC_MEASUREMENT=nl_BE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> Package version:
#>   base64enc_0.1.3 digest_0.6.29   evaluate_0.14   fastmap_1.1.0  
#>   glue_1.6.0      graphics_4.1.2  grDevices_4.1.2 highr_0.9      
#>   htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.3  knitr_1.37     
#>   magrittr_2.0.1  methods_4.1.2   rlang_0.4.12    rmarkdown_2.11 
#>   stats_4.1.2     stringi_1.7.6   stringr_1.4.0   tinytex_0.36   
#>   tools_4.1.2     utils_4.1.2     xfun_0.29       yaml_2.2.1     
#> 
#> Pandoc version: 2.14.0.3
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Linux Mint 20
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2022-01-31
#>  pandoc   2.14.0.3 @ /usr/lib/rstudio/bin/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.1.0   2021-10-27 [1] CRAN (R 4.1.2)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.2)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.2)
#>  glue          1.6.0   2021-12-17 [1] CRAN (R 4.1.2)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
#>  knitr         1.37    2021-12-16 [1] CRAN (R 4.1.2)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
#>  reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang         0.4.12  2021-10-18 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.1)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.2)
#>  stringi       1.7.6   2021-11-29 [1] CRAN (R 4.1.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
#>  withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.2)
#>  xfun          0.29    2021-12-14 [1] CRAN (R 4.1.2)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Thanks for the report. 

In fact it seems this is because we rely on Pandoc's extension [`yaml_metadata_block`](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) which is activated by default in **gfm** now I think. 

It seems like Pandoc reorder the content (and even add other internal metadata). 

To get back the previous behavior, we may need to deactivate it and just copy the YAML from the input to the output. 🤔

**Comment by florisvdh** [comment]
Thanks for the reference. Indeed, the Pandoc documentation declares:

> Note: the `yaml_metadata_block` extension works with `commonmark` as well as `markdown` (and it is enabled by default in `gfm` and `commonmark_x`). 

It is said that '_All of the metadata will appear in a single block at the beginning of the document._' However IMHO it could be argued (in the Pandoc repo) that this should not trigger sorting of the YAML fields.

**Comment by cderv** [comment]
> It is said that 'All of the metadata will appear in a single block at the beginning of the document.'

Yes, it seems that all the metadata including those no passed in input's YAML header will be in the output. I am not sure we want that in **rmarkdown**. 

> However IMHO it could be argued (in the Pandoc repo) that this should not trigger sorting of the YAML fields.

Yes I agree. Do you want to ask there with a Pandoc Only reprex ? 

We can still do our trick in **rmarkdown** and not rely on Pandoc for this `preserve_yaml`

**Comment by florisvdh** [comment]
> including those no passed in input's YAML header will be in the output

Could be, but at least in the reprex and in some real cases no extra metadata popped up in the output.

> Do you want to ask there with a Pandoc Only reprex ?

I'll see what I can do during this week, but feel free to take this over!

> We can still do our trick in **rmarkdown** and not rely on Pandoc for this `preserve_yaml`

Indeed, providing a workaround would be good for **rmarkdown** users, as long as it is not solved in a Pandoc version distributed by at least RStudio.

**Comment by florisvdh** [comment]
> Do you want to ask there with a Pandoc Only reprex ?

See https://github.com/jgm/pandoc/issues/7891

**Comment by cderv** [comment]
Thanks. Seems like it is not possible on Pandoc's side. So I'll have to revert part of https://github.com/rstudio/rmarkdown/pull/2190 to use our trick and deactivate `yaml_metadata_block` extension.

**Comment by florisvdh** [comment]
Thanks, looking forward to it!

**Comment by cderv** [comment]
@florisvdh you can try the PR to see if this correctly handle your issue 
This should now work ok in dev version of the package. 

```r
remotes::install_github("rstudio/rmarkdown#2303")
```

Feel free to review the PR also if you desire.

**Comment by florisvdh** [comment]
Re-ran the reprex and this works :tada:!

Indeed Pandoc-output is now extended with `-yaml_metadata_block`, and **rmarkdown** magically copied the YAML header to the output. Excellent, thanks a lot.

<details><summary><strong>Reprex revisited</strong></summary>

``` r
tmpin <- tempfile()
tmpout <- tempfile(fileext = ".md")
string <- 
  '---
title: "Example title"
description: "Example description"
date: 2022-01-31
output: 
  md_document:
    preserve_yaml: true
    variant: gfm+footnotes\n---
    
Some text.'

writeLines(string, tmpin)
cat(readLines(tmpin), sep = "\n")
#> ---
#> title: "Example title"
#> description: "Example description"
#> date: 2022-01-31
#> output: 
#>   md_document:
#>     preserve_yaml: true
#>     variant: gfm+footnotes
#> ---
#>     
#> Some text.

rmarkdown::render(tmpin, output_file = tmpout)
#> /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS file9c2e3e4f2501 --to gfm+footnotes-yaml_metadata_block --from markdown+autolink_bare_uris+tex_math_single_backslash --output /tmp/Rtmpmv8ZWs/file9c2e59c6e965.md
#> 
#> Output created: /tmp/Rtmpmv8ZWs/file9c2e59c6e965.md

cat(readLines(tmpout), sep = "\n")
#> ---
#> title: "Example title"
#> description: "Example description"
#> date: 2022-01-31
#> output: 
#>   md_document:
#>     preserve_yaml: true
#>     variant: gfm+footnotes
#> ---
#> 
#> Some text.

xfun::session_info('rmarkdown')
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Linux Mint 20
#> 
#> Locale:
#>   LC_CTYPE=nl_BE.UTF-8       LC_NUMERIC=C              
#>   LC_TIME=nl_BE.UTF-8        LC_COLLATE=nl_BE.UTF-8    
#>   LC_MONETARY=nl_BE.UTF-8    LC_MESSAGES=nl_BE.UTF-8   
#>   LC_PAPER=nl_BE.UTF-8       LC_NAME=C                 
#>   LC_ADDRESS=C               LC_TELEPHONE=C            
#>   LC_MEASUREMENT=nl_BE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> Package version:
#>   base64enc_0.1.3   bslib_0.3.1       digest_0.6.29     evaluate_0.14    
#>   fastmap_1.1.0     fs_1.5.2          glue_1.6.1        graphics_4.1.2   
#>   grDevices_4.1.2   highr_0.9         htmltools_0.5.2   jquerylib_0.1.4  
#>   jsonlite_1.7.3    knitr_1.37        magrittr_2.0.2    methods_4.1.2    
#>   R6_2.5.1          rappdirs_0.3.3    rlang_1.0.1       rmarkdown_2.11.15
#>   sass_0.4.0        stats_4.1.2       stringi_1.7.6     stringr_1.4.0    
#>   tinytex_0.36      tools_4.1.2       utils_4.1.2       xfun_0.29        
#>   yaml_2.2.2       
#> 
#> Pandoc version: 2.14.0.3
```

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

</details>
