### ISSUE TITLE
[FR] Use Github footnotes syntax for README/github_document

### ISSUE THREAD

**Issue by assignUser** [rstudio/rmarkdown#2298]
Hello! Thanks for your amazing work!

Recently Github has started supporting markdown [footnote syntax
](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) and automatically creates links for navigation on each footnote and in the text. ([example](https://github.com/assignUser/octolog/tree/documentation#octolog))

Currently `rmarkdown` converts the markdown footnotes into a non-interactive version when `output: github_document` is set, it would be a nice convenience if the native version could be supported.

**Comment by cderv** [comment]
> Currently rmarkdown converts the markdown footnotes into a non-interactive version when output: github_document is set, it would be a nice convenience if the native version could be supported.

Can you precise the output you are looking for ? 

I tried this 
````markdown
---
output: 
  github_document: default
---

# Footnote example

Here is a simple footnote[^1]. With some additional text after it.

[^1]: My reference.
````

And it outputs in the md file this content
````markdown

# Footnote example

Here is a simple footnote[^1]. With some additional text after it.

[^1]: My reference.

````

which correctly renders as footnotes, with a footnotes at the bottom of this comment. 
I pasted it below 

--------------


# Footnote example

Here is a simple footnote[^1]. With some additional text after it.

[^1]: My reference.

--------------

What am I missing that is not working for you ?

**Comment by assignUser** [comment]
The issue seems to be the pandoc version, with rmarkdown 2.11/@main & pandoc 2.9(default ubuntu repo) this creates the following:
```
# Footnote example

Here is a simple footnote\[1\]. With some additional text after it.

1.  My reference.

```
But with pandoc 2.17 I get the same result as you!

**Comment by cderv** [comment]
Oh I see. 

I believe this is because the `gfm` formats in Pandoc has changed over time. 
Footnotes are supported through an extension and I think it was not supported by `gfm` formats in ealier Pandoc. One need to build from `markdown` and activating desired extension. 

Updating Pandoc is by far the easier solution here. 

Thanks
