### ISSUE TITLE
add \pdfoutput to preamble for arXiv sumbission

### ISSUE THREAD

**Issue by bakaburg1** [rstudio/rmarkdown#2315]
Hello,

Seems strange this issue wasn't raised before since rmarkdown is much used for scientific publishing.

I recently submitted a manuscript to arXiv, but it failed because they need the option `\pdfoutput = 1` within the first 5 lines of the preamble when processing a .tex file.

Using the `in_header` option doesn't seem to work because if one is using a template (I am using rticles::arxiv_article()) then the latex code passed to `in_header` is appended much later in the document.

How does one add `\pdfoutput = 1` in rmarkdown forcing it to be at the top of the produced .tex document?

**Comment by cderv** [comment]
Thanks for the report. 

> How does one add \pdfoutput = 1 in rmarkdown forcing it to be at the top of the produced .tex document?

If this is not an option in the `.tex` template used by Pandoc, there is not easy solution unless post processing the `.tex` file. 

If this line is mandatory for `arxiv` submission, then it should be added in [`template.tex` for `rticles::arxiv_article()`](https://github.com/rstudio/rticles/blob/7fff4766aead70782b366ad769f314fc61494854/inst/rmarkdown/templates/arxiv/resources/template.tex). 

This has not been reported in **rticles** repo in the past surprisingly. The current template has been initially submitted in https://github.com/rstudio/rticles/pull/236 and we can definitely update it with a new version. 

Would you like to submit a PR in **rticles** for this ? Do you have an updated version of arxiv template to use ?

**Comment by bakaburg1** [comment]
Dear cderv. I wasn't planning to add a PR to `rticles`. I can either do the PR myself or raise an issue there, as is more convenient to you.

**Comment by cderv** [comment]
Thanks for opening in **rticles**. I close this here and we'll continue there
