### ISSUE TITLE
Release rmarkdown 2.12

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2321]
Using this issue as the way to track progress and discuss potential issue preparing release. 
This is created by `usethis::use_release_issue("2.12")` and all may not be adapted to our process yet, but this remains a good checklist. 

Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_rmarkdown.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `xfun::crandalf_check()`
* [x] `revdepcheck::cloud_check()` 
* [x] Update `cran-comments.md`
* [ ] Review pkgdown reference index for, e.g., missing topics
* [x] `git push`
* [x] ~Draft blog post~
* [ ] Notify in #open-source-comms on Slack

Submit to CRAN:

* [x] `usethis::use_version('minor')` 
* [x] `devtools::submit_cran()` / `xfun::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_version("patch")`
* [x] `git push`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by yihui** [comment]
crandalf's revdep checks also revealed three of the packages you discovered:

gitdown

```
+   ── Failure (test-git_down.R:25:5): git_down function ───────────────────────────
+   `one_line_exists` has length 0, not length 1.
+   ── Failure (test-git_down.R:26:5): git_down function ───────────────────────────
+   `sub_commit_1` has length 0, not length 1.
+   ── Failure (test-git_down.R:27:5): git_down function ───────────────────────────
+   `sub_commit_2` has length 0, not length 1.
+   ── Failure (test-git_down.R:48:5): git_down no name function ───────────────────
+   length(one_line_exists) == 1 is not TRUE
+   
+   `actual`:   FALSE
+   `expected`: TRUE 
+   ── Failure (test-git_down.R:75:5): git_down multiple pattern works ─────────────
+   length(one_line_ticket_exists) == 1 is not TRUE
+   
+   `actual`:   FALSE
+   `expected`: TRUE 
+   ── Failure (test-git_down.R:80:5): git_down multiple pattern works ─────────────
+   length(one_line_exists) == 1 is not TRUE
+   
+   `actual`:   FALSE
+   `expected`: TRUE 
```

molic

```
+ * checking re-building of vignette outputs ... WARNING
+ Error(s) in re-building vignettes:
+ --- re-building ‘dermatitis.Rmd’ using rmarkdown
+ Error: processing vignette 'dermatitis.Rmd' failed with diagnostics:
+ invalid 'x' type in 'x && y'
+ --- failed re-building ‘dermatitis.Rmd’
+ 
+ --- re-building ‘genetic_example.Rmd’ using rmarkdown
+ Error: processing vignette 'genetic_example.Rmd' failed with diagnostics:
+ invalid 'x' type in 'x && y'
+ --- failed re-building ‘genetic_example.Rmd’
+ 
+ --- re-building ‘outlier_intro.Rmd’ using rmarkdown
+ Error: processing vignette 'outlier_intro.Rmd' failed with diagnostics:
+ invalid 'x' type in 'x && y'
+ --- failed re-building ‘outlier_intro.Rmd’
+ 
+ SUMMARY: processing the following files failed:
+   ‘dermatitis.Rmd’ ‘genetic_example.Rmd’ ‘outlier_intro.Rmd’
```

SEMsens

```
+ * checking re-building of vignette outputs ... WARNING
+ Error(s) in re-building vignettes:
+ --- re-building ‘Hom-vignette.Rmd’ using rmarkdown
+ Loading required package: lavaan
+ This is lavaan 0.6-10
+ lavaan is FREE software! Please report any bugs.
+ Loading required package: SEMsens
+ Error: processing vignette 'Hom-vignette.Rmd' failed with diagnostics:
+ (converted from warning) invalid input found on input connection '/Users/runner/work/crandalf/crandalf/SEMsens.Rcheck/vign_test/SEMsens/vignettes/Hom-vignette.pdf'
+ --- failed re-building ‘Hom-vignette.Rmd’
```

**Comment by cderv** [comment]
I have rerun things. 

* **SEMsens** is not more an issue. It was fixed by #2282 - The merged commit was not there in the version I tested unfortunately. 

The two other are two investigate. I am looking at **gitdown** now.

**Comment by cderv** [comment]
# gitdown issue 

One of their tests needs to be updated as they are testing some HTML output and dev rmarkdown changes it due to #1964 where a Lua filter is now used instead of JS only. 

* CRAN rmarkdown

````
<h2><span class=\"header-section-number\">1.2</span> Issue: #1</h2>
````

* dev rmarkdown

````
<h2><span class=\"header-section-number\">1.2</span> Issue: #1<a href=\"section-issue.html#issue-1\" class=\"anchor-section\" aria-label=\"Anchor link to header\"></a></h2>
````

I'll contact the maintainer for this

**Comment by yihui** [comment]
I just pushed a workaround for the gitdown issue. It's a hack that I often use to avoid breaking tests in other packages. It won't block our release, and will also give other package authors time to patch their packages (they'll have to do it before they make their next CRAN submission).

**Comment by cderv** [comment]
And the other issue is actually and issue in our package 😓 

````
> rmarkdown::render("vignettes/dermatitis.Rmd")
Error in highlight_downlit && !xfun::loadable("downlit") : 
  invalid 'x' type in 'x && y'
````

Code is  from
https://github.com/rstudio/rmarkdown/blob/7e4ed620081040478dd8cdfe6847f9c359555558/R/html_document.R#L456

Vignette in yaml is 
````
  rmarkdown::html_vignette:
    highligh: zenburn
    toc: true
    fig_height: 4
    fig_width: 4
    fig_align: "center"
````

and `highlight_downlit` gets the value `zenburn`, I believe because partial matching of argument name when passed from `html_vignette` to `html_document`. We need to fix this on our side.

**Comment by cderv** [comment]
Oh no it is not that ! It is related though.

The package author uses `highligh` and not `highlight`. So it was silently ignored but now it is partially matched to the new argument. 

In fact, currently `highlight` can't be changed for `html_vignette()`
https://github.com/rstudio/rmarkdown/blob/7e4ed620081040478dd8cdfe6847f9c359555558/R/html_vignette.R#L68-L76
but we don't check the arguments. 

Several solution: 
* We could allow the highlight argument in vignette, could solve the issue.
* Check better for argument value (i.e `highlight_downlit` should be logical only). Then it would error and the vignette should be changed. 
* We could set `highlight_downlit` to FALSE explicitly in `html_vignette`. But not really needed for us. 

First one seems the right one to do. It should be ok to change the highlighting.

Anyway, I let you decide how you want to handle that as I won't do much before tomorrow on my side.

**Comment by cderv** [comment]
Thanks for the PR ! 

FWIW I have rechecked the 15 failed from https://github.com/rstudio/rmarkdown/issues/2321#issuecomment-1056720321 and all is ok.

**Comment by yihui** [comment]
Okay, I've added the `highlight` argument to `html_vignette()`. I think I can continue the release process now.
