### ISSUE TITLE
Issue with new 2.12 version and vignette building

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2324]
First reported @hadley as **ggplot2** CI is failing for oldrel-4 (R 3.4.4) during vignette creation. 
https://github.com/tidyverse/ggplot2/runs/5409764795?check_suite_focus=true#step:5:4808

I added 3 more R versions to tests **rmarkdown** (f46a1756c5ce5c0817c47ae92add7dbe03491c15) and I get the same issue: 
https://github.com/rstudio/rmarkdown/runs/5410652398?check_suite_focus=true

It seems there is something that changed between 3.4.4 et 3.5.3 that impact our new internal function usage. 

We need to look into and probably do a patch release - 2.12.1 ideally, but will be 2.13 with current scheme.

**Comment by hadley** [comment]
I'm guessing that the problem is using `pandoc_math_engines()` in an argument evaluated by `match.arg()`, which in 3.4 doesn't use the correct environment.

**Comment by cderv** [comment]
Using `force()` fix the issue

````r
diff --git a/R/pandoc.R b/R/pandoc.R
index c9eb2c29..4c85e554 100644
--- a/R/pandoc.R
+++ b/R/pandoc.R
@@ -483,7 +483,7 @@ pandoc_math_engines <- function() {
 }
 
 pandoc_math_args <- function(engine = pandoc_math_engines(), url = NULL) {
-
+  engine <- force(engine)
   engine <- match.arg(engine)
````

And rlang backtrace is 
````r
Error in pandoc_math_engines() : 
  could not find function "pandoc_math_engines"
Backtrace:
    ▆
 1. └─rmarkdown::render("vignettes/lua-filters.Rmd")
 2.   └─output_format$pre_processor(...)
 3.     └─rmarkdown base(...)
 4.       └─rmarkdown base(...)
 5.         └─rmarkdown:::add_math_support(math, template, lib_dir, output_dir)
 6.           └─rmarkdown:::pandoc_math_args(math$engine)
 7.             └─base::match.arg(engine)
 ````

**Comment by cderv** [comment]
However, `rlang::arg_match()` seems to work in that case

```diff
diff --git a/R/pandoc.R b/R/pandoc.R
index c9eb2c29..3a400450 100644
--- a/R/pandoc.R
+++ b/R/pandoc.R
@@ -483,8 +483,7 @@ pandoc_math_engines <- function() {
 }
 
 pandoc_math_args <- function(engine = pandoc_math_engines(), url = NULL) {
-
-  engine <- match.arg(engine)
+  engine <- rlang::arg_match(engine)
````

**Comment by cderv** [comment]
I should put the choice explicitly for `match.arg` probably like this as this works. 

````diff
diff --git a/R/pandoc.R b/R/pandoc.R
index c9eb2c29..1aeb02cd 100644
--- a/R/pandoc.R
+++ b/R/pandoc.R
@@ -482,9 +482,8 @@ pandoc_math_engines <- function() {
   c("mathjax", "mathml", "webtex", "katex", "gladtex")
 }
 
-pandoc_math_args <- function(engine = pandoc_math_engines(), url = NULL) {
-
-  engine <- match.arg(engine)
+pandoc_math_args <- function(engine, url = NULL) {
+  engine <- match.arg(engine, choices = pandoc_math_engines())
````

**Comment by hadley** [comment]
@cderv yeah that looks like a reasonable fix to me

**Comment by cderv** [comment]
**rmarkdown** 2.13 is now on CRAN - no binary build yet but source version contain the fix for this issue.

**Comment by hadley** [comment]
Awesome, thanks for working on this!
