### ISSUE TITLE
[FR] Animation in Microsoft word with rmarkdown 

### ISSUE THREAD

**Issue by WayneGitShell** [rstudio/rmarkdown#2326]
I work on an open source project www.gwsdat.net with the University of Glasgow. It is an R package with Shiny front end to analyse groundwater data and used by students, environmental engineers and regulators. 

It would be fantastic to be able to embed  animations from the app into a word document. I know you can do this in HTML and pdf - but the trouble here is that the document is not easily editable. 

I've previously asked the question here: https://community.rstudio.com/t/animation-in-microsoft-word-with-rmarkdown/97616/2  but had no response.

**Comment by cderv** [comment]
Hi, 

Sorry for missing your post on the community. I have reopen the discussion there to continue and will close here for now. We'll reopen if there is indeed an FR or an issue to fix. Thanks !
