### ISSUE TITLE
third footnote crashes PDF rendering

### ISSUE THREAD

**Issue by splaisan** [rstudio/rmarkdown#2333]
```
RStudio server 2021.09.2 Build 382 
knitr 1.37
```

I have this code in a RMD document which works until I add third footnote: https://www.ensembl.org/Gallus_gallus

<pre>
---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
---

\```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
\```

\footnote{https://github.com/lh3/bwa} 

\footnote{https://gatk.broadinstitute.org/hc/en-us/articles/360035535932-Germline-short-variant-discovery-SNPs-Indels-}

\footnote{https://www.ensembl.org/Gallus_gallus}

</pre>

When I replace the html of ref3 with [text](https://www.ensembl.org/Gallus) it knits 
The URL works until ''https://www.ensembl.org/Gallus'' but as soon as I add the following '_' it fails to knit with

```
! Missing $ inserted.
<inserted text> 
                $
l.80 \footnote{https://www.ensembl.org/Gallus_}
                                                and additional variant data 

Try to find the following text in test.Rmd:
  \footnote{https://www.ensembl.org/Gallus_} 

You may need to add $ $ around a certain inline R expression `r ` in test.Rmd (see the above hint). See https://github.com/rstudio/rmarkdown/issues/385 for more info.
Error: LaTeX failed to compile test.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test.log for more info.
Execution halted
```

Knitr does not seem to like chicken or underscores !?

Any help is welcome to fix this weirdness

**Comment by cderv** [comment]
I don't think this has anything to do with **knitr**. Having `_` in your `\footnote{}` in LaTeX is not supported without escaping. You could try without knitr to render to pdf a LaTeX file with this and you'll get an error. 

You need to escape 
````
\footnote{https://www.ensembl.org/Gallus\_gallus}
````

or you could also use `\url{}` in LaTeX that would mark the string as with potential special characters

````
\footnote{\url{https://www.ensembl.org/Gallus_gallus}}
````

You could also use Markdown syntax directly, which is all the benefit from R Markdown using Pandoc 
* https://bookdown.org/yihui/rmarkdown/markdown-syntax.html
* https://pandoc.org/MANUAL.html#footnotes

````markdown
---
title: "Untitled"
output:
  pdf_document: 
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

^[https://github.com/lh3/bwa]

^[https://gatk.broadinstitute.org/hc/en-us/articles/360035535932-Germline-short-variant-discovery-SNPs-Indels-]

^[https://www.ensembl.org/Gallus_gallus]
````

This would have deal for you about the special character, and you can see in the `tex` file that `\url{}` will be added for you. 

So afterall, a LaTeX issue - often the case when you are trying to use raw LaTeX in R Markdown document. 

Hope it helps understand

**Comment by splaisan** [comment]
thank you so much, it was so obvious, my brain did not click.
