### ISSUE TITLE
Wrapping existing text in a code block

### ISSUE THREAD

**Issue by jcpayne** [rstudio/rmarkdown#2341]
Hi.  I'm converting some long scripts (thousands of lines) into .Rmd files, in RStudio.  The scripts contain both code and documentation, and It's tedious to have to type the code block start and end (triple backtick{r} or {sql}, ...code..., triple backtick) for every code block.  

I know that the "Insert code chunk" shortcut (Option-Cmd-I on a Mac) will create a ready-made, empty code chunk; but I'm wondering if there is a way to wrap a new chunk around _existing_ text without having to copy and paste.  

It would also be great to have different pre-made chunks for R and SQL, for example, since I use them both.

Thanks.

**Comment by cderv** [comment]
Hi, 

this would be feature for the IDE directly to allow this. You should give a 👍 in the feature request: https://github.com/rstudio/rstudio/issues/2444

However, this can easily be done with extension feature that are RStudio Addin. Current workaround is using **remedy** for this
https://thinkr-open.github.io/remedy/#chunk

![](https://raw.githubusercontent.com/ThinkR-open/remedy/master/reference/figures/chunck.gif)

> It would also be great to have different pre-made chunks for R and SQL, for example, since I use them both.

Not sure to understand what you mean here. Juts in case it is related, know you can create some custom snippets with pre-filled chunk option that suits you: https://rstudio.github.io/rstudio-extensions/rstudio_snippets.html

Jope it helps

**Comment by jcpayne** [comment]
Thanks, brilliant!  I love remedy's ability to turn head(df) into a table, too.
