### ISSUE TITLE
Release rmarkdown 2.14

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2351]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_rmarkdown.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()` @yihui you will receive the result
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::cloud_check()`
* [ ] ~Update `cran-comments.md`~
* [ ] `git push`
* [ ] ~Draft blog post~
* [ ] ~Slack link to draft blog in #open-source-comms~

Submit to CRAN:

* [ ] `usethis::use_version('minor')`
* [ ] `devtools::submit_cran()` / `xfun::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `git push`
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version('patch')`
* [ ] `git push`
* [ ] ~Finish blog post~
* [ ] Tweet
* [ ] ~Add link to blog post in pkgdown news menu~

**Comment by cderv** [comment]
So here is some of the results. I think we are mainly good. As usual the package failing to check are because of installation problem in our coud service. 

## revdepcheck results

We checked 6410 reverse dependencies (6383 from CRAN + 27 from Bioconductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 0 new problems
 * We failed to check 9 packages

Issues with CRAN packages are summarised below.

### Failed to check

* CausalImpact (NA)
* iemisc       (NA)
* iemiscdata   (NA)
* loon.ggplot  (NA)
* loon.shiny   (NA)
* loon.tourr   (NA)
* nlmixr       (NA)
* SSVS         (NA)
* vivid        (NA)

**Comment by yihui** [comment]
Got you. I'll make the release later this afternoon. Thanks!
