### ISSUE TITLE
A power-off shutdwon while rendering `.RMD` file ruined the file

### ISSUE THREAD

**Issue by HossamGhorab** [rstudio/rmarkdown#2352]
Hi all

While rendering a `.Rmd` file, my PC shut down due to unexpected sudden power cut-off. 

As a result, the `.Rmd` file, the `.bib` bibliography, and the output `.docx` file got all missed up. The characters/text of the files is now unreadable using either Rstudio or Notepad++.  The `.Rmd` and `.bib` files text are now turned into a **single lengthy line of bad characters** as shown below. The `.docx` document is corrupted. 

![image](https://user-images.githubusercontent.com/62452366/165415675-455d66fc-bbbc-47aa-8cd4-86b64781ccec.png)
**What happened? And is there a way I can get convert these ruined files to my original pre-rendering files?**

Sincerely

**Comment by cderv** [comment]
Unfortunately, I really don't know what could have happen. I understand you don't have a copy or don't use version control ? 
About version control if you don't know about it: 
* https://inbo.github.io/git-course/static/presentations/git.pdf
* https://carpentries-incubator.github.io/open-science-with-r/08-git/index.html

I don't think this could be related to the **rmarkdown** 📦 directly. Probably more something related to the IDE or the OS directly. Are you on Windows ? 

I can try to have a look if you can send me the files though, but this is possible you can't revert that corruption

**Comment by HossamGhorab** [comment]
Fortunately, I have an earlier copy of the files. I'm asking mainly to see if the experts have a solution to such a rare problem, which may help others in the future. It may be the time to start using version control though.

Yes, I'm on Windows 10. I will send you the files on [christophe.dervieux@gmail.com](mailto:christophe.dervieux@gmail.com) 2 days from now, so that I can send you the both the corrupted and the earlier versions (maybe that will help).

I can't thank you enough.

**Comment by cderv** [comment]
> It may be the time to start using version control though.

I would say control version is now a must-do when doing data science. With integration in most of the IDE it is pretty easy to use, and it will be valuable even if you don't master all of its power. Just taking snapshot every day and have history shared in a remote repo is super valuable. 

> I will send you the files

ok. thanks

**Comment by cderv** [comment]
I'll close this as there is no issue with the **package**. But this will stay here in case anyone encounter the same.
