### ISSUE TITLE
Render line break in inline code?

### ISSUE THREAD

**Issue by albert-ying** [rstudio/rmarkdown#2355]
Hi, I'm trying to generate multiple lines from an R object in my **body text**. But I haven't found a way to do it.

For example

\```{r include = F}
a = "a, \n b, \n c"
\```

\`r a\`

### Desired output

a,

b,

c

### output rendered

a, b, c

I'm wondering if it is possible to do it in Rmarkdown? Thank you!

p.s., I knit to word format, if that is relevant;

I also tried with double '\n', still giving the same output.

**Comment by atusy** [comment]
For this kind of questions, we recommend ask on communities.
You should have seen suggestions on creating the issue like below.

![image](https://user-images.githubusercontent.com/30277794/166123220-f8c96ebd-996b-45ca-bb1f-4379c94be070.png)

Anyway, to answer your question, it is already possible.

You need to keep in mind that rendered texts are treated as **markdown**.
That means lines with single linebreaks are collapsed to a single sentence.
Double line breaks will separate lines into paragraphs.

````
```{r include = F}
a = "a, \n\n b, \n\n c"
```

`r a`
````

**Comment by albert-ying** [comment]
Ah, sorry for that! Thank you so much tho.
