### ISSUE TITLE
[FR] Option to add "Contents" Subsection Header Before GitHub Table of Contents

### ISSUE THREAD

**Issue by amarakon** [rstudio/rmarkdown#2356]
I want the ability for a "Contents" subsection header before the actual table of contents in `github_document` output appears, sort of like with `pdf_document` output:

```markdown
## Contents

*contents*
```

**Comment by cderv** [comment]
Are you looking for a TOC title ?  or other type of content ?

**Comment by amarakon** [comment]
Thank you, this worked.
