### ISSUE TITLE
Section headers with consecutive underscores (_) could mess up {section settings} in HTML output

### ISSUE THREAD

**Issue by zhuxr11** [rstudio/rmarkdown#2358]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

==========================================================

I discovered that section headers with consecutive underscores (_) could mess up section settings (wrapped in {} after the header) in HTML output.

For example, if I want to remove numbering of some sections with `{.unnumbered}` and prevent them from appearing in ToC with `{.unlisted}`, headers with two or more consecutive underscores will not let such settings take effect.

A minimal reprex:

````
---
title: "Untitled"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown

Let us see how consecutive underscores (_) affect header options:

## Subsetction 1 {.unlisted .unnumbered}

foo

## Subsection_2 {.unlisted .unnumbered}

bar

## Subsection__3 {.unlisted .unnumbered}

baz

## Subsection___4 {.unlisted .unnumbered}

uhh

````

This will knit into an HTML page like this:

```
Untitled
1 R Markdown
Let us see how consecutive underscores (_) affect header options:

Subsetction 1
foo

Subsection_2
bar

1.1 Subsection__3 {.unlisted .unnumbered}
baz

1.2 Subsection___4 {.unlisted .unnumbered}
uhh
```

We can see that section settings are not taking effect on "Subsection__3" and "Subsection___4".

Session info:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 2021.9.2.382

Locale:
  LC_COLLATE=Chinese (Simplified)_China.936 
  LC_CTYPE=Chinese (Simplified)_China.936   
  LC_MONETARY=Chinese (Simplified)_China.936
  LC_NUMERIC=C                              
  LC_TIME=Chinese (Simplified)_China.936    
system code page: 65001

Package version:
  base64enc_0.1.3 digest_0.6.29   evaluate_0.14   fastmap_1.1.0  
  glue_1.6.0      graphics_4.1.2  grDevices_4.1.2 highr_0.9      
  htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.2  knitr_1.37     
  magrittr_2.0.1  methods_4.1.2   rlang_0.4.12    rmarkdown_2.11 
  stats_4.1.2     stringi_1.7.6   stringr_1.4.0   tinytex_0.36   
  tools_4.1.2     utils_4.1.2     xfun_0.29       yaml_2.2.1     

Pandoc version: 2.14.0.3
```

This reprex showed the same results using the developmental version of Rmarkdown. Any insight into this?

**Comment by cderv** [comment]
This is probably because `_` has special meaning in markdown. It is a special character that you need to escape. 
Replace `_` by `\_` if you need to use a underscore. This should work.

**Comment by zhuxr11** [comment]
> This is probably because `_` has [special meaning in markdown](https://pandoc.org/MANUAL.html#emphasis). It is a special character that you need to escape. Replace `_` by `\_` if you need to use a underscore. This should work.

Thanks, I see.
