### ISSUE TITLE
[FR] `github_document` no longer needs to create images for math expressions

### ISSUE THREAD

**Issue by kylebutts** [rstudio/rmarkdown#2361]
Pretty excited about the news that GitHub now natively supports latex math expressions when displaying markdown documents. Thought I would flag as it might be nice to add an option to not parse $$ $$ into images for the `github_document` format (save from creating a lot of images in the GitHub repo)

https://github.blog/changelog/2022-05-19-render-mathematical-expressions-in-markdown/

$a^2 + b^2 = c^2$

$$
a^2 + b^2 = c^2
$$

**Comment by cderv** [comment]
Thanks a lot! I miss the information. Yes I'll think we'll default to this in `github_document` and still leave the option to opt-in webtex if desired.

**Comment by cderv** [comment]
I have open an issue upstream to help supporting this. Currently, Pandoc does not really allow math in `gfm`, except using webtex.
https://github.com/jgm/pandoc/issues/8085

**Comment by cderv** [comment]
Thanks @kylebutts. 

We've added support and made it the default now when Pandoc 2.10.1 is used.

**Comment by kylebutts** [comment]
Awesome! That'll be super helpful with statistics/econometrics packages' README!
