### ISSUE TITLE
`error=TRUE` not honored with certain ggplot2 errors

### ISSUE THREAD

**Issue by sjspielman** [rstudio/rmarkdown#2363]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

## Bug Report

I am filing this issue because I am observing circumstances where `error=TRUE` is not honored in code chunks. When the chunk contains `ggplot2` code _and_ the error is related to an incorrect `aes()` specification, it seems that rmarkdown is expecting to include an output image associated with that chunk. There should not be any image, because `error=TRUE`. Other errors in `ggplot2` code that are not related to incorrectly specified `aes()` arguments do not have this problem - `error=TRUE` is honored and the document knits. Similarly, base R `graphics` plots with errors do not prevent knitting. 

I have included here an Rmarkdown file and its rendered HTML with several chunks that demonstrate what I am seeing. I have commented out the chunks that prevent knitting in spite of `error=TRUE`. When I uncomment these chunks, the document does not render with errors that I include in the comments within.
[potential_bug.zip](https://github.com/rstudio/rmarkdown/files/8767001/potential_bug.zip)
Note that I originally observed this with `rmarkdown 2.14`, so I installed `2.14.1` and the problem remained (hence it's in the `sessionInfo()` in the rendered HTML.)

The Rmarkdown itself contains a `sessionInfo()` chunk relevant to what is in the environment during knitting, but either way I am also pasting my `sessionInfo()` from Console below:

```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.0   fastmap_1.1.0    cli_3.3.0        htmltools_0.5.2  tools_4.2.0     
 [6] yaml_2.3.5       rmarkdown_2.14.1 knitr_1.39       xfun_0.31        digest_0.6.29   
[11] rlang_1.0.2      evaluate_0.15   
```

**Comment by yihui** [comment]
@sjspielman That's really a great bug report! Should be fixed in the dev version of **evaluate** now:

```r
remotes::install_github('r-lib/evaluate')
```

Thanks!

@cderv If you have time, please help with adding tests to https://github.com/r-lib/evaluate/blob/main/tests/testthat/test-graphics.r At least we should expect

```r
evaluate::evaluate('library(ggplot2); ggplot(iris) +
  aes(x = Speciess, y = Sepal.Length) + 
  geom_boxplot()')

evaluate::evaluate('library(ggplot2); ggplot(iris) +
  aes(x = Species, y = Sepal.Length) + 
  geom_bar()')
```

not to contain recorded plots (because the plots are empty). Thanks!

**Comment by cderv** [comment]
I can add those tests yet. 

It is interesting to see though that I can't reproduce on windows the issues in the Rmd file shared. 
`error1-1.png` and `error2-1.png`  are created and on disk, so they are found and setting `error = TRUE` does not prevent knitting. Everything is included in the output, the errors and the empty graphics (as you would get in R console + Viewer)

Using dev version of **evaluate**, I get the no error as expected, and this time empty graphics are not included. 

Just wanted to share this. I'll add the test for the later case

**Comment by cderv** [comment]
> but the empty images were displayed as the icons for missing images

Ok. On my side, I had the images and the files, but blank image. Anyway, this is fixed.
