### ISSUE TITLE
Printing Regex "as is" inline

### ISSUE THREAD

**Issue by vivek-verma202** [rstudio/rmarkdown#2368]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
I define a vector of regex as follows:
![image](https://user-images.githubusercontent.com/33168572/171041457-8beec739-7487-485a-ba75-69c50d4f5afb.png)

Then I try printing that vector in a table cell, in Rmarkdown as follows:
![image](https://user-images.githubusercontent.com/33168572/171041643-a7b842f1-29a4-4399-b983-5b8b38bab759.png)

But when the html is rendered, the output looks like:
![image](https://user-images.githubusercontent.com/33168572/171041766-373fbcb4-63ee-4ae1-b65b-605fcbbe6273.png)

Trying with ```r instead of `r helps but the table is no more of appropriate width and overlaps with the ToC

- [ ] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?
```
> sessioninfo()
## R version 4.2.0 (2022-04-22 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19044)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.utf8 
## [2] LC_CTYPE=English_United States.utf8   
## [3] LC_MONETARY=English_United States.utf8
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.utf8    
## 
## attached base packages:
## [1] grid      stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## 
## other attached packages:
##  [1] mice_3.14.7       kableExtra_1.3.4  survey_4.1-1      Matrix_1.4-1     
##  [5] tableone_0.13.2   survminer_0.4.9   ggpubr_0.4.0      survival_3.3-1   
##  [9] magrittr_2.0.3    ggplot2_3.3.6     dplyr_1.0.9       data.table_1.14.2
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.8.3      svglite_2.1.0     lattice_0.20-45   tidyr_1.2.0      
##  [5] zoo_1.8-10        digest_0.6.29     utf8_1.2.2        R6_2.5.1         
##  [9] backports_1.4.1   labelled_2.9.1    evaluate_0.15     highr_0.9        
## [13] httr_1.4.3        pillar_1.7.0      rlang_1.0.2       rstudioapi_0.13  
## [17] car_3.0-13        jquerylib_0.1.4   rmarkdown_2.14    splines_4.2.0    
## [21] webshot_0.5.3     stringr_1.4.0     munsell_0.5.0     broom_0.8.0      
## [25] compiler_4.2.0    xfun_0.31         systemfonts_1.0.4 pkgconfig_2.0.3  
## [29] htmltools_0.5.2   mitools_2.4       tidyselect_1.1.2  tibble_3.1.7     
## [33] gridExtra_2.3     km.ci_0.5-6       codetools_0.2-18  viridisLite_0.4.0
## [37] fansi_1.0.3       crayon_1.5.1      withr_2.5.0       MASS_7.3-56      
## [41] jsonlite_1.8.0    xtable_1.8-4      gtable_0.3.0      lifecycle_1.0.1  
## [45] DBI_1.1.2         pacman_0.5.1      KMsurv_0.1-5      scales_1.2.0     
## [49] cli_3.3.0         stringi_1.7.6     carData_3.0-5     ggsignif_0.6.3   
## [53] xml2_1.3.3        bslib_0.3.1       ellipsis_0.3.2    survMisc_0.5.6   
## [57] generics_0.1.2    vctrs_0.4.1       forcats_0.5.1     tools_4.2.0      
## [61] glue_1.6.2        purrr_0.3.4       hms_1.1.1         abind_1.4-5      
## [65] fastmap_1.1.0     yaml_2.3.5        colorspace_2.0-3  rstatix_0.7.0    
## [69] rvest_1.0.2       haven_2.5.0       knitr_1.39        sass_0.4.1
```
- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
> Printing Regex "as is" inline

By printing "as is", you are explicitly saying to consider the output text as markdown syntax. You need to explicitly escape any character that will be otherwise interpreted as markdown syntax. Basically you need to mark this text as raw and as being not touch during Markdown to HTML conversion. 

> Then I try printing that vector in a table cell,

Which table framework are you using ? The way of escaping or marking as raw html output can depend on the tool used. 

I can't really give you an example as you provided screenshots and not code we can copy and run.

**Comment by vivek-verma202** [comment]
Thanks for the response, @cderv .
I am not using any special table framework but manually typing it within the .rmd file, so I guess, it's markdown. Manually escaping each special character s not an option as I intend to display the entire vector of regex in the report.

**Comment by cderv** [comment]
> I am not using any special table framework but manually typing it within the .rmd file, so I guess, it's markdown. 

So you are creating the table manually writing markdown syntax. Can you share a small reproducible example just to be sure I understand correctly ? 

> Manually escaping each special character s not an option as I intend to display the entire vector of regex in the report.

At the end, you are writing markdown syntax, so you need to escape somehow the markdown characters or tell pandoc to not process it as markdown

Possibly using ``` `raw content`{=html}``` would tell Pandoc to leave the raw content alone and not consider it as markdown. 

having a simple example would help.

**Comment by vivek-verma202** [comment]
Thanks @cderv ,
`raw content`{=html} worked !!
