### ISSUE TITLE
[FR] Add an Option Called lower-headers for github_document

### ISSUE THREAD

**Issue by amarakon** [rstudio/rmarkdown#2377]
This is for GitHub documents.
Since the top-level header (`#`) is only used for the title, you have to use second-level headers after that (`##`).
This is inconvenient since I will always set the title using the `title` option in the YAML metadata.
I would like an option to automatically lower all the headers.
For example, `#` becomes `##`, `##` becomes `###`, etc.
You can add a file called `lower-headers.lua`:

```lua
function Header(el)
  el.level = el.level + 1
  return el
end
```

Then you simply just have to include it in `pandoc_args` via `--lua-filters`.
This feature is great because it doesn't mess with anything before the main body of the document.
So the title section will still be a top-level header.
It seems appropriate to make this option enabled by default too, since I see no reason not to use it.

**Comment by cderv** [comment]
I think there is already an option for that in Pandoc called [`--shift-heading-level-by`](https://pandoc.org/MANUAL.html#option--shift-heading-level-by)

With this R Markdown content : 

````markdown
---
title: "Untitled"
output: 
  github_document:
    pandoc_args: --shift-heading-level-by=1
---

# First part

## Sub part

Content

# Another part

Content
`````

it will produce this markdown content

````markdown
Untitled
================

## First part

### Sub part

Content

## Another part

Content
````

I think usually people are not using `title` when output `github_document()` ([example](https://github.com/tidyverse/dplyr/blob/main/README.Rmd)) or are using `##` level headers and below only. 

But you could definitely use this option to do both (set `title` and then use `#` in your document). 

Is this what you need ?

**Comment by amarakon** [comment]
Thanks, this is exactly what I need.
