### ISSUE TITLE
navbar problems in output: html_document with theme version 5

### ISSUE THREAD

**Issue by guasi** [rstudio/rmarkdown#2379]
**The problem:** When there is a navbar in an html_document, the <style> element added via javascript to adjust the navbar is not added for the index page in bootstrap 5. This causes the header to hide under the navbar. Also, the active navbar is never highlighted when page is index. 

**_site.yml**
```
name: "my-website"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
output: 
  html_document:
    theme:
      version: 5
```

**index.Rmd**
```
---
title: "Index"
---
index here
```

**about.Rmd**
```
---
title: "About"
---
about here
```

The index page's header hides under the nav bar
<img width="285" alt="Screen Shot 2022-06-13 at 1 07 06 PM" src="https://user-images.githubusercontent.com/972487/173416982-9f3f1b62-a2c5-47b2-9f95-316f6076e084.png">

The about page displays correctly. The html outputs of the two pages look identical, but when comparing the pages through the browser's inspector, you see that a `<style>` element is missing in the index page. This element is produced by the javascript chunk with comment `// manage active state of menu based on current page`

Looking at the [default.html](https://github.com/rstudio/rmarkdown/tree/main/inst/rmd/h/default.html) document, it seems the problem is the javascript section between lines 269-298. There is a problem with menuAnchor, but I don't know what it is. I just know that the style element the JS adds is not added when in index.html, and that causes problems. When in index, the `document.head.appendChild(style)` does not add anything because `style` is empty.

```
> xfun::session_info('rmarkdown')
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 2022.2.3.492

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bslib_0.3.1     digest_0.6.29   evaluate_0.15   fastmap_1.1.0  
  fs_1.5.2        glue_1.6.2      graphics_4.2.0  grDevices_4.2.0 highr_0.9      
  htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.8.0  knitr_1.39      magrittr_2.0.3 
  methods_4.2.0   R6_2.5.1        rappdirs_0.3.3  rlang_1.0.2     rmarkdown_2.14 
  sass_0.4.1      stats_4.2.0     stringi_1.7.6   stringr_1.4.0   tinytex_0.39   
  tools_4.2.0     utils_4.2.0     xfun_0.31       yaml_2.3.5     

Pandoc version: 2.17.1.1
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Thanks a lot for this very useful issue report. 

There seems to be indeed a conflict with our JS and Bootstrap 5, specifically in this code
https://github.com/rstudio/rmarkdown/blob/f2bfeec501441abfa17b64fce12de7157bd75940/inst/rmd/h/default.html#L279-L280

There must be a new way to make a tabs active 🤔 

@cpsievert if you have insight on this as you added the code above in https://github.com/rstudio/rmarkdown/commit/64072ebfe0236f128fe02d61f89b23dcb8f52383 when moving to Boostrap 4 support in https://github.com/rstudio/rmarkdown/pull/1706 

thanks

**Comment by cderv** [comment]
If my understanding is correct, `menuAnchor.tab('show')` will call this part of **bslib** code 
https://github.com/rstudio/bslib/blob/a4946a49499438e71dce29c810a41e2d05170376/inst/bs3compat/js/bs3compat.js#L33-L39

So @cpsievert, I am relying on your insights : 
* is it possible that something is not correct in the compatibility layer in **bslib** ? 
* Do we need some specific adjustment in `default.html` for BS5 support ?

**Comment by cderv** [comment]
Great. I missed https://github.com/rstudio/bslib/issues/415 while looking into **bslib**. Probably wrong keyword search. I'll look at the PR and I agree that we should undo the workaround and do it properly as expected. We just need to insure backward compatibility from BS3 or do the change only for newer bootstrap if necessary

**Comment by cderv** [comment]
Thanks for the report @guasi !
