### ISSUE TITLE
InvalidUrlException when absolute path specified for output_dir on Windows

### ISSUE THREAD

**Issue by jrowen** [rstudio/rmarkdown#238]
When calling `render` and an specifying a absolute path for `output_dir` on a Windows machine

```
rmarkdown::render("c:/data/test.Rmd", output_dir = "c:/temp")
```

an `InvalidUrlException` exception is returned

```
pandoc.exe: Failed to retrieve c:/temp/test_files/figure-html/unnamed-chunk-2.png
InvalidUrlException "c:/temp/test_files/figure-html/unnamed-chunk-2.png" "Invalid scheme"
```

Relative paths work fine.

**Comment by yihui** [comment]
In general I'd recommend the `file.rename()` approach. My experience is that the `output_dir` and `output_file` arguments are quite fragile and should be avoided if possible. I have seen problems several times, e.g. it just happened yesterday at https://github.com/rstudio/shiny/issues/1831.
