### ISSUE TITLE
Python code and R code conflict in R Markdown

### ISSUE THREAD

**Issue by TomBener** [rstudio/rmarkdown#2383]
The full code is as followed:

````md
---
title: "This is a Title"
subtitle: "An implementation in R Markdown"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html:
    tufte_features: ["fonts", "background"]
---

```{r setup, include = FALSE}
# use Python in R Markdown
library(tufte)
library(reticulate)
use_python("/usr/bin/python3")

# install.packages("package name")
# import packages
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(showtext)
font_add("lxgw", "LXGWWenKai-Regular.ttf")
showtext_auto()
```
---

# Python Code

```{python}
# import libraries
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# load the data
df = pd.read_csv('moment.csv')
text = " ".join(key for key in df.keywords.astype(str))

# create the wordcloud
wordcloud = WordCloud(font_path = "LXGWWenKai-Regular.ttf",
                      width = 3000,
                      height = 1500,
                      max_font_size = 200,
                      max_words = 400,
                      background_color = "#fffff8",
                      collocations = False
                      ).generate(text)

plt.figure(figsize = (20,10))
plt.imshow(wordcloud, interpolation = "bilinear")

# show the image
plt.show(plt.axis("off"), plt.tight_layout(pad = 0))
```

# R code

```{r}
data <- read.csv('moment.csv')
sepdata = separate_rows(data, medium, sep = ", ")

df <-
  sepdata %>%
  count(medium) %>%
  mutate(perc = n / sum(n)) %>%
  mutate(labels = scales::percent(perc)) %>%
  arrange(desc(medium)) %>%
  mutate(text_y = cumsum(n) - n/2)

df %>%
  ggplot(aes(x = "", y = n, fill = medium)) +
  geom_col() +
  geom_label_repel(aes(label = labels, y = text_y),
                   force = 0.5,
                   nudge_x = 0.8,
                   nudge_y = 0.5,
                   size = 3,
                   show.legend = FALSE,
                   family = "lxgw") +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "Pastel2") +
  guides(fill = guide_legend(title = NULL)) +
  theme_void() +
  theme(text = element_text(family = "lxgw"))
```
````

When running the code above, warnings were printed as:

```
There were 50 or more warnings (use warnings() to see the first 50)
```

And the figure generated by `ggplot2` was not correct either. A long list of warnings was printed.

However, when changing the order of R code and Python code, everything will be okay. I guess it’s the issue of the package of `tidyr` and `pandas`. But it got me stuck on how to solve the problem. Does anyone have idea on the issue? Thanks in advance.

**Comment by TomBener** [comment]
I updated the example. And additional dataset and font file were uploaded below.

- [moment.csv](https://github.com/rstudio/rmarkdown/files/8915005/moment.csv)
- [LXGWWenKai-Regular.ttf](https://github.com/rstudio/rmarkdown/files/8915017/LXGWWenKai-Regular.zip)

And the output html:

- [python-r-conflict.html](https://github.com/rstudio/rmarkdown/files/8915033/python-r-conflict.zip)


@cderv Thanks for your reply, hope it helps for the issue.

**Comment by TomBener** [comment]
Thank you so much!

But unfortunately, I didn’t figure out what’s wrong with the issue on my side. And I have tried to uninstall the Python (3.10.0) on my system by [pyenv](https://github.com/pyenv/pyenv) and re-install the version you provided (Python 3.9.12) and required libraries. It didn’t make sense.

After trying for many times, I found a workaround to avoid the issue by moving the code to the setup code chunk, which was for separating rows from the package `tidyr`: `sepdata = separate_rows(data, medium, sep = ",\\s+")`.

Now, it works well for me. And thanks again! @cderv

**Comment by cderv** [comment]
OK. did you use same R package version too ? 

Anyway, it seems it is not an issue with **rmarkdown**. I'll close! 

Thanks

**Comment by TomBener** [comment]
Yeah. R package versions are consistent.

```
showtext_0.9-5  showtextdb_3.0  sysfonts_0.8.8  ggrepel_0.9.1
[5] ggplot2_3.3.6   tidyr_1.2.0     dplyr_1.0.9     reticulate_1.25
[9] tufte_0.12
```

**Comment by cderv** [comment]
That is strange. From your HTML, the warning you get is 
````
## Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : UTF-8
## decoding error for '��, ������'
````

So maybe something related to Encoding and different system. Possibly graphic devices too. If you get the issue only within R Markdown document, then maybe there is something on our side. If you get in R console too, then could be something else. 

Also are you on Windows ?  R 4.2.0 has improved regarding encoding by dealing with default encoding as UTF-8 now. Which fixes some things for sure.

Hope it helps

**Comment by TomBener** [comment]
I don’t really understand the encoding problem. But I use R 4.2.0 (2022-04-22) on macOS 12.4.
