### ISSUE TITLE
Fix daily pandoc check action on Ubuntu 

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2396]
https://github.com/rstudio/rmarkdown/runs/7743229397?check_suite_focus=true

It seems the daily pandoc binary is built on unbuntu 20 now and that cause issue on 18 where GLIBC 2.9 is not available. Or something like that. 

I need to look into that.

**Comment by yihui** [comment]
It seems the change should be simple enough like this? https://github.com/yihui/travis-bin/commit/1508c6fcffa4d3c84861cb489393fbd8afbd4a8a I wonder why we are using windows-latest and macos-latest but a fixed version of ubuntu.

**Comment by cderv** [comment]
Yes you are right. We should do that. I think we use 18 because I kept the version when migrated from Travis but using the latest should be fine. 

However, I think it is interested to check that pandoc will still be working on Ubuntu 18. I open this issue to remember to check in pandoc project why the change. 

You can make the change for this project to use latest though. Thanks!

**Comment by yihui** [comment]
Okay, I'll leave this issue to you then.
