### ISSUE TITLE
`colorlinks: yes` stopped working for PDF output

### ISSUE THREAD

**Issue by leowill01** [rstudio/rmarkdown#2397]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

# PROBLEM

It seems the `colorlinks: yes` option for PDF output is not working correctly after a recent update.
It was working correctly last week before I updated all my software & packages this past Monday.
I'm not sure if this is an issue with `rmarkdown`, `pandoc`, `knitr`, `RStudio`, or `bookdown`, but the render command shows `rmarkdown::render(...)` in the RStudio render tab, so I'm coming here first.

# REPREX

This minimal RMD example does not produce a PDF with red-colored TOC links or blue-colored hyperlinks as it was doing previously:

```
---
title: 'Title'

output:
  bookdown::pdf_document2:
    latex_engine: xelatex

colorlinks: yes # doesnt work as it recently used to
urlcolor: blue # doesnt do anything
---

`[^ TOC LINKS NOT COLORED RED AS EXPECTED]`

# Header

Some text.
This is a [hyperlink to Google](www.google.com). `[<- HYPERLINK NOT COLORED BLUE AS EXPECTED]`
```

I did notice that my `pandoc` version was in the recent update list, so I also tried straight pandoc using:

```bash
pandoc -f markdown -o out.pdf -V colorlinks=true doc.Rmd
pandoc -f markdown -o out.pdf -V colorlinks=true -V urlcolor=blue doc.Rmd
```

, but that doesn't work either.

# SESSION INFO

```
> sessionInfo()

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsthemes_0.3.1

loaded via a namespace (and not attached):
 [1] bookdown_0.28     prettyunits_1.1.1 ps_1.7.1          withr_2.5.0      
 [5] rprojroot_2.0.3   crayon_1.5.1      digest_0.6.29     R6_2.5.1         
 [9] evaluate_0.16     rlang_1.0.4       cli_3.3.0         curl_4.3.2       
[13] remotes_2.4.2     rstudioapi_0.13   callr_3.7.1       rmarkdown_2.14.3 
[17] tools_4.2.1       processx_3.7.0    xfun_0.32         yaml_2.3.5       
[21] fastmap_1.1.0     compiler_4.2.1    pkgbuild_1.3.1    htmltools_0.5.3  
[25] knitr_1.39
```

```
> xfun::session_info('rmarkdown')

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5, RStudio 2022.7.1.554

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3  bslib_0.4.0      cachem_1.0.6     digest_0.6.29    evaluate_0.16    fastmap_1.1.0    fs_1.5.2         glue_1.6.2       graphics_4.2.1  
  grDevices_4.2.1  highr_0.9        htmltools_0.5.3  jquerylib_0.1.4  jsonlite_1.8.0   knitr_1.39       magrittr_2.0.3   memoise_2.0.1    methods_4.2.1   
  R6_2.5.1         rappdirs_0.3.3   rlang_1.0.4      rmarkdown_2.14.3 sass_0.4.2       stats_4.2.1      stringi_1.7.8    stringr_1.4.0    tinytex_0.40    
  tools_4.2.1      utils_4.2.1      xfun_0.32        yaml_2.3.5      

Pandoc version: 2.19

```

**Comment by yihui** [comment]
I just discovered [your bug report to pandoc](https://github.com/jgm/pandoc/issues/8226) (which has been fixed there) while trying to debug this issue. I'll truly appreciate it if you could let us know you have reported the same issue elsewhere. Thank you very much!

**Comment by yihui** [comment]
Pandoc 2.19.1 has been released, which has included the fix: https://github.com/jgm/pandoc/releases/tag/2.19.1
