### ISSUE TITLE
Python errors with `error=TRUE` fails to knit

### ISSUE THREAD

**Issue by chendaniely** [rstudio/rmarkdown#2401]
When using Python chucks in an Rmd document:
Python code that we expect to fail, but want to display the error message fails on knit even when setting the `error=TRUE` knitr chunk option.
The expected behavior is the same as R, where the code will fail, and the failure message will be captured and rendered in the document.

(I know quarto is a separate process, but this behaviour works as expected there)

![image](https://user-images.githubusercontent.com/5782147/185971212-c0d8b84e-7a90-4956-8c75-8387d217928d.png)

### Reprex

`````
---
output: html_document
---

```{python, error=TRUE}
# this works
3 + 3
```

```{python, error=TRUE}
# this fails to knit, supposed to show message below
3 + 
```

```
SyntaxError: invalid syntax (<string>, line 1)
```
`````

### Session Info:

```
> xfun::session_info('rmarkdown')
R version 4.1.3 (2022-03-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.5, RStudio 2022.10.0.9

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bslib_0.4.0     cachem_1.0.6    digest_0.6.29   evaluate_0.16   fastmap_1.1.0  
  fs_1.5.2        glue_1.6.2      graphics_4.1.3  grDevices_4.1.3 highr_0.9       htmltools_0.5.3
  jquerylib_0.1.4 jsonlite_1.8.0  knitr_1.39      magrittr_2.0.3  memoise_2.0.1   methods_4.1.3  
  R6_2.5.1        rappdirs_0.3.3  rlang_1.0.4     rmarkdown_2.15  sass_0.4.2      stats_4.1.3    
  stringi_1.7.8   stringr_1.4.0   tinytex_0.40    tools_4.1.3     utils_4.1.3     xfun_0.32      
  yaml_2.3.5     

Pandoc version: 2.19
```

**Comment by cderv** [comment]
I believe you are encountering this issue : https://github.com/rstudio/reticulate/issues/583

Python code chunk in **rmarkdown** are using the **reticulate** python engine and issue are probably from there. 

I'll close this issue and it should be followed there.

**Comment by yihui** [comment]
As I replied in https://github.com/rstudio/reticulate/issues/583, this shouldn't be hard to implement in **reticulate**. I hope someone could contribute a PR there :)

**Comment by yihui** [comment]
It has been fixed in the dev version of **reticulate**.
