### ISSUE TITLE
[html_document] no images when self_contained: true

### ISSUE THREAD

**Issue by conig** [rstudio/rmarkdown#2403]
Hi, since updating to Pandoc 2.19.1 images are not appering in self-contained html_documents.

Reproducible example:

````
---
output: 
  html_document:
    self_contained: true
---

## Figure

```{r pressure}
plot(pressure)
```
````

![image](https://user-images.githubusercontent.com/12742211/186061407-a3a2ea83-ad38-407e-81ce-875a82aaaebb.png)

Setting self_contained: false restores expected functionality

````
---
output: 
  html_document:
    self_contained: false
---

## Figure

```{r pressure}
plot(pressure)
```
````
![image](https://user-images.githubusercontent.com/12742211/186061252-cb0614f6-6fc1-4004-89ff-517c6b90a7f3.png)

```
xfun::session_info('rmarkdown')
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22000)
#> 
#> Locale:
#>   LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8   
#>   LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                      
#>   LC_TIME=English_Australia.utf8    
#> 
#> Package version:
#>   base64enc_0.1.3  bslib_0.4.0      cachem_1.0.6     digest_0.6.29   
#>   evaluate_0.16    fastmap_1.1.0    fs_1.5.2         glue_1.6.2      
#>   graphics_4.2.1   grDevices_4.2.1  highr_0.9        htmltools_0.5.3 
#>   jquerylib_0.1.4  jsonlite_1.8.0   knitr_1.39       magrittr_2.0.3  
#>   memoise_2.0.1    methods_4.2.1    R6_2.5.1         rappdirs_0.3.3  
#>   rlang_1.0.4      rmarkdown_2.15.2 sass_0.4.2       stats_4.2.1     
#>   stringi_1.7.6    stringr_1.4.1    tinytex_0.41     tools_4.2.1     
#>   utils_4.2.1      xfun_0.32        yaml_2.3.5      
#> 
#> Pandoc version: 2.19.1
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by yihui** [comment]
This is a Pandoc bug and has been fixed: https://github.com/jgm/pandoc/releases/tag/2.19.2

**Comment by conig** [comment]
Thanks for fast response, that fixed it.
