### ISSUE TITLE
Rmarkdown `site_generator` case sensitivity.

### ISSUE THREAD

**Issue by kamalsacranie** [rstudio/rmarkdown#2409]
> Relevant GitHub repo located [here](https://github.com/kamalsacranie/rmarkdown-sitegen-exmp). The `bookdown` source files are located in `working-files/book/`.

The gist of the issue is that, at least in my `renv` environment, `rmarkdown` can only find the site generator indicated by

```{yaml}
site: bookdown::bookdown_site
```

in `index.rmd` when the file extension is `Rmd`. I.e. `rmarkdown` is file extension case sensitive when looking for the site generator. This occurs when I run `rmarkdown::render_site`

My scenario should be reproducible using the indicated GitHub repo.

I am using the latest `remotes` version of `rmarkdown` and `bookdown`

---

`fun::session_info`:

```
> xfun::session_info()
R version 4.2.0 (2022-04-22)
Platform: aarch64-apple-darwin21.3.0 (64-bit)
Running under: macOS Monterey 12.1

Locale: en_GB.UTF-8 / en_GB.UTF-8 / en_GB.UTF-8 / C / en_GB.UTF-8 / en_GB.UTF-8

Package version:
  compiler_4.2.0  graphics_4.2.0  grDevices_4.2.0 renv_0.15.5
  stats_4.2.0     tools_4.2.0     utils_4.2.0     xfun_0.32
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by kamalsacranie** [comment]
The thinking is that, even if naming your files in lowercase `rmd` is not best practice, the `rmarkdown` package should surely not be broken by this simple case difference.

**Comment by kamalsacranie** [comment]
In this case I have used `bookdown::bookdown_site` but I also tried `rmarkdown::default_site` (which doesn't actually exist) which should eliminate the dependency on bookdown. In this case, there is identical behaviour whereby the `rmarkdown::render_site` function does not locate the input file if the extension is in lower-case but does if it is in the `Rmd` extension (images below).

Figure 1: unable to find site generator

<img width="676" alt="image" src="https://user-images.githubusercontent.com/66880161/188726414-1f1899e5-1049-4f86-9b14-5ba33cf9f4a9.png">

Figure 2: now finds the file but can't run the site generator function

<img width="804" alt="image" src="https://user-images.githubusercontent.com/66880161/188726784-a95329d5-319c-4314-b627-90d83647cdbf.png">

> Note the file extension in each figure

**Comment by cderv** [comment]
Thank you - I'll look closer into this on **rmarkdown** side.
