### ISSUE TITLE
Rmarkdown Notebooks try to change the working directory even after it has been specified. 

### ISSUE THREAD

**Issue by mlane3** [rstudio/rmarkdown#2415]
![image](https://user-images.githubusercontent.com/1785885/193439666-bfcfdbc2-7deb-431b-b189-180af9032770.png)

This is a really annoying bug.

I have noticed for some reason in the latest version of R-markdown constantly tried to "switch" or change my working directory from a project or master folder to what it thinks should be an fair directory for an individual. 

I have to user certain directory as a my project folder in order to meet organizational requirements for collaboration on R markdown documents.   Other files in document will crash if I deviate from that standard. 

 I have tried [https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html](https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html)

**Comment by cderv** [comment]
I believe this would be an issue with RStudio IDE itself and not just **rmarkdown**. We did not change anything in the `html_notebook` format recently, maybe the IDE did some changes in behavior. 

Please open an issue there about this : https://github.com/rstudio/rstudio/issues/new/choose

Thanks you !

**Comment by mlane3** [comment]
Thanks,  I will do :D
