### ISSUE TITLE
R Markdown with a chunk name containing a # causes images to be located in the temporary directory and not render

### ISSUE THREAD

**Issue by pete-arnold** [rstudio/rmarkdown#2430]
Images are missing from HTML and Word output. HTML contains img with src to temporary folder which is deleted rather than data.

**Error in RStudio render window:**
...
output file: untitled.knit.md

[WARNING] Could not fetch resource untitled_files/figure-html/BROKEN

Output created: untitled.html

**HTML output snippet:**
...
<html>
<body>

plot(perf, avg= &quot;threshold&quot;, colorize=TRUE, lwd= 3,
  | main= &quot;With ROCR you can produce standard plots like ROC curves ...&quot;)</code></pre>
  | <p><img src="untitled_files/figure-html/BROKEN#1-1.png" width="672" /></p>
 

<br class="Apple-interchange-newline">
</body>
</html>plot(perf, avg= &quot;threshold&quot;, colorize=TRUE, lwd= 3,
           main= &quot;With ROCR you can produce standard plots like ROC curves ...&quot;)</code></pre>
<p><img src="[untitled_files/figure-html/BROKEN#1-1.png](https://github.com/rstudio/rmarkdown/issues/untitled_files/figure-html/BROKEN#1-1.png)" width="672" /></p>

...

**Markdown code:**
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r BROKEN#1}
library(ROCR)
data(ROCR.hiv)

pp <- ROCR.hiv$hiv.svm$predictions[[1]]

ll <- ROCR.hiv$hiv.svm$labels[[1]]

pred<- prediction(pp, ll)

perf <- performance(pred, "tpr", "fpr")

plot(perf, avg= "threshold", colorize=TRUE, lwd= 3,
           main= "With ROCR you can produce standard plots like ROC curves ...")
```

**Comment by cderv** [comment]
Hello, 

Please try to follow issue guide linked and format your code correctly - https://yihui.org/issue/#please-format-your-issue-correctly

Especially because it seems you are talking about R code chunk label issue. 

> R Markdown with a chunk name containing a #

From this in title, I assume that you have `#` in the code chunk. This is not supported, especially for figures when label is used as filename usually, and `#` in filename does not always play well. 

As mentioned in doc: https://bookdown.org/yihui/rmarkdown/r-code.html

> There is an optional chunk option that does not take any value, which is the chunk label. It should be the first option in the chunk header. **Chunk labels are mainly used in filenames of plots and cache**. If the label of a chunk is missing, a default one of the form unnamed-chunk-i will be generated, where i is incremental. **I strongly recommend that you only use alphanumeric characters (a-z, A-Z and 0-9) and dashes (-) in labels**, because they are not special characters and will surely work for all output formats. Other characters, spaces and underscores in particular, may cause trouble in certain packages, such as bookdown.

So please try without the `#`

thank you
