### ISSUE TITLE
Breakage caused by Pandoc 3.0.1

### ISSUE THREAD

**Issue by yihui** [rstudio/rmarkdown#2450]
I received an email from CRAN notifying me of breakage of several packages caused by Pandoc 3.0.1. It seems Pandoc 3.0.1 is having trouble with certain `.bib` files. A few examples:

## GREMLINS

Problem: https://www.stats.ox.ac.uk/pub/bdr/M1mac/GREMLINS.out

https://github.com/GrossSBM/GREMLINS/blob/3fb0d3f213bae9c729a47b9437791ab2f6c14697/vignettes/biblio.bib#L97

## ANOVAreplication

Problem: https://www.stats.ox.ac.uk/pub/bdr/M1mac/ANOVAreplication.out

I don't know what's wrong with this bib file: https://github.com/cran/ANOVAreplication/blob/master/vignettes/Library_Marielle.bib

## Full list

| package | source | problem |
|--|--|--|
| [ANOVAreplication](https://cran.r-project.org/package=ANOVAreplication) | [cran/ANOVAreplication](https://github.com/cran/ANOVAreplication) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/ANOVAreplication.out |
| [GREMLINS](https://cran.r-project.org/package=GREMLINS) | [cran/GREMLINS](https://github.com/cran/GREMLINS) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/GREMLINS.out |
| [MLML2R](https://cran.r-project.org/package=MLML2R) | [cran/MLML2R](https://github.com/cran/MLML2R) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/MLML2R.out |
| [MODIStsp](https://cran.r-project.org/package=MODIStsp) | [cran/MODIStsp](https://github.com/cran/MODIStsp) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/MODIStsp.out |
| [MTA](https://cran.r-project.org/package=MTA) | [cran/MTA](https://github.com/cran/MTA) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/MTA.out |
| [MatchIt](https://cran.r-project.org/package=MatchIt) | [cran/MatchIt](https://github.com/cran/MatchIt) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/MatchIt.out |
| [RGCCA](https://cran.r-project.org/package=RGCCA) | [cran/RGCCA](https://github.com/cran/RGCCA) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/RGCCA.out |
| [RGENERATEPREC](https://cran.r-project.org/package=RGENERATEPREC) | [cran/RGENERATEPREC](https://github.com/cran/RGENERATEPREC) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/RGENERATEPREC.out |
| [RNeXML](https://cran.r-project.org/package=RNeXML) | [cran/RNeXML](https://github.com/cran/RNeXML) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/RNeXML.out |
| [SourceSet](https://cran.r-project.org/package=SourceSet) | [cran/SourceSet](https://github.com/cran/SourceSet) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/SourceSet.out |
| [TOSTER](https://cran.r-project.org/package=TOSTER) | [cran/TOSTER](https://github.com/cran/TOSTER) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/TOSTER.out |
| [TreeSearch](https://cran.r-project.org/package=TreeSearch) | [cran/TreeSearch](https://github.com/cran/TreeSearch) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/TreeSearch.out |
| [TrenchR](https://cran.r-project.org/package=TrenchR) | [cran/TrenchR](https://github.com/cran/TrenchR) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/TrenchR.out |
| [bootf2](https://cran.r-project.org/package=bootf2) | [cran/bootf2](https://github.com/cran/bootf2) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/bootf2.out |
| [breathtestcore](https://cran.r-project.org/package=breathtestcore) | [cran/breathtestcore](https://github.com/cran/breathtestcore) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/breathtestcore.out |
| [codyn](https://cran.r-project.org/package=codyn) | [cran/codyn](https://github.com/cran/codyn) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/codyn.out |
| [colorSpec](https://cran.r-project.org/package=colorSpec) | [cran/colorSpec](https://github.com/cran/colorSpec) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/colorSpec.out |
| [colorspace](https://cran.r-project.org/package=colorspace) | [cran/colorspace](https://github.com/cran/colorspace) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/colorspace.out |
| [cricketdata](https://cran.r-project.org/package=cricketdata) | [cran/cricketdata](https://github.com/cran/cricketdata) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/cricketdata.out |
| [dogesr](https://cran.r-project.org/package=dogesr) | [cran/dogesr](https://github.com/cran/dogesr) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/dogesr.out |
| [indicspecies](https://cran.r-project.org/package=indicspecies) | [cran/indicspecies](https://github.com/cran/indicspecies) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/indicspecies.out |
| [itp](https://cran.r-project.org/package=itp) | [cran/itp](https://github.com/cran/itp) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/itp.out |
| [lifecontingencies](https://cran.r-project.org/package=lifecontingencies) | [cran/lifecontingencies](https://github.com/cran/lifecontingencies) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/lifecontingencies.out |
| [mable](https://cran.r-project.org/package=mable) | [cran/mable](https://github.com/cran/mable) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/mable.out |
| [prevtoinc](https://cran.r-project.org/package=prevtoinc) | [cran/prevtoinc](https://github.com/cran/prevtoinc) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/prevtoinc.out |
| [sylly](https://cran.r-project.org/package=sylly) | [cran/sylly](https://github.com/cran/sylly) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/sylly.out |
| [vegclust](https://cran.r-project.org/package=vegclust) | [cran/vegclust](https://github.com/cran/vegclust) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/vegclust.out |

## Warnings

| package | source | problem |
|--|--|--|
| [MorphoTools2](https://cran.r-project.org/package=MorphoTools2) | [cran/MorphoTools2](https://github.com/cran/MorphoTools2) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/MorphoTools2.out |
| [RFmerge](https://cran.r-project.org/package=RFmerge) | [cran/RFmerge](https://github.com/cran/RFmerge) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/RFmerge.out |
| [VARMER](https://cran.r-project.org/package=VARMER) | [cran/VARMER](https://github.com/cran/VARMER) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/VARMER.out |
| [VedicDateTime](https://cran.r-project.org/package=VedicDateTime) | [cran/VedicDateTime](https://github.com/cran/VedicDateTime) | https://www.stats.ox.ac.uk/pub/bdr/M1mac/VedicDateTime.out |

**Comment by yihui** [comment]
I've finally finished examining all packages above. The main problem has been fixed in pandoc nightly: https://github.com/jgm/pandoc/issues/8604

For packages in the "Warnings" section above, the problems were caused by raw tex code and HTML tags in title/date fields in YAML. I've sent PRs to packages that can be found on Github:

- https://github.com/MarekSlenker/MorphoTools2/pull/3
- https://github.com/hzambran/RFmerge/pull/9
- https://github.com/prajwalkpatil/VedicDateTime/pull/10

**Comment by cderv** [comment]
Awesome ! Thank you @yihui. I missed this Pandoc issue and fix. Hopefully they'll make a release.

**Comment by yihui** [comment]
They have released Pandoc 3.1: https://github.com/jgm/pandoc/releases/tag/3.1

**Comment by yihui** [comment]
All bibliography errors are gone. I have emailed the maintainers of the four packages in the Warnings section, so there is nothing left for us to do now.
