### ISSUE TITLE
Long figure caption causing footnote to skip a number in RMarkdown file (PDF/Latex)

### ISSUE THREAD

**Issue by melissagwolf** [rstudio/rmarkdown#2456]
**Having a long figure caption in an Rmarkdown file is causing the footnote numbering to skip a number:**

````markdown
---
title: "Untitled"
output: pdf_document
date: "2023-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a sentence with a footnote \footnote{Footnote 1}.

```{r fig1, echo=FALSE, warning=FALSE, message=FALSE,out.width="50%", fig.cap="This is a
long figure caption. This is a long figure caption. This is a long figure caption. This is a 
long figure caption. \\protect\\footnotemark"}

plot(mtcars$mpg)
```

\footnotetext{Footnote 2}

This is a sentence with a third footnote \footnote{Footnote 3}.
````

**This causes it to skip footnote 2:**

[![Rmarkdown output displaying a skipped footnote number][1]][1]

[![Bottom of Rmarkdown file displaying a skipped footnote number][2]][2]

**This does not happen with shorter figure captions.**

  [1]: https://i.stack.imgur.com/XxGrf.png
  [2]: https://i.stack.imgur.com/XylA2.png

---

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621), RStudio 2022.12.0.353

Locale:
  LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
  LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
  LC_TIME=English_United States.utf8    

Package version:
  base64enc_0.1.3   bslib_0.4.2       cachem_1.0.7      cli_3.5.0         digest_0.6.31    
  ellipsis_0.3.2    evaluate_0.20     fastmap_1.1.0     fontawesome_0.5.0 fs_1.6.1         
  glue_1.6.2        graphics_4.2.2    grDevices_4.2.2   highr_0.10        htmltools_0.5.4  
  jquerylib_0.1.4   jsonlite_1.8.4    knitr_1.42        lifecycle_1.0.3   magrittr_2.0.3   
  memoise_2.0.1     methods_4.2.2     mime_0.12         R6_2.5.1          rappdirs_0.3.3   
  rlang_1.0.6       rmarkdown_2.20.1  sass_0.4.5        stats_4.2.2       stringi_1.7.12   
  stringr_1.5.0     tinytex_0.44      tools_4.2.2       utils_4.2.2       vctrs_0.5.2      
  xfun_0.36         yaml_2.3.6       

Pandoc version: 2.19.2

**Comment by cderv** [comment]
I believe this is an issue or limitation of LaTeX itself
https://tex.stackexchange.com/questions/433322/why-does-latex-step-the-footnote-counter-twice-in-a-two-line-caption

It seems using footnote in caption with latex is tricky https://texfaq.org/FAQ-ftncapt

This is really a LaTeX problem and maybe there is a solution. If one is found in LaTeX, then it could probably applied easily.

**Comment by yihui** [comment]
Sorry I'm not familiar with this problem...

**Comment by cderv** [comment]
@melissagwolf I am not sure we can be of further help here. It seems an issue with LaTeX directly. Maybe someone passing by will have more insight. Otherwise, I am suggestion asking about this on TeX Q&A website maybe.

**Comment by melissagwolf** [comment]
Thanks for trying and for explaining the issue! You can close this.
