### ISSUE TITLE
`output_file` relative path causes `render` function fatal error in Windows

### ISSUE THREAD

**Issue by cloudy-sfu** [rstudio/rmarkdown#2464]
In the Windows system, assume there is an R markdown file `lab_1/main.Rmd` relative to your working directory. Write anything in it. Then, run these codes in the R command line (in your working directory):

```
rmd_path = 'lab_1/main.Rmd'
library(rmarkdown)
html_path = with_ext(rmd_path, 'html')
render(rmd_path, output_file = html_path)
```

It says `Error: The directory 'lab_1' does not not exist.` (The error message has two "not", it's not my typo, and you can address the line causing the problem easily).

My debug attempt is shown as follows. In Lines 54-57 of `render` function:

```
    if (!is.null(output_dir)) {
        if (!dir_exists(output_dir)) 
            dir.create(output_dir, recursive = TRUE)
        output_dir <- normalize_path(output_dir)
    }
```

If `output_dir` is the default value `null`, it doesn't cause any problem. But if we assign a relative path to `output_dir`, the `normalize_path` will convert it to something like this:

```
C:/Users/Administrator/Documents/lab_1/main.Rmd
```

In Lines 153-155:

```
    output_dir <- dirname(output_file)
    if (!dir_exists(output_dir)) {
        stop2("The directory '", output_dir, "' does not not exist.")
    }
```

The `dir_exists` function returns `FALSE` for any path which uses slash in Windows, whereas `dir_exists` thinks a path should use backslash!

The session information:

```
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Locale:
  LC_COLLATE=English_United States.utf8 
  LC_CTYPE=English_United States.utf8   
  LC_MONETARY=English_United States.utf8
  LC_NUMERIC=C                          
  LC_TIME=English_United States.utf8    

Package version:
  base64enc_0.1.3 bslib_0.4.2     cachem_1.0.7    cli_3.6.0      
  digest_0.6.31   ellipsis_0.3.2  evaluate_0.20   fastmap_1.1.1  
  fs_1.6.1        glue_1.6.2      graphics_4.2.3  grDevices_4.2.3
  highr_0.10      htmltools_0.5.4 jquerylib_0.1.4 jsonlite_1.8.4 
  knitr_1.42      lifecycle_1.0.3 magrittr_2.0.3  memoise_2.0.1  
  methods_4.2.3   mime_0.12       R6_2.5.1        rappdirs_0.3.3 
  rlang_1.1.0     rmarkdown_2.20  sass_0.4.5      stats_4.2.3    
  stringi_1.7.12  stringr_1.5.0   tinytex_0.44    tools_4.2.3    
  utils_4.2.3     vctrs_0.6.0     xfun_0.37       yaml_2.3.7     

Pandoc version: 3.1.1
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?
- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
First, Thanks for the typo finding ! 

Regarding your main issue here, I believe this is directly related to https://github.com/rstudio/rmarkdown/issues/2370

See my answer there https://github.com/rstudio/rmarkdown/issues/2370#issuecomment-1147609190 about `output_dir` and `output_file`

**Comment by cderv** [comment]
> The dir_exists function returns FALSE for any path which uses slash in Windows, whereas dir_exists thinks a path should use backslash!

Are you refering to this that needs fixing ? `dir_exists()` works with slash on Windows too 

````
> dir.create("dummy/examples", recursive = TRUE)
> rmarkdown:::dir_exists("dummy/examples")
[1] TRUE
> unlink("dummy", recursive = TRUE)
````

In your example, `render(rmd_path, output_file = html_path)` you only called `output_file` and not `output_dir` so this part of the code where you mentioned `dir_exists` is not run 
````r
    if (!is.null(output_dir)) {
        if (!dir_exists(output_dir)) 
            dir.create(output_dir, recursive = TRUE)
        output_dir <- normalize_path(output_dir)
    }
````

What exactly do you think the issue is ? 

> Also, it's quite redundant that the function uses both output_dir and output_file.

Maybe, but this will not change. Paths handling is quite complicated already - `output_dir` and `output_file` needs to be used together depending on what to do. Also doing path operation (renaming, moving, copying) after `render()` is still the best way to avoid any issue. Sorry for that. 

We tried to explained in the doc of argugments https://rmarkdown.rstudio.com/docs/reference/render.html

> output_file
> The name of the output file. If using NULL then the output filename will be based on filename for the input file. If a filename is provided, a path to the output file can also be provided. Note that the output_dir option allows for specifying the output file path as well, however, if also specifying the path, the directory must exist. If output_file is specified but does not have a file extension, an extension will be automatically added according to the output format. To avoid the automatic file extension, put the output_file value in [I](https://rdrr.io/r/base/AsIs.html)(), e.g., I('my-output').

> output_dir
> The output directory for the rendered output_file. This allows for a choice of an alternate directory to which the output file should be written (the default output directory of that of the input file). If a path is provided with a filename in output_file the directory specified here will take precedence. Please note that any directory path provided will create any necessary directories if they do not exist.

**Comment by cderv** [comment]
> Please mention the relationship of output_file and input

Yes this https://github.com/rstudio/rmarkdown/issues/2370 we'll do that. 

Thanks !
