### ISSUE TITLE
`shiny_prerendered_option_hook` no longer works since xfun 0.38 version

### ISSUE THREAD

**Issue by andreahgsin** [rstudio/rmarkdown#2469]
Since the [new version 0.38](https://github.com/yihui/xfun/blob/main/NEWS.md) of `xfun` and the modification of the function `xfun::is_blank`, this code no longer works : 

https://github.com/rstudio/rmarkdown/blob/c2d165ac18bd448619d4e6fc69754e81aed8a5ba/R/shiny_prerendered.R#L487

To have the same behavior, it should be replaced by ` if (all(xfun::is_blank(options$code)))` as suggested in the NEWS.md of xfun package.

Example : 

```
---
title: "Hello Prerendered Shiny"
output: html_document
runtime: shiny_prerendered
---

```{r, echo=FALSE}
sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r, context="server"}
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```

Thank you in advance !

**Comment by yihui** [comment]
Ah, too bad that I didn't discover this in the revdep checks. I'll fix it in a minute. Thank you so much!
