### ISSUE TITLE
`beamer_presentation` does not resolve latex_dependencies

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#2478]
````markdown
---
output: 
  pdf_document:
    keep_tex: true
    keep_md: true
---

```{r}
knitr::asis_output("", meta = list(rmarkdown::latex_dependency("longtable")))
```

\begin{longtable}{r|r}
\hline
speed & dist\\
\hline
4 & 2\\
\end{longtable}

````

This will throw: 
````
output file: test.knit.md

! LaTeX Error: Environment longtable undefined.
````

`pdf_document` does not. This is because we don't resolve depdencies in `beamer_presentation` format. 

`extra_dependencies` is not even allowed argument

Initially from https://community.rstudio.com/t/apparent-bug-in-rmarkdown-to-beamer-using-gt/164778

**Comment by setgree** [comment]
Hi there, I am weighing in to say that I am encountering this issue as well. I am working on this presentation: https://github.com/setgree/vegan-meta/blob/main/vegan-meta-presentation.Rmd

and getting a million errors that all basically look like 

```
This is LuaHBTeX, Version 1.18.0 (TeX Live 2024) 
 restricted system commands enabled.
tlmgr search --file --global '/bkm-pdftex.def'
Trying to automatically install missing LaTeX packages...
tlmgr install bookmark
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (verified)
tlmgr install: package already present: bookmark
This is LuaHBTeX, Version 1.18.0 (TeX Live 2024) 
 restricted system commands enabled.
tlmgr search --file --global '/bkm-pdftex.def'
! Undefined control sequence.
\@currentHref ->table.\theHtable 

Error: LaTeX failed to compile vegan-meta-presentation.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See vegan-meta-presentation.log for more info.
Execution halted
```

I commented something to this effect [here](https://github.com/rstudio/gt/issues/109) as well before I found this issue

**Comment by cderv** [comment]
@atusy would you like to give it try ? 

`pdf_document` does handle extra dependencies 
https://github.com/rstudio/rmarkdown/blob/e1c93a996596994eecdc2ca210b6627f48e31783/R/pdf_document.R#L181-L185

but it seems `beamer_presentation` does not. I believe the same can be done so that `latex_dependencies`  from any R package are correctly retrieved and inserted.
