### ISSUE TITLE
Cannot call `render` in a code chunk of the file being rendered

### ISSUE THREAD

**Issue by cubranic** [rstudio/rmarkdown#248]
Running `rmarkdown::render` on an Rmd document that contains a code chunk that calls `render` on a different file throws the following error:

```
Error in env$metadata <- list() :
  cannot change value of locked binding for 'metadata'
```

It appears to be thrown in [render.R](https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L245) during the exit cleanup. The nested call resets the binding to "metadata" and locks `render`'s environment, and when the outer call tries to do the same, it fails because the environment is already locked.

**Comment by zachary-foster** [comment]
+1 This would be useful for me too. I wanted to demonstrate a function that uses `render

**Comment by mattsigal** [comment]
I just ran into the same issue, working on a multi-faceted project with an "overview/table of contents" style main Rmd, that renders the subsections with a meta description about what each does (while the subsections produce their own output that are more specific).  All the PDFs are created and everything appears OK, but getting the error in the console is a bit annoying.

**Comment by lcolladotor** [comment]
You can use `devtools::clean_source()` to dodge this problem as shown at my earlier referenced commit. Basically use a code chunk like this:

```
    ```{r 'renderFile'}
    cat("
    ## Render file in a clean environment
    rmarkdown::render('myFile.Rmd')

    ## Clean up
    file.remove('tempRender.R')
    ", file = 'tempRender.R)
    clean_source('tempRender.R', quiet=TRUE)
    ```
```

**Comment by mattsigal** [comment]
Cool, @lcolladotor! I put your idea into a function (probably not the most elegant, but seems to get the job done): https://github.com/mattsigal/mmisc/blob/master/R/clean_render.R

In my script, I can now write:
library(mmisc)
clean_render('5-report', 'Reports', '.docx') to knit a docx of 5-report.Rmd to the Reports subdirectory.

**Comment by lcolladotor** [comment]
Looks good =)

I guess that you could use a `...` argument if you need to pass an object, then inside the function save the objects in a temporary Rdata file, and have it loaded inside `tempRender.R`. 

I have some use cases where I've had to do something like this. Basically, it's when I have a function that calls rmarkdown::render itself and takes some objects as input, and I want to show how to use this function in a vignette which itself is rendered by rmarkdown::render.

**Comment by jennybc** [comment]
Thanks @mattsigal and @lcolladotor for your helpful dialogue re: a workaround. In the process of implementing it, I learned a bit more about this -- specifically, how the workaround can interact unexpectedly with RStudio. See #491 for that.

Bottom line: it may be advantageous to include `quiet = TRUE` in the nested `rmarkdown::render()` call. Here's [a gist](https://gist.github.com/jennybc/1f747c5bb84aa9be9c3c#file-2015-08-06_nested-render-confuses-rstudio-rmd) with a self-contained `.Rmd` file showing another successful adaptation of the `devtools::clean_source()` trick, in case it helps anyone else.

**Comment by lcolladotor** [comment]
Awesome work @jennybc!

**Comment by jennybc** [comment]
OMG this is huge!

**Comment by yihui** [comment]
Sorry for fixing it so late, and the fix turned out to be really simple.
