### ISSUE TITLE
r inline code mess formatting of markdown table

### ISSUE THREAD

**Issue by raffaem** [rstudio/rmarkdown#2482]
R inline code inside a grid table messes the formatting of such table.

````
---
title: "Test"
output:
  beamer_presentation
---

# Test

## Hi

```{r, include=FALSE}
a=1
b=2
c=3
d=4
```

+------+----------+---------+
|      | Treated  | Control |
+======+==========+=========+
| age  | `r a`    | `r c`   |
| educ | `r b`    | `r d`   |
+------+----------+---------+
````

![image](https://user-images.githubusercontent.com/54762742/235433793-3bea002b-cff1-4ba6-944a-fa56cf655e82.png)

`xfun::session_info('rmarkdown')`

```
> xfun::session_info('rmarkdown')
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux, RStudio 2023.3.0.386


Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_DK.UTF-8       
  LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
  LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
  LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Rome
tzcode source: system (glibc)

Package version:
  base64enc_0.1.3   bslib_0.4.2       cachem_1.0.7      cli_3.6.1         digest_0.6.31    
  ellipsis_0.3.2    evaluate_0.20     fastmap_1.1.1     fontawesome_0.5.1 fs_1.6.2         
  glue_1.6.2        graphics_4.3.0    grDevices_4.3.0   highr_0.10        htmltools_0.5.5  
  jquerylib_0.1.4   jsonlite_1.8.4    knitr_1.42        lifecycle_1.0.3   magrittr_2.0.3   
  memoise_2.0.1     methods_4.3.0     mime_0.12         R6_2.5.1          rappdirs_0.3.3   
  rlang_1.1.1       rmarkdown_2.21.3  sass_0.4.5        stats_4.3.0       stringi_1.7.12   
  stringr_1.5.0     tinytex_0.45      tools_4.3.0       utils_4.3.0       vctrs_0.6.2      
  xfun_0.39         yaml_2.3.7       

Pandoc version: 3.0.1
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by raffaem** [comment]
This is not a bug: grid tables are not supported

**Comment by cderv** [comment]
For context, this is because in [grid tables](https://pandoc.org/MANUAL.html#extension-grid_tables) are expecting the `+` and `|` to be aligned. When **knitr** evaluates the inline, the content is replaced and takes less spaces. this is the result in the markdown 

````markdown
+------+----------+---------+
|      | Treated  | Control |
+======+==========+=========+
| age  | 1    | 3   |
| educ | 2    | 4   |
+------+----------+---------+
````

If you had the missing whitespace in your Rmd file, it will output correct markdown table. 

But when using R expression in a table, it is best to build a data.frame and then use one the many table formatting package.
