### ISSUE TITLE
Multiple tables are not included in html report when compiled through a shiny app

### ISSUE THREAD

**Issue by aghaynes** [rstudio/rmarkdown#2484]
I believe that a colleague and I have found a bug which only seems to be present when an Rmd is compiled through a shiny app. When a chunk should return multiple tables (i've tested with both `gt` and `kableExtra`), the tables are missing from the final HTML (although the tables can be found in subfolders of the temporary directory mentioned in the pandoc command). The same Rmd, when compiled with the knit button in RStudio, is as expected. I also tested an equivalent quarto document, and that works. Therefore, I believe it is an issue with `rmarkdown` (as quarto uses both `knitr` and `pandoc`, it is unlikely to be them... i think).

MRE:

Shiny app (just compiles the Rmd, no UI):
```{r}
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(

)

# Define server logic required to draw a histogram
server <- function(input, output) {
  rmarkdown::render("template.Rmd",
                    rmarkdown::html_document(),
                    "temp.html",
                    clean = FALSE
                    )
}

# Run the application
shinyApp(ui = ui, server = server)
```

Rmd (return the same table 3 times, as `gt` tables):
````{r}
---
title: "Untitled"
output: html_document
date: "2023-05-08"
---

```{r, results='asis'}
library(gt)
for(i in 1:3) cars[1:5, ] |> gt() |> print()
```

````

Session info:
```
> xfun::session_info('rmarkdown')
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 2023.3.0.386

Locale:
  LC_COLLATE=German_Switzerland.utf8  LC_CTYPE=C                          LC_MONETARY=German_Switzerland.utf8
  LC_NUMERIC=C                        LC_TIME=German_Switzerland.utf8    
system code page: 65001

Package version:
  base64enc_0.1.3   bslib_0.4.2       cachem_1.0.7      cli_3.6.1         digest_0.6.31     ellipsis_0.3.2    evaluate_0.20    
  fastmap_1.1.1     fontawesome_0.5.1 fs_1.6.2          glue_1.6.2        graphics_4.2.1    grDevices_4.2.1   highr_0.10       
  htmltools_0.5.5   jquerylib_0.1.4   jsonlite_1.8.4    knitr_1.42        lifecycle_1.0.3   magrittr_2.0.3    memoise_2.0.1    
  methods_4.2.1     mime_0.12         R6_2.5.1          rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.21.4  sass_0.4.5       
  stats_4.2.1       stringi_1.7.12    stringr_1.5.0     tinytex_0.45      tools_4.2.1       utils_4.2.1       vctrs_0.6.2      
  xfun_0.39         yaml_2.3.7       

Pandoc version: 2.19.2
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
I bet you don't get the same results because the `print()` don't do the same in the shiny context somehow. 

**knitr** works with some custom printing method to handle dependencies  and more. Vignette explains it https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html
Regular `print()` won't always do what is expected for **knitr** to correctly include the results. 

When doing loops to create  you should leverage child component with `knit_child()` or `child = ` option for child document with your gt plot. See https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html

For loops, are tricky for that in R Markdown, as **gt** - could try this chunk and see if it works from your shiny app ?

````markdown
```{r, results='asis'}
library(gt)
res <- lapply(1:3, \(x) knitr::knit_child(text = c(
  "```{r, echo = FALSE}",
  "cars[1:5, ] |> gt()",
  "```"), quiet = TRUE)
)
cat(unlist(res), sep = "\n")
```
````
