### ISSUE TITLE
Output missing for `html_notebook` in preview and when rendering

### ISSUE THREAD

**Issue by AjayKMehta** [rstudio/rmarkdown#2497]
I recently noticed that output for code chunks is not showing up for RMarkdown documents with `output_format` set to `html_notebook`. This happens when rendering or clicking the **Preview** button in RStudio. I can still see the chunk output inline.

The attached zip file contains a sample notebook and rendered HTML output. What is odd is that I don't see comments in the HTML file like `<!-- rnb-plot-begin -->` followed by an `img` tag which I see in HTML output for notebooks I rendered successfully in the past.

[test.zip](https://github.com/rstudio/rmarkdown/files/11927651/test.zip)

FWIW, if I add a section for `html_document` in YAML frontmatter and run `rmarkdown::render("test.Rmd", output_format="all")`, then the notebook's HTML output includes chunk output.

I am using pandoc v 3.12 that comes with Quarto 1.4.176. Snippet from my `.Renviron` file:

```env
QUARTO_PATH="D:/Apps/quarto/bin/quarto.cmd"
RSTUDIO_PANDOC="D:/Apps/quarto/bin/tools"
```

Removing these values and restarting R did not help.

``` r
xfun::session_info("rmarkdown")
#> R version 4.3.0 (2023-04-21 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> 
#> Locale:
#>   LC_COLLATE=English_United States.utf8 
#>   LC_CTYPE=English_United States.utf8   
#>   LC_MONETARY=English_United States.utf8
#>   LC_NUMERIC=C                          
#>   LC_TIME=English_United States.utf8    
#> 
#> time zone: America/Los_Angeles
#> tzcode source: internal
#> 
#> Package version:
#>   base64enc_0.1.3   bslib_0.5.0       cachem_1.0.8      cli_3.6.1        
#>   digest_0.6.32     ellipsis_0.3.2    evaluate_0.21     fastmap_1.1.1    
#>   fontawesome_0.5.1 fs_1.6.2          glue_1.6.2        graphics_4.3.0   
#>   grDevices_4.3.0   highr_0.10        htmltools_0.5.5   jquerylib_0.1.4  
#>   jsonlite_1.8.7    knitr_1.43        lifecycle_1.0.3   magrittr_2.0.3   
#>   memoise_2.0.1     methods_4.3.0     mime_0.12         R6_2.5.1         
#>   rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.23    sass_0.4.6       
#>   stats_4.3.0       stringi_1.7.12    stringr_1.5.0     tinytex_0.45     
#>   tools_4.3.0       utils_4.3.0       vctrs_0.6.3       xfun_0.39        
#>   yaml_2.3.7       
#> 
#> Pandoc version: 3.1.2
```

<sup>Created on 2023-07-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
 

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Something is definitely not right here. It seems the plot is missing now and this makes other chunk following content not found either. Really odd !! It won't be easy to debug as this is tied to the IDE - could be an issue there but it seems to not be working with current release of RStudio. I need to try older one too.

````markdown
---
title: test
output:
  html_notebook: default
---

```{r}
1 + 1 
```

```{r}
#| label: plot
library(ggplot2)

ggplot(mtcars, aes(x = hp, y = mpg, fill = cyl)) +
  geom_point()
```

```{r}
head(mtcars)
```
````

**Comment by AjayKMehta** [comment]
IMHO it seems to be connected to changes in newer versions of **pandoc** (v 3.11+) that cause `rmarkdown::render` to not produce output.

`rmarkdown::render(.., output_format = "html_notebook")` does not produce output but changing to `output_format = "all"` does 🤔

**Comment by cderv** [comment]
`html_notebook` is a special format only working inside RStudio IDE  (or other ide if they implemented support)
https://bookdown.org/yihui/rmarkdown/notebook.html

[Notebook Format](https://bookdown.org/yihui/rmarkdown/notebook.html#notebook-format) is a special `.nb.html`. No `.html` will be produced. When doing `output_format = "all"`, it will also render using the `html_document` output key, which lead to a `.html` version of the file.

**Comment by AjayKMehta** [comment]
Are there any updates for this issue?

Thanks.

**Comment by cderv** [comment]
I can't find a RStudio version that works, so I open an issue without much more information in RStudio repo
* https://github.com/rstudio/rstudio/issues/13706

We should now follow there.

**Comment by AjayKMehta** [comment]
Closed as new issue opened in RStudio repo.
