### ISSUE TITLE
Knit issue using stargazer function

### ISSUE THREAD

**Issue by Magnolia103** [rstudio/rmarkdown#2498]
I'm running into an issue when I try to knit my rmd file (wanting a PDF using latex). Instead of nice tables in my PDF, I just get a bunch of latex code. I think it may have something to do with the headers in my rmd file. In previous work, I would change the heading from ```{r} to ```{r, results = "asis"} to get a table to populate but it does not work in this example. Using the stargazer function, is there something special I need to do in my rmd headers so that I can have the table produce and not just latex code.

Here's a snippet of my code:
````markdown
---
title: "Islamic control and education"
date: "July 1, 2023"
output:
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load in packages
```{r packages, warning = FALSE, message = FALSE}
library(foreign)
library(dplyr)
library(survey)
library(ggplot2)
library(scales)
library(rvest)
library(httr)
library(xtable)
library(tidyr)
library(stargazer)
library(rdd)
library(knitr)
```

##Define the local directory
```{r setwd}
setwd("~/Desktop/17.803")
```

##Import Data
```{r}
islamic <- read.csv("islamic.csv")
``` 

##Part 1.I
```{r}
#0.40 bandwidth
fitf40 <- islamic %>%
  filter(iwm94 < 0.4 & iwm94 > -0.4) %>%
  lm(hischshr1520f ~ iwm94 * islamicwin, .)
#0.20 bandwidth
fitf20 <- islamic %>%
  filter(iwm94 < 0.2 & iwm94 > -0.2) %>%
  lm(hischshr1520f ~ iwm94 * islamicwin, .)
#0.05 bandwidth
fitf05 <- islamic %>%
  filter(iwm94 < 0.05 & iwm94 > -0.05) %>%
  lm(hischshr1520f ~ iwm94 * islamicwin, .)
#Table of 3 different bandwidth sizes
stargazer(fitf40, fitf20, fitf05,
          dep.var.labels = c("Female high school completion rate"),
          covariate.labels = c("Islamic Party Margin", "Treatment (Islamic Win)",
                               "Interaction Margin:Win"),
          omit.stat = c("f", "ser"),
          add.lines = list(c("Bandwidth", "0.40", "0.20", "0.05")),
          align = T,
          title = ("Regression Discontinuity Analysis with Varying Bandwidths"),
          no.space = T,
          header = F)
```
````

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ x] included a minimal, self-contained, and reproducible example?

- [ x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
> Here's a snippet of my code

I reformatted your code (you checked the box but probably did not check the "how to format" https://yihui.org/issue/#please-format-your-issue-correctly) 

> ````
> ##Define the local directory
> ```{r setwd}
> setwd("~/Desktop/17.803")
> ```

> ##Import Data
> ```{r}
> islamic <- read.csv("islamic.csv")
> ````

Can you please provide a reproducible example ? This is not reproducible and the "snippet" is quite long with probably some content not related to **stargazer**. 

Can you simplify it too to scope to the issue you have ?  thank you 

Setting `results = "asis"` still seems require for using **stargazer** package

````markdown
---
output:
  pdf_document:
    keep_tex: true
---

```{r}
library(stargazer)
```

##Define the local directory
```{r, results='asis'}
stargazer(attitude)
```
````

![image](https://github.com/rstudio/rmarkdown/assets/6791940/feaaf203-3a3d-4915-9da2-d6c66a623042)
