### ISSUE TITLE
Shiny prerendered dependencies are sometimes written twice into prerendered HTML

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/rmarkdown#2499]
learnr has [long-suffered from a hard-to-replicate bug](https://github.com/rstudio/learnr/issues/597) that results in an error like this:

```
Error: parse error: trailing garbage

          ":{},"value":["0.10.1"]}]}]} {"type":"list","attributes":{},

                     (right here) ------^

Execution halted
```

I've finally tracked down the core mechanism, but I don't know the root cause. When a shinyrmd document is pre-rendered into HTML, it writes the dependencies used in the app into the prerendered HTML so that it can be used at runtime:

https://github.com/rstudio/rmarkdown/blob/1d739bd4b8f66e992dd68f4253981c0d015cf7c1/R/render.R#L857-L862

`shiny_prerendered_append_dependencies()` writes two JSON-serialized objects into `<script>` tags with `data-context` attributes `"dependencies"` and `"execution_dependencies"`.

https://github.com/rstudio/rmarkdown/blob/1d739bd4b8f66e992dd68f4253981c0d015cf7c1/R/shiny_prerendered.R#L370-L380

In https://github.com/rstudio/learnr/issues/597#issuecomment-979817558 I was sent copies of tutorial files that exhibited this behavior, and they contain duplicated dependency chunks. Importantly, the _entire group_ of dependencies + execution dependencies are duplicated, rather than each one being written twice in place. Here's roughly what the prerendered html looks like:

```html
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[... "value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names": ...
</script>
<!--/html_preserve-->
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[... "value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names": ...
</script>
<!--/html_preserve-->
```

When starting up the app, `shiny_prerendered_html()` extracts the `"dependencies"` and `"execution_dependencies"` contexts

https://github.com/rstudio/rmarkdown/blob/1d739bd4b8f66e992dd68f4253981c0d015cf7c1/R/shiny_prerendered.R#L157-L159

but strongly assumes that there is exactly a single string returned by `shiny_prerendered_extract_context()` when it passes the extracted context to `jsonlite::unserializedJSON()`, which does not like the invalid JSON.

``` r
obj_json <- jsonlite::serializeJSON(list(a = 1))
jsonlite::unserializeJSON(c(obj_json, obj_json))
#> Error: parse error: trailing garbage
#>           ttributes":{},"value":[1]}]} {"type":"list","attributes":{"n
#>                      (right here) ------^
```

I'd like to know why `shiny_prerendered_append_dependencies()` is called twice during pre-render, but I also think we can reasonably avoid this issue by checking the `"dependencies"` context contents before handing them to `unserializedJSON()`. I'll submit a PR with this change shortly.

**Comment by gadenbuie** [comment]
I have a suspicion that there are somehow two processes running at the same time to prerender the source document and are inadvertently writing into the same file. I've uncovered a reproducible example that produces the expected error (here shown before the fix in #2500).

```r
render_bg <- function(path) {
  callr::r_bg(
    function(path) {
      rmarkdown::render(path)
    },
    args = list(path = path)
  )
}

# Remove prerendered HTML and source if they exist
unlink("issue.html")
unlink("issue.Rmd")

writeLines('---
title: "issue"
output: html_document
runtime: shiny_prerendered
---

```{r}
textInput("text", "Text", "Text")
renderText(input$text)
```', "issue.Rmd"
)

# Render the Rmd twice at basically the same time
r1 <- render_bg("issue.Rmd")
r2 <- render_bg("issue.Rmd")
r2$wait()
```

When you try to run the document, it will have been corrupted by simultaneous writes into the `.html` file.

```r
rmarkdown::run("issue.Rmd")
#> Error: parse error: trailing garbage
#>           ":{},"value":["2.23.3"]}]}]} {"type":"list","attributes":{},
#>                      (right here) ------^
```

After applying the fix in #2500, we still get errors due to failures in other places in the file.

```
rmarkdown::run("issue.Rmd")
#> Error: lexical error: invalid char in json text.
#>           s":{},"value":["jquerylib"]} <!--html_preserve--> {"type":"l
#>                      (right here) ------^
```

**Comment by cderv** [comment]
Good find ! 

I don't know if we should do something about this in **rmarkdown** (at least as a bug fix). I don't think we do anything against this  not even for `render()`. 

This is the responsability to who or what is calling `rmarkdown::run()` or `rmarkdown::render()` to do that in a safe context for concurrency. 

Related issue on that concurrency topic: 

* https://github.com/rstudio/rmarkdown/issues/2454
* https://github.com/rstudio/rmarkdown/issues/499
* https://github.com/quarto-dev/quarto-cli/issues/4730
* https://github.com/quarto-dev/quarto-cli/issues/5861

**Comment by gadenbuie** [comment]
In this case, my reprex is a hypothetical example that's at least consistent with the real-world scenario. I've heard reports of this kind of problem for learnr users on Connect and shinyapps.io as well as Posit Cloud. Cloud is surprising to me because in theory it should be equivalent to a local installation, where this problem hasn't been reported really.

Related to the concurrency option, I understand that there are many reasons that make writing unique files difficult. That said, if we're using a mechanism like `writeLines(text, file_connection)`, I do think rmarkdown/knitr should write into a temporary uniquely-named file that's moved into place when the contents are finished. This way, even if there are race conditions, then at least the final intermediate file is the atomically the complete and correct winner of the race.
