### ISSUE TITLE
fig.alt option doesn't work with quarto style chunk option when specifying with code

### ISSUE THREAD

**Issue by szimmer** [rstudio/rmarkdown#2501]
I'm trying to use the BrailleR package to add alt-text to figures. If I specify the alt.text in the in-line chunk option, things work but don't seem to work with quarto-style chunk options. By work, I mean that the first example below with quarto-style chunk options has the alt text be the literal R code while when using in-line chunk options, the alt-text is the output from R which is desired.

Reprex:

`````
---
title: "Brailler Alt Text"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| label: make-plot
library(tidyverse)

p1 <- mpg %>%
  ggplot(aes(class)) + geom_bar()
```

Plot below has alt text specified by:

````{verbatim}
```{r}
#| label: print-plot-bad
#| fig.cap: "Bar plot of car class with bad alt-text"
#| fig.alt: str_c(BrailleR::VI(p1)$text, collapse=" ")
p1
```
````

The alt-text ends up being: "str_c(BrailleR::VI(p1)$text, collapse=" ")"

```{r}
#| label: print-plot-bad
#| fig.cap: "Bar plot of car class with bad alt-text"
#| fig.alt: str_c(BrailleR::VI(p1)$text, collapse=" ")
p1
```

Plot below has alt text specified by:

````{verbatim}
```{r, fig.alt=str_c(BrailleR::VI(p1)$text, collapse=" ")}
#| label: print-plot-good
#| fig.cap: "Bar plot of car class with good alt-text"

p1
```
````

The alt-text ends up being: "`r str_c(BrailleR::VI(p1)$text, collapse=" ")`"


```{r, fig.alt=str_c(BrailleR::VI(p1)$text, collapse=" ")}
#| label: print-plot-good
#| fig.cap: "Bar plot of car class with good alt-text"

p1
```


```{r}
xfun::session_info('rmarkdown')
```


`````

Session info:

```
## R version 4.3.0 (2023-04-21 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19045)
## 
## 
## Locale:
##   LC_COLLATE=English_United States.utf8 
##   LC_CTYPE=English_United States.utf8   
##   LC_MONETARY=English_United States.utf8
##   LC_NUMERIC=C                          
##   LC_TIME=English_United States.utf8    
## 
## time zone: America/New_York
## tzcode source: internal
## 
## Package version:
##   base64enc_0.1.3   bslib_0.4.2       cachem_1.0.8      cli_3.6.1        
##   digest_0.6.31     ellipsis_0.3.2    evaluate_0.20     fastmap_1.1.1    
##   fontawesome_0.5.1 fs_1.6.2          glue_1.6.2        graphics_4.3.0   
##   grDevices_4.3.0   highr_0.10        htmltools_0.5.5   jquerylib_0.1.4  
##   jsonlite_1.8.4    knitr_1.42        lifecycle_1.0.3   magrittr_2.0.3   
##   memoise_2.0.1     methods_4.3.0     mime_0.12         R6_2.5.1         
##   rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.23.4  sass_0.4.5       
##   stats_4.3.0       stringi_1.7.12    stringr_1.5.0     tinytex_0.45     
##   tools_4.3.0       utils_4.3.0       vctrs_0.6.2       xfun_0.39        
##   yaml_2.3.7       
## 
## Pandoc version: 3.1.1
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x ] included a minimal, self-contained, and reproducible example?

- [x ] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Thanks for asking the question. This really a side effect of using YAML syntax for chunk options, which Quarto does expect by default. 

* When using chunk header to place options (usual **knitr** way), you are using special `key = value` syntax that will be parsed as R. This means by default, `value` is parsed and evaluated as an R expression. 

* When using YAML syntax for placing options in-chunk, this is really using YAML syntax. This means `key: value` respect the YAML spec, and it won't parse and evaluate a string as R code expression. 

R YAML parser has a way to trigger expression evaluation before YAML parsing which is using `!expr`

````markdown
```{r}
#| label: print-plot-bad
#| fig.cap: "Bar plot of car class with bad alt-text"
#| fig.alt: !expr str_c(BrailleR::VI(p1)$text, collapse=" ")
p1
```
````

We explain the limitation in

* Quarto doc: https://quarto.org/docs/computations/r.html#chunk-options
   > Chunk options included this way use YAML syntax rather than R syntax for consistency with options provided in YAML front matter. You can still however use R code for option values by prefacing them with !expr. For example:
* In knitr post about new chunk header syntax: https://yihui.org/en/2022/01/knitr-news/
   > Personally I do not like YAML but I know many people do (I can never remember how to properly write a string value that contains both single quotes and colons). For the traditional comma-separated syntax, you only need to know the R syntax, with which you should be familiar. Another benefit of the comma-separated syntax is that [you can write R expressions freely](https://bookdown.org/yihui/rmarkdown-cookbook/chunk-variable.html), which is a little awkward in YAML—to provide an R expression as a YAML value, you need to add `!expr` before the expression


So the behavior you see is expected. You need to adapt the syntax to your usage. 

Hope it helps understand

**Comment by szimmer** [comment]
Thanks for a very thorough and helpful response!

**Comment by cderv** [comment]
For reference this was also asked at https://community.rstudio.com/t/using-brailler-to-create-alt-text-in-rmarkdown/170468
