### ISSUE TITLE
Filenames beginning with "-" cause incorrect invocation of pandoc

### ISSUE THREAD

**Issue by mbaynton** [rstudio/rmarkdown#2503]
## Steps to reproduce

1. Create an R Markdown file whose name begins with a `-`, for example `-3-something.Rmd`
2. `rmarkdown::render('-3-something.Rmd')`

## Result

```
processing file: -3-something.Rmd
                                                                                          
output file: -3-something.knit.md

/usr/bin/pandoc +RTS -K512m -RTS -3-something.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output -3-something.html --lua-filter /home/mbaynton/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/mbaynton/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --variable bs3=TRUE --section-divs --template /home/mbaynton/R/x86_64-pc-linux-gnu-library/4.3/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable theme=bootstrap --mathjax --variable 'mathjax-url=https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --include-in-header /tmp/Rtmp0WU9RC/rmarkdown-str1bc8d4b28f56f.html 
Unknown option -3.
Unknown option --something.knit.md.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [ ] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Related issue at https://community.rstudio.com/t/error-pandoc-document-conversion-failed-with-error-6/171491/4

I think there the file start with `(1)` and we transform special character to `-`. Then this issue happens

**Comment by yihui** [comment]
I think we just need to `shQuote()` the `pandoc_convert()` input. I'll test it.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

```r
remotes::install_github('rstudio/rmarkdown')
```
