### ISSUE TITLE
R expressions in SQL code chunks are not interpolated in the rendered output

### ISSUE THREAD

**Issue by thothal** [rstudio/rmarkdown#2505]
## Preamble

[Problem first posted on SO.](https://stackoverflow.com/questions/76962658/show-value-in-sql-chunk-of-r-value/76967822#76967822)

## Issue

We can use (simple) [R expressions in SQL chunks ](https://bookdown.org/yihui/rmarkdown/language-engines.html#sql) like so:

````
---
title: "SQL Interpolation"
output: html_document
---

```{r}
subjects <- 10
db <- dbplyr::simulate_mssql()
```

```{sql, connection = db, eval = FALSE}
SELECT * FROM trials WHERE subjects >= ?subjects
```
```` 

Which works like a charm. However, in the rendered output we see the code a bit too literal (IMHO):

![image](https://github.com/rstudio/rmarkdown/assets/30824940/7e2cd2b8-6443-48f5-bc75-b1aac406ca8e)

## Expected Outcome

I would expect  (or at least have an option to do so) to see the code neatly interpolated, that is `?subject` replaced by its value. Eventually, the code will be sent to the DBMS, so my non-technical assumption is that at some point this interpolation happens, so why not showing it also in the output?

![image](https://github.com/rstudio/rmarkdown/assets/30824940/ee591d3e-870d-4ba3-8c21-f135335efdb5)

## Current Workaround

I must rely on manual interpolation to get the expected results:

````
---
title: "SQL Interpolation"
output: html_document
---

```{r}
subjects <- 10
db <- dbplyr::simulate_mssql()
sql <- glue_sql("SELECT * FROM trials WHERE subjects >= {subjects}", .con = db)
```

```{sql, connection=db, code = sql}
```
```` 

## Session Info
```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Locale:
  LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
  LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
  LC_TIME=German_Germany.utf8    

Package version:
  base64enc_0.1.3   bslib_0.5.0       cachem_1.0.6      cli_3.6.1        
  digest_0.6.31     ellipsis_0.3.2    evaluate_0.21     fastmap_1.1.0    
  fontawesome_0.5.1 fs_1.5.2          glue_1.6.2        graphics_4.2.2   
  grDevices_4.2.2   highr_0.10        htmltools_0.5.4   jquerylib_0.1.4  
  jsonlite_1.8.4    knitr_1.43        lifecycle_1.0.3   magrittr_2.0.3   
  memoise_2.0.1     methods_4.2.2     mime_0.12         R6_2.5.1         
  rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.23    sass_0.4.4       
  stats_4.2.2       stringi_1.7.8     stringr_1.5.0     tinytex_0.43     
  tools_4.2.2       utils_4.2.2       vctrs_0.6.3       xfun_0.39        
  yaml_2.3.6       

Pandoc version: 2.19.2
```

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [ ] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ ] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
You need to opt-in interpolation at the moment.

See duplicates:

* https://github.com/yihui/knitr/issues/2131

It is in **knitr** since 1.16 https://github.com/yihui/knitr/blob/master/NEWS.md#changes-in-knitr-version-116 but one need to find the information I guess... 

I'll see to surface that somewhere in doc. 

Please do reopen if this is not working as expected.
