### ISSUE TITLE
How can I make a code block full-width without horizontal scrolling?

### ISSUE THREAD

**Issue by danli349** [rstudio/rmarkdown#2506]
Hi Yihui:

How can I make a code block full-width without horizontal scrolling?
I want to show the full-width code because horizontal scrolling is difficult to touch on a small screen or in PDF format.

![image](https://github.com/rstudio/rmarkdown/assets/33963919/bfaa3046-a026-42de-8ca0-d150a567c902)

I customized the `style.css` file like this, but it doesn't work
```
.title {
  font-size: 38px;
  color: DarkRed;
  text-align: center;
}

html, body {
    max-width: 100%;
    overflow-x: hidden;
}
```
and use it in `Rmd` file:
```
output:
  html_document:
    css: style.css
```

I also tried to change the `opts_chunk`:
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, width = 300)
```
But it doesn't work either.

``
> blogdown::hugo_version()
[1] '0.80.0'
> rmarkdown::pandoc_version()
[1] '3.1.1'
``

Thanks a lot

**Comment by yihui** [comment]
In future please follow [the issue guide](new/choose) when asking questions (i.e., try other public forums first). Thanks!

I'm not sure I understand your question. Do you want the whole document to be full-width or only code blocks? Please note that sometimes your code can be even wider than the full document width. In that case, you can't avoid the horizontal scrollbar without wrapping the lines. The trick that I use by myself is to hard-wrap the lines for smaller screens and when the mouse is over the code blocks:

https://github.com/rstudio/markdown/blob/32c3de2/inst/resources/default.css#L15-L22
https://github.com/rstudio/markdown/blob/32c3de2/inst/resources/default.css#L64-L66

You can see https://cran.r-project.org/web/packages/markdown/vignettes/slides.html for the effects of the CSS above.
