### ISSUE TITLE
[FR] Don't purge intermediate files when ask to keep_tex

### ISSUE THREAD

**Issue by diekhans** [rstudio/rmarkdown#2509]
Even when keep_tex is set to true, Rmarkdown still purges many of the LaTeX/BibTeX intermediate files.  In particular, purging the .aux files makes it impossible to have cross-references between two documents.

Please have keep_tex keep all latex output.

**Comment by diekhans** [comment]
Christophe Dervieux ***@***.***> writes:
>  if you want to keep intermediary file you can use an option as answered in https://stackoverflow.com/a/55408923/3436535 
> which is `options(tinytex.clean = FALSE)` 

I am not using tinytex.

> I am no expert in LaTeX - regarding which file not to clean for example like `.aux` you are suggesting - so I am not sure which should be clean or not when doing `keep-tex: true`. Is there any other ? 

How about just leaving them all?  .aux .bbl .blg .log .pdf .tex

Where is the code that removes them?

**Comment by cderv** [comment]
> I am not using tinytex.

If you are using **rmarkdown**, then `tinytex::latexmk()` is used. It is a function from the **tinytex** R package, not the TinyTeX distribution (https://yihui.org/tinytex/)

https://github.com/rstudio/rmarkdown/blob/c306a43c97b75d15a436f8c8a037750db86e1ab5/R/util.R#L342-L344

https://github.com/rstudio/rmarkdown/blob/c306a43c97b75d15a436f8c8a037750db86e1ab5/R/render.R#L973-L984

So the option will be used during the rendering no matter which distribution you are using
It is here in tinytex code: https://github.com/rstudio/tinytex/blob/a45272cca6f9e25aa936d8c2f4fb7e85e3bf78de/R/latex.R#L102

Then the cleaning happen through tinytex function too 

* with emulation mode of `latexmk` CLI, files are removed by R call in tinytex
https://github.com/rstudio/tinytex/blob/a45272cca6f9e25aa936d8c2f4fb7e85e3bf78de/R/latex.R#L179-L185

* without emulation mode, it is a call to `latexmk -c` directly 
https://github.com/rstudio/tinytex/blob/a45272cca6f9e25aa936d8c2f4fb7e85e3bf78de/R/latex.R#L140

The LaTeX distribution you are using does not matter here. 

Hope it helps understand

**Comment by diekhans** [comment]
Thanks for the info, somethings I can work around without having my
collaborators run make to build the document.

However, this still seems like reasonable behavior to not purge
the latex output if keep_tex is set.  This could be a clean, documented
way.  Of course, it could be another option, but that seems like overkill.

**Comment by yihui** [comment]
`keep_tex` is only for keeping the intermediate `.tex` file. For auxiliary files generated by LaTeX, you need to set `options(tinytex.clean = FALSE)` in your `.Rprofile` to prevent them from being purged. Changing the default behavior may be too late now (this has existed for several years), and I feel it's easy enough for you to change the default via the aforementioned option, so I tend not to do it for all other users (some of them may not like it). Thanks for your understanding!

**Comment by diekhans** [comment]
Oh yes, understand why this would bug people. Perhaps just a
mention in the keep_tex documentation? It is rather obscures to
find.

**Comment by yihui** [comment]
Of course we can do that. Thank you very much for the suggestion!

**Comment by cstjohn810** [comment]
> `keep_tex` is only for keeping the intermediate `.tex` file. For auxiliary files generated by LaTeX, you need to set `options(tinytex.clean = FALSE)` in your `.Rprofile` to prevent them from being purged. Changing the default behavior may be too late now (this has existed for several years), and I feel it's easy enough for you to change the default via the aforementioned option, so I tend not to do it for all other users (some of them may not like it). Thanks for your understanding!

I have tried to include `options(tinytex.clean = FALSE)` in my `.Rprofile` and even unchecked the Clean auxiliary output after compile Global and Project options in RStudio. I have not been able to keep any of the auxiliary files in the output folder. After Pressing Render in a .qmd, I am still only left with the PDF and the QMD. I have also included an R chunk which calls for the same option, but all files are removed once the PDF is created.

**Comment by cderv** [comment]
@cstjohn810 It seems you are using Quarto not R Markdown. 

> manually running rmarkdown::render(file, output_format = "pdf_document",clean = FALSE) does indeed keep the files. Only clicking the Render button does not.

Especially this - you are running `rmardown::render()` which runs R Markdown and **tinytex** R package which does follow the options in R profile, and this issue is about all that. 

Render button in IDE is a sign that the document is .qmd file run with Quarto. For R Markdown, it should be Knit button. 

So for Quarto this is another issue because it does not run TinyTeX using R package **tinytex** and options `tinytex.clean` is for the R package. 

Please do open an issue in Quarto if I am right, we'll look into the problem. So if you look at the doc (https://quarto.org/docs/output-formats/pdf-engine.html#pdf-compilation) there is a `latex-clean` option you can set to false and it should help your case

**Comment by cstjohn810** [comment]
> @cstjohn810 It seems you are using Quarto not R Markdown.
> 
> > manually running rmarkdown::render(file, output_format = "pdf_document",clean = FALSE) does indeed keep the files. Only clicking the Render button does not.
> 
> Especially this - you are running `rmardown::render()` which runs R Markdown and **tinytex** R package which does follow the options in R profile, and this issue is about all that.
> 
> Render button in IDE is a sign that the document is .qmd file run with Quarto. For R Markdown, it should be Knit button.
> 
> So for Quarto this is another issue because it does not run TinyTeX using R package **tinytex** and options `tinytex.clean` is for the R package.
> 
> Please do open an issue in Quarto if I am right, we'll look into the problem. So if you look at the doc (https://quarto.org/docs/output-formats/pdf-engine.html#pdf-compilation) there is a `latex-clean` option you can set to false and it should help your case

Thanks for looking into this. If I do just an .Rmd with a Knit button and set the same options `options(tinytex.clean = FALSE)`, I still lose all of the files. I will separately look at the Quarto documentation as well.

**Comment by cderv** [comment]
@cstjohn810 here is an example with current situation. You need both `keep_tex` and `tinytex.clean = FALSE` to keep all the intermediary file. 

``` r
dir.create(tmp_dir <- tempfile())
owd <- setwd(tmp_dir)

xfun::write_utf8(c(
  "---",
  "title: test",
  "---",
  "",
  "# A header",
  ""
), "test.Rmd")
fs::dir_tree()
#> .
#> └── test.Rmd

# Default: only PDF
rmarkdown::render("test.Rmd", "pdf_document", quiet = TRUE)
fs::dir_tree()
#> .
#> ├── test.pdf
#> └── test.Rmd

# Don't clean: Only tex file is not keep
options(tinytex.clean = FALSE)
rmarkdown::render("test.Rmd", "pdf_document", quiet = TRUE)
fs::dir_tree()
#> .
#> ├── test.aux
#> ├── test.log
#> ├── test.pdf
#> └── test.Rmd

# Because it requires `keep_tex: true`
rmarkdown::render("test.Rmd", "pdf_document", output_options = list(keep_tex = TRUE), quiet = TRUE)
fs::dir_tree()
#> .
#> ├── test.aux
#> ├── test.log
#> ├── test.pdf
#> ├── test.Rmd
#> └── test.tex


setwd(owd)
unlink(tmp_dir, recursive = TRUE)
```

**Comment by yihui** [comment]
The `pdf_document` option `keep_tex` and the **tinytex** option `tinytex.clean` are orthogonal. One controls the `.tex` file and the other controls the auxiliary files. I tend not to make this change.

**Comment by cderv** [comment]
OK great. Makes sense. Thanks ! 

so @cstjohn810 you need to set both as in the example. 

Hope it helps
