### ISSUE TITLE
Plot not showing while knitting markdown pdf

### ISSUE THREAD

**Issue by PCK1992** [rstudio/rmarkdown#2512]
I'm having a really weird issue that I can't reproduce right now and can't tell if it's a package issue or a markdown issue.

I trying to plot a graph using the `netdiffuseR` package.

````
---
title: "Untitled"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(netdiffuseR)
# Generating a random graph
set.seed(1234)
n <- 6
nper <- 5
graph <- rgraph_er(n,nper, p=.3, undirected = FALSE)
toa <- sample(2000:(2000+nper-1), n, TRUE)
adopt <- toa_mat(toa)

# Computing exposure
expos <- exposure(graph, adopt$cumadopt)


```

## Plot

```{r pressure, echo=FALSE}
plot_threshold(graph, expos, toa)
```

````

This example works well when I knit.

Now to my issue

I basically do the same thing with my data and if I generate the plot in my markdown document it looks like this:

![image](https://github.com/rstudio/rmarkdown/assets/17555094/62d9a7b2-32c4-48fa-9d22-90031fbfcaf5)

It's supposed to look like that so it's great!

But once I knit the document the pdf version looks like this:
![image](https://github.com/rstudio/rmarkdown/assets/17555094/4b197d11-8c28-4c75-a0fe-102e911840b2)

It's really strange and I can't reproduce this behavior. Any idea what could be the cause here?

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS, RStudio 2023.6.1.524


Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Indianapolis
tzcode source: system (glibc)

Package version:
  base64enc_0.1.3   bslib_0.5.1       cachem_1.0.8      cli_3.6.1         digest_0.6.33     ellipsis_0.3.2   
  evaluate_0.21     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3          glue_1.6.2        graphics_4.3.1   
  grDevices_4.3.1   highr_0.10        htmltools_0.5.6   jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.43       
  lifecycle_1.0.3   magrittr_2.0.3    memoise_2.0.1     methods_4.3.1     mime_0.12         R6_2.5.1         
  rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.24.2  sass_0.4.7        stats_4.3.1       stringi_1.7.12   
  stringr_1.5.0     tinytex_0.46      tools_4.3.1       utils_4.3.1       vctrs_0.6.3       xfun_0.40        
  yaml_2.3.7       

Pandoc version: 3.1.1
```

**Comment by PCK1992** [comment]
HTML was a great suggestion: It works with HTML! Any idea what could cause the PDF issue?

Unfortunately, I can't share the data with anyone and I can't create a reproducible example beyond my problem with the empirical data.

I'm using `netdiffuseR` 1.22.6

**Comment by cderv** [comment]
> Any idea what could cause the PDF issue?

No as it works for me with HTML and PDF with your shared code. So not sure what the difference is.

**Comment by PCK1992** [comment]
The difference is that the shared code relies on data provided by the package. Knitting the plot with that data set works well. When I try to do the exact same thing the plot shows correctly when I run the code chunk locally within the RMarkdown script, it also shows up in the html version but it doesn't properly render in the PDF version.

In Rstudio:
![image](https://github.com/rstudio/rmarkdown/assets/17555094/dd8987da-e1bf-4c09-8f5f-71c2133afdb8)

As HTML:
![image](https://github.com/rstudio/rmarkdown/assets/17555094/5a2cc640-761c-4986-9e18-1114937894f1)

As PDF:
![image](https://github.com/rstudio/rmarkdown/assets/17555094/d67aebd5-0207-4d49-aa4f-10701567f856)


Unfortunately, I can't share my data to exactly reproduce it. I'll see if I can find another example that reproduces the behavior. Other than that, I don't have problems rendering graphs. It's odd.

**Comment by cderv** [comment]
This is indeed a bit strange... Unfortunately I can't help further without being able to reproduce...

**Comment by PCK1992** [comment]
Let me see if I can find another example with similar behavior...

**Comment by PCK1992** [comment]
If I open the document in Chrome it displays the plot in the PDF. Same on Windows computers with PDF readers. My Linux PDF readers do not display the PDF properly. Any idea and is this relevant to markdown? Just curious if this could be some systematic issue or if it's just my individual configuration. But I guess what I can confirm is that the PDF is knitted properly, just that apparently some PDF viewers can't properly render it.

**Comment by cderv** [comment]
Really weird. I did not know about that. Maybe something related to font or else. I believe it could ha

> Any idea and is this relevant to markdown? 

If this is the same file that you can open on Windows and Chrome but not in PDF reader on Linux, then I don't think it is R Markdown. LaTeX is used to create the PDF, so maybe there is something related to it. 

Anyhow, not sure what we can do in rmarkdown directly

**Comment by PCK1992** [comment]
I think in that case we can close this issue. Thanks for looking into this!
