### ISSUE TITLE
pdflatex error when rendering in locale LC_NUMERIC=fr_FR.UTF-8

### ISSUE THREAD

**Issue by tdhock** [rstudio/rmarkdown#2525]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ x] included a minimal, self-contained, and reproducible example?

- [ x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [ x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [ x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

Hi! first of all, thanks very much for supporting the rmarkdown package, which I find very useful.
I am trying to render Rmd to beamer slides on a computer with LC_NUMERIC=fr_FR.UTF-8 meaning that the decimal separator prints as a comma (one half is 0,5). 
I expected that I should be able to render rmarkdown to beamer slides, but I observe that there is an error.
The issue is that there is a line in the generated tex file which looks like `\includegraphics[width=4,5in]{figure}` and that is problematic because pdflatex interprets the comma as a separator between optional arguments in the [ ].
The issue only happens when dev: png is specified in the yaml header. 

The work-around that users can do, is to set LC_NUMERIC=C, and then the compilation works fine.
The fix in the rmarkdown package is to change the comma to a period, `\includegraphics[width=4.5in]{figure}` or maybe to set LC_NUMERIC=C while generating the tex file?

Below is a minimal reproducible example R script
```r
cat('---
title: "matplotlib test"
author: "Toby Dylan Hocking"
output: 
  beamer_presentation:
    dev: png
---\n```{r}
Sys.setenv(RETICULATE_PYTHON="/home/tdhock/miniconda3/envs/2023-08-artificial-intelligence/bin/python")
Sys.setlocale("LC_NUMERIC","fr_FR.UTF-8")
(width <- 4.5)\n```\n```{python fig.width=width}
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.show()\n```
', file="fig-size-bug.Rmd")
rmarkdown::render("fig-size-bug.Rmd")
system("grep 4,5 fig-size-bug.tex")
xfun::session_info("rmarkdown")
```

When running the code above on my system, the output is shown below:

```r
> rmarkdown::render("fig-size-bug.Rmd")


processing file: fig-size-bug.Rmd
                                                                                                            
output file: fig-size-bug.knit.md

/usr/bin/pandoc +RTS -K512m -RTS fig-size-bug.knit.md --to beamer --from markdown+autolink_bare_uris+tex_math_single_backslash --output fig-size-bug.tex --lua-filter /home/tdhock/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/tdhock/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --highlight-style tango --pdf-engine pdflatex --self-contained 
! Package keyval Error: 5in undefined.

Erreur : LaTeX failed to compile fig-size-bug.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See fig-size-bug.log for more info.
> system("grep 4,5 fig-size-bug.tex")
## [1] 4,5
\includegraphics[width=4,5in]{fig-size-bug_files/figure-beamer/unnamed-chunk-2-1}
> xfun::session_info("rmarkdown")
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS


Locale: fr_FR.UTF-8

time zone: America/Phoenix
tzcode source: system (glibc)

Package version:
  base64enc_0.1.3   bslib_0.5.1       cachem_1.0.8      cli_3.6.1        
  digest_0.6.33     ellipsis_0.3.2    evaluate_0.22     fastmap_1.1.1    
  fontawesome_0.5.2 fs_1.6.3          glue_1.6.2        graphics_4.3.1   
  grDevices_4.3.1   highr_0.10        htmltools_0.5.6.1 jquerylib_0.1.4  
  jsonlite_1.8.7    knitr_1.44        lifecycle_1.0.3   magrittr_2.0.3   
  memoise_2.0.1     methods_4.3.1     mime_0.12         R6_2.5.1         
  rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.25.1  sass_0.4.7       
  stats_4.3.1       stringi_1.7.12    stringr_1.5.0     tinytex_0.48     
  tools_4.3.1       utils_4.3.1       vctrs_0.6.4       xfun_0.40        
  yaml_2.3.7       

Pandoc version: 2.9.2.1
```

Please note that in the grep command, the first 4,5 is expected, because I set the french locale in my Rmd, so I would like to see that in the generated R code chunk output blocks (but it should be 4.5 in the tex file includegraphics width line).

**Comment by yihui** [comment]
Do you mean this only occurs for the `python` engine but not `r`? If so, I think you need to report to https://github.com/rstudio/reticulate/issues Thanks!

**Comment by tdhock** [comment]
r engine works fine, for example this MRE works:
````r
cat('---
title: "R code chunk test"
author: "Toby Dylan Hocking"
output: 
  beamer_presentation:
    dev: png
---
```{r}
Sys.setlocale("LC_NUMERIC","fr_FR.UTF-8")
(width <- 4.5)
```
```{r fig.width=width}
plot(1:4)
```
', file="fig-size-bug.Rmd")
rmarkdown::render("fig-size-bug.Rmd")
system("grep 4,5 fig-size-bug.tex")
xfun::session_info("rmarkdown")
````

**Comment by cderv** [comment]
FWIW On windows I can't reproduce this with latest RStudio version too 
````
> xfun::session_info("rmarkdown")
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621), RStudio 2023.12.0.201


Locale:
  LC_COLLATE=French_France.utf8 
  LC_CTYPE=French_France.utf8   
  LC_MONETARY=French_France.utf8
  LC_NUMERIC=fr_FR.UTF-8        
  LC_TIME=French_France.utf8    

time zone: Europe/Paris
tzcode source: internal

Package version:
  base64enc_0.1.3   bslib_0.5.1       cachem_1.0.8     
  cli_3.6.1         digest_0.6.33     ellipsis_0.3.2   
  evaluate_0.22     fastmap_1.1.1     fontawesome_0.5.2
  fs_1.6.3          glue_1.6.2        graphics_4.3.1   
  grDevices_4.3.1   highr_0.10        htmltools_0.5.6.1
  jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.44       
  lifecycle_1.0.3   magrittr_2.0.3    memoise_2.0.1    
  methods_4.3.1     mime_0.12         R6_2.5.1         
  rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.25   
  sass_0.4.7        stats_4.3.1       stringi_1.7.12   
  stringr_1.5.0     tinytex_0.48      tools_4.3.1      
  utils_4.3.1       vctrs_0.6.4       xfun_0.40        
  yaml_2.3.7       

Pandoc version: 3.1.8
````

If I do `rmarkdown::render("fig-size-bug.Rmd", output_options = list(keep_tex = TRUE))` to look at the tex file, I correctly get `4.5`

Also using latest reticulate 
````markdown
> xfun::session_info("reticulate")
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621), RStudio 2023.12.0.201


Locale:
  LC_COLLATE=French_France.utf8 
  LC_CTYPE=French_France.utf8   
  LC_MONETARY=French_France.utf8
  LC_NUMERIC=fr_FR.UTF-8        
  LC_TIME=French_France.utf8    

time zone: Europe/Paris
tzcode source: internal

Package version:
  graphics_4.3.1         grDevices_4.3.1       
  grid_4.3.1             here_1.0.1            
  jsonlite_1.8.7         lattice_0.21.9        
  Matrix_1.6.1.1         methods_4.3.1         
  png_0.1.8              rappdirs_0.3.3        
  Rcpp_1.0.11            RcppTOML_0.2.2        
  reticulate_1.34.0.9000 rlang_1.1.1           
  rprojroot_2.0.3        stats_4.3.1           
  utils_4.3.1            withr_2.5.1  
````

**Comment by tdhock** [comment]
Hi @yihui 
@t-kalinowski said 
I'm not sure this is reticulate issue, and it's not clear to me what we can do to fix it in reticulate. In reticulate::eng_python() we only read chunk options options$fig.width and options$fig.height and pass them through to the appropriate python contexts for rendering plots; we don't munge on the options any further, and return them unmodified.

I think this might be a knitr::include_graphics() bug, since that's how reticulate includes python plots, and is a difference between the Python MRE and the R examples in https://github.com/rstudio/rmarkdown/issues/2525#issuecomment-1778432785

**Comment by tdhock** [comment]
I confirm this is still an issue for me with the following package versions:
```
> xfun::session_info("rmarkdown")
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Locale: fr_FR.UTF-8

Package version:
  base64enc_0.1.3   bslib_0.6.1       cachem_1.0.8      cli_3.6.2         digest_0.6.34    
  ellipsis_0.3.2    evaluate_0.23     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3         
  glue_1.7.0        graphics_4.3.2    grDevices_4.3.2   highr_0.10        htmltools_0.5.7  
  jquerylib_0.1.4   jsonlite_1.8.8    knitr_1.45        lifecycle_1.0.4   magrittr_2.0.3   
  memoise_2.0.1     methods_4.3.2     mime_0.12         R6_2.5.1          rappdirs_0.3.3   
  rlang_1.1.3       rmarkdown_2.25.1  sass_0.4.8        stats_4.3.2       stringi_1.8.3    
  stringr_1.5.1     tinytex_0.49      tools_4.3.2       utils_4.3.2       vctrs_0.6.5      
  xfun_0.41         yaml_2.3.8       

Pandoc version: 2.9.2.1
```

**Comment by yihui** [comment]
> I think this might be a knitr::include_graphics() bug, since that's how reticulate includes python plots

Thanks! That's it. The problem came from here: https://github.com/yihui/knitr/blob/a14074c58e46fb51f61b219c8a195a8ef4914971/R/plot.R#L534

I'm not sure what we should do about it, though. R will warn against setting `LC_NUMERIC`:

```
> Sys.setlocale("LC_NUMERIC","fr_FR.UTF-8")
[1] "fr_FR.UTF-8"
Warning message:
In Sys.setlocale("LC_NUMERIC", "fr_FR.UTF-8") :
  setting 'LC_NUMERIC' may cause R to function strangely
```

The problem is that decimal points will be commas after you change `LC_NUMERIC`. I don't see a way to change that behavior other than temporarily setting `LC_NUMERIC` to `C`. Anyway, I recommend that you reset `LC_NUMERIC` to `C` unless you have a reason not to do so, otherwise you may run into other problems anyway as the warning indicated.

Another solution is specify the chunk option `out.width` by yourself, e.g., `out.width='4.5in'`.

**Comment by tdhock** [comment]
hi! thanks for suggesting the `out.width` work-around, that works for me, although it is a bit awkward (not very user friendly) to have to switch to LC_NUMERIC=C when I want to create the out.width string, (see code below) then switch back to French if I want code chunk output to have `,` as decimal separator. It seems that it would be a lot easier and user friendly if this could be handled internally on your side (please?)

The fix that I would suggest in your code is to temporarily set LC_NUMERIC to C when you convert numeric/fig.width (4.5) to text/out.width, and then switch locale back to whatever the user had before that.

This issue should affect anybody in French speaking countries, with a French locale on their computer, so I'm surprised I'm the only one having reported this issue so far. Even though R warns that it may function strangely, most people in French speaking countries probably do want to display code chunk numeric decimal output using the traditional French comma/virgule/, (instead of the English period/point/.)

```r
cat('---
title: "matplotlib test"
author: "Toby Dylan Hocking"
output: 
  beamer_presentation:
    dev: png
---\n```{r}
Sys.setenv(RETICULATE_PYTHON="/home/tdhock/miniconda3/envs/2023-08-artificial-intelligence/bin/python")
width.in <- 4.5
Sys.setlocale("LC_NUMERIC", "C")
(out.width <- paste0(width.in,"in"))
Sys.setlocale("LC_NUMERIC", "fr_FR.UTF-8")
width.in
\n```\n```{python out.width=out.width}
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.show()\n```
', file="fig-size-bug.Rmd")
rmarkdown::render("fig-size-bug.Rmd")
```

**Comment by cderv** [comment]
(note that I am french) 

Usually, I will do that in the formatting function to set comma in printed values. `format()` function as a `decimal.mark` option for example. 

There is also a global option for this (that `format()` will use too), which is `OutDec` [options](https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html)
> OutDec:
> character string containing a single character. The preferred character to be used as the decimal point in output conversions, that is in printing, plotting, [format](https://stat.ethz.ch/R-manual/R-devel/library/base/help/format.html), [formatC](https://stat.ethz.ch/R-manual/R-devel/library/base/help/formatC.html) and [as.character](https://stat.ethz.ch/R-manual/R-devel/library/base/help/as.character.html) but not when deparsing nor by [sprintf](https://stat.ethz.ch/R-manual/R-devel/library/base/help/sprintf.html) (which is sometimes used prior to printing).

But this can cause issues with functions and packages that do not handle this correctly especially if the value printed must have a `.` instead (like in tex file size).  So usually I am setting that on specific content to print (for example using `withr::with_options()` to apply only the expression. 

I think even using `options(OutDec = ",")` will cause issue here, because if set the printed value in the tex file will have a commas.

Anyhow, `LC_NUMERIC` is not usually something to play with. Here is the doc of R itself 
https://stat.ethz.ch/R-manual/R-devel/library/base/html/locales.html

![image](https://github.com/rstudio/rmarkdown/assets/6791940/16a9b4a0-6ea5-49af-bc1b-818d4aa6cbbf)

It explains the warning you see. 

So I am not sure this should be used to change a period to a comma. Not sure we should handle it either directly. Though, maybe we should ensure to use `OutDec = "."` when we print to  size for tex file. 

I don't remember any report of this though, so maybe it is just due to LC_NUMERIC change. 🤷

**Comment by yihui** [comment]
> This issue should affect anybody in French speaking countries, with a French locale on their computer, so I'm surprised I'm the only one having reported this issue so far.

@tdhock Using the French locale should be fine. The problem arises only when you manipulate `LC_NUMERIC`.

Even under the French locale, `LC_NUMERIC` is still `C` by default, as you can see below:

```
% echo $LANG
en_US.UTF-8

% LANG=fr_FR.UTF-8 R

> Sys.getlocale()
[1] "fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8"

> Sys.getlocale('LC_NUMERIC')
[1] "C"
```

My locale is `en_US.UTF-8`. Then I temporarily change it to French and start R in the terminal. `LC_NUMERIC` is `C` instead of `fr_FR.UTF-8`. I don't know why it's different on your computer.

Can we fix it? Yes we can, but I wish to understand why the problem occurs first. As I said, even we fix this specific problem in **knitr**, there is a chance that `LC_NUMERIC=fr_FR.UTF-8` can cause you other trouble in other places, which can be hard to fix case by case, and the best fix might be reset `LC_NUMERIC` to the correct value.

@cderv We have been bitten by this `OutDec` problem a few times before: https://github.com/search?q=repo%3Ayihui%2Fknitr+OutDec&type=code I'm not sure what the best fix would be. It sounds burdensome to have to temporarily set `options(OutDec = '.')` whenever we need to coerce a number to character...

**Comment by tdhock** [comment]
thanks for the detailed comments/feedback. Actually to clarify, I'm not setting the LC_NUMERIC specifically in my code usually, I just did that in the code above for reproducibility. On my computer (Ubuntu jammy) the LC_NUMERIC locale is fr_FR.UTF-8 by default, which is why I filed the issue in the first place (and it took me quite a while to figure out the comma issue, so by filing this issue I am trying to avoid similar headaches for others in the future).

**Comment by yihui** [comment]
Should be fixed in the development version of **knitr** now:

```r
remotes::install_github('yihui/knitr')
```

**Comment by tdhock** [comment]
works now, thanks very much.
I do get a message about changing the LC_NUMERIC, which you may want to suppress?
```
Output created: fig-size-bug.pdf
Message d'avis :
Dans Sys.setlocale("LC_NUMERIC", lcn) :
  changer 'LC_NUMERIC' peut résulter en un fonctionnement étrange de R
```

**Comment by yihui** [comment]
Sure. Done:

```r
remotes::install_github('yihui/xfun')
```
