### ISSUE TITLE
Persistent resetting of "Editor content width" in visual mode of Rmarkdown docs

### ISSUE THREAD

**Issue by SaltyRydM** [rstudio/rmarkdown#2531]
Greetings,

I've been experiencing a persistent issue while using "Visual mode" for editing RMarkdown documents.

The problem revolves around the "editor content width," which constantly resets. Whenever I'm working on sections of plain text, I prefer to specify the "editor content width" within settings Tools -> Global Options -> R Markdown -> Visual -> Editor content width (px). However, this setting consistently reverts to default settings following certain actions. For example:

- Right-clicking on a misspelled word causes the reset, as illustrated below.
- Clicking on various options such as "Format," "Insert," or "Table" (highlighted in red) also triggers the reset.
- Switching between tabs of different RMarkdown documents, adjusting the window size, or performing other basic interactions lead to the same issue.

I can easily recreate this issue by opening two Rmarkdown documents in RStudio, were one will function normally while the other(s) are bugged.

This recurring problem disrupts the workflow significantly and impacts the editing process.

I kindly request your assistance in investigating and resolving this issue as soon as possible. Should you require any further details or specific examples, please don't hesitate to reach out.

Best regards,
Marius

With preferred editor content width:
<img width="1418" alt="Editor-content-width" src="https://github.com/rstudio/rmarkdown/assets/65944393/f9d66835-3e0f-4c68-81cf-b03fd51c72a9">

After I right click on misspelled word (or other interactions):
<img width="1420" alt="bugged" src="https://github.com/rstudio/rmarkdown/assets/65944393/8915eb05-9830-486c-a9b9-7a52eef9b9ec">

Additional info:
xfun::session_info('rmarkdown')
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.2, RStudio 2023.9.1.494

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   bslib_0.6.1       cachem_1.0.8      cli_3.6.1         digest_0.6.33     ellipsis_0.3.2   
  evaluate_0.23     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3          glue_1.6.2        graphics_4.3.2   
  grDevices_4.3.2   highr_0.10        htmltools_0.5.7   jquerylib_0.1.4   jsonlite_1.8.8    knitr_1.45       
  lifecycle_1.0.4   magrittr_2.0.3    memoise_2.0.1     methods_4.3.2     mime_0.12         R6_2.5.1         
  rappdirs_0.3.3    rlang_1.1.2       rmarkdown_2.25    sass_0.4.8        stats_4.3.2       stringi_1.8.2    
  stringr_1.5.1     tinytex_0.49      tools_4.3.2       utils_4.3.2       vctrs_0.6.5       xfun_0.41        
  yaml_2.3.7       

Pandoc version: 3.1.1

**Comment by cderv** [comment]
This is an issue  with Visual Editor feature of RStudio IDE. 

Can you open your issue in https://github.com/rstudio/rstudio following their guide https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports ? 

Thank you !
