### ISSUE TITLE
`fig.dim` doesn't work (rmarkdown: 2.25)

### ISSUE THREAD

**Issue by wbvguo** [rstudio/rmarkdown#2539]
Hello,

It seems the `fig.dim` option is not working in the code chunk, while `fig.height`, `fig.width` works fine
![image](https://github.com/rstudio/rmarkdown/assets/31968837/7faf7526-5efc-4133-9ad2-b7e5d0e1e491)

![image](https://github.com/rstudio/rmarkdown/assets/31968837/5b88f7e0-7ab8-49cc-8e1a-a2d00c767cef)

Package Version:
```r
packageVersion("rmarkdown")
[1] ‘2.25’
```

Thanks,
Wenbin

**Comment by cderv** [comment]
Hi thanks for the report. 

When you say not working, 

- Is this in the output after rendering with `html_document()` or another format ? 
- Is this in the IDE notebook mode when executing interactively the code cells to preview plots ¿

The screenshot made me think of the latter, but I am unsure. If this is it, then it is a feature request in the RStudio IDE notebook mode to support this option for plot preview. 

Thanks

**Comment by wbvguo** [comment]
Hi, thanks for your response.

Yes, I mean the later one:
> in the IDE notebook mode, when executing interactively the code cells to preview plots

the rendered `html` file has the correct specified length/width. 

I will make a feature request on RStudio IDE, and close this issue now. Thanks for your suggestion!
