### ISSUE TITLE
Citations not working where multiple articles from same author in same year

### ISSUE THREAD

**Issue by befriendabacterium** [rstudio/rmarkdown#2545]
## Issue
When there are multiple papers from the same author from the same year, RStudio/RMarkdown's "Insert Citation" feature in the Visual editor linking to Zotero won't register that some articles exist, so I can't cite these articles.

## Minimal reproducible example

This is done in the visual editor, so please use the files provided to reproduce via the screenshots.

The folder in Zotero has three refs from same year:

![image](https://github.com/rstudio/rmarkdown/assets/42059798/27ec1a94-daec-4216-bd18-21d6da9ab338)

However, in the Insert Citation window in RStudio/markdown, it only find two. So it seems to struggle when over 2 from same author in same year?

![image](https://github.com/rstudio/rmarkdown/assets/42059798/f07a8e0a-37e0-45b7-96ba-66cfe73de2a7)

The content of 'wolfgang.bib' is (apologies i cannot attach here because github does not accept this file format):

```
@misc{viechtbauerComparisonRmaUni2022,
  title = {A {{Comparison}} of the Rma.Uni() and Rma.Mv() {{Functions}} [{{The}} Metafor {{Package}}]},
  author = {Viechtbauer, Wolfgang},
  year = {2022},
  month = aug,
  journal = {The metafor Package: A Meta-Analysis Package for R},
  urldate = {2024-02-28},
  howpublished = {https://www.metafor-project.org/doku.php/tips:rma.uni\_vs\_rma.mv?s[]=random\&s[]=effects},
  file = {C:\Users\mlj206\Zotero\storage\Z5JA2K6R\tipsrma.uni_vs_rma.html}
}

@misc{viechtbauerCrede2010Metafor2022,
  title = {Cred{\'e} et al. (2010) [{{The}} Metafor Package]},
  author = {Viechtbauer, Wolfgang},
  year = {2022},
  journal = {The metafor Package: A Meta-Analysis Package for R},
  howpublished = {https://www.metafor-project.org/doku.php/analyses:crede2010?s[]=multiple\&s[]=outcomes\#intraclass\_correlation\_of\_the\_true\_outcomes}
}

@misc{viechtbauerForestPlotAggregated2022,
  title = {Forest {{Plot}} with {{Aggregated Values}} [{{The}} Metafor {{Package}}]},
  author = {Viechtbauer, Wolfgang},
  year = {2022},
  month = aug,
  journal = {The metafor Package: A Meta-Analysis Package for R},
  urldate = {2024-01-22},
  howpublished = {https://www.metafor-project.org/doku.php/tips:forest\_plot\_with\_aggregated\_values?s\%3E[]=forest\&s[]=plot\&s[]=aggregated},
  file = {C:\Users\mlj206\Zotero\storage\NW7PZHUJ\tipsforest_plot_with_aggregated_values.html}
}

@misc{viechtbauer2022,
	title = {A Comparison of the rma.uni() and rma.mv() Functions [The metafor Package]},
	author = {Viechtbauer, Wolfgang},
	year = {2022},
	month = {08},
	date = {2022-08-03},
	url = {https://www.metafor-project.org/doku.php/tips:rma.uni_vs_rma.mv?s[]=random&s[]=effects}
}

```

The preamble of the RMarkdown doc should look something like (apologies i cannot attach here because github does not accept this file format):

```r
---
title: "Multiple articles per author bug"
author: "Matt Lloyd Jones"
date: "2024-03-11"
output: html_document
bibliography: wolfgang_betterbib.bib
---

wolfgang_betterbib.bib should be in same directory as RMarkdown doc, for clarity.

```
## Session Info

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045), RStudio 2023.6.1.524

Locale:
  LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8
  LC_NUMERIC=C                            LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

Package version:
  base64enc_0.1.3   bslib_0.5.0       cachem_1.0.6      cli_3.6.0         digest_0.6.31     ellipsis_0.3.2    evaluate_0.23    
  fastmap_1.1.0     fontawesome_0.5.1 fs_1.5.2          glue_1.6.2        graphics_4.3.1    grDevices_4.3.1   highr_0.10       
  htmltools_0.5.5   jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.43        lifecycle_1.0.4   magrittr_2.0.3    memoise_2.0.1    
  methods_4.3.1     mime_0.12         R6_2.5.1          rappdirs_0.3.3    rlang_1.1.1       rmarkdown_2.23    sass_0.4.7       
  stats_4.3.1       stringi_1.7.12    stringr_1.5.1     tinytex_0.45      tools_4.3.1       utils_4.3.1       vctrs_0.6.2      
  xfun_0.39         yaml_2.3.7       

Pandoc version: 3.1.1

## Other

I am running Zotero

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X ] included a minimal, self-contained, and reproducible example?

- [X ] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

**Comment by cderv** [comment]
Thanks for the report. 

If this happens with the visual editor, we'll need to move this in another repo, as **rmarkdown** itself is not involved in this. Is this in RStudio IDE ?

**Comment by befriendabacterium** [comment]
Ah ok - hm, well I initially thought it was an Rmarkdown/visual editor problem but i've just had a look and it seems to be related to the BetterBibTex format specifically...I'm not sure if there's some compatibility between RMarkdown/VE/BetterBibtex issue going on here. Tagging @retorquere in case they wish to investigate/contribute to discussion. Updated the issue accordingly. Maybe be worth looking if this happens in non-vis editor too?

**Comment by befriendabacterium** [comment]
For completeness, the normal, non-better bib file looks like:

```


@misc{viechtbauerForestPlotAggregated2022,
	title = {Forest {Plot} with {Aggregated} {Values} [{The} metafor {Package}]},
	url = {https://www.metafor-project.org/doku.php/tips:forest_plot_with_aggregated_values?s%3E[]=forest&s[]=plot&s[]=aggregated},
	urldate = {2024-01-22},
	journal = {The metafor Package: A Meta-Analysis Package for R},
	author = {Viechtbauer, Wolfgang},
	month = aug,
	year = {2022},
	file = {Forest Plot with Aggregated Values [The metafor Package]:C\:\\Users\\mlj206\\Zotero\\storage\\NW7PZHUJ\\tipsforest_plot_with_aggregated_values.html:text/html},
}

@misc{viechtbauerCrede2010Metafor2022,
	title = {Credé et al. (2010) [{The} metafor package]},
	url = {https://www.metafor-project.org/doku.php/analyses:crede2010?s[]=multiple&s[]=outcomes#intraclass_correlation_of_the_true_outcomes},
	journal = {The metafor Package: A Meta-Analysis Package for R},
	author = {Viechtbauer, Wolfgang},
	year = {2022},
}

@misc{viechtbauerComparisonRmaUni2022,
	title = {A {Comparison} of the rma.uni() and rma.mv() {Functions} [{The} metafor {Package}]},
	url = {https://www.metafor-project.org/doku.php/tips:rma.uni_vs_rma.mv?s[]=random&s[]=effects},
	urldate = {2024-02-28},
	journal = {The metafor Package: A Meta-Analysis Package for R},
	author = {Viechtbauer, Wolfgang},
	month = aug,
	year = {2022},
	file = {A Comparison of the rma.uni() and rma.mv() Functions [The metafor Package]:C\:\\Users\\mlj206\\Zotero\\storage\\Z5JA2K6R\\tipsrma.uni_vs_rma.html:text/html},
}

```

Seems like BetterBibTex is duplicating a reference?

**Comment by retorquere** [comment]
BBT isn't always involved with the rstudio integration - is it in this case? If so, I'd need to know what is being called in BBT. I

**Comment by retorquere** [comment]
> For completeness, the normal, non-better bib file looks like:
> 
> ```
> 
> 
> @misc{viechtbauerForestPlotAggregated2022,
> 	title = {Forest {Plot} with {Aggregated} {Values} [{The} metafor {Package}]},
> 	url = {https://www.metafor-project.org/doku.php/tips:forest_plot_with_aggregated_values?s%3E[]=forest&s[]=plot&s[]=aggregated},
> 	urldate = {2024-01-22},
> 	journal = {The metafor Package: A Meta-Analysis Package for R},
> 	author = {Viechtbauer, Wolfgang},
> 	month = aug,
> 	year = {2022},
> 	file = {Forest Plot with Aggregated Values [The metafor Package]:C\:\\Users\\mlj206\\Zotero\\storage\\NW7PZHUJ\\tipsforest_plot_with_aggregated_values.html:text/html},
> }
> 
> @misc{viechtbauerCrede2010Metafor2022,
> 	title = {Credé et al. (2010) [{The} metafor package]},
> 	url = {https://www.metafor-project.org/doku.php/analyses:crede2010?s[]=multiple&s[]=outcomes#intraclass_correlation_of_the_true_outcomes},
> 	journal = {The metafor Package: A Meta-Analysis Package for R},
> 	author = {Viechtbauer, Wolfgang},
> 	year = {2022},
> }
> 
> @misc{viechtbauerComparisonRmaUni2022,
> 	title = {A {Comparison} of the rma.uni() and rma.mv() {Functions} [{The} metafor {Package}]},
> 	url = {https://www.metafor-project.org/doku.php/tips:rma.uni_vs_rma.mv?s[]=random&s[]=effects},
> 	urldate = {2024-02-28},
> 	journal = {The metafor Package: A Meta-Analysis Package for R},
> 	author = {Viechtbauer, Wolfgang},
> 	month = aug,
> 	year = {2022},
> 	file = {A Comparison of the rma.uni() and rma.mv() Functions [The metafor Package]:C\:\\Users\\mlj206\\Zotero\\storage\\Z5JA2K6R\\tipsrma.uni_vs_rma.html:text/html},
> }
> 
> ```
> 
> Seems like BetterBibTex is duplicating a reference?

Is BBT making this via an auto export (in which case it'd be a BBT bug) or is rstudio pulling it from the pull export and assembling it (in which case it's not a BBT problem). I have no idea what is happening here.

**Comment by befriendabacterium** [comment]
Honestly I’m not sure I do either 🥴 but those bibtex files were manually generated by me via Zotero, choosing bibtex or betterbibtex as  the export option. 

What really confuses me is that when I put the better bibtex file (wolfgang_betterbib.bib) as the reference file in the markdown preamble, the Insert Citations visual interface actually reads my whole Zotero folder somehow. Then when I go back to using the ‘normal’ bib file (wolfgang_normalbib.bib) it still does this.” (even though it was working before I used better bib). So it seems somehow related to rmarkdown and/or the visual interface, as well as the better bibtex?! Sorry I can’t narrow it down more I’m pretty damn confused. Thanks for your patience so far.

**Comment by retorquere** [comment]
That doesn't look like a duplicate btw. If the keys are different, there's a duplicate entry in Zotero. We can look into that if you want, but that's going to be the cause. 

If rstudio picks up the results incorrectly, there's nothing I can do about that.

**Comment by befriendabacterium** [comment]
Yeah there’s no duplicate in Zotero. So I suppose the BBT export is duplicating the entry somehow? But I’m not sure if this is even a separate issue to the bot picking up references one?!

**Comment by retorquere** [comment]
Please open an issue on the BBT project. I'll look into it.

**Comment by befriendabacterium** [comment]
Hi Emiliano, 

I've investiated this more thoroughly this morning and neither the bug of not identifying all the articles, or duplicating references with new keys, are specific to BBT, so it's either RMarkdown or RStudio's bug so I'll raise it with RStudio too, instead of you. Thanks for your help!

Cheers
Matt

**Comment by befriendabacterium** [comment]
@cderv I've raised this as a bug in RStudio too, providing a hopefully improved report. Still not sure if it's Rmarkdown or RStudio IDE causing this but maybe with some initial investigation you can identify which and close one of these issues? https://github.com/rstudio/rstudio/issues/14409

**Comment by cderv** [comment]
> Still not sure if it's Rmarkdown or RStudio IDE causing this but maybe with some initial investigation you can identify which and close one of these issues?

It seems to be reading your issue that you want to import from Zotero. I am not sure of your workflow but here how it is supposed to work (More context at: https://rstudio.github.io/visual-markdown-editing/citations.html): 

- When you have a bib file, provided as `bibliography` field in your document, the visual editor will find this, and show you the entry 
  ![image](https://github.com/rstudio/rmarkdown/assets/6791940/b2b13480-c8d7-49b5-9f88-7d042f67feb8)

  I am mentioning this, because if you export to bib file from zotero already, the visual editor should be able to find all the ref in your bib file - you can avoid using zotero lib directly.

- It will also find your Zotero library, and you can import directly from it and it will add an entry to your bib file  
  ![image](https://github.com/rstudio/rmarkdown/assets/6791940/53b55396-ee05-47ee-a018-4ca211bddf80)

It seems in your case 

* Bug 1 is : 
	* Visual editor Zotero support don't see all the references you have in your library. 

* Bug 2: 
	*  As it does not see all the ref, but one with ref `viechtbauer2022a`, it will add it anyway in the current bib file. 

If I understand ok, this is both bug related to Visual Editor, and not **rmarkdown** R package.

**Comment by retorquere** [comment]
Or BBT for that matter.

**Comment by befriendabacterium** [comment]
Hi  Christophe,

Yep, that's correct - you are correct both that I am following that workflow, and in your description of the bugs. I also agree now that this can be narrowed down to an issue with the way the Visual Editor is reading the Zotero library - it's simply not finding all references where the same author is publishing multiple articles in the same year. This is supported by the fact that I can cite all three references using the untidied citation keys in the references file (workingversion.bib) with the '@reference' syntax.*

Thanks both @cderv and @retorquere for helping me figure this out - @cderv feel free to close to be dealt with at https://github.com/rstudio/rstudio/issues/14409.

Cheers
Matt

*I will flag though that a new issue now emerges in that only the first reference in the bibliography has the author name (even though the author name is present as a field in the bibliography file):

![image](https://github.com/rstudio/rmarkdown/assets/42059798/3993ae80-5e09-49c8-a46d-4e18771f7182)

**Comment by retorquere** [comment]
I'm going to assume that if a change to BBT is wanted at some point, an issue will be opened on the BBT github project.

**Comment by befriendabacterium** [comment]
@retorquere don't think there's any change to BBT needed from this, to confirm. Thanks!

**Comment by cderv** [comment]
> I will flag though that a new issue now emerges in that only the first reference in the bibliography has the author name (even though the author name is present as a field in the bibliography file

@befriendabacterium this is expected. It is because the default CSL is Chicago Manual of Style, author date and the CSL has this spec 
````xml
<bibliography hanging-indent="true" et-al-min="11" et-al-use-first="7" subsequent-author-substitute="&#8212;&#8212;&#8212;" entry-spacing="0">
````

which means that if an author is repeated, some character will be put in place to avoid repeating. 

If you don't want that, you need to change `csl` style to another one that does not have this

**Comment by cderv** [comment]
> feel free to close to be dealt with at https://github.com/rstudio/rstudio/issues/14409.

I'll do that thanks !
