### ISSUE TITLE
Adding suffixes on references in Citations widows

### ISSUE THREAD

**Issue by franceskoi** [rstudio/rmarkdown#2569]
Visual -> Insert -> Citations  works fine when adding references via DOI, but when I have to make a reference which doesn't have a DOI (with only a web address for a certain report) I have to do it in Zotero, and after that, all my previously inserted references via Visual (Citations) get suffixes (a, b, c) in the end of their names in the Citations window, and when I want to insert them again in the R Markdown file, they come up with those suffixes.
Is there a way to avoid this behavior?

![suffixes for references](https://github.com/user-attachments/assets/f673bbf9-ddc7-4ce9-a069-e2b114b98f13)

**Comment by yihui** [comment]
This is an RStudio IDE issue. Please report to https://github.com/rstudio/rstudio instead. Thanks!
