### ISSUE TITLE
"Error in file: cannot open the connection" when rendering child rmarkdown document with `runtime: shiny`

### ISSUE THREAD

**Issue by rempsyc** [rstudio/rmarkdown#2574]
## Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

# Issue 

Apologies if this has already been documented in a different issue (I could not find one). This [source](https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html) describes child documents and this [source](https://bookdown.org/yihui/rmarkdown/shiny-start.html) describes using `runtime: shiny` in an rmarkdown document. However, I encounter a problem when attempting to use both of them together: `Error in file: cannot open the connection`, suggesting that rmarkdown and shiny rely on different working environments. Changing the working directory from within the rmarkdown file doesn't seem to help either.

# Reprex

The minimalist rmarkdown file below works very well with its child file (the child file only contains the string "Hello world").

````
---
output: html_document
---

```{r, child=c('child.Rmd')}
```
````

However, adding `runtime: shiny` to the YAML:

````
---
output: html_document
runtime: shiny
---

```{r, child=c('child.Rmd')}
```
````

Leads to the following error when knitting from RStudio or using `rmarkdown::run("parent.Rmd")`:

```
Warning in file(con, "r") :
  cannot open file 'C:/Users/there/AppData/Local/Temp/Rtmp0sJTFB/child.Rmd': No such file or directory

Quitting from lines 8-8 [unnamed-chunk-1] (C:\Users\there\AppData\Local\Temp\Rtmp0sJTFB\file3304301b1d05.md)
Warning: Error in file: cannot open the connection
  145: <Anonymous>
  144: signalCondition
  143: signal_abort
  142: cnd_signal
  141: rlang::entrace
  140: h
  139: .handleSimpleError
  138: file
  137: readLines
  136: xfun::read_utf8
  135: knit
  134: FUN
  133: lapply
  132: tangle_block
  131: process_tangle
  128: process_file
  127: knit
  126: knitr::purl
  125: discover_rmd_resources
  124: find_external_resources
  123: copy_render_intermediates
  122: output_format$intermediates_generator
  121: <Anonymous>
  116: <reactive>
  100: doc
   99: renderUI
   98: func
   85: renderFunc
   84: output$__reactivedoc__
    3: <Anonymous>
    1: rmarkdown::run
```

Is this a bug, or is there another established way to work in those cases?

# Session Info

<details>
<summary>Session Info</summary>
<br>

``` r
packageVersion("rmarkdown")
[1] ‘2.28.2’
packageVersion("shiny")
[1] ‘1.9.1’

xfun::session_info(c('rmarkdown', 'shiny'))
R version 4.4.1 Patched (2024-07-08 r86915 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631), RStudio 2024.4.2.764

Locale:
  LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
  LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

Package version:
  base64enc_0.1.3     bslib_0.8.0         cachem_1.1.0        cli_3.6.3           commonmark_1.9.1   
  crayon_1.5.3        digest_0.6.37       evaluate_0.24.0     fastmap_1.2.0       fontawesome_0.5.2  
  fs_1.6.4            glue_1.7.0          graphics_4.4.1      grDevices_4.4.1     highr_0.11         
  htmltools_0.5.8.1   httpuv_1.6.15       jquerylib_0.1.4     jsonlite_1.8.8      knitr_1.48         
  later_1.3.2         lifecycle_1.0.4     magrittr_2.0.3      memoise_2.0.1       methods_4.4.1      
  mime_0.12           promises_1.3.0      R6_2.5.1            rappdirs_0.3.3      Rcpp_1.0.13        
  rlang_1.1.4         rmarkdown_2.28.2    sass_0.4.9          shiny_1.9.1         sourcetools_0.1.7.1
  stats_4.4.1         tinytex_0.52        tools_4.4.1         utils_4.4.1         withr_3.0.1        
  xfun_0.47           xtable_1.8.4        yaml_2.3.10        

Pandoc version: 3.1.11
```

</details>

**Comment by cderv** [comment]
This is an issue with how child option is set. If you do this, no problem. 
````markdown
---
output: html_document
runtime: shiny
---

```{r, child='child.Rmd'}
```
````

In happens only with `runtime: shiny` here because we need to find dependencies and so we run `rmarkdown::find_external_resources()` internally. This is supposed to look for child document to also discover dependencies in it. But here is what we do
https://github.com/rstudio/rmarkdown/blob/da85f8c7a6294cab3447a41ad82e4018a51139c4/R/html_resources.R#L308-L331
The regex used does not match the specific `c("child.Rmd")` option. 
https://github.com/rstudio/rmarkdown/blob/da85f8c7a6294cab3447a41ad82e4018a51139c4/R/html_resources.R#L319

So right now you can change the option syntax, and we'll probably add support for finding using `c()` in the option. 

Again, a problem of regex for static analysis... 


Thanks !

**Comment by cderv** [comment]
Reprex: 

This is  `test.Rmd`

````markdown
---
output: html_document
---

```{r, child=c('child.Rmd')}
```
````

````
> rmarkdown::find_external_resources("test.Rmd")
Error in `file()`:
! impossible d'ouvrir la connexion
Backtrace:
  1. knitr::knit(..., tangle = TRUE)
  2. knitr:::process_file(text, output)
  5. knitr:::process_tangle(group)
  6. knitr:::tangle_block(x)
  7. base::lapply(sc_split(params$child), knit_child)
  8. knitr (local) FUN(X[[i]], ...)
  9. knitr::knit(..., tangle = opts_knit$get("tangle"), envir = envir)
 10. xfun::read_utf8(input)
 11. base::readLines(con, encoding = "UTF-8", warn = FALSE)
 12. base::file(con, "r")
Message d'avis :
Dans file(con, "r") :
  impossible d'ouvrir le fichier 'C:/Users/chris/AppData/Local/Temp/RtmpEP25bq/child.Rmd' : No such file or directory

Quitting from lines 7-7 [unnamed-chunk-1] (C:\Users\chris\AppData\Local\Temp\RtmpEP25bq\file8eac72032fef.md)
````

It should detect `child.Rmd`
