### ISSUE TITLE
R Markdown not working, code is shown instead of output

### ISSUE THREAD

**Issue by LeaLe88** [rstudio/rmarkdown#2578]
Good afternoon,

For some reason suddenly my rmarkdown doesnt hide code anymore & doesnt show the output.

Even when I run the example in RStudio (by pressing "Knit to html") for a Rmarkdown sheet it doesnt show the output correctly.
Please find the example and output below:

````
---
title: "Untitled"
output: html_document
date: "2024-09-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. r more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any bedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

````

Output:

![image](https://github.com/user-attachments/assets/0b6b8c17-d861-42b2-8fe4-96a05a2d20da)

Anyone has any idea what could be the issue?

Thank you!

**Comment by cderv** [comment]
Your document mentions `output: html_document` but your screenshot seems to be PDF

How are you rendering ? 

This is duplicated from community forum: https://forum.posit.co/t/r-markdown-suddenly-showing-output-of-code/191714 - is this your report there too ? 


Rstudio version used  is the latest release
````
> RStudio.Version()$version
[1] ‘2024.9.0.375’
````


I can't reproduce by using your document (I edited to get correct source above) - it gives me a PDF when I click with PDF and all the code shows correctly.

**Comment by cderv** [comment]
BTW it seems [forum.posit.co/t/r-markdown-suddenly-showing-output-of-code/191714](https://forum.posit.co/t/r-markdown-suddenly-showing-output-of-code/191714) - is solved now by restarting correctly everything.

**Comment by LeaLe88** [comment]
Yes thank you!
