### ISSUE TITLE
envir param doesn't work

### ISSUE THREAD

**Issue by avishai987** [rstudio/rmarkdown#2582]
Hi, I am trying to render with a new environment, but it keeps rendering with parent env. 
Example:
When I type in console:

```r
a = "3"
``` 
 and render my file: 

```r
title: "R Notebook"
output:  html_document


print(a)

print("234")
``` 

with:
```r
rmarkdown::render("my_test.Rmd",envir = new.env())
``` 

I get no error, and it prints "a" variable from my global environment. 

Thanks,
Avishai
## session info:
```r
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS, RStudio 2024.9.0.375

Locale:
  LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
  LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   bslib_0.3.1       digest_0.6.29     evaluate_0.15     fastmap_1.1.0     fontawesome_0.5.2 fs_1.5.2         
  graphics_4.4.1    grDevices_4.4.1   highr_0.11        htmltools_0.5.2   jquerylib_0.1.4   jsonlite_1.8.9    knitr_1.49       
  methods_4.4.1     R6_2.5.1          rappdirs_0.3.3    rlang_1.1.4       rmarkdown_2.29    sass_0.4.1        stats_4.4.1      
  tinytex_0.38      tools_4.4.1       utils_4.4.1       xfun_0.49         yaml_2.3.5       

Pandoc version: 3.4
``` 

## Checklist
When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

**Comment by yihui** [comment]
That's expected. Please see the help page `?new.env` (in particular, see the default of its `parent` argument). You might be expecting `new.env(parent = emptyenv())`.
