### ISSUE TITLE
Interactive bash/shell session not working

### ISSUE THREAD

**Issue by julianbarg** [rstudio/rmarkdown#2583]
## Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [X] included a minimal, self-contained, and reproducible example?

- [X] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [X] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [X] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")` ?

## Issue

I've tried many different things, but interactive bash sessions are broken, at least for my system (and a couple previous, similar installs). Here is a reproducible example:

rmarkdown file

````
```{bash set}
TEST="Hello World!"
```

```{bash test}
echo $TEST
```
````

I am manually knitting with `render("test.Rmd", html_document())` to ensure that I am using the development version of rmarkdown in my test. Obviously, I would expect the first chunk not to return anything and the second chunk to print "Hello world!" The second chunk does not print anything, implying that the variable is not cell. In addition, I tried setting `knitr::opts_chunk$set(engine.opts = list(bash = "-i"))` in an R chunk to ensure that we are running an interactive session. Now we get the (only slightly more helpful) error message:

```
## bash: cannot set terminal process group (61774): Inappropriate ioctl for device
## bash: no job control in this shell
```

Here is the output of session_info. Note that I had the same issue with previous systems, most recently the stable version of debian. Have not tested any MacOS or Windows systems.

```
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Debian GNU/Linux trixie/sid, RStudio 2024.9.1.394

Locale:
  LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
  LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
  LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

Package version:
  base64enc_0.1.3   bslib_0.7.0       cachem_1.1.0      cli_3.6.3         digest_0.6.37    
  evaluate_1.0.0    fastmap_1.2.0     fontawesome_0.5.2 fs_1.6.4          glue_1.7.0       
  graphics_4.4.2    grDevices_4.4.2   highr_0.11        htmltools_0.5.8.1 jquerylib_0.1.4  
  jsonlite_1.8.9    knitr_1.49        lifecycle_1.0.4   memoise_2.0.1     methods_4.4.2    
  mime_0.12         R6_2.5.1          rappdirs_0.3.3    rlang_1.1.4       rmarkdown_2.29.1 
  sass_0.4.9        stats_4.4.2       tinytex_0.53      tools_4.4.2       utils_4.4.2      
  xfun_0.49         yaml_2.3.10      

Pandoc version: 3.5
```

**Comment by cderv** [comment]
For `bash` chunk, this is the engine that is ran by **knitr** if you want to see implementation details.
https://github.com/yihui/knitr/blob/483577596ca9a19d6511f37d2d2e75581d18fd65/R/engine.R#L103-L162

There is some documentation at https://bookdown.org/yihui/rmarkdown-cookbook/eng-bash.html

In summary, it will be 
```
bash -c '<code cell content as one string>'
```

Note that this will run the command at each cell and it won't open a single shell for all cells. So setting `TEST=` in one chunk, and calling it in another won't work. 

> Obviously, I would expect the first chunk not to return anything and the second chunk to print "Hello world!" The second chunk does not print anything, implying that the variable is not cell.

Considering what I explain above, your second cell will not return anything as `$TEST` is not defined when calling `bash -c 'echo $TEST'`

> Note that I had the same issue with previous systems, most recently the stable version of debian.

You had the same "issue" because this is how **knitr** `bash` engine currently works. 

To get a bash session to work on with multiple cell, it would require a new engine, where a process session is open and can be reuse. Maybe using **ps** (https://ps.r-lib.org/) but I am not really sure 🤷‍♂ 

Hope it clarifies the situation you are observing

**Comment by julianbarg** [comment]
Thanks, appreciate the write-up! Couldn't really find anything on how it is supposed to work.

**Comment by cderv** [comment]
> Couldn't really find anything on how it is supposed to work.

Sometimes reading some code is the best way to understand how something is implemented. That is the advantage of open source projects - easy access to internal to really understand how something works :)

**Comment by yihui** [comment]
Just for the record, I wrote an experimental package several years ago to solve this problem: https://github.com/yihui/runr Perhaps I'll revisit it someday.

**Comment by cderv** [comment]
Really cool ! I didn't know that one!
