### ISSUE TITLE
Cannot knit PDF a second time an with cache = TRUE

### ISSUE THREAD

**Issue by Farewe** [rstudio/rmarkdown#262]
Hi,

When I knit the pdf of an R markdown file with cache = TRUE in R code chunks, it works fine the first time. However, it never works a second time, and I receive error messages saying that the images cannot be found:

pandoc.exe: Could not find image './my_folder_files/figure-latex/wcex2.pdf', skipping...
pandoc.exe: Could not find image './my_folder_files/figure-latex/resp4.pdf', skipping...
...

Erreur : pandoc document conversion failed with error 43

As I was looking into my folder /my_folder_files/, I noticed that the first time the pdf is generated, the whole folder ./my_folder_files/figure-latex/ is deleted right after the pdf is generated. I don't understand why. This is probably the cause of the issue.

RStudio version:  0.98.1028
rmarkdown version: 0.3.3
knitr version : 1.6

As an additional note, when I use knit HTML, it works perfectly with cache = TRUE. The issue only happens with knit PDF.

**Comment by yihui** [comment]
This issue has gone (at least in the current version of rmarkdown).
