### ISSUE TITLE
toc + html + child documents

### ISSUE THREAD

**Issue by vbonhomme** [rstudio/rmarkdown#271]
Hi there !

I enjoy rmarkdown. Thanks a bunch for that.

In my quest of making multiformat documents, I (seem to) have found that combining child documents + a nice toc in the html output doestn work properly. All the sections come successively and not as a proper hierarchy. Apparently I have the same problem for MS Word. Do I have to declare the parent document in every child ala knitr/Sweave? It works fine for .pdf though.

All the best !

v

**Comment by yihui** [comment]
I cannot reproduce the issue with the following minimal example:

test.Rmd:

````
---
title: "Hello World"
output:
  html_document:
    toc: true
---

# Section One

```{r child='test2.Rmd'}
```
````

test2.Rmd:

````
# Section Two
````

Output:

![image](https://user-images.githubusercontent.com/163582/29901822-da8a7ed6-8dbf-11e7-8d6c-77c9638cbd18.png)
