### ISSUE TITLE
Handle index.html

### ISSUE THREAD

**Issue by trestletech** [rstudio/rmarkdown#272]
When `run`ning with a NULL `file` and a given directory, we should serve up an `index.html` file if it's available and an `index.Rmd` file is not when a user visits the root path. This matters for Shiny Server, etc.

It turns out that doing this in the current architecture is not feasible without the ability to setup custom routes in Shiny being exported. Returning HTML directly from the UI gets us close, but still has all of the shiny.js/css in the `<head>` and just embeds whatever HTML you return inside of a `<body>`, which is probably not the expected behavior for an `index.html` file.

Might involve changes in Shiny and/or belong in that repo, but marking it here so it's recorded somewhere.

**Comment by yihui** [comment]
Fixed via #306.
