### ISSUE TITLE
small math in Viewer

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/rmarkdown#273]
This is a very small problem..  I have not yet come across a post regarding the issue, but I've noticed variants of it for a while, first with Previews of R Presentations and now with package vignettes.

Here's the issue as it relates to vignettes.  Suppose that:

* you are using the R Studio Windows desktop version
* package X was installed from binary (.zip file)
* a vignette from package X has been written in R Markdown
* you look at the vignette in the Viewer pane

then the LaTeX math is very small.

It seems that all four of the above conditions are required in order to get the small math.

Now that I'm using R Markdown for package vignettes, I wonder if there is some trick I should be employing to keep it from happening.

**Comment by jjallaire** [comment]
Fixed in RStudio.
