### ISSUE TITLE
Output Format-specific `output_file`

### ISSUE THREAD

**Issue by jamiefolson** [rstudio/rmarkdown#277]
I am currently using various knitr options with pandoc to render multiple distinct versions of an output file to different locations.  

To clarify, I have a top-level directory structure like:
- `src`
- `build`
- `data`

I currently place all knitr cache, knitr figures, build markdown and pdf/html output in the `build` directory.  This makes it easier to identify generated artifacts from the source files, as well as keep multiple output (from multiple knit/pandoc calls) files separate.

It would be great if I could transition this process over to `render` using different  `output_format`s and use the Rstudio UI.  However, it seems that both the intermediate and output files are defined inside `render` based on the filename when no `output_file` argument is defined (as happens from the rstudio UI).  This means that I'd need to use a post-processor to move the initial output file to my target location, populating my source directory with ambiguous output.

Maybe `output_format` could return a filename to render so that `output_format`s could choose their `output_file`s?

**Comment by lmmx** [comment]
For anyone else who came across this searching, the hook function can be anonymous, but has to be a one-liner, e.g. a knit function to set the output filename to "README.md":

```YAML
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile),'/README.md')) })
```

Metadata is still used to set the contents of the file as expected.

See also [this related StackOverflow Q&A](http://stackoverflow.com/questions/28500096/r-markdown-variable-output-name)
