### ISSUE TITLE
rmarkdown unable to use data.table's `:=` operator when render is wrapped in a function

### ISSUE THREAD

**Issue by alexdeng** [rstudio/rmarkdown#278]
When trying to put render function inside of another function in a R package, rmarkdown ran into truble with data.table

render the following rmd

``` r
require(data.table)
a=data.table(iris)
a[,k:=1] #problem here!
```

using render4 function,where envir is local of render4 function, hit a weird error on the last line(error is about `:=` can only be applied to data table(check is.data.table(DT)==True)) 

using render3 function, where envir is globalenv(), the rendering was successful. 

Also if run the line of render directly in R interactive, the rendering of course has no issue.

Any thoughts? Is it special to data.table?

---

``` r
#'@import rmarkdown
render3 = function(file){
  render(input = file,output_options=list(self_contained=TRUE),output_file="output.html",envir = globalenv())
  invisible()
}


#'@import rmarkdown
render4 = function(file){
  render(input = file,output_options=list(self_contained=TRUE),output_file="output.html")
  invisible()
}
```

**Comment by yihui** [comment]
I believe this issue should be resolved in the data.table package if it still exists.

**Comment by christiantillich** [comment]
I believe this issue is back again. @alexdeng's solution of including envir = globalenv() still works, and without it, as long as render is wrapped in a function, data.table assignment breaks. I'm running knitr 1.23, data.table 1.12.2, and rmarkdown 1.15
