### ISSUE TITLE
The `render` paths are relative to the input directory

### ISSUE THREAD

**Issue by jamiefolson** [rstudio/rmarkdown#285]
The `intermediates_dir` and `output_dir` directories are relative to the input path, not the working directory.

You can make that work with this:

```r
render("path/to/source/tst.Rmd",
  intermediates_dir = "../../../path/intermediate/",
  output_dir = "../../../path/to/even/deeper/output/",
  clean=FALSE)
```

But that's a bit unusual.

**Comment by jmcphers** [comment]
Arguably the existing behavior wasn't correct, so we've made the recommended change in https://github.com/rstudio/rmarkdown/pull/431. Let us know if it doesn't behave as you'd expect!
