### ISSUE TITLE
Way to specify markdown extensions for beamer_output

### ISSUE THREAD

**Issue by cubranic** [rstudio/rmarkdown#292]
When the output is markdown (i.e., `md_output`), I can specify the flavour using the "variant" option in the header. ([docs](http://rmarkdown.rstudio.com/markdown_document_format.html#markdown-variants))

Unfortunately, this is not the case for `beamer_output`, which fixes the `--from` argument to be the `rmarkdown_format`, with the only option to turn on or off figure captions. Would it be possible to allow some kind of "variant" option for beamer output as well?

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/f891a1f90bdb4ecd2671d5bf53c638090d33539f
