### ISSUE TITLE
Resolution of ioslides on mobile device

### ISSUE THREAD

**Issue by mansunkuo** [rstudio/rmarkdown#298]
Hi, Thanks for providing the incredible tools in R.
Recently I found that the resolution of ioslides presentation on mobile device is not correct.
I've tried chrome/firefox on my android device(HTC One) and both of them does not work.
The Version of my RStudio is 0.98.1083.
Will it be fixed in the future?

**Comment by yihui** [comment]
Probably not. In my experience, several other more modern and better maintained libraries are almost uniformly better than ioslides. Two examples are [revealjs](/rstudio/revealjs) and [xaringan](/yihui/xaringan). You want to give them a try instead. The ioslides format has too many issues and I imagine it will be difficult for us to address them all: https://github.com/rstudio/rmarkdown/issues?utf8=%E2%9C%93&q=is%3Aissue%20ioslides

**Comment by mansunkuo** [comment]
Thank you. I'll try xaringan in my next slides.
