### ISSUE TITLE
captions & subcaptions do not show for multi figure plots

### ISSUE THREAD

**Issue by JWiley** [rstudio/rmarkdown#303]
Below is a reproducible example of what I mean.  The file "styles.tex" simply has "\usepackage{subfig}" to make LaTeX work with figure sub captions.

``````

---
title: "This is my minimal example"
output:
  html_document:
    fig_caption: yes
  pdf_document:
    fig_caption: yes
    includes:
      in_header: styles.tex

---

My working plot.

```{r, results = 'asis', echo=FALSE, fig.width=3, fig.height=3, fig.cap="Figure 1: A smiley face because I work."}
plot(-5:5, (-5:5)^2)
```

My failing plot.

```{r, results = 'asis', echo=FALSE, fig.show='hold', fig.width=3, fig.height=3, fig.cap="Figure 2: I do not work :(", fig.subcap = c("Neither do I", "or me!")}
plot(1:10)
plot(rnorm(10))
```

and here is my system

```{r}
sessionInfo()
```
``````

I render this using:

``` r
library(rmarkdown)
render("captionexample.rmd", "all")
```

and the PDF looks like this:

![image](https://cloud.githubusercontent.com/assets/322716/4910298/cd66e834-647d-11e4-8f3a-13f7e174d53c.png)

**Comment by N0rbert** [comment]
I can't get `fig.subcap` working in `html_document` or `bookdown::html_document2`. 

<pre>
---
output:
  html_document: default
  bookdown::pdf_document2:
    fig_caption: yes
  bookdown::html_document2:
    fig_caption: yes
header-includes:
- \usepackage{subfig}  
---

# TWO PLOTS

```{r, fig.width=4, fig.cap="Graphics test", fig.subcap=c("sin", "cos")}
plot(sin(1:10))
plot(cos(1:10))
```
</pre>
Is it related to current issue? Could you please provide any solution?

```
## R version 3.4.3 (2017-11-30)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 16.04.3 LTS
## 
## Matrix products: default
## BLAS: /usr/lib/openblas-base/libblas.so.3
## LAPACK: /usr/lib/libopenblasp-r0.2.18.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=ru_RU.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] compiler_3.4.3  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
##  [5] tools_3.4.3     htmltools_0.3.6 yaml_2.1.16     Rcpp_0.12.14   
##  [9] stringi_1.1.6   rmarkdown_1.8   highr_0.6       knitr_1.18     
## [13] stringr_1.2.0   digest_0.6.13   evaluate_0.10.1
```

**Comment by yihui** [comment]
@N0rbert It is still LaTeX-only.

**Comment by N0rbert** [comment]
Understood. Then I'll continue to use my solution for HTML:
```

|   |   |
| :---: | :---: |
| ![](sin.png)  | ![](cos.png) |
| *a* | *b* |

![(\#fig:sin-cos) Sinus (a) and cosinus (b)](img/1x1.png)
```

Thank you for your work, anyway!

**Comment by fatima221994** [comment]
hello !
i've the same problem, i can't use fig.cap in my rmarkdown doxument  , i've tried all what did you say inn your documentation ,but always the same problem, can't display name of figure.
thanks for your help
regards


---
title: "Untitled"
author: "title"
date: "19 février 2018"
output:
  html:
    fig_caption: yes
---
```{r pressure, echo=FALSE,fig.cap="pressure plot"}
plot(pressure)
```

**Comment by fatima221994** [comment]
hello !
i've the same problem, i can't use fig.cap in my rmarkdown doxument  , i've tried all what did you say inn your documentation ,but always the same problem, can't display name of figure.

---
title: "This is my  example"
output:
  pdf_document:
    fig_caption: yes
---



```{r cars, echo=FALSE,fig.cap="cars plot"}
plot(cars)
```




thanks for your help
regards

**Comment by grabear** [comment]
@N0rbert  try removing the comma:
```r
# From this:
{r, fig.width=4, fig.cap="Graphics test", fig.subcap=c("sin", "cos")}
# To this:
{r fig.width=4, fig.cap="Graphics test", fig.subcap=c("sin", "cos")}
```
Did that work?  After I resolved my sub-caption issues this way, I came across this by chance.

**Comment by yihui** [comment]
@grabear The comma after `{r` should not matter (**knitr**'s parser will silently remove the extra comma).

**Comment by grabear** [comment]
@yihui I'll try to reproduce this tomorrow then.
