### ISSUE TITLE
rmarkdown, jekyll, git pages

### ISSUE THREAD

**Issue by jangorecki** [rstudio/rmarkdown#304]
I was wondering if anybody (maybe `rmarkdown` team) have already setup a flow of publishing from R to github pages, like: `c("R","Rmd","md","jekyll","html","github pages")`
and could share effective integration setup?

My setup use `knitr::knit` instead of `rmarkdown` package to achieve compatibility with [jekyll](https://github.com/jekyll/jekyll).

What would be useful:
- Documentation for jekyll integration
- Developing better interface for jekyll html renderers and jekyll options, `md_document(variant="markdown_github")` and `md_document(variant="markdown_strict")` was not very useful.
- or switching to direct Rmd->html?  
  Anyone could precisely tell what would be the pros and cons of moving to: `c("R","Rmd","html","jekyll","github pages")`  
  We would avoid `md` to `html` by jekyll so potentially also some it's useful functionality.

My current setup, I assume not as bad, supports syntax highlighting, tags, rss for specific tags: [jangorecki.github.io](http://jangorecki.github.io/)

**Comment by maxheld83** [comment]
+1

**Comment by znmeb** [comment]
I believe https://github.com/ramnathv/poirot was heading in this direction as well.

**Comment by jangorecki** [comment]
Indeed. I believe rmarkdown could be linking to it in the docs. Closing

**Comment by maxheld83** [comment]
I'm curious as to why this issue was closed, since both of the above cited solutions (Poirot and Nikola) are static website generators, but *not* Jekyll – for that, there's only @yihui's great work at https://github.com/yihui/knitr-jekyll.

I, for my part, would still love a feature inside (or well integrated with rmarkdown) to publish via Jekyll.

**Comment by jangorecki** [comment]
@maxheld83, good point. I didn't verify it is not for jekyll.

**Comment by maxheld83** [comment]
thanks @jangorecki – I have to admit I'm also still fuzzy about what a good Rmarkdown -> Jekyll workflow would look like, and whether/which functionality would even belong inside Rmarkdown.
Curious what @yihui's plans for https://github.com/yihui/knitr-jekyll are ...

**Comment by yihui** [comment]
@maxheld83 I do not have more plans for that repo. It is only an example of what you could do with the servr package. You are not restricted to Jekyll.

**Comment by jangorecki** [comment]
Github from the May 2016 will not support Rdiscount or Redcarpe markdown renderers. See [2100-github-pages-now-faster-and-simpler-with-jekyll-3-0](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0).
Additionally jekyll, the main engine of the static site rendering, allows to attach own renderers more easily, see [custom-markdown-processors](https://jekyllrb.com/docs/configuration/#custom-markdown-processors). See the link, maybe it isn't as much work.
It wouldn't be supported on github obviously but still can be useful for rendering static site in much more automatic way for documents produced by R.

**Comment by yihui** [comment]
Please try blogdown: https://github.com/rstudio/blogdown It primarily supports Hugo, but you can use Jekyll and Hexo, too.
