### ISSUE TITLE
one single xtable not rendering  - no idea why

### ISSUE THREAD

**Issue by mlnelson** [rstudio/rmarkdown#307]
I am writing a script that will automatically generate reports for my work.  These reports contain dozens of tables (many are very similar to one another)...all of which work except for one and for the life of me I cant figure out why. I suspect it is a markdown issue because I can take the latex code generated by xtable and copy and paste it into latex and the table renders fine. Also, if I create the table using pandoc.table or kable it also renders fine but these options wont work for the report as I cant get the specific formatting I want. Maybe there is something stupid I missed but any help would be greatly appreciated.

This is what the latex code from the xtable looks like:

``` latex
\begin{table}[ht]
\centering
\begin{tabular}{|c|c|c|c|c|l|}
  \hline
 & station & date & depth & parmcode & comments \\ 
  \hline
1 & D11 & 30 Jul 2014 &  &  & Resample \\ 
  2 & D8 & 30 Jul 2014 &  &  & Resample \\ 
   \hline
\end{tabular}
\end{table}
```

This is the code used to generate and print the xtable that give me the error. The error actually comes from print.xtable :

``` r
comments.ploo.shore <- xtable(comments.list[['PLOO shore']],align = "|c|c|c|c|c|l|")
    print.xtable(comments.ploo.shore, tabular.environment="longtable", floating = F,include.rownames = FALSE, include.colnames = TRUE, sanitize.colnames.function =  bold.allcols)
```

This is the error I am getting:

```
! LaTeX Error: Environment longtable undefined.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                                                                             
l.376 \begin{longtable}
pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
```

A few quick notes:
1. Even though the table is rather short, I am using the longtable environment as the length of this table can vary from month to month
2. in "sanitize.colnames.function =  bold.allcols", the bold.allcols function is a separate function I wrote to change all of the column headers to bold font.  It has worked flawlessly in every other usage so I doubt that this is the source of the problem.

PLease Help!

-Matt

**Comment by xhie** [comment]
hi guys,

I'm facing the same problem with the 'rticles' package. and 

`tables: yes
`
does not work

Sergio

**Comment by DonnaHaga** [comment]
Try adding \usepackage{longtable} to your header file (i.e. the file referenced in the yaml field in_header: header.tex). I was having the same problem but using the tabularx package and this worked.
