### ISSUE TITLE
Shiny Presentation is working fine locally but throws error on Server

### ISSUE THREAD

**Issue by ncdingari** [rstudio/rmarkdown#310]
I have an `index.Rmd` file,`global.R` file and data folder in a folder called `app1`. I am doing all my calculations in `global.R`. When I copied the whole folder to server and Chowned the data folder. The app throws the following error at me.

An error has occurred

The application failed to start.

The application exited during initialization.

`Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'data/mdata.RData', probable reason 'No such file or directory'
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: <Anonymous> ... source -> withVisible -> eval -> eval -> load -> readChar
Execution halted`

**Comment by yihui** [comment]
I think it is impossible for us to figure out the reason for the failure without seeing a minimal reproducible example. It might have something to do with user permission. You said you chowned the folder, but we have no idea what exactly you did.
