### ISSUE TITLE
UTF-8 mathematical operator ∴ (U+2234) not rendered in knitted PDF

### ISSUE THREAD

**Issue by lmmx** [rstudio/rmarkdown#311]
It seems to be valid UTF-8 from the [spec page](http://codepoints.net/U+2234) I found online, though I'm not an expert. 

When I write HTML with knitr in RStudio the ∴ symbol ("therefore") in my notes becomes a crossed-out box, so the encoding's gone wrong somewhere.

I can't see how I could encode unicode differently, and I think it's encoding as UTF-8 by default (from the output dialogue, with `.utf8.md`).

... but then I look at the knitted HTML, and it looks fine, with `meta-charset="UTF-8"` in the HTML. I looked at a [similar issue](https://github.com/rstudio/rmarkdown/issues/205) but that's resolved and when I make a PDF from the example .Rmd code and add in ∴ it's definitely not showing up there either.

Do I need to edit something in the YAML metadata header or is this a bug? The fact it's just the PDF output suggests it might be a bug somewhere to me.

I'm running Linux Mint, up-to-date versions of R/RStudio/knitr etc. There are no warnings being given:

<pre>  |.................................................................| 100%
  ordinary text without R code

/usr/lib/rstudio/bin/pandoc/pandoc Reading_notes.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Reading_notes.pdf --template /home/louis/R/x86_64-pc-linux-gnu-library/3.1/rmarkdown/rmd/latex/default.tex --highlight-style tango --latex-engine xelatex --variable 'geometry:margin=1in' 

processing file: Reading_notes.Rmd
output file: Reading_notes.knit.md

Output created: Reading_notes.pdf
</pre>

**Comment by yihui** [comment]
Here is a minimal working example:

````
---
title: "Hello World"
output:
  pdf_document:
    includes:
      in_header: preamble.tex
---

The ∴ symbol.
````

where preamble.tex contains

```tex
\usepackage{amssymb}
\DeclareUnicodeCharacter{2234}{$\therefore$}
```

This is more like a LaTeX issue instead of R Markdown issue (cf https://tex.stackexchange.com/q/342494/9128), so I'm closing it.
