### ISSUE TITLE
Any Idea How to Fix This in the pandoc_args, Can't Seem to Get It Fixed

### ISSUE THREAD

**Issue by abresler** [rstudio/rmarkdown#315]
Stack space overflow: current size 33632 bytes.
Use `+RTS -Ksize -RTS' to increase it.
Error: pandoc document conversion failed with error 2
Execution halted

Tried pandoc_args: [ +RTS, -Ksize, -RTS ] and had no luck getting it fixed.  I assume I have to enter numbers some where just not clear where

**Comment by dash00** [comment]
Same problem, cannot fix it using the proposed parameters .. I tried 
"+RTS", "-K64m", "-RTS"
and
"+RTS", "-Ksize", "-RTS"

**Comment by jjallaire** [comment]
The development (GitHub) version of rmarkdown already does this by default
so I'd just use that for the time being.
