### ISSUE TITLE
auto-complete in citing

### ISSUE THREAD

**Issue by laoyang945** [rstudio/rmarkdown#317]
Hi there, is it possible to pop up a "key/id" list from the designated reference file when I press tab after an @? The current workflow needs many copy-paste operations.
thanks a lot!

**Comment by yihui** [comment]
This is an RStudio IDE issue, and you may file the feature request to support.rstudio.com instead.

You may also check out the citr package mentioned in the bookdown book: https://bookdown.org/yihui/bookdown/rstudio-ide.html
