### ISSUE TITLE
Multi-plots with different size via fig.width knitr chunk option

### ISSUE THREAD

**Issue by koseokbum** [rstudio/rmarkdown#321]
For multi-plots with different width in a code chunk, If I set the fig.width option with a numeric vector  with `Keep markdown source file` unchecked in 'Edit R Markdown Document options' window, it works. 

However, if I set html_document settings  in `_output.yaml` with the same options as above, it does not work and I've got the plots with the same widths. Is there any problem?

**Comment by yihui** [comment]
I cannot reproduce this issue with the latest version of rmarkdown.

_output.yaml

```yaml
html_document:
  fig_width: [7, 4]
```

test.Rmd

````
---
title: "Hello World"
output: html_document
---

```{r}
plot(iris[, 1:2])
plot(cars)
```
````

Anyway, I think setting `fig.width` to a vector globally is probably a bad idea. You are assuming that every chunk produces the same number of plots.
