### ISSUE TITLE
Silly feature request

### ISSUE THREAD

**Issue by cscheid** [rstudio/rmarkdown#322]
It would be phenomenally cool if the PDF output of RMarkdown included, as metadata, the source code that was used to generate it. This occurred to me because I'm submitting an RMarkdown PDF as supplemental material, _and_ the .Rmd file to recreate it. Feels like it shouldn't be necessary.

**Comment by rbq** [comment]
Usually to make it reproducible not only the file itself but also any data processed by it would be required. IMO embedding the Markdown source automatically would make people think less about what actually belongs into the package.

I also believe that software should behave in the way people expect, which usually doesn't include leaking random information. In the science community the principle of sharing might be ubiquitous, but the toolchain is equally useful to generate business stuff like reports for external clients. You usually don't want to accidentally share your source code with them, potentially including stuff like casual comments, business secrets and access data for web services and databases.

**Comment by maxheld83** [comment]
nice idea – but let's not waste any more time than necessary with PDF.
We shall *overcome* it, not *improve* it :).

If people only started to read rmarkdown-made HTML, with always a link to the source ready ...
