### ISSUE TITLE
Impress.js/Jmpress-based presentations

### ISSUE THREAD

**Issue by kmader** [rstudio/rmarkdown#324]
The impress.js presentations which are very strongly based on ideas that Prezi popularized are a very convenient format for more dynamic presentations and make "digging down" natural. It would be really nice to have support / a template in rmarkdown to make this format. A simple shiny app generating impress.js code is here: https://4quant.shinyapps.io/gimpress/

**Comment by yihui** [comment]
@kmader Given the age of this issue, I assume nobody really has interest in supporting impress.js in rmarkdown, so I'll just leave it to the broader R community to do it. The only relevant R package I could find was https://github.com/ramnathv/slidify, but apparently its development has stopped for a couple of years.

@sje30 I don't know why I didn't notice this earlier, but you know I have written the xaringan package as an interface to remark.js: https://github.com/yihui/xaringan
