### ISSUE TITLE
Inline HTML not passed through

### ISSUE THREAD

**Issue by wch** [rstudio/rmarkdown#326]
When raw HTML is added to a Rmd document, any tags that are indented four or more spaces get treated as code instead of raw HTML. @hadley and @jmcphers pointed me to some workarounds, shown below:

``````

---
title: "Untitled"

---

Doesn't work:

<div>
    <div>block 1
    </div>
</div>

*****

Works:

```{r echo=FALSE}
knitr::asis_output(htmltools::htmlPreserve("
<div>
    <div>block 2
    </div>
</div>
"))
```

*****

Works:

<!--html_preserve-->
<div>
    <div>block 3
    </div>
</div>
<!--/html_preserve-->
``````

I suspect this is actually a bug in Pandoc. I'm using 1.13.1 with RStudio 0.99.97.

**Comment by xvrl** [comment]
@hadley I'm running into this issue as well. Is there a way to tell rmarkdown to use the `markdown_strict` variant when producing html output? That would also be a workaround.

**Comment by jjallaire** [comment]
You can now use the `md_extensions` parameter to remove the "markdown in html" behavior on a per-document basis.

**Comment by yihui** [comment]
The example on the rmarkdown website seems to have been fixed. There isn't much we can do on rmarkdown's side. For this issue, we are at the mercy of Pandoc...
