### ISSUE TITLE
Changing font size in ioslides 

### ISSUE THREAD

**Issue by sje30** [rstudio/rmarkdown#327]
Is there anyway in markdown to change the font size for a chunk of text?  Or is that all done with CSS wizardry?

I'm used in beamer to being able to do stuff like

Title {\scriptsize reference} Title

to temporarily reduce font size.

**Comment by yihui** [comment]
I think you have to use CSS. LaTeX commands certainly won't work for HTML output.

With xaringan/remark.js, it is slightly easier, e.g. you may use the syntax `.foo[text]` and define CSS for the class `.foo`. For ioslides, you have to use raw HTML like `<span style="font-size: 9px;">text</span>`.
