### ISSUE TITLE
.img-responsive in Bootstrap 3

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#332]
Sorry if this is premature. I made some scripts for automatically turning knit markdown sections into collapsibles and tabs and needed BS3, so I just installed the master branch.
Images are no longer automatically responsive (scaling width and height) in BS3, the class needs to be `.img-responsive` (or the default styles need to be modified).
I think this was a pretty good default for rmarkdown though.

**Comment by wch** [comment]
This can be closed; it was fixed by #333.
