### ISSUE TITLE
Cannot create table, please help

### ISSUE THREAD

**Issue by billchenxi** [rstudio/rmarkdown#334]
Please help me on this issue! Should I install some package? 
I followed the syntax listed in the instruction, and it down's work. 
I type like this:

```
Table Header  | Second Header
------------- | -------------
Table Cell    | Cell 2
Cell 3        | Cell 4
```

And it comes out like this: 
![screenshot at dec 17 22-05-35](https://cloud.githubusercontent.com/assets/986935/5483038/7a30cfbc-8639-11e4-9922-2cd630d3682e.png)

**Comment by yihui** [comment]
I think you can just change `html_document` to `pdf_document`. For more info, please see http://rmarkdown.rstudio.com
