### ISSUE TITLE
Is anyone working on tufte book or tufte handout?

### ISSUE THREAD

**Issue by elbamos** [rstudio/rmarkdown#340]
I was asking around the rstudio discussion area, and they suggested I bring the topic here.  

The tufte-handout template is a partial implementation of the tufte-handout latex class, which in turn is a subset of the tufte-book latex class.

Some issues with the handout template at the moment include:  margin tables don't work; floats overlap each other; margin elements won't stay with text; no TOC's; and so on.  Beyond that, tufte book supports things like TOCs, multiple layers of subheadings, multi-column pages, etc. etc.  

I thought about just trying to fix the existing template, but the fact that things like margin tables are partially implemented suggests to me that converting the latex class to rmarkdown is non-trivial.  

Has anyone gotten into modifying these things?  Is anyone interested in working on it with me? Thanks.

**Comment by elbamos** [comment]
I guess that's true in academia, and probably some other places, but in business especially many of us like to *email* memos and reports to people, and that means either Word or, better, PDF.

**Comment by 1beb** [comment]
I believe there's a template for Tufte Book in the rticles package: 

https://github.com/rstudio/rticles/tree/master/inst/rmarkdown/templates/tufte_ebook

**Comment by elbamos** [comment]
Yes, it was my contribution. Try it, I think it's pretty good :)
