### ISSUE TITLE
Something deletes cached images

### ISSUE THREAD

**Issue by gonulate** [rstudio/rmarkdown#341]
I run the following very basic RMD file:

    ---
    output: html_document
    ---

    ```{r, cache=TRUE}
    a <- 2
    ```

    ```{r, echo=FALSE, cache=TRUE}
    plot(rnorm(1e5), rnorm(1e5))
    ```

When I run this first time it runs perfectly. But second time it tries to locate the cached images and it fails. Because something deletes them. After pressing the "knit HTML" in Rstudio, I watch the folder contents in another window, The folder "trial1_files" created and mysteriously deleted just after the html file produced (when I run it first time). Later, when I knit it again, it gives an error because it cannot locate the deleted folder. The "trial1_cache" folder is there intact. 

This is weird. The cache functionality run without error in Latex documents. 

I asked the same question in knitr forum. Yihui Xie offered following solution (updating the package), but it did not work. 
```
update.packages(ask = FALSE) 
devtools::install_github('rstudio/rmarkdown') 
```

RStudio version: 0.98.1091
rmarkdown version: 0.4.2
knitr version : 1.8

Here is the error:
```
  |................                                                 |  25%
  ordinary text without R code


  |................................                                 |  50%
label: unnamed-chunk-1 (with options) 
List of 1
 $ cache: logi TRUE


  |.................................................                |  75%
  ordinary text without R code


  |.................................................................| 100%
label: unnamed-chunk-2 (with options) 
List of 2
 $ echo :


processing file: trial1.Rmd
 logi FALSE
 $ cache: logi TRUE




"C:/Program Files/RStudio/bin/pandoc/pandoc" trial1.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output trial1.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Dropbox\UNCATE~1\R\RLIBRA~1\RMARKD~1\rmd\h\DEFAUL~1.HTM" --variable "theme:bootstrap" --include-in-header "C:\Users\XXXXX\AppData\Local\Temp\RtmpumonNt\rmarkdown-str1b5c41b02092.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=C:\Dropbox\UNCATE~1\R\RLIBRA~1\RMARKD~1\rmd\h\HIGHLI~1" 
output file: trial1.knit.md


pandoc.exe: Could not find data file trial1_files/figure-html/unnamed-chunk-2-1.png
Error: pandoc document conversion failed with error 97
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" trial1.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output trial1.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Dropbox\UNCATE~1\R\RLIBRA~1\RMARKD~1\rmd\h\DEFAUL~1.HTM" --variable "theme:bootstrap" --include-in-header "C:\Users\XXXXX\AppData\Local\Temp\RtmpumonNt\rmarkdown-str1b5c41b02092.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=C:\Dropbox\UNCATE~1\R\RLIBRA~1\RMARKD~1\rmd\h\HIGHLI~1"' had status 97 
Execution halted
```

**Comment by yihui** [comment]
Do you really have the preceding `#`'s in your example? If not, could you please make it a valid Rmd file?

**Comment by gonulate** [comment]
No, I just did it here because both github and rmarkdown use ``` for codes. I couldn't find a way to handle code in github.  In my original files there are no #'s.

**Comment by yihui** [comment]
Then just indent the whole thing by four spaces. I have updated your original post.

**Comment by jjallaire** [comment]
The issue here is that for self-contained HTML documents the _files directory is removed after rendering. This is however NOT done if the global cache option is set like this:

```r
knitr::opts_chunk$set(cache=TRUE)
```

So there are two workarounds possible here:

1. Set the cache option globally; or

2. Add the self_contained: false option to the output format YAML

@yihui Can you think of a better way here? (e.g. is there an easy way to detect whether any individual chunks used the cache as opposed to the whole document)

**Comment by gonulate** [comment]
Thanks for the solution. Changing the RMD file to the following worked:
```
    ---
    output: 
      html_document:
        self_contained: false
    ---

    ```{r}
    a <- 2
    ```
    
    ```{r, cache=TRUE}
    plot(rnorm(1e5), rnorm(1e5))
    ```
```

**Comment by yihui** [comment]
@jjallaire I do not have a general solution for that. If the user does not set `cache.path`, we can just check if the dir `cache_dir` exists after rendering; if it does, we probably should not clean up `intermediates`.

**Comment by jjallaire** [comment]
It looks like this was actually a windows-only bug. @yihui here is a pull request with the fix (could you review and merge): https://github.com/rstudio/rmarkdown/pull/342

**Comment by yihui** [comment]
@gonulate Please `devtools::install_github('rstudio/rmarkdown')` and see if you still have the problem (I verified it on Windows and the problem has gone).

**Comment by gonulate** [comment]
After updating to the new version in Github, I run the RMD file without ```self_contained: false``` and it worked. Thanks.
