### ISSUE TITLE
code block breaks nested lists

### ISSUE THREAD

**Issue by jpmorris** [rstudio/rmarkdown#343]
1. test
        + test2
            + test3
    ```{r}
    a <- 1
    ```
                + test3a
                + test3b
            + test4
        + test5
            + test6
            + test7
        + test8
    2. test9

**Comment by yihui** [comment]
Indent the code block to the same level as the list items, e.g.

    1. test
        + test2
            + test3
                ```{r}
                a <- 1
                ```
                + test3a
                + test3b
            + test4
        + test5
            + test6
            + test7
        + test8
    2. test9
