### ISSUE TITLE
sh: 1: /home/travis/opt/pandoc/pandoc: not found

### ISSUE THREAD

**Issue by audy** [rstudio/rmarkdown#346]
Rmarkdown is trying to find pandoc instead of just using `$PATH`.

the [`find_pandoc`](https://github.com/rstudio/rmarkdown/blob/d4947c70cbbc7a588a18a71dfcbcabef0dba1412/R/pandoc.R#L487) function is supposed to find the Pandoc _executable_, which it does, using `Sys.which`.

Once found, `find_pandoc` tries to find pandoc's version [here](https://github.com/rstudio/rmarkdown/blob/d4947c70cbbc7a588a18a71dfcbcabef0dba1412/R/pandoc.R#L501) using the function [`get_pandoc_version`](https://github.com/rstudio/rmarkdown/blob/d4947c70cbbc7a588a18a71dfcbcabef0dba1412/R/pandoc.R#L527) which takes the location of the pandoc **binary** as first argument, but treats it as if it is the pandoc installation directory. It joins `pandoc` to the path of the binary (resulting in `pandoc/pandoc`) then tries to execute it crashing the program because the file does not exist.

I have a [`.travis.yml`](https://github.com/audy/make-rmarkdown/blob/5cb1d097b6c300fd436e3adc41ed256e62ee6f3c/.travis.yml) that reproduces this error.

Is there a way to override this or just use `$PATH`?

**Comment by yihui** [comment]
To me, this looks more like a issue of @craigcitro's travis-tool.sh than an rmarkdown issue.

I do not use this travis script myself, and I just install pandoc from the marutter PPA:

    sudo apt-get install pandoc pandoc-citeproc

The version of Pandoc in his PPA is a little dated. If you really care about the latest version, here is another of my personal recipe: https://github.com/yihui/crandalf/blob/master/inst/scripts/install-pandoc

**Comment by craigcitro** [comment]
`travis-tool.sh` puts it where @jjallaire recommended, see the [r-travis issue](https://github.com/craigcitro/r-travis/issues/136) for more detail. my understanding was that the path in question was one that RMarkdown always checked?

in any event, it sounds like the issue @audy mentions (of conflating the file path with a directory) is probably worth fixing?

**Comment by yihui** [comment]
@craigcitro I guess there was a misunderstanding: when JJ said `${HOME}/opt/pandoc`, I believe he meant `${HOME}/opt/pandoc/`, i.e. the executables `pandoc` and `pandoc-citeproc` are under `${HOME}/opt/pandoc/`, but not that `${HOME}/opt/pandoc` is the executable.

BTW, it seems you installed pandoc to `${HOME}/opt/`, and also symlinked to `/usr/local/bin`, and the latter step is unnecessary. You can either install to `${HOME}/opt/pandoc/`, or just copy the executables to `/usr/local/bin`.

**Comment by znmeb** [comment]
I had a number of problems with RStudio using the version of Pandoc that it carries. I ended up "hiding" that directory by renaming "rstudio/bin/pandoc" to "rstudio/bin/pandoc.bak" and installing the Fedora pandoc packages. I think RStudio needs an environment variable about where to look for pandoc.

**Comment by yihui** [comment]
@znmeb You do not need to hide RStudio's built-in pandoc, if you have installed a version of pandoc that is >= RStudio's pandoc version and it is on your `PATH`. Then RStudio will just pick your version; if not, it should be an rmarkdown bug.

**Comment by znmeb** [comment]
> @znmeb You do not need to hide RStudio's built-in pandoc, if you have installed a version of pandoc that is >= RStudio's pandoc version and it is on your PATH. Then RStudio will just pick your version; if not, it should be an rmarkdown bug.

That's what I thought - I'll have to try to reproduce it now. Is it RMarkdown or RStudio 'knit' button that makes the choice?

**Comment by znmeb** [comment]
Ah - yours is slightly newer than Fedora's:

RStudio pandoc:
$ /usr/local/lib/rstudio/bin/pandoc/pandoc --version
pandoc 1.12.4.2
Compiled with texmath 0.6.6.3, highlighting-kate 0.5.8.4.

Fedora 21 pandoc:
$ pandoc --version
pandoc 1.12.3.3
Compiled with texmath 0.6.6.1, highlighting-kate 0.5.6.

Both work now with RStudio Desktop built from source.

**Comment by jjallaire** [comment]
@craigcitro, I think @yihui provided the right clarification here (`/opt/pandoc` is actually a directory that contains `/opt/pandoc/pandoc` and `/opt/pandoc/pandoc-citeproc` within in)

**Comment by audy** [comment]
@yihui this fixes my issue as does your method of installing Pandoc. Thanks. Close?

**Comment by yihui** [comment]
@audy Sure.

**Comment by craigcitro** [comment]
@yihui @jjallaire thanks! fixing right now, so r-travis will start putting pandoc where RMarkdown expects. `;)`

@yihui on the `/usr/local/bin` thing -- actually, i still need that. the issue is that it's impossible for a shell script (here `travis-tool.sh`) to set an env var in the *calling* environment, and users who install pandoc might want to add a line to `.travis.yml` that just calls `pandoc` directly. in that case, they either need to know where i stuck it on the path, or i have to add it somewhere already on the path.

**Comment by yihui** [comment]
@craigcitro I see. Then you can just install the pandoc executables directly to `/usr/local/bin`. There is no no need to add them to `~/opt/pandoc/` first.

**Comment by craigcitro** [comment]
@yihui i'd originally done it that way, but there were two reasons to switch back:

1. JJ mentioned that RMarkdown finding it in the "usual" spot was probably good
2. travis's container move requires no `sudo`, but i'm in the process of moving the code into travis itself -- so i can fiddle with the path directly. in that case, i'll be able to keep `pandoc` on the path in the location that `RMarkdown` is looking, and all is well.

**Comment by yihui** [comment]
@craigcitro Thanks for the explanation. I'm not sure if `~/opt/pandoc/` is "usual" or not, and I do not remember if it was JJ or Hadley or someone else who invented it. The path name is a little odd in my eyes. On Ubuntu, `~/bin` is normally automatically added to PATH (see `~/.profile`), and that is where I put my personal scripts without requiring sudo. Perhaps you can set PATH=$PATH:$HOME/bin and download Pandoc to ~/bin, if ~/bin is not in Travis's PATH? Then this solves both problems: pandoc will be on PATH, and it does not require sudo.
