### ISSUE TITLE
Knit pdf problem

### ISSUE THREAD

**Issue by nishantsbi** [rstudio/rmarkdown#349]
Knit pdf and got the error:

This is pdfTeX, Version 3.1415926-2.5-1.40.14 (MiKTeX 2.9)
pdflatex: The memory dump file could not be found.
pdflatex: Data: pdflatex.fmt

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/Users/nishant/AppData/Local/Pandoc/pandoc" Foundation_of_Data_Analysis_edX_Labs.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Foundation_of_Data_Analysis_edX_Labs.pdf --template "C:\Users\nishant\Documents\R\win-library\3.1\rmarkdown\rmd\latex\default.tex" --highlight-style tango --latex-engine pdflatex --variable "geometry:margin=1in"' had status 43 
Execution halted

it tried various options such as updating rmarkdown by

devtools::install_github("rstudio/rmarkdown")

still the problem remains...please suggest

My session info:

sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
locale:
[1] LC_COLLATE=English_India.1252 LC_CTYPE=English_India.1252

[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C

[5] LC_TIME=English_India.1252

attached base packages:
[1] stats graphics grDevices utils datasets methods base

other attached packages:
[1] SDSFoundations_1.1 gmodels_2.15.4.1

loaded via a namespace (and not attached):
[1] digest_0.6.8 gdata_2.13.3 gtools_3.4.1 htmltools_0.2.6 MASS_7.3-35

[6] rmarkdown_0.4.2 tools_3.1.2 yaml_2.1.13

**Comment by yihui** [comment]
Looks like a Windows permission issue. A few Google search results:

- http://tex.stackexchange.com/questions/81739/the-memory-dump-file-could-not-be-found
- http://tex.stackexchange.com/questions/114248/error-when-compiling-pdflatex
