### ISSUE TITLE
Unable to add math expression to shiny interactive document

### ISSUE THREAD

**Issue by mielniczuk** [rstudio/rmarkdown#350]
The only way to display the math in the following is to remove the runtime: shiny metadata

    ---
    title: "ShinyTest"
    author: "ASM"
    date: "Friday, January 09, 2015"
    output: html_document
    runtime: shiny
    ---

    ## Math, Footnote, and Table Check

    You can write math expressions, such as $Y = X\beta + \epsilon$ , footnotes^[A footnote here.], and tables, e.g. using `knitr::kable()`.

    ```{r, echo=FALSE, results='asis'}
    knitr::kable(head(mtcars, 10))
    ```

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.10.2.2

loaded via a namespace (and not attached):
 [1] digest_0.6.8    evaluate_0.5.5  formatR_1.0     htmltools_0.2.6 httpuv_1.3.2    knitr_1.8      
 [7] mime_0.2        R6_2.0.1        Rcpp_0.11.3     RJSONIO_1.3-0   rmarkdown_0.4.2 stringr_0.6.2  
[13] tools_3.1.2     xtable_1.7-4    yaml_2.1.13

**Comment by jjallaire** [comment]
Thanks, we'll investigate. FYI I could reproduce the problem on OSX but I see you are on Windows. There must be some type of windows path-handling problem, hopefully easy to resolve.

**Comment by jjallaire** [comment]
@jmcphers I've confirmed that this is a problem on Windows (but not OSX). Here's the errors I see in the console for this page:

![screen shot 2015-01-10 at 3 02 38 pm](https://cloud.githubusercontent.com/assets/104391/5693028/da126366-98d9-11e4-8b46-646c851de942.png)

That's in Qt 5.4. Here's what I get in Chrome:

![screen shot 2015-01-10 at 3 04 39 pm](https://cloud.githubusercontent.com/assets/104391/5693034/1d423bf2-98da-11e4-9ced-99180eeaeea4.png)

I don't understand the ins and outs of how we load resources for runtime: shiny but it looks like this affects both highlighting and mathjax.

I think we should take a look at this for the preview (as we're getting very close to a CRAN submission for rmarkdown and it would be nice to have this fix getting tested as part of the preview).

**Comment by jmcphers** [comment]
Thanks @jjallaire, I'll take a look at this.

**Comment by yihui** [comment]
Actually I have also got problems with MathJax in the RStudio preview version (0.99.167) even if it is a non-shiny document:

![screenshot from 2015-01-12 21 48 10](https://cloud.githubusercontent.com/assets/163582/5715774/ce58b5da-9aa4-11e4-8dfc-fc289536d033.png)

The error is there regardless of `self_contained` being yes or no. The math content can be rendered correctly when I open the HTML page in Chrome or RStudio Viewer.  It just fails in the preview window popped up after clicking the Knit HTML button.

**Comment by jmcphers** [comment]
Should be resolved on master now (@mielniczuk, let us know if you still see this with the latest bits).
