### ISSUE TITLE
document error=TRUE options override in render()?

### ISSUE THREAD

**Issue by bbolker** [rstudio/rmarkdown#351]
I spent a while today figuring out that `render` by default overrides `knitr`'s default value of `error=TRUE` (i.e., `render` stops on error by default, `knitr` continues by default). I don't mind that too much -- arguably it's enforcing better practice, and one can just add `error=TRUE` to any particular chunk (I *think* that putting `knitr::opts_chunk$set(error=TRUE)` at the head of the document did *not* work, but I might not have tested it carefully enough).  However, it would be nice to document. (If you like I can fork/make a suggestion/submit a pull request.)

**Comment by jjallaire** [comment]
We document it here in the R Markdown v1 migration guide: http://rmarkdown.rstudio.com/authoring_migrating_from_v1.html

**Comment by bbolker** [comment]
Thanks for the quick response -- that was actually the third Google hit for me on "render knitr error options", but I mistakenly skipped over it since I didn't see `error=...` in the Google search thumbnail  (oops) ...  Would it be reasonable to add a short note to `?render`  ... ?

**Comment by jjallaire** [comment]
Just committed the updated docs: https://github.com/rstudio/rmarkdown/commit/374395fc09db9faedf8a13a317e9bd330751d541
