### ISSUE TITLE
Support 'compress' option 

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/rmarkdown#352]
My beamer documents use a theme you support, but with style option you do not:

```
\documentclass[12pt,compress]{beamer}
```

I may have overlooked something and you already do--but I like the 'compress' very much as it results in a tighter page title.

**Comment by jjallaire** [comment]
This definitely could stand better documentation! You can do what you are looking for via the `classoption` field:

    ---
    title: "Untitled"
    output: 
       beamer_presentation:
          keep_tex: true
    fontsize: 12pt
    classoption:
       - compress
    ---

You can add an arbitrary list of `classoption` values. I added the `keep_tex` bit so you can see exactly what tex pandoc is generating.

**Comment by eddelbuettel** [comment]
Doh.

Thanks for the cluebat.
