### ISSUE TITLE
I can not get sigma with ioslides_presentation but I can with slidy_presentation. I can always get mu

### ISSUE THREAD

**Issue by jjpcaste** [rstudio/rmarkdown#357]
It crash when I knit this scrIpt

---
title: "Bug example"
author: "jjpc"
date: ""
output: ioslides_presentation
---

## I can NO get sigma with these script

&sigma;>10

END OF SCRIPT

But it works well when I knit all the following ones

---
title: "Example 1 OK"
author: "jjpc"
date: ""
output: slidy_presentation
---

## I can get sigma with these script

&sigma;>10 

END OF SCRIPT

---
title: "Example 2 OK"
author: "jjpc"
date: ""
output: ioslides_presentation
---

## I can get mu with these script

&mu;>10   

END OF SCRIPT

---
title: "Example 3 OK"
author: "jjpc"
date: ''
output: slidy_presentation
---
## I can get mu with these script

&mu;>10  

END OF SCRIPT

Aditional information:

> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.4    htmltools_0.2.6 rmarkdown_0.3.3 tools_3.1.1     yaml_2.1.13    

> Bug report when knitting Bug example script

processing file: debug_script2.Rmd
output file: debug_script2.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" debug_script2.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output debug_script2.html --smart --email-obfuscation none --self-contained --variable transition=0.4 --template "C:\Users\usuario\Documents\R\win-library\3.1\rmarkdown\rmd\ioslides\default.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --variable ioslides-url=debug_script2_files/ioslides-13.5.1 
"C:/Program Files/RStudio/bin/pandoc/pandoc" debug_script2.utf8.md --to ioslides_presentation.lua --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output "C:\Users\usuario\AppData\Local\Temp\RtmpWMd6pW\ioslides-output7906ca97351.html" 
pandoc.exe: Cannot decode byte '\xcf': Data.Text.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1
Ademas: Mensajes de aviso perdidos
comando ejecutado '"C:/Program Files/RStudio/bin/pandoc/pandoc" debug_script2.utf8.md --to ioslides_presentation.lua --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output "C:\Users\usuario\AppData\Local\Temp\RtmpWMd6pW\ioslides-output7906ca97351.html"' tiene estatus 1 
Ejecucion interrumpida

**Comment by jjallaire** [comment]
@yihui Does this look like other encoding issues we've seen with ioslides in the past?

**Comment by jjpcaste** [comment]
Hi. I agree with you. But some tip for fixing the problem? Thanks in advance

**Comment by yihui** [comment]
We have received several reports like this problem with ioslides: #134, #242, #281, #288

Perhaps our Lua script is the culprit. I do not know. Pandoc's built-in presentation formats do not seem to have such problems, e.g. Slidy as reported above.

**Comment by jjpcaste** [comment]
Hi. I have just checked reports @yihui mentioned. Yes, #134 is the same problem than mine. In my ioslides scripts, problems dissapear just when I delete '&sigma;' from code. The problem is not present in slidy scripts. It is important to note that '&mu;' causes no problems with slidy nor with ioslides.

**Comment by jjallaire** [comment]
Okay, we will need to dig into how/why UTF-8 characters aren't working with
ioslides (@yihui 's speculation about where the problem lies is I think
correct however I'm not sure how to fix it)

**Comment by yihui** [comment]
The latest dev version might have fixed this issue. It will be nice if you can test it: `devtools::install_github('rstudio/rmarkdown')`

**Comment by jjpcaste** [comment]
Hi. I have tested. It seems it works perfectly now. I will report later if I find some problem. By now it works excellent. Thanks.
