### ISSUE TITLE
Extending knitr_options to define some global options

### ISSUE THREAD

**Issue by larmarange** [rstudio/rmarkdown#358]
I'm trying to develop some custom output format. 

For this specific output, I need to set some global options through `base:options()` in the knitr environment, like:

``` r
options(
  knitr.table.format = "html", # Tables in HTML (kable)
  xtable.type = "html", # Tables in HTML (xtable)
  xtable.caption.placement = "top" # Caption on top of the table (xtable)
)
```

So far, I have to put these options within a chunk inside the Rmarkdown file. However, as these options are specific to my custom format, it would be better to define them in `output_format`.  (as these options should not be applied when I'm rendering my document with another format).

An easy way would be to extend `knitr_options()` with an additional argument allowing to set global R options.

Best regards

**Comment by jjallaire** [comment]
Since your custom output format can execute R code I think you can set
these options there. You can provide a pre_processor and post_processor
function in the output_format that can set/unset these options.

**Comment by larmarange** [comment]
Thanks. I will explore that possibility.
