### ISSUE TITLE
Ability to set cairo_pdf as a default graphic device for pdf output

### ISSUE THREAD

**Issue by zozlak** [rstudio/rmarkdown#361]
pdf_cairo() has one big advantage over pdf() for non-english users - it supports national characters on Windows out of the box.

Obviously I can change default graphic device in the first chunk of my markdown document:
```r
if(identical(opts_knit$get('rmarkdown.pandoc.to'), 'latex')){
  if(identical(capabilities()['cairo'], c('cairo' = TRUE))){
    opts_chunk$set('dev' = 'cairo_pdf')
  }
}
```
but an important reason you use rmarkdown is you do not have to take care of such things.

So maybe it will be worth to include an option to switch to pdf_cairo(), e.g. as an 
```
output: 
  pdf_document: 
    dev: [pdf/cairo_pdf]
```
option of the YAML section of a markdown document (and move the code above to the `rmarkdown::render()`).

By the way - it would be nice to be able to choose between PNG and SVG graphics in the HTML output in the same way.

**Comment by jjallaire** [comment]
Fixed via: https://github.com/rstudio/rmarkdown/commit/d66a5e6c1b5a98774d499bf6162c1be98b4388b4
