### ISSUE TITLE
PDF compile error: unused argument (pdf = list(useDingbats = FALSE))

### ISSUE THREAD

**Issue by jdiggans** [rstudio/rmarkdown#363]
When trying to use a PNG graphics device with pdf_document output formats, I get an error.

MWE:

    ---
    title: "test"
    date: "Wednesday, January 28, 2015"
    output:
      pdf_document:
       dev: png
       keep_tex: yes
    ---
    
    ```{r, echo=FALSE}
    plot(cars)
    ```

If I try 
> dev: png

then I get an error upon clicking 'Knit PDF':

>processing file: test.rmd
>Quitting from lines 11-12 (test.rmd) 
>Error in (function (filename = "Rplot%03d.png", width = 480, height = 480,  : 
>  unused argument (pdf = list(useDingbats = FALSE))
>Calls: <Anonymous> ... block_exec -> chunk_device -> dev_new -> do.call -> <Anonymous>
>Execution halted

and if I instead use

>dev: cairo_pdf

or

>dev: jpeg

then things work just fine.

**Comment by jjallaire** [comment]
Should be fixed on master via https://github.com/rstudio/rmarkdown/commit/e3fd06f0712a409cf2a66220a015e24a0b8a7223 (let us know if it's not)
