### ISSUE TITLE
pandoc document conversion failed with error 43

### ISSUE THREAD

**Issue by StepanSushko** [rstudio/rmarkdown#364]
I saw that this error already discussed. I tried to install devtools::install_github('rstudio/rmarkdown') . But it doesn't work for me. I updated R (Version 0.98.1091) and MikTex (x64). Besdies I have win 8.1 x64. I still can't knit minimal TeX example:

```
---
output: pdf_document
---
\documentclass[article]
\begin{document}

This is an R Markdown document.

\end{document}
```

Log:
"C:/Program Files/RStudio/bin/pandoc/pandoc" Preview-147c60ce730c.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Preview-147c60ce730c.pdf --template "C:\PROGRA~1\R\R-31~1.2\library\RMARKD~1\rmd\latex\default.tex" --highlight-style tango --latex-engine pdflatex --variable "geometry:margin=1in" 

processing file: Preview-147c60ce730c.Rmd
output file: Preview-147c60ce730c.knit.md

! LaTeX Error: Can be used only in preamble.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.74 \begin{document}

pandoc.exe: Error producing PDF from TeX source
������: pandoc document conversion failed with error 43
��������: ��������������
���������� ������� '"C:/Program Files/RStudio/bin/pandoc/pandoc" Preview-147c60ce730c.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Preview-147c60ce730c.pdf --template "C:\PROGRA~1\R\R-31~1.2\library\RMARKD~1\rmd\latex\default.tex" --highlight-style tango --latex-engine pdflatex --variable "geometry:margin=1in"' ����� ������ 43 
���������� �����������

**Comment by yihui** [comment]
I do not understand why you added

```
\documentclass[article]
\begin{document}
```

and

```
\end{document}
```

to a Markdown document. Markdown is not LaTeX, and you should not add these lines. (The LaTeX syntax is even wrong in `\documentclass[article]` -- should be `{article}`)

Please learn more about Markdown from http://rmarkdown.rstudio.com

**Comment by StepanSushko** [comment]
In documention I've read the Knitr can work with LaTex, but I can't understand how.

**Comment by cvbusa** [comment]
HI ... I was getting this pandoc error 43 when running Knit PDF because of the following "bad" Rmarkdown code:

* #### An unordered list text using Header 4 

The code below works fine and a PDF is created without error:

#### Regular text using Header 4.

Charles.

**Comment by yihui** [comment]
The Markdown text

```md
* #### An unordered list text using Header 4
```

will be translated to LaTeX code like this

```latex
\begin{itemize}
\item
  \paragraph{An unordered list text using Header
  4}\label{an-unordered-list-text-using-header-4}
\end{itemize}
```

I do not really know why LaTeX does not like `\paragraph{}` in `\item`. You may try to ask LaTeX questions in these places: http://tex.stackexchange.com or http://stackoverflow.com But personally I do not understand why one wants to put a fourth-level section header in a bullet point, either. That seems to be really rare to me.

**Comment by cvbusa** [comment]
Thanks for your comments ... all is good!!!  I agree that the first line of code is just bad/sloppy code.

Charles.

**Comment by rpalloni** [comment]
What should I do if I want to customize the title of a slide in a beamer presentation.
For esemple:

# 1.2 Rate of project selection and expenditure declared by OP (%)
```{r echo=F}
knitr::read_chunk('Section_1/algo_1_2.R')
```
```{r figure_1_2, fig.align='center', fig.width = 12, fig.height = 5}
```\footnotesize{* Calculation based on totals}

How can I edit font, size, position, etc of ## 1.2 Rate of project selection and...
Why does it accept LaTex instruction in the footnot but not in the title? (error 43)
