### ISSUE TITLE
submitButton

### ISSUE THREAD

**Issue by pssguy** [rstudio/rmarkdown#365]
The fact that does not work in rmarkdown was raised several months ago

http://rmarkdown.rstudio.com/authoring_shiny.html

Any progress yet?

**Comment by yihui** [comment]
No.

I'm just moving the Disqus comment from @daattali here, to make it clear what @pssguy was talking about:

````
---
title: "Submit in markdown"
runtime: shiny
output: html_document
---

```{r, echo=FALSE}
library(shiny)
inputPanel(
textInput("text", "Text:", "text here"),
submitButton("Submit")
)
renderText({
paste("Input text is:", input$text)
})
```
````

**Comment by daattali** [comment]
The issue was raised a few years ago. Since then I've learned to dislike the submit button and wouldn't mind if this never gets implemented
