### ISSUE TITLE
Tufte handouts partially working (no tikz, classoptions or highlight)

### ISSUE THREAD

**Issue by xfim** [rstudio/rmarkdown#367]
I am not able pick some of the options for tufte handouts when using rmarkdown.

The issue is that while passing 'fig_width', 'fig_height', 'fig_crop' works, some other options do not work, namely 'highlight' and 'dev: tikz', as well as passing 'classoption' arguments.

This is a minimal example. The tikz device is not working and the pandoc line clearly says that the highlight used is not the one specified "espresso", for that matter. Not the final pdf is A4, justified, or with sans serif fonts for the notes.

I am using R-3.1.2, rmarkdown-0.5.1 and knitr-1.9.

The minimal.Rmd example: 
http://pastebin.com/raw.php?i=0dFYFE4M

Then, running the following generates a pdf, but not with the desired properties:

    library(rmarkdown)
    library(tikzDevice)
    render("minimal.Rmd", output_format="tufte_handout")

So the questions are a) how to correctly pass classoptions to tufte_handout, b) how to use tikz with tufte_handout and c) how to pass the correct highlight option to tufte_handout.

**Comment by jjallaire** [comment]
You are correct that tufte_handout doesn't support those additional options (they aren't part of that particular LaTeX template). You can use the tkiz device by just including this in a setup chunk:

```r
opts_chunk$set(dev = 'tikz')
```

**Comment by xfim** [comment]
Two issues:

1. if tufte_handout doesn't support them, how is in that in the documentation of the function the argument "highlight" does exist? Either something is wrong in the function or in the documentation.

2 Using 'tikz' hardcoded is a neat workaround, thank you. However, it collides if both html and tufte_handouts are to be produced.

**Comment by jjallaire** [comment]
I fixed the highlight problem here: https://github.com/rstudio/rmarkdown/commit/af27b7ccb4ad0cb75982f2faf58194867ce1c004 (thanks for pointing that out).

In terms of tkiz, I can't even get dev: tkiz to work at all. Here's the error message I get (clearly I am doing it wrong or haven't met some other requirement):

```
Error in check_dev(i) : 
  the graphical device'tkizDevice::tkiz'does not exist (as a function)
```

@yihui It would be very nice to get tkiz working with tufte_handout (especially considering you did this in the knitr graphics manual!). Let me what you think and if I am doing something wrong. Once we get tkiz itself working we should also consider whether we should turn off the pdfcrop filter in that case. Seems like we should but I guess if the pdfcrop filter knows to only act on pdfs then it's harmless to leave it active (and beneficial if any chunks override the tkiz device in favor of pdf).

**Comment by yihui** [comment]
@jjallaire I'm afraid `tkiz` was a typo? It should be `tikz`. You cannot use `dev = tikzDevice::tikz` either. Only `dev = tikz` is supported.

**Comment by jjallaire** [comment]
A typo indeed! @xfim you should indeed be able to add dev = 'tikz' as it should work as expected (this is with rmarkdown on github rather than CRAN).

**Comment by jjallaire** [comment]
@xfim, also just added support for classoption here: https://github.com/rstudio/rmarkdown/commit/f35553d58d354686925b2256b3230dcb680cc2d9

**Comment by xfim** [comment]
Many thanks.

The "classoption" works perfectly.

The 'tikz' device also works, but generates figures with "Computer Modern" font, instead of the default Palladio for tufte-handouts.

**Comment by yihui** [comment]
Unfortunately, the font issue is expected. It is because knitr does not know your LaTeX class in this case (you were knitting an R Markdown document instead of .Rnw). You will have to tell tikzDevice your LaTeX class manually via the option `tikzDocumentDeclaration` (e.g. `\documentclass{tufte-handout}`; I'm not 100% sure if this works); see `package?tikzDevice` for more info.

**Comment by xfim** [comment]
Exactly. Thank you very much @yihui .
