### ISSUE TITLE
Numbered bullets not formatted correctly in Pandoc

### ISSUE THREAD

**Issue by pyltime** [rstudio/rmarkdown#368]
According to the instructions here: http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html bullets with the format i. ii. iii. should create roman numerals. However, they instead use Arabic numbers when knit into Beamer presentations.

**Comment by jjallaire** [comment]
I think that's just a known limitation of Beamer (it works in HTML, PDF, etc.)
