### ISSUE TITLE
Captions don't work in R Markdown

### ISSUE THREAD

**Issue by pyltime** [rstudio/rmarkdown#369]
According to the Pandoc markdown documentation (http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html), the code `![Caption here](image.png)` should create an image with a caption if the image is by itself in a paragraph. This doesn't seem to work with R Markdown knitting to presentations or docs.

**Comment by jjallaire** [comment]
Try setting the fig_caption option to true (we turn off figure captions by
default)
