### ISSUE TITLE
Disable `-autolink_bare_uris` pandoc option?

### ISSUE THREAD

**Issue by cboettig** [rstudio/rmarkdown#372]
Is there a way to remove options that rmarkdown attaches to the format by default? (e.g. here: https://github.com/rstudio/rmarkdown/blob/e3fd06f0712a409cf2a66220a015e24a0b8a7223/R/output_format.R#L260)

I've tried defining a custom template modifying the call to `output_format`

```r
output_format(knitr = knitr_options_pdf(fig_width, fig_height,
                                            fig_crop, dev),
                  pandoc = pandoc_options(to = "latex",
                                          from = my_from_rmarkdown(fig_caption), args = args, keep_tex = keep_tex),
                  clean_supporting = !keep_tex, pre_processor = pre_processor)
```
using the modified definitions

```r
## No autolink bare uris please
my_from_rmarkdown <- function(implicit_figures = TRUE){
  my_rmarkdown_format(ifelse(implicit_figures, "", "-implicit_figures"))
}
my_rmarkdown_format <- function (extensions = NULL)
{
  paste(c("markdown", "-autolink_bare_uris", "+ascii_identifiers",
          "+tex_math_single_backslash", extensions), collapse = "")
}

```

but get the error that my format is not of the class `rmarkdown_output_format`.   In general a way to turn this off would be useful, for instance, it is responsible for the error in #125 by causing pandoc to put an `\href` into a LaTeX field that is expecting only a bare email.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/f891a1f90bdb4ecd2671d5bf53c638090d33539f

**Comment by cboettig** [comment]
Awesome, works like a charm.  Just updated https://github.com/rstudio/rticles/pull/27 to take advantage of this.

**Comment by jjallaire** [comment]
Great, sorry it took so long to get that in!
