### ISSUE TITLE
CSL file outside of working directory

### ISSUE THREAD

**Issue by mdlincoln** [rstudio/rmarkdown#376]
Is there a reason why the CSL file must be stored in the same directory as the Rmd document, while the bibliography file may live elsewhere? For example, if I set the options below:

```
bibliography: ~/[...]/Zotero/zotero.bib
csl: ~/[...]/Zotero/styles/chicago-fullnote-bibliography.csl
```

I receive the error `pandoc-citeproc: ~/Dropbox/Zotero/styles/chicago-fullnote-bibliography.csl: openBinaryFile: does not exist (No such file or directory)`.

**Comment by jjallaire** [comment]
I'm not sure what the reason for this is (this is a constraint we inherit from pandoc). You could file an issue over on the pandoc repo: https://github.com/jgm/pandoc

**Comment by mdlincoln** [comment]
> this is a constraint we inherit from pandoc

Is it? I can call pandoc from the command line directly and use bibliography and CSL files in other directories without any problem:

```
pandoc file.md -o file.latex --bibliography ~/Zotero/zotero.bib --csl ~/Zotero/styles/chicago-fullnote-bibliography.csl [etc...]
```

**Comment by jjallaire** [comment]
We aren't adding the CSL file via the command line, rather it's specified
within the document metadata. It looks like pandoc supports absolute paths
via the command line however doesn't when it's a reference in the document
metadata.

One possible workaround would be to detect the presence of the csl field in
the yaml front matter and then explicitly forward it to pandoc using the
--csl parameter. We're planning on a pass through the open rmarkdown issues
in a month or so and it should be easy to make this fix then (in the
meantime we'd certainly entertain a pull request).

**Comment by mdlincoln** [comment]
OK, that is more clear. And I can now file a more specific issue now on the Pandoc repo.

**Comment by dmenne** [comment]
@mdlincoln: Have you been able to solve this problem? It is a bit unexpected that I can use a path for the bib-file, but not for csl:

```
bibliography: C:/Users/Dieter/Documents/bibtex/menne.bib
csl: C:/Users/Dieter/Documents/bibtex/springer-basic-author-date.csl

```
This fails, I have to put csl in path
