### ISSUE TITLE
issue with UTF-8 / SHIFT-JIS in ioslides under pandoc 1.13.1

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#379]
I cannot render any UTF-8 (or SHIFT-JIS) encoded rmd file with 'Knit
HTML' button in GUI after updating Rstudio to the latest version 0.98.1102.
No such problem has occurred with previous versions as 0.98.1091.

This appears to be an issue on Windows however not on Linux or Mac.

Repro:

```

---
title: "Rプログラミング"
subtitle: "基礎"
author: "テスト"
date: "2015年2月20日（金）"
output: ioslides_presentation

---

## あああ
- イイイ
- うううエエエ
- test
- てすと
```

**Comment by yihui** [comment]
This might have been fixed by https://github.com/rstudio/rmarkdown/commit/955ebae74a6797f13953bee5d586b83b84a0dada
