### ISSUE TITLE
[FR] TO DO list

### ISSUE THREAD

**Issue by jangorecki** [rstudio/rmarkdown#380]
A feature request for *TO DO list* feature, like the one below, would be handy.
```
- [ ] my first item in list
- [ ] my second item in list
  - [ ] first sub item in second item in list
- [x] my third item in list, already done
```
- [ ] my first item in list
- [ ] my second item in list
  - [ ] first sub item in second item in list
- [x] my third item in list, already done

Also explained on [SO](http://stackoverflow.com/questions/28628903/to-do-list-in-rmarkdown)

**Comment by maxheld83** [comment]
+1

**Comment by yihui** [comment]
I think this feature request should be filed to Pandoc instead of rmarkdown.
