### ISSUE TITLE
indexed, named objects (formulae, tables, figures etc.) as in LaTeX

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#382]
It would be great if, in addition to referencing sections (as is already possible), it would also be possible to reference other objects by a similar syntax.

There's already some debate on this over at SO: http://stackoverflow.com/questions/13848137/figure-captions-references-using-knitr-and-markdown-to-html

Thought I'd post this here, too, couldn't find it anywhere.

**Comment by yihui** [comment]
Thanks for the report. I think this issue should be filed to Pandoc instead; rmarkdown is based on Pandoc, and cannot support Markdown features beyond what Pandoc allows.

**Comment by maxheld83** [comment]
yes of course, that makes sense. Pandoc issue lives here, I think: https://github.com/jgm/pandoc/issues/813
