### ISSUE TITLE
render with bibtex bibliography always throws error: `pandoc-citeproc: could not find locale data for C-UTF-8`

### ISSUE THREAD

**Issue by cboettig** [rstudio/rmarkdown#383]
This error seems to have appeared in the last month or so and prevents me from compiling anything with rmarkdown::render that uses an external latex `.bib` file.  

This problem only seems to occur with the rmarkdown call, and not when I call pandoc directly.  

Consider a trivial test.Rmd file: 

```
---
title: "Untitled"
output: html_document
bibliography: lib.bib
---

some text
```

Here the call to `render` fails, but pasting the same call into a system command works:

```r
 rmarkdown::render("test.Rmd", clean=FALSE)
output file: test.knit.md

...

/usr/lib/rstudio-server/bin/pandoc/pandoc test.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.html --filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /tmp/RtmpuVoztU/rmarkdown-str686249e0a7.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/usr/local/lib/R/site-library/rmarkdown/rmd/h/highlight --bibliography lib.bib 
pandoc-citeproc: could not find locale data for C-UTF-8
pandoc: Error running filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc
Error: pandoc document conversion failed with error 83
```

Above, error regarding locale.  But I try:

```r
> system("/usr/lib/rstudio-server/bin/pandoc/pandoc test.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.html --filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /tmp/RtmpuVoztU/rmarkdown-str686249e0a7.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/usr/local/lib/R/site-library/rmarkdown/rmd/h/highlight --bibliography lib.bib")
> 
```

and everything works just fine.  Huh?  What is rmardown doing that has so confused pandoc-citeproc on my system?

I realize this is probably some system-specific error, but I have no idea how to debug.  As you see above, I am using the versions of pandoc and pandoc-citeproc that ship with RStudio.  You should be able to replicate this by launching RStudio using the docker image `rocker/hadleyverse`, opening the PLoS tempate or any other template with a bib file, and hitting knit2pdf.  (Or more simply the rocker/rstudio image, after it installs `rmarkdown` and dependencies).  

Let me know if there's any further information I can provide to debug this.  Here's `sessionInfo()`:

```r
sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C         LC_MONETARY=C        LC_MESSAGES=C       
 [7] LC_PAPER=C           LC_NAME=C            LC_ADDRESS=C         LC_TELEPHONE=C       LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.8    evaluate_0.5.5  formatR_1.0     htmltools_0.2.6 knitr_1.9       rmarkdown_0.5.1 stringr_0.6.2   tools_3.1.2    
[9] yaml_2.1.13    
```

**Comment by cboettig** [comment]
Just a quick note: the above `sessionInfo()` was from inside an RStudio session -- I'm not sure why I get different locales in my `sessionInfo()` when using command-line R, but I get the same error regardless.  

Here, running the same test from command-line R (also on the rocker/hadleyverse image):

```r
 rmarkdown::render("test.Rmd")
```

```
processing file: test.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: test.knit.md

/usr/local/bin/pandoc test.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.html --filter /usr/local/bin/pandoc-citeproc --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /tmp/RtmpXqJL7B/rmarkdown-str12ad15aa.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/usr/local/lib/R/site-library/rmarkdown/rmd/h/highlight --bibliography lib.bib 
pandoc-citeproc: could not find locale data for C-UTF-8
pandoc: Error running filter /usr/local/bin/pandoc-citeproc
Error: pandoc document conversion failed with error 83
```

same error.  

Note that `sessionInfo()` is showing more UTF-8s in the locales now:
```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.8    evaluate_0.5.5  formatR_1.0     htmltools_0.2.6
[5] knitr_1.9       rmarkdown_0.5.1 stringr_0.6.2   tools_3.1.2    
[9] yaml_2.1.13    
```

**Comment by jjallaire** [comment]
My guess is that the change to pandoc 1.13.1 resulted in pandoc-citeproc
being more strict about having a particular locale set? By default Docker
images sometimes don't have all of the configuration required for locales,
does the composition of the image have something like what's in section 6
of this document:
http://crosbymichael.com/dockerfile-best-practices-take-2.html

Might be wrong about this but I recall when getting Docker images built for
shinyapps.io we had issues with pandoc and locales until we managed to get
all the configuration bits right.

**Comment by cboettig** [comment]
@jjallaire Thanks for the quick reply.  Yes, we configure locales to en-US.UTF-8 in the [r-base image](https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile) (thanks to @wch for some early input on this: https://github.com/rocker-org/rocker/issues/19).  

If this were simply an issue with locales and pandoc then I would expect the problem to occur with the `system()` or command-line calls.  However, as I show above, I can only produce this error by calling `render`, calling (the same, rstudio-server-included version of) pandoc does not produce this error.  Very strange. Any idea what is different between how `rmarkdown` is calling pandoc and the `system()` call I show above?

**Comment by jjallaire** [comment]
At it happens we do some manipulation of locale related environment
variables when we call pandoc. This is to avoid an OOM condition which
occurs for static Haskell binaries that don't have a locale defined. Here
is the code that does this:

https://github.com/rstudio/rmarkdown/blob/master/R/pandoc.R#L539-L564

You could try modifying this code to do nothing just to confirm that it's
introducing the problem and then see what other variations might work. I
don't think we have the option of doing nothing here as we need step around
the OOM problem, but perhaps there's another way that avoids the issue you
are seeing.

**Comment by cboettig** [comment]
@jjallaire Brilliant, thanks so much for the pointer; that indeed explains what is going on here.  Looks like simply setting the system env var `LANG=en_US.UTF-8` is enough to resolve this on my end.

Having LANG unset seems to cause rmarkdown to tell pandoc to use C.UTF-8 as LANG.  This seems like a bit of a strange choice given that rmarkdown has correctly detected that my `LC_CTYPE` is using `en_US.UTF-8` instead (as is my `LC_ALL`, which rmardown has decided to unset).  (I see the notes you have in there about the OOM condition, but couldn't seem to replicate the error.)  Would you consider setting this to use `LC_CTYPE` instead?  

It is not clear to me if pandoc fails when `LANG=C.UTF-.8` because `detect_generic_lang()` function is overly optimistic in deciding that I have the `C.UTF-8` locale configured, or because pandoc isn't finding the configuration (I noticed the pandoc error spells the locale with a dash, `C-UTF-8`)

**Comment by jjallaire** [comment]
Figured out the underling problem. Prior to Ubuntu 14.10 our R process was
automatically provided the LANG environment variable so everything worked
swimmingly. We now need to do something explicit to inherit it -- I've
sorted that out and the next daily/preview build will have fix. Discovered
and fixed one other Ubuntu 14.10 bug while I was at as well :-)

**Comment by cboettig** [comment]
Awesome, thanks again!

**Comment by jjallaire** [comment]
RStudio v0.99.320 fixes this issue. You can download it here: http://www.rstudio.com/products/rstudio/download/preview/

**Comment by setgree** [comment]
Just encountered this issue, and this thread helped a lot -- thanks very much!
