### ISSUE TITLE
get more editor support

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#386]
I love `rmarkdown`, and I think as a format, it may just finally solve a lot of problems in academic / data-driven publishing (LaTeX being great, but paper-focused and unwieldy).

There's just one thing that's holding me back a little: Rmarkdown seems a little ... RStudio-y, meaning, if you don't use RStudio,  a lot of support (syntax highlighting, REPL, build functions etc.) are gone.

I understand that this is an open source project and that I (nor anyone) isn't entitled to support of their favorite editor (or anything, really), but I still wanted to raise this issue and see what other people thought about it.

I've also raised a [package suggestion for atom.io](https://discuss.atom.io/t/package-suggestion-rmarkdown/15074), but had little resonance so far.

There's also *some* support in Sublime Text 3, via [R-Box](https://github.com/randy3k/R-Box) and (hopefully?) [AcademciMarkdown](https://github.com/mangecoeur/AcademicMarkdown), but it seems like both could use more help.

**Comment by yihui** [comment]
I think you did the right thing to file a request to atom.io, and such requests should be filed to _developers of other editors_. We are not Atom or SublimeText developers, so we cannot really do much on our side. Thanks!
