### ISSUE TITLE
support long-form output

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#387]
Rmarkdown is fantastic, but (other than PDF via LaTeX), it seems a little lacking in publishing long-form stuff like a book.
I am aware of @yihui's great [Rmarkdown vs LaTeX](http://yihui.name/en/2013/10/markdown-or-latex/) piece, and I agree that if floats and _typesetting_ on a physical piece of paper are key, it's probably easier to start with LaTeX and `.rnw` to begin with.

If you're _not_ into paper, however, there's nothing Rmarkdown can't do for you (ok, maybe except for indexed tables, figures etc. #382 :).

The only thing missing for fully digital publishing from this fantastic [Rmarkdown](https://github.com/rstudio/rmarkdown/) / [Pandoc](https://github.com/jgm/pandoc) / [Knitr](https://github.com/yihui/knitr) toolchain is an easy way to deploy long-form pieces to the web.

Several alternative / additional ways of how to do this come to mind.
- Go via [Jekyll](https://github.com/jekyll/jekyll)
  Have an `output_options =  "Jekyll"`, where `render` wraps a bunch of `*.md`s in a directory ready to be published via Jekyll.
  Maybe have 1-2 suitable Jekyll templates that would make the result look suitably book-like (chapter and section navigation, etc.).
  The nice thing would be that many people already have their work on github, and if `render` could somehow write the result to the `gh-pages` branch you'd have your book up and running in two commands. (`render`, `push`)
- Go via [gitbook.io](https://github.com/GitbookIO/gitbook)
  These guys have made a really pretty UI.
  An `output_options = "Gitbook.io"` would simply place all of the `*.md`s appropriately in a directory and create an additional `SUMMARY.MD` as specified by gitbook.io.
  Getting this stuff online would be a tad more difficult though, but I guess it could also be done in `gitbook-io` branch of some project.
  I have raised an issue with gitbook.io about *.Rmd support -> https://github.com/GitbookIO/gitbook/issues/307
- There is also [softcover](https://github.com/softcover/softcover)

I'm just curious what other people think about this / how they go about this.

**Comment by maxheld83** [comment]
@dpastoor mentioned that he had started some work on this (a separate function, actually) in [lpgitbook](https://github.com/dpastoor/lpgitbook).

**Comment by yihui** [comment]
I think this issue can be closed since we have got bookdown and blogdown now :)
