### ISSUE TITLE
Chunk option size do not work with rmarkdown (pdf_document)

### ISSUE THREAD

**Issue by LluisRamon** [rstudio/rmarkdown#388]
Using chunk option size don't work with rmarkdown and template pdf_document.

Here I include a minimal .Rmd document.

 ```
---
title: "Chunk option size do not work"
author: "Lluís Ramon"
date: "Tuesday, March 03, 2015"
output: pdf_document
---

Using chunk option size don't work with rmarkdown and template pdf_document.

    ```{r, size = "Large"}
    summary(cars)
    ```

    ```{r, size = "small"}
    summary(cars)
    ```

    ```{r, size = "tiny"}
    summary(cars)
    ```

```

Here I include a minimal .Rnw document which gives the expected behavior. 

```
\documentclass{article}

\begin{document}

\section*{Chunk option size work with .Rnw

}

<<size = "Large">>=
summary(cars)
@

<<size = "small">>=
summary(cars)
@

<<size = "tiny">>=
summary(cars)
@

\end{document}
```

Here is an image of the resulting pdf with .Rnw.

![chunk option size work with rnw](https://cloud.githubusercontent.com/assets/2566110/6459206/d4caf95a-c18c-11e4-853e-589e507544e8.png)
---

Here is my session info.

```
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.8       rmarkdown_0.5.1

loaded via a namespace (and not attached):
[1] digest_0.6.8    evaluate_0.5.5  formatR_1.0     htmltools_0.2.6 stringr_0.6.2   tools_3.1.2    
[7] yaml_2.1.13 
```

**Comment by jjallaire** [comment]
This is because Rmd documents are not highlighted by knitr (unlike Rnw
documents which are) and the "size" chunk option only affects knitr
highlighting. @yihui, anything to add here?

**Comment by yihui** [comment]
Right, the `size` option only applies to Rnw documents (R + LaTeX). It does not work for R Markdown.

**Comment by LluisRamon** [comment]
Hi @jjallaire and @yihui ,

Thank you for your rapid response.

I think that the [rmarkdown reference guide][] is misleading at this point because the chunk option size is defined there. 

[rmarkdown reference guide]: http://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-reference.pdf


Is there I place/way to know which knitr chunks work for rmarkdown and which ones don't?

Thank you for all the R products you are building.

**Comment by jjallaire** [comment]
Thanks, we'll update the cheat sheet to be correct!

**Comment by yihui** [comment]
@LluisRamon The vast majority of knitr chunk options (http://yihui.name/knitr/options/) apply to all document formats, and the only two exceptions are `size` and `background`.

**Comment by LluisRamon** [comment]
Thank you!

Is good to know that just size and background are the two only exceptions. 

By the way, background is also included in the reference guide.

**Comment by Kenkleinman** [comment]
2.5 years later, it still the case that size and background chunk options do not work with rmarkdown/latex/pdf?

If not, two questions:

1) Is there any convenient way to change the background color in pdf output from rmarkdown?
2) the rmarkdown cheat sheet is still unclear about this-- in fact I think it implies, for both options, that it is _for_ .Rmd file and for latex output.

Much gratitude, as always.

**Comment by jmcastagnetto** [comment]
A quick workaround for a few chunks is to use `\small` (or similar option, see: https://cran.r-project.org/web/packages/highlight/highlight.pdf#Rfn.highlight.1) before the chunk and `\normalsize` after it.

**Comment by AmeliaMN** [comment]
Thanks @jmcastagnetto! This workaround helped me out of a bind.

**Comment by yihui** [comment]
Yes, 5 years later, we do have a nice way to change the font size for code chunks. Example:

````
---
title: "Changing font sizes"
output: pdf_document
---

::: {.large}
```{r, size = "Large"}
summary(cars)
```
:::

::: {.small}
```{r, size = "small"}
summary(cars)
```
:::

::: {.tiny}
```{r, size = "tiny"}
summary(cars)
```
:::
````

You can read more about the fenced `Div`s (i.e. `:::`) here: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

The really nice thing about `:::` is that it works for other output formats, too. For example, for HTML output, you can define CSS rules for the classes `.small`, `.large`, and `.tiny`.
