### ISSUE TITLE
LaTeX Error: File `framed.sty' not found.

### ISSUE THREAD

**Issue by glfeng318** [rstudio/rmarkdown#39]
Knit PDF and got the error output:

```
/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc t.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output t.pdf --filter /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc-citeproc --template /Users/13k/R/rmarkdown/rmd/latex/default.tex --highlight-style tango --latex-engine pdflatex --variable geometry:margin=1in 
output file: t.knit.md

pandoc: Error producing PDF from TeX source.
! LaTeX Error: File `framed.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.31 \definecolor

Error: pandoc document conversion failed
Execution halted
```

my env:

```
> system('kpsewhich framed.sty')
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rmarkdown_0.1.19 tools_3.0.2      yaml_2.1.10     
> Sys.getenv('PATH')
[1] "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin"
```

`system('kpsewhich framed.sty')` returns nothing
i found a `framed.sty` in knitr package located:/Users/13k/R/knitr/misc
my TeX is `TeXLive-2013-Basic`
![snip20140330_44](https://cloud.githubusercontent.com/assets/394134/2560627/6562a0ba-b7d6-11e3-9ad0-81fc9fce8daa.png)
so, how to fixed this issue: `File 'framed.sty' not found.`

**Comment by nishantsbi** [comment]
Knit pdf and got the error:

This is pdfTeX, Version 3.1415926-2.5-1.40.14 (MiKTeX 2.9)
pdflatex: The memory dump file could not be found.
pdflatex: Data: pdflatex.fmt

pandoc.exe: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/Users/nishant/AppData/Local/Pandoc/pandoc" Foundation_of_Data_Analysis_edX_Labs.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output Foundation_of_Data_Analysis_edX_Labs.pdf --template "C:\Users\nishant\Documents\R\win-library\3.1\rmarkdown\rmd\latex\default.tex" --highlight-style tango --latex-engine pdflatex --variable "geometry:margin=1in"' had status 43 
Execution halted


it tried various options such as updating rmarkdown by

devtools::install_github("rstudio/rmarkdown")

still the problem remains...please suggest

My session info:
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SDSFoundations_1.1 gmodels_2.15.4.1  

loaded via a namespace (and not attached):
[1] digest_0.6.8    gdata_2.13.3    gtools_3.4.1    htmltools_0.2.6 MASS_7.3-35    
[6] rmarkdown_0.4.2 tools_3.1.2     yaml_2.1.13

**Comment by yihui** [comment]
@nishantsbi You need to install the framed package (cf http://docs.miktex.org/manual/pkgmgt.html)

**Comment by leofontenelle** [comment]
I had the same problem with Arch Linux, and solved it by installing the package `texlive-latexextra` (thanks!). The funny thing is, there was a `framed.sty` in the knitr package...

**Comment by cormac-work** [comment]
I ran 
`sudo tlmgr install titling`
and this worked for me on Mac 10.12.6

**Comment by JosiahParry** [comment]
I just had this issue on a new macbook pro with mojave. 
After downloading BasicTeX running `sudo tlmgr update --self` followed by `sudo tlmgr install titling` did the trick.

**Comment by JosiahParry** [comment]
Ah, interesting. Now I know for the future. I followed the suggested error output which suggested to download MacTeX. Perhaps the error output could suggest installing TinyTeX?

**Comment by yihui** [comment]
@JosiahParry I just submitted a PR for that: https://github.com/rstudio/rstudio/pull/3979 Thanks!

**Comment by JosiahParry** [comment]
Amazing. You rock!

**Comment by ras44** [comment]
I am on CentOS 7 and am receiving the same error message.  I was able to fix it by running

`sudo yum install -y texlive-titling`

**Comment by yihui** [comment]
For users who are still struggling with this issue, please see my comment above: https://github.com/rstudio/rmarkdown/issues/39#issuecomment-443078347 All you need is `tinytex::install_tinytex()`, no matter what your platform is. No need to use `sudo`, `apt`, `yum`, or any other commands. Everything will work automatically and out of the box.

I'm going to lock this thread. If TinyTeX doesn't work, please file an issue to https://github.com/yihui/tinytex. Thanks!
