### ISSUE TITLE
rmarkdown 0.5.1 / pandoc 1.13 / TeXLive 2014 - issue with the pdflatex engine

### ISSUE THREAD

**Issue by michaelmayer2** [rstudio/rmarkdown#391]
Hi, there seems to be an issue when trying to export markdown output to PDF together with pandoc. PDF's are not generated but pandoc exits with error code 43, 

My solution was to edit the file 

rmarkdown/templates/tufte_handout/resources/tufte-common.def

and replace the line 

\typeoutbool{pdfatex}{@tufte@pdf}

with

\typeoutbool{xelatex}{@tufte@pdf}

Then xelatex will be used instead of pdflatex to generate pdf's with rmarkdown

I am not sure if this is a correct fix so will leave it up to you to decide.

Kindly let me know if you need any additional information. 

Many thanks,

Michael.

**Comment by yihui** [comment]
I doubt that change will fix anything, because `\typeout` is simply a command to type a message to the LaTeX log. If you can post a minimal reproducible example, we may be able to figure out the real reason why Pandoc did not work.

**Comment by LyingCortex** [comment]
Oh,I have this problem too.^_^

**Comment by yihui** [comment]
@LyingCortex Again, could you provide a minimal reproducible example, along with the output of the following R code?

```
library(rmarkdown)
sessionInfo()
system('pdflatex --version')
```
