### ISSUE TITLE
Figures disappear in html with opts_chunk$set(dev="pdf")

### ISSUE THREAD

**Issue by ehrlinger** [rstudio/rmarkdown#392]
If you rmarkdown to html (ioslides for sure) with

`opts_chunk$set(dev="pdf")`

The slides show figures fine in the Rstudio viewer and when you view in browser. However, if you open the resulting html file directly in a browser, the figures links are all broken.

Changing dev="png", or removing the `dev` command entirely fixes the issue. Should there be a warning, or something when you have this chunk option set?

**Comment by yihui** [comment]
But why did you `opts_chunk$set(dev="pdf")` in the first place?... If you choose to use it explicitly, you are supposed to understand the consequences.

BTW, I do not think PDF figures will show up in HTML (which OS and version of RStudio are you using?) and I'm not aware of any web browsers that support this without using any plugins or special tools.
