### ISSUE TITLE
add gitbook format

### ISSUE THREAD

**Issue by maxheld83** [rstudio/rmarkdown#394]
a gitbook output format would be great for long form stuff (as per #387).

[Gitbook](https://github.com/GitbookIO/gitbook) is an open source project that takes a directory of `*.md`s, and together with very lightweight metadata (`SUMMARY.md`) builds the whole thing into a beautiful HMTL5 book.

Might be a nice idea to add that as an output format, where the structure of (`SUMMARY.md`) is somehow inferred from the knitr child option structure (maybe?).

I'm guessing this would not be too much work, since it only requires `*.md`s.

Might eventually try this myself, though I am pretty much a newbie.

Thought I'd ask for some feedback here, also from @SamyPesse and @AaronO of gitbook.io, and also @hadley who seems to have done something similar with [bookdown](https://github.com/hadley/bookdown) already, though via Jekyll in that case.

**Comment by znmeb** [comment]
One thing I've looked at is adding EPUB output to RMarkdown via Pandoc. You need some kind of Pandoc table of contents file, but aside from that it's probably just a matter of making some templates or even just passing Pandoc options in the YAML front matter.

You can already make PDFs via LaTeX - the only thing left would be making MOBI files. Calibre does that for GitBook, and there's also an Amazon tool called "KindleGen" which I think runs on Linux.

**Comment by yihui** [comment]
Just for the record: http://github.com/rstudio/bookdown/
