### ISSUE TITLE
HTML table issue with Rmarkdown 0.5.1

### ISSUE THREAD

**Issue by cloudly** [rstudio/rmarkdown#396]
Hi, 
I am trying to compile a very simple HTML table using rmarkdown 0.5.1...

    ---
    title: "HTML_TEST"
    autdor: "Liyun"
    date: "3/13/2015"
    output: html_document
    ---

    this is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

    When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

    ```{r, results='asis'}
    cat(' <table style="width:100%">
      <tr>
        <td>Jill</td>
        <td>Smith</td>
        <td>50</td>
      </tr>
      <tr>
        <td>Eve</td>
        <td>Jackson</td>
        <td>94</td>
      </tr>
    </table> ')
    ```

This one works perfect with an older version 0.3.10, but it breaks when using 0.5.1 (this version treats it as codes and pre-format it)... could anyone suggest how to solve it?

with 0.5.1:
![screen shot 2015-03-13 at 11 32 57 am](https://cloud.githubusercontent.com/assets/175005/6644876/c54d259e-c974-11e4-8e77-3057b74278cd.png)

with 0.3.10:
![screen shot 2015-03-13 at 11 35 02 am](https://cloud.githubusercontent.com/assets/175005/6644914/0d4ffe7a-c975-11e4-8e3e-7443f7f2aa11.png)

Thank you.

**Comment by jjallaire** [comment]
HTML that is indented 4 spaces is treated as pre-formatted text (as per the
markdown spec).  Just remove the indentation and all should be well. BTW if
you use the htmltools package to generate HTML it will automatically
generate output without the indenting.

**Comment by cloudly** [comment]
I was actually using htmlreg() from the texreg package... It worked perfectly before but just does not work with the new version of markdown...what has changed from 0.3.10 to 0.5.1?

**Comment by jjallaire** [comment]
It's a change in pandoc I believe (which is what rmarkdown uses for
markdown to html conversion). It's more strictly enforcing the 4 space
indentation rule.

More info here:
http://rmarkdown.rstudio.com/authoring_migrating_from_v1.html#preserving-generated-html

**Comment by cloudly** [comment]
Thank you @jjallaire. That points the key.

Finally my solution is to write a simple regular expression to eliminate the indents at beginning of each row:

<pre> <code> 
gsub("\n[[:space:]]","", htmlreg(list(A, B, C), single.row = T ))
</code> </pre>

It looks good now! Thank you.
