### ISSUE TITLE
broken links in documentation for pdf_document.r

### ISSUE THREAD

**Issue by 1beb** [rstudio/rmarkdown#397]
Documentation for pdf_document points to

1. http://johnmacfarlane.net/pandoc/demo/example9/templates.html
2. http://johnmacfarlane.net/pandoc/demo/example19/Citations.html
3. http://johnmacfarlane.net/pandoc/demo/example19/Footnotes.html

I think these can be replaced by: 

1 & 2. http://johnmacfarlane.net/pandoc/README.html#citations
3. http://johnmacfarlane.net/pandoc/README.html#footnotes

Not having seen the previous content, I'm not sure (hence havne't submitted a PR). Possible to replace with internal documentation: 

http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html 

Although this doesn't include anything about footnotes.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/8712121fccf6a2212f433891038bc786926ebbe2
