### ISSUE TITLE
JSS markdown template issue with plots and "$"

### ISSUE THREAD

**Issue by mbannert** [rstudio/rmarkdown#398]
I encountered an issue with plot chunks in the JSS Markdown template shipped with the latest preview release of R Studio (I assume the issue existed in previous versions too).

When I try to create a simple plot like:

plot(1:10)
I get the following error when I use the jSS template.

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43

Other templates like R Journal template work using the same code chunk. 

Also I have trouble with lists like `plot(mylist$my_eleemnt)` . The '$' seems to be an issue, too. At some points I can produce the plot but I get to see the latex code of the chunk in my document/

**Comment by yihui** [comment]
This is an rticles issue and has been reported multiple times, e.g. https://github.com/rstudio/rticles/issues/132. It should be fixed there instead of in rmarkdown. Thanks!

**Comment by yihui** [comment]
Fixed. Please try `devtools::install_github('rstudio/rticles')`. Note that it will require Pandoc 2.2.1. You can use the Preview version of RStudio if you do not want to install Pandoc separately: https://www.rstudio.com/products/rstudio/download/preview/
