### ISSUE TITLE
ioslides not printing to pdf as displayed

### ISSUE THREAD

**Issue by 1beb** [rstudio/rmarkdown#399]
Here's my miminmal reproducible example: 

``` markdown

---
title: "Title: Minimal Working Example"
output: ioslides_presentation
date: "Date: March 2015"
subtitle: "Subtitle: This is a subtitle"

---

## This is a test

This is a lot of text

## This is some more text

## This is a plot

CHUNK with Plot that breaks presentation in the issue

## This is another plot

CHUNK with Plot that breaks presentation in the issue 
```

When I try to print the presentation to PDF, I receive the following issue: 

![screenshot 35](https://cloud.githubusercontent.com/assets/421859/6681717/8a5f6858-cc39-11e4-9c61-275abb30d32b.png)

I'm able to print them reliably using phantomjs / casperjs under linux environment. But would be nice not to have to switch out for this task.

**Comment by papageorgiou** [comment]
Had the same issue
I had to take the following steps
- When the browser tab appears, click to disable the pop up block
- close the presenter pop up
- click the right arrow until you reach the last slide
- then try to printing to pdf (the last slide might still not print correctly). Hope this helps

**Comment by dselivanov** [comment]
+ 1 for this issue

**Comment by remi-daigle** [comment]
+1 for this issue

**Comment by yihui** [comment]
I'm afraid we are not going to substantially patch ioslides any more. Several other more modern and better maintained libraries are more friendly in terms of printing to PDF. Two examples are [xaringan](/yihui/xaringan) and [revealjs](/rstudio/revealjs). Please give them a try and let us know if we really have to bite the ioslides bullet :)

**Comment by yihui** [comment]
Recently I tried to improve the printing of ioslides, and I'm not sure if this issue happens to be resolved. Please try `remotes::install_github('rstudio/rmarkdown', upgrade = TRUE)`. I tested the minimal example above and the PDF generated from Chrome looked fine. Thanks!
