### ISSUE TITLE
consider looking for pdflatex in /usr/texbin on the mac if it's not found in the PATH

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rmarkdown#400]
Would make it easier to e.g. call rmarkdown::render from R.app which doesn't pickup the paths from /etc/paths and /etc/paths.d

**Comment by yihui** [comment]
I guess this is no longer an issue due to
https://github.com/rstudio/rmarkdown/blob/f2584f7f0d936692e947ca18f242267b73d6de48/R/util.R#L277-L297
