### ISSUE TITLE
subtitle spits an error when preparing a pdf document

### ISSUE THREAD

**Issue by 1beb** [rstudio/rmarkdown#403]
When preparing a document in multiple formats, using `render("...", "all")`, "subtitle" in the yaml header for other formats spits an error when used in conjunction with pdf_document.

**Comment by yihui** [comment]
What exactly was the error?

**Comment by 1beb** [comment]
It looks like pandoc spits the error but I'm not sure how to debug that. 
![screenshot 37](https://cloud.githubusercontent.com/assets/421859/6745734/a1f1af88-ce89-11e4-8e6d-0286a893d545.png)

**Comment by 1beb** [comment]
I looked in the dev branch and it looks like someone has merged a pull request for subtitle functionality, I would have thought that extras would just be ignored rather than spit an error.

**Comment by yihui** [comment]
It seems you need to install the `titling` package in MikTeX: https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/latex/default.tex#L140

**Comment by 1beb** [comment]
I'm looking at my Miktex installation and it says I already have it installed.
![screenshot 39](https://cloud.githubusercontent.com/assets/421859/6746692/bbbce502-ce9a-11e4-8e53-de33c2efdbaf.png)

**Comment by yihui** [comment]
Are you using the latest development version of rmarkdown here? Or the CRAN version?

**Comment by 1beb** [comment]
CRAN version.

**Comment by yihui** [comment]
That is weird. Can you run `system('kpsewhich titling.sty')` in R and tell me what it returns?

**Comment by 1beb** [comment]
Sorry, it's been a while. I'll be working on something this weekend where I will try to use subtitle.

**Comment by animalito** [comment]
Have the same problem, CRAN version

```
> system('kpsewhich titling.sty')
/usr/share/texlive/texmf-dist/tex/latex/titling/titling.sty
```

**Comment by yihui** [comment]
@animalito That is weird. I cannot reproduce this issue.

**Comment by chrisconlan** [comment]
Happens to me even when using a custom template file that supports subtitles. Very strange.

**Comment by cderv** [comment]
@chrisconlan If you still have an issue with this, please open a new issue following the [issue guide](https://yihui.org/issue/) and we'll look into it. This is not the best to post on old closed issue... and this is quite a old issue. You may link the issue for sure if they relate.

Thank you !
