### ISSUE TITLE
allow me to set title from render function instead of YAML

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#409]
I am turning my reports into a website. Currently, I don't need to use the YAML for anything but the title and I prefer it that way (with 50 reports I prefer to keep my options in one place).
As far as I can tell, the only way to set a title is via the YAML inside the document.
This feels redundant in my case. I'd prefer to use either the first top-level heading (this is probably not easy) or the processed file name as the title. 
The file names are already meaningful, if I could process them a little (e.g. turn underscores into spaces, capitalise) and feed them to my render function, I'd be happy.

Currently, the only way I can think of doing this, is by automatically modifying the Rmd file before rendering.

**Comment by jjallaire** [comment]
You can do this by passing custom metadata via pandoc_args. For example:

```r
rmarkdown::render("~/Desktop/foo.Rmd", 
   output_options = list(pandoc_args = c("--metadata=title:\"foo\""))
)
```
