### ISSUE TITLE
Personalized theme for shiny presentation?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/rmarkdown#411]
I would like to be able to create shiny R presentations using a personalized theme. Right now I am able to create [something that looks like what I want](http://people.virginia.edu/~im5j/test/test_template.html#1), but with a couple of limitations.

The first is the amount of html code that I have to use in the Rmd file. Creating a slide is not longer as easy as "# slidy name"

The second, and more important, is that shiny is not really working. I cannot push the `Run presentation` button on Rstudio. Moreover, I cannot have interactive shiny stuff in the presentation. To compile it I'm running `rmarkdown::render(input = 'test_template.Rmd')`.

Is it relatively easy to achieve what I want? Can you point me to the right direction?

Thanks!

PS: I uploaded the code that I'm using to [bitbucket](https://bitbucket.org/ignacio82/test-template)

**Comment by jjallaire** [comment]
I'd strongly recommend that you take a look at adding custom CSS to the
slidy_presentation format (which is compatible with shiny). The base CSS it
already uses is extremely minimal and I'd guess you could do just about
anything you want on top of it.

If you don't want to go this way and really want to create your own custom
format then I'd suggest looking at the source code for slidy_presentation
and doing something similar.

**Comment by ignacio82** [comment]
Thanks. Could you give me a link to what you have in mind?

**Comment by jjallaire** [comment]
Here is the documentation for the Slidy format:

http://rmarkdown.rstudio.com/slidy_presentation_format.html

You can use the css parameter to provide an additional stylesheet. The
original CSS you are customizing is here:

https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/slidy/Slidy2/styles/slidy.css
