### ISSUE TITLE
Use compareVersion

### ISSUE THREAD

**Issue by luckyrandom** [rstudio/rmarkdown#412]
On
https://github.com/rstudio/rmarkdown/blob/92b5aa4b3a3e090f8adf99bbb1a890e14ee56f59/R/render.R#L420

compare version as string is not safe, since "1.6.5" > "1.6.28". Use compareVersion instead.

similar issue in function `pandoc_available`.

**Comment by jjallaire** [comment]
I don't think you are correct about this. On my system I have the latest version of Rcpp (0.11.5) and the following expression evaluates to FALSE:

```r
packageVersion("Rcpp") > "0.11.28"
```
