### ISSUE TITLE
 LaTeX Error: File `ifluatex.sty' not found

### ISSUE THREAD

**Issue by myRpacks** [rstudio/rmarkdown#414]
Hi, I'm getting this error when I use KNIT PDF in rstudio-server (KNIT HTML runs without problems)

```
! LaTeX Error: File `ifluatex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.5 \usepackage

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted
```

Here are some details from R console:

```
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.8      htmltools_0.2.6   rmarkdown_0.5.3.2 tools_3.1.3       yaml_2.1.13  
```

and from the bash (I have texlive 2014 full distribution):

```
$ pdflatex -v
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
kpathsea version 6.2.0
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.10; using libpng 1.6.10
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.03

$ luatex -v
This is LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971)

Execute  'luatex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

Copyright 2014 Taco Hoekwater, the LuaTeX Team.

$ kpsewhich ifluatex.sty
/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/ifluatex.sty
```

Any idea on how to deal with this issue?
Thanks

**Comment by myRpacks** [comment]
I discovered that for some reason rstudio-server is using Latex 2007

system('pdflatex --version')
pdfTeX using libpoppler 3.141592-1.40.3-2.2 (Web2C 7.5.6)
kpathsea version 3.5.6
Copyright 2007 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Kpathsea is copyright 2007 Karl Berry and Olaf Weber.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX using libpoppler copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX using libpoppler source.
Primary author of pdfTeX using libpoppler: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Kpathsea written by Karl Berry, Olaf Weber, and others.

Compiled with libpng 1.2.46; using libpng 1.2.49
Compiled with zlib 1.2.3; using zlib 1.2.3
Compiled with libpoppler

So at this point I think this is an issue related to my rstudio-server. Any idea on how to fix the issue is welcome. Thanks.

**Comment by jjallaire** [comment]
RStudio Server just uses the version of pdflatex on your PATH, so you need
to resolve this at the system level

On Apr 19, 2015, at 4:09 PM, myRpacks <notifications@github.com> wrote:

I discovered that for some reason rstudio-server is using Latex 2007

system('pdflatex --version')
pdfTeX using libpoppler 3.141592-1.40.3-2.2 (Web2C 7.5.6)
kpathsea version 3.5.6
Copyright 2007 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Kpathsea is copyright 2007 Karl Berry and Olaf Weber.
There is NO warranty. Redistribution of this software is
covered by the terms of both the pdfTeX using libpoppler copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX using libpoppler source.
Primary author of pdfTeX using libpoppler: Peter Breitenlohner (eTeX)/Han
The Thanh (pdfTeX).
Kpathsea written by Karl Berry, Olaf Weber, and others.

Compiled with libpng 1.2.46; using libpng 1.2.49
Compiled with zlib 1.2.3; using zlib 1.2.3
Compiled with libpoppler

So at this point I think this is an issue related to my rstudio-server. Any
idea on how to fix the issue is welcome. Thanks.

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rmarkdown/issues/414#issuecomment-94309644>.

**Comment by myRpacks** [comment]
I'm not so sure about that. 

From R console i get
> system('latex -v')
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
kpathsea version 6.2.0
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.10; using libpng 1.6.10
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.03

whereas from rstudio server I get 

> system("latex -v")
pdfTeX using libpoppler 3.141592-1.40.3-2.2 (Web2C 7.5.6)
kpathsea version 3.5.6
Copyright 2007 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Kpathsea is copyright 2007 Karl Berry and Olaf Weber.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX using libpoppler copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX using libpoppler source.
Primary author of pdfTeX using libpoppler: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Kpathsea written by Karl Berry, Olaf Weber, and others.

Compiled with libpng 1.2.46; using libpng 1.2.49
Compiled with zlib 1.2.3; using zlib 1.2.3
Compiled with libpoppler

So it seems they are using different latex distributions!!

**Comment by jjallaire** [comment]
Then you must have a different PATH when running under RStudio Server
(again, there is no attempt to 'use' a specific version of pdflatex it's
just whatever is on the PATH)

On Apr 19, 2015, at 4:41 PM, myRpacks <notifications@github.com> wrote:

I'm not so sure about that.

From R console i get

system('latex -v')
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
kpathsea version 6.2.0
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty. Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.10; using libpng 1.6.10
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.03

whereas from rstudio server I get

system("latex -v")
pdfTeX using libpoppler 3.141592-1.40.3-2.2 (Web2C 7.5.6)
kpathsea version 3.5.6
Copyright 2007 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Kpathsea is copyright 2007 Karl Berry and Olaf Weber.
There is NO warranty. Redistribution of this software is
covered by the terms of both the pdfTeX using libpoppler copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX using libpoppler source.
Primary author of pdfTeX using libpoppler: Peter Breitenlohner (eTeX)/Han
The Thanh (pdfTeX).
Kpathsea written by Karl Berry, Olaf Weber, and others.

Compiled with libpng 1.2.46; using libpng 1.2.49
Compiled with zlib 1.2.3; using zlib 1.2.3
Compiled with libpoppler

So it seems they are using different latex distributions!!

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rmarkdown/issues/414#issuecomment-94311501>.

**Comment by myRpacks** [comment]
rstudio server knows the PATH for texlive but for some reason is using latex from /usr/bin/ 

> system("echo $PATH")
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/local/texlive/2014/bin/x86_64-linux/

**Comment by jjallaire** [comment]
That's because /use/bin is first in the PATH

Sent from my iPhone

On Apr 19, 2015, at 4:56 PM, myRpacks <notifications@github.com> wrote:

rstudio server knows the PATH for texlive but for some reason is using
latex from /usr/bin/

system("echo $PATH")
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/local/texlive/2014/bin/x86_64-linux/

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rmarkdown/issues/414#issuecomment-94313010>.

**Comment by myRpacks** [comment]
yeah. Any idea on how to change the ordering?

**Comment by jjallaire** [comment]
Sys.setenv(PATH=/the/path/you/want)

On Apr 19, 2015, at 5:10 PM, myRpacks <notifications@github.com> wrote:

yeah. Any idea on how to change the ordering?

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/rmarkdown/issues/414#issuecomment-94315041>.

**Comment by myRpacks** [comment]
Ok, I run
Sys.setenv(PATH="/usr/local/texlive/2014/bin/x86_64-linux")
> system("latex -v")
pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
kpathsea version 6.2.0
Copyright 2014 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.10; using libpng 1.6.10
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.03

but knit PDF still doesn't run

! LaTeX Error: File `ifluatex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.5 \usepackage

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted

**Comment by myRpacks** [comment]
Hi, I solved the problem by re-installing rstudio server.
