### ISSUE TITLE
Rmarkdown & googleVis issue

### ISSUE THREAD

**Issue by ncdingari** [rstudio/rmarkdown#415]
If I use

```
output:
  html_document:
    self_contained: no
```

and

You can also embed plots

````
```{r, results='asis'}
suppressMessages(library(googleVis))
Pie1 = gvisPieChart(CityPopularity)
Pie1
```
````

The font size for the text "You can also embed plots", is decreasing

**Comment by rainer-rq-koelle** [comment]
Was there any development on this? I struggle with the same problem. While working with _self_contained: no_ to overcome a pandoc fails with error 67, the font size of the html page is shrinking to a minimal size. Fixing this in a css stylesheet file for all html tags (e.g. p, ul, etc) is cumbersome. 
Is there a way to work without the _self_contained: no_ when embedding googleVis in R Markdown (and avoiding the _pandoc error 67_?

**Comment by ncdingari** [comment]
The following code worked
```
{r warning=FALSE, echo=FALSE, message=FALSE, results='asis', tidy=FALSE}
library(googleVis)

op <- options(gvis.plot.tag = 'chart')

df = data.frame(models = c("PLAT", "LC", "APC", "CBD", "M6", "M7", "M8"), val = 1:7)
Column <- gvisColumnChart(df)
Column
```

**Comment by yihui** [comment]
This not rmarkdown's fault. The font size issue was caused by googleVis in this case. Specifically: https://github.com/mages/googleVis/blob/c6822163e0/R/gvis.R#L577
