### ISSUE TITLE
RMarkdown overparses CSS files

### ISSUE THREAD

**Issue by kmader** [rstudio/rmarkdown#418]
I have an RMarkdown report exporting to HTML and a few lines adding relevant css files to the report, specifically
```{html}
<link rel="stylesheet" href="leaflet.css" />
```
It then produces the error message
```
pandoc: Could not fetch html-demo/#default#VML
```

Since it is trying to parse this line
```{css}
.lvml {
	behavior: url(#default#VML);
	display: inline-block;
	position: absolute;
	}
```
which  does not refer to a physical file.

**Comment by jjallaire** [comment]
This issue occurs within pandoc resource downloading (used to implement self contained documents) so needs to be resolved in pandoc. You can post an issue here: https://github.com/jgm/pandoc

In the meantime you can get a version of your reporting working by setting `self_contained: false` in the output format options.
