### ISSUE TITLE
pandoc: Could not fetch ...

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/rmarkdown#419]
Hi,

I don't know that I can claim reproducibility on this, but I am happy to work towards reproducibility.

Over the weekend, I updated R -> 3.2.0, reinstalled all my packages, now I get this error in the "R Markdown" window, whenever I hit the "knit html" button on an Rmd file:

````
pandoc: Could not fetch //maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted
````

This looks a little bit like #228, but perhaps the resemblance is superficial.
 
FWIW, I have pandoc 1.31.1 installed, but I get the same error using pandoc 1.13.2. 

Thanks,

Ian

Here's my session info.

````
> session_info()
Session info -------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.386)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             

Packages -----------------------------------------------------------------------------------------------------------------
 package    * version date       source                            
 devtools     1.7.0   2015-01-17 CRAN (R 3.2.0)                    
 digest     * 0.6.8   2014-12-31 CRAN (R 3.2.0)                    
 htmltools  * 0.2.6   2014-09-08 CRAN (R 3.2.0)                    
 memoise    * 0.2.1   2014-04-22 CRAN (R 3.2.0)                    
 rmarkdown  * 0.5.3.1 2015-04-27 Github (rstudio/rmarkdown@4c8b860)
 rstudioapi * 0.3.1   2015-04-07 CRAN (R 3.2.0)                    
 yaml       * 2.1.13  2014-06-12 CRAN (R 3.2.0)   
````

**Comment by jjallaire** [comment]
This relates to a package you are using that is importing the font-awesome
library from a CDN (the rmarkdown package doesn't make any use of
font-awesome). pandoc appears to not know how to handle the
protocol-relatively link.

Here's what appears to be a related link:
https://github.com/jimhester/knitrBootstrap/issues/172

You may be able to work around this by specifying self_contained: false

**Comment by ijlyttle** [comment]
Hi JJ,

You're right. I found a stray `_output.yaml` file in the directory that refers to a formatting package that I need to update.

Moved to its own directory; all is well. No issue other than operator error.

Thanks,

Ian
