### ISSUE TITLE
Request:  pandoc_version() function

### ISSUE THREAD

**Issue by dmurdoch** [rstudio/rmarkdown#422]
rmarkdown 0.5.1 (current on CRAN) includes a function pandoc_available(), which allows a document to check for a particular version of pandoc.  But if the test fails, it would be nice to give the user a warning stating what version was found.  A function like

    pandoc_version <- function() {
      find_pandoc()
      .pandoc$version
    }

would make that message easy without snooping into rmarkdown internals.

**Comment by jjallaire** [comment]
Just added this. BTW we're hoping to rev the CRAN version within 30 days or so.

**Comment by dmurdoch** [comment]
On 28/04/2015 5:08 PM, JJ Allaire wrote:
> Just added this. BTW we're hoping to rev the CRAN version within 30 days
> or so.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/rmarkdown/issues/422#issuecomment-97207511>.
> 
Thanks!

Duncan
