### ISSUE TITLE
pandoc now includes woff2 in mime-types

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/rmarkdown#427]
As of https://github.com/jgm/pandoc/commit/7031748a434c0624ca2139e91da0ea8a5559169c , pandoc now can support `woff2` fonts.  I have run into this often in building htmlwidgets and previously had to manually remove `woff2` from the CSS, such as https://github.com/sdwfrost/phylowidget/pull/9.  Can/will you update this in `rmarkdown` to ease this pain?  Thanks so much.

**Comment by jjallaire** [comment]
I don't think we can do this anytime soon as RStudio pandoc typicailly
tracks about 12 months behind the tip of pandoc and even then don't
necessarily rev the minimum pandoc version (so as to better support
non-RStudio environments). Also, currently if you want to support RStudio
v0.98 you need to use truetype (this isn't true of RStudio v0.99 but it
isn't out yet).

Net: yes, eventually, where eventually could still be a couple of years.

**Comment by yihui** [comment]
The latest version of RStudio ships Pandoc 1.19.2.1, so I assume this issue can be closed now.
