### ISSUE TITLE
ioslides: Small copy of logo on each slide does not get included with self_contained: true

### ISSUE THREAD

**Issue by rbubley** [rstudio/rmarkdown#428]
I have

<pre>
output:
  ioslides_presentation:
    logo: media/SquareCircle.svg
    self_contained: true
</pre>

And my logo gets included in the HTML file on the title page, but on subsequent pages it still appears as a remote URL.

Looking at the css reported by Chrome, I see (among other things):

<pre>
slides > slide:not(.nobackground):before {
  background: url(media/SquareCircle.svg) no-repeat 0 50%;
}
</pre>

All of the other resources get included perfectly well. (I'm using rmarkdown_0.6.1 )

**Comment by jaredlander** [comment]
The logo shows up (tiny) when self_contained is false but is absent when self_contained is true.  Guessing it's not getting base64 encoded properly?  Looks like it's still trying to pick it up through a relative path in the CSS.

**Comment by yihui** [comment]
Occasionally I also find Pandoc's base64 encoding of background images in CSS problematic. What is your Pandoc version? You can get it from `rmarkdown::pandoc_version()`

**Comment by yihui** [comment]
Oh just took a look at the pandoc repo, and @jgm has fixed the bug that I intended to report: https://github.com/jgm/pandoc/commit/fb1843ecdeea5131ea4ed27adc1124e13ae1c5d9 So it looks we will have to wait for the next version of Pandoc... Or you do base64 encoding by yourself in CSS, e.g. replace `media/SquareCircle.svg` with the output of `knitr::image_uri('media/SquareCircle.svg')`

**Comment by jaredlander** [comment]
I'm running ‘1.15.0.6’.  Glad he issued a fix.

Could I do `knitr::image_uri('media/SquareCircle.svg')` in the yaml header?

**Comment by yihui** [comment]
Sorry, I have no idea... You may try something like

```yaml
---
....
    logo: `r knitr::image_uri('media/SquareCircle.svg')`
---
```

**Comment by jaredlander** [comment]
yaml didn't like that.  When I enclosed it in double quotes pandoc could not load the resource.  Could be a working directory issue at that point.

**Comment by yihui** [comment]
Okay, then I guess we will have to wait for the next version of Pandoc to be released.

**Comment by yihui** [comment]
This issue should be resolved if you use the latest version of RStudio, which comes with Pandoc 1.19.2.1, or upgrade your Pandoc.
