### ISSUE TITLE
unused argument error depending on output format

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rmarkdown#437]
I have an RMarkdown file with leading YAML:

```
title: "empty"
output:
  pdf_document: {}
```

I have some generic code that is attempting to render a document. That code blindly specifies `self_contained=TRUE` which produces the error:

```
> rmarkdown::render("empty.Rmd", output_options=list(self_contained=TRUE))
Error in (function (toc = FALSE, toc_depth = 2, number_sections = FALSE,  : 
  unused argument (self_contained = TRUE)
```

If I change to `output: html_document` there is no error, as one would expect.

If I specify multiple outputs and have `html_document` first, there is no error:

```
output:
  html_document: {}
  pdf_document: {}
```

If, however, I reverse the order of the output formats, we see the error again:

```
output:
  pdf_document: {}
  html_document: {}
```

The `self_contained` option does not apply to PDFs; is there a way to give `output_options` which will only apply to specific output formats (or _not_ apply to specific output formats)? Alternatively, could the fact that the `output_options` value is not used be an information (or warning) message instead of a hard error?

**Comment by jjallaire** [comment]
There isn't a way to do this now. However, there is a
rmarkdown::default_output_format function that will allow you to probe the
file to determine whether it's safe to pass self_contained=TRUE or not.

**Comment by aronatkins** [comment]
Thanks. That's helpful. Right now, I've got the following, which works around the problem:

```
  output_options <- NULL
  output_format <- rmarkdown::default_output_format(rmdFile)
  if (output_format$name != "pdf_document") {
    output_options <- list(
        self_contained = TRUE
        )
  }
  rmarkdown::render(rmdFile, output_options=output_options)
```

**Comment by jjallaire** [comment]
I think the code needs to be a bit more general to work for all possible
formats (e.g. beamer_presentation and the PDF formats in the rticles
package also don't support self_contained). You can actually inspect the
object returned from rmarkdown::default_output_format to determine if it
has a self_contained parameter. The code would look like this:

```r
format <- rmarkdown::default_output_format("foo.Rmd")
"self_contained" %in% names(format$options)
```

**Comment by aronatkins** [comment]
Thanks again. This technique appears to work for me.

**Comment by poudas1981** [comment]
Thanks this technique works for me
