### ISSUE TITLE
ioslides: problem with rendering several htmlwidgets

### ISSUE THREAD

**Issue by davidpham87** [rstudio/rmarkdown#441]
Hi,

I have to display several html widgets one after the other using the ioslides_presentation argument with rmd.

It seems that the html code is in the source code, however, the slide does not display the chart.

Here is a sample code

```
---
title: "R and Data Visualizations"
output: ioslides_presentation
--- 


## HTML Widgets - dygraphs {.smaller}

```{r dygraphs, message=FALSE, results='asis'}
library(dygraphs)
dygraph(nhtemp, main = "New Haven Temperatures") %>%
    dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01"))
```

## HTML Widgets - metricgraphics {.smaller}

```{r metricgraphics, message=FALSE, results='asis'}
library(metricsgraphics)
mjs_plot(mtcars, x=wt, y=mpg) %>%
  mjs_point(color_accessor=carb, size_accessor=carb) %>%
  mjs_labs(x="Weight of Car", y="Miles per Gallon")
```

## HTML Widgets - networkD3 {.smaller}

```{r networkD3, message=FALSE, results='asis'}
library(networkD3); data(MisLinks, MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4)
```

```

**Comment by jjallaire** [comment]
We've recently made some changes to the htmlwidgets package to better handle sizing in the case of DOM elements that are shown and hidden (like ioslides does). Try installing the latest htmlwidgets from GitHub then restarting:

```r
devtools::install_github("ramnathv/htmlwidgets")
```

We'll be releasing a version of htmlwidgets to CRAN with this fix within 2 or 3 weeks.

**Comment by davidpham87** [comment]
Thanks a lot for your answer! Your solution did work really well :-)

**Comment by wlandau-lilly** [comment]
The `visNetwork` graph is blank for me in the following ioslides, but it renders just fine with Slidy and reveal.js. I have tried the latest CRAN and dev versions of `htmlwidgets` and `rmarkdown`.

```
---
title: "slides"
output: ioslides_presentation
---

## The HTML widget should render.

```{r}
library(visNetwork, quietly = TRUE)
visNetwork(data.frame(id = 1:3), data.frame(from = c(1,2), to = c(1,3)))
```
```
