### ISSUE TITLE
figures appear in toc

### ISSUE THREAD

**Issue by beamgau** [rstudio/rmarkdown#445]
Hi, 

i have a problem when making headers from chunks; somehow the following plot gets into the heading. i believe it has to do with closing tabs from the header, but i am not sure. please check the following rmd-file.

best, felix

```
---
   title: "Untitled"
   output: 
    html_document:
        toc: true
        toc_depth: 3
---

```{r, echo=FALSE, results='asis'}
cat("## section 1")
plot(cars)
    ```
```

**Comment by yihui** [comment]
I believe you can solve this problem by adding a few line breaks in the section heading, e.g. `cat("## section 1\n\n")`

**Comment by beamgau** [comment]
ah, thanks a lot! i thought something like this would be the solution but tried adding <br>s.

**Comment by yihui** [comment]
HTML linebreaks `<br/>` won't work in this case. What you need is at least one empty line after the heading.
