### ISSUE TITLE
Bullet points do not nest properly when tab width is 2 in Rmd docs

### ISSUE THREAD

**Issue by chendaniely** [rstudio/rmarkdown#446]
Rstudio has a default setting that sets the tab width to 2.  However, when one tries to nest bullet points in an `.Rmd` document, the 2 spaces do not register as an indented bullet and will show it as the same level as the parent bullet

**Comment by vyp** [comment]
This might be a pandoc restriction?

**Comment by chendaniely** [comment]
@vyp Thanks for pointing that out.  According to the pandoc documentation [1] "The nested list must be indented four spaces or one tab", so it does seem to be a pandoc restriction.

I know the easiest fix would be to set the tab width to 4 spaces, but for those new to Rmd documents, the default rstudio setting may cause confusion for new comers... Not sure what the best solution would be.

[1] http://pandoc.org/README.html

**Comment by vyp** [comment]
> According to the pandoc documentation [...]

Yes, sorry that's what I meant. But I'm not exactly sure how rmarkdown works in relation to pandoc, hence the question mark.

I agree it's confusing for new users using rstudio though. Perhaps a note in the readme?

---

Just in case, you will not be able to change pandoc for this. The list indentation thing has been done to death. If you are interested in the "theoretical" issues with list indentation though, and if you didn't already know, the author of pandoc and others are working on a "standardized" markdown specification [1], where he has rethought the matter a bit (read the spec, if you have the time). (Pandoc will implement commonmark, if it hasn't already.)

[1] http://commonmark.org/

**Comment by yihui** [comment]
I feel there is not much we can do in the rmarkdown package, other than reminding users of reading the Pandoc's Markdown syntax over and over again.

**Comment by vyp** [comment]
@yihui FYI https://github.com/jgm/pandoc/issues/3511 :tada:

**Comment by yihui** [comment]
@vyp That is awesome!!
