### ISSUE TITLE
include css located in parent folder?

### ISSUE THREAD

**Issue by happyshows** [rstudio/rmarkdown#449]
Hi,

I'm trying to apply the same css for multiple projects (in their own folders). Hence I'd like to have each of the rmd point to a master.css file located in their parent folder.

I have tried html_document: css: ../master.css  and html_document: css: "../master.css", but none of them are working.

What's the right way to point to the master.css file?

**Comment by jjallaire** [comment]
You might want to consider creating a custom R Markdown format that
includes your master.css file:

http://rmarkdown.rstudio.com/developer_custom_formats.html

**Comment by happyshows** [comment]
@jjallaire JJ, I wanted to dump a few Rmd templates on shiny server folder and let them run individually. My understanding is shiny server can pick up and run the index.Rmd automatically. I feel the approach you suggested is more appropriate for someone generate rmd from a desktop. Let me know if this clarifies...

**Comment by jjallaire** [comment]
I think in that case you might just need to write a script which copies the
CSS files to all of the directories. Realize this isn't ideal but it's the
only thing that will work right now.

**Comment by happyshows** [comment]
@jjallaire ok, thanks for the help.
