### ISSUE TITLE
navigation in Rstudio

### ISSUE THREAD

**Issue by acoppock** [rstudio/rmarkdown#452]
When writing an rmd in Rstudio, the navigation in the lower left hand corner of the editor window lets you jump to chunks.  But if a user is structuring a document with
# Section 1
## Subsection 1.1
# Section 2

etc, then I think it would be nice if Rstudio would use this structure for navigation.

**Comment by jjallaire** [comment]
That's in the works now (we also going to add a side-by-side outline view
which will do the gutter navigation one better!)

**Comment by mdlincoln** [comment]
:+1:

**Comment by yihui** [comment]
The latest version of RStudio should show you the document outline now.
