### ISSUE TITLE
Feature request: enable adding images/logos above document title in word output

### ISSUE THREAD

**Issue by simonthelwall** [rstudio/rmarkdown#459]
One barrier to greater adoption of Rmarkdown is the need to incorporate corporate branding. Templates go some way to solving this, but to my knowledge it is not currently possible to insert a corporate logo (or any image) at the top of the document if the output is Word. 

It would be great if one could specify an image file in the YAML header which would go at the very top of the document.

**Comment by jjallaire** [comment]
You might be able to achieve this now with a custom pandoc word template.
In pandoc 1.13 they enhanced the docx writer to carry over image headers in
reference.docx:

Docx writer:

   - Document formatting is carried over from reference.docx. This includes
   margins, page size, page orientation, header, and footer, including images
   in headers and footers.


So if you create your own reference.docx and pass it to word_document you
should be able to get this to work.

**Comment by simonthelwall** [comment]
That does work, thanks very much. I wasn't aware of the image headers in Word.

**Comment by yihui** [comment]
For future reference: http://rmarkdown.rstudio.com/articles_docx.html

**Comment by ellereve** [comment]
http://rmarkdown.rstudio.com/articles_docx.html is very helpful in getting started but I don't see how it helps in solving the image issue. Nor do I understand how pandoc fits in to the picture. Could someone please clarify? I followed the instructions from this link and made a template with an image header. I get: scanner error: mapping values are not allowed in this context at line 4: column 22
