### ISSUE TITLE
lost of formatting with html_vignette

### ISSUE THREAD

**Issue by stla** [rstudio/rmarkdown#461]
Hello, 
The formatting of a markdown table printed as a comment is totally lost with the `html_vignette` rendering.
For example,
```
---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

Hello.

    ```{r}
    library(pander)
    cat(pander(data.frame(a=1:3, b=11:13, c=c("The sun", "is", "shining"), d=91:93)))
    ```
```
generates:

![capture du 2015-06-29 12 22 18](https://cloud.githubusercontent.com/assets/4466543/8406103/8ac5e0f2-1e59-11e5-9a3f-5d3c50e7be92.png)

**Comment by jjallaire** [comment]
For pander you need to add the results='asis' chunk option:

```{r, results='asis'}
library(pander)
cat(pander(data.frame(a=1:3, b=11:13, c=c("The sun", "is", "shining"),
d=91:93)))
```

**Comment by stla** [comment]
I get the html output if I do that. Exactly the same as 
```
    ```{r}
    library(pander)
    pander(data.frame(a=1:3, b=11:13, c=c("The sun", "is", "shining"), d=91:93))
    ```
```
This is not what I want. I want the following output, and I can't get it with `rmarkdown::html_vignette`:

![capture du 2015-06-29 13 26 31](https://cloud.githubusercontent.com/assets/4466543/8406991/889e5742-1e62-11e5-970b-f17803e906ca.png)

**Comment by jjallaire** [comment]
Hmm...when I execute the same code I get exactly what you are looking for:

![screen shot 2015-06-29 at 1 32 37 pm](https://cloud.githubusercontent.com/assets/104391/8407090/83ec0ae0-1e63-11e5-891d-3f05787be4c9.png)

Perhaps a difference in versions of packages in play? Here's my sessionInfo:

```
## R version 3.1.2 (2014-10-31)
## Platform: x86_64-pc-linux-gnu (64-bit)
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] pander_0.5.2
## 
## loaded via a namespace (and not attached):
##  [1] digest_0.6.8    evaluate_0.7    formatR_1.2     htmltools_0.2.6
##  [5] knitr_1.10.5    magrittr_1.5    Rcpp_0.11.6     rmarkdown_0.7  
##  [9] stringi_0.4-1   stringr_1.0.0   tools_3.1.2     yaml_2.1.13
```

**Comment by stla** [comment]
Strange !
```
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=fr_BE.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_BE.UTF-8        LC_COLLATE=fr_BE.UTF-8    
 [5] LC_MONETARY=fr_BE.UTF-8    LC_MESSAGES=fr_BE.UTF-8   
 [7] LC_PAPER=fr_BE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] brr_0.0

loaded via a namespace (and not attached):
 [1] contfrac_1.1-9    curl_0.9          digest_0.6.8      elliptic_1.3-5   
 [5] gsl_1.9-10        htmltools_0.2.6   hypergeo_1.2-9    jsonlite_0.9.16  
 [9] knitr_1.10.12     magrittr_1.5      MASS_7.3-39       pander_0.5.2     
[13] Rcpp_0.11.6       rmarkdown_0.7     rstudio_0.98.1091 rstudioapi_0.3.1 
[17] stringi_0.5-5     stringr_1.0.0     SuppDists_1.1-9.1 TeachingDemos_2.9
[21] tools_3.1.3       V8_0.6            yaml_2.1.13    
```

**Comment by stla** [comment]
Oh wait ! It doesn't work in the Rstudio viewer, but it works in the browser !

**Comment by jjallaire** [comment]
Interesting, what version of RStudio are you running?

**Comment by stla** [comment]
It is given in the session info. This is version `0.98.1091`.

**Comment by jjallaire** [comment]
Okay,  I'm running RStudio v0.99 so that may explain the difference.

J.J.

**Comment by yihui** [comment]
I believe the different RStudio versions was the problem. I remember monospaced fonts did not work in lower versions of RStudio.

**Comment by stla** [comment]
I have just tried under Windows with the latest RStudio and it works fine.
Is it really due to RStudio itself or to the version of pandoc included in RStudio ? I would like to know because I am releasing a package - https://github.com/stla/brr - and I propose to install it with `install_github('brr', 'stla', build_vignettes=TRUE)`. 
BTW this is my first package to be released, I really thank RStudio for providing all these user-friendly tools to build a package !

**Comment by jjallaire** [comment]
It's a result of the version of RStudio and specifically the version of
QtWebKit we were using in the older version.

**Comment by stla** [comment]
Does that mean that someone using R but not RStudio would not be able to build the vignette of my package ?

**Comment by jjallaire** [comment]
No, this just has to do with previewing (i.e. the browser used to view the
vignette). It has no impact on building the vignette. Note however that
pandoc is required to build the vignette using the default formatting.
While pandoc comes with RStudio a system that doesn't have it would need to
install it another way (see:
https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md)

There is one saving grace though: if pandoc is not installed then the
markdown package is used which still produces the vignette however it just
doesn't look quite as nice.

**Comment by stla** [comment]
Stupid of me, I was still confused between previewing and viewing in the browser.
Thanks for the explanations. I think there are problems with the Mathjax rendering if the markdown package is used.

**Comment by stla** [comment]
I have just tried to install the latest RStudio but the `deb` does not work. 
I will do my vignette in pdf with lualatex because I have utf-8 symbols in monofont, and with html that does not work correctly on Windows.
Anyway I think we could close this issue, which is surely due to the RStudi version.
