### ISSUE TITLE
Greek characters garbled when self_contained = FALSE

### ISSUE THREAD

**Issue by yihui** [rstudio/rmarkdown#464]
Originally reported at https://github.com/rstudio/DT/issues/121. I simplified the repro:

``````

---
title: "self_contained issue"
output:
  html_document:
    keep_md: yes
    self_contained: no

---

## Εισαγωγή

```{r}
library(htmltools)
em('Συντελεστής')
```
``````

Session info:

``` r
> Sys.setlocale(,'Greek')
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Greek_Greece.1253  LC_CTYPE=Greek_Greece.1253   
[3] LC_MONETARY=Greek_Greece.1253 LC_NUMERIC=C                 
[5] LC_TIME=Greek_Greece.1253    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_0.7.1

loaded via a namespace (and not attached):
[1] htmltools_0.2.8 tools_3.2.1     digest_0.6.8   
```

FYI

``` r
> iconv(enc2utf8('Συντελεστής'), to = 'Windows-1253')
[1] "Ξ£Ο…Ξ½Ο„ΞµΞ»ΞµΟƒΟ„Ξ®Ο‚"
```

**Comment by stla** [comment]
Hello. I intended to open an issue to ask a UTF8-related question. When I type that in the console under Windows, it works fine:
```
> intToUtf8(981L)
[1] "ϕ"
```
But in a `Rmd` file I get:
```
## [1] "<U+03D5>"
```

**Comment by yihui** [comment]
@gd047 Your issue should be solved by [updating all R packages](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) now.

@stla Your issue is different. It is the same as https://github.com/r-lib/evaluate/issues/66 and https://github.com/r-lib/evaluate/issues/59.

**Comment by gd047** [comment]
Thanks. My problem had been solved since you published an answer here
https://github.com/rstudio/rmarkdown/issues/686#issuecomment-231557101
<https://mailtrack.io/trace/link/bb5e2374d02ebb56a6b0ee3cb087c7e9b0fec854?url=https%3A%2F%2Fgithub.com%2Frstudio%2Frmarkdown%2Fissues%2F686%23issuecomment-231557101&userId=322274&signature=bc703540d1e83900>



‌

**Comment by yihui** [comment]
Ah, great. I had forgotten that :)
