### ISSUE TITLE
open connection error when using relative paths in Rmarkdown

### ISSUE THREAD

**Issue by benjaminMears** [rstudio/rmarkdown#465]
I often structure my Rmarkdowns in the following way:

MyPackage
- R/
  - R files
- Rmarkdown/
  - Rmarkdown files
- tests/
- DESCRIPTION
- NAMESPACE

In the Rmarkdown, the package is then loaded using devtools::load_all('..').  This allows most of the logic in the Rmarkdown to be in a package and tested.

Starting with commit eed788ee8f275d, the following error occurs when doing this:

Warning in file(con, "r") :
  cannot open file '/private/var/folders/yn/qtbpjjlj4lb5yvjyxq_v52nw0000gn/T/rmarkdown/629c30d4d0fe92495258901301ba94a3/rmd_629c30d4d0fe92495258901301ba94a3.html': No such file or directory
Error in file(con, "r") : cannot open the connection

If I use devtools::load_all with an absolute path, I do not see this problem.

**Comment by yihui** [comment]
Could you provide a minimal, self-contained, and reproducible example as a Github repo or a zip archive?
