### ISSUE TITLE
knit html image urls from dataframe

### ISSUE THREAD

**Issue by mobcdi** [rstudio/rmarkdown#468]
Is it possible to supply the image url from a dataframe so that a number of images are pulled from the internet and displayed as image in the end document?

I tried inlining the code as below
```
`r ![Twitter Profile images](TwitterProfilesDF$profileImageUrl)` 
and
![Twitter Profile images](`r TwitterProfilesDF$profileImageUrl`)
```
Do I need to loop over the dataframe while inlining and building up the markdown some how?

**Comment by yihui** [comment]
I don't think you need a loop. You can just paste the images together like this:

    `r paste0('![Image](', URLs, ')', collapse = '\n')`

**Comment by mobcdi** [comment]
Great thanks. It worked a treat
