### ISSUE TITLE
error = T

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#471]
Today I noticed that I cannot easily override the "new" `error = F` default in rmarkdown from outside the render function, by simply calling `opts_chunk$set(error=TRUE)`. The workaround I use now is to call `html_document()` first, and then set `output_format$knitr$opts_chunk$error = TRUE` (e.g. [here](https://github.com/rubenarslan/formr/blob/master/R/rmarkdown_options.R#L26)).

I want to suggest that this be simplified, i.e. through an option like `break_on_error` in the render function. 

Once that option exists, it would be great if the new options gear icon next to the "Knit HTML" button in Rstudio had this as a checkbox, since the error handling that rmarkdown already has sometimes doesn't meet my needs (see also https://github.com/rstudio/rmarkdown/issues/381). Also, I sometimes prefer to keep errors in my report (e.g. if I run a bunch of models and one does not converge, that's something I want in my report in some cases).

**Comment by jjallaire** [comment]
@yihui  I thought that it was possible to restore the old behavior via `opts_chunk$set(error=TRUE)`. Is that not true? If it used to be true was there something we changed in rmarkdown or knitr recently?

**Comment by rubenarslan** [comment]
@jjallaire No, that works, I wanted to specify it from "outside the render function", i.e. I meant without altering the input by adding a chunk containing `opts_chunk$set(error=TRUE)` to the beginning.

**Comment by jjallaire** [comment]
Okay, thanks for the clarification!

**Comment by yihui** [comment]
Right, it is not possible to change the `error` option outside `render()`, since it will be set to `FALSE` unconditionally in `render()`.

Actually there is an undocumented hacky way in knitr, but I'm not sure if I should ever mention it...

**Comment by rubenarslan** [comment]
It would seem more logical if render actually took all opts_chunk and _knit from the output format, i.e. if these options were set in the output format. That way it would be possible to have a std output format with the desired error handling or e.g. tidy settings.

**Comment by jjallaire** [comment]
If you look at the sequencing of the code it should be possible to have a
custom output format specify whatever behavior it wants for knitr chunk
options and have it override the built in defaults:

https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L210-L245

Does that sound like what you are looking for?

**Comment by rubenarslan** [comment]
Yes, that's what I'm doing here: https://github.com/rubenarslan/formr/blob/master/R/rmarkdown_options.R#L26
but it necessitates making a custom output format, because html_document does not accept an argument for knitr chunk options (AFAICT).

Really, my suggestion is only that this be simplified a little more, for easier usage within Rstudio, because in many cases I think the old error handling was better (for my purposes).

**Comment by jjallaire** [comment]
Okay, understood.

One other possible workaround if you want to control the behavior from
render is to use Rmd parameters (
http://rmarkdown.rstudio.com/developer_parameterized_reports.html) to set
the behavior then just pass the desired behavior in the call to render
(e.g. render("foo.Rmd", params = list(knitr_error = TRUE)). That requires
your controlling the Rmd and annotating every Rmd with that parameters
which I understand might be either not practical or onerous.
