### ISSUE TITLE
feature request:  code highlighting

### ISSUE THREAD

**Issue by rpruim** [rstudio/rmarkdown#476]
This is already possible when creating ioslides presentations in RStudio, but it would be nice to have available more generally.  At a minimum the ability to highlight selected lines would be useful.  If smaller code elements (a variable or argument name/argument value pair, etc.) could be highlighted, that would be a bonus.

Possible syntax?

``` r
foo ** <- function (** a = 7 **){**
  a^2
**}**
```

to highlight the outline of creating a function.

But line oriented highlighting (as in ioslides) make the code easier to read and makes it easier to execute on line of code in a code chunk.

**Comment by yihui** [comment]
This? http://rmarkdown.rstudio.com/ioslides_presentation_format.html#code_highlighting

An alternative is the xaringan package: https://slides.yihui.name/xaringan/#28
