### ISSUE TITLE
ioslides do not render in OSX

### ISSUE THREAD

**Issue by homerhanumat** [rstudio/rmarkdown#477]
The following issue occurs for only on my MacPro (OSX Yosemite, most recent version).  When I knit the sample R Markdown document to ioslides, I get:

```
/usr/local/bin/pandoc +RTS -K512m -RTS test.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.html --smart --email-obfuscation none --self-contained --variable transition=0.4 --template /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/ioslides/default.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --variable ioslides-url=/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/ioslides/ioslides-13.5.1 
pandoc: Could not fetch /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/ioslides/ioslides-13.5.1/fonts/OpenSans.ttf) format('truetype
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/ioslides/ioslides-13.5.1/fonts/OpenSans.ttf) format('truetype: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted
```

I checked and the file in question does exist.  Perms are such that everybody can read; admin and I can read and write.  `rmarkdown` version is the up-to-date from the GitHub repo.

**Comment by josiekre** [comment]
I have this same problem happening right now.

```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin14.3.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] htmltools_0.2.6 tools_3.2.1     yaml_2.1.13     rmarkdown_0.7   digest_0.6.8
```

My error looks like this. I replaced my home directory details with `[...]`.

```
pandoc: Could not fetch [...]/Library/R/3.2/library/rmarkdown/rmd/ioslides/ioslides-13.5.1/fonts/OpenSans.ttf) format('truetype
[...]/Library/R/3.2/library/rmarkdown/rmd/ioslides/ioslides-13.5.1/fonts/OpenSans.ttf) format('truetype: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted
```

This file exists.

**Comment by jmcphers** [comment]
Sounds like this error:

https://github.com/jgm/pandoc/issues/2224

Are you both using Pandoc 1.14? If so, does 1.13.1 work?

**Comment by homerhanumat** [comment]
From my terminal the command `pandoc --version` shows version 1.14.0.1,  I don't recall installing pandoc separately when setting up the machine, so assumed that it came along with R Studio:  guess not!   I'll try to figure out how to get 1.13.1 on a Mac, and let you know what happens.

**Comment by homerhanumat** [comment]
Sure enough, Rmd knits ot ioslides with pandoc 1.13.1 installed.

**Comment by homerhanumat** [comment]
It occurs to me that others may want to know how to get pandoc 1.13.1.  Go here:

[https://github.com/jgm/pandoc/releases/tag/1.13.1](https://github.com/jgm/pandoc/releases/tag/1.13.1)

and download the .pkg file at the bottom of the page.
