### ISSUE TITLE
feature request: map "jk/kj" to esc in VIM mode

### ISSUE THREAD

**Issue by Januzz** [rstudio/rmarkdown#488]
It would be great if one could use a custom key combination to change modes in VIM editing mode. Apparently this should be possible with the ACE editor, but has to be handled within the application, see https://github.com/ajaxorg/ace/issues/2616

**Comment by jmcphers** [comment]
This repo is for the R markdown R package; RStudio feature requests can be posted here:

https://support.rstudio.com/hc/communities/public/topics/200022758-Feature-Requests

We're working on support for user keybindings; you can try it out at https://dailies.rstudio.com/. However, as far as I know these aren't Vim mode aware so it may not be possible to bind `jk` as you want.
