### ISSUE TITLE
Very slow (impossible?) to render word_document with large data display.

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rmarkdown#490]
I noticed this in a sales webinar we gave today and distilled it down to this example. The file below takes a very long time to render as a word document. In fact, it might not render at all (I haven't waited long enough).

    ---
    output: word_document
    ---
    ```{r}
    1:10000
    ```

However, it renders quite fast as an html

    ---
    output: html_document
    ---
    ```{r}
    1:10000
    ```

or pdf document. 

    ---
    output: pdf_document
    ---
    ```{r}
    1:10000
    ```

I'm using rmarkdown 0.7 and RStudio IDE 0.99.467

**Comment by jjallaire** [comment]
This is likely a pandoc issue. Here's what I recommend:

1) Get a plain .md version of the file (e.g. by using keep_md)

2) Call plain pandoc with that file as input and docx as output, verifying
that you still see the performance problem

3) Post that issue to the pandoc repo on GitHub

**Comment by garrettgman** [comment]
I was able to recreate the poor performance with plain pandoc. I added the issue to pandoc's repo, https://github.com/jgm/pandoc/issues/2356

**Comment by jjallaire** [comment]
Great! Let's hope there is an easy fix on the pandoc side.

**Comment by yihui** [comment]
@garrettgman Did you forget to include the R output in ```` ``` ```` in your markdown example? Like this

    ```
    ## [1] 1 2 ....
    .....
    ````

**Comment by garrettgman** [comment]
@yihui Yes, I missed the ```s when I copied and pasted. Thank you for catching that. I added them back into https://gist.github.com/garrettgman/ce50c30831de0346c66a

**Comment by garrettgman** [comment]
John McFarlane found the source of the problem and fixed it over at https://github.com/jgm/pandoc/issues/2356

**Comment by jjallaire** [comment]
Fantastic!

On Mon, Aug 10, 2015 at 1:57 PM, Garrett Grolemund <notifications@github.com
