### ISSUE TITLE
Nested render confuses RStudio re: which document to display

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#491]
I need to render a child document inside a chunk from a parent document.

It is not a situation where the `child =` chunk option helps. It is like what @lcolladotor describes in [this comment on issue 248](https://github.com/rstudio/rmarkdown/issues/248#issuecomment-118623178): I'm writing `README.Rmd` for a package (the parent) and a function in the package calls `rmarkdown::render()` (on some child document) and I want to show a working example. The same thing would arise for a vignette.

I successfully adapted the `devtools::clean_source()` trick from #248 but find that when I use the "Knit" button in RStudio to render the parent `README.Rmd` the thing that pops up is the render result from knitting the child.

If you open [this gist](https://gist.github.com/jennybc/1f747c5bb84aa9be9c3c#file-2015-08-06_nested-render-confuses-rstudio-rmd) in RStudio and click the "Knit" button, you will see the rendered child `foo.md` (or at least I do!), not an HTML preview of the gist itself. The parent document is being rendered to HTML, it's just not served up by the RStudio IDE.

**Comment by jennybc** [comment]
Now I wonder whether I should have filed this here or on the RStudio IDE ...

**Comment by jjallaire** [comment]
The issue is that RStudio is watching the output stream from the render to
figure out when (and which) output document to display. If you can manage
to suppress the output from the child render (i.e. via capture.output) I
think the preview will behave as you expect.

**Comment by jennybc** [comment]
Thanks @jjallaire. I have updated [the gist](https://gist.github.com/jennybc/1f747c5bb84aa9be9c3c#file-2015-08-06_nested-render-confuses-rstudio-rmd) to use capture.output but RStudio's display behavior does not change. Here's what the wrapper chunk looks like now:

```r
writeLines('output <- capture.output(rmarkdown::render("foo.R", "md_document"))',
           "render_wrapper.R")
devtools::clean_source("render_wrapper.R", quiet = TRUE)
file.remove("render_wrapper.R")
```

Did I misunderstand you?

**Comment by jjallaire** [comment]
I think that's because the output in question is emitted as a message
rather than as standard output.

That affords us a simpler workaround: you can get rid of the whole
capture.output business and just add quiet = TRUE to the call to
rmarkdown::render.

**Comment by jennybc** [comment]
That does it! Thanks. [Gist](https://gist.github.com/jennybc/1f747c5bb84aa9be9c3c#file-2015-08-06_nested-render-confuses-rstudio-rmd) now reflects a successful nested render, with expected RStudio display behavior.

**Comment by jjallaire** [comment]
Great! Glad we got to the bottom of that :-)

**Comment by mclaeysb** [comment]
@jennybc @jjallaire How would this work if you want to pass params with render?
