### ISSUE TITLE
Feature request: Option to remove YAML from output markdown documents 

### ISSUE THREAD

**Issue by thercast** [rstudio/rmarkdown#496]
I've been utilizing the `md_document` output option for many of my R-markdown documents in addition to the other output formats.  I would like to do some additional post processing of these markdown documents to other formats to conform to my company's documentation requirements, and I have to manually delete the YAML front matter before supplying the markdown output to another script for further processing.  I looked through the documentation of rmarkdown as well as pandoc and did not find any custom option to remove YAML from output markdown files, so I wondered if this could be something incorporated in a future version of the package.  Thanks for all of your excellent and innovative work!

**Comment by yihui** [comment]
I don't remember when this was implemented, but at least `preserve_yaml = FALSE` is the default option for `md_output()` in the current version of rmarkdown:

```yaml
output: 
  md_document:
    preserve_yaml: false
```

**Comment by rand-asswad** [comment]
This is very useful! This can also be useful for `html_fragment` format as one might prefer to use Rmd instead of jekyll's markdown to html conversion.

For now I have written my own script and added a hook, which works fine, but just saying.

**Comment by chigix** [comment]
Is this option supported in `html_fragment` output as well?

**Comment by cderv** [comment]
@rand-asswad @chigix 
as this issue is already close, can you open a new one to detail the feature request, linking to this one ? 

I am not sure to see how keeping the yaml header relates to html generation ? 🤔 but i may be missing something...
 
Thanks.
