### ISSUE TITLE
Weird warning produced in Rscript -e "rmarkdown:run()"

### ISSUE THREAD

**Issue by caijun** [rstudio/rmarkdown#497]
I run following command in Terminal on Mac OS X Yosemite

```
Rscript -e "rmarkdown::run(dir = \"/Users/tonytsai/Documents/R/packages/rmarkdown\", shiny_args = list(port=3120, launch.browser=TRUE))"
```

It successfully runs the shiny app. Then I stop the interactive rmarkdown document by entering `CTRL+C`, which prints the following warning

```
Warning message:
In normalizePath(file, winslash = "/") :
  path[1]="index.Rmd": No such file or directory
```

However, `index.Rmd` does exist.

```
ls /Users/tonytsai/Documents/R/packages/rmarkdown |grep index.Rmd
index.Rmd
```

Though it's a warning, but I would like to know how it produced and how to avoid it.

**Comment by yihui** [comment]
Not sure why this happened or whether it still happens, but I'd recommend you to cd to the directory before calling Rscript. Tricky bugs often appear when dealing with absolute full paths in rmarkdown...

```bash
cd /Users/tonytsai/Documents/R/packages/rmarkdown && \ 
  Rscript -e "rmarkdown::run(shiny_args = list(port=3120, launch.browser=TRUE))"
```
