### ISSUE TITLE
render with intermediates_dir fails with images

### ISSUE THREAD

**Issue by petrelharp** [rstudio/rmarkdown#500]
The `pandoc` call fails because the `_files` directory is not put in `intermediates_dir`, so `pandoc` can't find the images.

MWE:
`test.Rmd`:

``````
```{r plot}
plot(1)
```
``````

Then, calling

```
render("test.Rmd", intermediates_dir="temp")
```

fails with

```
# pandoc: Could not fetch test_files/figure-html/plot-1.png
```

This is with the github version of rmarkdown (pulled just now).

Changing the relevant line in `render` to

```
files_dir <- intermediates_loc( rmarkdown:::knitr_files_dir(basename(output_file)))
```

fixes it in my simple case, but might break other use cases.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
