### ISSUE TITLE
linkcolor, urlcolor in beamer output

### ISSUE THREAD

**Issue by jabranham** [rstudio/rmarkdown#503]
Currently there is no (easy) way to configure the color of links (url or otherwise) when using beamer output. This is supported in pdf output (latex), so hopefully should be easy to implement.

**Comment by pablogregori** [comment]
Dear @jabranham , I have today the same concern. Did you get any feedback outside Github? Thanks for reading!

**Comment by jabranham** [comment]
@pablogregori  - No, and AFAIK it's still not possible

**Comment by mihiriyer** [comment]
I've been marking-up links like this:
[\textcolor{blue}{U.S. Census Bureau webiste}](http://www.census.gov/acs)

This will color the link text blue and nothing more but at least the text will stick out and people will be able to see that it is a link.

**Comment by yihui** [comment]
This is similar to #362. Basically you have to:

1. Use the option `citation_package: natbib` for the `beamer_presentation` format.

1. Specify these colors in the YAML metadata.
