### ISSUE TITLE
Inline citations: 'et al' not italic in compiled document.

### ISSUE THREAD

**Issue by TomHarrop** [rstudio/rmarkdown#508]
Hello,

Running into an issue with inline citations using `Rstudio 0.99.473` and `rmarkdown 0.8`. I am cross-posting this from [my question on StackOverflow](https://stackoverflow.com/questions/32357593/italicising-et-al-in-inline-citiations-in-rmarkdown) which hasn't been answered. Here is some sample code:

```

---
title: "testCite"
output:
  html_document:
    keep_md: true
csl: the-plant-journal.csl
bibliography: test.bib

---

The fly *Drosophila melanogaster* is one of the most intensively studied organisms in biology [@Adams:2000tj].

According to @Adams:2000tj, the fly *Drosophila melanogaster* is one of the most intensively studied organisms in biology.
```

As you can see from the following `html`, this is getting me italic 'et al' in the normal citation but not in the inline one (or in the bibliography, I have just noticed):

![grab](https://cloud.githubusercontent.com/assets/5971975/9741259/b5342974-5659-11e5-8049-6be3ceca2466.png)

I am using a `csl` file from [the Zotero repository](http://www.zotero.org/styles/the-plant-journal). The contents of the bibliography file (`test.bib`) follows:

```
@article{Adams:2000tj,
author = {Adams, MD and Celniker, SE and Holt, RA and Evans, CA and Gocayne, JD and Amanatides, PG and Scherer, SE and Li, PW and Hoskins, RA and Galle, RF and George, RA and Lewis, SE and Richards, S and Ashburner, M and Henderson, SN and Sutton, GG and Wortman, JR},
title = {{The genome sequence of \emph{Drosophila melanogaster}}},
journal = {Science},
year = {2000},
volume = {287},
number = {5461},
pages = {2185--2195},
affiliation = {Celera Genom, Rockville, MD 20850 USA},
language = {English},
read = {Yes},
rating = {0},
date-added = {2012-03-02T23:35:05GMT},
date-modified = {2015-07-28T15:38:34GMT},
abstract = {The fly Drosophila melanogaster is one of the most intensively studied organisms in biology...},
url = {http://www.sciencemag.org/content/287/5461/2185.short}
}
}
```

Thanks for reading and please let me know if more details are required.

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] htmltools_0.2.6 tools_3.2.2     yaml_2.1.13     rmarkdown_0.8   digest_0.6.8   
```

**Comment by yihui** [comment]
The citations / bibliography are not generated directly by rmarkdown but pandoc / pandoc-citeproc. I recommend you to ask this question on StackOverflow instead, using tags `r`, `rmarkdown`, `csl`, `pandoc`, and `pandoc-citeproc`. We cannot afford investigating a specific csl file. Thanks!
