### ISSUE TITLE
Plotting in `for` loop after second-level header

### ISSUE THREAD

**Issue by tzerk** [rstudio/rmarkdown#509]
I do not know whether this is a bug or just my lack of understanding. Consider the situation where I want to create a PDF file that includes a multitude of similar plots. To get multiple plots side by side I use `par(mfrow = c(3, 2))`. In the minimal example below the number of plots is 18, so given the specified layout R supposedly creates three high-level plots. Here, I use `fig.height=7` just to force each plot on a new page. 

When running the example below, however, the subsection `## Plot` is on the second page of the document and the first and second high-level plot is printed to the same page (the second not being visible as it extends beyond the page).

```r
---
title: "Multiple figures after header"
output: pdf_document
---

# Section

Some text

## Plot

```{r, echo=FALSE, fig.height=7}
par(mfrow = c(3, 2))
for (i in 1:18) plot(i, main = i)
`` `
```

This **only** occurs if there is standard text in of the sections. When removing `Some text` the following example works just fine:

 ```r
---
title: "Multiple figures after header"
output: pdf_document
---

# Section

## Plot

```{r, echo=FALSE, fig.height=7}
par(mfrow = c(3, 2))
for (i in 1:18) plot(i, main = i)
`` `
```

Here, section `## Plot` is on the first page and each of the three plots are on a separate page. As a workaround I found that encapsulating the text in the markdown syntax for links (`[text](link)`) works as intended:

```r
---
title: "Multiple figures after header"
output: pdf_document
---

# Section

[Some text]()

## Plot

```{r, echo=FALSE, fig.height=7}
par(mfrow = c(3, 2))
for (i in 1:18) plot(i, main = i)
`` `
```

I played around with some of the plot related chunk options and also tried `layout()` instead of `par(mfrow)`, but to no avail.  This also occurs when removing the layout options, so that each of the 18 plots is expected to be on a new page. I also observed that removing the second level header (here: `## Plot`) solves the problem or, in other words, that there must be no second level header before plotting in a `for` loop.  

`sessionInfo()`
```
R Under development (unstable) (2015-08-17 r69109)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] htmltools_0.2.6 tools_3.3.0     yaml_2.1.13     rmarkdown_0.8   digest_0.6.8   
```

**Comment by yihui** [comment]
This is not a bug. It is just how LaTeX works. I think the problem should go away if you add blank lines between the figures, e.g.

```r
par(mfrow = c(3, 2))
for (i in 1:18) {
  plot(i, main = i)
  cat('\n\n')
}
```

Previously your LaTeX output would be like this

```latex
\section{Section}\label{section}

Some text

\subsection{Plot}\label{plot}

\includegraphics{foo_files/figure-latex/unnamed-chunk-1-1.pdf}
\includegraphics{foo_files/figure-latex/unnamed-chunk-1-2.pdf}
\includegraphics{foo_files/figure-latex/unnamed-chunk-1-3.pdf}
```

If you add blank lines, it will become

```latex
\section{Section}\label{section}

Some text

\subsection{Plot}\label{plot}

\includegraphics{foo_files/figure-latex/unnamed-chunk-1-1.pdf}

\includegraphics{foo_files/figure-latex/unnamed-chunk-1-2.pdf}

\includegraphics{foo_files/figure-latex/unnamed-chunk-1-3.pdf}
```

Now each figure will be a separate paragraph, and LaTeX will move the second figure to the next page when it sees the current page cannot hold it. In the previous case, all three figures are in the same paragraph, and it seems to be too late for LaTeX to realize that the second figure does not fit the page (after the second figure is inserted into the page, it knows the current page cannot hold more content, so it opens a new page for the third figure).

**Comment by tzerk** [comment]
Thanks for your reply yihui and indeed `cat("\n\n")` did the trick, another lesson learned about LaTeX. While I still do not quite understand why removing the text and having no blank lines between multiple `\includegraphics{}` also works, this here is obviously not the right place to ask. Many thanks for your help and sorry for the false alarm.

**Comment by jmichaelgilbert** [comment]
Understand this is closed, but I am having a similar issue and the cat() function does not resolve. What's strange is my friend can run my exact code, same version of R, R Studio, packages, etc. and it works. I checked our R Markdown settings, and they're identical as well. The only difference is he's on a OSX while I'm on Windows 7.

The issue is related to an `lm` object and the `plot.lm` - but regardless of using `ask = F` or adding a second loop to parse through each, the issue still occurs.

```{r setup.R, message = F, warning = F}
# Clear workspace
rm(list=ls())

# Load packages
library(knitr)
library(MASS)
library(RCurl)
```

```{r include = F}
par(mfcol = c(2, 2))
```

```{r Ex15d1, indent = "    ", fig.width = 8, fig.height = 8}
# Load and assign data
data(Boston); Boston

# Create loop for results
for (i in names(Boston)[2:14]){
    for (j in 1:4){
        plot(lm(as.formula(paste("crim ~", i, "+I(", i, "^2)", "+I(", i, "^3)")), 
                data = Boston), main = paste("Variable:", i), which = j)
        cat("\n\n")
    }
    cat("\n\n")
}
```

```{r include = F}
par(mfcol = c(1, 1))
```

The plots are stripped of their labels / titles when I run this, even though they show up in R Studio. As mentioned, my friend can execute and produce the plots without issue. Can share my entire code on GitHub if you'd like, or otherwise include output images.

Michael

**Comment by rpalloni** [comment]
@yihui is it valid also for beamer presentation?
I tried to follow your suggestion but i can't figure out why this is not working for me.
Here there is the code and the output attached

# 1.4 Rate of project selection and expenditure declared* by priority axis 

```{r echo=F}
source('Section_1/algo_1_4.R')
```
```{r figure_1_4, fig.width = 12, fig.height = 5}
for (i in 1:19){
  print(p[[i]])
  cat("\n\n")
}
```

where p is a list of 19 ggplot2 plots calculated in the sourced file algo_1_4.R

![nonewpage](https://user-images.githubusercontent.com/17080117/27866402-7b065bb0-6196-11e7-99b7-406524d074a1.PNG)
