### ISSUE TITLE
Inconsistency with using `initial-scale=1` and `initial-scale=1.0`

### ISSUE THREAD

**Issue by daattali** [rstudio/rmarkdown#511]
In [`html_dependencies`](https://github.com/rstudio/rmarkdown/blob/79f595b6dbcc28703a6136d2afafc9a11c6b6d49/R/html_dependencies.R#L35) the HTML uses `initial-scale=1`, while in [`default.html`](https://github.com/rstudio/rmarkdown/blob/3d46213d750fd4ebb83e73d0df357f081c73f49f/inst/rmd/ioslides/default.html#L17) it uses `initial-scale=1.0`.

I didn't want to fix this myself because I'm not sure if there's a difference, but I'm pretty certain it's the same

**Comment by jjallaire** [comment]
This is fine (both are valid). In the first case we took the code from the Bootstrap 3.1 examples and in the second case we took the code from the default ioslides template from Google. We could reconcile them but I'd just as soon leave code from vendors "as-is".

**Comment by daattali** [comment]
I pointed it out because on a project I'm working on, every document I render gets the `1.0` version but when others render it (on a different OS) its `1`. Not a big deal, just adding some extra noise to the commits.  It's possible that we're not using the same rmarkdown version or maybe for some reason the OS different matters, not sure why this is.  I just wanted to state my reasoning for filing such a seemingly nonimportant bug - no need to reply any further if there is nothing useful to add.

**Comment by jjallaire** [comment]
Okay, I changed things so that we always use the "1" form: https://github.com/rstudio/rmarkdown/commit/71c6cda823fc0c58eeb6f51dba3187d24786b657

**Comment by daattali** [comment]
thanks :)
