### ISSUE TITLE
There should be a way to force path separators to be unix style even when compiling on Windows

### ISSUE THREAD

**Issue by daattali** [rstudio/rmarkdown#512]
I'm currently trying to update some pages on a website that is a collaboration between several people where I'm the only Windows user.

In our `_output.yaml` we have a line:

```
css: libs/local/nav.css
```

When any of the other collaborators render a markdown file, the resulting HTML has:

```
<link rel="stylesheet" href="libs/local/nav.css" type="text/css" />
```

But when I render, I get

```
<link rel="stylesheet" href="libs\local\nav.css" type="text/css" />
```

It's probably not going to make a difference in practice, but it's not ideal that every time I commit a file, the diff will show all these lines as changed, and every time someone else renders that file it will again show a change in that file.

I would like to be able to force rmarkdown to add unix style slashes even when I render on Windows.

**Comment by jjallaire** [comment]
Ouch, this is a bummer. My concern about making a change here is that pandoc can be very finicky about how paths are represented (sometimes on Windows it *requires* that a path have backslahes rather than forward slashes). The current code reflects our iteration into a set of behavior that seems to make pandoc happy with all formats and all platforms so a change has a reasonably high likelihood of causing a downstream problem with pandoc.

**Comment by daattali** [comment]
I can definitely understand that. But I think if the user explicitly wants to use forward slashes, it assumes they know the consequence and are probably not intending for the output to be used on Windows. If I want to only convert (but not use) the document on Windows, I don't think it will cause problems.  I can get around the issue by adding my own search-n-replace after rendering, so it's not critical, but could be a useful feature to support at some point in the future IMO

**Comment by jjallaire** [comment]
Unfortunately the matrix of rendering/serving variations is huge (self-contained vs. non-self-contained, stock Rmd vs. runtime:shiny, ioslides vs. other formats, etc. etc.) and we have been playing whack-a-mole with all these variations (to avoid pandoc errors) for years. This isn't to say that you are wrong, just that any change we make now (in a state where pandoc rendering seems to always work correctly everywhere) will almost certainly break something else. As a result we are cautious about these changes.
