### ISSUE TITLE
Using slash (/) as separator in paste function breaks the document

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rmarkdown#514]
This was reported here:

https://rstudioide.zendesk.com/agent/tickets/14562

- Include the following line in an RMarkdown  shiny document
```
paste("a", "b", "c", sep= "/")
```

- Running the document causes this error:
```
Error: cannot open the connection
```

This happens with RMarkdown version 0.8. It worked fine in versions 0.6 and 0.7.

**Comment by yihui** [comment]
I feel this is a similar issue as #447. `"/"` might be treated as the root directory.

**Comment by jjallaire** [comment]
@jmcphers This is the commit that appears to have broken things: https://github.com/rstudio/rmarkdown/commit/eed788ee8f275d7e31aa03c7349c27c53665d8c2

Any insight as to what the problem might be?
