### ISSUE TITLE
ioslides presentation slide numbers not appearing in final html

### ISSUE THREAD

**Issue by dnegrey** [rstudio/rmarkdown#517]
When creating an ioslides presentation in R markdown, I am finding that the slide numbers do not appear in the final html file. They are present when you view the file by clicking on it in the RStudio "Files" pane, and then clicking "View in Web Browser", but emailing the standalone file or opening it from another file browser results in not being able to see the slide numbers. Below is a minimally reproducible example. I am using R 3.2.2 on CentOS 6.7, and have version 0.8 of the rmarkdown package installed.

    # R version 3.2.2 (2015-08-14) -- "Fire Safety"
    # Copyright (C) 2015 The R Foundation for Statistical Computing
    # Platform: x86_64-redhat-linux-gnu (64-bit)

    # load package (version 0.8)
    library(rmarkdown)
    # create Rmd file
    x <- c("---",
           "title: 'test'", 
           "output: ",
           "    ioslides_presentation",
           "---",
           "",
           "## Slide One",
           "",
           "## Slide Two")
    write(x, "test.Rmd")
    # render html file
    render("test.Rmd")

**Comment by JasonAizkalns** [comment]
I am experiencing similar issues with Windows 7, R Version 3.2.2 (64-bit), version 0.8, and Chrome.

**Comment by dnegrey** [comment]
I forgot to mention that I am also using Chrome. I just tested the result of my example (test.html), and the slide numbers do actually render in IE and Firefox when opening it as a standalone file. I would like to see if there's a resolution here for Chrome, though, as the majority of my organization uses that as their default browser. Thanks.

**Comment by aashanand** [comment]
This issue is also being discussed here on [stackoverflow](http://stackoverflow.com/questions/32478437/rmarkdown-ioslides-slide-number-does-not-show-in-browser?noredirect=1#comment53536025_32478437).

**Comment by hrbrmstr** [comment]
A potential workaround is to run `Rscript -e 'servr::httd()' -p9999` in the folder of the HTML file for the slide deck then browse to `http://localhost:9999/slidedeckfilename.html`. This gets around the Chrome security error issue.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/718e101d8bc095e50d25170ae0a9804c2dd1b18e
