### ISSUE TITLE
Is it possible to configure per-user or per-Project default YAML header?

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#518]
Let's say you always want to keep intermediate markdown. Or any of the other choices faciliated by "Output Options ..." for that matter.

Is there a way to express this so that _File > New file > R Markdown ... OK_ produces YAML with user-specified defaults, such as `keep_md: true`? Is a custom document template the best way to approximate this today?

Sidebar: when retaining markdown via that _(gear thing)  > Output Options... > Advanced > Keep markdown source_, it still inserts `keep_md: yes` but I sort of thought `true` was preferred syntax (I'm aware both work).

**Comment by jjallaire** [comment]
The best way to do this right now is indeed a custom document template.

I agree keep_md: true is preferrable, we'll change this in the next release.

**Comment by yihui** [comment]
Sounds like this is purely an RStudio IDE issue, so closing. If you have access to [FogBugz](https://rstudio.fogbugz.com), you can log the issue there.

That said, I'm not sure if `keep_md: true` is a better default. I rarely find it useful unless for debugging purposes. I understand that you may want to display it on Github, but given that we have got blogdown, you can render the HTML pages in any style you want (which can be much richer and pleasant than Github's rendering), and you can use automated services like Netlify (you only maintain source). I feel it is not necessary to maintain the intermediate Markdown output files any more.
