### ISSUE TITLE
Enable YAML support for R scripts

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#519]
Feature request: offer the same YAML authoring support for R scripts that is offered for Rmd. But, obviously, with `#'` prepended to each line. I guess one wouldn't want the upfront dialogue upon creation, but the YAML authoring stuff in _(gear thing) > Output Options..._ when editing Rmd would really nice.

Would a snippet be the best way to approximate this today?

**Comment by jjallaire** [comment]
Good suggestion, I don't think we can cram it into this release as we're
just about done with new feature work but we can do it the next release.

A snippet would indeed work well for this right now.

**Comment by jennybc** [comment]
This snippet is so satisfying. I have been pasting this out of a gist for a long time.

**Comment by yihui** [comment]
Again, this seems to be an IDE issue, so closing here...
