### ISSUE TITLE
Invalid rendering of hyperlink text that contains a URI scheme prefix

### ISSUE THREAD

**Issue by jonovik** [rstudio/rmarkdown#521]
I use RStudio and rmarkdown to generate a table of gene identifiers. It should display the gene name, but link to a web page with more information about the gene. For example, `[elovl4a](http://identifiers.org/ncbigene/393769)` renders as [elovl4a](http://identifiers.org/ncbigene/393769).

Some preliminary gene names contain a prefix and a colon that are on the [list of URI schemes](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml). This works fine here at GitHub and also in [MarkdownPad2](http://markdownpad.com/); for example, `[im:7139490](http://identifiers.org/zfin/ZDB-GENE-050522-453)` renders as [im:7139490](http://identifiers.org/zfin/ZDB-GENE-050522-453). However, with rmarkdown it renders invalidly as two nested `<a>` tags; see below. The error seems to happen with any URI scheme prefix, e.g. `gopher`, `http`, etc.

Example of the error, using an `im:` prefix, which is also used for instant messaging URIs:

```r
writeLines("[im:test this](http://example.org)", "test.Md")
rmarkdown::render("test.Md")
grep("<a href=", readLines("test.html"), value=TRUE)
## [1] "<p><a href=\"http://example.org\"><a href=\"im:test\" class=\"uri\">im:test</a> this</a></p>"
```

Example without error, using an `in:` prefix, which is not used in any URI scheme:

```r
writeLines("[in:test this](http://example.org)", "test.Md")
rmarkdown::render("test.Md")
grep("<a href=", readLines("test.html"), value=TRUE)
## [1] "<p><a href=\"http://example.org\">in:test this</a></p>"
```

My system setup is as follows:

```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Norwegian (Bokmål)_Norway.1252  LC_CTYPE=Norwegian (Bokmål)_Norway.1252    LC_MONETARY=Norwegian (Bokmål)_Norway.1252
[4] LC_NUMERIC=C                               LC_TIME=Norwegian (Bokmål)_Norway.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] htmltools_0.2.6 tools_3.2.1     rmarkdown_0.7   digest_0.6.8   
```

The generated pandoc command is:

`"C:/Program Files/RStudio/bin/pandoc/pandoc" test.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "%USERPROFILE%\Documents\R\win-library\3.2\rmarkdown\rmd\h\default.html" --variable "theme:bootstrap" --include-in-header "%USERPROFILE%\AppData\Local\Temp\Rtmp02nxtP\rmarkdown-str14d476f64986.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=%USERPROFILE%\Documents\R\win-library\3.2\rmarkdown\rmd\h\highlight"`

**Comment by yihui** [comment]
I think you can escape `:`, e.g. `im\:test`

**Comment by jonovik** [comment]
That's an excellent workaround, thank you very much.

```r
writeLines("[im\\:test if im\\:this works](http://example.org)", "test.Md")
rmarkdown::render("test.Md")
grep("<a href=", readLines("test.html"), value=TRUE)
## [1] "<p><a href=\"http://example.org\">im:test if im:this works</a></p>"
```

Also, I see that `im:` causes errors anywhere it appears. So I guess I'll replace `:` with `\:` throughout, inside link text.

**Comment by yihui** [comment]
Right, you can `gsub('im:', 'im\\:', your_text, fixed = TRUE)`
