### ISSUE TITLE
feature request: syntax highlighting in ioslides

### ISSUE THREAD

**Issue by uhlitz** [rstudio/rmarkdown#523]
R syntax highlighting is very poor in `ioslides`. only strings, integers and comments are recognised. Are there plans to bring full R syntax highlighting to `ioslides`, like it's the case in `Beamer` and `Slidy` templates (highlight option)?

**Comment by VincentGuyader** [comment]
any news about this issue ?

Regards

**Comment by yihui** [comment]
No. More on this: https://github.com/rstudio/rmarkdown/pull/404#issuecomment-326354500. I recommend you to try [xaringan](https://github.com/yihui/xaringan) instead.
