### ISSUE TITLE
Feature request: ability to specify yaml options (title, author, date) in render()

### ISSUE THREAD

**Issue by nkeriks** [rstudio/rmarkdown#524]
It's really nice that you can pass output_options through render, but I can't find a nice way to set the rest of the yaml (e.g., author/date/title) without directly sticking variables in the template (e.g., `output_options=list(panddoc_args=c('--variable', 'author:AUTHOR NAME'))`).

**Comment by yihui** [comment]
I think you should use `--metadata` instead of `--variable`: http://pandoc.org/MANUAL.html

In the future, please consider [asking questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) first, so you may not need to wait for so long to get an answer. Thanks!
