### ISSUE TITLE
Issue with style in MS Word

### ISSUE THREAD

**Issue by arturochian** [rstudio/rmarkdown#526]
I follow this example from SO [http://stackoverflow.com/questions/29440007/changing-word-template-for-knitr-in-rmarkdown?rq=1].
https://vimeo.com/110804387

It works perfect except for the title (The title has "normal style"). The example provided by @yihui  was 11 month ago, for that reason I think it could be an issue created from one commit...

PD: I'm using MS Office 2007. (Maybe it's related to that?)

My sessionInfo
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=Spanish_Peru.1252  LC_CTYPE=Spanish_Peru.1252   
[3] LC_MONETARY=Spanish_Peru.1252 LC_NUMERIC=C                 
[5] LC_TIME=Spanish_Peru.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.6 rmarkdown_0.8   tools_3.1.2    
[5] yaml_2.1.13

**Comment by arturochian** [comment]
It seems that this issue converts all-not normal style to normal style if it finds this style is modified. 
PD: Obviously, it doesn't affect to normal style text...

**Comment by arturochian** [comment]
I found something:
http://rmarkdown.rstudio.com/word_document_format.html

![image](https://cloud.githubusercontent.com/assets/4960935/10318226/1071dd9c-6c2e-11e5-9734-68262464c177.png)

**Comment by yihui** [comment]
I don't know. I was using MS Office 2013, and I don't have 2007, so I'm not sure if it makes a difference. Can you email me a copy of the Word document that you got from R Markdown? yihui [at] rstudio.com

**Comment by arturochian** [comment]
The file was sent. I tried with dotx extension but it fails :disappointed: 
PD: @yihui see this pull:  https://github.com/jgm/pandoc/pull/1968

**Comment by yihui** [comment]
I opened your doc with Word 2013 and the title has the `Title` style as expected (I can modify its style and it can be applied to new documents when it is used as the reference docx), so it appears that the Word version matters.

**Comment by arturochian** [comment]
could you email me with your word modified and the template? Maybe it could works now because it saved in word 2013

**Comment by arturochian** [comment]
It works!!! :smile:

**Comment by arturochian** [comment]
It seems it's related to the english version. I can't saved anything because it saved on word 2007 (and in spanish version).
See this
![image](https://cloud.githubusercontent.com/assets/4960935/10319840/f4854094-6c35-11e5-8a34-777fcb4ce945.png)

**Comment by yihui** [comment]
The latest preview version of RStudio has upgraded the built-in Pandoc (1.15.0.6 now), which might have solved this problem: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by arturochian** [comment]
Perfect! Thank you so much for your time and all R Studio Team for their wonderful packages and IDE!
