### ISSUE TITLE
Online documentation for retina figures in md_document does not match package documentation

### ISSUE THREAD

**Issue by lmullen** [rstudio/rmarkdown#528]
The [online documentation](http://rmarkdown.rstudio.com/markdown_document_format.html#figure-options) for `md_document` says that the default is to use retina figures:

> fig_retina Specifies the scaling to perform for retina displays (defaults to 2, which currently works for all widely used retina displays). 

However in `?rmarkdown::md_document`, the default argument is `fig_retina = NULL`.

```
> packageVersion("rmarkdown")
[1] '0.8'
```

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/97f890d94de21e7253d111577eb6ce628a34ed70
