### ISSUE TITLE
ioslides_presentation ignores custom css option

### ISSUE THREAD

**Issue by icarvalhosa** [rstudio/rmarkdown#531]
I am trying to customise the slides using css. However, ioslides seems to be ignoring whatever I put into the css file. 

The YAML is : 

```
---
output: 
  ioslides_presentation: 
    css: styles.css
    widescreen: true
---
```

I would like to change the hyperlink and header color for example with css:

```
a {
  color: red;
  text-decoration: none;
  border-bottom: 1px solid rgba(42, 124, 223, 0.5);
}

h2 {
  font-size: 45px;
  line-height: 65px;
  letter-spacing: -2px;
  color: #0000FF;
}
```

How can make ioslides use my style.css instead of the default without messing with the default css?
I would like to also change the iframe size when embeded in slides. Any suggestions on how i can do that?

Thanks a lot. :)

**Comment by yihui** [comment]
It works for me. Can you show a screenshot of your slide that didn't work? If you open the slides in Google Chrome, you can right-click on a hyperlink, Inspect Element, and see the styles applied to it. Then you will know if your styles are really applied, or overridden by other stylesheets.

![image](https://cloud.githubusercontent.com/assets/163582/10465264/8e3b71cc-71b3-11e5-8015-974fcf4f3323.png)


For `iframe`, I don't think there is anything special about it.

```css
iframe {
  width: specify_your_width_here;
  height: ...;
}
```
