### ISSUE TITLE
Feature request: scrollspy toc for rmarkdown reports

### ISSUE THREAD

**Issue by uhlitz** [rstudio/rmarkdown#539]
would be nice to optionally display the toc as a scrollspy sidebar, like implemented in [knitrBootstrap](https://github.com/jimhester/knitrBootstrap). 

[Example](https://rawgit.com/jimhester/knitrBootstrap/master/inst/examples/all.html)

**Comment by crsh** [comment]
Yes, this would be very nice.

**Comment by yihui** [comment]
I guess this has been implemented now: http://rmarkdown.rstudio.com/html_document_format.html#floating_toc
