### ISSUE TITLE
servr::make() JS inputs?

### ISSUE THREAD

**Issue by Nicktz** [rstudio/rmarkdown#544]
Hi all, I have the following concern which may either be a quick fix or a require some deeper digging on my side.

I am using Rmarkdown V2 to create html's that we can host online. The problem I have is that, using Rmarkdown v2, I can easily edit the .css scripts in the YAML directly, but I cannot find a way of telling Rmarkdown to use other JS, img and other folders to customize my html.

I specifically want to include html wigets, and as @yihui suggested in [this](https://github.com/yihui/knitr-jekyll/issues/8) thread, we should make use of server::make().

Is there an input into the YAML that allows me to define and use JS scripts, or alternatively is there perhaps a way to include JS scripts in the render() command directly?

**Comment by yihui** [comment]
You can specify arbitrary (CSS/JS/HTML/...) files to be included in your HTML output. Please see the section Includes at http://rmarkdown.rstudio.com/html_document_format.html

You don't need to do anything for HTML widgets if you want to include the dependencies of widgets; these dependencies will just be included automatically.

**Comment by Nicktz** [comment]
Thanks for the great package @yihui!
