### ISSUE TITLE
When rendering Rmd with an HTML h1-h4 header tag to markdown, the header tag is spread over multiple lines

### ISSUE THREAD

**Issue by daattali** [rstudio/rmarkdown#545]
If I have an Rmarkdown document with the following lines in it:

```
## Header with pounds

<h2>Header with HTML</h2>

<span>another tag<span>
```

And render it to markdown, the resulting markdown has

```
Header with pounds
------------------

<h2>
Header with HTML
</h2>

<span>another tag<span>
```

Note how the `h2` tag has its opening tag and closing tag on separate lines. When rendering such a markdown on GitHub, the result is that a whitespace appears before the text.  If you just knit the file directly using knitr, this doesn't happen.

Not a huge deal, but a tiny bit of an aesthetic issue.  The reason I sometimes use `h2` tags instead of the markdown equivalent is if I want to give the header an ID so that I can link to it within the document

**Comment by yihui** [comment]
That is what Pandoc does internally for HTML tags, and we cannot do anything about it. You may file a feature request to Pandoc if you want. Thanks!

**Comment by daattali** [comment]
@yihui shouldn't the behaviour of Rmd -> md be the same whether called from knitr::knitr or from rmarkdown::render?  I don't understand how pandoc can affect this in the rmarkdown package but not in knitr.

If you still think so then I will not argue any further, just wanted to point out my confusion

**Comment by yihui** [comment]
No, `knitr::knit()` only runs the code chunks in R Markdown and generates a Markdown output file; it does not parse Markdown or render to HTML. `rmarkdown::render()` is basically `knitr::knit()` plus Pandoc. Your h2 tag should be preserved in the first step, i.e. `knitr::knit()`, but it will be altered by Pandoc in the second step, i.e. when Markdown is rendered to HTML. You can verify it from command line:

```
pandoc -f markdown -t html
```

paste

```
## Header with pounds

<h2>Header with HTML</h2>

<span>another tag<span>
```

Ctrl + D to end the input, and Pandoc writes the following to the terminal:

```
<h2 id="header-with-pounds">Header with pounds</h2>
<h2>
Header with HTML
</h2>
<p><span>another tag<span></p>
```

**Comment by daattali** [comment]
Right, that makes sense.

But the "bug" is that the h2 tag is **not** preserved in the first step; the markdown document itself already contains the multi-line HTML.

To reproduce: If you start with the following as your Rmd

```
---
output: md_document
---
<h2>Header with HTML</h2>
```

Then the output is three lines.

But if you either knit directly with knitr, or specify in the YAML `output: html_document: keep_md: true` then the resulting markdown is only one line. That's why I think there's something off in `rmarkdown`.

Thanks for addressing so promptly

**Comment by yihui** [comment]
By the first step, I mean exactly `knitr::knit()` and nothing else. If you `knit()` (I mean the `knit` function in knitr instead of the Knit button in RStudio) the document, the h2 line should not be changed. If you render the R Markdown document with rmarkdown, that is _two_ steps: knit(), and then Pandoc. Pandoc changed the h2 line to three lines. I hope I have made it clear this time.

**Comment by daattali** [comment]
Hmm I still don't understand why the markdown file is different when using `output: html_document` vs `output: md_document`...

Am I correct in thinking that pandoc only operates on the .md file, not on the .Rmd file? If that is true, that the .md file should not be different from the source and it should have the h2 on one line only.  So, I still don't see why pandoc is relevant here when only I'm talking strictly about the .md file.

**Comment by yihui** [comment]
You are right that Pandoc does not touch Rmd, but md only. The fact is that when `output: md_document`, Pandoc still comes in and converts Markdown (generated from `knitr::knit()`) to Markdown. You may think this should not change anything, but that is not true for Pandoc. Pandoc does parse the HTML tags in Markdown and add cosmetic changes. You can repeat what I mentioned above but change the command line to

```
pandoc -f markdown -t markdown
```

**Comment by daattali** [comment]
Ah, ok, mystery solved. I still think the output markdown from `output: md_document` should be identical to the intermediate markdown from `output: html_document`, but perhaps you have good reasons for that.  Now at least it make sense to me, thanks!

**Comment by yihui** [comment]
The reason that we call Pandoc is that users may want to convert one flavor of Markdown to another flavor, which is what Pandoc can do.

**Comment by daattali** [comment]
Thanks for sticking with me, now all is clear.
