### ISSUE TITLE
html output jumps to random location

### ISSUE THREAD

**Issue by csrvermaak** [rstudio/rmarkdown#547]
When I Knit HTML from my rmarkdown document, everything works perfectly (thank you for a FANTASTIC product!), but when the HTML opens, the default location is halfway down the document, as opposed to the top. Thus, the reader has to scroll up to get to the top of the doc. This happens in the preview, as well as in the browser, so something must be compiled into the html for this to occur?

Please advise?

**Comment by csrvermaak** [comment]
OK, I've figured out that this is caused by the htmlwidgets I'm using. A random widget takes the focus, thus the page moves to that widget's location. I will replicate this issue in the htmlwidgets /DT repo, but not sure where it should be fixed? Perhaps here?

**Comment by yihui** [comment]
There is indeed a certain DataTables extension that has this problem. It is probably KeyTable: http://rstudio.github.io/DT/extensions.html If you look at the HTML source of this page, you will see I have a hack there:

```js
<script type="text/javascript">
// a certain extension scrolls the page to Section 6 for some reason, so scroll
// to top first on load
$(function() {
  setTimeout(function() {
    window.scrollTo(0, 0);
  }, 1);
});
</script>
```

It is not DT's fault, but you can log this issue at https://github.com/rstudio/DT/issues anyway, so I may see if the problem will be fixed upstreatm in the DataTables library. Thanks!
