### ISSUE TITLE
RStudio button: "Knit HTML" irrespective of document format with indentation in YAML header

### ISSUE THREAD

**Issue by crsh** [rstudio/rmarkdown#548]
I'm sorry if this is the wrong place to report this, but I found no other place to report RStudio-related things and this is related to RMarkdown.

It's very handy that the "Knit"-Button in RStudio changes its label depending on the target format. Now the default YAML header where this information is taken from looks something like this:

    ---
    title: "Untitled"
    author: "John Doe"
    date: "12. November 2015"
    output: pdf_document
    ---

For long YAML headers I find it neater to indent variable definitions like this:

    ---
    title   : "Untitled"
    author  : "John Doe"
    date    : "12. November 2015"
    output  : pdf_document
    ---

This works perfectly with the exception that with this header the "Knit"-Button is labeled as "Knit HTML". I was pretty confused because I expected the output to be in HTML format.

**Comment by jjallaire** [comment]
Hi Frederik, thanks for reporting this. Note for future reference that you
can report RStudio IDE issues at https://support.rstudio.com.

We are closing down the current release of RStudio IDE so this isn't
something we can address right now but we can look at it for the next
release (I'd recommend submitting this at the support site linked to above
if you want to track status/resolution).

**Comment by crsh** [comment]
Thanks for your quick reply. I have [copied this issue](https://support.rstudio.com/hc/communities/public/questions/207170877-RStudio-button-Knit-HTML-irrespective-of-document-format-with-indentation-in-YAML-header) to the support-site.
