### ISSUE TITLE
Problem with a custom css background in ioslides

### ISSUE THREAD

**Issue by martinschmelzer** [rstudio/rmarkdown#550]
Hi there,

I posted a question in stackoverflow.com and it would be great if someone could check it:

http://stackoverflow.com/questions/33668705/images-in-ioslides-presentation-not-properly-converted-to-base64-anymore

The essence is, that somehow an background image that is defined via a css stylesheet wont display in the final HTML file. I assume it has something to do with the double encoding (the stylesheet is included as base64 code inside the html and the image is include as base64 inside the stylesheet) but I am not sure. You find more details in the link above.

Kind regards,
Martin

**Comment by yihui** [comment]
I believe that is due to the Pandoc bug that I mentioned in my second comment in #428.

**Comment by pozelei** [comment]
Oh yeah. looks like to be the similar problem. Didn'T find that issue. Then I'll have to wait I guess :(

**Comment by yihui** [comment]
I mentioned in #428 that you could also base64 encode the image by yourself.
