### ISSUE TITLE
render's document_format does not always use output_file name

### ISSUE THREAD

**Issue by machow** [rstudio/rmarkdown#555]
If I have an Rmd file named `somefile.Rmd`, with the yaml header

```
---
title: Some title
output: 
    html_document:
        keep_md: true
---
```

Then using `rmarkdown::render('somefile.Rmd', output_file='newname.html')` will reports named `newname.html` and `newname.md`.

However, if I try to render the file using

```r
rmarkdown::render('somefile.Rmd', output_file='newname.html',
  output_format=c("html_document", "md_document")
```

it will produce reports names `somefile.html` and `somefile.md`.

Intuitively, I would have expected the above command to have produced `newname.html` and `newname.md`. Is this the intended behavior? If so, is there a way to rename the output **and** specify multiple output formats when using render? 

I'm happy to try and make changes if someone can point me in the right direction (and I can find some free time!).

(this is with Rmarkdown 0.8.1)

**Comment by yihui** [comment]
I have fixed this via #572 (see an example there). Thanks!

**Comment by ralfer** [comment]
I have the same issue with the last version of rmarkdown from github (or version 1.0 from CRAN). If I try

`rmarkdown::render('somefile.Rmd', output_file='newname.html', output_format=c("html_document", "word_document"))`

I receive a error message:
`Error in do.call(output_format_func, options) :  second argument must be a list` 

If I try

`rmarkdown::render('somefile.Rmd', output_file='newname.html', output_format=c("html_document", "word_document"),output_options	=list())`

the files are rendered with original name instead of newname.

**Comment by jjallaire** [comment]
I'm unable to repro your first error -- could you post the contents of
"somefile.Rmd" as well as your sessionInfo

**Comment by machow** [comment]
When you have multiple output formats, it looks like the render function ignores the file_name argument. [See comments in these lines of the render function](https://github.com/rstudio/rmarkdown/blob/9dfb5d6a62c26dd18495c1a1436db8773120cefe/R/render.R#L46-L61).

**Comment by ralfer** [comment]
Sorry, the first error was due to malformed header of Rmd file. I fixed it, and now I don't get an error, but the output_file is still ignored

**Comment by ralfer** [comment]
@machow it would be useful to have it as a prefix for generating different output formats based on the same template but different environment. Right now, I have to use two loops for that, e.g.:
```
for (ext in c('html','word')){
  for (i in data_files_list){
    prefix <- file_path_sans_ext(basename(i))
    env = new.env()
    load(i, env)
    render('summaries_and_plots.Rmd',output_dir = 'outputs', output_file = paste0(prefix,'.',ifelse(ext=='html',ext,'docx')), output_format=paste0(ext, '_document'),output_options = list(keep_md=T), envir=env)
  }
}
```

**Comment by machow** [comment]
I didn't test this, but from Yi Hui's example above, it seems like you
could do something like...

```

output_format <- c('html_document', 'word_document')
output_file <- c('newname.html', 'newname.docx')
render(FILENAME, output_format=output_format, output_file=output_file)

```

If that doesn't work, a simple example showing how it produces an error
would be useful.

**Comment by ralfer** [comment]
Doesn't seem to work:
```
> output_format <- c('html_document', 'word_document')
> output_file <- c('newname.html', 'newname.docx')
> render('somefile.Rmd', output_format=output_format, output_file=output_file)


processing file: somefile.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: somefile.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS somefile.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output somefile.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template "d:\MRO\R-3.2.3\library\rmarkdown\rmd\h\default.html" --variable "theme:bootstrap" --include-in-header "C:\Users\Notandi\AppData\Local\Temp\RtmpIreMkj\rmarkdown-str18e018908bd.html" --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --no-highlight --variable "highlightjs=d:\MRO\R-3.2.3\library\rmarkdown\rmd\h\highlight" --variable "navigationjs=d:\MRO\R-3.2.3\library\rmarkdown\rmd\h\navigation-1.1" 

Output created: somefile.html


processing file: somefile.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: somefile.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS somefile.utf8.md --to docx --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output somefile.docx --highlight-style tango 

Output created: somefile.docx
```

That makes sense because output_file is set to NULL in the [code you referred to above]( https://github.com/rstudio/rmarkdown/blob/9dfb5d6a62c26dd18495c1a1436db8773120cefe/R/render.R#L46-L61)

**Comment by yihui** [comment]
You should see `newname.html` and `newname.docx` under your working directory. The messages only showed you the _temporary_ output filenames (`somefile.html`, `somefile.docx`).

**Comment by ralfer** [comment]
Ah. Did not expect that. Indeed, they are created! But then output_dir is ignored.
