### ISSUE TITLE
Compiling ioslides Presentation Terminates RStudio

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#557]
A minimal Rmd document terminates RStudio when the Knit HTML (ioslides) option is used, but it works fine if Knit PDF (Beamer) is chosen instead.

    ---
    title: "Workshop"
    author: "Dario"
    date: "30 November 2015"
    output: ioslides_presentation
    ---

    The End.

Why does it work when Beamer is chosen from the drop-down menu? If anything, I would think it would fail when Beamer was chosen and ioslides was specified in the document header, not when ioslides was chosen and agrees with the `output` field of the document header.

RStudio version is 0.99.489 and session information is : 

    > sessionInfo()
    R version 3.2.2 (2015-08-14)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu Wily Werewolf (development branch)

    locale:
     [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
     [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
     [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
     [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] knitr_1.11      yaml_2.1.13     rmarkdown_0.8.1

Pandoc is also at the minimum version specified in the requirements.

    $ pandoc --version
    pandoc 1.13.2.1
    Compiled with texmath 0.8.1, highlighting-kate 0.5.12.

**Comment by yihui** [comment]
I cannot reproduce this issue on Ubuntu 15.04. Both ioslides and beamer work fine. For RStudio IDE issues, you may report to https://support.rstudio.com

Regarding the drop-down menu: I don't see your point. When `output` is specified in YAML, you may _choose_ to render the R Markdown document to other formats if you want. It is a choice. It will be too bad to stop users from rendering beamer slides even when `output` is ioslides. If you don't want to render beamer slides, you may choose not to do so, but it is a bad idea not to have the freedom. The default menu item in the Knit button will change according to `output` anyway.

**Comment by DarioS** [comment]
You're right. There's no problem with `render("slides.Rmd")`; only when the Preview window opens. I will describe the problem on the RStudio support site.

I didn't realise that making selections in RStudio could alter the text content in the text editor. That's surprising, but I'm glad to be aware of it. What happened was that when I chose Beamer, it changed the entry of `output` to `beamer_presentation`. That's why the error stopped in that case.
