### ISSUE TITLE
ioslides with Rectangular Logo

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#558]
The documentation states `the logo should be square and at least 128x128` but provides no information about what to do if the logo is rectangular. Because the description uses "should" instead of "must", there could be be a way to use rectangular logos which is not documented. Could this section of the documentation be expanded? The University of Sydney only has a rectangular logo, for example.

**Comment by jjallaire** [comment]
The logo will be rendered in a square form factor so if it's rectangular
then I think it will just be scaled to square (likely making it look rather
different)

**Comment by DarioS** [comment]
I understand it would be squared and look odd, but surely there must be some CSS option to customise the dimensions ?

**Comment by jjallaire** [comment]
There very well may be (we didn't write the CSS, it's from Google
ioslides). You can add custom CSS using the css option. Here's the base
CSS:
https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/ioslides/ioslides-13.5.1/theme/css/default.css

**Comment by DarioS** [comment]
It was hard to find the section in the CSS file because the information on the rmarkdown webpage is wrong. By default, the dimensions are actually 85 x 85, not 128 x 128.

    aside.gdbar img {
      width: 85px;
      height: 85px;
      position: absolute;
      right: 0;
      margin: 8px 15px;
    }

The easy way to modify the size is : 

    .gdbar img {
      width: 353px !important;
      height: 152px !important;
    }

This code should be placed in a document such as `my.css` and the header of the Rmd should have `css: my.css`. I don't think the webpage is in GitHub, so I can't make a pull request with suggested documentation changes. Can you modify it ? I can't find the settings for the slides footer logo anywhere, though.

**Comment by jjallaire** [comment]
The documentation is on the gh-page branch of the main rmarkdown repo.
Would welcome any PR you can provide to make the docs more clear!

BTW the 128x128 will be scaled down to 84x84 by the browser so it's okay to
overspecify this (and also means that if we ever take it up from 84x84
there will be no ugly upscaling on existing presentations).

**Comment by DarioS** [comment]
Do you have any information about how to change the size of the icon in the slides footer ? I *didn't* resolve that part of the question.

**Comment by DarioS** [comment]
I found it, eventually. This is explained in Pull Request #567

**Comment by jjallaire** [comment]
Awesome, thanks!
