### ISSUE TITLE
Error if smaller is TRUE and Page Breaks are Used

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#561]
Small example : 

```

---
title: "Test"
date: "1 December 2015"
output:
    ioslides_presentation:
        smaller: true

---

## R Markdown

This is an R Markdown presentation.

----

When you click the Knit button, a document will be generated.
```

This example results in : 

```
pandoc: user error ([string "custom"]:253: attempt to concatenate field 'class' (a nil value))
Error: pandoc document conversion failed with error 1
```

If `smaller` is changed to `false` **or** the `----` page break is removed, then the document compiles fine.

**Comment by DarioS** [comment]
It is possible to make a page break as:

    ##

This is a workaround to the bug, not a solution.

**Comment by yihui** [comment]
Sorry that this has been left here for two years, but I'm afraid we won't be able to fix this in the future... More on ioslides: http://rmarkdown.rstudio.com/html_document_format.html#floating_toc

In my experience, several other more modern and better maintained libraries are almost uniformly better than ioslides. Two examples are [xaringan](/yihui/xaringan) and [revealjs](/rstudio/revealjs). You want to give them a try instead.
