### ISSUE TITLE
ioslides Incremental Bullets Work Only Once

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#562]
If the final slide is navigated to by repeatedly pressing the keyboard's right arrow, then the left arrow is repeatedly pressed so that the title slide is returned to, the second time navigating past the slide with the bullets fails to show them incrementally.

    ---
    title: "Test Increments"
    date: "1 December 2015"
    output: ioslides_presentation
    ---
    
    ## R Markdown
    
    This is an R Markdown presentation.
    
    Countdown:
    
    > - 3
    > - 2
    > - 1
    
    When you click the **Knit** button, a document will be generated.
    
    ## The End
    
    Summary

Clicking on the internet browser's refresh button while on the title slide restores the incremental appearance of bullets. Is it a design choice or bug ?

**Comment by yihui** [comment]
It is probably a design choice of ioslides: https://code.google.com/p/io-2012-slides/ If this behavior has to be changed anyway, the change should ideally occur in the upstream ioslides library, and I guess we are unlikely to patch it. Given that it is usually cheap to hit the refresh button, I'm closing this issue. If you tend to think this is a bug, you may report to ioslides developers. Thanks!
