### ISSUE TITLE
Two-Column ioslides Documentation Missing Delimiter Information

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#565]
The section http://rmarkdown.rstudio.com/ioslides_presentation_format.html#advanced-layout describes a layout of two columns, but provides no information about how to switch to the second column. This should be added. I plan to have two columns of bullet points on the acknowledgements slide, one for each research centre.

**Comment by jjallaire** [comment]
The docs do point out that the content flows from column to column so you need to make sure the content in column 1 is large enough to force flowing to column 2. See:

https://github.com/rstudio/rmarkdown/blame/gh-pages/ioslides_presentation_format.Rmd#L245-L248

For example, the following will create two lists one in each columns however if there were less bullet points in the first list you'd see the second list starting in column 1:

```html
<div class="columns-2">
<ul>
  <li class="red">class="red"</li>
  <li class="red2">class="red2"</li>
  <li class="red3">class="red3"</li>
  <li class="blue">class="blue"</li>
  <li class="blue2">class="blue2"</li>
  <li class="blue3">class="blue3"</li>
  <li class="green">class="green"</li>
  <li class="green2">class="green2"</li>
</ul>
<ul>
  <li class="green3">class="green3"</li>
  <li class="yellow">class="yellow"</li>
  <li class="yellow2">class="yellow2"</li>
  <li class="yellow3">class="yellow3"</li>
  <li class="gray">class="gray"</li>
  <li class="gray2">class="gray2"</li>
  <li class="gray3">class="gray3"</li>
  <li class="gray4">class="gray4"</li>
</ul>
</div>
```
