### ISSUE TITLE
ioslides Ordinary Bullets Don't Work

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#566]
All items appear on a single line.

    ---
    title: "Test Bullets"
    date: "2 December 2015"
    output: ioslides_presentation
    ---

    ## Acknowledgements

    <span style=font-weight:bold>Statistical Bioinformatics</span>
    - A. Prof. Jean Yang
    - Dr. John Ormerod

**Comment by jjallaire** [comment]
You need a linebreak before the list. Like this:

```html
<span style=font-weight:bold>Statistical Bioinformatics</span>

- A. Prof. Jean Yang
- Dr. John Ormerod
```
