### ISSUE TITLE
Footnote references pointing to the same footnote get different numbering and footnote

### ISSUE THREAD

**Issue by chozelinek** [rstudio/rmarkdown#568]
I don't know if this is the pretended behaviour, but I would expect that footnotes references pointing to the same footnote should get the same number and point to the same footnote.

```
If I define [^notavailable]: The information was not available.

And then I write something like:

- Arrival time[^notavailable].
- Flight code
- Departure time[^notavailable].
```
I would expect:

- Arrival time[1]
- Flight code
- Departure time[1]

[1]: Information was not available.

But I get:

- Arrival time[1]
- Flight code
- Departure time[2]

[1]: Information was not available.
[2]: Information was not available.

**Comment by jjallaire** [comment]
This behavior is inherited from pandoc so you should post an issue on the
pandoc repo: https://github.com/jgm/pandoc

**Comment by chozelinek** [comment]
Hi @jjallaire, thank you for your reply and the pointer. I have looked for the topic there, and it was already reported in 2014. https://github.com/jgm/pandoc/issues/1603
