### ISSUE TITLE
Compile notebook can't find file

### ISSUE THREAD

**Issue by jgellar** [rstudio/rmarkdown#570]
I have been writing a .R script, and want to use the "Compile Notebook" feature to create HTML output. The script reads in a dataset as follows:

```r
library(data.table)
data <- fread("Data/mydata.csv", header = TRUE, sep = ",")
```

This code runs fine when it run it interactively. However, when I try to compile the notebook, I get the following error:

```
Error in fread("Data/mydata.csv",  : 
  File 'Data/mydata.csv' does not exist. Include one or more spaces to consider the input a system command.
Calls: <Anonymous> ... withVisible -> eval -> eval -> as.data.frame -> fread

Execution halted
```

I am using an RStudio project, will the "Data" directory as a folder in the main project directory, so the relative path should work. Why won't it find the file when executed through Compile Notebook? Does the working directory change to something other than the project directory?

**Comment by yihui** [comment]
The working directory of code chunks is the directory containing the R script that you try to compile as a notebook, and this directory may not be the same as the RStudio project directory. Please see https://github.com/yihui/knitr/blob/master/man/knit.Rd#L104-L107
