### ISSUE TITLE
New rmarkdown template loads with multiple files

### ISSUE THREAD

**Issue by jgellar** [rstudio/rmarkdown#571]
I have created a package containing a few rmarkdown [templates](http://rmarkdown.rstudio.com/developer_document_templates.html), which I defined. The problem is that when somebody wants to create a new document from the template, it says that there are multiple files associated with the template, and wants to create a new directory for the new markdown file. The directory ends up containing the .Rmd file, as well as the .html and .pdf output that is created from compiling the template. I don't want these output files to be included - I just want the user to get the .Rmd file.

I think the problem is related to the fact that, while developing the template, I would compile it (both in .html and .pdf), which would create skeleton.html and skeleton.pdf files in the skeleton directory for the template. However, once I realized that these files were being included in the package template, I deleted them before building the binary package (which I am distributing as a file). I'm not sure why they are being re-created as part of the binary distribution.

To reiterate, here is my current file structure for one of the templates:

```
mypackage/inst/rmarkdown/templates/mytemplate/
    template.yaml
    skeleton/
        skeleton.Rmd
    resources/
        style.css
        header.html    # This file is added with the "include" argument of html_document()
```

One thing that is weird is that I don't have this problem if I try to create a new rmarkdown file from the template, with the package loaded using "Build & Reload" (in the RStudio project used to create the package). It is not clear why this would be different than installing the binary version from file.

**Comment by jjallaire** [comment]
You could add these files to .Rbuildignore to make sure they are never
included in the binary package. Would that work?

**Comment by jgellar** [comment]
I added the following lines to .Rbuildignore:
```
^.*skeleton.pdf$
^.*skeleton.html$
```
Unfortunately this had no effect - new files that are created from the template still come with skeleton.html and skeleton.pdf.

**Comment by yihui** [comment]
@jgellar Are you using the button `Build & Reload` in RStudio to install your package? If so, you have to use `Build source package` to get the tarball, and run `R CMD INSTALL` on the tarball. The reason is that `Build & Reload` runs `R CMD INSTALL` on the package directory, and that does not respect `.Rbuildignore`. You should use the canonical way of installing an R source package, which is `R CMD build foo`, then `R CMD INSTALL foo_*.tar.gz`.

@jjallaire I think what `Build & Reload` really does is `Install & Reload`. It clearly has the advantages of speed (when the package has `vignettes` and `src` directories) and `--with-keep.source` (for debugging purposes), but often times I find the real build + reload useful.

**Comment by jgellar** [comment]
I was using `Build binary package`, as I am distributing this package to others (not publicly) and was testing the installation. But you are right that when I switched to building the source package, the problem went away. Thanks to both of you for your help!

The problem did not occur when I used `Build & Reload`, but I don't think this had to do with the `.Rbuildignore` - I had already deleted skeleton.html and skeleton.pdf, so it was weird that they were still going along with the package when I built the binary. The difference seems to be between what `Build binary package` and `Build source package` are doing.

**Comment by yihui** [comment]
FWIW, `Build binary package` uses `R CMD INSTALL` instead of `R CMD build`, and it does not respect `.Rbuildignore`.

**Comment by jjallaire** [comment]
It looks like you can create a ".Rinstignore" file which will take care of
it for R CMD INSTALL

**Comment by yihui** [comment]
Closing since this turned out to be more of an RStudio IDE issue.

**Comment by MichelineCampbell** [comment]
I had the same problem, but adding ```create_dir: false``` to the yaml file fixed it.
