### ISSUE TITLE
--natbib now added

### ISSUE THREAD

**Issue by ismayc** [rstudio/rmarkdown#577]
I just noticed that the newest version of rmarkdown now includes the `--natbib` pandoc option by default.  Since I didn't include natbib in my cls file or template.tex file, I am now getting an error with `\citep` and `\citet` references.  Can I disable this `--natbib` option?

**Comment by jjallaire** [comment]
@yihui Is there a way to do this?

**Comment by yihui** [comment]
Probably not. I'll take a look, and chances are I'll send a PR to make it possible to disable natbib.

**Comment by yihui** [comment]
#578 will revert to the old behavior, i.e. not use natbib by default.

**Comment by krlmlr** [comment]
The `citation_package` option to `pdf_document()` is not yet documented on http://rmarkdown.rstudio.com. I tried `pandoc_options: [ "--natbib" ]` first, obviously to no avail.

**Comment by jjallaire** [comment]
@yihui Could you add documentation for that option when you get a chance?

It occurs to me that this article may also need some updating:
http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

**Comment by yihui** [comment]
Sure I'll update the doc.

**Comment by jjallaire** [comment]
Thanks!
