### ISSUE TITLE
Feature Request: Convert Presentation to Handout Format

### ISSUE THREAD

**Issue by DarioS** [rstudio/rmarkdown#579]
Many of the popular presentation programs, like Microsoft PowerPoint, allow the presentation to be printed in handout format, where there are 3 or 6 slides per A4 page. It should be possible with rmarkdown.

**Comment by yihui** [comment]
You can print it to PDF, then it is up to the printer setting how to arrange the single pages. When you print the PDF, normally you can choose the layout (such as 2x2 or 3x2).
