### ISSUE TITLE
New update deletes .bib file

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/rmarkdown#580]
Hi RMarkdown folks,

I just updated to the new version (9) and now something rather strange is happening. Everytime I knit a pdf, it seems to delete the .bib file and the .csl file that I was using (both named in the YAML header). Quite naturally, I thought I must be imagining things, but this happened on two separate computers, one a Mac and one using Windows, about six or seven times now. It was fine before (the pdf still gets produced, btw). I know it sounds like the craziest thing, but...

**Comment by yihui** [comment]
I cannot reproduce this issue. Could you provide a small reproducible example? Mine is below:

test.Rmd

```
---
output: pdf_document
bibliography: test.bib
---

@R-base is cool.
```

test.bib

```
@Manual{R-base,
  title = {R: A Language and Environment for Statistical Computing},
  author = {{R Core Team}},
  organization = {R Foundation for Statistical Computing},
  address = {Vienna, Austria},
  year = {2015},
  url = {https://www.R-project.org/},
}
```

BTW, do you have `latexmk` installed, and what is your LaTeX version? You may check them in R:

```r
system('latexmk -v')
system('pdflatex -v')
```

**Comment by RobertMyles** [comment]
Hi Yihui,

Thanks for the quick reply. When I run a small test example like yours above, this error doesn't happen. However, when I use the full document I was using earlier (I'm writing a phd thesis in RMarkdown), then it happens every time, deleting both the .bib file and the .csl I'm using (on both mac and Windows). I didn't include a reproducible example earlier because this was all working fine until I updated RMarkdown on both the computers. As you can imagine, having to redo my entire bibliography in the last few weeks of my phd is making me 'slightly' mad.

The versions of latexmk and pdflatex are:

Latexmk, John Collins, 5 February 2015. Version 4.43a
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)

Is there any other information I could include to help us figure out the problem?

**Comment by yihui** [comment]
I apologize for the loss of your bibliography. I cannot think of a possible reason that .bib and .csl could be deleted. Can you try to create a reproducible example by minimizing your thesis Rmd file? e.g. you can delete the vast majority of the content (say, only keep one sentence there) and see if the problem is still there. Of course, you need to do this with a backup copy of your thesis. If you are able to figure out a minimal reproducible example, I can probably find out the cause. BTW, I guess it is unlikely to solve the problem, but you may also try the dev version of rmarkdown here: `devtools::install_github('rstudio/rmarkdown')` Thanks!

**Comment by RobertMyles** [comment]
Well, I took your advice and minimised the thesis down to one line, then one paragraph, then two and etc.  until I had the full file again. (I started a brand new .Rmd file to do this.) The good news is that there are no problems now, no suddenly-missing bibliography, etc. However, this still happens with the original file, which is identical to the copied one except it is a file from the earlier version of RMarkdown.  I dunno, I'm way too tired to try and figure this out. But it's working now–thanks for the help, Yihui.

**Comment by Rckrd** [comment]
Hello, I noticed the same issue and a cause - white spaces in document names. Rendering documents with spaces in their names deletes any file that have been sourced or loaded. The work around is to not use spaces in document names.

**Comment by yihui** [comment]
@Rckrd Thanks so much for the hint! I'll see if I can reproduce the issue with spaces in filenames.

@RobertMyles Thanks a lot for your time, and again I apologize for the frustration. I'll definitely try to find out the root cause and fix it.

**Comment by RobertMyles** [comment]
@Rckrd That IS one difference between the two files, well spotted!!

**Comment by RobertMyles** [comment]
@yihui  No worries about the problems, I think rmarkdown is fantastic, keep up the good work.

**Comment by Rckrd** [comment]
@yihui it is the output_format$intermediates_generator that picks up the loaded/sourced files i line 210 in render.R

    intermediates <- c(intermediates, output_format$intermediates_generator(original_input, 
      encoding, intermediates_dir))

**Comment by yihui** [comment]
Does the problem also occur when rendering HTML output? I assume both of you were rendering PDF output.

**Comment by yihui** [comment]
I provided a fix at #582 and you may test it by installing the fix via

```r
devtools::install_github('yihui/rmarkdown@bugfix/534')
```

Please let me know if it fixes your issues. Thanks!

**Comment by RobertMyles** [comment]
That works fine now!

**Comment by yihui** [comment]
@RobertMyles Thanks for letting us know! We have uploaded a new version 0.9.1 to CRAN. This bug report is very much appreciated!

**Comment by Matherion** [comment]
I arrived here through http://stackoverflow.com/questions/34889069/knitr-markdown-removes-image-file-from-project-folder, where a problem is explained where an image is deleted from a folder. I'm currently running into the same problem, but with

```
> packageVersion('rmarkdown');
[1] ‘0.9.5’
```

In my case, the line:

```
![Figuur 1.1.1. Dit is een afbeelding [...], Philosophical Transactions.](1665_phil_trans_vol_i_title.png)
```

Causes that .png file to be included but deleted. Could it be this error got 'reintroduced' somehow?

`cache` is set to TRUE, in case that matters.

Thank you in advance!

**Comment by yihui** [comment]
@Matherion Could you provide a minimal reproducible example with your `sessionInfo()`? I cannot reproduce your issue with my example.

**Comment by Matherion** [comment]
Um. Well. No. :-)

Ah. Yes I can. Ok, I figured it out. `render` deletes the files if you specify the directory containing the images as `intermediates_dir`. I guess this makes sense; although the fact that `render` happily overwrites existing files without warning (I assume it copied any included images to `intermediates_dir`), and then deletes them, may not be desirable? It could rename the 'intermediate' versions if a file with the same name already exists; or temporarily store the existing version elsewhere and put it back when it's done.

Or, the manual could explain this behavior perhaps? Also, the manual page for `render` seems to miss the last bit of the explanation of `intermediates_dir`. So at least that's *something* useful that came out of this :-)

My apologies for wasting your time, and thank you very much for helping me figure this out!!!

**Comment by jjallaire** [comment]
Thanks for the explanation of what was going on (glad you got to the bottom
of it!). I agree we should update the docs to clarify that behavior.

**Comment by alves** [comment]
The (as far as I can tell windows-specific) bug is still there when dealing with r-produced figures. A file knitted **for the first time** has no problem. The second time the -r-produced-figures are deleted (i see with the file browser that they are created and then deleted) and the process cannot find them. Exactly the same files does not have a problem in the Mac (!) Funnily enough deleting the intermediate folder does not help the second run, as RStudio somehow remembers it is not the first run. I am really tired of changing the file name to something new constantly!

Any help would be appreciated as I have to alternate between Mac and windows.

It is not the (old) version of rmarkdown:

> packageVersion('rmarkdown');
[1] ‘0.9.6.14’

Nothing in the path has spaces:

processing file: InterconnectednessEW.Rmd
  |.....                                                            |   8%
   inline R code fragments
  |..........                                                       |  15%
label: setup (with options) 
List of 1
 $ include: logi FALSE
  |...............                                                  |  23%
  ordinary text without R code
  |....................                                             |  31%
label: Allseries (with options) 
List of 1
 $ echo: logi FALSE

Quitting from lines 54-70 (InterconnectednessEW.Rmd) 
Error in (function (file = ifelse(onefile, "Rplots.pdf", "Rplot%03d.pdf"),  : 
  cannot open file 'InterconnectednessEW_files/figure-latex/Allseries-1.pdf'
Calls: <Anonymous> ... in_base_dir -> in_dir -> plot2dev -> do.call -> <Anonymous>
Execution halted

**Comment by yihui** [comment]
@alves Could you provide a minimal reproducible example?

**Comment by alves** [comment]
Example (saved as test1.Rmd in J:\workspace\InterconnectednessEW\: 

`---
title: "test"
author: "Ivan Alves"
date: "June 22, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
`

First run:

   |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: setup (with options) 
List of 1
 $ include: logi FALSE



processing file: test1.Rmd
  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: cars
  |..............................................                   |  71%
  ordinary text without R code

  |........................................................         |  86%
label: pressure (with options) 
List of 1
 $ echo: logi FALSE

  |.................................................................| 100%
  ordinary text without R code


output file: test1.knit.md

"C:/Users/alvesso/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS test1.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test1.pdf --template "D:\applications\MRO\R-3.2.4\library\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" 

Output created: test1.pdf

Second run:

  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%


processing file: test1.Rmd
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |............................                                     |  43%
  ordinary text without R code

  |.....................................                            |  57%
label: cars
  |..............................................                   |  71%
  ordinary text without R code

  |........................................................         |  86%
label: pressure (with options) 
List of 1
 $ echo: logi FALSE


Quitting from lines 27-28 (test1.Rmd) 
Error in (function (file = ifelse(onefile, "Rplots.pdf", "Rplot%03d.pdf"),  : 
  cannot open file 'test1_files/figure-latex/pressure-1.pdf'
Calls: <Anonymous> ... in_base_dir -> in_dir -> plot2dev -> do.call -> <Anonymous>
Execution halted

**Comment by alves** [comment]
In the meantime I also established that it seems to be related to the folder path. The exactly same file saved in a folder on my desktop works fine.
My J:\drive is a network drive \\SomeName\SomeDirectory$. Thus the "real" (?) path is something like  \\SomeName\SomeDirectory$\SomeUser\workspace\test, even though in windows it appears as J:\workspace\test.  Now this is really funny.

**Comment by Matherion** [comment]
Ah, interesting - I usually work in a SUBSTed folder (my dropbox is SUBSTed to B:, so it's always in the same spot regardless of which PC I'm using). So this may be the problem. I'll see whether using a 'regular' location fixes it when I have some time!

**Comment by eringrand** [comment]
I'm now seeing a similar situation, but have been unable to produce a reproducible example. I'm running
