### ISSUE TITLE
First author in citation has unwanted first initial

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/rmarkdown#586]
I'm running into a problem with citations in rmarkdown that seems to be linked to authors with more than one first name and citations of more than one author. For example, a reference of a 2004 paper with authors Joshua D. Clinton, Simon Jackman and Doug Rivers shows up as:

(J.D. Clinton, Jackman, and Rivers 2004), 

but should be: (Clinton, Jackman, and Rivers 2004).

The bibliography entry is correct, and Tex previews in Bibdesk are also correct. I've tried changing the csl, or not using a specified csl, but that doesn't change anything. I've also tried changing the style in Bibdesk and changing the .bib file, but that doesn't seem to be related to the problem. Obviously, the reference changes if I delete the "D." from Clinton's name, but I would rather not do that. 

Here is a reproducible example of the problem:

Test.Rmd

```
---
title: "Test"
author: ""
date: "January 2, 2016"
fontsize: 12pt
output: pdf_document
bibliography: Test.bib
---

This paper references various authors [@Clinton:2004aa]; 
various times [@Clinton:2004bb] and so on [@Clinton:2004cc]. 
```

Test.bib

```


@article{Clinton:2004cc,
	Author = {Clinton, Joshua D. and Jackman, Simon and Rivers, Doug},
	Date-Added = {2016-01-02 14:48:51 +0000},
	Date-Modified = {2016-01-02 14:49:31 +0000},
	Journal = {Journal},
	Number = {3},
	Pages = {1-20},
	Title = {Article 3},
	Volume = {1},
	Year = {2004}}

@article{Clinton:2004bb,
	Author = {Clinton, Joshua D and Jackman, Simon and Rivers, Doug},
	Date-Added = {2016-01-02 14:47:54 +0000},
	Date-Modified = {2016-01-02 14:48:40 +0000},
	Journal = {Journal},
	Number = {2},
	Pages = {1-20},
	Title = {Article 2},
	Volume = {1},
	Year = {2004}}

@article{Clinton:2004aa,
	Author = {Clinton, Joshua and Jackman, Simon and Rivers, Doug},
	Date-Added = {2016-01-02 14:46:56 +0000},
	Date-Modified = {2016-01-02 14:47:44 +0000},
	Journal = {Journal },
	Number = {1},
	Pages = {1-20},
	Title = {Article 1},
	Volume = {1},
	Year = {2004}}

```

In these examples above, what I would like to see is simply: (Clinton, Jackman, and Rivers 2004). This *was* the case until recently, but I don't know what changed. I tried using an earlier version of markdown (8.1), but that didn't have an effect. 
I'm using the latest versions of rmarkdown and RStudio. Thanks.

**Comment by yihui** [comment]
What is the exact version of your rmarkdown? I introduced some changes related to citations in rmarkdown 0.9 but reverted the changes soon in 0.9.1. Pandoc's default citation processing (via `pandoc-citeproc`) can be problematic sometimes, especially in the case of multiple authors. I find it more reliable to process citations via bibtex instead of pandoc-citeproc when the output is PDF. To do that, you may specify the `citation_package` argument of `pdf_document`:

```
output:
  pdf_document:
    citation_package: natbib
```

You may specify the bibliography style via `biblio-style` in YAML, e.g.

```
output:
  pdf_document:
    citation_package: natbib
bibliography: Test.bib
biblio-style: apalike
```

**Comment by RobertMyles** [comment]
Changing to natbib fixed that for me, thanks Yihui.

(I've version 0.9.1)

**Comment by yihui** [comment]
Great. Thanks for the confirmation!

BTW, rmarkdown 0.9.2 is on CRAN now, and that is to fix #580 (that you reported) on Windows. If you happen to use Windows, you are recommended to update rmarkdown again.

**Comment by mariusrubo** [comment]
I'll just drop this here: I had the same problem with unwanted first author initials in some of the references. In my specific case, using natbib did not solve the problem, as I did not get it to respect all of the details in my reference file (apa.csl). Probably I just don't understand natbib and/or csl-files well enough. What did solve the problem rather easily was to just (re-)install pandoc: 

install.packages("installr") # installing installr
require(installr)
install.pandoc() # use installr to install pandoc

**Comment by yihui** [comment]
Instead of installing Pandoc separately, you could also try the preview version of RStudio, which includes a newer version of Pandoc: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by mariusrubo** [comment]
I now experience this problem after I knitted an Rmarkdown file on a new computer with everything newly installed. 
For instance, my reference
```
@article{Blanke_2012,
doi = {10.1038/nrn3292},
	url = {https://doi.org/10.1038%2Fnrn3292},
	year = 2012,
	month = {jul},
	publisher = {Springer Nature},
	volume = {13},
	number = {8},
	pages = {556--571},
	author = {Olaf Blanke},
	title = {Multisensory brain mechanisms of bodily self-consciousness},
	journal = {Nature Reviews Neuroscience}
}
```
now appears as "(O. Blanke, 2012)" instead of "(Blanke, 2012)". 

I use
R version 3.5.3
rticles_0.7
rmarkdown_1.12
and 
"rmarkdown::pandoc_available()" returns TRUE. 
Using "citation_package: natbib" had no effect.

What could be the cause here?
