### ISSUE TITLE
render markdown with paths relative to output directory

### ISSUE THREAD

**Issue by machow** [rstudio/rmarkdown#587]
If I have an Rmd file named `somefile.Rmd`, with the yaml header

```

---
title: Some title
output: md_document

---
```

using 

```
rmarkdown::render('test.Rmd', 
                  output_file='test/test.md')
```

will create `test/test.md`, with figures in the directory `test/test_files`. However, figure paths in the markdown document will be relative to the directory `test.Rmd` lives in (`test/test_files/figure-html/chunk-1.png`). It makes sense that Rmarkdown might use this convention, in order to convert from markdown to html from the current working directory. However, if viewed as the final output from rmarkdown, the markdown file is not very self-contained: in order to view it or convert it to another format, a user needs to know what directory the original Rmarkdown file was in.

Moreover, if I use

```
rmarkdown::render('test.Rmd', output_file='test.md', output_dir='test')
```

It will produce the same files, except this time, the paths in the markdown document will be absolute--which leads to the same issue. Intuitively, since the figure directory is put in same folder as `test.md`, I would expect the figure paths to be relative to that file, so using the markdown file doesn't necessarily require knowledge about where it was generated from.

It seems like the cases right now are..
1. generated figure paths are relative to Rmarkdown file (output_file case)
2. generated figure paths are absolute (output_dir case)
3. generated figure paths are relative to markdown file (no case? except for manually tinkering with rmd file/knitr)

Case 3 seems very useful and intuitive if a markdown document is being considered as a final product of render, rather than an intermediate. Is there a simple way to do get this using render? Otherwise, does it seem reasonable to implement it, either by changing the default behavior of output_file/dir or adding an options for it? I'm happing to try implementing a solution if it seems reasonable, and someone points me in the right direction.

(also, I remember reading a knitr issue similar to this. Sorry if I've repeated it!)

**Comment by yihui** [comment]
The issue with output file paths is a forever pain. I feel it is extremely hard to get it completely right. To put it short, my person advice:

1. Do not use the `output_dir` argument of `render()`;
2. For `output_file`, do not put it in a different directory; `output_file = 'test.md'` is good, and `foo/test.md` is bad;
3. If you want the output to be in a different directory, render it in the current directory, then move the files to the directory you want (you may call `file.rename()`).

I have spent many hours on thinking about this issue in the past in **knitr**. Figures generated from R Markdown is only one of the potential issues, and is an easier one to solve. There are many other possible complicated issues, e.g. what does a custom image `![](foo/bar.png)` really mean when `output_file` contains a directory or `output_dir` is specified? Is `foo/bar.png` relative to which directory? Similarly, what does `read.csv('foo/bar.csv')` mean?...

**Comment by machow** [comment]
Thanks for the quick response and suggestions. I've been doing what you suggest, and moving everything after rmarkdown generates it, but remember spending a fair amount of time trying to figure out what was going on with output_dir, so your first point is especially useful!

It seems like interpreting the meaning of paths in a document involves two choices:

* Whether to make figure paths relative to input/output file
* Whether to interpret other asset paths relative to input/output file. 

If the next step after markdown is generating self contained HTML using pandoc, then they have to be the same (both relative to input or both relative to output), and in this situation, 99% of the time I'd imagine the answer is that asset paths are relative to input. However, if you don't plan to to create HTML, or don't want it to be self-contained, then 99% of the time I'd guess the answer is output for both, because that's how a simple web server will do it. Right now, it seems hard to break out of the self-contained pandoc route (though it is a useful route to have as the default). I can't use the chunk opt base.url, because it's not a matter of pre-pending figure paths.

I was going to say that a good solution might be moving the output files and figures folder after generating everything. This way, self-contained documents are generated normally, and documents that aren't self contained (like markdown files, or html without the flag via pandoc) can be rendered using relative paths. But that's exactly what I've been doing manually (and what you've suggested), so maybe continuing to move things manually is simpler! In any event, thanks for wrestling with the output path issue, I feel like most of the pain was removed by root.dir, base.dir, and root.url!

**Comment by tdhock** [comment]
I also have this issue. We have a `knit_print.animint` function https://github.com/tdhock/animint/blob/master/R/knitr.R which was working fine with `knit2html` and the knitr `output.dir` option. However upon upgrading to a more recent version of knitr we get an error that says we should use `rmarkdown::render` now https://travis-ci.org/tdhock/animint/jobs/105500479#L1940

So we did, and actually it works fine if we just use `render("file.Rmd")`.

But it doesn't work when we do `render("/path/to/file.Rmd", output_dir="animint-htmltest")`. I was expecting that value of `output_dir` to be passed on as `opts_knit$get("output.dir")` --- that is not the case! In fact `opts_knit$get("output.dir")` is `/path/to`.

**Comment by yihui** [comment]
@tdhock The error was a completely different issue. Please read the documentation `?knitr::knit2html`.

I don't know why you were expecting `output_dir` to be passed to `opts_knit$get('output.dir')`. This is not what is documented in `?render`, and `opts_knit$get('output.dir')` is not a [documented option](http://yihui.name/knitr/options/#package_options) either.

If `render("/path/to/file.Rmd", output_dir="animint-htmltest")` does not work, it is _probably_ a bug of rmarkdown, but as I said, personally (not speaking on behalf of the team) I do not recommend you to use the `output_dir` argument.

**Comment by royfrancis** [comment]
In relation to the comment above by YiHui ''If you want the output to be in a different directory, render it in the current directory, then move the files to the directory". If I have an R package that generates an rmarkdown report, the .Rmd file lives in the system library/package directory (eg. /files folder). Is it a good idea to render the html file in the package directory and then copy it to the user's current working directory? What if they are write restrictions in the package directory etc. I am not sure how to go about  doing this when I have an R package that generates an html report.

**Comment by yihui** [comment]
@royfrancis If you do not have write permission, one workaround is to copy the source files to a directory where you have write permission, and render the output there. Of course this is not efficient when the source files contain huge data files.

**Comment by royfrancis** [comment]
Thanks for the reply. I will leave [this here](https://github.com/daattali/ezknitr) as I just came across it. Seems like there is a whole package to address this issue.

**Comment by jananiravi** [comment]
@yihui years later, I still have a similar Qn: how do I insert figures relative to the `Rmd` filepath or the main repo's `Rproj` path. Also, is there a way to use `here::here` to specify the relative path rather than the absolute filepath. Alternatively, could I specify the image(s) location in the `yaml` part of the RMarkdown? I looked these up, and I still don't seem to have reliable solutions.

**_e.g.,_ use case**
Let's say, the Rmd file is within `/.../repo/docs` and the image to be inserted is within `/.../repo/images`, is there a clean way to use here or other relatives paths rather than absolute paths specifying my local HOMEDIR to insert images?
What works now is `![](/absolute/path/to/repo/images/image.png)`
Instead, I would like to call the relative paths w.r.t. my repo home `![](images/image.png)` -- that way it would work for me and my collaborators equally well!

> The issue with output file paths is a forever pain. I feel it is extremely hard to get it completely right. To put it short, my person advice:
> 
>     1. Do not use the `output_dir` argument of `render()`;
> 
>     2. For `output_file`, do not put it in a different directory; `output_file = 'test.md'` is good, and `foo/test.md` is bad;
> 
>     3. If you want the output to be in a different directory, render it in the current directory, then move the files to the directory you want (you may call `file.rename()`).
> 
> 
> I have spent many hours on thinking about this issue in the past in **knitr**. Figures generated from R Markdown is only one of the potential issues, and is an easier one to solve. There are many other possible complicated issues, e.g. what does a custom image `![](foo/bar.png)` really mean when `output_file` contains a directory or `output_dir` is specified? Is `foo/bar.png` relative to which directory? Similarly, what does `read.csv('foo/bar.csv')` mean?...

**Comment by cderv** [comment]
Hi @jananiravi 

Can you asked your question on https://community.rstudio.com ? It will be a better fit than in and old github issue thread. 

From there, we will be able to discuss your usecase, and open a new issue if necessary.

Thank you.
