### ISSUE TITLE
Knitting PDF from Rmd fails

### ISSUE THREAD

**Issue by chozelinek** [rstudio/rmarkdown#590]
Hi,

Problem:

I try to knit  a PDF from an Rmd, and I get the following messages (I tried with the default content when one creates a new Rmd file).

```
processing file: test.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: unnamed-chunk-1
  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: unnamed-chunk-2 (with options) 
List of 1
 $ echo: logi FALSE

cropping test_files/figure-latex/unnamed-chunk-2-1.pdf
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `test_files/figure-latex/unnamed-chunk-2-1.pdf'.
  |.................................................................| 100%
  ordinary text without R code


output file: test.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output test.pdf --template /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rmarkdown/rmd/latex/default-1.14.tex --highlight-style tango --latex-engine /Library/TeX/texbin/pdflatex --variable 'geometry:margin=1in' 
Unknown program /Library/TeX/texbin/pdflatex
pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
Execution halted
```

My set up:

- OS: Mac OS X El Capitan Version 10.11.2 (15C50).
- TeX distribution: latest MacTeX distribution (https://tug.org/mactex/mactex-download.html)
- RStudio: Version 0.99.491

The intermediate TeX file is compiled out of RStudio without problems.

If I use pandoc to transform the intermediate TeX file to PDF I get it right:

```
pandoc test.tex -o test.pdf
```

**Comment by yihui** [comment]
This is a known bug of Pandoc that has been fixed: https://github.com/jgm/pandoc/issues/2618 I have no idea when the next version of Pandoc will be released. Before the next version of Pandoc, you can revert to Pandoc 1.15.2: https://github.com/jgm/pandoc/releases/tag/1.15.2

**Comment by chozelinek** [comment]
Downgraded pandoc to 1.15.2 and it works again. Thank you @yihui for the pointer, and all the work!

**Comment by yihui** [comment]
No problem. FYI, Pandoc 1.16.0.1 has been released and this issue has been fixed there: https://github.com/jgm/pandoc/releases

**Comment by cpsievert** [comment]
Looks as though pandoc 2.0 might have re-introduced this issue

**Comment by rdrr1990** [comment]
I just posted about this issue for 2.0: https://github.com/rstudio/rmarkdown/issues/1120

**Comment by yihui** [comment]
@cpsievert Thanks! I'll investigate it tomorrow. Also reported to #1183.

**Comment by yihui** [comment]
This issue should be resolved now. Again:

```r
devtools::install_github("rstudio/rmarkdown")
```

This should work with Pandoc 2.0. Thanks for the testing!
