### ISSUE TITLE
PDF's do not render properly - new sections not recognized after plots

### ISSUE THREAD

**Issue by Rckrd** [rstudio/rmarkdown#596]
Adding a section below a plot does not render a new section, only the the verbatim  "## new section".

Snippet below from the standard template for a pdf_document. Two sections added, but only the second is displayed properly. 

 ## Including Plots
 
 You can also embed plots, for example:
 
 ``{r pressure, echo=FALSE}

      plot(pressure)

 ``
 ## this is displayed verbatim
  
 ## but this is a proper section

Session info -----------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32           
 ui       RStudio (0.99.860)          
 language (EN)                        
 collate  Swedish_Sweden.1252         
 tz       Europe/Paris                
 date     2016-01-20                  

Packages ---------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 curl        0.9.4   2015-11-20 CRAN (R 3.2.3)                    
 devtools  * 1.9.1   2015-09-11 CRAN (R 3.2.3)                    
 digest      0.6.9   2016-01-08 CRAN (R 3.2.3)                    
 htmltools   0.3     2015-12-29 CRAN (R 3.2.3)                    
 httr        1.0.0   2015-06-25 CRAN (R 3.2.3)                    
 knitr       1.12    2016-01-07 CRAN (R 3.2.3)                    
 magrittr    1.5     2014-11-22 CRAN (R 3.2.3)                    
 memoise     0.2.1   2014-04-22 CRAN (R 3.2.3)                    
 R6          2.1.1   2015-08-19 CRAN (R 3.2.3)                    
 rmarkdown * 0.9.5   2016-01-19 Github (rstudio/rmarkdown@314eff9)
 stringi     1.0-1   2015-10-22 CRAN (R 3.2.3)                    
 stringr     1.0.0   2015-04-30 CRAN (R 3.2.3)                    
 yaml        2.1.13  2014-06-12 CRAN (R 3.2.3)

**Comment by yihui** [comment]
You need a blank line before the section header. Or use the current development version of knitr: https://github.com/yihui/knitr#installation

**Comment by Rckrd** [comment]
Hello, yes, I used a single blank line in the document, but accidentally removed it when pasting it here.

However, adding two blank lines solves the problem..
