### ISSUE TITLE
allow output_dir in YAML front matter

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#597]
Hi, I generate my reports in a different folder because I have a gh-pages branch checked out there to document my analyses as a website.
I'd like to be able to set the output_dir in the YAML, so I don't have to call render by hand. I've done it by hand before without trouble, but it was bothersome.

**Comment by artemklevtsov** [comment]
It would be great.

**Comment by PedramNavid** [comment]
This would be nice. It would save me a lot of trouble and keep my source code folders clean of all the extras produced by knitting.

**Comment by yihui** [comment]
Sorry, but the arguments `output_dir` and `output_file` are like a forever pain for us; see #587 for more info.

If you want to build websites based on R Markdown, I have spent a year working on a new package blogdown: https://github.com/rstudio/blogdown. It is a much more comprehensive solution, and you won't need to worry about the `output_dir` issue any more if you use blogdown.
