### ISSUE TITLE
vignette engine error with travis-ci

### ISSUE THREAD

**Issue by jrowen** [rstudio/rmarkdown#609]
I'm running into an issue with creating vignettes on travis-ci (you can find the config [here](https://github.com/jrowen/rhandsontable/blob/master/.travis.yml)). 
```
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  The vignette engine knitr::rmarkdown is not available, because the rmarkdown package is not installed. Please install it.
Error: processing vignette 'intro_rhandsontable.Rmd' failed with diagnostics:
It seems you should call rmarkdown::render() instead of knitr::knit2html() because intro_rhandsontable.Rmd appears to be an R Markdown v2 document.
```
Here's the header to my vignette.
```
title: ""
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rhandsontable Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
```
Everything builds fine locally.  If this looks like an issue with the travis-ci set-up, let me know and I can post an issue over [there](https://github.com/craigcitro/r-travis).

**Comment by jjallaire** [comment]
The error message indicates that the rmarkdown package isn't installed on travis-ci so I'd as you suggested follow up there to see why this might be the case.

**Comment by jrowen** [comment]
There appears to have been a change with the r set-up for travis-ci, as the error goes away if rmarkdown is explicitly installed via the yml file.  Thanks for taking a look.
```
r_packages:
  - rmarkdown
```

**Comment by yihui** [comment]
You need to put rmarkdown in Suggests of your DESCRIPTION.

**Comment by jrowen** [comment]
That fixed things. Thanks for the suggestion.
