### ISSUE TITLE
Error: cannot open file 'C:/.../3.2/rmarkdown/R/rmarkdown.rdb' : No such file or directory

### ISSUE THREAD

**Issue by Isaacsh** [rstudio/rmarkdown#610]
I am getting this error today when I wanted to create a new R Markdown program. Everything was normal yesterday and have no idea what happened. Am using RStudio Version 0.99.491. My sessionInfo is as follows: 

`R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_3.2.3

loaded via a namespace (and not attached):
[1] tools_3.2.3`

Any ideas?

**Comment by yihui** [comment]
I have no ideas either (my best guess is your anti-virus software might have deleted this file for some reason), but I believe you can simply reinstall the package: `install.packages('rmarkdown')`

**Comment by Isaacsh** [comment]
That's right, it gets deleted by anti-virus. After I add RStudio in trusted applications everything's back to normal.
