### ISSUE TITLE
wish list item: conditional text and code running depending on output format

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rmarkdown#614]
I would like to produce output in different formats from the same Rmd source file and be able to use format specific trickery for, say, html and LaTeX. For that, it would be handy to mark text sections (not code sections) as LaTeX only, html only and so on.

Then, by just changing the output tag in the header, on could produce different outputs and still use the raw power of the underlying engines.

A related issue: I also would like to be able to perform code chunks conditionally depending on the output format.
The tufte template package has output formats tufte_handout and tufte-html.
tufte_html has default background color '#fffff8', tufte_handout has backround color white.
So when I use tufte_html I insert this code chunk:

```{r echo=FALSE}
library(ggplot2)
theme_set(theme_grey())
theme_update(panel.background=element_rect(fill='#fffff8'),
             plot.background=element_rect(fill='#fffff8'))
```

It would be convenient if one could somehow tag this chunk so it is only used when the output format is tufte_html.

**Comment by jjallaire** [comment]
You can get some of this context via knit options that we set during render:

https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L248-L251

This won't give you the output format name but it will give e.g. LaTeX vs.
HTML output.

In terms of the name of the current output format we actually don't have
it! (formats aren't named at runtime, they are just an R list with a
collection of knitr options, pandoc options, pre/post processing hooks, etc.

**Comment by neuwirthe** [comment]
That solves my problem with adapting the theme to the output format. 
Is there an easy way of having text not in code chunks depend on the output fotmat engine?

**Comment by neuwirthe** [comment]
I can do this brute force solution, but is there a better way?

```{r echo=FALSE, results='asis'}
if (opts_knit$get("rmarkdown.pandoc.to")=="html") {
cat("
This is
very simple
text
    ")}
```

**Comment by jjallaire** [comment]
No, unfortunately there isn't a better way than this right now.

**Comment by yihui** [comment]
I don't have a significantly better approach, but you can certainly write a helper function, and use the `asis` engine to include some text conditionally, e.g.

    ```{r setup, include=FALSE}
    is_html_output = function() {
      knitr::opts_knit$get("rmarkdown.pandoc.to") = ="html"
    }
    ```
    
    
    ```{r eval=is_html_output()}
    library(ggplot2)
    theme_set(theme_grey())
    theme_update(panel.background=element_rect(fill='#fffff8'),
                 plot.background=element_rect(fill='#fffff8'))
    ```
    
    
    ```{asis, echo=is_html_output()}
    Some text that is only included in **HTML** output.
    ```

**Comment by neuwirthe** [comment]
Thanks, yihou's solution is good enough for me right now!
