### ISSUE TITLE
ioslides doesn't work with custom CSS

### ISSUE THREAD

**Issue by gchiuoc** [rstudio/rmarkdown#615]
Refer. to https://support.rstudio.com/hc/en-us/articles/200532307-Customizing-Fonts-and-Appearance and http://rmarkdown.rstudio.com/ioslides_presentation_format.html 
For the life of me I can't get the examples on `.reveal section` or `.exclaim .reveal` to work for ioslides. They either get ignored by knitr or give weird output (e.g. "===" to declare slide titles no longer works, and `type: exclaim` anywhere in the .Rmd file gets shown as body text. This is especially frustrating because I need certain styles from a slide theme (e.g. 'journal') but also need to override certain aspects of that theme. But many declarations in my .css doesn't override the loaded theme.
Am I missing something??

**Comment by jjallaire** [comment]
I think you are criss-crossing two different types of slides. The first one
is from the "R Presentations" feature of RStudio (which uses reveal) and
the second is from the ioslides rmarkdown format. The former supports the
various attributes below the slide title and the latter does not (which is
why you see the behavior you are seeing -- i.e. they are treated as text).

**Comment by gchiuoc** [comment]
Wow thank you so much for pointing this out. I didn't realize "RMarkdown Presentation" and "R Presentation" are different beasts. Much appreciated.
