### ISSUE TITLE
Plotting within loop not working several functions: plot, barplot, qplot or ggplot2

### ISSUE THREAD

**Issue by dani-lbnl** [rstudio/rmarkdown#616]
Our rmd code to generate html needs to create several plots inside a loop, but unfortunately the plots get chopped off (eg. using plot, barplot) or in the case of qplot and ggplot2, I get an error Error: stat_count() must not be used with a y aesthetic. Any thoughts? 
I'm using: 

    ```{r , echo=FALSE, warning=FALSE,message=FALSE,results='asis',fig.show='asis'}

and the first barplot shows up perfect, the additional 2+ plots get chopped off with: 

```r
barplot(v[1:20],las=2,col="lightblue",main ="Most frequent words")
```

Similarly to the tutorial:
http://www.cs.ukzn.ac.za/~murrellh/dm/content/slides10.pdf
Any help welcome! thx, Dani

**Comment by yihui** [comment]
For the plot/barplot issue, please post a minimal self-contained reproducible example, and ideally with a screenshot illustrating how the plots were chopped off.

For the ggplot2 issue, I believe it is irrelevant to rmarkdown. Please consider the ggplot2 mailing list or StackOverflow when asking such questions.

**Comment by dani-lbnl** [comment]
Hi Yihui,

I'm sending you the code and image by email since this is part of unpublished work with my student. thx, ~Dani

**Comment by yihui** [comment]
The Rmd file you sent me is not self-contained: it has references to external files that I do not have, so there is no way for me to reproduce your problem. My best guess is a certain package/function modified `par('mar')` or something. It is hard to say without a reproducible example. The other thing you may want to check is if the problem exists when you just run the code in a clean R session without using rmarkdown, to see if rmarkdown/knitr is the culprit, or some other packages/functions.

**Comment by dani-lbnl** [comment]
Hi Yihui,
The input is the path for a set of pdf articles (e.g. 3 journal articles in
pdf format), it performs text mining and produce infographics similarly to
the file attached.

About par, it is not an option because the graphs are large and the fonts
will be too small to be useful. Making fonts larger is not an option
either, because the other graphical elements are not scalable.

What I need is a way to make sure labels for the bar plot can be shown. Any
help is much appreciated. thanks, ~Dani

Best Regards,
Dani
-------------------------------
*Daniela Ushizima*, PhD.
Deputy Head of the Data Analytics and Visualization Group
Staff Scientist - CRD, Lawrence Berkeley National Lab.
Data Scientist - BIDS, University of California, Berkeley
lab: +1 510 486-4061
dushizima@lbl.gov

**Comment by yihui** [comment]
You are replying to a Github issue by email, and Github does not allow email attachments, so I cannot see your attachments.

Again, I need a _self-contained reproducible_ example to investigate your issue. And you didn't reply to this in my preivous response:

> The other thing you may want to check is if the problem exists when you just run the code in a clean R session without using rmarkdown, to see if rmarkdown/knitr is the culprit, or some other packages/functions.

**Comment by DanielEWeeks** [comment]
Dear Yihui,

This sounds like the same problem I've been encountering.  You can find a self-contained minimal reproducible example at

http://stackoverflow.com/questions/37030219/r-markdown-plots-within-a-loop-going-out-of-margin-when-typesetting-to-pdf

Thank you,
Dan Weeks

**Comment by yihui** [comment]
There has been an answer on SO. Basically LaTeX is not smart enough to wrap the plots in this case.
