### ISSUE TITLE
MathjaxZoom.js not loading properly when using Shiny in Rmarkdown

### ISSUE THREAD

**Issue by Nicktz** [rstudio/rmarkdown#617]
When loading a shiny document from Rmarkdown, it says that it fails to load the mathjax's MathZoom.js extension.

All worked well and then it suddenly started giving problems. I have seen on github this was an [old issue](http://stackoverflow.com/questions/25705703/mathjax-in-shiny-suddenly-stopped-working) fixed in 2014, but I'm just wondering how I can point in Rmarkdown to the correct source for mathjax.

The error message looks as follows:
    File failed to load: http://127.0.0.1:4299/file1a9839f31451_files/mathjax-local/extensions/MathZoom.js

It also shows in the rmarkdown console:
    Stack trace (innermost first): followed by exprFunc, widgetFunc, func, renderFunc, etc.

Any ideas what might be going on here or how I can fix it?

**Comment by jjallaire** [comment]
Could you post a minimal reproducible example of this (shortest Rmd file
that exhibits the problem) so we can try to replicate locally. You should
include a call to sessionInfo() in the document so we can see the versions
of all the packages you have installed.

**Comment by Nicktz** [comment]
Hi @jjallaire, I am unfortunately struggling to produce a simple MWE where the mathjax library fails to load the MathZoom.js. I use the latest shiny, rmarkdown, R, Leaflet and plotly packages. I am asking more specifically whether the failure to load this extension is a general problem (as rmarkdown seems to point automatically to a wrong address it seems, as happened in 2014)? I reinstalled all my packages and drivers and it still fails to load. If you do not have a general answer as to why Rmarkdown points to a wrong address I will close this issue. Many thanks!

**Comment by jjallaire** [comment]
I need more details to go on here. I don't see any problem with loading mathjax or MathZoom.js when running this simple shiny document:

    ---
    title: "MathJax Test"
    runtime: shiny
    output: html_document
    ---

    $$ 
       \frac{d}{dx}\left( \int_{0}^{x} f(u)\,du\right)=f(x).
    $$

    ```{r, echo=FALSE}
    sliderInput("x", label = "Value:",  min = 1, max = 10, value = 5)

    renderText({
       input$x
    })
    ```

**Comment by efehandanisman** [comment]
Hello everyone,
I am having this issue with my RMarkdown document with Shiny component when I try to work with that on my local computer. I checked for possible solutions but could not find any. Anyone have an idea?
