### ISSUE TITLE
rmarkdown::run() doesn't work when running with a BAT file

### ISSUE THREAD

**Issue by qiwei-li** [rstudio/rmarkdown#620]
I want to create a short cut to run a shiny rmarkdown document.
I found a guide about how to create a BAT shortcut to run a shiny app (ui.R and server.R) below:
> http://rstudio-pubs-static.s3.amazonaws.com/3269_a6682dfda37e411fb5e0e6699495cdc4.html

With similar approach, I have the following code in run.R:
> library(shiny)
> library(rmarkdown)
> Sys.setenv(RSTUDIO_PANDOC="C:/Program Files/RStudio/bin/pandoc")
> rmarkdown::run(file="path_to_rmd\\report.Rmd")

And the following code in app.bat
> "C:\Users\Documents\R\R-3.2.3\bin\R.exe" CMD BATCH "run.r"

If I manually enter each line from run.R in R console, everything works. Running the bat file starts r sessions in task manager, but nothing pops in the browser. Is there a "launch.browser=TRUE" argument for rmarkdown::run()?

I'm really new to this, any help is appreciated.

**Comment by yihui** [comment]
Please take a look at the help page `?rmarkdown::run`. I think this should work:

```r
rmarkdown::run(file = "path_to_rmd/report.Rmd",
  shiny_args = list(launch.browser = TRUE))
```
