### ISSUE TITLE
table column headers always left-aligned

### ISSUE THREAD

**Issue by diegogruber** [rstudio/rmarkdown#625]
Hi, 

I just started trying the development version of rmarkdown and noticed that all my markdown tables have column headers that are left-aligned, regardless of the column's alignment. Here is a simple example:

```
---
title: "test"
date: "19 February 2016"
output: html_document
---

```{r echo = TRUE, results='asis'}
knitr::kable(head(mtcars), align = "r")
```

Here's a screenshot of the result:

![screen shot 2016-02-19 at 10 29 57](https://cloud.githubusercontent.com/assets/4028929/13171566/c27ec9ac-d6f3-11e5-894d-67438494c58e.png)

I've tried this on two different computers with OS X and Windows and both gave the same result. I'm using R version 3.2.3 within RStudio version 0.99.868.

Thanks for the great work!

PS: This is the first time I submit an issue on github, I hope I'm doing it right!

**Comment by jjallaire** [comment]
@yihui I'm guessing there was some change in the way that pandoc renders tables in v1.15.2 (I know for sure there was at least one change related to how columns widths are handled).

**Comment by yihui** [comment]
That is because Bootstrap 3.3.5 forced table headers to be aligned to the left: https://github.com/rstudio/rmarkdown/blob/8b8ce7758b/inst/rmd/h/bootstrap-3.3.5/css/bootstrap.css#L2261-L2263

**Comment by jjallaire** [comment]
Thanks for reporting this. We should have a fix available soon.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/b167f2b73e34995baa2e5f7642135d015521a8ff

**Comment by diegogruber** [comment]
Thanks! Working perfectly now.
