### ISSUE TITLE
Proposed feature: output=FALSE

### ISSUE THREAD

**Issue by mhwombat** [rstudio/rmarkdown#627]
I would like to be able to have some R code that is displayed and evaluated, but with all non-error output hidden. This would be particularly useful with `require` statements that generate a lot of output.

    ```{r comment='', output=FALSE}
    require(fields)
    require(ggplot2)
    ```

**Comment by jjallaire** [comment]
You should be able to accomplish this with "include = FALSE". There is a convention to start documents with a setup chunk that sets knitr options, loads required packages, etc. For example:

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    require(fields)
    require(ggplot2)
    ```

**Comment by yihui** [comment]
Normally `message = FALSE` is the way to suppress package startup messages, if the package author used the correct mechanism to emit messages, i.e. `packageStartupMessage()`, otherwise either `results = 'hide'`or `include = FALSE`, depending on what kind of output you want to suppress.
