### ISSUE TITLE
FR: local HTML preview is written to a temporary directory

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#628]
A great feature of the new GitHub document format is this:

> local HTML preview is written to a temporary directory

Could that be offered for `.md` files more generally? Then those html files aren't left behind in the Project, requiring git- and Rbuildignoring.

~~I notice I can already get that by requesting `output: github_document` in the document `foo.md` -- good news! But the bad news is that then `foo.markdown_github` gets left behind instead of `foo.html`. It is nice to get the github flavoured markdown and, of course, the html preview. Has anyone thought about how this might work?~~ _This no longer works, i.e. you actually can't (and shouldn't) use `output: github_document` in the YAML of an `.md` file._

**Comment by yihui** [comment]
Closing since this is an RStudio IDE issue.
