### ISSUE TITLE
Combat belief that captions do not work by setting `fig_caption = TRUE`?

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rmarkdown#629]
Is it possible to make the default for `fig_caption = TRUE` (especially for pdf documents)?

I keep encountering the false belief that R Markdown does not support captions (e.g. from users at last week's CSP conference, in emails from students, at the end of this article: http://www.ssc.wisc.edu/sscc/pubs/RFR/RFR_RMarkdown.html)

I think people try to set the chunk option `fig.cap` and then see no effect because `fig_caption = FALSE`. This behavior led me to believe that captions did not work, until Yihui told me otherwise.

This is just a suggestion because I do not know the other side of the story (e.g. why `fig_caption = FALSE`).

**Comment by jjallaire** [comment]
I just took a closer look at this and I can't think of a reason not to change `fig_caption` to `TRUE`. I think the reason I may have set this to `FALSE` originally was that some sort of default caption (based on chunk labels?) was getting generated for chunks and I thought it looked unsightly. I could be wrong about this though, @yihui 

The behavior I'm currently observing is that captions are only included when there is a `fig.cap`. If that's the case then I can't think of a reason not to do as you suggest. @yihui What's your take?

**Comment by yihui** [comment]
You are right. The reason that we set `fig_caption = FALSE` was because the default figure caption was like "plot of chunk unnamed-chunk-i". I have set the default caption to an empty string long time ago for R Markdown v2, so I think we are good to go with a better default `fig_caption = TRUE`.

**Comment by jjallaire** [comment]
Okay, that's great news! Resolved here: https://github.com/rstudio/rmarkdown/commit/6da5e5937e0ad2447e38b1decab6ae0271ca5e76
