### ISSUE TITLE
pandoc: Could not fetch /tabsets.js

### ISSUE THREAD

**Issue by dtenenba** [rstudio/rmarkdown#630]
Hi,

This seems related to other issues but since those have supposedly been fixed, I'm filing  a new one.
With the following vignette `test.Rmd`:

```
---
title: "my title"
author: "me"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
theme: united
vignette: >
  %\VignetteIndexEntry{my title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Header

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip 
ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
 fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

I get this:

```
$ R --vanilla -q CMD Sweave test.Rmd
pandoc: Could not fetch /tabsets.js
/tabsets.js: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted
```

If I remove the `theme` line, the problem goes away. Adding `self_contained: no` as suggested elsewhere does not help. Substituting a different theme (say `superhero`) for `united` has the same issue. This is with rmarkdown 0.9.5.1 and various versions of pandoc (1.15.0.6, 1.13.2, 1.16.0.1,  1.16.0.2) on various versions of R-devel (one is `2015-12-31 r69828`).

Thanks.

**Comment by jjallaire** [comment]
The problem is that "theme" is not compatible with html_vignette because it
uses a custom template. If you want to use themes then you should switch to
html_document.

**Comment by dtenenba** [comment]
I can confirm this works. Thanks.
