### ISSUE TITLE
Plot Previews Broken

### ISSUE THREAD

**Issue by jonyoder** [rstudio/rmarkdown#636]
https://github.com/rstudio/rmarkdown/commit/6f9a95248326aaeb0b5f6b065458d27b700d9a50 appears to have broken plot publishing (to Connect; previews are also broken).

**Comment by jonyoder** [comment]
See https://github.com/rstudio/connect/issues/1581 for more details.

**Comment by jjallaire** [comment]
I'm going to fix this in the IDE rather than rmarkdown. Already done here:
https://github.com/rstudio/rstudio/commit/2b107e549e8e2ffdb3e2adcc5ed02d2aff67fe8c

We'll roll a patch release with this fix ASAP.
