### ISSUE TITLE
feature request: option to default toc_float to first item

### ISSUE THREAD

**Issue by pssguy** [rstudio/rmarkdown#639]
Currently when an rMarkdown page is rendered it opens at the top of the page
Would it be possible to set it, optionally, so that it opens at specific content (or even just the first item) which would also have the advantage of drawing attention to the now-highlighted table of contents

**Comment by jjallaire** [comment]
A couple of follow ups:

1. The first item should already be selected when the document opens. Are
you not seeing this? If you aren't it would be helpful to see the Rmd you
are testing with as well what platform/browser you are on, etc.

2. If you select an item the URL in the address bar should be highlighted.
You can then send this as the document link (which will give you the
automatic navigation behavior you are hoping for).

**Comment by pssguy** [comment]
point 1
 It defaults to the title at the top of page "mytinyshinys - Socio-Economics" rather than first item,"UK Library Borrowings". I appreciate this is best default for most instances. I'm using windows/Chrome , rmarkdown 0.9.5


---
title: "mytinyshinys - Socio-Economics"
author: "mytinyshinys"
date: "March 4, 2016"
output:
  html_document:
    fig_caption: yes
    theme: flatly
    toc: true
    toc_float: true
    toc_depth: 2
    code_folding: hide
css: customBlog.css
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r libraries,  echo=TRUE, include= FALSE}
# # libraries required
library(shiny)

#library(shinydashboard)

library(dplyr)

# more for collecting initial data?
library(rsdmx)
library(readr)
library(plotly)
#library(crosstalk)
library(countrycode)
library(tidyr)
library(DT)
library(markdown)


```
This is a series of short articles usually related to apps I develop for the [mytinyshinys site](https://mytinyshinys.shinyapps.io/dashboard/) relating to socio/economic issues.     
Commented out code can be shown or hidden by toggling buttons


##  <span class="post">UK Library Borrowings</span>
*9th March 2016*

Many websites provide text or tables solely in pdf format. This makes it difficult to access the underlying data
and may be due to ignorance, lack of time/desire to help out developers or intended to make scraping more difficult  
etc

point 2
 Yes this does work and will prove helpful. However, I am endeavouring to use the rmarkdown file as a blog so would want it available on the web as just the base URL as a link rather than any named anchor    
    Further to this, am I right in thinking all the code on an rMarkdown page gets processed at once or is there the ability for each item to be run only when it is selected something like suspendWhenHidden = TRUE in shiny outputOptions

**Comment by jjallaire** [comment]
If you could create a standalone Rmd document which exhibits the problem as
a gist (https://gist.github.com/) that would be the most helpful thing for
me. This document shouldn't depend on any external files (e.g. datasets or
css files) so it can be easily re-run locally.

**Comment by pssguy** [comment]
Hope this is what you want to see (https://gist.github.com/pssguy/7daf757906c68695face)

TBH it is a fairly trivial point. The last para of my previous reply is more significant. Would you rather I raised that as a separate issue or am I just missing an option

**Comment by jjallaire** [comment]
Thanks! I see that the TOC item does get highlighted in static R Markdown
documents however unfortunately does not for runtime: shiny. This
unfortunately might be pretty tough to track down as the order of loading
for runtime: shiny is hard to program around.

As for automatically navigating to a sub-item, I think you could write some
JavaScript that would do that on document load (don't know exactly what the
recipe for that would be though).

J.J.

**Comment by pssguy** [comment]
a) OK. Never mind

b) Sorry, I have not made myself clear
  
    In a shiny web app, one can set output options
    outputOptions(output, "myplot", suspendWhenHidden = FALSE) with the default TRUE

  Is it possible to do an equivalent on a shiny RMarkdown page with several items on all with their own separate code? I may be wrong, but it seems like all the code gets processed effectively equivalent to  suspendWhenHidden = FALSE - which, of course, slows the page rendering

**Comment by jjallaire** [comment]
I am really not sure about suspendWhenHidden (haven't seen that before).

You could look at delayed rendering:
http://rmarkdown.rstudio.com/authoring_shiny_advanced.html#delayed_rendering

**Comment by pssguy** [comment]
Possibly, although it does not seem to make much difference that I can see on my page

The example code on that link produces an error
 length(n) == 1L is not TRUE
