### ISSUE TITLE
Images do not appear with runtime:shiny

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rmarkdown#64]
My images do not appear when I run a Shiny document. For example, this document does not find the image mentioned

```

---
title: "Shiny Document"
output: html_document
runtime: shiny

---

This is a picture.

![logo](images/RStudioLogoTM.png)
```

If I take out `runtime:shiny`, the RStudio Run Document option turns into a Knit HTML option and the images begin to work. For example, this document _does_ find the image mentioned

```

---
title: "Shiny Document"
output: html_document

---

This is a picture.

![logo](images/RStudioLogoTM.png)
```

This pattern occurs whether I put the image in a sub-directory or not.

**Comment by vnijs** [comment]
@jmcphers Could you explain how this is supposed to work? I posted issue #316. Is this resolved? Thanks.
