### ISSUE TITLE
Missing biblio-style support for BibLaTeX

### ISSUE THREAD

**Issue by inventionate** [rstudio/rmarkdown#640]
Hi, 

unfortunately the build in TeX template prevents the use of individual BibLaTeX styles. It's just one litte change in default-1.15.2.tex (99) to support the biblio-style variable [http://pandoc.org/README.html#variables-for-latex](url):

`\usepackage$if(biblio-style)$[style=$biblio-style$]$endif${biblatex}`

Best regards,
Fabian

**Comment by jjallaire** [comment]
@yihui Do you think we should make this change?

**Comment by inventionate** [comment]
I hope you'll make it. In particular because the support is built in for natbib already.

**Comment by yihui** [comment]
Yes I think we should make the change. @inventionate Do you want to submit a simple pull request?

**Comment by inventionate** [comment]
Thank you very much! I've submitted a pull request.

**Comment by yihui** [comment]
Great. Thanks!
