### ISSUE TITLE
Markdown to PDF - Wrap text in code chunks and results

### ISSUE THREAD

**Issue by raencinas** [rstudio/rmarkdown#646]
Hi,

I'm trying to create a PDF report with markdown in Rstudio. Some code chunks have long texts that I'm using to create paragraphs with paste(), like this:

```
paragraph1 = paste(
"test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test",
"new test new tes tnew test new test new tes tnew test new test new tes tnew test new test new tes tnew test new test new tes tnew test new test new tes tnew test",
sep=" ")

paragraph1
```

But, both the code chunk and the result in the PDF document have the text in just one line, that continues out of the page. It doesen't breaks the paragraph in multiple lines. 

Its possible to wrap the text inside the margins of the document?

tks,
Rafael

**Comment by DanielEWeeks** [comment]
Does this help?

```
```{r,echo=FALSE,message=FALSE,warning=FALSE}
require(knitr)
# Set so that long lines in R will be wrapped:
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```
```

**Comment by yihui** [comment]
@DanielEWeeks No, `tidy = TRUE` cannot break a long character string into lines of a certain width.

You have to manually break the long string into shorter ones, or customize the `Shaded` or `Highlighting` environment in LaTeX so the long lines can be wrapped automatically. I know the **listings** package in LaTeX can do this, but I have no idea how to apply **listings** to these environments (generated by Pandoc).

**Comment by LechMadeyski** [comment]
Hi! An easy workaround would be to use `tabular` environment:
\begin{tabular}{|p{1.00\linewidth}|}
```R
<<...>>=
...
paragraph1
@
```
\end{tabular}

**Comment by ulyngs** [comment]
Another easy workaround that I use in [`oxforddown`](https://github.com/ulyngs/oxforddown) is this:

```r
library(knitr)
hook_output = knit_hooks$get('source')  #this is the output for code

knit_hooks$set(source = function(x, options) {
  # use if the output is PDF and you set an option linewidth to e.g. 70
  # in the chunk options
  if (!is.null(n <- options$linewidth) & knitr::is_latex_output()) {
    x <- strwrap(x, width = n, exdent = 4)
  }
  hook_output(x, options)
})
```

(For an example, I use this to wrap a long LaTeX command shown on page 28 of the sample PDF: https://github.com/ulyngs/oxforddown/blob/master/docs/_main.pdf )

**Comment by biologisturiel** [comment]
This doesn't work for me, until I install the "formatR" package.
Also, I realized that it applied in all chunks, except the one that was written, so create one, only with: 
```{r, echo = F}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

**Comment by yihui** [comment]
For anyone who still comes to this issue, you may read:

- https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html
- https://bookdown.org/yihui/rmarkdown-cookbook/opts-tidy.html

**Comment by apriljkissinger** [comment]
> This doesn't work for me, until I install the "formatR" package.
> Also, I realized that it applied in all chunks, except the one that was written, so create one, only with:
> 
> ```
> ```{r, echo = F}
> library(knitr)
> opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
> ```
> ```

Thank you so much! It worked!

**Comment by dansmith01** [comment]
Here's everything put together with an example.

1. Install `formatR` (otherwise the wrapping quietly fails).
2. Set both `tidy=TRUE` and `tidy.opts=list(width.cutoff=60)` for the code chunk.

```rmarkdown
```{r, tidy=TRUE, tidy.opts=list(width.cutoff=60)}
ggboxplot(data = df, x = "clarity", y = "price", fill = "clarity", palette = c("#4682b4", "#ffff00", "#ff82ab"), facet.by = c("cut", "color")) + geom_bracket(aes(xmin = group1, xmax = group2, label = p.adj), data = stats, step.increase = 0.2, step.group.by = c("cut", "color"), y.position = 21000) + scale_y_continuous(expand = expansion(mult = c(NA, 0.15)))
```

Screenshot of PDF output:
<img width="488" alt="wrapping" src="https://user-images.githubusercontent.com/2066273/111661512-5095ba00-87cc-11eb-862a-ed60605f7215.png">

**Comment by yihui** [comment]
@dansmith01 With the dev version of **formatR**, you may also try `width.cutoff = I(60)` so that **formatR** will try to enforce the maximum line width 60 instead of the minimum.

```r
remotes::install_github('yihui/formatR')
```

**Comment by quantitative-technologies** [comment]
> Does this help?
> 
> ```
> ```{r,echo=FALSE,message=FALSE,warning=FALSE}
> # Set so that long lines in R will be wrapped:
> knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
> ```
> ```

Does nothing.

**Comment by quantitative-technologies** [comment]
> @dansmith01 With the dev version of **formatR**, you may also try `width.cutoff = I(60)` so that **formatR** will try to enforce the maximum line width 60 instead of the minimum.
> 
> ```r
> remotes::install_github('yihui/formatR')
> ```

None of these solution seems to break a very long line such as

    x <- 'This is a very very very very very very very very very very very very very very very very very very very very very very very very long text'

This LaTeX package `listings` discussed in the cookbook works, but it destroys the formatting. Is there any other way?

**Comment by xf15** [comment]
> This doesn't work for me, until I install the "formatR" package.
> Also, I realized that it applied in all chunks, except the one that was written, so create one, only with:
> 
> ```
> ```{r, echo = F}
> library(knitr)
> opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)
> ```
> ```

this doesn't work for me, i did `update.packages(ask = FALSE, checkBuilt = TRUE)`

**Comment by xf15** [comment]
@quantitative-technologies 
> > @dansmith01 With the dev version of **formatR**, you may also try `width.cutoff = I(60)` so that **formatR** will try to enforce the maximum line width 60 instead of the minimum.
> > ```r
> > remotes::install_github('yihui/formatR')
> > ```
> 
> None of these solution seems to break a very long line such as
> 
> ```
> x <- 'This is a very very very very very very very very very very very very very very very very very very very very very very very very long text'
> ```
> 
> This LaTeX package `listings` discussed in the cookbook works, but it destroys the formatting. Is there any other way?


the wrapping works for a comment not code 
> When there is a super long element that cannot be broken in the code, such as a long variable name or a character string, setting the maximum width is likely to fail.

from https://yihui.org/en/2021/06/formatr-news/

**Comment by ulyngs** [comment]
The solution I use in [`oxforddown`](https://github.com/ulyngs/oxforddown/commit/ee17c2fff6d5df37df972936dd9df25866c088bb) is to simply include the `fvextra` latex package.

Here's an example:

# **some-rmd-file.Rmd**

````
---
output: 
  pdf_document:
    includes:
      in_header: "wrap-code.tex"
---

# Breaking a long line

```{r}
x <- 'This is a very very very very very very very very very very very very very very very very very very very very very very very very long text'
```
````

# wrap-code.tex
```latex
\usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
```

<img width="693" alt="image" src="https://user-images.githubusercontent.com/23137032/134673558-8cd51cc0-e111-4bd8-ac41-b0f64db30334.png">

**Comment by benyamindsmith** [comment]
> The solution I use in [`oxforddown`](https://github.com/ulyngs/oxforddown/commit/ee17c2fff6d5df37df972936dd9df25866c088bb) is to simply include the `fvextra` latex package.
> 
> Here's an example:
> 
> # **some-rmd-file.Rmd**
> ```
> ---
> output: 
>   pdf_document:
>     includes:
>       in_header: "wrap-code.tex"
> ---
> 
> # Breaking a long line
> 
> ```{r}
> x <- 'This is a very very very very very very very very very very very very very very very very very very very very very very very very long text'
> ```
> ```
> 
> # wrap-code.tex
> ```
> \usepackage{fvextra}
> \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
> ```
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/23137032/134673558-8cd51cc0-e111-4bd8-ac41-b0f64db30334.png">

I can confirm this does work!
