### ISSUE TITLE
External package guessing output format

### ISSUE THREAD

**Issue by zeehio** [rstudio/rmarkdown#649]
Thanks for your time and effort on both `rmarkdown` and `knitr`.

Let's say I have a package with a function that returns an S3 object:

``` r
new_myclass <- function() {
  return(structure(list(a=1, b=2), class = "myclass"))
}
```

I also have two functions that take a `myclass` object and return respectively a HTML representation and a LaTeX representation of the object.

``` r
myclass2html <- function(obj) { return("<p>MyClass object</p>")}
myclass2latex <- function(obj) { return("\begin{em}MyClass\end{em} object $x$")}
```

What functions/methods should I define to provide consistent and transparent `knitr` and `rmarkdown` support? I would like to support both `.Rmd` files and `.R` files with a header like:

``` r
#'---
#' title: My document
#' output: pdf_output
#'---
```

So far my approach is:

``` r
#' @importFrom rmarkdown metadata
#' @importFrom knitr opts_knit
guess_output_format <- function() {
  rmd_output <- tryCatch({rmarkdown::metadata$output},
                         error = function(e) {NULL})
  if (is.null(rmd_output)) {
    rmd_output = ""
  }
  if (is.list(rmd_output)) {
    rmd_output <- names(rmd_output)[1]
  }
  if (rmd_output == "pdf_document") {
    return("latex")
  } else if (rmd_output %in% c("html_document", "html_vignette")) {
    return("html")
  } else if (rmd_output != "") {
    return("")
  }
  # No rmarkdown, let's try with knitr:
  format <- knitr::opts_knit$get("out.format")
  if (format %in% c("html", "markdown")) {
    return("html")
  } else if (format %in% c("latex")) {
    return("latex")
  } else {
    return("")
  }
}
```

My main issue is that there may be two variables `rmarkdown::metadata$output` and `knitr::opts_knit$get("out.format")` that may or may not be defined (depending on whether or not `rmarkdown` is being used). I find this confusing.
- What is the right way to know the output format?
- Is there a `get_output_format` function that tells me the output format? 

To put the question in context, I am working on the [condformat](http://www.sergioller.com/2016-03-10-condformat-release.md) package that allows to visualize DataFrames with conditional formatting rules.

This question has been asked also in [stackoverflow](http://stackoverflow.com/questions/36044610/print-custom-object-in-rmarkdown-and-knitr-pdf-and-html) without answer in several days.

Thanks for any piece of advice

**Comment by jjallaire** [comment]
We define some knitr options that give you the pandoc to and from formats:

https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L246-L252

Note that getting the *name* of the output format isn't that helpful as
there could be dozens of output formats you'd need to write code to
determine whether they are HTML or PDF. I'd say you should check the
output.to and look for "latex" or "beamer" to discover PDF output and then
assume HTML for everything else (i.e. don't try to emit RTF, ODF, MS Word,
markdown, etc.).

**Comment by zeehio** [comment]
Thanks @jjallaire, `rmarkdown.pandoc.to` makes things easier to me.

To make it better to future developers, would you accept a pull request to export `knitr:::is_html_output`, `knitr:::is_latex_output`, `knitr::escape_html` and `knitr:::escape_latex`? (or at least the first two?)

Otherwise I am happy enough with my approach:

- If format is either "latex" or "beamer" then: output to LaTeX 
- If format is either "html" or starts with "markdown" (many markdown flavours!) then: output to HTML
- Else: Use a generic output (I forgot to mention I have one) 

```r
#' @importFrom rmarkdown metadata
#' @importFrom knitr opts_knit
guess_output_format <- function() {
  outfmt <- knitr::opts_knit$get("rmarkdown.pandoc.to")
  if (is.null(outfmt)) {
    outfmt <- knitr::opts_knit$get("out.format")
  }
  if (is.null(outfmt)) {
    return("") # not in knitr
  }
  if (outfmt %in% c("latex", "beamer")) {
    return("latex")
  } else if (outfmt == "html" || substr(outfmt, 1, nchar("markdown")) == "markdown") {
    return("html")
  } else {
    return("unsupported") # uses a generic fallback
  }
}
``` 

Here is in its [context](https://github.com/zeehio/condformat/blob/master/R/condformat_render.R#L72)

**Comment by jjallaire** [comment]
@yihui, maybe we could even have a function like this:

knitr::current_output_type()

Which returns either "latex", "html", "markdown", or "unknown"

**Comment by yihui** [comment]
Okay, I'll consider exporting some of these functions from knitr.

**Comment by yihui** [comment]
I have exported `is_latex_output` and `is_html_output` in the dev version of **knitr**.

**Comment by hughjonesd** [comment]
Actually, it *would* be useful for package authors to get the name of the current output format. For example, `bookdown` uses a special reference scheme for tables. I currently detect this by looking at
`rmarkdown::default_output_format(knitr::current_input())`. That can be wrong if the default format is not what is being knitted.
