### ISSUE TITLE
Custom formatting h1, h2 in

### ISSUE THREAD

**Issue by dmenne** [rstudio/rmarkdown#652]
The following was posted in http://stackoverflow.com/questions/36162188/formatting-h1-h2-in-rmd-rmarkdown but there was only one partial response by Lazane and one by Aziz:

With an external css file, I can change many items in an Rmd/html document, but some basic ones are overridden by inline css inserted by markdown (?). 

```
    .main-container {
    ....
    h1 {
      font-size: 34px;
    }
    h2 {
      font-size: 30px;
    }

```

So the only way to change h2 font size is by inserting the style code directly into the document, which is ugly:

```
---
output: 
  html_document:
    theme: cosmo
   # css: whatever.css # adding h2 here does not work
---

<style type = "text/css">
h2 {color: red;}
</style>

## R Markdown
```

Suggestions were: (Lazane)

```
h2{
  font-size: 14px !important;
}
```
which works, but !important is considered bad style. And

```
h2[style] { color: blue !important; }
```
Which I could not get to work.

Why is there an inline css at all that cannot be overridden? 

Suggestion: remove it from inline section.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rmarkdown/commit/d8c027763b29348abce76213a5dd9dcd7144ccd6
