### ISSUE TITLE
Equation disappears in HTML output but fine with PDF format

### ISSUE THREAD

**Issue by henrywoo** [rstudio/rmarkdown#657]
I used Latex for equation as below, which works fine for PDF output

```
\begin{equation}
\begin{aligned}
\sigma_{T}^2 =  \sum\limits_{i=1}^N [Q_{t_i} - Q_{t_{i-1}}] ^2  \label{eq:rv}
\end{aligned}
\end{equation}
```

But in html format, the equation disappears. Can anybody tell me how to make it work for both PDF and HTML output? Thanks a lot.

**Comment by yihui** [comment]
This is not reproducible to me. Please report `rmarkdown::pandoc_version(); sessionInfo()`.

**Comment by henrywoo** [comment]
Thanks Yihui! I encountered this issue in both linux and windows. The following is my result in Linux:

```
> rmarkdown::pandoc_version(); sessionInfo()
[1] ‘1.13.2.1’
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] htmltools_0.3   rmarkdown_0.9.2 digest_0.6.9   
```

**Comment by yihui** [comment]
I think you need to upgrade at least Pandoc. If you installed Pandoc separately, do not use the version of Pandoc from the Ubuntu repository: it is often way too old. Pandoc has provided its own deb package: http://pandoc.org/installing.html Alternatively, use a recent version of RStudio IDE. Your R packages seem to be outdated as well, although that should not hurt in this case.

**Comment by henrywoo** [comment]
Issue is solved. Thanks Yihui. You are the man!
