### ISSUE TITLE
Abnormal use of resources when using download function from package downloader

### ISSUE THREAD

**Issue by simonkth** [rstudio/rmarkdown#659]
Hello,

I encountered an issue when using the _download()_ function from package _downloader_ in a Rmd document (see code below). It is not such a big issue and there is an easy fix, but I just wanted to report it.

```{r dl_clean, message=FALSE}
# load packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(downloader, data.table, dplyr)

# download and load the data (Windows setup)
if(!file.exists("./data/insertion_raw.csv")) {
      if(!file.exists("./data")) {dir.create("./data")}
      dataUrl <- paste0("https://data.enseignementsup-recherche.gouv.fr/explore/dataset/", 
                        "fr-esr-insertion_professionnelle-master/download?format=csv")

      download(dataUrl, dest="./data/insertion_raw.csv", mode="wb")
} else message("The dataset had previously been downloaded.")
```

In this case, _download.file()_ would report a warning: “downloaded length 978696 != reported length 200”. I use the _downloader::download()_ function instead and it suppresses this warning but the download bar continues further than 100%. When using Knit HTML this results in an endless printing of “=” signs in the R Markdown pane of R Studio. During this time on my computer (Dell XPS 13), R Studio proc usage becomes abnormally high, and the application stops responding. After a few minutes it stops freezing and the html document is successfully compiled, but R Studio remains unstable until you close and restart it (evaluation of R code can become very slow).

Specifying quiet=TRUE avoids this issue.

```{r dl_clean2, message=FALSE}
download(dataUrl, dest="./data/insertion_raw.csv", mode="wb", quiet=TRUE)
```

**Comment by yihui** [comment]
Thanks the report! I guess that was due to the text progress bar of `download()`. I'm not to explain this in great technical detail, but basically the progress bar produced a huge amount of text output (the progress bar will behave different in the R console vs knitr documents).

What is your R version? I just tried `download.file(dataUrl, 'test.csv')` and it worked fine with R 3.2.4 on OS X.

**Comment by simonkth** [comment]
I use R 3.2.3 on Windows 10. But actually I just updated to RStudio 0.99.893, the behavior changed a little bit. There is still a lot of output text in the R Markdown console but RStudio doesn't crash anymore. However, there is a big lag when you switch between consoles after this, until you knit once again and it cleans the R Markdown console.
