### ISSUE TITLE
\maketitle in generated .tex (->pdf) even when no title is present

### ISSUE THREAD

**Issue by fabiangehring** [rstudio/rmarkdown#660]
Hi, 

Even when not specifying a title or explicitely specifying title: false in the yaml block, the generated .tex contains "\maketitle". This surprised me and causes some troubles with vertical space.

this surprised me, since in the template the following block can be found:

```
$if(title)$
\maketitle
$endif$
```

Is this intended?

**Comment by fabiangehring** [comment]
using an old pandoc-version here. It seems as if the if around \maketitle was added in the newer default-x.xx.tex. Any reason why not adding it in default.tex as well?

**Comment by yihui** [comment]
This was an oversight. I just added it. Thanks!
