### ISSUE TITLE
ioslides not handling sofbreaks

### ISSUE THREAD

**Issue by mtorchiano** [rstudio/rmarkdown#661]
When generating ioslides from rmd soft-breaks (i.e. newlines added just to rearrange content are not handled correctly.

```
---
title: "Bug new line"
output: ioslides_presentation
---
## R Markdown

* If I write a bullet list element
  with a new-line in it is is not rendered correctly
```

In the output the word _element_ and the word _with_ are present **without** a separating space.

**Comment by yihui** [comment]
Fixed by #661.
