### ISSUE TITLE
Square brackets

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#667]
There's an odd interaction re: escaping of square brackets for markdown output and RStudio html preview.

Let's say this text appears in an Rmd:

```
A reference to cell B2 in an expression in cell C3 can be written as R[-1]C[-1].
```

If this is the yaml:

```
---
output:
  html_document:
    keep_md: true
---
```

The text is unchanged in the intermediate markdown. Specifically, the square brackets are unchanged. The RStudio html preview looks as expected = good.

But if this is the yaml:

```
---
output: md_document
---
```

The square brackets are escaped in the resulting markdown:

```
A reference to cell B2 in an expression in cell C3 can be written as is
also R\[-1\]C\[-1\].
```

If I then open that md in RStudio and knit it, the RStudio html preview looks goofy. The most efficient way to do that is to use this yaml instead:

```
---
output: github_document
---
```

Here's the goofy html preview:

<img width="618" alt="screen shot 2016-04-08 at 9 59 29 am" src="https://cloud.githubusercontent.com/assets/599454/14391404/a444e1ee-fd70-11e5-9f18-a267346ec1ee.png">

All of this markdown looks as expected on GitHub and all html files look as expected in Safari.

Why do the backslashes get added when output format is explicitly markdown? Given that they're there, why do they confuse the RStudio html preview?

I put my little experiment here: <https://github.com/jennybc/square-brackets>.

**Comment by jjallaire** [comment]
I think the problem is that the backslashes are getting (correctly) escaped when converting to markdown_strict (since brackets have formatting meaning in markdown escaping them with `\` makes it clear that they aren't formatting). However, when converting to HTML for the RStudio preview the `\[foo`\]` sequence is getting interpreted as a MathJax equation!

I think that the best way to avoid this is to just include the bracket sequences as inline code (e.g. `R[-1]C[-1]`)

**Comment by jennybc** [comment]
That's what I've been doing, so will carry on. This phenomenon also happens within tables, which is where I found it. The inline code approach is more inconvenient there but I will just do it.

I'm having related problems with dollar signs (e.g. cell B$14) but only inside tables and in that case escaping the `$` is the solution, not the problem (https://github.com/yihui/knitr/issues/1182).
