### ISSUE TITLE
Reference docx styles are renamed when using Word in another language than English

### ISSUE THREAD

**Issue by semuelle** [rstudio/rmarkdown#668]
I am trying to style my R report by editing the Word styles in the knitted Word document, then using it as a `reference_docx`. Like so:

```

---

title: "Untitled"
author: "My name"
date: "11. April 2016"
output: 
  word_document:
          reference_docx: test.docx

---

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
```

However, Word seems to rename the styles to their German equivalent, so that all headings and some other styles are not assigned any style anymore when using the reference docx, as seen in

![this screenshot](http://i.imgur.com/e4v5vpS.png).

Is this known? Does anyone know a workaround?

**Comment by yihui** [comment]
I'm afraid we cannot do anything about it. It is either a Pandoc issue or a Word issue.

**Comment by Cullrich** [comment]
I have the same issue with a French Microsoft Office. If someone found a workaround I am interested

Thanks in advance

**Comment by izmartinez** [comment]
I had the same issue. Changing the default language of Word fixed the problem!
Under 
File > Options > Language 
I changed the display language and the help language to English.
Hope this helps!
