### ISSUE TITLE
Install and config pandoc to use in R terminal (RStudio is not allowed to install)

### ISSUE THREAD

**Issue by ThoDuyNguyen** [rstudio/rmarkdown#669]
I make a dynamic report generator Shiny app. 
It used `rmarkdown::render` to make html report.
When i test the app in R console, it seems that my R could not find pandoc though I have installed it. 

I have read this [link](https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md). 

Is there some way to config pandoc so that R terminal could use `rmarkdown::render` to generate html document from .Rmd. 

My production server is not allowed to install RStudio, only Shiny Server is allowed.

**Comment by yihui** [comment]
Please see #1008. The bin path of Pandoc needs to be on the PATH variable. You can either update the PATH variable of your system, or use `Sys.setenv()` in R.
