### ISSUE TITLE
Knitting causes settings in par("mar") and par("mai") to change

### ISSUE THREAD

**Issue by jmichaelgilbert** [rstudio/rmarkdown#670]
Knitting the 'issue' file below in RMD causes the `par("mar")` and `par("mai")` settings to change (without explicitly calling or asking them to). However, knitting the 'no issue' file below in RMD, these settings do not change and retain their default values. The options and setting between the files appear identical, with the only difference being the 'no issue' file is shorter in terms of lines of code.

I have searched Google and StackOverflow but cannot find a similar issue or question. No clue what's going on, only noticed it because my produced plots looked really wonky.

Apologize that the reproducible code where this occurs is a bit lengthy, it's the only instance I could get it to occur. However, the code should be fully self-contained and reproducible. Can include `sessionInfo()` if helpful, but on the latest official release of R Studio, R, and all packages are up to date.

No Issue: [raw code](https://raw.githubusercontent.com/jmichaelgilbert/mspaScripts/master/RMD_Test_Code.Rmd) on GitHub; [PDF of output](https://www.dropbox.com/s/46glym0bncvtds6/RMD_Test_Code.pdf?dl=0)
Issue: [raw code](https://raw.githubusercontent.com/jmichaelgilbert/mspaScripts/master/422_Programming_Assignment_02.Rmd) on GitHub; [PDF of output](https://www.dropbox.com/s/o3rlfnqsw9qc6v5/422_Programming_Assignment_02.pdf?dl=0)

Both calls to check the `par("mar")` and `par("mai")` values appear at the end of the code and output documents. The graphs that are wonky in the 'issue' file appear throughout. Any thoughts or guidance is greatly appreciated.

Michael

**Comment by yihui** [comment]
I believe this is an issue of the corrplot package and I have fixed it a while ago: https://github.com/taiyun/corrplot/pull/54 Please just install its development version: https://github.com/taiyun/corrplot

又一个碰到跟您同样问题的人了 @LiXinyi

**Comment by jmichaelgilbert** [comment]
Thanks for the quick reply. Worked perfectly. Is there a central page that lists 'known package issues' or the like on it? Even something like a simple bulleted list would be great. Happy to help if needed.

Michael

**Comment by yihui** [comment]
I'd urge @taiyun to make a new release of corrplot to CRAN.
