### ISSUE TITLE
Trouble embedding iframe tags using rmarkdown 0.9.5

### ISSUE THREAD

**Issue by lcolladotor** [rstudio/rmarkdown#671]
Hi,

The following simple R Markdown file used to embed an iframe. 

```
---
output:
  html_document:
    theme: united
---

[L. Collado-Torres](http://bit.ly/LColladoTorres) Curriculum vitae
================

<iframe src="http://docs.google.com/viewer?url=http://lcolladotor.github.io/cv/en_CV_lcollado.pdf&embedded=true" width="900" height="780" style="border: none;"></iframe>
```

[Source](https://github.com/lcolladotor/cv/blob/gh-pages/index.Rmd) that rendered into [this html file](https://github.com/lcolladotor/cv/blob/gh-pages/index.html).

However using `rmarkdown` version 0.9.5 and `pandoc` 1.17.0.3, the iframe tag is not working as intended. I modified my original Rmd file to add some version info and uploaded the resulting html file at https://gist.github.com/lcolladotor/0cc9014d1591d38b7ebf20140842d1a9. 

The error is fairly simple. At https://gist.github.com/lcolladotor/0cc9014d1591d38b7ebf20140842d1a9#file-index-html-L116 we can see that `<` got changed into `&lt;` and put inside a `<p>` tag.

Best,
Leo

**Comment by yihui** [comment]
Replace `&` with `&amp;` in the iframe URL, otherwise it is not valid HTML to Pandoc so it will be treated as normal text.

**Comment by lcolladotor** [comment]
Thanks Yihui!
