### ISSUE TITLE
Set option hooks

### ISSUE THREAD

**Issue by aoles** [rstudio/rmarkdown#672]
Is there a way of setting option hooks `knitr::opts_hooks` in rmarkdown documents? I didn't find a corresponding argument to `rmarkdown::knitr_options`.

I would like to change certain chunk options according to the values of other chunk options, as described at http://yihui.name/knitr/hooks/#option_hooks. For example, to achieve the behavior described in the example presented  there.

**Comment by jjallaire** [comment]
You can just use knitr_options$knitr_hooks, e.g.
https://github.com/rstudio/flexdashboard/blob/master/R/flex_dashboard.R#L144-L164

**Comment by aoles** [comment]
I would like to override the default `fig.width` and `fig.height` options for the code chunks which have set a certain `fig.env`. In **knitr** I could achieve this by changing `fig.width` and `fig.height` in `knitr::opts_hooks`. Is there no similar mechanism in **rmarkdown** to change the device dimensions of the current code chunk according to the code chunk options?

**Comment by jjallaire** [comment]
You can just set knitr hooks right inside your Rmd I believe (e.g. in the
setup chunk). @yihui am I missing something there? (i.e. rmarkdown is knitr
so anything you can do in knitr you should be able to do in rmarkdown)

**Comment by yihui** [comment]
@jjallaire You are right. Just do it in the first code chunk in R Markdown, e.g.

    ```{r setup}
    knitr::opts_hooks$set(fig.width = function(options) {
      if (options$fig.width < options$fig.height) {
        options$fig.width = options$fig.height
      }
      options
    })
    ```

This does not really require special support in rmarkdown.

**Comment by aoles** [comment]
@yihui @jjallaire thank you for your help!

I wasn't quite specific before. What I actually would like to achieve is to set `knitr::opts_hooks` in a new output format function which extends `pdf_document`, rather than from a code chunk within the document itself. So far I was able to set things via the interface provided by `output_format`. I was puzzled to find out that all knitr hooks but the `opts_hooks` can be provided in the `knitr` argument to `output_format`. It seems that this deficiency can be easily fixed, see https://github.com/rstudio/rmarkdown/pull/674.

As I mentioned before, I would like to create a new LaTeX-based output format for Rmd documents providing different figure environments for output plots. These environments would differ in their size and aspect ratio, say small square plots and landscape full-width plots. In order to get this work I need to change the `fig.width` and `fig.height` of the current code chunk according to `fig.env`. Not being able to set `opts_hooks` in my format function is kind of a show-stopper for me right now. Therefore it would be great if you would consider the fix suggested in my pull request. Thanks!
