### ISSUE TITLE
Access document YAML metadata in output format function

### ISSUE THREAD

**Issue by aoles** [rstudio/rmarkdown#673]
Is it possible to access YAML metadata of the current R Markdown document inside an output format function? I tried to use `rmarkdown::metadata` for this purpose but the returned list is empty at the time the format function is run. 

The motivation for this is, for example, to adjust `"width"` in `opts_knit` according to `fontsize` specified in the YAML header.

**Comment by jjallaire** [comment]
The metadata unfortunately isn't known at the time when the format function
is called.
