### ISSUE TITLE
Display ```{r} or `r ` in knitted file

### ISSUE THREAD

**Issue by gingershuying** [rstudio/rmarkdown#675]
Dear all, 
   I am using rmarkdown to write a teaching material of rmarkdown for my students. I want to show them how to put R code blocks in a rmd file. Therefore I want to put for example
```
```{r}
summary(cars)
```
```
with the ```{r} and ```displaying or 
`r 2+3`
with `r ` displaying.

However, I can't successfully make it work. Could anyone please tell me how to make it work? Thanks in advance!

**Comment by yihui** [comment]
Please see knitr FAQ 8: https://bit.ly/knitr-faq
