### ISSUE TITLE
Error: Runtime 'autostaticshiny' is not supported ...

### ISSUE THREAD

**Issue by jennybc** [rstudio/rmarkdown#677]
If I have a markdown document `foo.md` with `output: github_document` in the YAML, I get this error when I render (via RStudio IDE or `rmarkdown::render("foo.md")`):

```
Error: Runtime 'autostaticshiny' is not supported for markdown_github output.
Please change the output type of this document to HTML.
```

Why do I even do this? [1] I like to first-draft markdown w/o worrying about the GitHub-flavor and then I do this to get GFM; [2] I like the HTML preview behaviour (see #628).

If I rename the file `foo.Rmd`, all is well, which is I suppose how this output format is intended to be used. Maybe I get what I deserve....

Versions:

```
rmarkdown   0.9.5.9 2016-04-18 Github (rstudio/rmarkdown@6a71abe)
RStudio IDE Version 0.99.1130 (Mac OS)
```

**Comment by jjallaire** [comment]
Yeah, you are definitely supposed to start with Rmd for this format. One
important reason why is the filename (i.e. when we render .md to .md we'd
overwrite the input file with the output file.

Note that a "knit" of an Rmd with no code chunks is basically a no-op. As a
result we've definitely let the .md mode go a bit (e.g. no document
outline). I'd strongly recommend just authoring in .Rmd

**Comment by jennybc** [comment]
OK thanks. I will modify my behavior/expectations accordingly.
