### ISSUE TITLE
Table captions after table

### ISSUE THREAD

**Issue by wuffi** [rstudio/rmarkdown#678]
Hello everybody out there using R Markdown,

When compiling a R Markdown file with knitr chunks to docx format using R Studio, the caption of the table's get placed before the tables.
However, when keeping the (pure) markdown file, which is generated from the R Markdown file, the caption of the table is placed after the table. Calling pandoc, I get a docx file with the caption of the table after the table itself.
Therefore I conclude, that R Studio is calling pandoc in a way that it puts table captions before the table themselves, although the opposite behaviour seems to be pandoc's default option.
Could anyone help me in finding out where to find this switch in order to change the behaviour according to my needs. It would be good to document this feature and how to change it.

Best

**Comment by jjallaire** [comment]
If you could provide us with exact repro steps/documents that would be helpful (i.e. the simplest possible md/Rmd documents which exhibit the problem, the exact pandoc command line you used, and the output of the following:

From R: ` rmarkdown::pandoc_version()`

From the command line before you call pandoc `pandoc --version`

**Comment by wuffi** [comment]
Hi,
Sorry for not reporting the versions:
`rmarkdown::pandoc_version() 1.15.2`
`pandoc --version 1.12.3.3`

A minimal document can consist just of the following code chunk:
```{r table, echo=FALSE}
library(pander)
set.caption("Sample table")
pander(head(iris))
```

**Comment by jjallaire** [comment]
The differing pandoc version is likely the issue. You should use a newer
version of pandoc when invoking from the shell

**Comment by wuffi** [comment]
Thanks a lot for your answer. Upgrading to a newer version of pandoc for the shell would actually result in the opposite result I want - then, the captions would also be placed before the tables in that case. Actually I would need to downgrade the pandoc version RStudio uses.
What I am actually looking for is an option to put the captions after the table in the docx documents like it used to be done with the older versions of pandoc.

**Comment by jjallaire** [comment]
I think that's something you'll need to report to pandoc to see if they can
provide an option for the older behavior to be restored. You may also want
to look into creating a custom reference.docx which has the "Table Caption"
style that you are seeking.
