### ISSUE TITLE
a few figures are swapped between chunks

### ISSUE THREAD

**Issue by julou** [rstudio/rmarkdown#684]
Hello,

I'm using markdown site to glue several data analysis reports and already love it!
I recurrently face the following issue (and couldn't find any issue matching "_site fig_"): after rendering long rmd files with many chunks (typically 30 plots in total), I usually get one or two figures out of nowhere (e.g. plot 3 of chunck 6 shown in another chunk at a random position; yesterday I even got a figure from another page of the same site!).

I use the following workflow: in a .R file, I load packages, data, etc. Then I call `render_site` once for each analysis file (because I want the knitting to occur in the parent environment since these files correspond to consecutive steps of the analysis). Something like:

```
rmarkdown::clean_site()
rmarkdown::render_site('index.Rmd')
rmarkdown::render_site('page1.Rmd')
rmarkdown::render_site('page2.Rmd')
```

I didn't try to come up with a minimal reproducible example yet… Thanks for your help,
Thomas

**Comment by yihui** [comment]
I'm afraid it is hard to tell what was wrong without a reproducible example...

**Comment by julou** [comment]
I didn't take time to come up with a minimal example but I noticed that the problem disappears when I comment out all `ggsave` calls in the .Rmd documents.
Any chance that using `ggsave` might be giving `rmarkdown::render_site` a hard time with pictures? If yes, it would be convenient to fix this…

**Comment by yihui** [comment]
In the R Markdown world, it should be very rare that you actually need `ggsave()`, since all your plots will be automatically saved.
