### ISSUE TITLE
404 errors only in Firefox

### ISSUE THREAD

**Issue by trestletech** [rstudio/rmarkdown#69]
(Not sure if this is an RMarkdown or RStudio issue)

But the "Open in Browser" link when using Shiny+Rmd doesn't seem to work in Firefox (28.0) in Windows (7).

The same URL opens just fine in Chrome and, of course, in the preview WIndow.

![rmd-ff](https://cloud.githubusercontent.com/assets/1593639/2790838/319fdd58-cbc0-11e3-941e-46b19903ee19.png)

**Comment by herrdeh** [comment]
Appears on firefox 36.0 for ubuntu (14).
