### ISSUE TITLE
Breaking out of tabset without creating a new header

### ISSUE THREAD

**Issue by jtlawren** [rstudio/rmarkdown#692]
I'm trying to have a single body of text appear under two different tabsets without creating a new header.  Not sure whether or not there is a way to do this.

Two things that work functionally are just defining a new blank header and placing the text there (but this also creates a blank table of contents entry which I don't want) and copying the text into both tabs in the tabset (but this is cumbersome if I need to edit the block of text).

Here is an example of what I'd like to do and the issue:
```R
---
title: "Test"
output: html_document
---

# I'm a main header {.tabset}

## The First Tab
I'm the first tab

## The Second Tab
I'm the second tab

I'm text that I would like to have under both tabs!!!
But I only appear under the second tab :-(
```

**Comment by jjallaire** [comment]
You need to create a new section to break out of the tabset. So for example:

```
# I'm a main header {.tabset}

## The First Tab
I'm the first tab

## The Second Tab
I'm the second tab

#

I'm text that I would like to have under both tabs!!!
But I only appear under the second tab :-(

```

**Comment by jtlawren** [comment]
Would there then be a way to prevent that empty section break (#) from causing a blank bullet point in the TOC?

**Comment by jjallaire** [comment]
Unfortunately there isn't a clean way to do this.

Here's the unclean way to do it:

```html
<div class="section level1 tabset">

<div id="first-tab" class="section level2">
<h2>The First Tab</h2>
I'm the first tab
</div>

<div id="second-tab" class="section level2">
<h2>The Second Tab</h2>
I'm the second tab
</div>

</div>

I'm text that I would like to have under both tabs!!!
But I only appear under the second tab :-(
```

**Comment by jtlawren** [comment]
Got it!

Thank you!
