### ISSUE TITLE
Title starting with enumerate generates error

### ISSUE THREAD

**Issue by strongway** [rstudio/rmarkdown#694]
When rmarkdown title starting with numbering, such as 

```
---
title: "1. Subtopic"
---
```

Knit PDF will generate a error: 

```
! Argument of \reserved@a has an extra }.
<inserted text> 
                \par 
l.109 \end{enumerate}}
```

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
Execution halted

**Comment by yihui** [comment]
You can escape the period to prevent Pandoc from translating it to an enumerate item, e.g.

```
---
title: "1\\. Subtopic"
---
```
