### ISSUE TITLE
Problems with DataTables Fixed Header Extension with {.tabset}

### ISSUE THREAD

**Issue by smmurphy** [rstudio/rmarkdown#695]
I am working on an Rmd report that includes 4 tables rendered using the `DT` package and the `datatables()` function, with the `FixedHeader` extension.  Everything works perfectly when the document is rendered as one long page, or even as a long page with a floating toc.  When I add {.tabsets}, however, the FixedHeader from the first table on the page switches with the headers of subsequent tables as I scroll.  When I start scrolling the correct header appears and then switches to the header of the first table as I continue scrolling.  If I click on the fixed header at this point it will cycle through the headers of the different tables each time I click.  This may be a better issue for DT and I will cross post there, but since this seems to occur exclusively with tabs I thought I would start here.  Any thoughts about what might be causing this or suggestions on how this issue might be addressed?

**Comment by yihui** [comment]
Closed here in favor of https://github.com/rstudio/DT/issues/285
