### ISSUE TITLE
toc_float and sideways scrolling

### ISSUE THREAD

**Issue by and3k** [rstudio/rmarkdown#696]
Hi!

when I have HTML documents where I can scroll sideways/horizontal (happens with wide tables, etc), the floating TOC stays fixed on the screen, and not fixed relative to the content. It’s then hidden behind code boxes and everything else that is transparent.

IMHO it should stay were it is on the left side.

Thanks!
Bela

**Comment by yihui** [comment]
This looks like a CSS question, so please consider [asking it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead, like this one https://stackoverflow.com/q/3303173/559676. Thanks!
