### ISSUE TITLE
github_document does not seem to read trailing white spaces correctly 

### ISSUE THREAD

**Issue by M-E-Steiner** [rstudio/rmarkdown#698]
Yesterday I posted [this](http://stackoverflow.com/questions/37187641/two-space-line-break-doesnt-work-on-github-when-converting-rmd-to-md-using-git?noredirect=1#comment61915371_37187641) question on StackOverflow. 

Is this a bug? If not. What am I doing wrong?

Thanks, and keep up the great work!

**Comment by jjallaire** [comment]
Just answered on SO
