### ISSUE TITLE
render won't overwrite open html files or files it has previously failed to overwrite?

### ISSUE THREAD

**Issue by Henry-E** [rstudio/rmarkdown#699]
RMarkdown appears to no longer overwrites open html files. I've tried this on a couple of different machines and with lots of different files. As recently as last summer I was able to write html documents, render a new version and simply refresh the page to see the update.

On top of that, once you've tried to overwrite an open html file, even after closing it, no further updates are allowed until you delete the file.

Any ideas what might be causing this or possible solutions?

I originally posted this as a stackoverflow question but it seems more like it could be a bug.

```
library(rmarkdown)

# set up to allow the use of a different directory
directory <- getwd()
write(' ## Testing what comes out ', file = paste(directory, "nonsense.rmd", sep=""))

render(paste(directory, "nonsense.rmd", sep=""), output_format="html_document", 
       output_file="openPageBeforeRe-runningRender.html", output_dir = directory)

# open url
browseURL(paste(directory, "openPageBeforeRe-runningRender.html", sep=""))

# re-run render with document open
render(paste(directory, "nonsense.rmd", sep=""), output_format="html_document", 
       output_file="openPageBeforeRe-runningRender.html", output_dir = directory)

# close document and re-run render
render(paste(directory, "nonsense.rmd", sep=""), output_format="html_document", 
       output_file="openPageBeforeRe-runningRender.html", output_dir = directory)

# even with the document now closed it appears to be permanently unable to write updates to the html file

# once you remove the file you're allowed to write it again
file.remove(paste(directory, "openPageBeforeRe-runningRender.html", sep=""))
render(paste(directory, "nonsense.rmd", sep=""), output_format="html_document", 
       output_file="openPageBeforeRe-runningRender.html", output_dir = directory)
```

**Comment by jjallaire** [comment]
This is something related to file permissions and file locks held by whatever browser you are using. Nothing has changed about the way rmarkdown writes files -- it attempts to write them and if the operating system won't permit it, well, then, it won't!

**Comment by Henry-E** [comment]
That should help narrow down the problem. Thanks.
