### ISSUE TITLE
lib_dir removed on render

### ISSUE THREAD

**Issue by botanize** [rstudio/rmarkdown#700]
I specified `lib_dir: libs` for my gitbook document. I have a `libs` folder at the base of my file hierarchy that I keep copies of additional javascript libraries I use in my documents. When I render the document the contents of libs are correctly copied to the `_book` output, but the libs folder is also removed. 

I expect the `libs` directory to remain where I left it. I'd like to add `libs` to version control and ignore `_book`. However, if the render process removes `libs` I have to revert that folder after each render.

The problem appears to be caused by line 251 of `render_site.R`.

**Comment by yihui** [comment]
I'd recommend you to put your own JS libraries in a different folder. I expect `lib_dir` to contain the automatically copied JS libraries. Or put your libraries in an R package (you can probably consider htmlwidgets).
