### ISSUE TITLE
Problem with the SSL CA cert

### ISSUE THREAD

**Issue by jcquiroz** [rstudio/rmarkdown#707]
After install Rstudio Daily Build (desktop-windows) version 0.99.1198 I got the next message when I tried to update rmarkdown

> devtools::install_github("rstudio/rmarkdown")
> Downloading GitHub repo rstudio/rmarkdown@master
> from URL https://api.github.com/repos/rstudio/rmarkdown/zipball/master
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Problem with the SSL CA cert (path? access rights?)

my ssl libraries looks well,
thoughts?

**Comment by jjallaire** [comment]
You don't actually need to update rmarkdown if you are running the daily
build (it includes an embedded copy of rmarkdown master which it will
install on demand).
