### ISSUE TITLE
Render tufte pdf fails

### ISSUE THREAD

**Issue by abarbour** [rstudio/rmarkdown#710]
After generating a tufte-handout styled rmd (thanks to https://github.com/rstudio/rmarkdown/commit/5c5cdcd5c337166f043a3861e11fa58085d66a67):

`rmarkdown::draft("my_handout.Rmd", template = "tufte_html", package = "tufte")`

I can render `my_handout.Rmd` to html without issues (and it looks the same as on http://rstudio.github.io/tufte/):

`rmarkdown::render("my_handout.Rmd")`
...
`Output created: my_handout.html`

But this fails when I try to create a pdf:

`rmarkdown::render("my_handout.Rmd", output_format='pdf_document')`
...
```
! Undefined control sequence.
l.178 \newthought

pandoc: Error producing PDF from TeX source
Error: pandoc document conversion failed with error 43
```

Am I supposed to pass `documentclass=tufte-handout` to the default latex file, somehow? I cant seem to find a good example of this to see what I'm doing wrong. 

Some info:

rmarkdown: V 0.9.6.11
tufte: V 5.0.1

```
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/MacPorts 2015_11)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.44.0
```
(FYI, I've confirmed that the 'tufte-handout' latex class is installed properly.)

**Comment by yihui** [comment]
The example given in the tufte package is not supposed to work with the `pdf_document` format. For PDF output, you should use the `tufte::tufte_handout` format.

**Comment by abarbour** [comment]
Not sure I understand why this does not (cannot?) work, given what was fixed [here](https://github.com/rstudio/rmarkdown/commit/5c5cdcd5c337166f043a3861e11fa58085d66a67). Is there any example that shows this?

**Comment by yihui** [comment]
The tufte example only works with tufte output formats, because there are some LaTeX commands specific to the tufte-latex package, such as `\newthought{}`. These commands are not available in an ordinary LaTeX document with the `article` class.
