### ISSUE TITLE
Rmd non-english characters in fig: "render" ok but "render_site" not

### ISSUE THREAD

**Issue by MortenGrum** [rstudio/rmarkdown#712]
I have Rmd files with Danish characters "Æ Ø Å æ ø å" within both text and plotly charts.

Characters in both text and figures comes out fine when I use:

`rmarkdown::render("index.Rmd")`
but the characters in plotly figure get messed up when I use:

`rmarkdown::render_site()`
Any ideas?

Thanks in advance.

Morten

PS: I'm on Windows 10 and I needed to save with encoding WINDOWS-1252 even to get the characters right at all with any of the methods and in the text too (would have prefered UTF-8 but that didn't work).

**Comment by yihui** [comment]
Perhaps `rmarkdown::render_site(encoding = 'UTF-8')`? I'm surprised that `render()` without `encoding = 'UTF-8'` worked, though.

**Comment by yihui** [comment]
If you are going to retry, please `devtools::install_github('rstudio/rmarkdown')`

**Comment by Balou9** [comment]
I've retried it. Still not working. Please, can you look after it? Thanks a lot :)
