### ISSUE TITLE
Pandoc.exe  openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by juansahe** [rstudio/rmarkdown#713]
With Rstudio 0.99.1205 (windows 10). 

Doing: File -> New File -> R Notebook. Everything inside the .Rmd file is working as expected but when  trying to make a preview no .nb.html file is generated and the console shows:

`pandoc.exe: ~/Personal/project_folder/file_name.nb.html: openFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1`

Pandoc 1.17.0.2 is installed and accesible via cmd.

**Comment by jjallaire** [comment]
@kevinushey I can repro this error. I think it's because we are passing a file name with ~ in it on Windows (and that construct doesn't exist outside R so pandoc can't resolve the path). 

This seems like an issue worth fixing right away and updating the preview build for. My guess is that it's a one liner somewhere, hopefully you know where!

**Comment by kevinushey** [comment]
I can repro as well; unfortunately it looks like it's going to be more than just a one-liner (we need to sanitize file separators in a bunch of spots). Hopefully I'll be able to nail all this down this morning.

**Comment by jjallaire** [comment]
It is just file separators or does the ~ also need to be expanded? (I don't
think pandoc has any concept of ~ on Windows)

**Comment by kevinushey** [comment]
Should be resolved on the RStudio side with this: https://github.com/rstudio/rstudio/commit/79584e8512f9e0217f3f45812e5a7ef30e1e549b

**Comment by jjallaire** [comment]
Thanks!

**Comment by kevinushey** [comment]
This is now fixed on the RStudio side, but we might actually want to fix this in `rmarkdown` itself.

**Comment by kevinushey** [comment]
This should now be handled in both cases.

**Comment by juansahe** [comment]
Now working as expected. Thanks!

**Comment by Kenkleinman** [comment]
Just encountered this error trying to compile the learnr default file, when I saved the file into a different directory than where it was originally created.  This isn't an issue with pandoc or RMarkdown, but I'm leaving this note here for future users.
