### ISSUE TITLE
render_site cannot show the Chinese characters correctly

### ISSUE THREAD

**Issue by byzheng** [rstudio/rmarkdown#715]
I have the similar problem with #712. The same document with Chinese characters can show Chinese characters with `render_html`, but cannot with `render_site`. 

My file is saved as UTF-8 format, and already try render_site(encoding="UTF-8").

**Comment by byzheng** [comment]
Now `render_site(encoding="UTF-8")` can render Chinese characters correctly. But the build site button in RStudio still cannot correctly show Chinese characters.

**Comment by yihui** [comment]
Sounds like RStudio didn't pass the encoding to `render_site()`? cc @jjallaire

**Comment by yihui** [comment]
Scratch that. Just saw your fix. Thanks!

**Comment by byzheng** [comment]
There is one more problem need to be fixed: L312 at html_document.R, but I am not sure how to fix it.

config <- site_config(input_file, encoding = ???)

**Comment by yihui** [comment]
We can pass `encoding` to the `post_knit` function: https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L358-L360

**Comment by jjallaire** [comment]
One note here: since there are existing post_knit handlers in the wild that
don't take ... we'd be breaking those if we just added a parameter. As a
result, I think we should check the formals of the post_knit function
before calling and only pass the encoding if it takes > 3 arguments (or
better yet if it actually has an encoding parameter).

**Comment by jjallaire** [comment]
Re-opening to confirm that we've in fact fixed the problem with the latest commits to master (we already updated RStudio Preview Release to pass encoding to render_site). If everything is now working as expected please close this issue. Thanks!
