### ISSUE TITLE
Bug (or at least unexpected behavior) for code chunks commented out w/ HTML comments

### ISSUE THREAD

**Issue by jgellar** [rstudio/rmarkdown#720]
I'm not sure if this is a bug in rmarkdown, knitr, or RStudio, but i'm posting it here. I'm using rmarkdown version 0.9.6, knitr version 1.12.3, and Rstudio version 0.99.893. Also, I'm running MRO version 3.2.5, if that matters at all.

It appears that if you comment out a section of an R markdown document using HTML comments, and that section contains an R code chunk, then that code chunk is still executed when you knit the document. The execution is silent, so any print statements/figures do not appear in the output. However, if you modify variables in the chunk, they do get modified.

Note that if you "run all previous chunks in the source file" from a chunk after the commented-out section, so that the code is executed in the console, the commented-out chunk does not get executed. This is the behavior I would expect to happen when you knit the document. Here's a reproducible example:

``````

---
title: "Bug when using HTML comments"
author: "Jonathan Gellar"
date: "June 8, 2016"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I am going to demonstrate a small bug that occurs when using HTML comments. First, I'll generate some data:
```{r gendata}
x <- 1:5
x
```

That was easy. Now I'm going to comment out a section using HTML comments.

<!--
This section will be commented out and won't appear in the output file. Now I insert a code chunk:
```{r moddata}
x <- 6:10
print(x)
```

-->

Now we are done with the commented section. Let's print x and see what's there:
```{r print}
x
```
``````

**Comment by jjallaire** [comment]
That's correct. knitr treats your document as a set of text with chunks in
it (it doesn't know about comments). If you want to comment out the R code
at this point you just need to comment it out using R comment syntax (or
just add eval=FALSE) to it.

**Comment by jgellar** [comment]
Yeah, I imagined this would be the case. I just think it would be more appropriate for the knitr parser to recognize that a code chunk is contained within an HTML comment, so the programmer probably does not intend for it to be executed. At least I would hope it would be consistent with what happens when you execute "Run all previous chunks in the source file", which recognizes that the chunk is commented out.

**Comment by jjallaire** [comment]
Interesting, that's not an intended inconsistency!

@yihui, what do you think about respecting HTML comments in knitr?

**Comment by yihui** [comment]
As mentioned above, knitr does not know anything about HTML comments. There are two complications if I have to recognize HTML comments in knitr: 1) it is hard/impossible to do it well only by using regular expressions (on which knitr's parser is based); 2) I will also have to consider other document formats such as Rnw, Rhtml, and so on. So the only solution for now is `eval=FALSE`. Sorry.

**Comment by jgellar** [comment]
Perhaps it could be done within rmarkdown? e.g., in `rmarkdown::render`, you add a step like
```
if(output_format == "html_document") {
    # search through the file for html comment tags, and remove everything between them
    # ....
}
```
Even if regular expressions are difficult for finding `<!--` and `-->` (not sure why it would be, but I'll admit I don't know how to do this off the top of my head), there has to be some way to do it in R, right?

**Comment by yihui** [comment]
A simple example illustrating why it is difficult:

    This is not an HTML comment `<!-- `

    ```{r}
    ```

    `-->`

To reliably parse the HTML comment, I will have to use a real Markdown parser instead of regular expressions.

**Comment by yihui** [comment]
Closing this one and let's focus on #974 instead.
