### ISSUE TITLE
switching output type reformats date field

### ISSUE THREAD

**Issue by baptiste** [rstudio/rmarkdown#724]
I have this date field in yaml,
```
date: "`r format(Sys.time(), '%d %B, %Y')`"
```
and I've noticed that switching from `output:  pdf_document` to `output:  html_document` in Rstudio reformat it to 

```
date: '`r format(Sys.time(), ''%d %B, %Y'')`'
```
which throws an error when parsing.

**Comment by jmcphers** [comment]
This is an issue in RStudio rather than R Markdown; I've just added your notes to the bug we have tracking this. Thanks for reporting!
