### ISSUE TITLE
html_fragment and scripts, lib_dir etc.

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#725]
## Problem

Libraries such as rCharts and ggplot2 can be included in an html_fragment, their dependent files live in the `<body>`.

Many newer htmlwidgets place JS and CSS in the document head. This is of course sensible, especially for CSS.

However, I have not found a way to programmatically create an html_fragment and import the right header files that I can rely on.

My use case is that I dynamically generate (among other things) feedback graphs (via openCPU) for my survey software. I'm using my own bootstrap styles to keep the feedback in the same look as the site.

If I use html_fragment as the output, anything that would go in the lib_dir is not created in the first place. Same for md_document.
## Possible solutions I can think of
1. I can use html_document, parse the <head>, drop title, cruft and bootstrap and put it in my own header. But that seems likely to fail at some point and isn't very elegant.
2. You could re-write html_fragment to use the lib_dir directory option, then I could use this more easily as a parseable "necessary resources for inclusion" list. I'm not sure this would suffice since you have a quite colorful mix of external inlined styles and scripts in many rmarkdown-generated documents.
3. You could re-write html_fragment to inline styles and scripts for htmlwidgets like rCharts does. Would generate invalid HTML, but would work. Probably this is not something that rmarkdown is completely in charge of and it would be hell to maintain?
4. I could also include html_documents as iframes. I would now have to insert my styles via a header template. This seems most future-proof and elegant, but I wouldn't want to do it in cases where I generate lots of small fragments, and the way my program is written, this is very flexible for the user and I can't tell from rmarkdown's output for html_fragment whether any dependencies have gone missing.

So, solution 4 sounds best?

**Comment by jjallaire** [comment]
You can use theme: null and self_contained: false for html_document and
you'll end up with a pretty clean piece of html. If you want even more
control you can even use a custom template for html_document and you can
approximate exactly what you are looking for (lib_dir created, just the
body and minimal head within the document).

**Comment by rubenarslan** [comment]
Wow, that was quick. Thanks for the tip. I'd still get a second, older copy of jQuery, FontAwesome though (when including e.g. highcharter). 
Do you concur that the iframe route probably has less unforeseeable downsides?

**Comment by yihui** [comment]
To avoid conflicts in JS libraries, iframes is certainly the only way to go. That is what @bhaskarvk's widgetframe package does: https://github.com/bhaskarvk/widgetframe

I think I had the same issue in developing blogdown, and I just used a custom minimal template: https://github.com/rstudio/blogdown/blob/master/inst/resources/template-minimal.html You can separate the `<head>` part from `<body>` by post-processing if necessary.
