### ISSUE TITLE
Customizing figure numbers from rmarkdown chunks

### ISSUE THREAD

**Issue by rraadd88** [rstudio/rmarkdown#726]
Dear rmarkdown,

When I use this rmarkdown chunk,

`
'''{r figure_name,fig.cap="\\label{figure_name:cap}caption."} 
`
`
    -plotting-code-here-
`
`
'''
`
I get a figure caption like this,

`Figure 1: caption.`

But I need a caption like this,

`Figure S1: caption.`

How should I go about customizing the figure number in this way through rmardown or knitr?

**Comment by yihui** [comment]
That is essentially a LaTeX question, and out of the scope of rmarkdown. Once you figure out the LaTeX solution, you can apply it to R Markdown: http://rmarkdown.rstudio.com/pdf_document_format.html#includes
