### ISSUE TITLE
MathJax + self_contained w/ custom templates

### ISSUE THREAD

**Issue by jgellar** [rstudio/rmarkdown#727]
I have spent awhile making a custom rmarkdown template. I would like to use it as a template for data analyses, allowing for both Latex equations and figures. However, when I use the template I get the following warning message:

```
Warning message:
MathJax doesn't work with self_contained when not using the rmarkdown "default" template. 
```

Setting `self_contained` to FALSE makes the resulting output much more difficult to email around to collaborators. A few questions:
1. Is there any way I'm missing to allow for self-contained output that includes both Latex equations and figures in a custom template?
2. If not, is there any chance that this limitation will be resolved any time soon?

Sorry if this has been answered before, but a quick search didn't reveal anything.

Thanks,
Jon

**Comment by aoles** [comment]
Hi Jon,

One possible solution circumventing this limit is to define a custom format function which first calls `rmarkdown::html_document` with the `"default"` template (to retain MathJax functionality), but then modifies the pandoc template setting.

```r
my_html_document <- function(template = "path_to_custom_template", ...) {
  base_format <- rmarkdown::html_document(...)
  
  template_arg <- which(base_format$pandoc$args == "--template") + 1L
  base_format$pandoc$args[template_arg] <- template
  
  base_format
}
```

Cheers,
Andrzej

**Comment by pat-s** [comment]
@aoles Works like a charm, thanks for that hack!

**Comment by andyrevell** [comment]
Where do we put the custom format function that @aoles mentioned? At the begining of the rmarkdown file?

**Comment by DavisBrian** [comment]
@andyrevell Did you ever figure this out?  I seem to be having a similar issue.
