### ISSUE TITLE
consider beefing up default ioslides CSS styles

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#730]
Right now, block quotes in `ioslides` don't get any styles (they just look plain / boring). Could we tweak the default CSS to give them a nicer treatment?

Or would it be better to delegate work like this to something like an `iothemes` package, providing custom template(s)?

**Comment by yihui** [comment]
The number of issues and feature requests of ioslides in this repo is so overwhelming that I don't think we will ever be able to deal with them. I have been mostly closing these issues over the past few days (kind of declaring that ioslides is feature-frozen), and pointing users to other presentation frameworks like [revealjs](/rstudio/revealjs) and [xaringan](/yihui/xaringan), where most of issues have been well solved.
