### ISSUE TITLE
Collapse/Expand all output in R Notebooks

### ISSUE THREAD

**Issue by Atrebas** [rstudio/rmarkdown#733]
Hi,
The new R Notebook is nice!
Is there a way to Collapse/Expand all output in the **HTML** document?
It is possible in the **Rmd** file but having this feature in the html would be useful, especially when the emphasis is put on code rather than output.
For example, to save space in cheatsheets but still making the results accessible (contrary to `eval=FALSE`).
Thanks.

**Comment by jmcphers** [comment]
No, there is not currently a way to do this.

**Comment by ReportMort** [comment]
I think this has been implemented, no? Go to "Edit" in your RStudio menu.

![image](https://cloud.githubusercontent.com/assets/5299737/26750595/2c752e50-47f5-11e7-8796-b24cad4167b0.png)

**Comment by Atrebas** [comment]
Thanks for the note @ReportMort. Apparently, the options in the edit menu only affect the display in the source pane, not the final html document.

**Comment by yihui** [comment]
Closing since this is an RStudio IDE issue instead of the rmarkdown package.
