### ISSUE TITLE
Cannot use MathJax 2.6

### ISSUE THREAD

**Issue by nathancarter** [rstudio/rmarkdown#740]
I'm using RStudio Server through Chrome.  When typesetting an RMarkdown document to HTML format, typeset mathematics has the visual artifacts documented [here](https://github.com/mathjax/MathJax/issues/1300), which were fixed a few months ago and released in MathJax 2.6.  Despite the fact that RMarkdown [seems to use the latest MathJax](https://github.com/rstudio/rmarkdown/blob/master/R/html_document.R#L480), when I right-click any typeset mathematics and choose "About MathJax," it reports version 2.3.  I tried to update the YAML header of my `.Rmd` file to import the latest MathJax directly, using this code:

```
    mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
```

The same visual artifacts remain, and MathJax still reports itself as version 2.3.  Where is this reference to an old MathJax hardcoded into the server?  How can I override it?

**Comment by yihui** [comment]
If I remember it correctly, when displaying the HTML page, RStudio IDE will use a bundled version of MathJax (which is probably 2.3). When the HTML page is published, it will just use whatever version of MathJax you chose (latest by default).

**Comment by jjallaire** [comment]
Yes, that's correct. We'll update our bundled version of MathJax in RStudio
to 2.6 soon.

J.J.

**Comment by nathancarter** [comment]
That's great to hear.  So I just watch for the next RStudio release?  Looks like [they come out pretty often](https://support.rstudio.com/hc/en-us/articles/200716783-RStudio-Release-History).  If RStudio Server is on the same schedule, then that's great.  Thanks!

**Comment by jjallaire** [comment]
The current RStudio Preview Release now includes MathJax 2.6 (among many
other features that hopefully you'll also find useful!):

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by nathancarter** [comment]
Great, thank you -- that was fast. :)  I'll tell my institution's server team that the new RStudio Server Pro is in preview, and they can update the server when they choose -- now, or after the official release, as they prefer.  Thanks again!
