### ISSUE TITLE
font-awesome not loaded correctly when using `html_dependency_font_awesome` and calling `shiny::icon()`

### ISSUE THREAD

**Issue by daattali** [rstudio/rmarkdown#742]
I found out about the `html_dependency_foo()` functions while creating an htmlwidget and I was told I can use these functions to include common shiny libraries (https://github.com/ramnathv/htmlwidgets/issues/218)

I think I may have found a bug with including font-awesome though, and I'm not sure if it belongs here, in htmlwidgets, or in shiny, so I'll just tag (ie spam....) a few people @wch @jcheng5 @jjallaire @ramnathv @yihui @jmcphers

I can call `createWidget()` and add bootstrap and jquery to the dependency list using `rmarkdown::html_dependency_foo()` with no problem.  But when I also try to include font-awesome (`rmarkdown::html_dependency_font_awesome()`), and then use `shiny::icon()` to render an icon, then the icons don't end up showing up in a non-shiny environment (such as when running the widget in the RStudio console).

It looks like the problem is that when calling `html_dependency_foo()`, the dependency resource path gets set to `lib/foo` (eg `lib/font-awesome-4.5.0/css/font-awesome.min.css`), but inside the `shiny::icon` function, the resource path gets set to `shared/font-awesome/css/font-awesome.min.css` instead.  This file actually leads to nowhere and is the reason font-awesome doesn't work. If instead of calling the `shiny::icon` function I just use `tags$i(class = "fa ...")` then the fonts do render properly because the `lib/` path gets used.

I hope this makes sense

**Comment by yihui** [comment]
You were correct that `shared/` makes no sense in non-shiny R Markdown documents, and the only way to go is `rmarkdown::html_dependency_font_awesome()` plus `tags$i()` instead of `shiny::icon()`. The latter can only be used in Shiny apps and Shiny Rmd documents.
