### ISSUE TITLE
text highlighting

### ISSUE THREAD

**Issue by grighi** [rstudio/rmarkdown#743]
I quite frequently make use of the color/soul packages in latex for text highlighting (with `\hl{}`). When I want to accomplish this in HTML documents from Rmarkdown, I just use `<mark>` tags. But if I am working on a project where the output is both HTML and pdf, it is not easy to switch between the two. The HTML will hide `\hl{highlighted text}` and a pdf will show the `<mark>` tags. Is there anyway to highlight text across both document types?

**Comment by yihui** [comment]
The rmarkdown package does not really process your LaTeX commands or HTML tags. It is Pandoc that does the job, so you have to ask this question in the Pandoc mailing list or Github issues or StackOverflow.
