### ISSUE TITLE
default spacing between paragraphs in Beamer output has changed

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#744]
It appears that newer versions of `pandoc` do not render separate paragraphs in a Beamer PDF output with extra whitespace between paragraphs. For a markdown file with contents:

```
# Title

A paragraph.

Another paragraph.
```

We get the following renders:

#### Older pandoc (1.12.4.2):

![screen shot 2016-07-19 at 2 30 03 pm](https://cloud.githubusercontent.com/assets/1976582/16967346/554cce88-4dbd-11e6-98ac-425de901d0ff.png)

#### Newer pandoc (1.17.2):

![screen shot 2016-07-19 at 2 30 15 pm](https://cloud.githubusercontent.com/assets/1976582/16967354/5a194e00-4dbd-11e6-9a40-b258d4d84dd2.png)

I'm not yet sure if this should be considered a regression in pandoc, or if it's just something we could handle on the `rmarkdown` side with a default beamer template (or something like that).

Is this something we might want to handle on the `rmarkdown` side?

**Comment by jjallaire** [comment]
We've tended to leave the pandoc beamer template alone and let these issues get addressed on the pandoc side. I'd say we could report it there and if it's not considered a bug we'd find out why.

**Comment by kevinushey** [comment]
Sounds good. Filed an issue here: https://github.com/jgm/pandoc-templates/issues/207

**Comment by kevinushey** [comment]
Sounds like this was indeed a minor regression in the default template; presumedly we'll get the fix with the next release of `pandoc`.

**Comment by jjallaire** [comment]
Okay, it might be a while before we update pandoc though. We do have a
function already that patches the default pandoc beamer template here:

https://github.com/rstudio/rmarkdown/blob/master/R/beamer_presentation.R#L141

We'd just have to scope our patching to just the "regressed" versions of
the beamer template.

**Comment by kevinushey** [comment]
Sounds good -- I'll submit a PR.

**Comment by jjallaire** [comment]
Awesome, thanks!

J
