### ISSUE TITLE
ioslides: adding keep_md: true to yaml header changes html output

### ISSUE THREAD

**Issue by TomHarrop** [rstudio/rmarkdown#749]
I'm using `ioslides_presentation`  in `rmarkdown_1.0`. To get nicer-looking plots, I'm producing 300 dpi pngs for my figures and then using css to scale the images down. Here is an example:

    ---
    title: "Test"    
    output:    
      ioslides_presentation:    
        self_contained: false    
        widescreen: true    
        fig_width: 9.16    
        fig_height: 4.5        
        css: overrides.css        
        keep_md: true        
    ---        
            
    ```{r setup, include=FALSE, results="hide"}    
    library(ggplot2)    
    knitr::opts_chunk$set(dpi = 300)    
    ```    
        
    ## Test plot    
        
    ```{r test, echo = FALSE}    
    qplot(rnorm(10), rnorm(10))    
    ```    

`overrides.css` contains the following:

```css
slide article img {
    max-width: 879px;
    max-height: 432px;
}
```

This works fine. The plots are rendered in the html as follows:

```html
<p><img src='test_files/figure-html/test-1.png' title=''/><!-- --></p>
```

However, if I remove `keep_md: true`, the html I get is:

```html
<p><img src="test_files/figure-html/test-1.png" width="2748" /></p>
```

This may not seem like a big deal, but the extra `width` in the `<img>` tag causes problems, for example when there are side-by-side images on the slide.

Is removing `keep_md` expected to change the html output?

**Comment by yihui** [comment]
You can specify the chunk option `out.width`, e.g. `out.width = '50%'`.

**Comment by TomHarrop** [comment]
Thanks, I forgot about `out.width`.  Actually the following chunk also works without `keep_md: true`

    ```{r test2, echo = FALSE, fig.width = 9.16/2, out.width = ""}
    qplot(rnorm(10), rnorm(10))
    qplot(rnorm(10), rnorm(10))
    ```

The images appear side-by-side correctly and the html is:

```html
<p><img src="test_files/figure-html/test2-1.png" width="" /><img src="test_files/figure-html/test2-2.png" width="" /></p>
```

I don't know whether it's better to explicitly specify the width or not...

**Comment by yihui** [comment]
I think `out.width = ''` is okay.
