### ISSUE TITLE
potential issue with patch_beamer_template

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#753]
Copied from the RStudio support forums:

```
Hi,

did two fresh installations in a VM each:

VM1:

Win 7 64Bit, R 3.3.1, RStudio-0.99.903, Miktex, Texstudio

Result:   Knit to PDF (Beamer) ist working .#

VM2:

Same procedure but with RSTudio-099-1266 instead.

Result:  Knit to PDF (Beamer) results in an error:

Fehler in file(con, "r") : kann Verbindung nicht öffnen
Ruft auf: <Anonymous> ... <Anonymous> -> patch_beamer_template -> readLines -> file
Zusätzlich: Warnmeldung:
In file(con, "r") :
  kann Datei 'C:\Users\Rolf\AppData\Local\Temp\RtmpO2ah7n\fileb94497f50ef.tex' nicht öffnen: No such file or directory
Ausführung angehalten

Regards,

Rolf
```

I'm guessing this implies that this line is failing:

https://github.com/rstudio/rmarkdown/blob/master/R/beamer_presentation.R#L201

but I don't yet know why.

**Comment by jjallaire** [comment]
To me it looks like perhaps pandoc failed to write the file. 

Looking a bit more closely, does Windows support output piping with ">", perhaps that's the problem?

**Comment by kevinushey** [comment]
I believe you're right -- we need to explicitly go through `shell` on Windows to get redirection. E.g.

```
> unlink("hello.txt")
> system("echo hi > hello.txt")
hi > hello.txt
> file.exists("hello.txt")
[1] FALSE
> 
> unlink("hello.txt")
> shell("echo hi > hello.txt")
> file.exists("hello.txt")
[1] TRUE
```

Maybe we need a system wrapper that uses `shell` on Windows, and `system` otherwise?
