### ISSUE TITLE
Session info

### ISSUE THREAD

**Issue by PachoAlvarez** [rstudio/rmarkdown#756]
Practically this was what was open yesterday when the problem occurred: A blank notebook, was starting the work session, creating the file.

So I think it was RStudio installation problem, in addition to reinstalling finally worked. Now, or curious is why not install well RStudio?

[Análisis Generales EVVOM.zip](https://github.com/rstudio/rmarkdown/files/399470/Analisis.Generales.EVVOM.zip)

**Comment by yihui** [comment]
Sorry, but I don't understand your question. What exactly was the problem?
