### ISSUE TITLE
Unnecessary metadata append at the end of intermerdiates *.spin.Rmd

### ISSUE THREAD

**Issue by cderv** [rstudio/rmarkdown#759]
Hey, 

Trying to understand how work `outpur_dir`, `intermediates_dir` and _working directory_ when using `rmarkdown::render` for Rmd and R files, I encounter a strange behaviour for knitting R files.

`render` looks at the file extension to see if it is an R file or a Rmd file. When it sees it is an R file, it will uses 
`knit::spin` to generate a *.spin.Rmd. Then something that looks odd to me : it will append at the end of the file, a metadata. 

Here the lines of code 

``` r
if (identical(tolower(tools::file_ext(input)), "r")) {
        spin_input <- intermediates_loc(file_with_meta_ext(input, 
            "spin", "R"))
        file.copy(input, spin_input, overwrite = TRUE)
        intermediates <- c(intermediates, spin_input)
        spin_rmd <- knitr::spin(spin_input, knit = FALSE, envir = envir, 
            format = "Rmd")
        intermediates <- c(intermediates, spin_rmd)
        knit_input <- spin_rmd
        metadata <- paste("\n", "---\n", "title: \"", input, 
            "\"\n", "author: \"", Sys.info()[["user"]], "\"\n", 
            "date: \"", date(), "\"\n", "---\n", sep = "")
        if (!identical(encoding, "native.enc")) 
            metadata <- iconv(metadata, to = encoding)
        cat(metadata, file = knit_input, append = TRUE)
    }
```

Why append this at the end of the file ? It seems unnecessary.
I could see why a default metadata is generated if no metadata is at the start of the file. But at the end don't see why. 

Conclusion, I do not know if it's something or not. It may be on purpose and I missed why. However, I prefered to ask and reporting this instead of do nothing.

**Comment by yihui** [comment]
I don't quite understand this either. @jjallaire introduced it in d22cdee8f93ab2a507e62547998081c977c50869 three years ago. I feel he wanted to make sure the output document always had title/author/date, but I don't know why that would be necessary.

**Comment by jjallaire** [comment]
Yes, that's exactly the reason. We wanted a document generated from a
script to always have some sort of header. I agree it's a toss-up though,
so feel free to remove if you don't think it's a good idea.

**Comment by yihui** [comment]
@jjallaire I don't have a strong opinion on this.

@cderv I can remove it if it bothers you. Just let me know.

**Comment by cderv** [comment]
It's been a while now. Currently, it don't bother me right now because it do not causes issues and I do not have currently usage of spin. 

However, I still do not understand the purpose of add metadata at the end of a file. Is yaml metadata at the end of a file still being parse ?

**Comment by yihui** [comment]
@cderv If users have already specified YAML metadata in the beginning of an R script, the YAML metadata we append to the end will be ignored. Pandoc only processes one copy (the first copy) of YAML. Basically the code here meant to make sure the Rmd generated from the R script always has YAML metadata. Is that a good idea? I don't know.

**Comment by cderv** [comment]
ok. I understand then that if there is no medata in the beggining pandoc will process the one at the end. Did not no that. Do not know either if it is a good idea. Time will tell us. Thanks for having looked into it.
