### ISSUE TITLE
Please allow us to disable param defaults 

### ISSUE THREAD

**Issue by DianaCesar** [rstudio/rmarkdown#762]
This is more of a request than an issue.

Currently, when a parameterized .Rmd is created, a default value must be coded for each param. For example, if I have the following param in the YAML...

``` yaml
other: 
      value: first
      choices: [first, second, third]
      input: select
      label: Other
      multiple: yes
```

...then I must specify a default option to go into the 'value' spot. If I leave this spot blank, it throws an error*. If I try knitting this doc with the above code, then backspacing this param widget so that no value is showing, it returns the first available value (from my choices) in the rendered doc.

It seems that RMarkdown requires a default value for every param in order to render. Is there a way I could create a parameter with no defaults (i.e., a param that passes through to the output as NULL)?

*There seems to be some NULL capability built into params in RMarkdown, but it is unpredictable (or I am using it incorrectly). For example, when I leave the 'value:' spot blank (or I make it NULL) and knit the doc with parameters, I can sometimes get an option to appear in the select widget that says "Unspecified (NULL)" and another option that says "Use a custom value." Selecting the first option _does_ pass a NULL value through to the output. Selecting the second option resets the widget to display my original choices, but throws an error during the knit. It seems like the more coder-friendly alternative would be to simply allow RMarkdown to interpret these NULL values (or blank widgets) as such, without displaying the extra options.

Thank you,

Diana

**Comment by aronatkins** [comment]
Here is the error that is obtained when a multi-select value is chosen and then unset before choosing to knit with custom values:
```
Error in knit_params_get(input_lines, params) : 
  render params not declared in YAML: other
Calls: <Anonymous> -> knit_params_get
Execution halted
```
This indicates that `knit_params_ask` is not returning all parameters under some conditions.

**Comment by aronatkins** [comment]
R Markdown does not require parameters to have defaults. The following documents will report `params$other` having a `NULL` value when it is knit:

```
    ---
    title: rmarkdown 762
    params:
      other:
        value:
        choices: [first, second, third]
        input: select
        label: Other
        multiple: yes
    ---
    
    ```{r}
    params$other
    ```
```

You could also specify: `value: !r NULL`.

@yihui / @jjallaire - How do you feel about assuming a parameter without a `value` takes `NULL`?

**Comment by aronatkins** [comment]
I am investigating the error caused by `knit_params_ask`; the `NULL` default is an open question.

**Comment by aronatkins** [comment]
I think #768 will improve handling of NULL values, but there is still work remaining.

**Comment by aronatkins** [comment]
@DianaCesar Unfortunately, support for `NULL` values either as defaults, as programmatic overrides, or as UI selections is not well supported. Some permutations involving `NULL` may work, but I cannot recommend using `NULL` values at this time.

We hope to improve `NULL` support in an upcoming release.

**Comment by DianaCesar** [comment]
OK. Thanks for the update.

**Comment by trestletech** [comment]
A start to a solution: https://github.com/rstudio/rmarkdown/pull/913

This, paired with a `required` flag might accomplish what you're after. Even with just #913 you could in your own code `stop()` the compilation if you found that one of the parameters looked empty (for some definition of "empty").
