### ISSUE TITLE
No left margin for code chunks with ioslides ?

### ISSUE THREAD

**Issue by privefl** [rstudio/rmarkdown#764]
Get the template for R presentations with ioslides,

When knitting it, you get the html as there: https://privefl.github.io/blog/2016/08/04/test#1

On slide 4, the R code chunk is printing weird (there should be a left margin). 
This problem appears only with ioslides (not with slidy or beamer).

Is there a way to fix this ?

**Comment by jjallaire** [comment]
That's by design (i.e. an intended part of the style). You could probably
tweak the CSS to change this behavior but I'm not exactly sure how.

**Comment by yihui** [comment]
You can include the following CSS into your slides:

```css
pre {
  width: auto;
  left: auto;
}
```

See http://rmarkdown.rstudio.com/ioslides_presentation_format.html#custom_css

**Comment by privefl** [comment]
Thanks for the tip.
I now use:
```
pre {
  width: 100%; /* 106%; */
  left: 0; /* -60px; */
  padding: 10px 15px 10px 15px; /* 10px 0 10px 60px; */
}
```
which seems more common TO ME.

You can see the defaults (from R\win-library\3.2\rmarkdown\rmd\ioslides\ioslides-13.5.1\theme\css\default.css - lines 524:538) in comments.
