### ISSUE TITLE
Render .Rmd to pdf not working with lists

### ISSUE THREAD

**Issue by eeenilsson** [rstudio/rmarkdown#765]
Example .Rmd file named "test.Rmd":

`---`
`title: Test`
`output: pdf_document`
 `---`
`* unordered list` 
`* item` 

Render in Rstudio:

`require(rmarkdown)
render("test.Rmd", "pdf_document")`

Gives error:

> 
! Undefined control sequence.
l.73 \tightlist
pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43"

Works fine when rendering html.

Using OSX Yosemite, Rstudio Version 0.98.1056

Regards

**Comment by jjallaire** [comment]
This was fixed in an earlier version of rmarkdown:
https://github.com/rstudio/rmarkdown/blob/f43f59ec0578d967d05e46bc7d8bb76e7bfd64a8/inst/NEWS#L255

Try updating to either the latest version of RStudio (it's on to v0.99 now)
or the latest version of rmarkdown.

**Comment by eeenilsson** [comment]
Thanks! Had an older version of R also. Rmarkdown package was installed recently. After updating R and Rstudio it works fine! Had the same problem in emacs/ESS which was also fixed by this procedure, so it might have been the R update that was needed. Thanks again for the response!

**Comment by jjallaire** [comment]
Great, glad everything is now working!
