### ISSUE TITLE
github_document does not center correctly images on github

### ISSUE THREAD

**Issue by Dralliag** [rstudio/rmarkdown#772]
Hi,
To center the images, we need to use the chunk option : fig.align  = "center".
The images are then rendered as `<img src="file.png" style="display: block; margin: auto;" />` instead of markdown syntax. This works great for standard html and in your preview. However, it seems that the github engine, which converts README.md to html, does not support style tag for images: they are deleted and the images are not centered.

The only solution I know to center images in github documents is to place the images as follows:
`<p align="center">
  <img src="file.png">
</p>`
Is is possible that the chunk option gives this rendering for github_document?
Thanks!

**Comment by jjallaire** [comment]
You might be able to add the "align" attribute to the img tag (I've had
success using align="left"). e.g.

```{r, out.extra='align="center"'}
plot(cars)
```

**Comment by Dralliag** [comment]
No the attribute align="center" does not seem to center the images in github.
However, I managed to build a workaround by defining a hook:
``` r
```{r echo=FALSE}
library(htmltools)
knitr::opts_chunk$set(
  fig.align = "center"
)
knitr::knit_hooks$set(imgcenter = function(before, options, envir){
  if (before) {
    HTML("<p align='center'>")
  } else {
    HTML("</p>")
  }
})
```    #
```{r myplot, echo = TRUE, eval = FALSE}
plot(1:3,1:3)
```    #
```{r myplot, echo = FALSE, imgcenter = TRUE}
```    #
```
But thanks anyway for the help!

**Comment by jjallaire** [comment]
Oh, that's great!

**Comment by brunoduran** [comment]
This also happens in beamer presentations (I have not tried with normal pdf's): 

```latex
\begin{figure}
	\centering
	\includegraphics{Image}
	\\
	\centering Normal text
\end{figure}
```

**Comment by yihui** [comment]
@brunoduran For latex/beamer output, `fig.align='center'` should just work.
