### ISSUE TITLE
consider disabling 'markdown_in_html_blocks'?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#774]
Right now, it appears that `pandoc` will attempt to render markdown encountered in HTML blocks. Unfortunately, this can lead to surprising / unexpected behavior in some cases:

```
$ cat inline-html.md
<td>    Foo</td>

$ pandoc inline-html.md --from markdown --to html --output inline-html.html && cat inline-html.html
<td>
<pre><code>Foo&lt;/td&gt;</code></pre>
```

One can opt-out of this behavior with `-markdown_in_html_blocks`, e.g.

```
$ pandoc inline-html.md --from markdown-markdown_in_html_blocks --to html --output inline-html.html && cat inline-html.html
<td>    Foo</td>
```

This would help users who generate raw HTML avoid somewhat surprising behavior, when generating indented HTML (or HTML with contents that are indented). However, it certainly is possible that some users rely on the 'markdown in HTML' behavior, so I'm not sure if this would be a good change.

It's also possible that we need to instruct users to generate HTML with `htmltools::htmlPreserve`, or perhaps even that some of the `htmltools` APIs for generating HTML should do this by default.

Any thoughts on if we should handle this; and if so, how?

**Comment by jjallaire** [comment]
This is definitely something we'll keep as many users rely on it to do more powerful forms of formatting within markdown documents. The solution(s) are as you suggest (use the  htmltools APIs, don't indent, etc.). Note that HTML generators can also surround their generated code explicitly with html-preserve comments as described here: http://rmarkdown.rstudio.com/authoring_migrating_from_v1.html#preserving-generated-html
