### ISSUE TITLE
Knitting the same markdown file twice changes the HTML output (and renders it blank)

### ISSUE THREAD

**Issue by ndphillips** [rstudio/rmarkdown#775]
When I knit the default markdown file once, the resulting HTML file looks fine. However, if I knit the exact same file a second time, the resulting HTML file generates a blank output. Comparing the original and second HTML files, it looks like the second HTML file does not include a style sheet (among other differences)

Here is an Rmd file and the resulting HTML file from a single knit (they work)

## Single knit files (works)
[Single knit Rmd](https://dl.dropboxusercontent.com/u/7618380/oneknit.Rmd)
[Single knit HTML](https://dl.dropboxusercontent.com/u/7618380/oneknit.html)

Here is an identical Rmd file, and the resulting HTML file from knitting the same document twice. The HTML file has changed even though the Rmd file did not.

## Two knit files (HTML is changed)
[Two knit Rmd](https://dl.dropboxusercontent.com/u/7618380/twoknit.Rmd)
[Two knit HTML](https://dl.dropboxusercontent.com/u/7618380/twoknit.html)

RStudio 0.99.903
R 3.3.0

**Comment by jjallaire** [comment]
Your second Knit appears to have been rendered with Slidify rather than
with rmarkdown. I'm not sure how you ended up with Slidify in your
rendering pipeline (is the markdownToHTML option set to Slidify?)

**Comment by ndphillips** [comment]
I see. I am not sure how that happened either. I reinstalled RStudio and now it seems to be back to the default and is working well. It is still strange that it would render with rmarkdown on the first knit, then switch to using Slidfy on the second knit without any additional input. 

Well it works now and I'm happy. Thanks for the help.
