### ISSUE TITLE
retain tex source even if conversion fails

### ISSUE THREAD

**Issue by rdiaz02** [rstudio/rmarkdown#779]
At least under Linux, the conversion from Rmd to PDF takes place in a temporary directory under `/tmp` (e.g., `/tmp/tex2pdf.15071`) that gets removed immediately if the conversion fails, even if we run `pdf_document(keep_tex = TRUE)`.   This makes it very hard to debug tex-related issues.  For example:

```
---
output: 
  rmarkdown::pdf_document:
    keep_tex: true 
---

# Something

This is wrong

$\wrong$

```

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by rdiaz02** [comment]
Thanks a lot for the fix. Just checked and it works perfectly.
