### ISSUE TITLE
Missing % in documentation?

### ISSUE THREAD

**Issue by wch** [rstudio/rmarkdown#781]
On this page: http://rmarkdown.rstudio.com/package_vignette_format.html, for vignettes, it says to use:

```
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  \usepackage[utf8]{inputenc}
```

But I believe it should be use:

```
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  %\usepackage[utf8]{inputenc}
```

According to @jimhester, the leading `%` is needed for `tools:::.get_vignette_metadata` to find it with the regex that it uses.

Also see hadley/devtools#587.

**Comment by yihui** [comment]
Thanks! Just changed it to `%\VignetteEncoding{UTF-8}`. RStudio IDE also uses this as the default in the HTML vignette template.
