### ISSUE TITLE
Problems knitting with pipes

### ISSUE THREAD

**Issue by NickDulvy** [rstudio/rmarkdown#783]
I am having problems knitting a document when using pipes. This simple example when knitted reveals this error:

    ## Error in eval(expr, envir, enclos): could not find function "%>%"
    
    ```{r setup, cache = F}
    knitr::opts_chunk$set(error = TRUE)
    ```
    
    ```{r}
    
    x <- rnorm(10)
    x %>% max
    x
    ```

In slightly more complex examples 'x' is not evaluated and I get errors like this:

    ## Error in eval(expr, envir, enclos): object 'ArchHemSum' not found

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

**Comment by yihui** [comment]
The pipe operator is not in base R, so you need to load the package (magrittr?) before using it.

**Comment by mk9y** [comment]
The following worked, and was ttsn was used later
<<ciBoot, rexample = TRUE>>=
ttsn  <- tts %>%
  select(estimate, conf.low, conf.high) %>%
  as.numeric() %>%
  as_data_frame()
@
but the following failed silently, even though magrittr had been loaded, throwing an error in a subsequent ggplot:
<<ciBoot, rexample = TRUE>>=
tts  %<>%
  select(estimate, conf.low, conf.high) %>%
  as.numeric() %>%
  as_data_frame()
@
