### ISSUE TITLE
RStudio Knit button not rendering correctly flexdashboard if _site.yml is present

### ISSUE THREAD

**Issue by renejuan** [rstudio/rmarkdown#784]
As requested in post https://support.rstudio.com/hc/en-us/community/posts/213030028-RStudio-Knit-button-not-rendering-correctly-flexdashboard-if-YAML-file-is-present

 If an RMD with output: flexdashboard::flex_dashboard is knitted using Knit button (RStudio) and a _site.yml file is present it will use the values from the _site.yml file instead of the header of the Rmd file.

**Comment by yihui** [comment]
I cannot reproduce this issue, and here is my example: [flexdashboard.zip](https://github.com/rstudio/rmarkdown/files/1418646/flexdashboard.zip).

## _site.yml

```yaml
output:
  flexdashboard::flex_dashboard:
    fig_width: 7
    fig_height: 8
```

## test.Rmd

````markdown
---
title: "Test"
output: 
  flexdashboard::flex_dashboard:
    fig_width: 3
---

# asdf

```{r}
plot(1)
```
````

When I knit `test.Rmd`, the figure width is 3 as expected (specified in `test.Rmd`, not overridden by the value 7 in `_site.yml`).
