### ISSUE TITLE
Pointless rewrite of \paragraph

### ISSUE THREAD

**Issue by robjhyndman** [rstudio/rmarkdown#786]
The default preamble for latex files rewrites \paragraph and \subparagraph by adding \mbox{} to each. As far as I can tell, this does nothing at all. Besides, it breaks some useful packages such as titlesec. I propose removing the relevant lines from the default*.tex files, but wanted to check if there was something I was missing before issuing a PR.

**Comment by jjallaire** [comment]
It looks to me like this is part of the default pandoc template:

https://github.com/jgm/pandoc-templates/blob/master/default.latex#L166-L174

I am a bit concerned about changing this downstream without knowing the
original rationale and purpose. I'd suggest taking it up with jgm and see
what he says.

Note also that you can disable this behavior by specifying the
"subparagraph" variable to pandoc:
http://pandoc.org/MANUAL.html#variables-for-latex

**Comment by robjhyndman** [comment]
OK. I'll see if I can find a way to do it that doesn't upset the titlesec package.

**Comment by robjhyndman** [comment]
The solution here is to set
```
subparagraph: true
```
in the yaml header. Then you can load the titlesec package (or any other package that might play with the definition of `\paragraph`.
