### ISSUE TITLE
Code chunks in lists do not display properly in html_notebooks

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rmarkdown#787]
The first code chunk in this file displays correctly when `output: html_document` but incorrectly when `output: html_notebook`:

``````

---
title: "R Notebook"
output: html_notebook

---

A list with

* A code chunk:

    ```{r}
    paste("displays incorrectly", "in nb.html file")
    ```

A regular code chunk:

```{r}
paste("displays correctly",  "in nb.html file")
```
``````

html_document:

<img width="457" alt="screen shot 2016-08-26 at 1 46 21 pm" src="https://cloud.githubusercontent.com/assets/85014/18015055/feaf2ff4-6b93-11e6-8406-020e2bec2960.png">

html_notebook: 

<img width="455" alt="screen shot 2016-08-26 at 1 50 56 pm" src="https://cloud.githubusercontent.com/assets/85014/18015096/26bc6886-6b94-11e6-9b63-826237eab7da.png">

**Comment by jmcphers** [comment]
cc @kevinushey; previously logged on the IDE side in case 5991.

**Comment by yihui** [comment]
Closing since this is an RStudio IDE issue and has been logged.
