### ISSUE TITLE
Any way to set default tabset in html_document

### ISSUE THREAD

**Issue by jangorecki** [rstudio/rmarkdown#789]
I have 5 tabsets (tabset-pills) defined, all shows fine. After opening html document by default the first tabset is selected. Is there any way to have by default selected tabset other than first one? I don't want to re-order tabs, but show the middle one (3rd) by default, and allow user to jump into 1st/2nd on the left side or 4th/5th on the right side.

As a side note, in the [docs](http://rmarkdown.rstudio.com/html_document_format.html#tabbed_sections) there is info in _Requirements_ section that recommends to install rmarkdown from source to get recent version, I believe it isn't necessary already.

**Comment by jjallaire** [comment]
No there isn't currently a way to this.

**Comment by jangorecki** [comment]
I found it quite complex to workaround in html as tabsets are dynamically generated, but it was very easy by tweaking rmarkdown for that. Of course this is not portable, just a hardcoded tab in tabset, so can't do PR. Posting git diff if anyone has a similar problem.
```
diff --git a/inst/rmd/h/navigation-1.1/tabsets.js b/inst/rmd/h/navigation-1.1/tabsets.js
index 27848af..a8c9133 100644
--- a/inst/rmd/h/navigation-1.1/tabsets.js
+++ b/inst/rmd/h/navigation-1.1/tabsets.js
@@ -56,7 +56,7 @@ window.buildTabsets = function(tocID) {
       a.attr('aria-controls', id);
       var li = $('<li role="presentation"></li>');
       li.append(a);
-      if (i === 0)
+      if (i === 2)
         li.attr('class', 'active');
       tabList.append(li);
 
@@ -66,7 +66,7 @@ window.buildTabsets = function(tocID) {
       tab.addClass('tabbed-pane');
       if (fade)
         tab.addClass('fade');
-      if (i === 0) {
+      if (i === 2) {
         tab.addClass('active');
         if (fade)
           tab.addClass('in');

```

**Comment by jjallaire** [comment]
You can now add the `{.active}` attribute to a tab section to specify it as the initially active tab. https://github.com/rstudio/rmarkdown/commit/919f54c7f2abe72299b8b2a70f6ca6a265ebe3b3

**Comment by frkbr** [comment]
@jjallaire is the {.active} attribute still working in the current version of RMarkdown? I try to make the second Subtab the initially active tab, and it does not work:

`First Subtab {data-navmenu="Level 1 Tab"}`
`Second Subtab {data-navmenu="Level 1 Tab" .active}`

RMarkdown still displays the first Subtab as the initially active tab. Should I use the attribute differently?

**Comment by cderv** [comment]
Hi @frkbr 

`.active` is still working in `html_document` output with tabset panel. 

<details><summary>See this example  where the panel by Region is by default selected if active class is provided</summary>

````r
---
title: test
output: html_document
---

## Quarterly Results {.tabset}

### By Product

(tab content)

### By Region

(tab content)

## Quarterly Results {.tabset}

### By Product

(tab content)

### By Region {.active}

(tab content)
````
![image](https://user-images.githubusercontent.com/6791940/79683881-86819580-822d-11ea-806e-b210065dd787.png)

</details>

If you have any issue with the usage of tabset, I would advice to ask on https://community.rstudio.com - there is a broad community ready to help. I see `data-navmenu` used so I wonder if you are not trying to mix it with flexdahboard 🤔 
If you encounter a bug with a format, open an issue including a reproducible example as it will help us help you. 

Hope it helps.

**Comment by frkbr** [comment]
@cderv you are right, I'm trying to use `{.active}`with flexdashboard, not with tabset. As I understand you, that attribute probably does not work in flexdashboard? In what repo would you then recommend I open an issue with a reproducible example? rmarkdown or flexdashboard?

**Comment by cderv** [comment]
If you are not sure this is a bug or not, you can always ask on https://community.rstudio.com with a reproducible example. 
Then if a bug is found, or if this is a feature request, you open it in the correct repository. 

In your case, I would open it in flexdashboard repo as this is what you seem to use.
