### ISSUE TITLE
R markdown render HTML (with datatable)  and included in Shiny Server

### ISSUE THREAD

**Issue by xtmgah** [rstudio/rmarkdown#792]
Hello: 

I use R markdown to render data_QC.Rmd to data_QC.html file by click the "knit HTML" button on Rstudio. in Rmd file, i included multiple table using DT::datatable. (because the render will take a long time calculation.. so, after rendering, i using another quick.Rmd file design to only included the "data_QC,html" with following script: 

``` r echo=FALSE
htmltools::includeHTML("data_QC.html")
```

When i render this quick.Rmd using the Rstudio "knit HTML" button, it can corrected show all the tables. However, When i put the same data_QC.html and quick.Rmd to Shiny Server,  no table will showing. Any suggestion here? Thanks.

**Comment by yihui** [comment]
I'm not entirely sure about the reason of the difference between your local HTML and the one you deployed to Shiny Server (it is easier to diagnose if you can share a link), but I don't recommend you to do it this way, because you are inserting a full HTML document into another HTML document, which renders an invalid HTML document. If the datatables are slow to render, you can cache the code chunks by setting the chunk option `cache = TRUE`, and remember to upload the cache folder along with the Rmd when you deploy.

**Comment by xtmgah** [comment]
Thanks for your reply. It really helpful. It' there any way to show html
file directly through shiny server.  No app, and no Rmd , just show the
html files (interactive files )using shiny server.

-- 
Tongwu Zhang

**Comment by xtmgah** [comment]
The reason I want to do this is the data is large and the R programming
will taking a little long time for calculation. So, is there any other way
to render the Rmd without put every data on shiny server?

-- 
Tongwu Zhang

**Comment by yihui** [comment]
The canonical way to include one HTML file into another is to use `<iframe>`, e.g. 

```r
htmltools::tags$iframe(src = 'data_QC.html', width = '100%', height = '...')
```

**Comment by xtmgah** [comment]
Hello: 

I make the following shiny app as your suggestion but only show "Not Found" on the website....Can you help to check? thanks/ 

library(shiny)

# Define UI for application that draws a histogram
ui <- shinyUI(fluidPage(
  htmltools::tags$iframe(src = 'data_QC_MM.html', width = '100%', height = '100%')
  #rmarkdown::render('data_QC_source.html')
))

# Define server logic required to draw a histogram
server <- shinyServer(function(input, output) {
})

# Run the application 
shinyApp(ui = ui, server = server)

**Comment by yihui** [comment]
It is a Shiny app, you should put `data_QC.html` under the `www` directory.

**Comment by xtmgah** [comment]
thanks. It now working. but all the html was limited on top very small window... is there any way to make the html full size as the webpage ?

**Comment by yihui** [comment]
`width=100%` is okay, and I think the problem is the height. Unless you are using an ancient web browser, you may try `height='100vh'` (http://www.w3schools.com/cssref/css_units.asp)

You can learn more about iframes here http://www.w3schools.com/html/html_iframe.asp

**Comment by xtmgah** [comment]
Hello:

Thanks for your help. I will try it later.  Also. Another question, if I
use cache when render Rmd file, how do it copy two cache files in one shiny
app? The cache fold will be different?

-- 
Tongwu Zhang

**Comment by yihui** [comment]
If you do not need to render the Rmd periodically on the Shiny Server, you don't need to do anything else. Just upload the www directory with the app, and you are done. Next time you regenerate the HTML output locally and redeploy.

If you do need to regenerate HTML output on the server side, you can put the Rmd document under the `www` directory as well, and render it there. When you deploy the app, just remember to  upload the cache directory along with the Rmd source.
