### ISSUE TITLE
validate requires file but does not check href

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/rmarkdown#794]
While developing `googlefontR`, I discovered that [lines](https://github.com/rstudio/rmarkdown/blob/master/R/html_dependencies.R#L217-L220) only check for `file` and not `href` when validating dependencies.  It seems either `file` or `href` should make a valid dependency.  I would like to not have to download every font available from Google.  Is it possible to validate with just `href` as `src`?

**Comment by timelyportfolio** [comment]
Any inclination to address this, especially in light of https://github.com/rstudio/shiny/issues/1389?  Will close if no interest or inclination, but the asynchronous behavior should not affect non-shiny rmarkdown.  Downloading, storing, and maintaining local dependencies is difficult, but impossible in the case of something like google fonts.

**Comment by crazycapivara** [comment]
I also have the problem with my [deckgl-r-package](https://github.com/crazycapivara/deckgl). In the latest version I added some js libs via the `href` parameter to not blow up the package size. I am creating a gallery site but cannot use features where the libs are included via `href`.

**Comment by matthewstrasiotto** [comment]
same here with my package [mandrake](https://github.com/matthewstrasiotto/mandrake) . 

As of  https://github.com/rstudio/htmltools/pull/188 , crossorigin resource checks can use SRI and are safe, but I was very surprised to see that these two APIs are not in alignment. 

For now, I suppose I'll install @crazycapivara 's fork (thank you for that) to drive my site.

**Comment by cderv** [comment]
Hopefully this should now be fixed in **rmarkdown** dev version. 

```r
remotes::install_github("rstudio/rmarkdown")
```

Thanks for the report - it was long overdue. Thanks @crazycapivara and @matthewstrasiotto for the two PRs that greatly help makes this finally happens.

**Comment by matthewstrasiotto** [comment]
Ah, sad to not get a contributor listing, but i must admit i did forget my promise to give you push access to my fork.
Thank you making it happen!

**Comment by cderv** [comment]
The commit for the PR is still co-authored by you - this was not loose in the process of making another PR. See https://github.com/rstudio/rmarkdown/commit/7107c68047c6952fada50aa8df6cbc2f75ad7cd4

**Comment by yihui** [comment]
We didn't do well enough to keep track of contributors in DESCRIPTION in this package in the past (I have tried harder in [the **knitr** package](https://github.com/yihui/knitr/blob/master/DESCRIPTION)): https://github.com/rstudio/rmarkdown/blob/master/DESCRIPTION#L17 

Please feel free to submit a PR to add your name to the list of contributors there. Thanks!

**Comment by matthewstrasiotto** [comment]
> The commit for the PR is still co-authored by you - this was not loose in the process of making another PR. See https://github.com/rstudio/rmarkdown/commit/7107c68047c6952fada50aa8df6cbc2f75ad7cd4
> 

Oh, that's plenty good enough for me
