### ISSUE TITLE
A theme is required in order to use the code folding option. Can we remove this requirement? 

### ISSUE THREAD

**Issue by tylerlee** [rstudio/rmarkdown#797]
I know this isn't the only place where an rmarkdown option requires a theme -- but is it necessary that you have a theme here?

My use case is we have a custom document template where we have set the theme to null (and then include our own css). The authors want to use code_folding but because our theme is set to null we can't use it. I understand I'll have to add some css to our custom stuff in order for code_folding to work appropriately, but that I can handle. 

Can we remove this restriction?

Added by @jjallaire in 
https://github.com/rstudio/rmarkdown/commit/3bf6857500a153e31afed256ed13de5f7d465144#diff-d244a3f1d96cb8bba005d659d4cdc69dR280

Thanks for the work everyone

**Comment by jjallaire** [comment]
The problem is that code folding makes use of Bootstrap CSS and JavaScript (i.e. requires a theme). The only way to remove this restriction is to implement alternate versions of code folding behaviors with raw jquery and perhaps some additional CSS. Open to a PR here if you are so inclined.

**Comment by tylerlee** [comment]
Went ahead and just used the folding javascript in our custom theme. I'll go ahead and close this since I'm the only one who needed this so far.  Thanks jj
