### ISSUE TITLE
Empty _files directory created with ioslides, self_contained and lib_dir

### ISSUE THREAD

**Issue by wjhopper** [rstudio/rmarkdown#801]
Normally if you use the `self_contained: false` YAML option for an rmarkdown document (lets say it's called `document.Rmd` for example), external dependencies such as css, javascript and any figures that get created are placed in a special directory following the naming convention "name_of_Rmd_file" + "_files" (so here the external dependencies folder for my example .Rmd file would be called `document_files`)

If you use the `self_contained: false` option along with the `lib_dir` YAML option and the `fig.path` knitr option when rendering a standard `html_document` file, no directory called `document_files` gets created. Consider the following example:

``````

---
title: "No _files dir created"
output: 
  html_document:
      self_contained: false
      lib_dir: libs

---

```{r setup, include=FALSE}
knitr::opts_chunk$set("cache" = FALSE, "fig.path" = "figures/")
```

## Including Plots
You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```
``````

Not creating the `document_files` directory makes sense here: all the plots that get created get placed in the the `figures/` directory, and all the javascript/css gets placed the `libs` directory, so there is no need for  the `document_files` directory.

But if I use the same setup when creating an `ioslides_presentation`, a `document_files` directory _is_ created, and it's empty, because all the external dependencies are placed elsewhere! To see this, contrast the output from this example file with the previous one:

``````

---
title: "Empty _files dir created!"
output: 
  ioslides_presentation:
      self_contained: false
      lib_dir: libs

---

```{r setup, include=FALSE}
knitr::opts_chunk$set("cache" = FALSE, "fig.path" = "figures/")
```

## Including Plots
You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```
``````

My question: Is there anyway to prevent these empty directories from being generated when rendering stand alone ioslides presentations? Or is this a bug? 

Here's my `sessionInfo()`, in case it's relevant

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_1.5    htmltools_0.3.5 tools_3.3.1     yaml_2.1.13    
 [5] Rcpp_0.12.7     stringi_1.1.1   rmarkdown_1.0   knitr_1.14     
 [9] stringr_1.1.0   digest_0.6.10   evaluate_0.9 
```

**Comment by yihui** [comment]
ioslides is an exception among all output formats, and it can behave differently with other formats. That said, I guess we probably won't fix this issue; it is a little annoying to have an empty directory created, but it is empty anyway. For more on the state of ioslides, see https://github.com/rstudio/rmarkdown/pull/404#issuecomment-326354500, #298, and #730. Thanks for the report!
