### ISSUE TITLE
output_dir: "docs" copies unnecessary files (i.e. non-documentation files)

### ISSUE THREAD

**Issue by randyzwitch** [rstudio/rmarkdown#804]
Follow-up of #803 

Now that I am able to direct my output to the `docs` directory so that I can use GitHub Pages, I'm noticing that the copying script replicates the entire package into `docs`, not just the documentation.

```
Randys-MacBook-Pro:RSiteCatalyst randyzwitch$ ls -ltr
total 96
drwxr-xr-x  12 randyzwitch  staff   408 Sep  9 09:59 tests
drwxr-xr-x  84 randyzwitch  staff  2856 Sep  9 09:59 man
-rw-r--r--   1 randyzwitch  staff  9149 Sep  9 09:59 README.md
drwxr-xr-x  84 randyzwitch  staff  2856 Sep  9 09:59 R
-rwxr-xr-x   1 randyzwitch  staff  4458 Sep  9 09:59 NEWS
-rw-r--r--   1 randyzwitch  staff  2354 Sep  9 09:59 NAMESPACE
-rw-r--r--   1 randyzwitch  staff    80 Sep  9 09:59 LICENSE
-rw-r--r--   1 randyzwitch  staff   600 Sep  9 09:59 DESCRIPTION
-rw-r--r--   1 randyzwitch  staff   225 Sep 14 19:47 RSiteCatalyst.Rproj
-rw-r--r--   1 randyzwitch  staff    61 Sep 14 20:23 about.Rmd
-rw-r--r--   1 randyzwitch  staff    44 Sep 14 20:50 index.Rmd
-rw-r--r--   1 randyzwitch  staff   160 Sep 14 21:01 _site.yml
drwxr-xr-x  13 randyzwitch  staff   442 Sep 15 09:33 docs
Randys-MacBook-Pro:RSiteCatalyst randyzwitch$ cd docs
Randys-MacBook-Pro:docs randyzwitch$ ls -ltr
total 112
drwxr-xr-x  12 randyzwitch  staff    408 Sep 15 09:33 tests
drwxr-xr-x   6 randyzwitch  staff    204 Sep 15 09:33 site_libs
drwxr-xr-x  84 randyzwitch  staff   2856 Sep 15 09:33 man
-rw-r--r--   1 randyzwitch  staff   4526 Sep 15 09:33 index.html
-rw-r--r--   1 randyzwitch  staff   4551 Sep 15 09:33 about.html
-rw-r--r--   1 randyzwitch  staff  16880 Sep 15 09:33 README.html
drwxr-xr-x  84 randyzwitch  staff   2856 Sep 15 09:33 R
-rwxr-xr-x   1 randyzwitch  staff   4458 Sep 15 09:33 NEWS
-rw-r--r--   1 randyzwitch  staff   2354 Sep 15 09:33 NAMESPACE
-rw-r--r--   1 randyzwitch  staff     80 Sep 15 09:33 LICENSE
-rw-r--r--   1 randyzwitch  staff    600 Sep 15 09:33 DESCRIPTION
```

You can see that `R`, `tests` and `man` in `docs` are exact copies of the files at the root of my directory, which I think is unnecessary.

My use case is this: I'd like to use the same [GitHub repo](https://github.com/randyzwitch/RSiteCatalyst) for my R package code and HTML documentation. Ideally, I would be able to put my Markdown in the docs directory AND build them from the docs directory (I think the requirement is the _site.yml and `index.Rmd`) have to be at the root level.

IF I have to keep the documentation markdown at the root level, that's fine, but I don't think the  `R`, `tests` and `man` source files should be copied into the documentation area (thus, creating a duplicate).

**Comment by jjallaire** [comment]
I'd suggest that you put the entire site in the docs directory (including
_site.yml) and just create a separate RStudio project within that scope.
This site would use '.' as it's output_dir.

My reasoning is that you don't want to have all of those documentation
artifacts at the root level of your package (needing to .Rbuildignore them,
etc.)

If you really, really want to make this work then you can use "exclude"
within _site.yml to exclude R, tests, man, DESCRIPTION, etc. etc.

**Comment by randyzwitch** [comment]
Great, thanks for the hint. I'll close this, but maybe it's something for the documentation or tutorial?

**Comment by jjallaire** [comment]
Yup, I'll add something to the docs
