### ISSUE TITLE
Run latex twice?  Needed for glossaries package

### ISSUE THREAD

**Issue by elbamos** [rstudio/rmarkdown#805]
The LaTeX glossaries package requires running the LaTeX engine twice for the glossaries to show up.  Is there a way to do this from rmarkdown?

**Comment by yihui** [comment]
rmarkdown uses latexmk to compile LaTeX, so you should not need to worry about how many times the document needs to be compiled (latexmk should be smart enough). If latexmk is not available, rmarkdown will fallback to calling the LaTeX engine three times. In either case, it does not seem to be an issue, so please bring a minimal reproducible example to show the problem.

**Comment by thetapper** [comment]
This would be my minimal example.Rnw for the mentioned problem:

```
    \documentclass{article}
    \usepackage[acronym]{glossaries}
    \makeglossaries
    \newacronym{abc}{ABC}{Alphabet}

    \begin{document}
    \SweaveOpts{concordance=TRUE, echo=FALSE}
    \acrfull{abc} is my acronym. 
    \printglossary[type=\acronymtype]
    \end{document}
```
The compiled PDF misses the glossary..

**Comment by yihui** [comment]
@thetapper That is an Rnw document, which is not within the scope of the rmarkdown package. If it does not work as expected, it is more likely to be an RStudio IDE issue.
