### ISSUE TITLE
github_document: latex expressions get messed up

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#806]
Initially reported discovered by @mine-cetinkaya-rundel -- MathJax within `.Rmd` documents rendered with the `github_document` format get their LaTeX munged up, e.g.

``` Rmd

---
title: "MathJax"
author: "Kevin Ushey"
date: "September 15, 2016"
output:
  github_document:
    toc: true

---

This is inline math: $P(|\epsilon| > \kappa \sigma)^n$.

This is a chunk of math:

$$
P(|\epsilon| > \kappa \sigma)^n
$$
```

is rendered as

``` md
MathJax
================
Kevin Ushey
September 15, 2016

This is inline math: *P*(|*ϵ*|&gt;*κ**σ*)<sup>*n*</sup>.

This is a chunk of math:

*P*(|*ϵ*|&gt;*κ**σ*)<sup>*n*</sup>
```

Is there a pandoc option we should enable by default here, or something else that needs to be done?

**Comment by kevinushey** [comment]
Ah, it looks like GitHub actually doesn't try to render latex with MathJax anymore, and so we try to pre-render the latex and insert the generated text into the `.md` document. Unfortunately, it looks like something is going wrong when rendering some of these equations?

**Comment by kevinushey** [comment]
Sorry, the rendered Markdown here is correct; the issue here is specifically with the HTML preview generated -- the conversion from `github_markdown` to `html` seems to go awry with MathJax equations. It looks like:

```md
*P*(|*ϵ*|&gt;*κ**σ*)<sup>*n*</sup>
```

becomes

```html
<em>P</em>(|<em>ϵ</em>|&gt;*κ**σ<em>)<sup></em>n*</sup>.</p>
```

after pandoc has transformed from Markdown to HTML. Note that the inner `*`s were not translated; likely because there is no whitespace separating the two `*` in `*κ**σ*`.

**Comment by kevinushey** [comment]
One workaround is to insert a latex 'negative' space in between the identifiers, e.g.

```
$P(|\epsilon| > \kappa \! \sigma)^n$
```

**Comment by jjallaire** [comment]
One saving grace is that there isn't much expectation of MathJax working
well with GitHub (since it's just based on pandoc's simple emulation)

**Comment by yihui** [comment]
I'd say that if you really care about LaTeX math in Markdown, you should render to HTML output instead of waiting indefinitely for Github to support MathJax in Markdown, which I doubt will ever happen.
