### ISSUE TITLE
Anybody encountered issue the location of graph/figure

### ISSUE THREAD

**Issue by henrywoo** [rstudio/rmarkdown#809]
I find the figure can jump over the text after it after converting to pdf. How did you solve this issue? Any suggestion?

**Comment by yihui** [comment]
That is normal. Figures often have to float in LaTeX, and this was briefly explained here: https://bookdown.org/yihui/bookdown/figures.html

There is no perfect solution to this problem. Figures just have to float. This is what I use in the LaTeX preamble to alleviate the problem:

```latex
\renewcommand{\textfraction}{0.05}
\renewcommand{\topfraction}{0.8}
\renewcommand{\bottomfraction}{0.8}
\renewcommand{\floatpagefraction}{0.75}
```

You may see http://rmarkdown.rstudio.com/pdf_document_format.html#includes on how to add stuff to the preamble.
