### ISSUE TITLE
Is there a way to create multi-page HTML documents with rmarkdown?

### ISSUE THREAD

**Issue by henrywoo** [rstudio/rmarkdown#810]
I was wondering if there is a way to create structured, multi page documents (e.g. with a navigation sidebar or something similar) with kntir/rmarkdown?

I was using sphinx and it is able to do that. I hope I can do the same like sphinx.

多谢.

**Comment by yihui** [comment]
Yes, bookdown is one possibility:

- https://bookdown.org
- https://github.com/rstudio/bookdown/
