### ISSUE TITLE
Knit problem - pandoc: Could not fetch array.png ....

### ISSUE THREAD

**Issue by THNCAD** [rstudio/rmarkdown#811]
I received this error message, would you please tell me what I should do?

pandoc: Could not fetch array.png
array.png: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted

Thanks

**Comment by yihui** [comment]
Find out where you used array.png in your R Markdown document, and if this file really exists in the directory of the document.

**Comment by EMIjess** [comment]
I have this same issue. image.png definitely exists within /Dir

Within my .Rmd, I have:


\```{r}
knitr::include_graphics("Dir/image.png")
\```

on knit to HTML, I get:

pandoc: Could not fetch ~/Dir/image.png
~/Dir/image.png: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
Execution halted

In older versions, I could use the markdown syntax ![Alt text][path] but that is not working either, with quoted or unquoted path, it just looks like another footnote.

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8     withr_1.0.1     digest_0.6.11   dplyr_0.5.0     assertthat_0.1 
 [6] R6_2.2.0        DBI_0.5-1       git2r_0.11.0    magrittr_1.5    evaluate_0.10  
[11] httr_1.2.1      stringi_1.1.1   curl_1.2        rmarkdown_1.1   tools_3.3.2    
[16] stringr_1.1.0   yaml_2.1.14     rsconnect_0.4.3 memoise_1.0.0   htmltools_0.3.5
[21] knitr_1.15.1    tibble_1.2 
```

**Comment by yihui** [comment]
@EMIjess In your code, you had `Dir/image.png`, but in your error message, it was `~/Dir/image.png`. I don't know why they are different. Anyway, `~/Dir/image.png` won't work because Pandoc won't do tilde expansion. You have to expand `~` to your home directory, but in general, it is a bad idea to use absolute paths. I wonder why you could not use a relative path here.
