### ISSUE TITLE
Changing Python executable to Ananconda

### ISSUE THREAD

**Issue by rouseguy** [rstudio/rmarkdown#812]
I use Anaconda as my Python distribution. 

How do I set the notebook so that it picks the Anaconda's Python and not the system default ?

**Comment by rouseguy** [comment]
Figured this out. Need to use `engine.path`

```
```{python, engine.path="/anaconda/bin/python"}
import pandas as pd
print(pd.__version__)
data = pd.read_csv("~/Documents/data/train.csv")
print(train.head())
```

**Comment by MGallow** [comment]
This is a minor issue but is there a way to set Rstudio to default to the correct engine.path?

**Comment by kevinushey** [comment]
Good question -- I think this could be accomplished with a `knitr` hook, e.g. in a setup chunk (pseudocode):

    ```{r setup}
    knit_hooks$set(engine = function(before, options, envir) {
        # detect python, set engine.path
    })
    ```

@yihui, does this sound like a solution?

**Comment by yihui** [comment]
@kevinushey It is a solution, but perhaps it feels a little weird. I just added a more straightforward approach to knitr, and you can install the development version via

```r
devtools::install_github('yihui/knitr')
```

Then you can set up the path of python in a code chunk like this:

    ```{setup, include=FALSE}
    knitr::opts_chunk$set(engine.path = list(python = '/anaconda/bin/python'))
    ```

And the rest of python code chunks will use `/anaconda/bin/python`.

**Comment by kevinushey** [comment]
@yihui that's awesome, thanks!

**Comment by MichaelChirico** [comment]
for the record this should be documented here: http://rmarkdown.rstudio.com/authoring_knitr_engines.html

**Comment by aedobbyn** [comment]
Unfortunately, neither setting my `opts_chunk` like this nor editing my .Rprofile to add Sys.setenv(PATH = paste("<path_to_python3>", Sys.getenv("PATH"), sep=":")) has set the default python correctly. I have no trouble setting an individual chunk to run python3 by setting the engine.path for that chunk, but setting all chunks to default to python3 hasn't worked; it still defaults to python2. I'm on version 1.1.423 of RStudio for Mac and R version 3.3.3. @yihui I'd love to hear any suggestions about what I might be doing wrong.

**Comment by MichaelBeyeler** [comment]
I'm having the same issue. I can't get RStudio to recognize my Anaconda 2 python.

What WOULD work, is adding Anaconda to %PATH%, but I don't want to do that because that causes all sorts of other troubles in Windows.
