### ISSUE TITLE
Feature Request: Font-Awesome Icons in Rmarkdown Docs

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/rmarkdown#813]
I've noticed that it's currently quite complicated to [insert font-awesome icons in Rmarkdown documents](http://stackoverflow.com/a/36343616/5170276).

Could this be made easier somehow? It's so straight-forward in `shiny`...

Thanks!

**Comment by jjallaire** [comment]
font-awesome is actually now included in the rmarkdown package (we use it for icons on the navbar for R Markdown websites). You can currently force it to be included in the document with the following code:

    ```{r, include=FALSE}
    htmltools::tagList(rmarkdown::html_dependency_font_awesome())
    ```

But of course we should make this much more straightforward!

**Comment by tiernanmartin** [comment]
This solution doesn't seem to be working correctly. Did I misunderstand your suggestion, @jjallaire ?

```
---
output: html_document
---

#```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
#```

#```{r}
shiny::icon('file',lib = "font-awesome")
#```

##Error: path for html_dependency not provided
##Execution halted

```

**Comment by jjallaire** [comment]
My solution is intended to allow you to add font awesome classes directly to e.g. `<i>` tags rather than to use the `shiny::icon` function, e.g. this works:

    ---
    output: html_document
    ---

    ```{r setup, include=FALSE}
    htmltools::tagList(rmarkdown::html_dependency_font_awesome())
    ```

    <i class="fa fa-file"></i>

**Comment by tiernanmartin** [comment]
Got it – thanks for the clarification!

**Comment by walmes** [comment]
This can also be used with bookdown html based documents. To accomplish I include the chunk below. The `fontawesome-webfont.ttf`must be included as an attachment to render.

    ```{r, include = FALSE, eval = knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"}
    # Enables Font Awesome in HTML based bookdown outputs.
    fa <- rmarkdown::html_dependency_font_awesome()
    fa$attachment <- "fonts/fontawesome-webfont.ttf"
    htmltools::tagList(fa)
    ```

Bests.

**Comment by yihui** [comment]
@walmes Interesting. fontawesome-webfont.ttf is included in bookdown: https://github.com/rstudio/bookdown/tree/master/inst/resources/gitbook/css/fontawesome So in theory, you don't need to add it in the HTML dependency.

**Comment by jtr13** [comment]
Worked for me in bookdown exactly as @jjallaire and @yihui stated, without attaching the `.ttf` file.

**Comment by ferroao** [comment]
Here is a workaround if you do not want the 5Mb added by (rmarkdown::html_dependency_font_awesome()).

In yaml:
output:
  html_document:
    includes:
      in_header: myheader.html

setup chunk: (get url of .js in https://fontawesome.com/v4.7.0/get-started/ )

```{r setup, include=FALSE}
#Create myheader.html
fileConn <- file("myheader.html")
writeLines('<script src="https://kit.fontawesome.com/<get In Link>.js" crossorigin="anonymous"></script>', fileConn)
close(fileConn)
```
works great for fontawesome 4. For 5, you need to register one .js for each project
Ready!
