### ISSUE TITLE
rmarkdown::render Discrepancy When run from Shiny

### ISSUE THREAD

**Issue by thecomeonman** [rstudio/rmarkdown#814]
As described [here](http://stackoverflow.com/questions/39661793/rmarkdownrender-discrepancy-when-run-from-shiny), rendering an RMD file from a Shiny session doesn't evaluate any of the R code. The same file, when knit from Rstudio, gives correct output. A theory ruled out is that `knitr::opts_chunk$set(include = TRUE)` was set to `FALSE`.

The arguments to the command ( `/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS 0.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Test.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /usr/local/lib/R/site-library/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /tmp/RtmpLEjCNI/rmarkdown-str5fa013e4c567.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/usr/local/lib/R/site-library/rmarkdown/rmd/h/highlight --variable navigationjs=/usr/local/lib/R/site-library/rmarkdown/rmd/h/navigation-1.1` ) looks identical in both cases.

Here are the two output files - https://drive.google.com/open?id=0B2K_uftT7xKxS3BrNjZMdURaaW8 and https://drive.google.com/open?id=0B2K_uftT7xKxa01kYTdGVjU0bzg which clearly look different, esp. in some of the scripts being sourced.

Thanks!

**Comment by thecomeonman** [comment]
I investigated this further. It turns out that the issue arose because I used Shiny's fileInput button to select a template. This moves it to /tmp/.../0 and that is what gets read to create the HTML file. If I hardcode the path to the template then this works fine. Still don't understand why though.
```

library(shinydashboard)
  ui <- dashboardPage(

  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
         title = 'Tab2',
         actionButton("Run", "Run"),
     fileInput(inputId = 'rmd', label = 'RMD')
      )
   )
)

# Server logic
server <- function(input, output, session) {

  observeEvent(input$Run, {
     
    rmarkdown::render(
  '/home/ask/Desktop/qweqwe.Rmd',
  params = list(
     dtDataset = mtcars
  ),
  output_file = c('Test.html')
)

    rmarkdown::render(
  input$rmd$datapath,
  params = list(
     dtDataset = mtcars
  ),
  output_file = c('TestFileInput.html')
)
  })


}

# Complete app with UI and server components
shinyApp(ui, server)
}
```

**Comment by cderv** [comment]
I replayed the example above and this works fine. 

Both Rmd file are rendered - the first one is rendered locally where is (from the working directory the app is launch), the second one is rendered from within the temp directory where the uploaded tempfile (named `0.Rmd`) has been put. 

The resulting HTML file should be moved or pass to a download handler to be accessed. 

i'll close this as it seems it is no more an issue.
