### ISSUE TITLE
header-includes doesn't seem to work in .Rmd file

### ISSUE THREAD

**Issue by richarddmorey** [rstudio/rmarkdown#816]
I'd like to inject content generated from an R function into my shiny/flexdashboard page's header. Yihui suggested that I try header-includes in my YAML header, e.g., in my `.Rmd` file

```

---
output: html_document
header-includes: "<!---\n Hi there\n --->"

---

## Testing
```

(this is just a minimal example; eventually I want something like header-includes: ``r foo()``, and all the flexdashboard/shiny stuff)

However, this does not result in anything being injected into my page's headers. I would expect to see 

```
<!---
 Hi there
 --->
```

in my page's `<head>` section. Here's my session info:

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] magrittr_1.5             rsconnect_0.4.3         
 [3] htmltools_0.3.5          tools_3.3.1             
 [5] flexdashboard_0.3.0.9000 yaml_2.1.13             
 [7] Rcpp_0.12.7              rmarkdown_1.0.9002      
 [9] stringi_1.1.1            knitr_1.14              
[11] jsonlite_1.1             stringr_1.1.0           
[13] digest_0.6.10            evaluate_0.9    
```

Thanks.

**Comment by yihui** [comment]
Perhaps the command-line argument `--include-in-header` generated by **rmarkdown** overrode `header-includes`. Anyway, I tried this and it worked:

    ---
    output: 
      html_document: 
        includes:
          in_header: foo.html
    ---
    
    ## Testing
    
    ```{r}
    writeLines('<!-- whatever -->', 'foo.html')
    ```
    
You just need to make sure the filename `foo.html` does not clash with existing files.

**Comment by richarddmorey** [comment]
Am I correct that this will require an extra compilation to get the information into the document; the first to write the headers to the file, and the second to include the information in the header?

**Comment by yihui** [comment]
No, one pass should be enough. The `in_header` file is read after the document has been knitted (in other words, code chunks have been executed).
