### ISSUE TITLE
R Notebook. Using custom figure size gives error

### ISSUE THREAD

**Issue by nuskcalb** [rstudio/rmarkdown#818]
If I try to change the figure size in a R Notebook, using the chunk menu option "Use custom figure size" it modifies the r chunk header acordingly:
"```{r, fig.height=600, fig.width=800}

Which, independently of the actual resolution used, gives the following error:

> cairo error 'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'
> Error in (function (filename = "Rplot%03d.png", width = 480, height = 480,  : 
>   unable to start device 'png'

**Comment by crsh** [comment]
`fig.height` and `fig.width` [by default](http://yihui.name/knitr/options/) interpret values in inches. The graphic you are trying to create here is too big (see the error message). Assuming you wanted to create a plot of size 800x600 pixels use this chunk header:

    {r, fig.height=600px, fig.width=800px}

**Comment by nuskcalb** [comment]
Thanks @crsh !

1. If I use "{r, fig.height=600px, fig.width=800px}", I get a warning in the console:

> (*) NOTE: I saw chunk options ", fig.height=1600px, fig.width=800px"
>  please go to http://yihui.name/knitr/options
>  (it is likely that you forgot to quote "character" options)

And an error when trying to save the R Notebook (yellow RStudio top notification):

> Error creating notebook: <text>:1:23: unexpected symbol 1: alist( fig.height=600px^

2. Wouldn't be pixels a better default, particularly for the international audience? :)

Thanks again for the quick response!

**Comment by yihui** [comment]
You cannot use pixels for `fig.height`/`fig.width`. The unit is always inches. 600 and 800 inches are way too big (about the area of a house). You just need smaller values here (default is 7x5).
