### ISSUE TITLE
Possible Feature Request: Print HTML as pdf directly

### ISSUE THREAD

**Issue by haozhu233** [rstudio/rmarkdown#823]
`LaTeX` definitely has its shiny points on paging but I believe many people today, as I do, feel like HTML is a much approachable way to generate a good-looking report (especially with `prettydoc`). However, the reality is that, in many cases, pdf might be a better way to send documents to other people (unless there are htmlwidgets in the HTML reports). 

As a result, I often go through a process that, first I generate a HTML report and then I open it up in Chrome and print it as pdf. I'm wondering if rstudio can import the print HTML page feature from either Chrome or Firefox (even safari) and make a button like "render HTML-pdf"? Is it possible? Thanks!

**Comment by yihui** [comment]
You can see if webshot works well for you: https://github.com/wch/webshot

**Comment by haozhu233** [comment]
@yihui Great! I was expecting an integrated feature (like a `print_as_pdf` option under `html_output` in the yaml file) but this definitely makes the process a lot easier! Thanks! :+1:
