### ISSUE TITLE
Rmarkdown with Shiny and cache=TRUE

### ISSUE THREAD

**Issue by Bustami** [rstudio/rmarkdown#824]
I don't know how to configure a Rmd file with shiny in order to run it without running again and again the previous chunks, each time. I set cache=TRUE for all chunks previous to Shiny's chunk which contains the selectInput and renderPlot functions. But anyway, the code is excuted complete each time.

**Comment by alrutten** [comment]
i ran into the same problem, see also [this stackoverflow question](https://stackoverflow.com/questions/30246597/possible-to-use-knitr-cache-chunk-in-interactive-rmarkdown-doc/44112524#44112524). You can now use `runtime:shiny_prerendered` in the YAML header, and `context=data` and `cache=TRUE` for your chunks to prevent re-evaluating (time-intensive) chunks.
