### ISSUE TITLE
ioslides and render: style.css deleted with clean = TRUE, out_format = "all", and intermediates dir set.

### ISSUE THREAD

**Issue by PedramNavid** [rstudio/rmarkdown#826]
When using a stylesheet with an ioslides Rmd presentation, using the following render command deletes the stylesheet for some reason:
`render("test.Rmd", output_format = "all", intermediates_dir = ".", clean = TRUE)`

If I don't set the intermediates dir it doesn't delete the files. It will delete the stylesheet regardless of what folder it is in. 

Attached a minimal example. 
[test.zip](https://github.com/rstudio/rmarkdown/files/511333/test.zip)

**Comment by yihui** [comment]
Thanks for the report, but we probably won't fix it... (see https://github.com/rstudio/rmarkdown/issues/801#issuecomment-326624787). Not sure why you needed an explicit `intermediate_dir`.
