### ISSUE TITLE
Applying a pandoc filter after pandoc-citeproc

### ISSUE THREAD

**Issue by crsh** [rstudio/rmarkdown#831]
Hi there, I have spent several hours looking for a solution but have come up empty. Any ideas would be greatly appreciated.

I'm creating documents that need citations in APA format. I'm using the APA citation style, which works great with one exception:

In APA guidelines 6th edition, Section 6.12 mention that:

> Precede the final name in a multiple-author citation in a running text by the word and. In parenthetical material, in tables and captions, and in the reference list, join the names by an ampersand (&).
> 
> as Kurtines **and** Szapocznik (2003) demonstrated
> as has been shown (Kurtines **&** Szapocznik 2003)

However, with pandoc-citeproc all "and" are rendered as ampersands.

> as Kurtines **&** Szapocznik (2003) demonstrated
> as has been shown (Kurtines **&** Szapocznik 2003)

I know this is because in-text citations are not supported by CSL and there is no way to define the in-text "and". I have written a simple filter that modifies the output of `pandoc-citeproc` to overcome this issue. The filter works on the AST and replaces all in-text `&` with `and`.

``` r
#!/usr/bin/env Rscript
intext_and <- function(x) {
  gsub("(\"citationMode\":\\{\"t\":\"AuthorInText\".*?\\})(.*?\\}\\],\\[.*?)(&)(.*?\\}\\]\\]\\})", "\\1\\2and\\4", x)
}

ast <- readLines(file("stdin"))
write(intext_and(ast), stdout())
```

The problem is, I need to call this filter after `--filter pandoc-citeproc`. From [another issue](https://github.com/rstudio/rmarkdown/issues/592) I get the impression the call to `pandoc-citeproc` is always appended at the end of the system call and there is no way to apply another filter after it. Is this indeed the case? Is there any way to apply a filter after `pandoc-citeproc`?

**Comment by crsh** [comment]
This issue is rather important to me because a package I'm working depends on the application of the additional filter. I'd be more than willing to tackle this issue myself and provide a pull request but I'd like to discuss what the best solution would be. For example, it would suffice for my purposes if I could use an argument to suppress the call to the `pandoc-citeproc`-filter. That way I could add it manually and apply my additional filter afterwards. Currently, it is determined automatically whether `pandoc-citeproc` is applied based on the information supplied in the YAML front matter. Would you accept a pull request that implemented such an additional argument?

**Comment by jjallaire** [comment]
I'd say the best way to do this would be to modify this function:

https://github.com/rstudio/rmarkdown/blob/f60364bca8adc258a9b484fa4cde1e0e756fdf46/R/output_format.R#L775-L779

I'd look for an additional "citeproc: false" YAML metadata entry and return
FALSE if it's found.

That way this behavior will work with all formats and won't require users
to pass an additional argument to render.

Would welcome a PR with this functionality! (please be sure to send a
contributor agreement:
https://github.com/rstudio/rmarkdown/blob/master/CONTRIBUTING.md as well as
update the NEWS file as part of the PR).

**Comment by crsh** [comment]
Thanks! Keep up the great work.
