### ISSUE TITLE
how to let rmarkdown parse text inside \begin and \end section

### ISSUE THREAD

**Issue by henrywoo** [rstudio/rmarkdown#833]
Hi YiHui, I used some latex syntax in Rmarkdown and can get correct output in pdf format. But I found everything inside \begin and \end section is not parsed and sometime gone, when i chose HTML format output. How can we output them in html format as if there were no \begin and \end?  Thanks!

**Comment by yihui** [comment]
Pandoc does not recognize LaTeX environments when the output is HTML (the only exceptions are LaTeX math environments). A workaround has been provided in bookdown: https://bookdown.org/yihui/bookdown/custom-blocks.html

**Comment by henrywoo** [comment]
`Custom blocks` only support one string? How can i pass more than one string?

Say my latex is:

```
\begin{question}{Business Case}{example}
\end{question}
```

**Comment by yihui** [comment]
```{block2, type='question', latex.options='{Business Case}{example}'}
    foo bar
    ```
