### ISSUE TITLE
export to OpenDocument Formats (.odp, .odt)

### ISSUE THREAD

**Issue by iembry-USGS** [rstudio/rmarkdown#844]
Hi, in a future version of RMarkdown, will it be possible to export to OpenDocument Formats (.odp and .odt)?

Thank you.

Irucka Embry

**Comment by yihui** [comment]
There is an output format `rmarkdown::odt_document`. Have you tried it?

**Comment by jjallaire** [comment]
There is an ODT format available now:
http://rmarkdown.rstudio.com/odt_document_format.html

**Comment by iembry-USGS** [comment]
Thank you @yihui  and @jjallaire for pointing out to me about the .odt format. What about .odp for presentations?

**Comment by yihui** [comment]
Pandoc does not support it, so we cannot support it, either: http://pandoc.org/MANUAL.html#producing-slide-shows-with-pandoc

**Comment by iembry-USGS** [comment]
@yihui - OK, thank you for letting me know.
