### ISSUE TITLE
problem  of installing  pandoc

### ISSUE THREAD

**Issue by chenwt** [rstudio/rmarkdown#851]
##Issue Description
I use  package visNetwork to save a  html
it raised out a error：

```
Couldnt get a file descriptor referring to the console
Error in htmlwidgets::saveWidget(graph, file, selfcontained) : 
  Saving a widget with selfcontained = TRUE requires pandoc. For details see:
https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
```
so i  wanted to install the pandoc ,but i have no root  in centos linux  system ,and the system is  too old to  support the latest pandoc binary.

how can i to solve this problem ?

I would be most grateful for your help!

**Comment by jjallaire** [comment]
The pandoc binary that ships with RStudio will work for CentOS 6. For
CentOS 5 you'd need to build from source on another system then copy the
binaries to your system.

You don't need root to make these binaries available (if you just copy them
to the ~/opt/pandoc/ directory they will be found by rmarkdown).

**Comment by Bryant-zhu** [comment]
@jjallaire  hi there, 
I have happened the same problem here. Could you help me explain your answer a little bit on this :
  "You don't need root to make these binaries available (if you just copy them
to the ~/opt/pandoc/ directory they will be found by rmarkdown)."

  I have only install R on my centos right now, if i want to use pandoc and markdown , did i need to do this ? 
  1 install Rstudio
  2 move the pandoc directory ?
  3

**Comment by yihui** [comment]
@Bryant-zhu You can either install RStudio and make symlinks (see [this doc](https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md)), or just install Pandoc directly (use the tarball of static binaries): http://pandoc.org/installing.html If you do not have root privileges, you may put the pandoc and pandoc-citeproc binaries under `~/opt/pandoc/` (note `~`).
