### ISSUE TITLE
render() fails to render figure with snug chunks

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#852]
NOTE: not yet sure if this is something that needs to be solved in `rmarkdown`, but reporting here for posterity...

Given the following document:

    ---
    title: "Hello World"
    output: html_document
    ---
    
    ```{r cars, echo=FALSE}
    knitr::kable(summary(cars))
    ```
    ```{r plot, echo=FALSE}
    library(ggplot2)
    ggplot(cars, aes(x = speed, y = dist)) + geom_point()
    ```

Attempting to render this with `rmarkdown::render()` produces verbatim HTML for the generated image:

![screen shot 2016-11-01 at 4 06 02 pm](https://cloud.githubusercontent.com/assets/1976582/19910875/21f76894-a04d-11e6-931d-710e22e72e88.png)

The issue does not present itself if no whitespace is present between the two chunks.

**Comment by yihui** [comment]
Yeah there has to be a blank line between the table and plot, otherwise Pandoc does not know where the table ends in Markdown:

    # Hello World
    
    
             speed           dist      
    ---  -------------  ---------------
         Min.   : 4.0   Min.   :  2.00 
         1st Qu.:12.0   1st Qu.: 26.00 
         Median :15.0   Median : 36.00 
         Mean   :15.4   Mean   : 42.98 
         3rd Qu.:19.0   3rd Qu.: 56.00 
         Max.   :25.0   Max.   :120.00 
    ![](test_files/figure-html/plot-1.png)
