### ISSUE TITLE
adding spongedown/svgbob diagrams

### ISSUE THREAD

**Issue by bquast** [rstudio/rmarkdown#854]
it might be interesting to spongedown or svgbob

https://github.com/ivanceras/spongedown

https://github.com/ivanceras/svgbobrus

SvgBobRus is an ascii to svg converter.

**Comment by yihui** [comment]
Thanks for the suggestion, but I don't think this will be implemented in the rmarkdown package. Either knitr (as a new a language engine) or a standalone package may be a better way to go.
