### ISSUE TITLE
Cannot plot neuralnetwork

### ISSUE THREAD

**Issue by mdeang** [rstudio/rmarkdown#856]
I'm a beginner with rmwarkdown and when I try to plot a simple neuralnetwork like this ( two lines of my Rmd file )

my_neuralnet<-neuralnet(output~input, my_train,hidden=2, threshold=0.01)
plot(my_neuralnet)

I have no plot.
I tried to plot in the same file something like "plot(iris)" and the plot runs correctly.

Thanks in advance for response
Mino

**Comment by yihui** [comment]
Not reproducible to me. Could you provide a minimal, self-contained, and reproducible example? Please also include your session info:

```r
devtools::session_info('rmarkdown')
```

Below is mine:

    ---
    title: "Neural Networks"
    output: html_document
    ---
    
    ```{r}
    library(neuralnet)
    XOR <- c(0,1,1,0)
    xor.data <- data.frame(expand.grid(c(0,1), c(0,1)), XOR)
    net.xor <- neuralnet( XOR~Var1+Var2, xor.data, hidden=2, rep=5)
    plot(net.xor, rep="best")
    ```
    
![image](https://cloud.githubusercontent.com/assets/163582/20047687/267902b4-a47c-11e6-972f-6a70fcec3d3f.png)

**Comment by mdeang** [comment]
Thanks 
solved using 
plot(my_neuralnetwork, rep = "best")
