### ISSUE TITLE
R markdown pdf output figure with out.width generating the wrong path with the render function and output_dir used

### ISSUE THREAD

**Issue by Courvoisier13** [rstudio/rmarkdown#861]
Hi,
I am generating a pdf from an Rmd file with output = pdf and xelatex. Some figures are large and cover the entire page. So the generated pdf creates an empty page. To avoid that I decided to reduce the size of the figure using out.width='90%'.

Here is my .Rmd file:

```
> ---
> title: "test out width"
> author: "Courvoisier"
> date: "8 November 2016"
> output:
>   pdf_document:
>     fig_height: 8
>     fig_width: 12
>     keep_tex: yes
>     latex_engine: xelatex
>     number_sections: yes
>     toc: yes
> ---
> ```{r setup, include=FALSE}
> knitr::opts_chunk$set(echo = TRUE)
> ```
> ## Including Plots
> ```{r pressure, echo=FALSE}
> plot(pressure)
> ```
> ```{r pressure2, echo=FALSE, out.width='90%'}
> plot(pressure)
> ```
```

I used render to create the pdf. Here is the .R code:

```
rm(list = ls())
library(knitr)
library(rmarkdown)

RmdFile = "testoutwidth.Rmd"
outputpdfFilePathoutPdf = "testoutwidth.pdf"
renderoutputpdfFilePath = render(input = RmdFile, output_file = outputpdfFilePathoutPdf)
```
This works fine and creates the following .TeX code for the figures:

```
\includegraphics{testoutwidth_files/figure-latex/pressure-1.pdf}

\includegraphics[width=0.9\linewidth]{testoutwidth_files/figure-latex/pressure2-1}
```
However, when choosing an output_dir in the render function such as:

`renderoutputpdfFilePath = render(input = RmdFile, output_dir = "out pdf/", output_file = outputpdfFilePathoutPdf)`
The includegraphics commands in the .TeX generated become

```
\includegraphics{C:/work/testRenderRmd/out pdf/testoutwidth_files/figure-latex/pressure-1.pdf}

\includegraphics[width=0.9\linewidth]{C:\work\testRenderRmd\out pdf\testoutwidth_files/figure-latex/pressure2-1}
```
In the second \includegraphics (the one that has [width=0.9\linewidth]) the path separators are "\\" instead of "/" and so the latex compilation fails. (it gives C:\work... instead of C:/work/... ).

What should I use to solve this?

thanks

**Comment by yihui** [comment]
Usually I don't recommend using `output_dir` or `output_file`. They are known to be problemtic, e.g. https://github.com/rstudio/rmarkdown/issues/587#issuecomment-168437646 #238 #348 #574 etc. I believe the only reliable strategy is to render everything in the current directory, and move the output files later.
