### ISSUE TITLE
Enhancement Request: Allow for Themes in RNotebooks

### ISSUE THREAD

**Issue by digital-dharma** [rstudio/rmarkdown#864]
**Background**
The fantastic [RNotebooks](http://rmarkdown.rstudio.com/r_notebooks.html) functionality automatically creates a .html file from an RMarkdown document.  This HTML file can be shared with R programmers and non R-programmers alike, and include both raw code as well as an general narrative around the analysis being performed.

@yihui 's [site](http://statr.me/2016/08/creating-pretty-documents-with-the-prettydoc-package/) describes how RMarkdown can be augmented to produce documents with an aesthetically pleasing theme.

**Problem**
It does not appear that RNotesbooks support this usage of themes.

**Request**
RNotebooks provide a tremendous methodology for dissemination of analytics.  Ensuring they support themes in the generation of HTML output would be a fantastic addition.

**Comment by yihui** [comment]
Just a minor correction: that was not my site, but @yixuan's :)

**Comment by jjallaire** [comment]
You can use the "theme" option as described by @yixuan in his post.

He goes on to describe how to create a more lightweight document that's
still attractive. If your goal is lightweight though then html_notebook is
anything but that (as it includes all code and output).

Hopefully what you are looking for is taken care of by the "theme" option
(most of the bootswatch themes are supported: https://bootswatch.com/)

**Comment by yixuan** [comment]
Yeah, `prettydoc::html_pretty` is a special version of `rmarkdown::html_document` to produce lightweight HTML. If you want to use `html_notebook` then you should look at the `theme` option provided by `html_notebook` as JJ suggested.

**Comment by digital-dharma** [comment]
Thanks @jjallaire @yixuan for the rapid response.  I may be misunderstanding what is possible.

In your site, you provide the following YAML header:

```
---
title: Nineteen Years Later
author: Harry Potter
date: July 31, 2016
output:
  rmarkdown::html_document:
    theme: lumen
---

```

If I create a RNotebook with this header however, it seems to consider itself a Knitr document and the 'Preview Notebook' button disappears.

Essentially, what I am looking for is a way to ensure that the HTML generated automatically by RNotebooks respects whatever theme is provided in the header (And the bootswatch themes described on the site are great).

Is this possible?

**Comment by yixuan** [comment]
Oh I see. Look at this line:

`rmarkdown::html_document:`

This is why the preview button disappears. You should change it to 

```
---
title: Nineteen Years Later
author: Harry Potter
date: July 31, 2016
output:
  html_notebook:
    theme: lumen
---
```

But remember that the options of the `theme` parameter should take from

- default
- cerulean
- journal
- flatly
- readable
- spacelab
- united
- cosmo
- lumen
- paper
- sandstone
- simplex
- yeti

Themes provided by the `prettydoc` package have not yet been supported.

**Comment by digital-dharma** [comment]
@yixuan - You nailed it, that was the problem.  Thanks to everyone for all their help!
