### ISSUE TITLE
Using rmarkdown::render fails to prompt for params when called from Rscript 

### ISSUE THREAD

**Issue by malcook** [rstudio/rmarkdown#865]
The following fails to prompt for Rmd parameters in a Shiny app

```
 Rscript -e "library(rmarkdown);render('test.Rmd',params='ask')"
```
instead, it fails with:

```Error in knit_params_get(input_lines, params) : 
render parameter configuration only allowed in an interactive environment
```

which is explicitly raised [in params.R](https://github.com/rstudio/rmarkdown/blob/395d2a39b0cd3b3220ba5ab53bcb47302f9c7cae/R/params.R#L15-L16) testing that `interactive() == FALSE` 

However, by following [this hack](http://stackoverflow.com/questions/17328172/forcing-interactive-r-session) it is possible to "trick" R into thinking it is running interactive, as follows:

```
 Rscript -e "unlockBinding('interactive',as.environment('package:base'));assign('interactive',function() TRUE,envir=as.environment('package:base'));library(rmarkdown);render('test.Rmd',params='ask')"
```

In which case the Shiny app pops up and everything works.

I wonder if this test is really required in params.R.  I would like to be able to render rmarkdown files from the command line like this without requiring this workaround.  Am I misguided in my efforts?

The same question was posted on StackOverflow: http://stackoverflow.com/q/40517733/559676

**Comment by yihui** [comment]
I think this is a good question. I would check add the condition `missing(params)` before `identical(params, "ask")`, i.e. if the user explicitly asked for `params = 'ask'`, just pop up the Shiny app no matter if it is an interactive R session or not, otherwise `stop()` in a non-interactive session.

**Comment by jjallaire** [comment]
@yihui agreed, changed here: https://github.com/rstudio/rmarkdown/commit/d197a8c155d891915e43247dc328791bd5d31601
