### ISSUE TITLE
Embedding non-local image causes Error: pandoc document conversion failed with error 139

### ISSUE THREAD

**Issue by lstmemery** [rstudio/rmarkdown#867]
When I knit the following RMarkdown:

```
---
title: "R Notebook"
output: github_notebook
---

<img src="https://upload.wikimedia.org/wikipedia/commons/9/97/Leonard_Cohen_2008.jpg">
```

First I see:

```
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS rmarkdown_issue.utf8.md --to markdown_github --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output rmarkdown_issue.md --standalone --template /home/memery/R/x86_64-pc-linux-gnu-library/3.3/rmarkdown/rmarkdown/templates/github_document/resources/default.md 
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS rmarkdown_issue.md --to html --from markdown_github --output rmarkdown_issue.html --standalone --self-contained --highlight-style pygments --template /home/memery/R/x86_64-pc-linux-gnu-library/3.3/rmarkdown/rmarkdown/templates/github_document/resources/preview.html --variable 'github-markdown-css:/home/memery/R/x86_64-pc-linux-gnu-library/3.3/rmarkdown/rmarkdown/templates/github_document/resources/github.css' --email-obfuscation none
```

Then I receive the following error message:

```
Segmentation fault (core dumped)
Error: pandoc document conversion failed with error 139
Execution halted
```

This occurs on github_document and html_document options. pdf_document is fine. I think this has something to with user permissions, but I can't be sure.

Ubuntu 16.10 64-bit.
Rstudio version:  1.0.44 (Just reinstalled)
pandoc 1.17.2

Running pandoc against the file works, which suggests that it has something to do with RStudio/RMarkdown.

Any ideas?

**Comment by jjallaire** [comment]
I'm unable to repro this on Ubuntu 16.04 so it might be something local to your environment.

**Comment by lstmemery** [comment]
An interesting development! I removed the rstudio pandoc from the path (by renaming it pandoc.backup) and the system pandoc works fine. This issue can be closed, if you wish, but there;s something about the RStudio pandoc that is having issues. Is there a way to repair/reinstall the Rstudio pandoc?

**Comment by jjallaire** [comment]
The RStudio pandoc is a static binary (i.e. no external dependencies). We
do this so that we can use a single binary for many, many systems
(including older RedHat and OpenSUSE systems). We generally haven't had any
problems with this, although we did early on have problem with running
pandoc in environments with locale configurations that diverged from what
is normal/customary (see workarounds here:
https://github.com/rstudio/rmarkdown/blob/d4aaf99b6510df18c0e4ea2c546940e805d131b0/R/pandoc.R#L563-L593).
It's possible that your system has some flavor of the same issue.

**Comment by rmcd1024** [comment]
I have the same problem with Ubuntu 16.10, xfce and Rstudio 1.0.136. This document 

```
---
title: "Untitled"
output: html_document
---

<img src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png">
```

renders correctly at the command line:

` r -e 'rmarkdown::render("~/inc/R/rstudio_pandoc_crash.Rmd")'`

 but throws an error 139 when compiled within rstudio.

Both rstudio and system versions of pandoc are 1.17.2.

I'm unclear about the locale issue, but I have
```
$ echo $LC_ALL
en_US.UTF-8
```

For the record, the error is

```
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS rstudio_pandoc_bug.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output rstudio_pandoc_bug.html --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/rmcd/R/x86_64-pc-linux-gnu-library/3.3/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --variable 'theme:bootstrap' --include-in-header /tmp/RtmpGBbusF/rmarkdown-str5da91b79dd24.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
Segmentation fault (core dumped)
Error: pandoc document conversion failed with error 139
Execution halted
```

Thanks!

**Comment by lbusett** [comment]
Same here (Ubuntu 16.10 Rstudio 1.0.136, R3.3.1):

```
Segmentation fault (core dumped)
Error: pandoc document conversion failed with error 139
Execution halted
```

**Comment by 1beb** [comment]
Getting this now myself. I suspect it's a "switching locale" problem. I have corworkers in LATAM but I'm running their code under UTF CA

**Comment by 1beb** [comment]
A quick update here. 

I found that this error occured when the external image was not available. So you might want to check your links!

**Comment by rmcd1024** [comment]
The test is to compile from the command line. In my case the program compiled correctly from the command line but not from within RStudio, so it's got something to do with RStudio and perhaps with its version of pandoc.

Whether or not the external image is available, a segfault seems like a bug. Here is what command line R/Pandoc does if the image is not available:

```
pandoc: Could not fetch https://i.creativecommons.xorg/l/by-sa/4.0/88x31.png
HttpExceptionRequest Request {
  host                 = "i.creativecommons.xorg"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/l/by-sa/4.0/88x31.png"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure getAddrInfo: does not exist (Name or service not known))
Error: pandoc document conversion failed with error 67
```

**Comment by pauljohn32** [comment]
On Ubuntu 17.04, I upgraded from Rstudio 0.99.903 to 1.0.143 and same 139 pandoc error started to occur. From command line, document compiles fine, with style and images.  Within Rstudio, seg fault.  Then I went to the Rstudio install directory and "sudo mv pandoc pandoc.orig".  After that, the 139 error is solved. I have tested by re-installing Rstudio 0.99.903 and the pandoc seg fault is eliminated.  Definitely appears there is something wrong in the Linux pandoc wrapped into newer Rstudio versions.

**Comment by jjallaire** [comment]
@jmcphers I realize that in v1.1 we will start producing a Xenial build with the pandoc binary built by the upstream, but this issue may also warrant a patch release for v1.0 as I don't think we want to leave pandoc broken in 16.10 and 17.04 for long. 

We could do this pretty easily by just adding the most up to date pandoc debian binary to our global pandoc binary zip file then using the `PANDOC_EXTENSION_DIR` variable along with some platform detection in CMake to install the correct binary. Here's how we do it for ensuring that the pandoc static binary is used on SLES (which would otherwise use the RHEL5 binary): https://github.com/rstudio/rstudio/blob/3bd734f3a4cf995a5a8d0cc3686ff28557a9e3cb/src/cpp/session/CMakeLists.txt#L455-L459

**Comment by jmcphers** [comment]
Thanks, I've filed a case with your remarks (and our earlier conversation on this matter with Dirk).

**Comment by MilesMcBain** [comment]
Just experienced this on a fresh install of Ubuntu 16.10. Spelling out the workaround for anyone else that winds up here:
`sudo apt-get install pandoc`
`sudo rm -R /usr/lib/rstudio/bin/pandoc`
should get you out of trouble while we wait for a better fix.

**Comment by lbusett** [comment]
@MilesMcBain workaround worked for me. Thanks !

**Comment by NamLQ** [comment]
It also works for me, thanks @MilesMcBain

**Comment by ibarraespinosa** [comment]
Also worked for me @MilesMcBain Thanks

**Comment by mpadge** [comment]
Problem may still arise even with solution of @MilesMcBain. An alternative work-around is to explicitly run the steps of
1. `render` to `md` with `clean = FALSE` to keep the intermediate `.utf8.md` file;
2. `render` that file to `html`.

```
rmarkdown::render("myfile.Rmd",
                  output_format=rmarkdown::md_document(),
                  clean = FALSE)
rmarkdown::render("myfile.utf8.md",
                                   output_format=rmarkdown::html_document(
                                                             # ... html options
                                  )   )

```

**Comment by thumdugger** [comment]
Just ran into this issue myself in my rstudio-server-git environment on Archlinux.

However, the problem appears related to quoting.  Following test proposed by @rmcd1024  was successful via the command line:
```
R -e 'rmarkdown::render("path-to-project-directory/R/stack.R",  encoding = "UTF-8", output_format = "html_document")'
```
However, further testing showed that switching the quotes, on the command line, failed:
```
R -e "rmarkdown::render('path-to-project-directory/R/stack.R',  encoding = 'UTF-8', output_format = 'html_document')"
```
This leads me to believe that there is something not playing nicely with single quoting the render options.
