### ISSUE TITLE
Errors When Installing TeX Packages For Knitting PDF In RMarkdown

### ISSUE THREAD

**Issue by risepj** [rstudio/rmarkdown#870]
I am currently attempting to knit a PDF using RMarkdown, but there are TeX packages (upquote, url, and microtype) needing to be installed in order for me to do so.

I’ve been attempting to install these packages using MiKTeX Package Manager; there is a normal version and an administrator version on my machine. I tried installing the packages using a remote package repository, but I was getting an “Unknown MiKTeX exception” error message using both the regular package manager and the administrator package manager (I recruited the help of the IT person in my building). This led me to download the package files through CTAN and attempt install the packages using local package repositories (one for each package). Based on this StackExchange post (http://tex.stackexchange.com/questions/2063/how-can-i-manually-install-a-package-on-miktex-windows), I also included two .tar files in each repository.

When I tried to perform the installation, I selected the local package repository for one of the packages and attempted to run the installation, but the process stopped immediately because a file or multiple files were missing. When I clicked on the package name in the package manager and selected “Properties,” there was a “Files” tab on which I saw a list of files that I believe are required for installing the package. I did this for all three packages, and for each one, the list of files from CTAN differed from the list on MiKTeK. Here are the files that I have in my repositories (based on what I found on CTAN) and the files required by MiKTeK Package Manager:

upquote (files in my local package repository):
•upquote.sty
•README
•upquote.pdf
•upquote.ins
•upquote.dtx
•miktex-zzdb1-2.9.tar
•miktex-zzdb2-2.9.tar

upquote (files required by MiKTeK Package Manager):
•upquote.sty
•upquote.tpm
•README
•upquote.pdf
•upquote-scr.tar.bz2

url (files in my local package repository):
•miscdoc.sty
•url.sty
•url.pdf
•url.texs
•miktex-zzdb1-2.9.tar
•miktex-zzdb2-2.9.tar

url (files required by MiKTeK Package Manager):
•miscdoc.sty
•url.sty
•url.tpm
•url.pdf
•url-src.tar.bz2

microtype (files in my local package repository):
•microtype.dtx
•microtype.ins
•microtype.pdf
•microtype-utf.dtx
•miscdoc.sty
•README.md
•miktex-zzdb1-2.9.tar
•miktex-zzdb2-2.9.tar

microtype (files required by MiKTeK Package Manager):
•(31 files)

A .tpm file seems to be some sort of temporary file, but I don’t know how to create it. I also do not know what the bz2 files are. I am missing so many files associated with the microtype installation that I do not know how I can possibly get that one working.

I looked up the function of each of these packages, and I don’t think I’ve ever made use of them in RMarkdown. If I can’t get the packages installed, I would be fine without them if there were a way to tell RMarkdown/TeX that I don’t want to require those packages. Is there a way to do this? If not, do you have any suggestions for getting the packages installed?

Software Versions:
•RMarkdown: Version 3.3.1
•RStudio: Version 0.99.903+
•MiKTex Package Manager: Version 2.9.5700
•TeXworks: Version 0.4.6

According to the RStudio, I’m attempting to “Typeset LaTeX into PDF using: pdfLaTeX”

Please let me know if there is any other information you need me to provide. Thank you in advance for your help!

**Comment by yihui** [comment]
You can probably try the portable version of MikTeX instead: http://miktex.org/portable It does not require system admin privilege but you will have to modify your environment variable `PATH` (add the bin path of MikTeX) so that other programs can find executables like `pdflatex`.
