### ISSUE TITLE
fluidPage() breaks the document theme, in Shiny v0.14+

### ISSUE THREAD

**Issue by vkapartzianis** [rstudio/rmarkdown#872]
Minimal example:

    ---
    title: "Test"
    runtime: shiny
    output: 
      html_document:
        theme: paper
    ---

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  
    ```{r}
    fluidPage()
    ```

Output:

![image](https://cloud.githubusercontent.com/assets/1918344/20346000/796e04a0-ac02-11e6-9a3f-1dda24b48067.png)

Commenting out `fluidPage()` gives the expected result:

![image](https://cloud.githubusercontent.com/assets/1918344/20346045/b267d90c-ac02-11e6-8362-829745ff5262.png)

Note that this only happens with Shiny v0.14+ and I'm not sure if it's really an rmarkdown problem therefore.

**Comment by jjallaire** [comment]
`fluidPage()` is a Shiny-only construct (note that R Markdown documents are *already* bootstrap fluid pages).
