### ISSUE TITLE
YAML argument fontsize ignored

### ISSUE THREAD

**Issue by guiastrennec** [rstudio/rmarkdown#878]
Hi,

I have been trying to change the font size in a PDF report written in Rmarkdown but in vain. I am not sure whether this issue is related to [this one from last year](https://github.com/rstudio/rmarkdown/issues/513).

Here is a reproducible example of Rmd file:
```
---
title: Foo
fontsize: 20pt
output: 
  pdf_document: 
    latex_engine: xelatex
---

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
```

My `sessionInfo()`:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_1.5    assertthat_0.1  htmltools_0.3.5 tools_3.3.2     yaml_2.1.14     tibble_1.2      Rcpp_0.12.8     stringi_1.1.2   rmarkdown_1.1  
[10] knitr_1.15      stringr_1.1.0   digest_0.6.10   evaluate_0.10  
```
Thanks

**Comment by yihui** [comment]
You are not alone. This is one of the most confusing things in LaTeX: http://tex.stackexchange.com/q/5339/9128 Basically you can only use 10pt, 11pt, or 12pt, unless you use other packages.

**Comment by guiastrennec** [comment]
Thank you very much for your answer, I never paid attention to this detail in LaTeX. 

For future reference, I used the following YAML header which gives the expected result:
```
---
title: Foo
output: 
  pdf_document: 
    latex_engine: xelatex
header-includes:
- \usepackage[fontsize=20pt]{scrextend}
---
```
