### ISSUE TITLE
Rmd file not processed at all for certain types of errors in the R code

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/rmarkdown#88]
This could be by design and for good reasons, but worth mentioning:

My Rmd file (based on the template) has  few sections of R code, and a section towards the bottom has a wrong file path passed to shinyAppDir. When I Run Document, the output is just:

'path[1]="": No such file or directory'

This only happens for certain type of errors. Many of the internal Shiny errors only cause that portion of document to be affected.

This seems inconsistent.

**Comment by yihui** [comment]
The error message seems to be clear in the current version of rmarkdown:

![image](https://user-images.githubusercontent.com/163582/29895580-3a1f3f2e-8d9f-11e7-8a00-3e3b4fc308c1.png)

So I'm closing this issue.
