### ISSUE TITLE
Unicode variable names in Javascript are not preserved when self_contained = true

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/rmarkdown#881]
I often have self_contained = TRUE for documents I need to upload to Rpubs.
Recently I found that if a javascript is using unicode characters for variable names, then these variable names are not encoded properly when the JS is base64 encoded in the final HTML.

Here's an example of a Javascript 
https://github.com/henrythasler/Leaflet.Geodesic/blob/master/Leaflet.Geodesic.js#L229

And here's a Rpubs page which uses that file
http://rpubs.com/bhaskarvk/geodesic

Here's the jumbled up code when inspected in chrome dev tools

![Imgur](http://i.imgur.com/ARhSfpb.png)

And here's the correct unicode chars

![Imgur](http://i.imgur.com/ozQN4NS.png)

**Comment by jjallaire** [comment]
This is very likely an issue with pandoc base64 encoding (I recall a while
back that people needed to use minified d3.js to avoid a UTF-8 pi character
that was in plain d3.js.

**Comment by bhaskarvk** [comment]
Found ramnathv/htmlwidgets#56, and the upstream issue in pandoc jgm/pandoc#1842, though it seems pandoc fixed this issue back in '14.
For now using a minified JS fixed my problem, but it might be worth investigating why the problem persists after pandoc claiming to have fixed it.
