### ISSUE TITLE
Using darkly theme

### ISSUE THREAD

**Issue by mghassany** [rstudio/rmarkdown#889]
I like dark themes. I would like to output the html_notebook i am creating using darkly theme from bosstwatch. 
I downloaded the css and putted theme to null and css to darkly.css but it isn't working. (i got this error : You must use a theme when specifying the 'code_folding' option.

**Comment by jjallaire** [comment]
Yes, currently html_notebook output requires an explicit theme. The
solution here would be to add more of the dark bootswatch themes to
rmarkdown. This is relatively straightforward however also typically
requires some font-embedding work (e.g. see
https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/h/bootstrap-3.3.5/css/flatly.min.css#L1-L18
)

**Comment by mghassany** [comment]
Thank you for you answer.
I will be happy when dark themes are added to rmarkdown.

**Comment by norcalbiostat** [comment]
I'll add my +1 to this request. Not just for the dark themes, but in general adding more bootswatch themes.

**Comment by MBarrows20** [comment]
I too am hoping to see dark themes come to RMarkdown. The light themes are so jarring against my all dark everything, especially at night!

**Comment by lubindent** [comment]
+1

**Comment by askrht** [comment]
darkly +1

**Comment by rich-iannone** [comment]
The darkly theme has been added in #1409
