### ISSUE TITLE
html_notebook stops previewing when calling a line from dataset

### ISSUE THREAD

**Issue by mghassany** [rstudio/rmarkdown#890]
when i call a line to show an example from my dataset the html_notebook stops compiling. (like if i insert `data[1,]` in a chunk). 
two files are shown in the same directory, one terminating by .utf8.md and one terminating by .knit.md when i get this bug.

**Comment by jjallaire** [comment]
@kevinushey Could you take a look at this. @mghassany Could you provide us with a simple Rmd with a minimal reproducible example of what you are seeing?

**Comment by mghassany** [comment]
Here is an example. I got the same bug with this Rmd example which i names test.Rmd
When i run `data[1,]` i see the result in the editor but can't save the file or preview it.
Here is a screen capture of the files produced i talked about in this case (note the file size ! i think when i call `data[1,]` it charges the whole dataset into the html so when my dataset is big the problem occurs) :

![snapshot12](https://cloud.githubusercontent.com/assets/11962615/20669096/8ec4add0-b572-11e6-8845-1ba8401bbfe3.png)


---
title: "Test"
output:
  html_notebook:
    theme: flatly
    toc: yes
    toc_float: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warnings = FALSE)
knitr::opts_chunk$set(message  = FALSE)
knitr::opts_chunk$set(comment=NA)
require(data.table)

```

# Traitement de données

## Joaillerie

```{r}
data <- read.csv("../clusters_gt20.csv",sep=",",fileEncoding = "UTF-8",header=T)
data <- data.table(data)
```


Dimensions : 

 observations | variables 
 ------------- | -------------
 `r nrow(data)` | `r ncol(data)` 


```{r}
data$story <- as.factor(as.vector(data$story))
```


```{r}
data[1,]
```

**Comment by kevinushey** [comment]
Can you please let us know the output of `utils::sessionInfo()` as well? What operating system / version of R / version of RStudio?
