### ISSUE TITLE
Google search result "snippet" is being pulled from disqus

### ISSUE THREAD

**Issue by clayzermk1** [rstudio/rmarkdown#893]
## What happened?
I Googled "rstudio rmarkdown" and the snippet for the search result was a complaint from a disqus thread.

## What did you expect to happen?
I expected to see a typical product summary or relevant text from the page.

## Evidence
Google search
![google_search](https://cloud.githubusercontent.com/assets/1075015/20690951/82203f80-b582-11e6-9a6c-def45e3ee1a1.png)

Source of snippet text in page source
![comment_source](https://cloud.githubusercontent.com/assets/1075015/20690952/8223fa80-b582-11e6-93e3-630d4e3be944.png)

## Possible Solutions
It looks like there are several options available, including excluding the disqus `<script>` tags from being considered for snippets entirely. https://support.google.com/gsa/answer/2672315?hl=en

Maybe simply moving the `<script>` tags to the end of the body would be enough to trick the algorithm.

Cheers!

**Comment by jjallaire** [comment]
@clayzermk1 I implemented all of the suggested solutions including moving the disqus script to the bottom, enclosing it in a noindex directive, and adding a `description` meta tag. Take a look at my change to make sure this corresponds to how you think things should be done.

**Comment by clayzermk1** [comment]
@jjallaire I think it looks good except for the comment tags themselves. If I'm reading the docs right, I think they should be either `<!--googleoff: snippet-->` or `<!--googleoff: all-->` depending on your personal preference. Other than that, :shipit:

**Comment by jjallaire** [comment]
Thanks, just updated to use 'all'
