### ISSUE TITLE
Bold and italic fonts not displayed in ioslides presentation

### ISSUE THREAD

**Issue by glimmerphoenix** [rstudio/rmarkdown#894]
Hello.

I suspect this is some kind of regression bug, since it happened before.

**Bold and italic fonts are not displayed properly in ioslides presentations**. Below I provide a minimal example to reproduce the problem. It happens on both Linux (Linux Mint 18) or Windows 7. It occurs on the internal browser in RStudio, on Google Chrome (54.0.2840.100 (64-bit)) or Mozilla Firefox (50.0).

An inspection of the intermediate .md file reveals that the words are correctly tagged with markdown syntax. Then, the HTML output file shows ```<em> </em>``` and ```<strong> </strong>``` tags in the correct position.

Placing the italics or bold text inside or outside itemized lists does not make any difference. However, using a customized ```font-style``` and ```font-weight``` via ```<span> </span>``` tags the text is displayed correctly. All I can think about is some kind of issue related to the style definition in ioslides.

Thanks in advance.

<pre>
---
title: "Example problem"
author: "Felipe Ortega"
date: "November 30, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

When you click the **Knit** button a *document* will be generated that includes both content as well as the output of any embedded R code chunks within the document.

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3
</pre>

**Comment by jjallaire** [comment]
I think this is a regression in rmarkdown v1.2 (latest CRAN version). Try
installing from GitHub to see if the issue is fixed there (it should be).

**Comment by glimmerphoenix** [comment]
Thanks @jjallaire, you are right! I confirm that version 1.2.9000 from GitHub fixes the issue.

I don't know how much time it will take to publish a fixed version on CRAN, but right now this is a very basic feature that is broken in the public package that 90% of users (or more) will use.

**Comment by jjallaire** [comment]
It will be another 3 weeks before the fix can go to CRAN (we can only
submit every 4 weeks).
