### ISSUE TITLE
asis handling inconsistancies

### ISSUE THREAD

**Issue by spgarbet** [rstudio/rmarkdown#895]
It may be my misunderstanding of the purpose of 'asis' chunks, but I've had trouble with it. I've attacked an Rmd file that shows my issues.
[asis.zip](https://github.com/rstudio/rmarkdown/files/622510/asis.zip)

**Comment by yihui** [comment]
I think this is a known issue but we have not found out the reason, which could be very deep somewhere in base R: https://github.com/hadley/evaluate/issues/59 https://github.com/hadley/evaluate/issues/66

Instead of `results='asis'`, you can probably replace `cat()` with `knitr::asis_output()`.
