### ISSUE TITLE
include html while keeping highlight

### ISSUE THREAD

**Issue by aaa34169** [rstudio/rmarkdown#900]
Hi

in a Rmd, i add a html snippets

```
<!--html_preserve-->
<section class="wrapper style1">
	<div class="container">
		<div class="row 200%">
			<section class="4u 12u(narrower)">
				<div class="box highlight">
					<i class="icon major fa-paper-plane"></i>
					<h3>Installation</h3>
					<p>Guildeline and requirement for Installation</p>
				</div>
			</section>
		</div>
	</div>
</section>
<!--/html_preserve-->
```

is there another wat that html_preserve ?
When i do that the code is not hightlight, it s not easy readable ! is there a way to do that

last question :
Maybe, i should ask this kind of question in a user forum instead github. is there a user forum anywhere ?

Fabien

**Comment by yihui** [comment]
For your last question, yes, please ask on StackOverflow with at least the tags `r` and `rmarkdown`: https://stackoverflow.com/questions/tagged/rmarkdown
