### ISSUE TITLE
Notebook: order of the plots is not preserved

### ISSUE THREAD

**Issue by lepennec** [rstudio/rmarkdown#902]
Dear all,

I have observed a strange behavior with rmarkdown 1.2 and the lastest RStudio (note that the behavior may be older) : the order of the plots in a chunk is not preserved.

For instance
```{r}
for (k in 1:4) {
  grid::grid.newpage()
  grid::grid.text(sprintf("%i",k))
}
```
does not yields the sequence 1,2,3,4 but a random one.

Yours,

Erwan

**Comment by jjallaire** [comment]
This might have more to do with knitr as that's where the plots are actually generated from. @yihui any idea?

**Comment by yihui** [comment]
I cannot reproduce it. I saw 1, 2, 3, 4 as expected. Could you post your `devtools::session_info('rmarkdown')` and tell us how exactly you compiled the Rmd (command-line in the console or clicked the Knit button)?

**Comment by lepennec** [comment]
I don't have the issue if I compile the Rmd with the "Knit to HTML" button.
I have it if I "Restart R and Run All Chunks":
  - the order within the notebook is not preserved (3 1 2 4)
  - the wrong order is stil there when I click on "Preview"

Erwan

Session info--------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/Paris                

Packages------------------------------------------------------------------------------------
 package    * version date       source        
 backports    1.0.4   2016-10-24 CRAN (R 3.3.1)
 base64enc    0.1.3   2015-07-28 CRAN (R 3.3.0)
 devtools     1.6.1   2014-10-07 CRAN (R 3.1.2)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 evaluate     0.10    2016-10-11 CRAN (R 3.3.1)
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.0)
 jsonlite     1.1     2016-09-14 CRAN (R 3.3.1)
 knitr        1.15.1  2016-11-22 CRAN (R 3.3.2)
 magrittr     1.5     2014-11-22 CRAN (R 3.3.0)
 Rcpp         0.12.8  2016-11-17 CRAN (R 3.3.2)
 rmarkdown  * 1.2     2016-11-21 CRAN (R 3.3.2)
 rprojroot    1.1     2016-10-29 CRAN (R 3.3.1)
 rsconnect    0.6     2016-11-21 CRAN (R 3.3.2)
 rstudioapi   0.6     2016-06-27 CRAN (R 3.3.0)
 stringi      1.1.2   2016-10-01 CRAN (R 3.3.1)
 stringr      1.1.0   2016-08-19 CRAN (R 3.3.1)
 yaml         2.1.14  2016-11-12 CRAN (R 3.3.2)

**Comment by jmcphers** [comment]
@lepennec what version of RStudio are you using? Much of the notebook plot rendering logic is baked into the IDE itself, so it's possible you're encountering an RStudio bug rather than an issue with rmarkdown.

We're preparing a preview release of RStudio which includes fixes for a number of common issues in RStudio 1.0. Would you be willing to see if the problem still happens there?

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by lepennec** [comment]
I am already using the 1.0.136 version... Do you want me to try the non preview version?

Erwan

**Comment by lepennec** [comment]
The issue was already there with 1.0.44 under Linux.

**Comment by DarwinAwardWinner** [comment]
I've been seeing the same issue. The plots for a given chunk always come out in a random order in the notebook interface.

**Comment by kevinushey** [comment]
@DarwinAwardWinner, can you provide a reproducible example? In addition, what version of RStudio + what operating system are you using?

**Comment by kevinushey** [comment]
I was able to reproduce the original issue from the OP with RStudio v1.0.136 as well as the current daily build (v1.1.60) on Ubuntu 14.04, so it looks like there is indeed an issue here.

I'll file an issue on the RStudio side for us to track this; thanks!

**Comment by DarwinAwardWinner** [comment]
Trivial example: https://gist.github.com/DarwinAwardWinner/1a949c5b5bdff205e869e82fea6e16ce

RStudio 1.0.136
Ubuntu 16.04.1 LTS

**Comment by kevinushey** [comment]
Thanks for the reproducible example @DarwinAwardWinner! I reproduced the issue using your example on my side as well; I'll make sure it's added on the associated RStudio ticket.

**Comment by bowenli37** [comment]
This issue still exists in version 1.0.153.

**Comment by Aariq** [comment]
This issue still occurs if a function returns a warning message.  Attached is a reproducible example.
[for loop problem.Rmd.zip](https://github.com/rstudio/rmarkdown/files/1928646/for.loop.problem.Rmd.zip)

**Comment by yihui** [comment]
This is an RStudio IDE issue. Please continue the report at https://github.com/rstudio/rstudio/issues/1795. Thanks!
