### ISSUE TITLE
slidy presentation TOC

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/rmarkdown#905]
Slidy presentations create a dropup TOC in the lower left corner of the browser.
This TOC used to display the slide titles.
Someho9w, this changed, not the TOC has the main title of the full presentation
with slide numbers (in parentheses). 

![2016-12-06_15-50-14](https://cloud.githubusercontent.com/assets/157619/20929843/b6bde66c-bbcb-11e6-9a53-e1dfe0d995e2.png)

Is there a way of getting hee slide titles back in the TOC?

-=-=-=-=-=-=-
---
title: "TOC problem"
author: "Erich Neuwirth"
date: "6 December 2016"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

This is an R Markdown presentation. 

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

**Comment by jjallaire** [comment]
For me I'm still seeing the titles when rendering the "Hello, World" slidy presentation. Could you include a copy of the Rmd you are seeing this behavior with?

**Comment by neuwirthe** [comment]
I am running RStudio 1.1.9 with rmarkdown 1.2.9000 on OSX 10.11.6
File is attached
[presdemo.Rmd.txt](https://github.com/rstudio/rmarkdown/files/638036/presdemo.Rmd.txt)

**Comment by neuwirthe** [comment]
I forgot, R is 3.3.2 CRAN version

**Comment by jjallaire** [comment]
With all the same versions and with running your demo file I still don't see this behavior:

<img width="1099" alt="screen shot 2016-12-08 at 12 02 39 pm" src="https://cloud.githubusercontent.com/assets/104391/21019400/4d72e2c4-bd3e-11e6-91ef-92673c6fbe39.png">

**Comment by neuwirthe** [comment]
Problem solved! I had the homebrew version of pandoc installed and in my path, and  when knitting from the button, this version of pandoc was used. Is there a way of telling RStudio to always using its own version of pandoc instead of a system supplied one?

**Comment by jjallaire** [comment]
Currently we always take the latest version of pandoc installed on the
system.

You could try removing the homebrew pandoc and instead installing the
pandoc binary using their native OS X installer.

**Comment by neuwirthe** [comment]
I simply removed the homebrew version and then things worked,
I will check the OSX version.

**Comment by neuwirthe** [comment]
I am running RStudio 1.1.381 with R 3.4.1 on MacOS 10.12.6
RStudio includes pandoc 1.19.2.1 which seems to be the latest version.
The content popup menu in the left corner of the status bar should dis-lay the titles of the sides
to be able to navigate there, but it only displays the main title (once for each slide).
I had this problem previously when I had the homebrew version of pandoc installed. At that time, RStudio included an earlier version of pandoc and just using the RStudio version (by deleting the homebrew version) solve the problem. Now, since RStudio also has the latest version, the problem surfaced again.

In my case, just creating a new slidy presentation and running the demo appearing immediately shows the problem.

The current RStudio devel build (1.1.383) comes with pandoc 1.19.2.1 and the problems occurs with this version.
The current production version of RStudio (1.0.153) comes with pandoc 1.17.2, and with this version the problem I described does not occur.
Replacing pandoc and pandoc-citeproc in RStudio 1.1.383 with the older version (from RStudio 1.0.153)
(in /Applications/RStudio/Contents/MacOS/pandoc/) makes the problem disappear.

Perhaps somebody else can check this on Linux and Windows.

**Comment by yihui** [comment]
This is a known bug of Pandoc that has been fixed in the dev version of Pandoc (not released): https://github.com/jgm/pandoc/issues/3566

Before the next version of Pandoc is available, your only choice is to use the first-level headings `#` instead of second-level `##` for a correct TOC.

**Comment by neuwirthe** [comment]
Thanks.
The issue of course is the for slide titles in slidy one needs second level headings.

**Comment by jtr13** [comment]
Is there any workaround for this issue? Btw, it only happens in the browser, not the RStudio preview (though I still get weird slide counts like 14/12 since slides without titles are apparently not counted in the slide total.)

**Comment by yihui** [comment]
@jtr13 Your `devtools::session_info('rmarkdown')`? `rmarkdown::pandoc_version()`? A reprex? Did you read my reply above? https://github.com/rstudio/rmarkdown/issues/905#issuecomment-339556672

**Comment by jtr13** [comment]
Apologies, first-level headings work.  (I assumed @neuwirthe 's comment that one needs second level headings was the last word on the topic.) Thank you!

**Comment by yihui** [comment]
@jtr13 My previous reply basically says that you have to either use first-level headings, or install a newer version of Pandoc. The first approach should work. I didn't test the second approach. The problem may or may not have been fixed in the current latest version of Pandoc.

**Comment by jtr13** [comment]
Yes, the first (simple and direct) approach indeed works, and hence I did not try another version of Pandoc either.  Many thanks!

**Comment by yihui** [comment]
@jtr13 Okay, great. Thanks for trying it out!

**Comment by neuwirthe** [comment]
The version available in homebrew on Macs now does the right thing again.
I ha the impression then 1st level  headings only define sections, and 2nd level headings are needed for slides. Am I wrong?

**Comment by yihui** [comment]
Yes, that is a wrong impression. [As I have told different users many times before](https://yihui.name/en/2017/11/thanks-tj-mahr/), you have to read the full Pandoc documentation at least once if you really care about Markdown, otherwise you will just spend your time on guessing, [changing stuff and seeing what happens](https://yihui.name/en/2017/05/when-in-doubt-upgrade/). Specifically, your impression can be corrected by this section in the doc: http://pandoc.org/MANUAL.html#producing-slide-shows-with-pandoc

**Comment by jtr13** [comment]
I think I'll tweet that.

**Comment by yihui** [comment]
@jtr13 Please feel free to. That will be super helpful to me! Thanks!

**Comment by jtr13** [comment]
Done! https://twitter.com/jtrnyc/status/938812242962927616

**Comment by neuwirthe** [comment]
Yihui, you are of course right. The problem is that the template understood as a recipe creates a wrong impression. And since for simple things just using the template was sufficient, people (including me) got it wrong. Essentially, making simple things work without the need to read a formal manual can be helpful.
Nevertheless, I plead guilty.

**Comment by yihui** [comment]
Understood! :)
