### ISSUE TITLE
rmarkdown...pandoc...run around...

### ISSUE THREAD

**Issue by merl-dev** [rstudio/rmarkdown#917]
Would be appreciated if a clear set of instructions were made available for installing and using rmarkdown.  I'm using 

RStudio Version 1.0.44
Microsoft R Open 3.3.1

"Keep getting rmarkdown 1.1 is required but 0.9.6 is available."

Now seems that CRAN repos need to be changed and pandoc needs to be installed, which requires Haskell etc...

How is all this going to affect just about everything else I have installed, particularly when I need all of this  done on a production system?  Is there no simpler install path?

**Comment by akzaidi** [comment]
Which mirror of CRAN are you using? i.e., can you check
`getOption("repos")`
Microsoft R Open uses the checkpoint package by default, which points to a daily snapshot of CRAN. 
You can update your CRAN mirror by running the following

```
r <- getOption("repos")
mran_date <- Sys.Date() - 1
r[["CRAN"]] <- paste0("https://mran.revolutionanalytics.com/snapshot/", mran_date)
options(repos = r)
```

or just use a different CRAN mirror altogether

```
r <- getOption("repos")
r["CRAN"] <- "https://cran.rstudio.com/"
options(repos = r)
```

or change your .Rprofile to automatically pick a different CRAN mirror, see `?Startup` for more details.
