### ISSUE TITLE
grid_table alignment not work

### ISSUE THREAD

**Issue by faridcher** [rstudio/rmarkdown#918]
kniting the following grid_table (with alignment colons) doesn't render properly in rstudio (rmarkdown), although the extension (grid_tables) is enabled by pandoc and work fine with pandoc markdown.

```
+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |  
+==============:+:=============:+:===================+
| Bananas       | $1.34         | * built-in wrapper |
|               |               | * bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | * cures scurvy     |
|               |               | * tasty            |
+---------------+---------------+--------------------+
```

**Comment by rfbressan** [comment]
I'm having basically the same issue trying to render a pdf_document (and html too). Bellow is a minimal example and it's not rendering to a grid table.

    title: "Test grid_table"
    author: "Rafael"
    date: "22 de julho de 2017"
    output: 
      pdf_document:
        md_extensions: +grid_tables
    ---

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```
    +---------------+---------------+--------------------+
    | Fruit         | Price         | Advantages         |
    +===============+===============+====================+
    | Bananas       | $1.34         | - built-in wrapper |
    |               |               | - bright color     |
    +---------------+---------------+--------------------+
    | Oranges       | $2.10         | - cures scurvy     |
    |               |               | - tasty            |
    +---------------+---------------+--------------------+

The call to pandoc from RStudio is this:

> /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS teste.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+grid_tables --output teste.pdf --template /home/rafael/R/i686-pc-linux-gnu-library/3.4/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' 
output file: teste.knit.md


> Output created: teste.pdf

What's going wrong?

**Comment by yihui** [comment]
Could you try the latest versions of rmarkdown and RStudio? I cannot reproduce this issue.

PDF output:

![image](https://user-images.githubusercontent.com/163582/29993150-fe593f22-8f73-11e7-8753-93956b1ef277.png)

HTML output:

![image](https://user-images.githubusercontent.com/163582/29993152-08489488-8f74-11e7-8e44-e8ce2ba62771.png)
