### ISSUE TITLE
file-based inputs don't work in parameterized documents (?)

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rmarkdown#919]
Given a document with the contents:

    ---
    title: "R Notebook"
    output: html_document
    params:
      data:
        input: file
        label: 'Input Dataset:'
        value: data.csv
    ---
    
    ```{r}
    print(params$data)
    file.exists(params$data)
    ```

Attempting to knit with parameters, and providing a path to a file that exists and uploading it, seems to fail to produce a path to an existing file:

![screen shot 2016-12-20 at 11 07 27 am](https://cloud.githubusercontent.com/assets/1976582/21364171/8a29c9a2-c6a4-11e6-8689-1df4c5ec1c22.png)

My best guess -- the temporary file produced in the tmpdir exists only for the duration of the Shiny application's lifetime, and is cleaned up after all is said and done? (Or perhaps I'm misunderstanding something else?)

Associated StackOverflow post: http://stackoverflow.com/questions/36937549/rmarkdown-parameterized-reports-cant-access-data-from-selected-file

**Comment by yihui** [comment]
I'm surprised that nobody has reported this obvious bug before? Anyway, the root reason is that Shiny will clean up uploaded files when a session is ended:
https://github.com/rstudio/shiny/blob/176fe699b92e29edf0d48de167257008b0f69b09/R/shiny.R#L513

To avoid the deletion, either shiny has to provide an option, or we have to backup the file elsewhere, e.g. copy the file to a different `tempfile()` and return the path of the latter:
https://github.com/rstudio/rmarkdown/blob/aa96f64a46c01de59770dab7c55dc72151ded05e/R/params.R#L104

**Comment by sjackman** [comment]
I have encountered this bug as well.

**Comment by yihui** [comment]
@sjackman I'll fix it in the next release.

**Comment by sjackman** [comment]
Thanks, Yihui!

**Comment by yihui** [comment]
A fix has been proposed at #1163. You may test with `devtools::install_github('rstudio/rmarkdown#1163')`.
