### ISSUE TITLE
RStudio: Default directory of fileInput dialog in parameterized reports

### ISSUE THREAD

**Issue by sjackman** [rstudio/rmarkdown#921]
The default directory of `fileInput` in parameterized reports is `~/Documents`. A more useful default directory would be the current working directory.

**Comment by yihui** [comment]
For issues related to the RStudio IDE, please file them to https://community.rstudio.com or https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by sjackman** [comment]
It looks as though this issue has been resolved. The default directory of the dialog is now the current working directory.

**Comment by yihui** [comment]
Good to hear! Time cures everything 😂
