### ISSUE TITLE
RStudio: Set parameters of a parameterized report for interactive use

### ISSUE THREAD

**Issue by sjackman** [rstudio/rmarkdown#922]
A dialog box similar to `Knit with Parameters` that changes the parameters for the current session would be nice to have. Setting the parameter manually using `params$foo <- "bar"` doesn't work because it gets reset to the default value with each ⌘Enter.

**Comment by yihui** [comment]
For issues related to the RStudio IDE, please file them to https://community.rstudio.com or https://github.com/rstudio/rstudio/issues. Thanks!

**Comment by sjackman** [comment]
Moved to https://github.com/rstudio/rmarkdown/issues/922
