### ISSUE TITLE
lack of empty lines below code obscures console output

### ISSUE THREAD

**Issue by Komodovaran** [rstudio/rmarkdown#923]
See video:
https://cl.ly/iX14

If there are no empty lines below your code and you run the chunk, the view will scroll so that your output is _exactly_ out of view.

Not a dealbreaker, but slightly annoying nonetheless if you forget to add an extra line at the bottom.

**Comment by jmcphers** [comment]
This isn't an issue with RMarkdown but rather with RStudio. I've filed it in our bug database over there. Thanks for reporting!
