### ISSUE TITLE
Error: pandoc document conversion failed with error 251 

### ISSUE THREAD

**Issue by cemppa** [rstudio/rmarkdown#927]
I'm not sure, whether this is the right place, but I'm trying to export my mapview in R using built-in mapview-function called mapshot. I get this error message:

**pandoc.exe: Out of memory

Error: pandoc document conversion failed with error 251

In addition: Warning message: running command 'C:/PROGRA~2/Pandoc/pandoc +RTS -K512m -RTS ...**

How do I increase the Pandoc haskell memory size permanently or even temporary in R **without** using a Rmarkdown-file? Is there a handle for this? The function in question is called mapshot, for example mapshot(m, url=paste0(getwd(), "/heatmap.html")).

**Comment by JasonFIN** [comment]
Getting the same error with Pandoc version 1.19.2.1 on Windows 7 64bit, 8GB of RAM and with large(ish) data; with four data frames, each having 260 000 obs in 7 variables (one POSIXct and six numeric), so around 1 million observations in total. I tried exporting a plotly graph to HTML-file from RStudio directly, but this resulted in the mentioned error. The same graph shows up nicely in the RStudio's own viewer, but exporting via Viewer -> Export -> Export as HTML, or via htmlwidgets::saveWidget results in an error.

Then I tried doing the pandoc - command manually from command prompt and adjusting the memory allocation with -K and -M parameters by replacing the "-K512m" with "-K4000m -M4000m" and smaller numbers, but still getting the same error.

My Rtemp folder with the template and data is less than 60MB of size... If I would have to guess, this is related to pandoc.exe's own internal memory handling? When running R, the Rsession takes around 5GB and the Rstudio around 360MB of RAM.

**Comment by yihui** [comment]
Is there a chance that either of you could provide a reproducible example? You can generate random data instead of using your real data. Thanks!

**Comment by TucoFernandes** [comment]
I'm having a similar problem with a heat map of a matrix [300, 300]. That is plotting 90,000 data points only. However, the R session is using only 3GB and still have more than 20GB of free memory. Anyone know a solution for this?

**Comment by BastienFR** [comment]
I've got the same error with `saveWidget` trying to save a leaflet map.  The problem was two things, the shape was too big and the use of the parameter `selfcontained` which worked at `FALSE` but didn't at `TRUE`. If you want to reproduce the error, it can be done by downloading a shapefile from [here](https://github.com/polygraph-cool/smoothing_tutorial/blob/master/us_county_hs_only.zip)  and running this code:

```
library(sf); library(leaflet);library(htmlwidgets); library(rmapshaper)

sh <- st_read("C:/Users/Bastien/Desktop/crap/us_county_hs_only/us_county_hs_only.shp")
sh <- st_transform(sh, '+proj=longlat +datum=WGS84')
object.size(sh)

lf <-leaflet(data=sh) %>% 
        addTiles() %>% 
        addPolylines()

htmlwidgets::saveWidget(lf, "C:/Users/Bastien/Desktop/crap/us_county_hs_only/us_leaflet.html", selfcontained = T)
pandoc.exe: Out of memory
Error: pandoc document conversion failed with error 251
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS C:\Users\Bastien\Desktop\crap\us_county_hs_only\us_leaflet_small.html --from markdown --output C:\Users\Bastien\Desktop\crap\us_county_hs_only\us_leaflet_small.html --self-contained --template C:\Users\Bastien\AppData\Local\Temp\2\RtmpcvKXMR\file2320552c5cba.html' had status 251 
```
Like I said, the error dissapeared by changing  `selfcontained` to `FALSE` or simplifying the shape with `st_simplify` or `rmapshaper::ms_simplify`.  

It's still weird that their is an error even if the job get done anyway...  BTW, I running windows and I have 32 gb or RAM.

**Comment by IndigoJay** [comment]
> Can someone reopen this please? Having the same issues.

I was getting error 251 as well

```
**pandoc.exe: Out of memory
Error: pandoc document conversion failed with error 251
```

I made three changes which helped

1) Turned on "paged" table printing in the header
```
output: 
  html_document:
    df_print: paged
```

2) Removed tabset
Before
`# Chapter 1  {.tabset}`
After
`# Chapter 1 `

3) Strategically inserted " exit knitr block" to narrow down crash area
```{r}
## early exit
knitr::knit_exit()
```

Of the three changes - the removal of **tabset** fixed my pandoc knitting out of memory error 251.

**Comment by timathomas** [comment]
I had a similar issue while making a leaflet map and then saving the html file using `htmlwidgets::saveWidget`. 

My fix was to run the code in terminal. Everything saved.

**Comment by DavorJ** [comment]
> I had a similar issue while making a leaflet map on an RStudio server and trying to save the html file using `htmlwidgets::saveWidget`.
> 
> My fix was to run the code in terminal. Everything saved.

It seems to be a RStudio issue.

Note though that to make selfcontained html files, pandoc is required, and a version is supplied with RStudio. If using R outside of RStudio environment, you need to download pandoc and add it to the R environment path (usually using .Rprofile)

`Sys.setenv(PATH = paste(Sys.getenv("PATH"), "path_to_pandoc", sep=.Platform$path.sep));`

To make sure R can use pandoc:

`rmarkdown::pandoc_available()`

**Comment by cderv** [comment]
Hi everyone, 

Can anyone provide a reproducible example so that we can look into it ? 
Without it, it is very difficult for us to know what is wrong - there could be many levels where an issue occurs, one being a pandoc issue too. 

Please help us help you by providing a reproducible example. Thank you !

**Comment by DavorJ** [comment]
@cderv , since you ask that nicely:

```
n <- 1e7
set.seed(2020)
df <- data.table::data.table(
  TIMESTAMP = as.POSIXct(runif(n, max = as.numeric(as.POSIXct('2020-01-01'))), origin = '1970-01-01'),
  VALUE = rnorm(n),
  GROUP = as.factor(sample.int(8L, n, replace = TRUE)), 
  key = 'TIMESTAMP'
)
df

p <- plotly::plot_ly(data = df, x = ~TIMESTAMP)
p <- plotly::add_trace(p = p, y = ~VALUE, color = ~GROUP, visible = 'legendonly',
                       mode = 'lines+markers', type = 'scattergl',
                       marker = list(size = 4), line = list(width = 1))
#p

htmlwidgets::saveWidget(p, 'plotly_large_output.html')

```

I have this failing in RStudio 1.1.463 (which I have to use since the new version has an unresolved bug).

In the new version 1.3.959 the code completes without any error. So I think everything is OK.

**Comment by atusy** [comment]
@DavorJ 

> In the new version 1.3.959 the code completes without any error. So I think everything is OK.

It indicates the later Pandoc (i.e., 2.7.3) solves the problem, which is bundled by the latest RStudio.
If you use old RStudio because of the bug of itself, and not of old pandoc, then I'd suggest update pandoc (https://bookdown.org/yihui/rmarkdown-cookbook/install-pandoc.html).

**Comment by cderv** [comment]
Thank you @DavorJ ! 

I agree with @atusy. It seems like this could come from pandoc and that one need to update pandoc to use at least 2.7.3, using the information in the link he provided. 
Can you try using a newer version of pandoc and confirm this works for you in the old IDE you need to still keep using ? 

Thank you very much to both of you !

**Comment by DavorJ** [comment]
Note that `rmarkdown::find_pandoc()` doesn't seem to have an effect on `htmlwidgets::saveWidget()` which hijacked this thread at some point.

To make `htmlwidgets` use the latest `pandoc`, replacing `pando.exe` in `rstudio_path\bin\pandoc` works.

So no stress, all is OK for `rmarkdown`!

**Comment by cderv** [comment]
> Note that rmarkdown::find_pandoc() doesn't seem to have an effect on htmlwidgets::saveWidget() which hijacked this thread at some point.

Yes it seems that `htmlwidgets` has its own `find_pandoc` version that does not include the new feature from rmarkdown one.  
So you're right this is an issue for htmlwidgets. Did you open one there yet ?

**Comment by DavorJ** [comment]
No. `htmlwidgets` doesn't explicitly depend on `rmarkdown`. On the other hand, it would be good to have a central setter function for pandoc.

Also there are lots of [old issues](https://github.com/ramnathv/htmlwidgets/issues?q=is%3Aissue+is%3Aopen+savewidget) related to `htmlwidgets::saveWidget()`, some fixed in forks but not pulled. Still maintained?

**Comment by cderv** [comment]
> Also there are lots of old issues related to htmlwidgets::saveWidget(), some fixed in forks but not pulled. Still maintained?

there are recent commits, so I would say yes. You should open a new issue linking to the others if you think it would be clearer to have a new one. I think this thread is no more the right place for this unfortunatly - it won't be seen by htmlwidgets maintainers.
