### ISSUE TITLE
Use output_format with base_format argument only

### ISSUE THREAD

**Issue by alequartz** [rstudio/rmarkdown#928]
I am creating a custom html_document format. using the html_document and **output_format** functions.

This is what I planned to do initially

```
knitr_opts <- knitr_options()
html_document_custom <- html_document()
output_format(knitr = knitr_opts,   base_format = html_document_custom)
```
This will NOT work since output_format requires a pandoc argument.
This means that despite the fact that I have an object, html_document_custom, with all the required goodies, I need to pass it argument by argument:

```
 output_format(
    knitr = knitr_opts,
    pandoc = html_document_custom$pandoc,
    keep_md = html_document_custom$keep_md,
    clean_supporting = html_document_custom$clean_supporting,
    df_print =  html_document_custom$df_print,
    pre_knit = html_document_custom$pre_knit,
    post_knit = html_document_custom$post_knit,
    pre_processor = html_document_custom$pre_processor,
    intermediates_generator = html_document_custom$intermediates_generator,
    post_processor = html_document_custom$post_processor,
    on_exit = html_document_custom$on_exit
  )
```

I think solution is error-prone and I am likely to run into issues if the arguments of output_format change in the future. 

I've also tried to trick the function like this:

```
output_format(knitr = knitr_opts,
              pandoc = html_document_custom$pandoc,
              base_format = html_document_custom)
```

This works, but the side effect is that all the pandoc arguments are duplicated. This has unwanted consequences on your final output. For example all your css will be added TWICE to your html output. 

- Am I using the correct mechanism ?
- If so, Would it be possible modify output_format so that is can run with the base_format argument alone?

Thanks for all the great work !

**Comment by alequartz** [comment]
This works ... but could be considered a hack

```
output_format(knitr = knitr_opts,
              pandoc = NULL,
              base_format = html_document_custom)
```

**Comment by jjallaire** [comment]
You can just set the knitr and pandoc arguments both to NULL.

**Comment by alequartz** [comment]
It works. Thank you.
