### ISSUE TITLE
Missing rgl plots in HTML document when generated from nested Rmd

### ISSUE THREAD

**Issue by rbagd** [rstudio/rmarkdown#930]
I needed to generate 3D plots using nested `Rmd` files and `rgl` and it looks like there's an issue with how `rmarkdown/knitr` interacts with `rgl`. Here's a minimal reproducible example.

`parent.Rmd` contains:
<pre>
---
title: 3D
output:
  html_document
---

```{r 3dplots}
library(rmarkdown)

render("child.Rmd", output_file = "first.html")
render("child.Rmd", output_file = "second.html")
```
</pre>

`child.Rmd` contains:
<pre>
---
title: "3D plots"
---

```{r echo = FALSE, warning = FALSE}
library(rgl)

plot3d(runif(50), runif(50), runif(50), type = "s")
rglwidget(width = 400, height = 800)
```
</pre>

`first.html`, generated by running `rmarkdown::render("parent.Rmd")`, leads to a proper `HTML` with the 3-dimensional plot. However, `second.html` doesn't have the plot of the 3D object (it has the title though). Inspecting `HTML` source show that the `rgl` object is indeed there and that `copyObj()` method failed in `rglwidgetClass` for this second `HTML`.

Here's my session info.
<pre>
## 
## 
## 
## [17] yaml_2.1.14     htmltools_0.3.5 knitr_1.15.1
</pre>

**Comment by yihui** [comment]
I investigated this issue for a while but still haven't got a clue (there seems to be something stateful in `rgl::rglwidget`). I'm afraid we have to ask @dmurdoch for help. Here is the reproducible example I used: [rglwidget.zip](https://github.com/rstudio/rmarkdown/files/1389030/rglwidget.zip)

**Comment by dmurdoch** [comment]
I'm travelling for the next week, but will try to take a look when I'm back
home.

**Comment by dmurdoch** [comment]
This is a case of an optimization in `rgl` that doesn't work in this context.  When the `reuse` argument to `rglwidget()` is `TRUE` (the default), it tells it not to reconstruct objects that already appear in other scenes in the same document.  But it can't tell that you really have two separate documents, so you need to specify `reuse = FALSE` in the second one (or in both, which is easiest with the sample source code).  

To fix the sample, in `test2.Rmd` change the `rglwidget()` call to

    rglwidget(width = 400, height = 800, reuse = FALSE)

and you should get the display in both places.

**Comment by yihui** [comment]
@dmurdoch Indeed that solved the problem. Thanks a lot!
