### ISSUE TITLE
Allow "console display" when sending code from a chunk

### ISSUE THREAD

**Issue by statquant** [rstudio/rmarkdown#931]
Hello, 
When I write a r notebook chunk I can send a single line of the chunk to the console (doing CTRL+MAJ+ENTER), which is very good.
However the result will never be displayed

Example:
```
``{r}
x = 1:9
plot(x) #CTRL+MAJ+ENTER do not produce a graph in the viewer
``
```
or more importantly
```
``{r}
x #CTRL+MAJ+ENTER do not produce show 1...9 in the console, to do it I need to go in the console and retype x
``
```
I understand that the display is supposed to happen in the notebook, but most of the time you want to focus on the data before executing the chunk

Would it be possible to add say CTRL+ALT+ENTER that would display in the console ?

**Comment by statquant** [comment]
@jjallaire is it to draw @jmcphers attention ?

**Comment by jjallaire** [comment]
Yes

**Comment by jmcphers** [comment]
The console is minimized by default when you have a notebook open. If you open it up, you should see that printing content in the notebook prints it in the console too. 

![image](https://cloud.githubusercontent.com/assets/470418/21651017/de48d4ca-d25b-11e6-8dbe-61d0d7e261d8.png)

(If that's not what you're seeing, it's a bug!)

There are also some options which may help you get the behavior you want. If you'd prefer to see the console all the time when working in the notebook, you can turn off "Hide console automatically" in Global Options -> R Markdown:

![image](https://cloud.githubusercontent.com/assets/470418/21651061/1504c29e-d25c-11e6-885f-da6b1fbabba2.png)

And if you'd just prefer the old pre-notebook behavior wherein output always goes to the console/plot pane, you can turn off "Show output inline for all R Markdown documents". 

Does any of that get you the behavior you want?

**Comment by statquant** [comment]
Hello,
I have been trying this at home on `Fedora 25` with `RStudio 1.0.136` (today's stable).
![image](https://cloud.githubusercontent.com/assets/3612473/21658015/b9347174-d2bc-11e6-9b42-930c08fe20e1.png)
I have some unexpected (for me :)) results.

My settings are as follows
![image](https://cloud.githubusercontent.com/assets/3612473/21658475/ba93eca0-d2be-11e6-93c1-d5394182e5da.png)

First for sending a ***single*** line from a chunk to the console I use *CTRL+ENTER*

Using the following notebook:
![image](https://cloud.githubusercontent.com/assets/3612473/21658981/94edbcfe-d2c0-11e6-8809-7899aaea788c.png)

Pressing *CTRL+ENTER* on the line of the first chunk gives me expected result I get
![image](https://cloud.githubusercontent.com/assets/3612473/21659072/f1d349ca-d2c0-11e6-9c80-e0b16fb4449c.png)
And
![image](https://cloud.githubusercontent.com/assets/3612473/21659084/02ebf5f4-d2c1-11e6-88c8-25ba6c7c473d.png)

The second chunk, executing line by line I ***DO*** see `1:9` printed but I ***CANNOT*** have the plot shown on the viewer, it only goes in the notebook

Not in the viewer:
![image](https://cloud.githubusercontent.com/assets/3612473/21658592/202832f6-d2bf-11e6-8a01-00dff0d6910f.png)
But in the notebook:
![image](https://cloud.githubusercontent.com/assets/3612473/21658648/55bec15a-d2bf-11e6-907e-10380c9536ad.png)

And finally  I ***CANNOT*** have the data.frame in the console, I ***CANNOT*** see the graph in the viewer
![image](https://cloud.githubusercontent.com/assets/3612473/21658865/1fedb468-d2c0-11e6-9cc4-837960008016.png)
 the notebook works as expected

What I would like to be able to get is all graphs going in the viewer, and also being able to print the data.frame in the console.
Can you reproduce ?
Am I missing something ?

**Comment by jmcphers** [comment]
Thanks, seeing your prefs and a complete document is very helpful!

For better or worse, this is how `html_notebook` works. When you execute a line in the notebook, it's going to capture its output and put it in the notebook. There is no way to turn that off for the `html_notebook` type.

However, given your preference settings, you should be able to do what you want for other R Markdown document types. For `html_document`, for instance, you should see graphs in the viewer since you have turned off inline output.

Does that do what you want? If not, are you looking for

1. a way to make graphs appear in the viewer and the notebook at the same time, OR
2. a gesture which directs a specific line to be executed outside the notebook context (as though you'd typed it at the console)?

**Comment by statquant** [comment]
Hello,
I do not get individual graphs in the viewer... the only thing I seem to be able to get is the whole html_document rendered (or the html_notebook for that matter).
Can you get a single graph in there ? send from the chunk ?

As to your questions you are right, I would be more encline to say 2. because that would give me the best of both world, notebook behavior and also fully fledged interactivity like if I was writing a normal r script

**Comment by statquant** [comment]
@jmcphers Hello, working on my workstation (Centos7) today I could do what I wanted aka send each line from an html_notebook to be evaluated in the console.
![image](https://cloud.githubusercontent.com/assets/3612473/21671577/46a6fb38-d314-11e6-894d-8a3ce2f50f32.png)
And I did this without altering the default global settings
![image](https://cloud.githubusercontent.com/assets/3612473/21671606/7a4c1464-d314-11e6-9b76-cd6720e1441b.png)

I am not sure what I missed here... :(
Plus this is precisely what you indicate in your 55 min video about notebooks

I'll make sure I can reproduce at home, sorry about this, notebooks options however simple seem to puzzle me...

I'll make sure I can reproduce on

**Comment by malsharifm** [comment]
@jmcphers 
how can I make the first point "a way to make graphs appear in the viewer and the notebook at the same time"

**Comment by jmcphers** [comment]
There's currently no way to do that as it would require the graphs to be rendered multiple times for the differing viewports -- not impossible but pretty tough given the way things work.

**Comment by grobins** [comment]
@statquant Thank you for this! inline plots, tables, and maps were the main reason I don't like using notebooks.  Now they're usable again!
