### ISSUE TITLE
Check if interactive markdown is being run on Shiny Server

### ISSUE THREAD

**Issue by thecomeonman** [rstudio/rmarkdown#933]
I want to write some R markdown templates which the user can choose to either save to the hard disk as an HTML document or run interactively through Shiny Server.

I think I need some way to check which of the modes the Rmd file is being executed through ( rendered to HTML or Shiny Server ) and accordingly decide whether I want the results to be static images, etc. or whether I want interactive Shiny elements.

Is there any way to achieve this?

(Also asked here - http://stackoverflow.com/questions/41437070/check-if-interactive-markdown-is-being-run-on-shiny-server)

**Comment by jjallaire** [comment]
Right now the best way to do this is to ask knitr what the current runtime
is. To check for runtime: shiny you'd use:

identical(knitr::opts_knit$get("rmarkdown.runtime"), "shiny")
