### ISSUE TITLE
Numbered lists disappearing when code added in Markdown

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/rmarkdown#935]
Greetings,

Numbered lists are displaying odd behaviour... the following code demonstrates... the presence of text following the number fixes things but sometimes one does not want any text... adding R code such as below causes 1. and (a) to vanish unless there is text proceeding them?

Latest version of R, RStudio, markdown etc. installed, macOS (latest version). If you run the attached you will get an HTML file (or PDF etc.) with no number 1 nor (a) displaying (at least on my system). Interesting that it previews properly here though...

Thanks!

---
title: "Issue"
---

1.  

    (a)
    
        ````{r}
        1+1
        ```
    
2.

**Comment by kevinushey** [comment]
Unformatted text:

    ---
    title: "Issue"
    ---
    
    
    1.  
    
	(a)
	
	    ````{r}
	    1+1
	    ```
	
    2.

**Comment by kevinushey** [comment]
It looks like the issue is caused specifically by the double-indented R code block, although I'm not sure why.

**Comment by JeffreyRacine** [comment]
Well, related but not sure it is the cause... the following works but remove the word "Test" and it displays the same issue... there are lots of pathologies including the backticks and letter r eventually showing up... placing any text after an item number resolves, so perhaps this will help diagnose?

Thanks!

---
title: "Issue"
---

1. Test

    ```{r}
    1+1
    ```

2.

```{r}
1+1
```

3.

    ```{r}
    1+1
    ```

4.
        ```{r}
        1+1
        ```

**Comment by JeffreyRacine** [comment]
Quick followup to demonstrate how adding text resolves in R Markdown (though oddly the last does not display properly here)...

Thanks!

---
title: "Issue"
---

1. Test

    ```{r}
    1+1
    ```

2. Test

```{r}
1+1
```

3. Test

    ```{r}
    1+1
    ```

4. Test

    (a) Test

        ```{r}
        1+1
        ```

**Comment by JeffreyRacine** [comment]
Followup... adding a zero width space fixes but is tedious (though oddly it displays differently here from R Markdown)...

Hope this helps.

---
title: "Issue"
---
                   
1.

    (a)
                    
        ```{r}
        1+1
        ```
        
2. 

    (a) &#8203;
                    
        ```{r}
        1+1
        ```   
        
3. &#8203;

    (a) &#8203;
                    
        ```{r}
        1+1
        ```
