### ISSUE TITLE
It should be possible to import RMarkdown files

### ISSUE THREAD

**Issue by nathancarter** [rstudio/rmarkdown#936]
A user asks [here](http://stackoverflow.com/questions/10966109/how-to-source-r-markdown-file-like-sourcemyfile-r) a very reasonable thing: to be able to "source" one RMarkdown file from another.  Although the user doesn't state this as the reason, the primary reason that comes to my mind is to be able to write one's entire codebase in the literate style, just like one [Literate Coffeescript](http://www.coffeescript.org#literate) file can import another.

Only one solution is offered, and Yihui [suggests that it is a bad idea](https://github.com/yihui/knitr/pull/812#issuecomment-53088636).  I have tried the solution and found that it works correctly in only simple situations, and more complex situations (such as A importing B importing C) cause errors (in that case, duplicate chunk labels for unnamed chunks).

I suggest that this be officially supported, with a new function for importing other RMarkdown files, due to the elegance and practicality of writing one's whole codebase literately, and having it be self-documenting.

**Comment by yihui** [comment]
I was only discouraging using `purl()`. As the main developer of knitr, I can tell you that I have never felt confident with `purl()`. Its implementation was not solid.

I think child documents will be a much better way to go: https://yihui.name/knitr/demo/child/

**Comment by nathancarter** [comment]
I finally got a chance to try this out recently.  Works great!  Thanks for the pointer.
