### ISSUE TITLE
setting src path to github repo

### ISSUE THREAD

**Issue by yonicd** [rstudio/rmarkdown#939]
I am working on an rmd file that compiles to an html. how can i set the src path to have a prefix to compile all the paths to have the prefix to the github url address

now its compiling to:

```
<script src="DataDrivenCheatsheets_files/jquery-1.11.3/jquery.min.js"></script>
```

would it be possible to set it globally to compile to 

```
<script src="https://raw.githubusercontent.com/metrumresearchgroup/ggedit/master/BlogPosts/Data%20Driven%20Cheatsheets/DataDrivenCheatsheets_files/jquery-1.11.3/jquery.min.js"></script>
```

same with img tags

<a href="https://raw.githubusercontent.com/metrumresearchgroup/ggedit/master/BlogPosts/Data%20Driven%20Cheatsheets/DataDrivenCheatsheets.Rmd" target="_blank">here</a> is the full example

thanks

**Comment by yonicd** [comment]
making this question more focused. there are some src's that can be set to https when setting in the yaml header `html_document:self_contained:false`

from what i found only the htmlwidget src's cant be set to a url src.

what could be the reason for this? is this something that can be fixed?

anyhow i think it would make the self_contained html output a lot smaller if the src was relational to a url where ever possible instead of the script that is currently pasted into it.

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/shim/html5shiv.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/shim/respond.min.js"></script>

<!--- htmlwidget
<script src="DataDrivenCheatsheets2_files/htmlwidgets-0.8/htmlwidgets.js"></script>
--->

<link href="https://raw.githubusercontent.com/cran/plotly/master/inst/htmlwidgets/lib/plotlyjs/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="https://cdn.plot.ly/plotly-1.16.3.min.js"></script>

<!--- htmlwidget
<script src="DataDrivenCheatsheets2_files/plotly-binding-4.5.6/plotly.js"></script>
--->

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="https://raw.githubusercontent.com/metrumresearchgroup/ggedit/master/BlogPosts/Data%20Driven%20Cheatsheets/DataDrivenCheatsheets_files/highlight/default.css"
      type="text/css" />
<script src="https://raw.githubusercontent.com/metrumresearchgroup/ggedit/master/BlogPosts/Data%20Driven%20Cheatsheets/DataDrivenCheatsheets_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>

<!-- tabsets -->
<script src="https://raw.githubusercontent.com/metrumresearchgroup/ggedit/master/BlogPosts/Data%20Driven%20Cheatsheets/DataDrivenCheatsheets_files/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

```

**Comment by yihui** [comment]
For the first question: it depends. If the `src` is in the body of the document, one possible approach is to use an inline variable like `` src="`r PREFIX`/foo/bar.js" ``  and you define `PREFIX`. If `src` is in `<head>`, no, it is not possible.

I think your second question is the same as #794.

For future questions, please do us a favor to [ask them on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with reproducible examples) and let us know the link if you don't get answers in a few days. Thanks!
