### ISSUE TITLE
mac dictionary does not work for rmarkdown documents

### ISSUE THREAD

**Issue by sriramab** [rstudio/rmarkdown#940]
Hi,

I found that when using rmarkdown in rstudio on a mac machine, the inbuilt mac dictionary is not available (using three finger tap or right click lookup). Are there some settings to be changed in rstudio? 

if this feature does not exist, I would like to request this enhancement so that words can be looked up while writing an article or a chapter of a thesis. This will help not only with Rmarkdown but also with the new bookdown package.

Thank you.

**Comment by yihui** [comment]
This is an RStudio IDE issue, so support.rstudio.com is a better place to go. Thanks!
