### ISSUE TITLE
build_site should ignore "packrat" folder by default

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/rmarkdown#946]
Or maybe at least the following: "packrat/src","packrat/lib-R","packrat/lib-ext", "packrat/lib", "packrat/init.R" (the packrat.lock file might be nice to keep).

Otherwise packrat gets confused and tries to tangle .Rmd files in the src files of packages (which takes ages and will add unnecessary dependencies). It ignores them at the root, but not under e.g. _site.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/rmarkdown/commit/3e697649ec430119dabc690111b88c40db288dc8

It's too messy to try to cherry pick the packrat.lock file so I am just ignoring the entire directory.

**Comment by rubenarslan** [comment]
Actually it seems to me that's it's not possible to ignore subdirectories,
but I want to run more tests to be sure.
