### ISSUE TITLE
Feature Request:  Please add keep_md to pdf_document

### ISSUE THREAD

**Issue by billdenney** [rstudio/rmarkdown#949]
Is it feasible to add keep_md to the pdf_document type the same way that it's present for the html_document?  Generally, could it be added to all document types?

**Comment by jjallaire** [comment]
It's very easy to add `keep_md`, however the reason it's currently not there is that this would yield a markdown file with PDF rather than PNG images, and as a result it's not really renderable for the web. Would this still be useful to you even w/ this caveat?

**Comment by billdenney** [comment]
My use case when I wanted it was that I was having problems with rendering complaining of an extra "\n" somewhere.  I wanted to look at the markdown intermediate form to troubleshoot it.  For that, yes, I'd like it.

To confirm my understanding, when rendering a .pdf, the sequence is:  Rmd -> md -> tex -> pdf
Right?

If it doesn't go through an intermediate md file, then my request probably doesn't make sense (as it's not part of the sequence it wouldn't help in troubleshooting).

**Comment by jjallaire** [comment]
For that use case you can actually call `render` with `clean = FALSE` which
will preserve all intermediate files.

I still would rather not add `keep_md` as an option because it will almost
certainly lead to confusion over why the images in the md files don't
render on the web / on GitHub.

**Comment by billdenney** [comment]
The potential confusion is perfectly fair.  Thanks for the pointer of a way to do what I am trying to do.
