### ISSUE TITLE
switch that discerns between types of document outputs

### ISSUE THREAD

**Issue by yonicd** [rstudio/rmarkdown#954]
i want to write within the code a switch that does one thing when the document is defined as an html and another when the document is a pdf.

is there an internal package function that i can use for this?

**Comment by jjallaire** [comment]
We set a bunch of knitr options that you can use for this:

https://github.com/rstudio/rmarkdown/blob/master/R/render.R#L320-L326

I think you'll want the `rmarkdown.pandoc.to` option. There is a bit more processing of this value you need to determine if HTML or PDF is being targeted, you can see that here:

https://github.com/rstudio/rmarkdown/blob/3e8cda482298adc6c11c03dde6c51109f128022a/R/util.R#L13-L34

Yes, this indeed should be a function in either knitr or rmarkdown, sorry it's so messy as it is :-\

**Comment by yonicd** [comment]
so it would be possible to query while its the document is compiling?

**Comment by jjallaire** [comment]
Yes it would

**Comment by yonicd** [comment]
another question along the same thread: 
i cant see in the output of `knitr::opts_knit$get()` a object that saves the name of the input file. is there a way to call that during the compile?

**Comment by jjallaire** [comment]
You can use a pre-knit hook to capture the name of the input file: https://github.com/rstudio/flexdashboard/blob/master/R/flex_dashboard.R#L260-L264

**Comment by yonicd** [comment]
great thanks.

btw you guys may like this extension for rmarkdown we are working on: 

[texPreview](https://github.com/metrumresearchgroup/texPreview/)

[internal viewer example](https://www.youtube.com/watch?v=sXWgdCDhdN4)
[html example](https://www.youtube.com/watch?v=10axkP4u6PI)

**Comment by jjallaire** [comment]
Thanks fantastic!
