### ISSUE TITLE
html_document cant fetch script from URI source

### ISSUE THREAD

**Issue by yonicd** [rstudio/rmarkdown#955]
html_document returns error
 `Could not fetch http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js`

this is the rmd trying to run 

any other html extension output returns same error except for ioslides_presentation, which compiles correctly.

ive tried the google and microsoft URI's

```
---
title: "HTML output that has embeded LaTeX tables"
author: "Jonathan Sidi"
date: "January 31, 2017"
output: html_document
---

```{r setup, echo=FALSE,results='asis'}
suppressMessages(library(texPreview))

rt=knitr::opts_knit$get('rmarkdown.pandoc.to')
fd=NULL 

if(rt%in%c("html", "html5", "s5", "slidy","slideous", "dzslides", "revealjs","md")){
  fd="test_files/texPreview"
  if(!dir.exists(fd)) dir.create(fd,recursive = T)
  
   if(rt%in%c('html')){
     writeLines('<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>')
     writeLines('<script src="zoomImage.js"></script>')
   }
}
```

error message:

```
output file: test.knit.md

pandoc: Could not fetch http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js
HttpExceptionRequest Request {
  host                 = "ajax.aspnetcdn.com"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/ajax/jQuery/jquery-3.1.1.min.js"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
Error: pandoc document conversion failed with error 67
Execution halted
```

**Comment by jjallaire** [comment]
The html_document format already includes jquery so you shouldn't need to do this (and in fact doing this may cause problems as there will end up being 2 copies of jquery active in the document).

**Comment by yonicd** [comment]
ok. why would the script i added in the header (not the jquery) work in the ioslides_presentation but not in the  html_document?

**Comment by yihui** [comment]
@yonicd ioslides is a different animal in this package. We used a custom Pandoc writer to generate this format. All other output formats use Pandoc's built-in writers. That probably explains the difference.

Anyway, I cannot reproduce your issue. Your example could be reduced to 

```
---
title: "Hello"
output: html_document
---

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
```

When I knit it, Pandoc is able to download this version of jQuery and embed it. You didn't provide your `devtools::session_info("rmarkdown")` (you always should), and from my experience, this may happen on Linux with a certain build of Pandoc. Please try to upgrade RStudio, R, and R packages, and retry.

**Comment by yonicd** [comment]
thank you. i used in the end `juba/rmdformats` for the effect i needed.
