### ISSUE TITLE
Does autocomplete for .bib citation work?

### ISSUE THREAD

**Issue by mcevzar** [rstudio/rmarkdown#958]
Example:

Can I write @cite... press "Tab" and RStudio will suggest an autocomplete based on my .bib file?

**Comment by yihui** [comment]
You can take a look at Figure 5.2: https://bookdown.org/yihui/bookdown/rstudio-ide.html

**Comment by gorkang** [comment]
+1 for the feature that @mcevzar proposes. The citr addin is alright, but the autocomplete way (as you would do in www.overleaf.com) is a lot more efficient.

**Comment by yihui** [comment]
@gorkang I agree with you. It requires work on the RStudio IDE side, and I have no idea how hard that would be. Currently your only option is still citr.

**Comment by gorkang** [comment]
Thanks @yihui. There is an couple years old open issue in the RStudio website: [https://support.rstudio.com/hc/en-us/community/posts/202160258-Tab-autocompletion-of-bibtex-references](url) 

Hopefully if more people show support there the RStudio gang would make it happen... :)

**Comment by yihui** [comment]
Closing since this is an RStudio IDE issue and has been filed.
