### ISSUE TITLE
Duplicated References entry in toc and pandoc version

### ISSUE THREAD

**Issue by lgatto** [rstudio/rmarkdown#961]
This [issue](https://github.com/Bioconductor/BiocStyle/issues/22) describes the case when the *Reference* section get duplicated, as illustrated below. 

![2017-02-08-115230_1260x778_scrot](https://cloud.githubusercontent.com/assets/384198/22743059/e5924dbc-ee10-11e6-966f-57d9ca69633f.png)

This turns out to be a `pandoc` issue, that appeared with version `1.12.4.2`. I have not been able to track the exact version bump when this has been solved (because I could only get `deb` packages from `1.15` onwards), but I can report that things work as expected with `pandoc` `1.15` or later.  Here's the expected output with the latest `1.19.2.1`.

![2017-02-08-151736_1200x778_scrot](https://cloud.githubusercontent.com/assets/384198/22743328/c9de9b4c-ee11-11e6-8ad5-94b040cf15c3.png)

May be the `rmarkdown` authors might consider adding a dependency on a minimal `pandoc` version. Hope this helps.

**Comment by yihui** [comment]
Currently we require a lower version of Pandoc but it is probably time to bump it now: https://github.com/rstudio/rmarkdown/blob/f098542c71933a03ab52431629b7dd034c5a4a97/R/render.R#L75

**Comment by jjallaire** [comment]
We could bump it but I don't know of a reason why we're incompatible with
1.12 -- Linux distros tend to be way behind on pandoc so it feels like
keeping it where it is will cause less hassle for users on those distros.

**Comment by lgatto** [comment]
FYI, I am running Ubuntu 14.04 LTS, so not really up-to-date.

**Comment by yihui** [comment]
Given that there is a huge number of packages on CRAN that use rmarkdown to build vignettes, I feel it is risky to increase the Pandoc version number, so I'll mark this issue as `wontfix` and let you upgrade your Pandoc. FWIW, RStudio IDE has bundled Pandoc 1.19.2.1.
