### ISSUE TITLE
No header when `self_contained` set to FALSE in `html_document_base`

### ISSUE THREAD

**Issue by juyeongkim** [rstudio/rmarkdown#963]
When rendering a rmarkdown (`test.Rmd`): 

```
---
output: 
  html_document_base:
    self_contained: FALSE
---

```{r}
x <- 10
y <- 1
x
y
`` `
```

As you can see in the pandoc command, it doesn't have `--include-in-header` option.
 
```
/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to html --output test.html --smart --email-obfuscation none --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' 
```

The output file is:
```html
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">10</span>
y &lt;-<span class="st"> </span><span class="dv">1</span>
x</code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y</code></pre></div>
<pre><code>## [1] 1</code></pre>
```

I expected it to include a header that loads a code highlighting css file from `test_files` folder as it is the case for `html_document` with `self_contained=FALSE`.

**Comment by jjallaire** [comment]
html_document_base isn't intended to be a standalone format but rather a format that other more complete ones inherit from.

**Comment by juyeongkim** [comment]
@jjallaire Does `html_document_base()` use [`rmd/h/default.html`](https://github.com/rstudio/rmarkdown/blob/master/inst/rmd/h/default.html) when `template="default"`?

**Comment by jjallaire** [comment]
No it doesn't use any template (as I said it's intended to be composed by a higher level format that provides it's own template). The template argument passed to `html_document_base()` is only there to condition some of it's behavior rather than as an instruction to use a given template.
