### ISSUE TITLE
beamer with R markdown: split a long output into two slides

### ISSUE THREAD

**Issue by pia1205** [rstudio/rmarkdown#966]
Hi, 

 

I'm generating a presentation slide using R markdown (beamer). 

One of my R chunk generates too long outputs to be in a slide. Is there any way to split it into two slides automatically?

I cannot see a part of the output because it goes beyond the page.

 

Thanks in advance. 

![image](https://cloud.githubusercontent.com/assets/5339836/23084726/2fafcfee-f5a7-11e6-8ac1-4962581b402b.png)

**Comment by Dan-N** [comment]
Hi, did you manage to solve the problem? I am having the same issue.

**Comment by yihui** [comment]
This looks like a (Pandoc) question instead of a bug report or feature request, so please do us a favor to [ask it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with a reproducible example) and let us know the link if you don't get an answer in a few days. Thanks!
