### ISSUE TITLE
render_site site generation ignores .rmd (lowercase "r") files

### ISSUE THREAD

**Issue by lukerobert** [rstudio/rmarkdown#968]
Not sure if this is intended or not but the site generator (render_site) will ignore any Rmarkdown files that start with a lowercase "r" instead of an uppercase "R". I suppose this is consistent with Rmarkdown's documentation but it's not consistent with RStudio or other functions in Rmarkdown, which will merrily take .rmd files.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/rmarkdown/commit/f0cb2f1e8e8743ac114e7e62ae3ff02a105bd530
