### ISSUE TITLE
openBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by romunov** [rstudio/rmarkdown#970]
When I run a chunk which produces a pdf through an external tool

```r
system("poretools hist  \\
          --saveas gs_histogram_gs_fail_reads_pass.pdf \\
          --theme-bw \\
          /mnt/spajza/minion_data/minion_gs_rerun/pass")
```

I get R console error message when I press save:

```
pandoc: Could not fetch gs_yield_plot_pass.pdf
gs_yield_plot_pass.pdf: openBinaryFile: does not exist (No such file or directory)
``` 

The file is there

```
> system("ls -l")
total 223153
-rwxrwxrwx 1 root root       935 feb 14 15:17 analysis.R
drwxrwxrwx 1 root root      4096 feb 15 16:27 cleaned
drwxrwxrwx 1 root root  18194432 feb 20 13:27 fail
-rwxrwxrwx 1 root root  54956704 feb 20 15:53 gs_fail.fasta
-rwxrwxrwx 1 root root      9626 feb 20 15:49 gs_histogram_gs_fail_reads_pass.pdf
-rwxrwxrwx 1 root root      9512 feb 20 15:31 gs_histogram_GS_RERUN_reads_fail.pdf
-rwxrwxrwx 1 root root 143910322 feb 20 15:56 gs_pass.fasta
-rwxrwxrwx 1 root root      1718 feb 21 09:32 minion_gs_rerun_analysis.Rmd
-rwxrwxrwx 1 root root       205 feb 15 12:43 minion_gs_rerun.Rproj
drwxrwxrwx 1 root root  11390976 feb 20 13:21 pass
-rwxrwxrwx 1 root root      6884 feb 15 14:11 primerji.xlsx
-rwxrwxrwx 1 root root      1207 feb 15 14:46 split_by_primer.R
```

Interestingly enough, the same doesn't happen for a chunk earlier:

```r
system("poretools hist  \\
          --saveas gs_histogram_GS_RERUN_reads_fail.pdf \\
          --theme-bw \\
          /mnt/spajza/minion_data/minion_gs_rerun/fail")
```
When I try to preview the notebook, error in title appears and nothing happens.

**Comment by jjallaire** [comment]
@jmcphers Could you take a look at this one?

**Comment by jmcphers** [comment]
Pandoc runs when you save notebooks to update the preview. Most likely the problem is that Pandoc is parsing the output of that command (and shouldn't be). @kevinushey do you have any idea why that might be?

@romunov I couldn't reproduce this, but it's probably because I can't actually run the code (if the above conjecture is true then something in the code's output is responsible). Could you paste the output you see when you run this command in an ordinary terminal?

**Comment by kevinushey** [comment]
I can't think of a reason why Pandoc would be stepping in here, but a reproducible example would be helpful (can you share a minimal Notebook file that showcases this error?)
