### ISSUE TITLE
No inline rendering of data frame in code chunk when using lubridate::ymd

### ISSUE THREAD

**Issue by adfi** [rstudio/rmarkdown#971]
Hi, 

I have tested the following with both R Notebook and R Markdown:

`df<- data.frame(One=c(1,2,3,4), Two=c('20170120','20170202','20170203','20170303'))`
`df$Two <- ymd(df$Two)`
`df`

When running this code in a code chunk, there is no output inline. However when knitting the entire file the output does get rendered correctly. I have tested it with POSIXct and other lubridate functions and they all seem to work fine.

I suspect it's a bug but I can't tell what is causing it.

**Comment by jjallaire** [comment]
@jmcphers and @javierluraschi I was able to repro the same behavior. Could you take a look?

**Comment by jmcphers** [comment]
What version of RStudio were you on? This should have been fixed with this recent commit:

https://github.com/rstudio/rstudio/pull/965/commits/bf16226e14e608d1ce057fc6d61463685727dbd8

I wasn't able to repro on the dailies so hopefully it's the same issue!

**Comment by adfi** [comment]
I'm on version 1.0.136

**Comment by jmcphers** [comment]
This was only fixed a few weeks ago so isn't in a stable release yet. It's in the daily build if you'd like to confirm the fix there:

https://dailies.rstudio.com/

**Comment by adfi** [comment]
Yeah that fixed it, thx!
