### ISSUE TITLE
shiny_prerendered & shinyApp() in Rmd file not working

### ISSUE THREAD

**Issue by S-UP** [rstudio/rmarkdown#973]
Hi,

It currently seems not possible to use ```runtime: shiny_prerendered``` in conjunction with ```shinyApp()``` or ```shinyAppDir()``` in a Rmd file.

My guess is that this is simply due to the runtime check in shiny. Is it save to simply modify the control statement to include shiny_prerendered, or did you deliberately not allow this?

The example below is based on the one mentioned [here](http://rmarkdown.rstudio.com/authoring_shiny_prerendered.html).

**Comment by jjallaire** [comment]
That's correct, those functions are technically incompatible with the way shiny_preredered works.

**Comment by jjallaire** [comment]
Checking with @jcheng5 in case there is some way to make this work that I'm not aware of.

**Comment by jcheng5** [comment]
I guess you could put a uiOutput("foo") in the default context, save the shinyApp object to a variable in context=server-start, and set output$foo <- renderUI(appobj) in context=server.

Oh or better yet, instead of saving the shinyApp itself to a variable, maybe save htmltools::as.tags(appobj) to a variable instead, I'm just guessing but this may prevent memory from leaking.

**Comment by S-UP** [comment]
Thanks guys for the suggestions. I won't have the time to play around with it right now.

Related to this, would the reverse maybe make more sense, e.g. using a standard Shiny dashboard to generate something like a report structure?

The main reason why I went with Rmd is to have a nice table of content (i.e. floating TOC). If I could easily implement this in the Shiny dashboard, this might be the more appropriate approach.

**Comment by jcheng5** [comment]
Why do you need embedded shinyApp objects in your dashboard? Could these be shiny modules instead?

**Comment by yihui** [comment]
@S-UP Any follow-up on this issue?
