### ISSUE TITLE
Diagrammer HTML widget grViz sets .Random.seed to NULL

### ISSUE THREAD

**Issue by tomroh** [rstudio/rmarkdown#980]
Warning message:
'.Random.seed' is not an integer vector but of type 'NULL', so ignored

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

You can run the following reproducible example:

```{r simpleModel, echo = FALSE}
library(DiagrammeR)
simpleModel <- 'digraph simpleQueue {
  graph[label = "Simple"]
  
  a
  b
  c
  a -> b ;
  b -> c ;
  {rank = same; a, b, c}
  }'
grViz(simpleModel, height = 200)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
set.seed(562)
x <- rweibull(100, shape = .7, scale = 10)
```

**Comment by jjallaire** [comment]
What version of htmlwidgets do you have installed? I believe that this bug was addressed in v0.8 of htmlwidgets which is on CRAN now. See https://github.com/ramnathv/htmlwidgets/pull/235

**Comment by datareaver** [comment]
I'm using version v0.8 and I still get that error

**Comment by jjallaire** [comment]
@kevinushey Can you think of any reason why this error would still be occurring after your fix?

**Comment by kevinushey** [comment]
Looks like we're bumping into the same issue here: https://github.com/ramnathv/htmlwidgets/blob/3ce9f90bac70a6c9b15a546b4729ec5992035b65/R/widgetid.R#L23-L42

```R
> htmlwidgets:::createWidgetId()
[1] "d846dc66c4d9c9cd4a62"
> .Random.seed
NULL
```

**Comment by jjallaire** [comment]
Okay, @jcheng5 we originally copied this code from Shiny at your recommendation for unique ID generation without interfering with .Random.seed. @kevinushey or @jcheng5 do you have some idea what we can do differently / better here to avoid this issue?

**Comment by yihui** [comment]
Should be fixed by @kbroman via https://github.com/ramnathv/htmlwidgets/pull/265. Please test the development version of htmlwidgets:

```r
devtools::install_github('ramnathv/htmlwidgets')
```

**Comment by tomroh** [comment]
I tested the development version and I am not longer getting a warning about the random seed.
