### ISSUE TITLE
Cannot render image with beamer_presentation output

### ISSUE THREAD

**Issue by LarsSoto** [rstudio/rmarkdown#986]
Hi, 

I'm getting the error below when trying to include an image in rmarkdown with "beamer_presentation" output. Using "ioslides_presentation" as output is fine.

```
![comment](/Users/pictures/pic.jpg)
```
pdfTeX error: /Library/TeX/texbin/pdflatex (file /Users/pictures/pic.jpg): reading JPEG image failed (no JPEG header found)
 ==> Fatal error occurred, no output PDF file produced!
pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
Execution halted

Any hints would be much appreciated!
Lars.

**Comment by yihui** [comment]
Using absolute paths is bad practice in general (not portable, and often problematic for LaTeX). Is there a chance that you could use relative paths instead?
