### ISSUE TITLE
render() failing on windows when output_format="pdf_document" and output_dir path has underscore

### ISSUE THREAD

**Issue by eeholmes** [rstudio/rmarkdown#992]
When render() called with output_format="pdf_document" and output_dir is a path with a directory starting with _ (underscore), the pdf cannot be made if the Rmd file is making figures.  render() changes the figure path to use `\\` and if the path has `\\_` in it, this becomes `\_` in the intermediary md file.  Latex cannot process a path with `\_` in it.

Proposed solution: Change line 194 of render() to
knitr::opts_chunk$set(fig.path = normalize_path(figures_dir))
i.e. wrap figures_dir in normalize_path()

Reproducible code of the error:

Run on a Windows machine

The tester1.Rmd file

<pre>
---
title: "Test"
output:
  html_document: default
  pdf_document: default
---

```{r plots}
plot(pressure)
```
</pre>

Two testing directories each with the above file in it.
C:/test
C:/_test

this code works on the directory with no leading underscore
```
setwd("C:/test")
rmarkdown:::render("tester1.Rmd", output_format="pdf_document", output_dir="C:/test", clean=FALSE)
```

this does not work  on the directory with a leading underscore
```
setwd("C:/_test")
rmarkdown:::render("tester1.Rmd", output_format="pdf_document", output_dir="C:/_test", clean=FALSE)
```

Error is Could not find image `C:_test\tester1_files/figure-latex/plots-1.pdf`

Here is the md file that is created in C:/_test for the above (tester1.knit.md)

<pre>
---
title: "Test"
output:
  html_document: default
  pdf_document: default
---

```r
plot(pressure)
```
![](C:\_test\tester1_files/figure-latex/plots-1.pdf) 

</pre>

Notice that render() changed the directory path to use a single `\` rather than a `/` as specified in the output_dir argument to render().  Latex cannot interpret a path with`\_` in it.  So the intermediary md file cannot be processed.

The path change occurs on line 139 of render() where `pandoc_path_arg(files_dir)` is called.  This is where the directory path for the intermediary files changes from `C:/_test/tester1_files` to `C:\\_test\\tester1_files`

Line 139  `files_dir <- pandoc_path_arg(files_dir)`

Later on line 194

`knitr::opts_chunk$set(fig.path = figures_dir)`

Running  knitr::opts_chunk$get()$fig.path  we see the problem:

```
knitr::opts_chunk$get()$fig.path
"C:\\_test\\tester1_files/figure-latex/"
```

Presumably knit() is somewhere processing `C:\\_test\\tester1_files` to `C:\_test\tester1_files` (which is how latex would convert the first to "text") and that is what is used for the figure path used in the intermediary md file.

Possible solution:

If line 194 were
`knitr::opts_chunk$set(fig.path = normalize_path(figures_dir))`

It would work as the path would only have forward slashes.

Note, Issue #235 indicates that "there are many instances where pandoc barfs when not presented with a path containing backslashes on Windows" .  However, it does not seem that normalizing fig.path to unix style is a problem here.  In fact the path that is currently specified by the call to opt_chunk$set(fig.path) on 194 is a mixture of `\\` and `/`.

**Comment by yihui** [comment]
Usually I don't recommend using `output_dir` or `output_file`. They are known to be buggy. You may see https://github.com/rstudio/rmarkdown/issues/861#issuecomment-326637323 for more info.
