### ISSUE TITLE
Numerical Citation Identifier

### ISSUE THREAD

**Issue by sammerk** [rstudio/rmarkdown#996]
Hey,
as pandoc allows to use of EndNote bibliography files (.enl) it would be great if one can use numerical identifiers for the citation syntax `[@12345]` as this is the default in Endnote.

Thank's
Samuel

**Comment by yihui** [comment]
What did you try and what problem did you run into? Could you provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by tingjhenjiang** [comment]
Hello here. Endnote library provides numerical identifiers, e.g. {Collins, 2013 #12944}, and when I want to cite the reference with [@12944], [@ref12944], [@12944] or [@Collins_2013] in my Rmarkdown doc, none of them work.
