### ISSUE TITLE
UTF-8 encoding moved (and thus inactivated) by Knit button

### ISSUE THREAD

**Issue by ugroempi** [rstudio/rmarkdown#998]
Dear rmarkdown team, 
thanks for the great work!

Not sure whether this is the right place for reporting this or whether it is about RStudio itself: 
the Knit button works fine with umlauts, as long as the default (top) output is used. Otherwise, the "Knit html" or "Knit pdf" or ... button does not only move the desired output mode to the top and knit the document, but also moves the "encoding: UTF-8" below the "output: ..." YAML and thus messes up the encoding in YAML fields like author. The attached file demonstrates this. 

Best regards,
Ulrike
[encoding_demo.zip](https://github.com/rstudio/rmarkdown/files/844311/encoding_demo.zip)

**Comment by dpprdan** [comment]
I have the same issue. On Windows, once you switch the output format, all umlauts in the YAML header are also converted, e.g. `ü` to `Ã¼`, `ö` to `Ã¶`, `ä` to `Ã¤`. This happens with every switch of the output format. The following is the markdown output of Ulrike's demo when I switch output from `html_document` (where the umlauts were formatted/encoded correctly in the first place) to `github_document`. 

Demo encoding behavior of umlauts (Ã¤,Ã¶,Ã¼,ÃŸ)
================
Ulrike GrÃ¶mping
14 MÃ¤rz 2017

Some blabla
-----------

My name is Grömping (and remains Grömping here). The umlauts in this text are (luckily) not affected by the move of the "encoding: UTF-8" piece below "output", but the texts entered in YAML fields are affected: Pressing the "Knit" button works, but choosing e.g. "Knit pdf", when html is currently active moves the "encoding: UTF-8" below "output: ..." and thus messes up the umnlauts in YAML fields.

**Comment by jmcphers** [comment]
This is indeed a known issue in the RStudio IDE (we hope to have a fix soon).

**Comment by yihui** [comment]
Closing since it is an RStudio IDE issue and not relevant to rmarkdown.
